"""Add Cambridge IELTS 13 Test 1 Reading Passage 2-3 to the local article library.

This is a curated seed file: the source text was extracted from the user's local
Cambridge IELTS 13 PDF/DOCX, then normalized into the app's passage JSON schema.
Run from project root:
    python tools/add_c13_test1_articles.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PASSAGES = ROOT / "data" / "passages"
INDEX = ROOT / "data" / "index.json"


def words(*items):
    return [{"w": w, "pos": p, "def": d} for w, p, d in items]


P2_SENTENCES = [
    (1, 1, "A", "We all know how it feels - it's impossible to keep your mind on anything, time stretches out, and all the things you could do seem equally unlikely to make you feel better.",
     "我们都知道那种感觉：脑子无法专注于任何事，时间被拉长，而所有可做的事情似乎都同样不可能让你感觉好些。",
     "并列句 + it 形式主语", "破折号后展开解释 how it feels；it's impossible to do 中 it 是形式主语；and 连接三个并列现象。",
     words(("stretch out", "phr.", "拉长；延展"), ("unlikely", "adj.", "不大可能的"))),
    (2, 1, "A", "But defining boredom so that it can be studied in the lab has proved difficult.",
     "但是，要给无聊下定义，以便能在实验室中研究它，已经证明很困难。",
     "动名词主语 + 目的状语", "defining boredom 是主语；so that 引导目的状语从句；has proved difficult 表示结果状态。",
     words(("define", "v.", "下定义"), ("boredom", "n.", "无聊"))),
    (3, 1, "A", "For a start, it can include a lot of other mental states, such as frustration, apathy, depression and indifference.",
     "首先，它可能包含许多其他心理状态，如挫败、冷漠、抑郁和漠然。",
     "列举结构", "such as 后列举 mental states 的具体类型。",
     words(("frustration", "n.", "挫败感"), ("apathy", "n.", "冷漠"), ("indifference", "n.", "漠然"))),
    (4, 1, "A", "There isn't even agreement over whether boredom is always a low-energy, flat kind of emotion or whether feeling agitated and restless counts as boredom, too.",
     "人们甚至没有达成一致：无聊是否总是一种低能量、平淡的情绪，或者焦躁不安是否也算无聊。",
     "whether 并列宾语", "over 后接两个 whether 从句，说明争议内容；feeling agitated and restless 是动名词短语作从句主语。",
     words(("agitated", "adj.", "焦躁的"), ("restless", "adj.", "坐立不安的"))),
    (5, 1, "A", "In his book, Boredom: A Lively History, Peter Toohey at the University of Calgary, Canada, compares it to disgust - an emotion that motivates us to stay away from certain situations.",
     "在《无聊：一部生动的历史》中，加拿大卡尔加里大学的 Peter Toohey 把无聊比作厌恶——一种促使我们远离某些情境的情绪。",
     "compare A to B + 同位解释", "compares it to disgust 为主干；破折号后的 an emotion 解释 disgust；that 引导定语从句。",
     words(("disgust", "n.", "厌恶"), ("motivate", "v.", "促使"))),
    (6, 1, "A", "If disgust protects humans from infection, boredom may protect them from infectious social situations, he suggests.",
     "他认为，如果厌恶保护人类免受感染，那么无聊也许能保护人类远离“有感染性”的社交情境。",
     "if 条件句 + 类比", "If 从句提出类比前提；may protect 表推测；he suggests 是插入性报告语。",
     words(("infection", "n.", "感染"), ("infectious", "adj.", "有感染性的"))),
    (7, 2, "B", "By asking people about their experiences of boredom, Thomas Goetz and his team at the University of Konstanz in Germany have recently identified five distinct types: indifferent, calibrating, searching, reactant and apathetic.",
     "通过询问人们的无聊经历，德国康斯坦茨大学的 Thomas Goetz 及其团队最近识别出五种不同类型：漠然型、校准型、搜索型、反应型和冷漠型。",
     "By doing + 现在完成时", "By asking... 表方法；have identified 表近期研究成果；冒号后列举五类。",
     words(("identify", "v.", "识别"), ("distinct", "adj.", "不同的"), ("apathetic", "adj.", "冷漠的"))),
    (8, 2, "B", "These can be plotted on two axes - one running left to right, which measures low to high arousal, and the other from top to bottom, which measures how positive or negative the feeling is.",
     "这些类型可以画在两条轴上：一条从左到右，衡量从低到高的唤醒程度；另一条从上到下，衡量这种感受有多积极或消极。",
     "被动语态 + 分词补充", "can be plotted 为被动；one...and the other... 解释 two axes；which 引导非限制性定语从句。",
     words(("axis", "n.", "轴"), ("arousal", "n.", "唤醒程度；兴奋度"))),
    (9, 2, "B", "Intriguingly, Goetz has found that while people experience all kinds of boredom, they tend to specialise in one.",
     "有趣的是，Goetz 发现，尽管人们会经历各种无聊，他们往往会特别偏向其中一种。",
     "that 宾语从句 + while 让步", "has found 后接宾语从句；while 表让步；tend to 表倾向。",
     words(("intriguingly", "adv.", "有趣的是"), ("specialise in", "phr.", "专门从事；偏向"))),
    (10, 2, "B", "Of the five types, the most damaging is reactant boredom with its explosive combination of high arousal and negative emotion.",
     "在五种类型中，最有害的是反应型无聊，它结合了高唤醒和负面情绪，具有爆发性。",
     "最高级 + with 短语", "the most damaging 为表语；with its... 补充说明 reactant boredom 的特征。",
     words(("damaging", "adj.", "有害的"), ("explosive", "adj.", "爆发性的"))),
    (11, 2, "B", "The most useful is what Goetz calls indifferent boredom: someone isn't engaged in anything satisfying but still feels relaxed and calm.",
     "最有用的是 Goetz 所说的漠然型无聊：一个人没有投入任何令人满意的事情，但仍然感到放松和平静。",
     "what 名词性从句 + 冒号解释", "what Goetz calls... 作表语；冒号后具体解释该类型。",
     words(("engaged", "adj.", "投入的"), ("satisfying", "adj.", "令人满意的"))),
    (12, 2, "B", "However, it remains to be seen whether there are any character traits that predict the kind of boredom each of us might be prone to.",
     "然而，是否存在某些性格特征能预测每个人容易产生哪类无聊，还有待观察。",
     "it remains to be seen + whether", "it 是形式主语；whether 从句是真正内容；that predict... 修饰 traits。",
     words(("trait", "n.", "特征"), ("be prone to", "phr.", "易于；倾向于"))),
    (13, 3, "C", "Psychologist Sandi Mann at the University of Central Lancashire, UK, goes further.",
     "英国中央兰开夏大学的心理学家 Sandi Mann 则更进一步。",
     "简单句", "goes further 表示在前人观点基础上提出更进一步的看法。",
     words(("psychologist", "n.", "心理学家"))),
    (14, 3, "C", "All emotions are there for a reason, including boredom, she says.",
     "她说，所有情绪的存在都有原因，包括无聊。",
     "直接引语 + including", "including boredom 补充说明 all emotions 的范围；she says 是报告语。",
     words(("emotion", "n.", "情绪"))),
    (15, 3, "C", "Mann has found that being bored makes us more creative.",
     "Mann 发现，无聊会让我们更有创造力。",
     "宾语从句 + make 复合结构", "that 引导 found 的宾语从句；being bored 作从句主语；makes us more creative 为 make + 宾语 + 宾补。",
     words(("creative", "adj.", "有创造力的"))),
    (16, 3, "C", "We're all afraid of being bored but in actual fact it can lead to all kinds of amazing things, she says.",
     "她说，我们都害怕无聊，但事实上它能带来各种令人惊奇的事情。",
     "转折并列句", "but 连接转折；lead to 表示“导致、带来”。",
     words(("in actual fact", "phr.", "事实上"), ("lead to", "phr.", "导致"))),
    (17, 3, "C", "In experiments published last year, Mann found that people who had been made to feel bored by copying numbers out of the phone book for 15 minutes came up with more creative ideas about how to use a polystyrene cup than a control group.",
     "在去年发表的实验中，Mann 发现，那些被要求抄电话簿号码 15 分钟而感到无聊的人，比对照组想出了更多关于如何使用聚苯乙烯杯的创意。",
     "复杂宾语从句 + 比较", "found 后是 that 从句；who 引导定语从句修饰 people；more...than 构成比较。",
     words(("control group", "n.", "对照组"), ("polystyrene", "n.", "聚苯乙烯"))),
    (18, 3, "C", "Mann concluded that a passive, boring activity is best for creativity because it allows the mind to wander.",
     "Mann 得出结论：被动而无聊的活动最有利于创造力，因为它允许思维游走。",
     "宾语从句 + because 原因", "concluded 后接 that 从句；because 解释为什么有利于创造力。",
     words(("passive", "adj.", "被动的"), ("wander", "v.", "游走；漫游"))),
    (19, 3, "C", "In fact, she goes so far as to suggest that we should seek out more boredom in our lives.",
     "事实上，她甚至建议我们应该在生活中主动寻找更多无聊。",
     "so far as to + that 从句", "goes so far as to suggest 表“甚至建议”；that 引导建议内容。",
     words(("seek out", "phr.", "寻找"), ("go so far as to", "phr.", "甚至做到"))),
    (20, 4, "D", "Psychologist John Eastwood at York University in Toronto, Canada, isn't convinced.",
     "加拿大多伦多约克大学的心理学家 John Eastwood 并不信服。",
     "被动形容词结构", "isn't convinced 表示“不相信、不认同”。",
     words(("convinced", "adj.", "确信的"))),
    (21, 4, "D", "If you are in a state of mind-wandering you are not bored, he says.",
     "他说，如果你处于思维游走状态，那你就不是无聊。",
     "if 条件句", "If 从句提出条件；主句给出判断。",
     words(("mind-wandering", "n.", "思维游走"))),
    (22, 4, "D", "In my view, by definition boredom is an undesirable state.",
     "在我看来，按定义来说，无聊是一种不受欢迎的状态。",
     "插入状语 + 主系表", "In my view 与 by definition 均为评注状语；主干为 boredom is a state。",
     words(("by definition", "phr.", "按定义"), ("undesirable", "adj.", "不受欢迎的"))),
    (23, 4, "D", "That doesn't necessarily mean that it isn't adaptive, he adds.",
     "他补充说，这并不一定意味着它没有适应性。",
     "双重否定 + 宾语从句", "doesn't necessarily mean 表“不一定意味着”；that 引导宾语从句。",
     words(("adaptive", "adj.", "有适应性的"))),
    (24, 4, "D", "Pain is adaptive - if we didn't have physical pain, bad things would happen to us.",
     "疼痛是有适应性的——如果没有身体疼痛，坏事就会发生在我们身上。",
     "虚拟条件句", "if we didn't have... 是与现实相反的虚拟条件；would happen 为主句。",
     words(("physical", "adj.", "身体的"))),
    (25, 4, "D", "But even if boredom has evolved to help us survive, it can still be toxic if allowed to fester.",
     "但即使无聊进化出来是为了帮助我们生存，如果任其恶化，它仍然可能有害。",
     "even if 让步 + if 省略", "even if 引导让步；if allowed to fester 省略 it is。",
     words(("toxic", "adj.", "有害的"), ("fester", "v.", "恶化"))),
    (26, 4, "D", "For Eastwood, the central feature of boredom is a failure to put our attention system into gear.",
     "对 Eastwood 来说，无聊的核心特征是未能启动我们的注意系统。",
     "主系表 + 不定式修饰", "feature is a failure 为主干；to put... 修饰 failure。",
     words(("attention system", "n.", "注意系统"), ("put into gear", "phr.", "启动"))),
    (27, 4, "D", "This causes an inability to focus on anything, which makes time seem to go painfully slowly.",
     "这会导致无法专注于任何事情，从而让时间显得慢得令人痛苦。",
     "因果 + 非限制性定语从句", "This causes... 表结果；which 指代前句结果并继续说明影响。",
     words(("inability", "n.", "无能力"), ("focus", "v.", "专注"))),
    (28, 4, "D", "What's more, your efforts to improve the situation can end up making you feel worse.",
     "更重要的是，你试图改善局面的努力最终可能让你感觉更糟。",
     "end up doing", "efforts 是主语；to improve... 修饰 efforts；end up making... 表最终结果。",
     words(("end up", "phr.", "最终"), ("effort", "n.", "努力"))),
    (29, 4, "D", "People try to connect with the world and if they are not successful there's that frustration and irritability, he says.",
     "他说，人们试图与世界建立联系，如果不成功，就会产生那种挫败和烦躁。",
     "并列 + 条件句", "try to connect 与 if 从句构成因果说明；there's 表出现某种状态。",
     words(("irritability", "n.", "烦躁"), ("connect with", "phr.", "与……联系"))),
    (30, 4, "D", "Perhaps most worryingly, says Eastwood, repeatedly failing to engage attention can lead to a state where we don't know what to do any more, and no longer care.",
     "Eastwood 说，也许最令人担忧的是，反复无法集中注意力会导致一种状态：我们不再知道该做什么，也不再在乎。",
     "动名词主语 + where 定语从句", "repeatedly failing... 作主语；where 引导定语从句修饰 state。",
     words(("engage attention", "phr.", "集中注意力"), ("worryingly", "adv.", "令人担忧地"))),
    (31, 5, "E", "Eastwood's team is now trying to explore why the attention system fails.",
     "Eastwood 的团队现在正试图探究注意系统为什么会失灵。",
     "why 宾语从句", "explore 后接 why 从句，说明研究问题。",
     words(("explore", "v.", "探究"), ("fail", "v.", "失灵"))),
    (32, 5, "E", "It's early days but they think that at least some of it comes down to personality.",
     "现在还为时尚早，但他们认为其中至少一部分归因于性格。",
     "转折并列 + that 从句", "It's early days 表研究尚早；comes down to 表归结为。",
     words(("come down to", "phr.", "归结为"), ("personality", "n.", "性格"))),
    (33, 5, "E", "Boredom proneness has been linked with a variety of traits.",
     "容易无聊已经被发现与多种特征有关。",
     "现在完成时被动", "has been linked with 表研究发现的关联。",
     words(("proneness", "n.", "倾向"), ("a variety of", "phr.", "多种"))),
    (34, 5, "E", "People who are motivated by pleasure seem to suffer particularly badly.",
     "以追求愉悦为动力的人似乎尤其容易受其困扰。",
     "定语从句 + seem to", "who are motivated by pleasure 修饰 People；seem to 表推测判断。",
     words(("pleasure", "n.", "愉悦"), ("suffer", "v.", "受苦"))),
    (35, 5, "E", "Other personality traits, such as curiosity, are associated with a high boredom threshold.",
     "其他性格特征，如好奇心，则与较高的无聊阈值有关。",
     "插入列举 + 被动关联", "such as curiosity 为例子；are associated with 表“与……相关”。",
     words(("curiosity", "n.", "好奇心"), ("threshold", "n.", "阈值"))),
    (36, 5, "E", "More evidence that boredom has detrimental effects comes from studies of people who are more or less prone to boredom.",
     "更多关于无聊具有有害影响的证据，来自对不同程度容易无聊的人群的研究。",
     "同位语从句 + 定语从句", "that boredom has... 解释 evidence；who are... 修饰 people。",
     words(("detrimental", "adj.", "有害的"), ("more or less", "phr.", "或多或少"))),
    (37, 5, "E", "It seems those who bore easily face poorer prospects in education, their career and even life in general.",
     "那些容易感到无聊的人，在教育、职业甚至整体生活方面似乎前景更差。",
     "It seems + 省略 that", "those who bore easily 是从句主语；face poorer prospects 为谓语宾语。",
     words(("prospect", "n.", "前景"), ("in general", "phr.", "总体上"))),
    (38, 5, "E", "But of course, boredom itself cannot kill - it's the things we do to deal with it that may put us in danger.",
     "当然，无聊本身不会致命；可能让我们陷入危险的是我们为了应对它而做的事情。",
     "强调句", "it's...that... 为强调结构；to deal with it 修饰 things。",
     words(("deal with", "phr.", "处理；应对"), ("put in danger", "phr.", "使处于危险中"))),
    (39, 5, "E", "What can we do to alleviate it before it comes to that?",
     "在事情发展到那一步之前，我们能做些什么来缓解它呢？",
     "特殊疑问句 + 不定式目的", "What can we do 为主干；to alleviate it 表目的。",
     words(("alleviate", "v.", "缓解"))),
    (40, 5, "E", "Goetz's group has one suggestion.",
     "Goetz 的团队有一个建议。",
     "简单句", "has one suggestion 过渡到下文解决方案。",
     words(("suggestion", "n.", "建议"))),
    (41, 5, "E", "Working with teenagers, they found that those who approach a boring situation report less boredom than those who try to avoid it by using snacks, TV or social media for distraction.",
     "他们在与青少年合作研究时发现，那些“接近”无聊情境的人，比那些通过零食、电视或社交媒体转移注意力来逃避的人报告的无聊更少。",
     "分词状语 + 比较结构", "Working with... 为背景；that 从句为 found 的宾语；less...than 比较两类人。",
     words(("approach", "v.", "接近；面对"), ("distraction", "n.", "分心物"))),
    (42, 6, "F", "Psychologist Francoise Wemelsfelder speculates that our over-connected lifestyles might even be a new source of boredom.",
     "心理学家 Francoise Wemelsfelder 推测，我们过度连接的生活方式甚至可能成为无聊的新来源。",
     "that 宾语从句", "speculates 后接 that 从句；might 表推测。",
     words(("speculate", "v.", "推测"), ("over-connected", "adj.", "过度连接的"))),
    (43, 6, "F", "In modern human society there is a lot of overstimulation but still a lot of problems finding meaning, she says.",
     "她说，在现代人类社会中，有大量过度刺激，但人们仍然很难找到意义。",
     "there be + 转折", "there is...but still... 对比刺激很多与意义不足。",
     words(("overstimulation", "n.", "过度刺激"), ("meaning", "n.", "意义"))),
    (44, 6, "F", "So instead of seeking yet more mental stimulation, perhaps we should leave our phones alone, and use boredom to motivate us to engage with the world in a more meaningful way.",
     "因此，也许我们不该继续寻求更多精神刺激，而应该放下手机，利用无聊来促使自己以更有意义的方式参与世界。",
     "instead of + 并列谓语", "instead of seeking... 表取代方案；leave 与 use 为并列谓语；to motivate... 表目的。",
     words(("mental stimulation", "n.", "精神刺激"), ("engage with", "phr.", "参与；接触"))),
]


P3_SENTENCES = [
    (1, 1, "The Painting Fool is one of a growing number of computer programs which, so their makers claim, possess creative talents.",
     "“绘画傻瓜”是越来越多电脑程序中的一个；其制作者声称，这些程序拥有创造才能。",
     "one of + 定语从句", "which 引导定语从句修饰 programs；so their makers claim 为插入语。",
     words(("possess", "v.", "拥有"), ("creative talent", "n.", "创造才能"))),
    (2, 1, "Classical music by an artificial composer has had audiences enraptured, and even tricked them into believing a human was behind the score.",
     "由人工作曲家创作的古典音乐曾让观众陶醉，甚至骗过他们，让他们相信乐谱背后是人类。",
     "并列谓语 + trick into doing", "has had 与 tricked 并列；trick somebody into doing 表“诱使某人相信/做”。",
     words(("artificial", "adj.", "人工的"), ("enraptured", "adj.", "着迷的"), ("score", "n.", "乐谱"))),
    (3, 1, "Artworks painted by a robot have sold for thousands of dollars and been hung in prestigious galleries.",
     "机器人绘制的艺术品已经卖到数千美元，并被挂在知名画廊中。",
     "现在完成时被动", "painted by a robot 修饰 Artworks；have sold 与 been hung 并列。",
     words(("prestigious", "adj.", "有声望的"), ("gallery", "n.", "画廊"))),
    (4, 1, "And software has been built which creates art that could not have been imagined by the programmer.",
     "还有人开发出软件，能够创造连程序员本人都无法想象的艺术。",
     "被动语态 + 双层定语从句", "which 修饰 software；that could not... 修饰 art。",
     words(("imagine", "v.", "想象"))),
    (5, 2, "Human beings are the only species to perform sophisticated creative acts regularly.",
     "人类是唯一经常进行复杂创造行为的物种。",
     "主系表 + 不定式定语", "to perform... 修饰 species。",
     words(("species", "n.", "物种"), ("sophisticated", "adj.", "复杂精密的"))),
    (6, 2, "If we can break this process down into computer code, where does that leave human creativity?",
     "如果我们能把这一过程拆解成计算机代码，那人类创造力将置于何地？",
     "条件句 + 反问", "If 从句提出假设；where does that leave... 表示对意义/地位的追问。",
     words(("break down", "phr.", "分解"), ("creativity", "n.", "创造力"))),
    (7, 2, "This is a question at the very core of humanity, says Geraint Wiggins, a computational creativity researcher at Goldsmiths, University of London.",
     "伦敦大学金史密斯学院计算创造力研究者 Geraint Wiggins 说，这是一个触及人性核心的问题。",
     "主系表 + 同位语", "a computational creativity researcher... 是 Geraint Wiggins 的同位语。",
     words(("humanity", "n.", "人性；人类"), ("computational", "adj.", "计算的"))),
    (8, 2, "It scares a lot of people.",
     "它让很多人感到害怕。",
     "简单句", "It 指代前文机器创造力问题。",
     words(("scare", "v.", "使害怕"))),
    (9, 2, "They are worried that it is taking something special away from what it means to be human.",
     "他们担心，它正在从“成为人类”这件事中夺走某种特殊的东西。",
     "that 宾语从句 + what 从句", "worried 后接 that 从句；what it means to be human 作 from 的宾语。",
     words(("take away from", "phr.", "从……夺走"), ("mean", "v.", "意味着"))),
    (10, 3, "To some extent, we are all familiar with computerised art.",
     "在某种程度上，我们都熟悉计算机化艺术。",
     "介词短语状语", "To some extent 限定程度；be familiar with 表熟悉。",
     words(("to some extent", "phr.", "在某种程度上"), ("computerised", "adj.", "计算机化的"))),
    (11, 3, "The question is: where does the work of the artist stop and the creativity of the computer begin?",
     "问题是：艺术家的工作在哪里停止，计算机的创造力又从哪里开始？",
     "表语从句式提问", "冒号后用直接疑问句解释 The question。",
     words(("artist", "n.", "艺术家"))),
    (12, 3, "Consider one of the oldest machine artists, Aaron, a robot that has had paintings exhibited in London's Tate Modern and the San Francisco Museum of Modern Art.",
     "以最早的机器艺术家之一 Aaron 为例，它是一个机器人，其画作曾在伦敦泰特现代美术馆和旧金山现代艺术博物馆展出。",
     "祈使句 + 同位语 + 定语从句", "Aaron 是 one of... 的同位语；that 引导定语从句修饰 robot。",
     words(("exhibit", "v.", "展出"), ("machine artist", "n.", "机器艺术家"))),
    (13, 3, "Aaron can pick up a paintbrush and paint on canvas on its own.",
     "Aaron 能自己拿起画笔在画布上作画。",
     "并列动词", "pick up 与 paint 并列；on its own 表独立完成。",
     words(("paintbrush", "n.", "画笔"), ("canvas", "n.", "画布"))),
    (14, 3, "Impressive perhaps, but it is still little more than a tool to realise the programmer's own creative ideas.",
     "这或许令人印象深刻，但它仍不过是实现程序员自身创意的工具。",
     "省略句 + 转折", "Impressive perhaps 省略 it is；little more than 表“不过是”。",
     words(("little more than", "phr.", "不过是"), ("realise", "v.", "实现"))),
    (15, 4, "Simon Colton, the designer of the Painting Fool, is keen to make sure his creation doesn't attract the same criticism.",
     "“绘画傻瓜”的设计者 Simon Colton 很想确保他的作品不会招致同样的批评。",
     "同位语 + 不定式", "the designer... 是同位语；to make sure... 表目的/倾向。",
     words(("be keen to", "phr.", "热衷于；很想"), ("criticism", "n.", "批评"))),
    (16, 4, "Unlike earlier artists such as Aaron, the Painting Fool only needs minimal direction and can come up with its own concepts by going online for material.",
     "与 Aaron 等早期“艺术家”不同，“绘画傻瓜”只需要极少指导，并能通过上网搜集素材提出自己的概念。",
     "Unlike 对比 + 并列谓语", "Unlike 引出对比对象；needs 与 can come up with 并列。",
     words(("minimal", "adj.", "极少的"), ("come up with", "phr.", "提出"))),
    (17, 4, "The software runs its own web searches and trawls through social media sites.",
     "该软件会自行进行网页搜索，并在社交媒体网站中搜罗信息。",
     "并列谓语", "runs 与 trawls through 并列。",
     words(("trawl through", "phr.", "搜罗；翻查"), ("social media", "n.", "社交媒体"))),
    (18, 4, "It is now beginning to display a kind of imagination too, creating pictures from scratch.",
     "它现在也开始展现某种想象力，从零开始创作图像。",
     "现在进行时 + 分词补充", "is beginning to display 表正在发展；creating... 作补充说明。",
     words(("from scratch", "phr.", "从零开始"), ("imagination", "n.", "想象力"))),
    (19, 5, "One of its original works is a series of fuzzy landscapes, depicting trees and sky.",
     "它的一件原创作品是一系列模糊的风景画，描绘树木和天空。",
     "主系表 + 分词定语", "depicting... 修饰 landscapes。",
     words(("fuzzy", "adj.", "模糊的"), ("landscape", "n.", "风景画"), ("depict", "v.", "描绘"))),
    (20, 5, "While some might say they have a mechanical look, Colton argues that such reactions arise from people's double standards towards software-produced and human-produced art.",
     "尽管有些人可能说它们看起来机械，Colton 认为这种反应源于人们对软件创作和人类创作艺术的双重标准。",
     "while 让步 + that 宾语从句", "While 引导让步；argues 后接 that 从句；arise from 表来源。",
     words(("mechanical", "adj.", "机械的"), ("double standard", "n.", "双重标准"))),
    (21, 5, "After all, he says, consider that the Painting Fool painted the landscapes without referring to a photo.",
     "毕竟，他说，要考虑到“绘画傻瓜”在没有参考照片的情况下画出了这些风景。",
     "祈使句 + that 从句", "consider 后接 that 从句；without doing 表“没有……”。",
     words(("refer to", "phr.", "参考；提到"))),
    (22, 5, "If a child painted a new scene from its head, you'd say it has a certain level of imagination, he points out.",
     "他指出，如果一个孩子凭脑海想象画出新场景，你会说他有一定程度的想象力。",
     "if 条件句 + 宾语从句", "If 从句设例；you'd say 后接从句。",
     words(("from one's head", "phr.", "凭脑海想象"), ("certain", "adj.", "某种程度的"))),
    (23, 5, "The same should be true of a machine.",
     "同样的判断也应该适用于机器。",
     "情态动词 + be true of", "should 表应然；be true of 表“适用于”。",
     words(("be true of", "phr.", "适用于"))),
    (24, 6, "Software bugs can also lead to unexpected results.",
     "软件错误也可能导致意想不到的结果。",
     "情态动词 + lead to", "can lead to 表可能导致。",
     words(("bug", "n.", "程序错误"), ("unexpected", "adj.", "意想不到的"))),
    (25, 6, "Some of the Painting Fool's paintings of a chair came out in black and white, thanks to a technical glitch.",
     "由于一个技术故障，“绘画傻瓜”的一些椅子画作呈现为黑白效果。",
     "thanks to 原因状语", "came out 表结果呈现；thanks to 引出原因。",
     words(("technical glitch", "n.", "技术故障"), ("black and white", "adj.", "黑白的"))),
    (26, 6, "This gives the work an eerie, ghostlike quality.",
     "这赋予作品一种怪异、幽灵般的质感。",
     "give + 双宾语", "gives the work a quality 为 give + 间接宾语 + 直接宾语。",
     words(("eerie", "adj.", "怪异的"), ("ghostlike", "adj.", "幽灵般的"))),
    (27, 6, "Human artists like the renowned Ellsworth Kelly are lauded for limiting their colour palette - so why should computers be any different?",
     "像著名的 Ellsworth Kelly 这样的人类艺术家会因限制调色板而受到赞扬，那么为什么计算机就该不同呢？",
     "被动语态 + 反问", "are lauded for 表因……受赞扬；why should... 反问双重标准。",
     words(("renowned", "adj.", "著名的"), ("laud", "v.", "赞扬"), ("palette", "n.", "调色板"))),
    (28, 7, "Researchers like Colton don't believe it is right to measure machine creativity directly to that of humans who have had millennia to develop our skills.",
     "像 Colton 这样的研究者认为，直接把机器创造力与人类创造力衡量比较并不公平，因为人类已有数千年发展技能。",
     "宾语从句 + 比较", "believe 后省略 that；it is right to... 中 it 为形式主语；that of humans 指代 creativity。",
     words(("measure", "v.", "衡量"), ("millennia", "n.", "数千年"))),
    (29, 7, "Others, though, are fascinated by the prospect that a computer might create something as original and subtle as our best artists.",
     "然而，其他人则着迷于这样一种可能性：计算机也许能创造出与顶尖艺术家一样原创而微妙的东西。",
     "同位语从句 + as...as", "that 从句解释 prospect；as original and subtle as 构成同级比较。",
     words(("prospect", "n.", "可能性；前景"), ("subtle", "adj.", "微妙的"))),
    (30, 7, "So far, only one has come close.",
     "到目前为止，只有一个程序接近做到这一点。",
     "现在完成时", "has come close 表“接近成功”。",
     words(("come close", "phr.", "接近"))),
    (31, 7, "Composer David Cope invented a program called Experiments in Musical Intelligence, or EMI.",
     "作曲家 David Cope 发明了一个名为“音乐智能实验”的程序，简称 EMI。",
     "过去分词定语", "called... 修饰 program；or EMI 给出简称。",
     words(("composer", "n.", "作曲家"))),
    (32, 7, "Not only did EMI create compositions in Cope's style, but also that of the most revered classical composers, including Bach, Chopin and Mozart.",
     "EMI 不仅能创作 Cope 风格的作品，还能创作最受尊崇的古典作曲家风格的作品，包括巴赫、肖邦和莫扎特。",
     "not only 倒装 + but also", "Not only 位于句首引起助动词 did 倒装；that 指代 style。",
     words(("composition", "n.", "作品；作曲"), ("revered", "adj.", "受尊敬的"))),
    (33, 7, "Audiences were moved to tears, and EMI even fooled classical music experts into thinking they were hearing genuine Bach.",
     "观众被感动落泪，EMI 甚至骗过古典音乐专家，让他们以为自己听到的是真正的巴赫。",
     "被动 + fool into doing", "were moved to tears 为被动；fooled...into thinking 表使误以为。",
     words(("move to tears", "phr.", "感动落泪"), ("genuine", "adj.", "真正的"))),
    (34, 8, "Not everyone was impressed however.",
     "然而，并非所有人都 impressed。",
     "部分否定", "Not everyone 表“并非每个人”。",
     words(("impressed", "adj.", "印象深刻的"))),
    (35, 8, "Some, such as Wiggins, have blasted Cope's work as pseudoscience, and condemned him for his deliberately vague explanation of how the software worked.",
     "一些人，如 Wiggins，猛烈批评 Cope 的作品是伪科学，并谴责他故意含糊解释软件如何运作。",
     "并列谓语 + how 从句", "have blasted 与 condemned 并列；how the software worked 作 explanation 的内容。",
     words(("blast", "v.", "猛烈批评"), ("pseudoscience", "n.", "伪科学"), ("vague", "adj.", "含糊的"))),
    (36, 8, "Meanwhile, Douglas Hofstadter of Indiana University said EMI created replicas which still rely completely on the original artist's creative impulses.",
     "与此同时，印第安纳大学的 Douglas Hofstadter 说，EMI 创造的是复制品，仍然完全依赖原艺术家的创作冲动。",
     "宾语从句 + 定语从句", "said 后接宾语从句；which 修饰 replicas。",
     words(("replica", "n.", "复制品"), ("impulse", "n.", "冲动"))),
    (37, 8, "When audiences found out the truth they were often outraged with Cope, and one music lover even tried to punch him.",
     "当观众发现真相后，他们常常对 Cope 感到愤怒，甚至有一位音乐爱好者试图打他。",
     "when 时间从句 + 并列句", "When 从句说明时间；were outraged 与 tried 并列描述反应。",
     words(("outraged", "adj.", "愤怒的"), ("punch", "v.", "用拳打"))),
    (38, 8, "Amid such controversy, Cope destroyed EMI's vital databases.",
     "在这样的争议中，Cope 销毁了 EMI 的关键数据库。",
     "介词短语状语", "Amid such controversy 表背景；destroyed 为主谓宾。",
     words(("controversy", "n.", "争议"), ("vital", "adj.", "关键的"))),
    (39, 9, "But why did so many people love the music, yet recoil when they discovered how it was composed?",
     "但是，为什么那么多人喜欢这些音乐，却在发现其创作方式后退缩反感呢？",
     "疑问句 + when 时间从句", "love 与 recoil 形成转折；how it was composed 作 discovered 的宾语。",
     words(("recoil", "v.", "退缩；反感"), ("compose", "v.", "作曲"))),
    (40, 9, "A study by computer scientist David Moffat of Glasgow Caledonian University provides a clue.",
     "格拉斯哥卡利多尼亚大学计算机科学家 David Moffat 的一项研究提供了线索。",
     "简单句", "by... 修饰 study；provides a clue 为谓语宾语。",
     words(("clue", "n.", "线索"))),
    (41, 9, "He asked both expert musicians and non-experts to assess six compositions.",
     "他要求专业音乐家和非专业人士评估六首作品。",
     "ask somebody to do", "both...and... 连接两个宾语；to assess 为宾补。",
     words(("assess", "v.", "评估"), ("non-expert", "n.", "非专业人士"))),
    (42, 9, "The participants weren't told beforehand whether the tunes were composed by humans or computers, but were asked to guess, and then rate how much they liked each one.",
     "参与者事先没有被告知这些曲子是人类还是计算机创作的，而是被要求猜测，然后评价自己有多喜欢每一首。",
     "被动语态 + whether 从句", "weren't told 与 were asked 并列被动；whether 从句作 told 的内容。",
     words(("participant", "n.", "参与者"), ("beforehand", "adv.", "事先"))),
    (43, 9, "People who thought the composer was a computer tended to dislike the piece more than those who believed it was human.",
     "认为作曲者是计算机的人，往往比认为作曲者是人类的人更不喜欢该作品。",
     "定语从句 + 比较", "两个 who 从句分别修饰 People 与 those；more than 构成比较。",
     words(("tend to", "phr.", "倾向于"), ("piece", "n.", "作品"))),
    (44, 9, "This was true even among the experts, who might have been expected to be more objective in their analyses.",
     "即使在本应更客观分析的专家中，这一点也成立。",
     "非限制性定语从句", "who 补充说明 experts；might have been expected 表本可期待。",
     words(("objective", "adj.", "客观的"), ("analysis", "n.", "分析"))),
    (45, 10, "Where does this prejudice come from?",
     "这种偏见来自哪里？",
     "特殊疑问句", "come from 询问来源。",
     words(("prejudice", "n.", "偏见"))),
    (46, 10, "Paul Bloom of Yale University has a suggestion: he reckons part of the pleasure we get from art stems from the creative process behind the work.",
     "耶鲁大学的 Paul Bloom 有一个解释：他认为，我们从艺术中获得的部分愉悦源于作品背后的创作过程。",
     "冒号解释 + 宾语从句", "冒号后解释 suggestion；we get from art 修饰 pleasure；stems from 表来源。",
     words(("stem from", "phr.", "源于"), ("creative process", "n.", "创作过程"))),
    (47, 10, "This can give it an irresistible essence, says Bloom.",
     "Bloom 说，这能赋予它一种不可抗拒的本质。",
     "give + 双宾语", "give it an essence 为 give 双宾结构。",
     words(("irresistible", "adj.", "不可抗拒的"), ("essence", "n.", "本质"))),
    (48, 10, "Meanwhile, experiments by Justin Kruger of New York University have shown that people's enjoyment of an artwork increases if they think more time and effort was needed to create it.",
     "与此同时，纽约大学 Justin Kruger 的实验表明，如果人们认为创作某件艺术品需要更多时间和努力，他们对它的欣赏会增加。",
     "that 宾语从句 + if 条件句", "have shown 后接 that 从句；if 引导条件；was needed 为被动。",
     words(("enjoyment", "n.", "欣赏；享受"), ("artwork", "n.", "艺术品"))),
    (49, 10, "Similarly, Colton thinks that when people experience art, they wonder what the artist might have been thinking or what the artist is trying to tell them.",
     "同样，Colton 认为，当人们体验艺术时，他们会想艺术家当时可能在想什么，或试图告诉他们什么。",
     "that 宾语从句 + when 从句", "thinks 后接 that 从句；when 引导时间；两个 what 从句作 wonder 的宾语。",
     words(("similarly", "adv.", "同样地"), ("wonder", "v.", "想知道"))),
    (50, 10, "It seems obvious, therefore, that with computers producing art, this speculation is cut short - there's nothing to explore.",
     "因此，显而易见，当计算机创作艺术时，这种揣测被截断了——没有什么可探索的。",
     "it 形式主语 + with 复合结构", "It seems obvious that... 中 it 为形式主语；with computers producing art 表背景。",
     words(("speculation", "n.", "揣测"), ("cut short", "phr.", "中断"))),
    (51, 10, "But as technology becomes increasingly complex, finding those greater depths in computer art could become possible.",
     "但随着技术变得日益复杂，在计算机艺术中发现更深层次的内容可能会成为可能。",
     "as 时间/伴随从句 + 动名词主语", "as 表随着；finding... 作主语；could become possible 表可能性。",
     words(("increasingly", "adv.", "日益"), ("depth", "n.", "深度"))),
    (52, 10, "This is precisely why Colton asks the Painting Fool to tap into online social networks for its inspiration: hopefully this way it will choose themes that will already be meaningful to us.",
     "这正是 Colton 要求“绘画傻瓜”利用在线社交网络获取灵感的原因：希望通过这种方式，它会选择对我们来说已经有意义的主题。",
     "why 表语从句 + 冒号解释", "why 引导表语从句；ask...to do；冒号后解释目的。",
     words(("tap into", "phr.", "利用；接入"), ("inspiration", "n.", "灵感"), ("meaningful", "adj.", "有意义的"))),
]


def make_passage_2():
    return {
        "id": "c13-test1-p2",
        "source": "剑桥雅思13 · Test 1 · Passage 2",
        "title": "Why being bored is stimulating - and useful, too",
        "phrases": [
            {"w": "mind-wandering", "pos": "n.", "def": "思维游走"},
            {"w": "attention system", "pos": "n.", "def": "注意系统"},
            {"w": "boredom proneness", "pos": "n.", "def": "易无聊倾向"},
            {"w": "social media", "pos": "n.", "def": "社交媒体"},
        ],
        "analysis_unit": "sentence",
        "sentences": [
            {"id": i, "para": para, "label": label, "en": en, "zh": zh, "grammar": {"type": gt, "note": gn}, "words": ws}
            for i, para, label, en, zh, gt, gn, ws in P2_SENTENCES
        ],
        "questions": [
            {
                "title": "Questions 14-19 · Matching headings",
                "type": "matching_headings",
                "instructions": [
                    "Reading Passage 2 has six paragraphs, A-F.",
                    "Choose the correct heading for each paragraph from the list of headings below.",
                    "Answer with Roman numerals i-viii.",
                    "i The productive outcomes that may result from boredom",
                    "ii What teachers can do to prevent boredom",
                    "iii A new explanation and a new cure for boredom",
                    "iv Problems with a scientific approach to boredom",
                    "v A potential danger arising from boredom",
                    "vi Creating a system of classification for feelings of boredom",
                    "vii Age groups most affected by boredom",
                    "viii Identifying those most affected by boredom",
                ],
                "items": [
                    {"number": 14, "prompt": "Paragraph A", "answer": "iv", "evidence_sentence": 1},
                    {"number": 15, "prompt": "Paragraph B", "answer": "vi", "evidence_sentence": 7},
                    {"number": 16, "prompt": "Paragraph C", "answer": "i", "evidence_sentence": 15},
                    {"number": 17, "prompt": "Paragraph D", "answer": "v", "evidence_sentence": 25},
                    {"number": 18, "prompt": "Paragraph E", "answer": "viii", "evidence_sentence": 31},
                    {"number": 19, "prompt": "Paragraph F", "answer": "iii", "evidence_sentence": 42},
                ],
            },
            {
                "title": "Questions 20-23 · Matching features",
                "type": "matching_features",
                "instructions": [
                    "Match each person with the correct idea, A-E.",
                    "A The way we live today may encourage boredom.",
                    "B One sort of boredom is worse than all the others.",
                    "C Levels of boredom may fall in the future.",
                    "D Trying to cope with boredom can increase its negative effects.",
                    "E Boredom may encourage us to avoid an unpleasant experience.",
                ],
                "items": [
                    {"number": 20, "prompt": "Peter Toohey", "answer": "E", "evidence_sentence": 5},
                    {"number": 21, "prompt": "Thomas Goetz", "answer": "B", "evidence_sentence": 10},
                    {"number": 22, "prompt": "John Eastwood", "answer": "D", "evidence_sentence": 28},
                    {"number": 23, "prompt": "Francoise Wemelsfelder", "answer": "A", "evidence_sentence": 42},
                ],
            },
            {
                "title": "Questions 24-26 · Summary completion",
                "type": "summary_completion",
                "instructions": ["Complete the summary below.", "Choose ONE WORD ONLY from the passage for each answer."],
                "items": [
                    {"number": 24, "prompt": "People cannot ___, due to a failure in the 'attention system'.", "answer": "focus", "evidence_sentence": 27},
                    {"number": 25, "prompt": "Those for whom ___ is an important aim in life may have problems coping with boredom.", "answer": "pleasure", "evidence_sentence": 34},
                    {"number": 26, "prompt": "Those who have the characteristic of ___ can generally cope with it.", "answer": "curiosity", "evidence_sentence": 35},
                ],
            },
        ],
    }


def make_passage_3():
    return {
        "id": "c13-test1-p3",
        "source": "剑桥雅思13 · Test 1 · Passage 3",
        "title": "Artificial artists",
        "phrases": [
            {"w": "The Painting Fool", "pos": "n.", "def": "“绘画傻瓜”（电脑绘画程序）"},
            {"w": "computerised art", "pos": "n.", "def": "计算机化艺术"},
            {"w": "double standards", "pos": "n.", "def": "双重标准"},
            {"w": "creative process", "pos": "n.", "def": "创作过程"},
        ],
        "analysis_unit": "sentence",
        "sentences": [
            {"id": i, "para": para, "en": en, "zh": zh, "grammar": {"type": gt, "note": gn}, "words": ws}
            for i, para, en, zh, gt, gn, ws in P3_SENTENCES
        ],
        "questions": [
            {
                "title": "Questions 27-31 · Multiple choice",
                "type": "multiple_choice",
                "instructions": ["Choose the correct letter, A, B, C or D."],
                "items": [
                    {"number": 27, "prompt": "What is the writer suggesting about computer-produced works in the first paragraph?", "answer": "B", "evidence_sentence": 1},
                    {"number": 28, "prompt": "According to Geraint Wiggins, why are many people worried by computer art?", "answer": "C", "evidence_sentence": 9},
                    {"number": 29, "prompt": "What is a key difference between Aaron and the Painting Fool?", "answer": "C", "evidence_sentence": 16},
                    {"number": 30, "prompt": "What point does Simon Colton make in the fourth paragraph?", "answer": "D", "evidence_sentence": 20},
                    {"number": 31, "prompt": "The writer refers to the paintings of a chair as an example of computer art which...", "answer": "A", "evidence_sentence": 25},
                ],
            },
            {
                "title": "Questions 32-37 · Matching sentence endings",
                "type": "sentence_endings",
                "instructions": [
                    "Complete each sentence with the correct ending, A-G.",
                    "A generating work that was virtually indistinguishable from that of humans.",
                    "B knowing whether it was the work of humans or software.",
                    "C producing work entirely dependent on the imagination of its creator.",
                    "D comparing the artistic achievements of humans and computers.",
                    "E revealing the technical details of his program.",
                    "F persuading the public to appreciate computer art.",
                    "G discovering that it was the product of a computer program.",
                ],
                "items": [
                    {"number": 32, "prompt": "Simon Colton says it is important to consider the long-term view when...", "answer": "D", "evidence_sentence": 28},
                    {"number": 33, "prompt": "David Cope's EMI software surprised people by...", "answer": "A", "evidence_sentence": 32},
                    {"number": 34, "prompt": "Geraint Wiggins criticised Cope for not...", "answer": "E", "evidence_sentence": 35},
                    {"number": 35, "prompt": "Douglas Hofstadter claimed that EMI was...", "answer": "C", "evidence_sentence": 36},
                    {"number": 36, "prompt": "Audiences who had listened to EMI's music became angry after...", "answer": "G", "evidence_sentence": 37},
                    {"number": 37, "prompt": "The participants in David Moffat's study had to assess music without...", "answer": "B", "evidence_sentence": 42},
                ],
            },
            {
                "title": "Questions 38-40 · YES / NO / NOT GIVEN",
                "type": "yes_no_not_given",
                "instructions": ["Do the following statements agree with the claims of the writer?"],
                "items": [
                    {"number": 38, "prompt": "Moffat's research may help explain people's reactions to EMI.", "answer": "YES", "evidence_sentence": 40},
                    {"number": 39, "prompt": "The non-experts in Moffat's study all responded in a predictable way.", "answer": "NOT GIVEN", "evidence_sentence": 41},
                    {"number": 40, "prompt": "Justin Kruger's findings cast doubt on Paul Bloom's theory about people's prejudice towards computer art.", "answer": "NO", "evidence_sentence": 48},
                ],
            },
        ],
    }


def write_passage(passage):
    path = PASSAGES / f"{passage['id']}.json"
    path.write_text(json.dumps(passage, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def update_index(*passages):
    idx = json.loads(INDEX.read_text(encoding="utf-8"))
    by_id = {item["id"]: item for item in idx.get("passages", [])}
    order = [item["id"] for item in idx.get("passages", [])]
    for passage in passages:
        item = {
            "id": passage["id"],
            "source": passage["source"],
            "title": passage["title"],
            "sentence_count": len(passage["sentences"]),
            "question_count": sum(len(group["items"]) for group in passage.get("questions", [])),
        }
        by_id[passage["id"]] = item
        if passage["id"] not in order:
            order.append(passage["id"])
    idx["passages"] = [by_id[i] for i in order if i in by_id]
    INDEX.write_text(json.dumps(idx, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main():
    PASSAGES.mkdir(parents=True, exist_ok=True)
    p2 = make_passage_2()
    p3 = make_passage_3()
    paths = [write_passage(p2), write_passage(p3)]
    update_index(p2, p3)
    for path in paths:
      print(path)


if __name__ == "__main__":
    main()
