#!/usr/bin/env python
# 第十七批(约50词):逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -duce 引导
  {"word":"introduction","phonetic":"ˌɪntrəˈdʌkʃən","pos":"n.","def":"介绍；引言；引入，采用","cefr":"B1","freq_rank":78,
   "sentence_en":"The book has a short introduction.","sentence_zh":"这本书有一段简短的引言。",
   "aids":{"morphemes":[M("intro","prefix","向内"),M("duct","root","引导，带"),M("ion","suffix","名词后缀")],
     "derivation":"introduce(带入)+ion → 引入/介绍的行为 → 介绍、引言",
     "family":FAM("duct/duce","引导、带",[W("introduce","介绍"),W("conduct","实施"),W("reduce","减少"),W("produce","生产")]),
     "mnemonic":"duct=引导(和 introduce 一家);把人/内容'带入'的部分,就是 introduction 介绍、引言。",
     "forms":[F("introduce","v.","介绍")]}},
  # -tribute 给
  {"word":"distribute","phonetic":"dɪˈstrɪbjuːt","pos":"v.","def":"分发，分配；分布","cefr":"B2","freq_rank":95,
   "sentence_en":"They distributed food to the poor.","sentence_zh":"他们向穷人分发食物。",
   "aids":{"morphemes":[M("dis","prefix","分开，散"),M("tribute","root","给予")],
     "derivation":"dis(散)+tribute(给) → 分散地给出去 → 分发",
     "family":FAM("tribute","给予",[W("contribute","贡献"),W("attribute","归因于"),W("distribution","分配")]),
     "mnemonic":"tribute=给(和 contribute 一家);把东西分散(dis-)给出去,就是 distribute 分发;distribution 分配。",
     "forms":[F("distribution","n.","分配"),F("distributor","n.","分销商")]}},
  # -tend 伸
  {"word":"pretend","phonetic":"prɪˈtend","pos":"v.","def":"假装，佯装","cefr":"B1","freq_rank":79,
   "sentence_en":"He pretended to be asleep.","sentence_zh":"他假装睡着了。",
   "aids":{"morphemes":[M("pre","prefix","在前"),M("tend","root","伸展")],
     "derivation":"pre(在前)+tend(伸) → 在人前伸出个假样子 → 假装",
     "family":FAM("tend/tent","伸展",[W("tend","倾向"),W("attend","出席"),W("intend","打算"),W("extend","延伸")]),
     "mnemonic":"tend=伸(和 extend 一家);在人前(pre-)摆出、'伸'出个假象,就是 pretend 假装;pretence 假装。",
     "forms":[F("pretence","n.","假装"),F("pretended","v.","过去式/过去分词")]}},
  {"word":"tendency","phonetic":"ˈtendənsi","pos":"n.","def":"趋势，倾向","cefr":"B2","freq_rank":127,
   "sentence_en":"He has a tendency to exaggerate.","sentence_zh":"他有夸大其词的倾向。",
   "aids":{"morphemes":[M("tend","root","伸展"),M("ency","suffix","名词后缀")],
     "derivation":"tend(伸)+ency → 心朝某方向伸的势头 → 倾向",
     "family":FAM("tend/tent","伸展",[W("tend","倾向"),W("intend","打算"),W("extend","延伸")]),
     "mnemonic":"tend=伸(和 tend 倾向一家);总朝某方向伸过去的势头,就是 tendency 趋势、倾向。",
     "forms":[F("tend","v.","倾向"),F("tendencies","n.","倾向(复数)")]}},
  # -viol 强力
  {"word":"violate","phonetic":"ˈvaɪəleɪt","pos":"v.","def":"违反，违背；侵犯；亵渎","cefr":"B2","freq_rank":80,
   "sentence_en":"They violated the rules.","sentence_zh":"他们违反了规则。",
   "aids":{"morphemes":[M("viol","root","强力，侵犯"),M("ate","suffix","动词后缀")],
     "derivation":"viol(强力)+ate → 强行破坏 → 违反、侵犯",
     "family":FAM("viol","强力、侵犯",[W("violence","暴力"),W("violent","暴力的")]),
     "mnemonic":"viol=强力侵犯(和 violence 一家);强行破坏规则/权利,就是 violate 违反、侵犯;violation 违规。",
     "forms":[F("violation","n.","违反，违规")]}},
  # -apt 适合
  {"word":"adapt","phonetic":"əˈdæpt","pos":"v.","def":"(使)适应；改编","cefr":"B2","freq_rank":90,
   "sentence_en":"Animals adapt to their environment.","sentence_zh":"动物会适应环境。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("apt","root","适合")],
     "derivation":"ad(朝向)+apt(适合) → 使朝向合适 → 适应",
     "family":FAM("apt","适合",[W("apt","易于的；恰当的"),W("aptitude","天资"),W("adept","擅长的")]),
     "mnemonic":"apt=适合(想 aptitude 天资);使自己朝(ad-)环境变得合适,就是 adapt 适应;adaptation 适应/改编。",
     "forms":[F("adaptation","n.","适应；改编"),F("adaptable","adj.","适应性强的")]}},
  # -fer 带
  {"word":"differ","phonetic":"ˈdɪfə","pos":"v.","def":"不同，相异；意见不合","cefr":"B1","freq_rank":109,
   "sentence_en":"Opinions differ on this issue.","sentence_zh":"人们对此事看法不一。",
   "aids":{"morphemes":[M("dif","prefix","分开(dis)"),M("fer","root","带")],
     "derivation":"dif(分开)+fer(带) → 各带各的、分道 → 不同",
     "family":FAM("fer","带、拿",[W("offer","提供"),W("transfer","转移"),W("prefer","更喜欢"),W("refer","提及")]),
     "mnemonic":"fer=带(和 offer 一家);各自(dif-)带走一套、彼此有别,就是 differ 不同;difference 差异;different 不同的。",
     "forms":[F("difference","n.","差异"),F("different","adj.","不同的")]}},
  {"word":"preference","phonetic":"ˈprefərəns","pos":"n.","def":"偏爱，偏好；优先","cefr":"B2","freq_rank":123,
   "sentence_en":"I have a preference for tea.","sentence_zh":"我更偏爱喝茶。",
   "aids":{"morphemes":[M("pre","prefix","在前"),M("fer","root","带"),M("ence","suffix","名词后缀")],
     "derivation":"prefer(优先带出)+ence → 更看重、优先选 → 偏爱",
     "family":FAM("fer","带、拿",[W("prefer","更喜欢"),W("offer","提供"),W("transfer","转移")]),
     "mnemonic":"prefer(更喜欢)的名词;把某物往前(pre-)带、优先看重,就是 preference 偏爱;动词 prefer。",
     "forms":[F("prefer","v.","更喜欢")]}},
  # -fic 做
  {"word":"efficient","phonetic":"ɪˈfɪʃnt","pos":"adj.","def":"高效的，有效率的","cefr":"B1","freq_rank":110,
   "sentence_en":"This is a very efficient system.","sentence_zh":"这是一个非常高效的系统。",
   "aids":{"morphemes":[M("ef","prefix","向外(ex)"),M("fic","root","做"),M("ient","suffix","…的")],
     "derivation":"ef(向外)+fic(做) → 少费力就做出成效的 → 高效的",
     "family":FAM("fic/fac","做、造",[W("effect","效果"),W("efficiency","效率"),W("factory","工厂")]),
     "mnemonic":"fic=做(和 effect 一家);用最少投入做出最多成效,就是 efficient 高效的;efficiency 效率;反义 inefficient。",
     "forms":[F("efficiency","n.","效率"),F("efficiently","adv.","高效地")]}},
  # -pos 放
  {"word":"composition","phonetic":"ˌkɒmpəˈzɪʃən","pos":"n.","def":"作文，作品；组成，构成","cefr":"B1","freq_rank":111,
   "sentence_en":"The composition of the soil varies.","sentence_zh":"土壤的构成各不相同。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("pos","root","放置"),M("ition","suffix","名词后缀")],
     "derivation":"com(一起)+pos(放) → 把各部分放到一起 → 组成;把词句组到一起 → 作文",
     "family":FAM("pos/pose","放置",[W("compose","组成"),W("propose","提议"),W("expose","暴露"),W("position","位置")]),
     "mnemonic":"pos=放(和 compose 一家);把要素放到一起构成的整体=组成;把文字组织成篇=作文,都是 composition。",
     "forms":[F("compose","v.","组成；创作")]}},
  # -calc 石子(计数)
  {"word":"calculate","phonetic":"ˈkælkjuleɪt","pos":"v.","def":"计算；预测，估计","cefr":"B1","freq_rank":126,
   "sentence_en":"Calculate the total cost.","sentence_zh":"算出总成本。",
   "aids":{"morphemes":[M("calcul","root","小石子(calculus)"),M("ate","suffix","动词后缀")],
     "derivation":"拉丁 calculus'小石子'(古人用石子计数);用石子算 → 计算",
     "family":FAM("calc","石子、计数",[W("calculator","计算器"),W("calculus","微积分")]),
     "mnemonic":"calcul=小石子(古人拿石子算数,calculus 微积分同源);算数,就是 calculate;calculator 计算器。",
     "forms":[F("calculation","n.","计算"),F("calculator","n.","计算器")]}},
  # -form 形
  {"word":"uniform","phonetic":"ˈjuːnɪfɔːm","pos":"n./adj.","def":"制服；统一的，一致的","cefr":"B1","freq_rank":128,
   "sentence_en":"Students wear a school uniform.","sentence_zh":"学生穿校服。",
   "aids":{"morphemes":[M("uni","root","一"),M("form","root","形式")],
     "derivation":"uni(一)+form(形式) → 统一样式的(衣) → 制服;引申'一律的'",
     "family":FAM("form","形式、形状",[W("form","形式"),W("reform","改革"),W("transform","改变"),W("format","格式")]),
     "mnemonic":"uni(一)+form(形式)——大家穿成一个样式=制服 uniform;样样一律=统一的;uniformly 一致地。",
     "forms":[F("uniforms","n.","制服(复数)"),F("uniformity","n.","一致")]}},
  # -miss 送
  {"word":"admission","phonetic":"ədˈmɪʃən","pos":"n.","def":"准许进入；入场费；承认，录取","cefr":"B2","freq_rank":125,
   "sentence_en":"Admission is free for children.","sentence_zh":"儿童免费入场。",
   "aids":{"morphemes":[M("ad","prefix","朝向，进入"),M("miss","root","送，放"),M("ion","suffix","名词后缀")],
     "derivation":"admit(放进来)+ion → 准入/录取/承认的行为 → 准许进入",
     "family":FAM("mit/miss","送、放",[W("admit","承认；准入"),W("submit","提交"),W("mission","任务"),W("permit","允许")]),
     "mnemonic":"miss=放(和 admit 一家);放人进(ad-)门=准入/入场费;放下心防承认=承认,都是 admission;大学 admission 录取。",
     "forms":[F("admit","v.","承认；准入")]}},
  # -lig 绑
  {"word":"obligation","phonetic":"ˌɒblɪˈɡeɪʃən","pos":"n.","def":"义务，责任；恩惠","cefr":"C1","freq_rank":107,
   "sentence_en":"You have no obligation to pay.","sentence_zh":"你没有付款的义务。",
   "aids":{"morphemes":[M("ob","prefix","朝向，加强"),M("lig","root","捆绑"),M("ation","suffix","名词后缀")],
     "derivation":"ob(加强)+lig(捆) → 被规矩/道义捆住 → 义务",
     "family":FAM("lig","捆绑",[W("oblige","使负义务"),W("ligament","韧带"),W("religion","宗教")]),
     "mnemonic":"lig=捆(想 ligament 韧带);被道义/契约'捆'住必须做的,就是 obligation 义务;动词 oblige。",
     "forms":[F("oblige","v.","使负义务"),F("obligatory","adj.","强制的")]}},
  # -vari 变
  {"word":"variation","phonetic":"ˌveəriˈeɪʃən","pos":"n.","def":"变化，变动；变种，变体","cefr":"B2","freq_rank":89,
   "sentence_en":"There is little variation in temperature.","sentence_zh":"温度变化不大。",
   "aids":{"morphemes":[M("vari","root","变化"),M("ation","suffix","名词后缀")],
     "derivation":"vary(变化)+ation → 变化的量/形式 → 变化、变体",
     "family":FAM("vari","变化",[W("vary","变化"),W("various","各种的"),W("variety","多样"),W("variable","可变的")]),
     "mnemonic":"vari=变(和 vary 一家);程度或形式上的变化,就是 variation;主题的'变奏'也是 variation。",
     "forms":[F("vary","v.","变化")]}},
  # -volu 卷
  {"word":"evolution","phonetic":"ˌiːvəˈluːʃən","pos":"n.","def":"进化，演变；发展","cefr":"B2","freq_rank":96,
   "sentence_en":"The theory of evolution is well established.","sentence_zh":"进化论已获充分确立。",
   "aids":{"morphemes":[M("e","prefix","向外"),M("volu","root","卷，转"),M("tion","suffix","名词后缀")],
     "derivation":"evolve(向外展开)+tion → 逐步展开发展 → 进化",
     "family":FAM("volv/volu","卷、转",[W("evolve","进化"),W("revolve","旋转"),W("involve","涉及"),W("revolution","革命")]),
     "mnemonic":"volu=卷(和 evolve 一家);像卷轴向外(e-)徐徐展开的过程,就是 evolution 进化、演变。",
     "forms":[F("evolve","v.","进化"),F("evolutionary","adj.","进化的")]}},
  # -sign 记号
  {"word":"significance","phonetic":"sɪɡˈnɪfɪkəns","pos":"n.","def":"重要性，意义","cefr":"B2","freq_rank":91,
   "sentence_en":"The discovery is of great significance.","sentence_zh":"这项发现意义重大。",
   "aids":{"morphemes":[M("sign","root","记号"),M("ific","root","做"),M("ance","suffix","名词后缀")],
     "derivation":"significant(值得标记的)+ance → 值得标出的分量 → 重要性",
     "family":FAM("sign","记号、标志",[W("significant","重要的"),W("sign","符号"),W("signal","信号")]),
     "mnemonic":"sign=记号(和 significant 一家);重要到需要标出来的分量/含义,就是 significance 重要性、意义。",
     "forms":[F("significant","adj.","重要的")]}},
  # -tract 拉
  {"word":"trace","phonetic":"treɪs","pos":"n./v.","def":"痕迹，踪迹；微量；追踪","cefr":"B2","freq_rank":121,
   "sentence_en":"There was no trace of the ship.","sentence_zh":"那艘船不见踪影。",
   "aids":{"morphemes":[M("trac","root","拉，拽(tract)"),M("e","suffix","结尾")],
     "derivation":"tract(拉)→ 拖拉过留下的痕 → 痕迹;顺痕迹拉查 → 追踪",
     "family":FAM("tract","拉、拽",[W("attract","吸引"),W("extract","提取"),W("track","轨迹"),W("contract","合同")]),
     "mnemonic":"trac=拉(和 track 轨迹一家);拖过留下的印=痕迹;顺着痕迹一路追查=trace 追踪;a trace of 一丝。",
     "forms":[F("traces","n.","痕迹(复数)"),F("traced","v.","过去式/过去分词")]}},
  # -limit 界限
  {"word":"limitation","phonetic":"ˌlɪmɪˈteɪʃən","pos":"n.","def":"限制；局限，缺陷","cefr":"B2","freq_rank":120,
   "sentence_en":"Everyone has their limitations.","sentence_zh":"每个人都有自己的局限。",
   "aids":{"morphemes":[M("limit","root","界限"),M("ation","suffix","名词后缀")],
     "derivation":"limit(限制)+ation → 受限的状况 → 限制、局限",
     "family":FAM("limit/limin","界限、门槛",[W("limit","限制"),W("eliminate","消除"),W("preliminary","预备的")]),
     "mnemonic":"limit=界限;被框住的范围/短板,就是 limitation 限制、局限;know one's limitations 有自知之明。",
     "forms":[F("limit","v.","限制")]}},
  # 高频名词/动词(常见/词根)
  {"word":"presentation","phonetic":"ˌpreznˈteɪʃən","pos":"n.","def":"展示，演示；报告；呈现","cefr":"B1","freq_rank":74,
   "sentence_en":"She gave a presentation on climate.","sentence_zh":"她做了一个关于气候的演示。",
   "aids":{"morphemes":[M("present","root","呈现，在场"),M("ation","suffix","名词后缀")],
     "derivation":"present(呈现)+ation → 呈现给人看/讲 → 展示、报告",
     "family":FAM("present","呈现、在场",[W("present","呈现"),W("represent","代表"),W("presence","出席")]),
     "mnemonic":"present=呈现(和 present 一家);把内容呈现出来讲/演,就是 presentation 展示、演示、报告。",
     "forms":[F("present","v.","呈现")]}},
  {"word":"appointment","phonetic":"əˈpɔɪntmənt","pos":"n.","def":"约会，预约；任命，职位","cefr":"B1","freq_rank":122,
   "sentence_en":"I have a doctor's appointment.","sentence_zh":"我预约了看医生。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("point","root","点，指定"),M("ment","suffix","名词后缀")],
     "derivation":"appoint(指定)+ment → 指定好的时间/职位 → 约会、任命",
     "family":FAM("point/punct","点、指定",[W("point","点"),W("appoint","任命"),W("punctual","准时的")]),
     "mnemonic":"point=指定(和 appoint 任命一家);指定好的会面时间=约会/预约;指定某人任职=任命,都是 appointment。",
     "forms":[F("appoint","v.","任命")]}},
  {"word":"reservation","phonetic":"ˌrezəˈveɪʃən","pos":"n.","def":"预订；保留(意见)；保留地","cefr":"B1","freq_rank":130,
   "sentence_en":"I'd like to make a reservation.","sentence_zh":"我想预订。",
   "aids":{"morphemes":[M("re","prefix","预先，back"),M("serv","root","保持，看守"),M("ation","suffix","名词后缀")],
     "derivation":"reserve(预留)+ation → 预先留住 → 预订;心里留而不说 → 保留意见",
     "family":FAM("serv","看守、保持",[W("reserve","保留"),W("preserve","保存"),W("observe","观察"),W("serve","服务")]),
     "mnemonic":"serv=保持(和 reserve 一家);预先给你留住位子=预订;心里'保留'不认同=保留意见(have reservations)。",
     "forms":[F("reserve","v.","保留，预订")]}},
  {"word":"conservation","phonetic":"ˌkɒnsəˈveɪʃən","pos":"n.","def":"保护，保存；节约","cefr":"B2","freq_rank":64,
   "sentence_en":"Wildlife conservation is important.","sentence_zh":"野生动物保护很重要。",
   "aids":{"morphemes":[M("con","prefix","完全"),M("serv","root","保持"),M("ation","suffix","名词后缀")],
     "derivation":"conserve(完全保持)+ation → 保护、节约的行为 → 保护",
     "family":FAM("serv","看守、保持",[W("conserve","保存"),W("preserve","保存"),W("reserve","保留"),W("conservative","保守的")]),
     "mnemonic":"serv=保持(和 conserve 一家);把资源/自然完好保持住,就是 conservation 保护、节约;energy conservation 节能。",
     "forms":[F("conserve","v.","保存，节约")]}},
  {"word":"imagination","phonetic":"ɪˌmædʒɪˈneɪʃən","pos":"n.","def":"想象力，想象","cefr":"B1","freq_rank":73,
   "sentence_en":"Use your imagination.","sentence_zh":"发挥你的想象力。",
   "aids":{"morphemes":[M("imag","root","像，图像"),M("ination","suffix","名词后缀")],
     "derivation":"imagine(在脑中造像)+ation → 造像的能力 → 想象力",
     "family":FAM("imag","像、模仿",[W("image","形象"),W("imagine","想象"),W("imaginary","虚构的")]),
     "mnemonic":"imag=像(和 imagine 一家);在脑海造出画面的能力,就是 imagination 想象力;imaginative 富想象力的。",
     "forms":[F("imagine","v.","想象"),F("imaginative","adj.","富想象力的")]}},
  {"word":"scholarship","phonetic":"ˈskɒləʃɪp","pos":"n.","def":"奖学金；学问，学术","cefr":"B1","freq_rank":129,
   "sentence_en":"She won a scholarship to Oxford.","sentence_zh":"她获得了去牛津的奖学金。",
   "aids":{"morphemes":[M("scholar","root","学者"),M("ship","suffix","…的身份/状态")],
     "derivation":"scholar(学者)+ship → 助学者求学的资助/学者的造诣 → 奖学金、学问",
     "family":FAM("schol","学校、学问",[W("scholar","学者"),W("school","学校"),W("scholastic","学业的")]),
     "mnemonic":"scholar(学者)+ship;资助学子的钱=奖学金;学者的学术造诣=学问,都是 scholarship。",
     "forms":[F("scholar","n.","学者")]}},
  {"word":"celebrity","phonetic":"sɪˈlebrəti","pos":"n.","def":"名人；名声","cefr":"B2","freq_rank":98,
   "sentence_en":"He became a celebrity overnight.","sentence_zh":"他一夜成名。",
   "aids":{"morphemes":[M("celebr","root","众多，著名"),M("ity","suffix","名词后缀")],
     "derivation":"celebr(著名)+ity → 出名的人 → 名人",
     "family":FAM("celebr","众多、著名",[W("celebrate","庆祝"),W("celebration","庆典")]),
     "mnemonic":"celebr=著名(和 celebrate 一家,众人传颂);广为人知的人物,就是 celebrity 名人;也指'名声'。",
     "forms":[F("celebrities","n.","名人(复数)")]}},
  {"word":"vulnerable","phonetic":"ˈvʌlnərəbl","pos":"adj.","def":"脆弱的，易受伤害的","cefr":"C1","freq_rank":97,
   "sentence_en":"Children are vulnerable to disease.","sentence_zh":"儿童易受疾病侵害。",
   "aids":{"morphemes":[M("vulner","root","伤口(vulnus)"),M("able","suffix","易…的")],
     "derivation":"vulner(伤口)+able → 容易受伤的 → 脆弱的",
     "family":FAM("vulner","伤口",[W("vulnerability","脆弱性")]),
     "mnemonic":"vulner=伤口;容易被戳伤、防护差的,就是 vulnerable 脆弱的、易受伤害的;vulnerability 弱点。",
     "forms":[F("vulnerability","n.","脆弱性")]}},
  {"word":"fantasy","phonetic":"ˈfæntəsi","pos":"n.","def":"幻想；奇幻(作品)","cefr":"B2","freq_rank":99,
   "sentence_en":"He lives in a world of fantasy.","sentence_zh":"他活在幻想世界里。",
   "aids":{"morphemes":[M("phan","root","显现，想象"),M("tasy","suffix","名词后缀")],
     "derivation":"phan(显现于脑中)→ 脑中浮现的非现实图景 → 幻想",
     "family":FAM("phan/phas","显现",[W("phantom","幻影"),W("phenomenon","现象"),W("emphasize","强调")]),
     "mnemonic":"phan=显现(和 phantom 幻影一家);脑中凭空显现的非现实场景,就是 fantasy 幻想;奇幻文学=fantasy。",
     "forms":[F("fantasies","n.","幻想(复数)"),F("fantastic","adj.","极好的；奇异的")]}},
  {"word":"segment","phonetic":"ˈseɡmənt","pos":"n./v.","def":"部分，段；分割","cefr":"B2","freq_rank":87,
   "sentence_en":"Divide the market into segments.","sentence_zh":"把市场分成几个部分。",
   "aids":{"morphemes":[M("seg","root","切(sect)"),M("ment","suffix","名词后缀")],
     "derivation":"seg(切)+ment → 切下来的一块 → 段、部分",
     "family":FAM("sect/seg","切",[W("section","部分"),W("sector","部门"),W("insect","昆虫")]),
     "mnemonic":"seg=切(和 section 一家);从整体切出的一段/一块,就是 segment;把整体分段=segment 分割。",
     "forms":[F("segments","n.","部分(复数)")]}},
  {"word":"emission","phonetic":"ɪˈmɪʃən","pos":"n.","def":"排放，散发；排放物","cefr":"B2","freq_rank":84,
   "sentence_en":"We must reduce carbon emissions.","sentence_zh":"我们必须减少碳排放。",
   "aids":{"morphemes":[M("e","prefix","向外"),M("miss","root","送，放"),M("ion","suffix","名词后缀")],
     "derivation":"e(向外)+miss(放) → 向外放出 → 排放",
     "family":FAM("mit/miss","送、放",[W("emit","发出"),W("submit","提交"),W("mission","任务"),W("transmit","传送")]),
     "mnemonic":"miss=放(和 emit 一家);向外(e-)放出气体/光/热,就是 emission 排放;动词 emit;carbon emissions 碳排放。",
     "forms":[F("emit","v.","发出，排放")]}},
  {"word":"scheme","phonetic":"skiːm","pos":"n./v.","def":"方案，计划；诡计，阴谋","cefr":"B2","freq_rank":113,
   "sentence_en":"The government launched a new scheme.","sentence_zh":"政府推出了一项新方案。",
   "aids":{"morphemes":[M("scheme","root","形式，图式(希腊 skhema)")],
     "derivation":"希腊 skhema'形状、方案';系统的安排 → 方案;暗中的安排 → 阴谋",
     "family":FAM("","相关词",[W("schematic","示意的")]),
     "mnemonic":"scheme=图式/安排;摆好的系统计划=方案(pension scheme 养老金计划);暗中盘算=诡计(scheme against)。",
     "forms":[F("schemes","n.","方案(复数)"),F("scheming","adj.","诡计多端的")]}},
  {"word":"frequency","phonetic":"ˈfriːkwənsi","pos":"n.","def":"频率，频繁；(电)频率","cefr":"B2","freq_rank":115,
   "sentence_en":"The frequency of accidents has increased.","sentence_zh":"事故的频率增加了。",
   "aids":{"morphemes":[M("frequ","root","频繁，拥挤(frequens)"),M("ency","suffix","名词后缀")],
     "derivation":"frequent(频繁)+ency → 频繁的程度 → 频率",
     "family":FAM("frequ","频繁",[W("frequent","频繁的"),W("frequently","经常")]),
     "mnemonic":"frequ=频繁(和 frequent 一家);某事发生的频繁程度,就是 frequency 频率;高频=high frequency。",
     "forms":[F("frequent","adj.","频繁的"),F("frequently","adv.","经常")]}},
  # 常见词
  {"word":"vital","phonetic":"ˈvaɪtl","pos":"adj.","def":"至关重要的；生命的，有活力的","cefr":"B2","freq_rank":85,
   "sentence_en":"Water is vital for life.","sentence_zh":"水对生命至关重要。",
   "aids":{"morphemes":[M("vit","root","生命"),M("al","suffix","…的")],
     "derivation":"vit(生命)+al → 关乎生命的 → 至关重要的",
     "family":FAM("vit/viv","生命、活",[W("vitamin","维生素"),W("survive","幸存"),W("vivid","生动的")]),
     "mnemonic":"vit=生命(想 vitamin 维生素);像生命一样不可或缺的,就是 vital 至关重要的;vitality 活力。",
     "forms":[F("vitality","n.","活力"),F("vitally","adv.","极其")]}},
  {"word":"fate","phonetic":"feɪt","pos":"n.","def":"命运，天数；结局","cefr":"B2","freq_rank":86,
   "sentence_en":"They left their fate to chance.","sentence_zh":"他们把命运交给了运气。",
   "aids":{"morphemes":[M("fat","root","说(拉丁 fari 说)"),M("e","suffix","结尾")],
     "derivation":"拉丁 fatum'神所说定的';命中注定 → 命运",
     "family":FAM("fat/fa","说",[W("fatal","致命的"),W("fable","寓言"),W("famous","著名的")]),
     "mnemonic":"fat=说(神'说定'的);命中被安排好的走向,就是 fate 命运;fatal 致命的(命定要死)。",
     "forms":[F("fatal","adj.","致命的"),F("fates","n.","命运(复数)")]}},
  {"word":"stable","phonetic":"ˈsteɪbl","pos":"adj.","def":"稳定的，安定的；牢固的","cefr":"B1","freq_rank":77,
   "sentence_en":"The patient is in a stable condition.","sentence_zh":"病人情况稳定。",
   "aids":{"morphemes":[M("st","root","站，立"),M("able","suffix","能…的")],
     "derivation":"st(站)+able → 能稳稳站住的 → 稳定的",
     "family":FAM("st/sta","站、立",[W("stand","站立"),W("status","状态"),W("stable","稳定的"),W("establish","建立")]),
     "mnemonic":"st=站(和 stand 一家);能稳稳立住不倒的,就是 stable 稳定的;stability 稳定性;反义 unstable。",
     "forms":[F("stability","n.","稳定性")]}},
  {"word":"steady","phonetic":"ˈstedi","pos":"adj./v.","def":"稳定的，平稳的；沉着的","cefr":"B1","freq_rank":83,
   "sentence_en":"He has a steady job.","sentence_zh":"他有一份稳定的工作。",
   "aids":{"morphemes":[M("stead","root","位置，站立处(sted)"),M("y","suffix","…的")],
     "derivation":"stead(站立处)+y → 站得稳的 → 平稳的",
     "family":FAM("st/stead","站、位置",[W("stead","代替；位置"),W("instead","代替"),W("stable","稳定的")]),
     "mnemonic":"stead=站立处(和 instead 一家);立得稳、不晃不变的,就是 steady 平稳的;steadily 稳步地。",
     "forms":[F("steadily","adv.","稳步地")]}},
  {"word":"prior","phonetic":"ˈpraɪə","pos":"adj.","def":"在先的，先前的；优先的","cefr":"B2","freq_rank":70,
   "sentence_en":"No prior experience is needed.","sentence_zh":"无需任何先前经验。",
   "aids":{"morphemes":[M("prior","root","更前的(prius)")],
     "derivation":"拉丁 prior'更前的';时间/次序在前的 → 先前的、优先的",
     "family":FAM("prior/prim","在前、第一",[W("priority","优先"),W("primary","首要的"),W("prime","首要的")]),
     "mnemonic":"prior=更前(和 priority 优先一家);时间上更早的=先前的;次序上更前的=优先的;prior to=在…之前。",
     "forms":[F("priority","n.","优先")]}},
  {"word":"loose","phonetic":"luːs","pos":"adj.","def":"松的，宽松的；松散的；不精确的","cefr":"B1","freq_rank":69,
   "sentence_en":"The screw is loose.","sentence_zh":"螺丝松了。",
   "aids":{"morphemes":[M("loose","root","松开(古诺斯语 lauss)")],
     "derivation":"与 lose/release'松开'同源;未系紧的 → 松的",
     "family":FAM("los/loose","松开",[W("loosen","放松"),W("release","释放")]),
     "mnemonic":"loose=松(与 lose/release 一家,注意与 lose 拼写区分);没绷紧、不牢的,就是 loose;loosen 使松;反义 tight。",
     "forms":[F("loosen","v.","放松，松开")]}},
  {"word":"vessel","phonetic":"ˈvesl","pos":"n.","def":"船，舰；容器；血管，脉管","cefr":"B2","freq_rank":92,
   "sentence_en":"A large vessel entered the harbor.","sentence_zh":"一艘大船驶入港口。",
   "aids":{"morphemes":[M("vess","root","容器(vas)"),M("el","suffix","小")],
     "derivation":"拉丁 vas'容器';盛装/运载之物 → 容器、船;体内运血的管 → 血管",
     "family":FAM("vas/vess","容器",[W("vase","花瓶"),W("vascular","血管的")]),
     "mnemonic":"vess=容器(和 vase 花瓶一家);盛东西的器皿=容器;能'装'货运人的大器=船;体内血的'管'=血管(blood vessel)。",
     "forms":[F("vessels","n.","船；血管(复数)")]}},
  {"word":"flee","phonetic":"fliː","pos":"v.","def":"逃跑，逃离","cefr":"B2","freq_rank":93,
   "sentence_en":"They fled the country.","sentence_zh":"他们逃离了这个国家。",
   "aids":{"morphemes":[M("flee","root","逃(古英语 flēon)")],
     "derivation":"古英语'逃跑';与 flight(逃)同源",
     "family":FAM("fl","飞、逃",[W("flight","逃跑；飞行"),W("fly","飞")]),
     "mnemonic":"flee=逃(过去式 fled;和 flight 逃一家);为躲危险迅速逃离,就是 flee;别和 free(自由)混。",
     "forms":[F("fled","v.","过去式/过去分词")]}},
  {"word":"squeeze","phonetic":"skwiːz","pos":"v./n.","def":"挤，压榨；紧握；(经济)紧缩","cefr":"B2","freq_rank":72,
   "sentence_en":"Squeeze the lemon.","sentence_zh":"挤柠檬。",
   "aids":{"morphemes":[M("squeeze","root","挤压(拟态)")],
     "derivation":"拟态词'用力挤压';压出汁/塞进窄处 → 挤",
     "family":FAM("","相关词",[W("squeezing","挤压")]),
     "mnemonic":"squeeze=用力挤;挤柠檬出汁、往窄缝里塞、握紧手,都是 squeeze;credit squeeze 信贷紧缩。",
     "forms":[F("squeezed","v.","过去式/过去分词")]}},
  {"word":"split","phonetic":"splɪt","pos":"v./n.","def":"劈开，分裂；分担；裂缝","cefr":"B1","freq_rank":81,
   "sentence_en":"Let's split the bill.","sentence_zh":"我们分摊账单吧。",
   "aids":{"morphemes":[M("split","root","劈开(中古荷兰语 splitten)")],
     "derivation":"中古荷兰语'劈裂';使分开 → 劈开、分裂",
     "family":FAM("","相关词",[W("splitting","分裂的")]),
     "mnemonic":"split=劈开(过去式仍是 split);把整体劈成几份=分裂;把费用分开=分担(split the cost);split up 分手。",
     "forms":[F("splits","n.","分裂(复数)")]}},
  {"word":"owe","phonetic":"əʊ","pos":"v.","def":"欠(债)；归功于；应给予","cefr":"B1","freq_rank":103,
   "sentence_en":"You owe me ten dollars.","sentence_zh":"你欠我十美元。",
   "aids":{"morphemes":[M("owe","root","拥有，欠(古英语 āgan)")],
     "derivation":"古英语'拥有→有义务归还';该还未还 → 欠",
     "family":FAM("ow/own","有、欠",[W("own","拥有"),W("ought","应该")]),
     "mnemonic":"owe 与 own(拥有)/ought(应该)同源;该还给人的=欠(owe money);把成就'归'于某人=owe...to;owing to 由于。",
     "forms":[F("owed","v.","过去式/过去分词"),F("owing","adj.","未付的")]}},
  {"word":"besides","phonetic":"bɪˈsaɪdz","pos":"prep./adv.","def":"除…之外(还)；而且","cefr":"A2","freq_rank":116,
   "sentence_en":"Besides English, she speaks French.","sentence_zh":"除英语外，她还会说法语。",
   "aids":{"morphemes":[M("be","prefix","加强"),M("side","root","旁边"),M("s","suffix","副词后缀")],
     "derivation":"by+side'在旁边'→ 在…之外还有 → 除…之外",
     "family":FAM("side","旁边",[W("beside","在旁边"),W("aside","在一旁")]),
     "mnemonic":"be+side(旁边)+s;'在…旁边另有'=除…之外(还);注意 beside(无s)=在…旁边,besides(有s)=除…之外/而且。",
     "forms":[]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 17
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
