#!/usr/bin/env python
# 第十三批(收官补足到>=655,约35词):逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -pon/-pos 放
  {"word":"opponent","phonetic":"əˈpəʊnənt","pos":"n.","def":"对手，敌手；反对者","cefr":"B2","freq_rank":36,
   "sentence_en":"He defeated his opponent easily.","sentence_zh":"他轻松击败了对手。",
   "aids":{"morphemes":[M("op","prefix","对着(ob)"),M("pon","root","放置"),M("ent","suffix","…的人")],
     "derivation":"op(对着)+pon(放) → 站在对立面放着的人 → 对手",
     "family":FAM("pon/pos","放置",[W("oppose","反对"),W("component","部件"),W("postpone","推迟")]),
     "mnemonic":"pon=放(和 oppose 一家);被摆在你对(op-)面较量的人,就是 opponent 对手;反义 supporter 支持者。",
     "forms":[F("opponents","n.","对手(复数)")]}},
  # -form 形/告知
  {"word":"inform","phonetic":"ɪnˈfɔːm","pos":"v.","def":"通知，告知","cefr":"B1","freq_rank":35,
   "sentence_en":"Please inform me of any changes.","sentence_zh":"如有变动请通知我。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("form","root","形式，塑造")],
     "derivation":"in(向内)+form(塑造) → 在人心中塑造出信息 → 告知",
     "family":FAM("form","形式、塑造",[W("form","形式"),W("format","格式"),W("reform","改革"),W("transform","改变")]),
     "mnemonic":"form=塑造;把消息'塑'进对方脑中,就是 inform 通知;information 信息;informative 提供信息的。",
     "forms":[F("information","n.","信息"),F("informed","adj.","消息灵通的")]}},
  # -volu 意愿
  {"word":"volunteer","phonetic":"ˌvɒlənˈtɪə","pos":"n./v.","def":"志愿者；自愿(做)","cefr":"B1","freq_rank":40,
   "sentence_en":"She volunteers at the hospital.","sentence_zh":"她在医院做志愿者。",
   "aids":{"morphemes":[M("volunt","root","意愿(voluntas)"),M("eer","suffix","…的人")],
     "derivation":"volunt(意愿)+eer → 出于自己意愿做事的人 → 志愿者",
     "family":FAM("vol","意愿",[W("voluntary","自愿的"),W("volition","意志")]),
     "mnemonic":"volunt=意愿(想 voluntary 自愿的);凭自己心愿无偿出力的人,就是 volunteer;动词=自愿。",
     "forms":[F("voluntary","adj.","自愿的"),F("volunteers","n.","志愿者(复数)")]}},
  # -journ 日
  {"word":"journalist","phonetic":"ˈdʒɜːnəlɪst","pos":"n.","def":"记者，新闻工作者","cefr":"B1","freq_rank":31,
   "sentence_en":"The journalist interviewed the mayor.","sentence_zh":"记者采访了市长。",
   "aids":{"morphemes":[M("journ","root","日，天(jour)"),M("al","suffix","名词"),M("ist","suffix","…的人")],
     "derivation":"journ(日)+al+ist → 做'每日'报道的人 → 记者",
     "family":FAM("journ","日、天",[W("journal","日报；期刊"),W("journey","旅程(一天的路)")]),
     "mnemonic":"journ=日(法语 jour;想 journal 日报);每天追新闻写报道的人,就是 journalist 记者。",
     "forms":[F("journal","n.","期刊；日记"),F("journalism","n.","新闻业")]}},
  # 常见词(词根/联想)
  {"word":"complaint","phonetic":"kəmˈpleɪnt","pos":"n.","def":"抱怨，投诉；(病)不适","cefr":"B1","freq_rank":42,
   "sentence_en":"We received a complaint from a customer.","sentence_zh":"我们收到了一位顾客的投诉。",
   "aids":{"morphemes":[M("com","prefix","加强"),M("plaint","root","捶胸，悲叹")],
     "derivation":"complain(抱怨)+t → 抱怨的话/事 → 投诉",
     "family":FAM("plaint","捶胸、悲叹",[W("complain","抱怨"),W("plaintiff","原告")]),
     "mnemonic":"plaint=捶胸悲叹(和 complain 一家);正式说出的不满,就是 complaint 投诉;make a complaint 投诉。",
     "forms":[F("complain","v.","抱怨")]}},
  {"word":"poverty","phonetic":"ˈpɒvəti","pos":"n.","def":"贫穷，贫困；缺乏","cefr":"B1","freq_rank":43,
   "sentence_en":"Many families live in poverty.","sentence_zh":"许多家庭生活贫困。",
   "aids":{"morphemes":[M("pover","root","穷(pauper)"),M("ty","suffix","名词后缀")],
     "derivation":"与 poor/pauper'穷'同源;贫穷的状态 → 贫困",
     "family":FAM("pauper/pover","穷",[W("poor","贫穷的"),W("impoverish","使贫穷")]),
     "mnemonic":"pover 与 poor(穷)同源;缺钱少物的状态,就是 poverty 贫困;反义 wealth 财富。",
     "forms":[]}},
  {"word":"mood","phonetic":"muːd","pos":"n.","def":"心情，情绪；氛围","cefr":"A2","freq_rank":44,
   "sentence_en":"She is in a good mood today.","sentence_zh":"她今天心情很好。",
   "aids":{"morphemes":[M("mood","root","心境(古英语 mōd 心)")],
     "derivation":"古英语 mōd'心、勇气';一时的心境 → 心情",
     "family":FAM("","相关词",[W("moody","喜怒无常的")]),
     "mnemonic":"mood=心境;一时的情绪状态,就是 mood;in the mood for 有心情做;moody 喜怒无常的。",
     "forms":[F("moods","n.","情绪(复数)"),F("moody","adj.","喜怒无常的")]}},
  {"word":"fashion","phonetic":"ˈfæʃən","pos":"n./v.","def":"时尚，流行；方式；制作","cefr":"A2","freq_rank":25,
   "sentence_en":"That style is back in fashion.","sentence_zh":"那种款式又流行起来了。",
   "aids":{"morphemes":[M("fash","root","做，形(fact/facon)"),M("ion","suffix","名词后缀")],
     "derivation":"与 fact/facon'做、样式'同源;当下被'做'成主流的样式 → 时尚",
     "family":FAM("fact/fash","做、形",[W("fashionable","时髦的")]),
     "mnemonic":"fash≈做/样式(fact 家族);当下大家追捧的样式,就是 fashion 时尚;in a...fashion=以…方式;fashionable 时髦的。",
     "forms":[F("fashionable","adj.","时髦的")]}},
  {"word":"slide","phonetic":"slaɪd","pos":"v./n.","def":"滑动，下滑；滑梯；幻灯片","cefr":"B1","freq_rank":34,
   "sentence_en":"The kids slid down the hill.","sentence_zh":"孩子们从山坡上滑下来。",
   "aids":{"morphemes":[M("slide","root","滑(古英语 slīdan)")],
     "derivation":"古英语'平滑移动';顺表面溜移 → 滑动;演示用的'滑'入画面=幻灯片",
     "family":FAM("sl","滑",[W("slip","滑倒"),W("slippery","滑的")]),
     "mnemonic":"slide=滑(过去式 slid);顺着面溜=滑动;数值下滑=slide;孩子的滑梯;PPT 一张=slide 幻灯片。",
     "forms":[F("slid","v.","过去式/过去分词"),F("slides","n.","幻灯片(复数)")]}},
  {"word":"pack","phonetic":"pæk","pos":"v./n.","def":"打包，装；一包，一群","cefr":"A2","freq_rank":38,
   "sentence_en":"I need to pack for the trip.","sentence_zh":"我得为旅行打包。",
   "aids":{"morphemes":[M("pack","root","包，捆(中古荷兰语 pak)")],
     "derivation":"中古荷兰语'包裹';把东西塞进包 → 打包",
     "family":FAM("pack","包、捆",[W("package","包裹"),W("packet","小包")]),
     "mnemonic":"pack=包;把行李装进箱=打包;一整包=a pack of;一群狼=a pack of wolves;package 包裹。",
     "forms":[F("packed","adj.","挤满的"),F("package","n.","包裹")]}},
  {"word":"cap","phonetic":"kæp","pos":"n./v.","def":"帽子；盖子；上限，封顶","cefr":"A2","freq_rank":41,
   "sentence_en":"He wore a baseball cap.","sentence_zh":"他戴着一顶棒球帽。",
   "aids":{"morphemes":[M("cap","root","头(caput)")],
     "derivation":"拉丁 caput'头';戴头上的/盖顶上的 → 帽子、盖子;设个'顶' → 上限",
     "family":FAM("cap/capit","头",[W("capital","首都"),W("captain","队长"),W("cape","披肩")]),
     "mnemonic":"cap=头(caput);扣头上的=帽子;盖瓶口的=盖子;给费用设个'顶'=封顶(price cap 限价)。",
     "forms":[F("caps","n.","帽子(复数)"),F("capped","v.","过去式/过去分词")]}},
  {"word":"iron","phonetic":"ˈaɪən","pos":"n./v.","def":"铁；熨斗；熨烫","cefr":"A2","freq_rank":39,
   "sentence_en":"The gate is made of iron.","sentence_zh":"这扇门是铁做的。",
   "aids":{"morphemes":[M("iron","root","铁(古英语 īsern)")],
     "derivation":"古英语'铁';金属铁 → 铁;用热铁压平衣服 → 熨斗、熨烫",
     "family":FAM("","相关词",[W("ironic","讽刺的(另源)")]),
     "mnemonic":"iron=铁(注意 r 不明显读 /ˈaɪən/);金属铁;拿热铁块压衣=熨斗/熨烫;意志坚如铁=iron will。",
     "forms":[F("ironing","n.","熨烫的衣物")]}},
  {"word":"alcohol","phonetic":"ˈælkəhɒl","pos":"n.","def":"酒精，酒","cefr":"A2","freq_rank":37,
   "sentence_en":"He doesn't drink alcohol.","sentence_zh":"他不喝酒。",
   "aids":{"morphemes":[M("al","prefix","阿拉伯语冠词 the"),M("cohol","root","细粉，精")],
     "derivation":"阿拉伯语 al-kuḥl'精细之物';后指蒸馏出的'酒精' → 酒精",
     "family":FAM("","相关词",[W("alcoholic","含酒精的；酒鬼")]),
     "mnemonic":"来自阿拉伯语'精提之物';酒里让人醉的成分,就是 alcohol 酒精;alcoholic 含酒精的/酒鬼。",
     "forms":[F("alcoholic","adj.","含酒精的")]}},
  {"word":"scream","phonetic":"skriːm","pos":"v./n.","def":"尖叫，喊叫","cefr":"B1","freq_rank":32,
   "sentence_en":"She screamed in fright.","sentence_zh":"她吓得尖叫。",
   "aids":{"morphemes":[M("scream","root","尖叫(中古英语 scremen)")],
     "derivation":"拟声词'尖锐喊叫' → 尖叫",
     "family":FAM("","相关词",[W("screaming","尖叫的")]),
     "mnemonic":"scream 是拟声——又尖又高地喊,就是 scream 尖叫;和 scratch/screech 一类刺耳词一起记。",
     "forms":[F("screamed","v.","过去式/过去分词"),F("screams","n.","尖叫(复数)")]}},
  {"word":"stare","phonetic":"steə","pos":"v./n.","def":"凝视，盯着看","cefr":"B1","freq_rank":12,
   "sentence_en":"Don't stare at people.","sentence_zh":"不要盯着别人看。",
   "aids":{"morphemes":[M("stare","root","瞪视(古英语 starian)")],
     "derivation":"古英语'睁大眼看';目不转睛地看 → 凝视",
     "family":FAM("","相关词",[W("staring","凝视的")]),
     "mnemonic":"stare=瞪视;睁大眼、一动不动地盯,就是 stare;stare at 盯着看(常含无礼/惊讶)。",
     "forms":[F("stared","v.","过去式/过去分词")]}},
  {"word":"hide","phonetic":"haɪd","pos":"v.","def":"隐藏，躲藏；隐瞒","cefr":"A2","freq_rank":13,
   "sentence_en":"The cat hid under the bed.","sentence_zh":"猫躲在床底下。",
   "aids":{"morphemes":[M("hide","root","藏(古英语 hȳdan)")],
     "derivation":"古英语'遮盖、藏起' → 隐藏",
     "family":FAM("","相关词",[W("hidden","隐藏的"),W("hideout","藏身处")]),
     "mnemonic":"hide=藏(过去式 hid,过去分词 hidden);把东西/自己藏起不让看见,就是 hide;hide-and-seek 捉迷藏。",
     "forms":[F("hidden","adj.","隐藏的"),F("hid","v.","过去式")]}},
  {"word":"grab","phonetic":"ɡræb","pos":"v./n.","def":"抓住，攫取；抢","cefr":"B1","freq_rank":18,
   "sentence_en":"He grabbed my arm.","sentence_zh":"他抓住了我的胳膊。",
   "aids":{"morphemes":[M("grab","root","抓(中古低地德语 grabben)")],
     "derivation":"拟态'一把抓住';迅猛抓取 → 抓住、抢",
     "family":FAM("grab/grasp","抓",[W("grasp","抓牢；领会"),W("grip","紧握")]),
     "mnemonic":"grab=一把抓;猛地抓住/抢过来,就是 grab;grab a bite 随便吃点;和 grasp/grip 一族。",
     "forms":[F("grabbed","v.","过去式/过去分词")]}},
  {"word":"hang","phonetic":"hæŋ","pos":"v.","def":"悬挂，垂下；绞死","cefr":"A2","freq_rank":7,
   "sentence_en":"Hang your coat on the hook.","sentence_zh":"把外套挂在钩子上。",
   "aids":{"morphemes":[M("hang","root","悬挂(古英语 hangian)")],
     "derivation":"古英语'吊、垂' → 悬挂",
     "family":FAM("","相关词",[W("hanger","衣架"),W("hangover","宿醉")]),
     "mnemonic":"hang=挂(过去式 hung;表'绞死'时用 hanged);把东西吊起=悬挂;hang out 闲逛;hang on 稍等/坚持。",
     "forms":[F("hung","v.","过去式/过去分词"),F("hanger","n.","衣架")]}},
  {"word":"spring","phonetic":"sprɪŋ","pos":"n./v.","def":"春天；弹簧；泉；跳跃","cefr":"A1","freq_rank":8,
   "sentence_en":"Flowers bloom in spring.","sentence_zh":"春天花开。",
   "aids":{"morphemes":[M("spring","root","跳起，涌出(古英语 springan)")],
     "derivation":"古英语'跃起、涌出';万物萌发的季节=春;蹦跳=跳跃;水涌出=泉;能弹跳=弹簧",
     "family":FAM("","相关词",[W("springboard","跳板"),W("offspring","后代")]),
     "mnemonic":"spring 核心义'跃出、涌出':万物迸发=春天;猛地跃起=跳跃;水往上涌=泉;能回弹=弹簧。",
     "forms":[F("sprang","v.","过去式"),F("springs","n.","泉(复数)")]}},
  {"word":"bar","phonetic":"bɑː","pos":"n./v.","def":"条，棒；酒吧；栏杆；阻挡","cefr":"A2","freq_rank":10,
   "sentence_en":"Chocolate comes in a bar.","sentence_zh":"巧克力做成条状。",
   "aids":{"morphemes":[M("bar","root","横木，栅(古法语 barre)")],
     "derivation":"古法语'横木、栅';长条的木/金属 → 条、栏杆;拦路的横木 → 阻挡;柜台=酒吧",
     "family":FAM("bar","横木、栅",[W("barrier","屏障"),W("barrel","桶"),W("embarrass","使尴尬(设障)")]),
     "mnemonic":"bar=横木/长条;巧克力'条'=a bar;拦路横木=栏杆/阻挡(bar sb from);卖酒的长柜台=酒吧。",
     "forms":[F("bars","n.","条(复数)"),F("barred","v.","过去式/过去分词")]}},
  {"word":"band","phonetic":"bænd","pos":"n./v.","def":"乐队；带子，条带；一群；联合","cefr":"A2","freq_rank":14,
   "sentence_en":"She plays in a rock band.","sentence_zh":"她在一支摇滚乐队里演奏。",
   "aids":{"morphemes":[M("band","root","捆绑，带(bind)")],
     "derivation":"与 bind'捆'同源;绑成一束/一伙 → 乐队、一群;条状物 → 带子",
     "family":FAM("band/bind","捆、带",[W("bind","捆绑"),W("bond","纽带"),W("bundle","捆")]),
     "mnemonic":"band 与 bind(捆)同源;绑成一伙合奏的人=乐队;绑扎的条=带子;一帮人=a band of;bandage 绷带。",
     "forms":[F("bands","n.","乐队(复数)")]}},
  {"word":"flight","phonetic":"flaɪt","pos":"n.","def":"飞行；航班；逃跑；一段(楼梯)","cefr":"A2","freq_rank":15,
   "sentence_en":"Our flight leaves at noon.","sentence_zh":"我们的航班中午起飞。",
   "aids":{"morphemes":[M("fl","root","飞(fly)"),M("ight","suffix","名词后缀")],
     "derivation":"与 fly'飞'同源;飞行/一趟飞=航班;'飞'着逃=逃跑",
     "family":FAM("fl","飞、流",[W("fly","飞"),W("flee","逃跑")]),
     "mnemonic":"与 fly(飞)一家;飞行/一趟班机=flight;仓皇'飞'逃=flight(fight or flight 战或逃);一段楼梯=a flight of stairs。",
     "forms":[F("flights","n.","航班(复数)")]}},
  {"word":"feed","phonetic":"fiːd","pos":"v.","def":"喂养，饲养；提供","cefr":"A2","freq_rank":16,
   "sentence_en":"She feeds the birds every morning.","sentence_zh":"她每天早上喂鸟。",
   "aids":{"morphemes":[M("feed","root","喂(与 food 同源)")],
     "derivation":"与 food'食物'同源;给食物 → 喂养",
     "family":FAM("food/feed","食",[W("food","食物"),W("fed","喂(过去式)")]),
     "mnemonic":"feed 与 food(食物)同源;给东西吃=喂养(过去式 fed);给机器/数据'喂'料=feed;news feed 信息流。",
     "forms":[F("fed","v.","过去式/过去分词"),F("feeding","n.","喂养")]}},
  {"word":"committee","phonetic":"kəˈmɪti","pos":"n.","def":"委员会","cefr":"B1","freq_rank":17,
   "sentence_en":"The committee will meet on Friday.","sentence_zh":"委员会将于周五开会。",
   "aids":{"morphemes":[M("commit","root","委托，交付"),M("tee","suffix","被…的一群人")],
     "derivation":"commit(委托)+ee → 被委以职责的一群人 → 委员会",
     "family":FAM("mit/miss","送、交付",[W("commit","委托；投入"),W("mission","任务"),W("submit","提交")]),
     "mnemonic":"commit(委托)+-tee(受托者);被托付办事的一群人,就是 committee 委员会(注意 m-t-t-e 双写)。",
     "forms":[F("committees","n.","委员会(复数)")]}},
  {"word":"mass","phonetic":"mæs","pos":"n./adj.","def":"大量，团块；质量；大众的","cefr":"B1","freq_rank":27,
   "sentence_en":"A mass of people gathered.","sentence_zh":"一大群人聚集起来。",
   "aids":{"morphemes":[M("mass","root","团，块(massa)")],
     "derivation":"希腊 maza'面团';揉成的一大团 → 团块、大量;物理'质量'",
     "family":FAM("mass","团、块",[W("massive","巨大的"),W("massacre","大屠杀")]),
     "mnemonic":"mass=一大团;成堆的量=大量/团块;物理里物体的'质量';mass media 大众媒体;the masses 民众。",
     "forms":[F("masses","n.","民众；大量(复数)")]}},
  {"word":"lower","phonetic":"ˈləʊə","pos":"adj./v.","def":"较低的，下方的；放低，降低","cefr":"A2","freq_rank":29,
   "sentence_en":"Please lower your voice.","sentence_zh":"请把声音放低。",
   "aids":{"morphemes":[M("low","root","低"),M("er","suffix","更…/使…")],
     "derivation":"low(低)的比较级/动词 → 较低的;使变低 → 降低",
     "family":FAM("low","低",[W("low","低的"),W("below","在下面")]),
     "mnemonic":"low(低)的比较级;更靠下的=lower 较低的;把某物往下放=lower 降低;反义 raise/higher。",
     "forms":[F("lowered","v.","过去式/过去分词")]}},
  {"word":"surgery","phonetic":"ˈsɜːdʒəri","pos":"n.","def":"外科手术；诊室","cefr":"B1","freq_rank":24,
   "sentence_en":"She had heart surgery.","sentence_zh":"她做了心脏手术。",
   "aids":{"morphemes":[M("sur","root","手(cheir)"),M("gery","root","做，工(erg)")],
     "derivation":"希腊 kheirourgia'手工操作';用手施术 → 外科手术",
     "family":FAM("erg/urg","做、工",[W("energy","能量"),W("surgeon","外科医生")]),
     "mnemonic":"源自'手(sur=cheir)+做(gery=erg)工'——动手在身体上操作,就是 surgery 手术;surgeon 外科医生。",
     "forms":[F("surgeon","n.","外科医生"),F("surgical","adj.","外科的")]}},
  {"word":"abuse","phonetic":"əˈbjuːs","pos":"n./v.","def":"滥用；虐待；辱骂","cefr":"B2","freq_rank":19,
   "sentence_en":"Drug abuse is a serious problem.","sentence_zh":"滥用药物是个严重问题。",
   "aids":{"morphemes":[M("ab","prefix","偏离，坏"),M("use","root","使用")],
     "derivation":"ab(偏离)+use(用) → 用歪、错用 → 滥用;错待人 → 虐待",
     "family":FAM("us/ut","使用",[W("use","使用"),W("useful","有用的"),W("utility","效用")]),
     "mnemonic":"ab-(偏坏)+use(用)——把东西用歪=滥用;把人'用坏'=虐待;用恶语=辱骂,都是 abuse。",
     "forms":[F("abused","v.","过去式/过去分词"),F("abusive","adj.","辱骂的；虐待的")]}},
  {"word":"athlete","phonetic":"ˈæθliːt","pos":"n.","def":"运动员","cefr":"A2","freq_rank":20,
   "sentence_en":"She is a professional athlete.","sentence_zh":"她是职业运动员。",
   "aids":{"morphemes":[M("athl","root","竞赛，奖(athlon)"),M("ete","suffix","…的人")],
     "derivation":"希腊 athlon'竞赛、奖品';参加竞技的人 → 运动员",
     "family":FAM("athl","竞赛",[W("athletic","运动的"),W("decathlon","十项全能")]),
     "mnemonic":"athl=竞赛(想 decathlon 十项全能);为奖竞技的人,就是 athlete 运动员;athletic 体育的。",
     "forms":[F("athletic","adj.","运动的"),F("athletes","n.","运动员(复数)")]}},
  {"word":"campus","phonetic":"ˈkæmpəs","pos":"n.","def":"校园","cefr":"B1","freq_rank":30,
   "sentence_en":"The library is on campus.","sentence_zh":"图书馆在校园里。",
   "aids":{"morphemes":[M("camp","root","田野，场地"),M("us","suffix","名词后缀")],
     "derivation":"拉丁 campus'田野、场地';大学那片场地 → 校园",
     "family":FAM("camp","田野、场地",[W("camp","营地"),W("campaign","战役")]),
     "mnemonic":"camp=场地(想 camp 营地);大学的那片场地园区,就是 campus 校园;on campus 在校内。",
     "forms":[F("campuses","n.","校园(复数)")]}},
  {"word":"cable","phonetic":"ˈkeɪbl","pos":"n.","def":"缆绳，电缆；有线电视","cefr":"B1","freq_rank":28,
   "sentence_en":"The bridge is held up by steel cables.","sentence_zh":"这座桥由钢缆支撑。",
   "aids":{"morphemes":[M("cabl","root","粗绳(capulum)"),M("e","suffix","结尾")],
     "derivation":"拉丁 capulum'套索';粗壮的绳/线 → 缆绳、电缆",
     "family":FAM("","相关词",[W("cabling","布线")]),
     "mnemonic":"cable=粗缆;拴船的粗绳、输电的电缆,都是 cable;经电缆传的电视=有线电视(cable TV)。",
     "forms":[F("cables","n.","电缆(复数)")]}},
  {"word":"poll","phonetic":"pəʊl","pos":"n./v.","def":"民意调查；投票；(pl.)投票站","cefr":"B2","freq_rank":21,
   "sentence_en":"The poll showed strong support.","sentence_zh":"民调显示支持率很高。",
   "aids":{"morphemes":[M("poll","root","头，人头(中古荷兰语 pol)")],
     "derivation":"本义'头';古时按'人头'计票 → 投票、民调",
     "family":FAM("","相关词",[W("pollster","民调人员")]),
     "mnemonic":"poll 本义'人头';数人头表决=投票;抽样问人意见=民意调查;go to the polls 去投票。",
     "forms":[F("polls","n.","民调；投票站(复数)"),F("polled","v.","过去式/过去分词")]}},
  {"word":"setting","phonetic":"ˈsetɪŋ","pos":"n.","def":"环境，背景；(仪器)设置","cefr":"B1","freq_rank":22,
   "sentence_en":"The story has a rural setting.","sentence_zh":"这个故事以乡村为背景。",
   "aids":{"morphemes":[M("set","root","放置"),M("ting","suffix","名词后缀")],
     "derivation":"set(放置)+ing → 事物所处/被设定的状态 → 环境、设置",
     "family":FAM("set","放置",[W("set","放置"),W("settle","安顿"),W("sunset","日落")]),
     "mnemonic":"set=放;人事被'放置'的周遭=环境/背景;把参数'设'好=设置(settings 设置菜单)。",
     "forms":[F("settings","n.","设置(复数)")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 13
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
