#!/usr/bin/env python
# 第十八批(约50词):逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -riv 河/流
  {"word":"derive","phonetic":"dɪˈraɪv","pos":"v.","def":"取得，得到；源自，衍生","cefr":"B2","freq_rank":89,
   "sentence_en":"The word derives from Latin.","sentence_zh":"这个词源自拉丁语。",
   "aids":{"morphemes":[M("de","prefix","从，向下"),M("rive","root","河，流(riv)")],
     "derivation":"de(从)+rive(河) → 从源头引出水流 → 源自、衍生",
     "family":FAM("riv","河、流",[W("river","河"),W("rival","对手(争同一河)"),W("arrive","到达")]),
     "mnemonic":"rive=河(想 river);像从大河引水一样从源头引出,就是 derive 源自、衍生;derive from=来自。",
     "forms":[F("derivation","n.","衍生；词源"),F("derived","v.","过去式/过去分词")]}},
  # -press 压
  {"word":"impress","phonetic":"ɪmˈpres","pos":"v.","def":"使印象深刻，给…深刻印象","cefr":"B1","freq_rank":91,
   "sentence_en":"Her speech impressed everyone.","sentence_zh":"她的演讲让每个人印象深刻。",
   "aids":{"morphemes":[M("im","prefix","向内"),M("press","root","压")],
     "derivation":"im(向内)+press(压) → 往人心里压印 → 使印象深刻",
     "family":FAM("press","压",[W("pressure","压力"),W("express","表达"),W("depress","使沮丧"),W("compress","压缩")]),
     "mnemonic":"press=压;在人心里(im-)压下深深一印,就是 impress;impression 印象;impressive 令人印象深刻的。",
     "forms":[F("impression","n.","印象"),F("impressive","adj.","令人印象深刻的")]}},
  # -sembl 相同
  {"word":"resemble","phonetic":"rɪˈzembl","pos":"v.","def":"像，与…相似","cefr":"B2","freq_rank":92,
   "sentence_en":"She resembles her mother.","sentence_zh":"她长得像她妈妈。",
   "aids":{"morphemes":[M("re","prefix","加强"),M("sembl","root","相同，一起(simil)")],
     "derivation":"re+sembl(相同) → 显出相同 → 相似",
     "family":FAM("sembl/simil","相同、类似",[W("similar","相似的"),W("assemble","集合"),W("simultaneous","同时的")]),
     "mnemonic":"sembl=相同(和 similar 一家);外貌/性质雷同,就是 resemble 像;resemblance 相似。",
     "forms":[F("resemblance","n.","相似")]}},
  # -port 部分
  {"word":"proportion","phonetic":"prəˈpɔːʃən","pos":"n.","def":"比例，比率；部分；均衡","cefr":"B2","freq_rank":94,
   "sentence_en":"A large proportion of students passed.","sentence_zh":"很大一部分学生通过了。",
   "aids":{"morphemes":[M("pro","prefix","按照"),M("port","root","部分，分")],
     "derivation":"pro(按照)+port(部分) → 各部分的对应份额 → 比例",
     "family":FAM("part/port","部分",[W("portion","部分"),W("part","部分"),W("partial","部分的")]),
     "mnemonic":"port=部分(和 portion 一家);各部分之间的对应份额,就是 proportion 比例;in proportion to 与…成比例。",
     "forms":[F("proportional","adj.","成比例的")]}},
  # -vinc 征服
  {"word":"conviction","phonetic":"kənˈvɪkʃən","pos":"n.","def":"坚信，信念；定罪","cefr":"C1","freq_rank":96,
   "sentence_en":"She spoke with conviction.","sentence_zh":"她说话充满信念。",
   "aids":{"morphemes":[M("con","prefix","完全"),M("vict","root","征服"),M("ion","suffix","名词后缀")],
     "derivation":"convince(完全说服)/convict(定罪)+ion → 被彻底说服的坚信;被判有罪 → 定罪",
     "family":FAM("vinc/vict","征服",[W("convince","说服"),W("victory","胜利"),W("convict","定罪")]),
     "mnemonic":"vict=征服(和 convince/victory 一家);被道理彻底征服后的坚信=信念;被证据征服而'定罪'=定罪,都是 conviction。",
     "forms":[F("convince","v.","说服"),F("convict","v.","定罪")]}},
  # -strong 强
  {"word":"strengthen","phonetic":"ˈstreŋθn","pos":"v.","def":"加强，增强；使更坚固","cefr":"B1","freq_rank":100,
   "sentence_en":"Exercise strengthens muscles.","sentence_zh":"锻炼能增强肌肉。",
   "aids":{"morphemes":[M("strength","root","力量(strong)"),M("en","suffix","使…")],
     "derivation":"strength(力量)+en → 使有力量 → 加强",
     "family":FAM("strong/string","强、拉紧",[W("strong","强壮的"),W("strength","力量"),W("string","弦")]),
     "mnemonic":"strength=力量(strong 的名词)+en(使);使更有力、更牢,就是 strengthen 加强;反义 weaken 削弱。",
     "forms":[F("strength","n.","力量"),F("strengthened","v.","过去式/过去分词")]}},
  # -sorb 吸
  {"word":"absorb","phonetic":"əbˈsɔːb","pos":"v.","def":"吸收；使全神贯注；理解","cefr":"B2","freq_rank":119,
   "sentence_en":"Plants absorb water through their roots.","sentence_zh":"植物通过根部吸收水分。",
   "aids":{"morphemes":[M("ab","prefix","离开，从"),M("sorb","root","吸")],
     "derivation":"ab(从)+sorb(吸) → 从外部吸进来 → 吸收",
     "family":FAM("sorb","吸",[W("absorption","吸收"),W("resorb","再吸收")]),
     "mnemonic":"sorb=吸;把水分/知识从外(ab-)吸进来,就是 absorb 吸收;被某事'吸'住=全神贯注(absorbed in)。",
     "forms":[F("absorption","n.","吸收"),F("absorbed","adj.","专注的")]}},
  # -prin 第一
  {"word":"principal","phonetic":"ˈprɪnsəpl","pos":"n./adj.","def":"校长；本金；主要的","cefr":"B2","freq_rank":120,
   "sentence_en":"The school principal gave a speech.","sentence_zh":"校长发表了讲话。",
   "aids":{"morphemes":[M("prin","root","第一，首(prim)"),M("cipal","suffix","…的")],
     "derivation":"prin(第一)+cipal → 排第一位的(人/物) → 主要的、校长",
     "family":FAM("prim/prin","第一、首",[W("primary","首要的"),W("prince","王子"),W("principle","原则")]),
     "mnemonic":"prin=第一(和 prince 一家);排头位的人=校长/负责人;排头的钱=本金;主要的=principal;别和 principle(原则)混。",
     "forms":[F("principally","adv.","主要地")]}},
  # -strict 拉紧
  {"word":"restriction","phonetic":"rɪˈstrɪkʃən","pos":"n.","def":"限制，约束","cefr":"B2","freq_rank":121,
   "sentence_en":"There are restrictions on parking.","sentence_zh":"停车有限制。",
   "aids":{"morphemes":[M("re","prefix","回，加强"),M("strict","root","拉紧"),M("ion","suffix","名词后缀")],
     "derivation":"restrict(拉紧、卡住)+ion → 限制的规定 → 限制",
     "family":FAM("strict/string","拉紧",[W("strict","严格的"),W("restrict","限制"),W("string","线"),W("district","地区")]),
     "mnemonic":"strict=拉紧(和 restrict 一家);把范围拉紧卡住的规定,就是 restriction 限制;动词 restrict。",
     "forms":[F("restrict","v.","限制")]}},
  # -sequ 跟随
  {"word":"sequence","phonetic":"ˈsiːkwəns","pos":"n.","def":"顺序，次序；一系列，连续","cefr":"B2","freq_rank":125,
   "sentence_en":"Follow the steps in sequence.","sentence_zh":"按顺序执行这些步骤。",
   "aids":{"morphemes":[M("sequ","root","跟随"),M("ence","suffix","名词后缀")],
     "derivation":"sequ(跟随)+ence → 一个接一个跟着 → 顺序、连续",
     "family":FAM("sequ/secut","跟随",[W("consequence","后果"),W("subsequent","随后的"),W("consecutive","连续的")]),
     "mnemonic":"sequ=跟随(和 consequence 一家);一个紧跟一个排列,就是 sequence 顺序、序列;in sequence 依次。",
     "forms":[F("sequences","n.","序列(复数)")]}},
  # -sume 拿
  {"word":"consumption","phonetic":"kənˈsʌmpʃən","pos":"n.","def":"消费，消耗(量)","cefr":"B2","freq_rank":126,
   "sentence_en":"Energy consumption has risen.","sentence_zh":"能源消耗上升了。",
   "aids":{"morphemes":[M("con","prefix","完全"),M("sumpt","root","拿，取(sume)"),M("ion","suffix","名词后缀")],
     "derivation":"consume(完全用掉)+ion → 用掉的量 → 消耗、消费",
     "family":FAM("sume/sumpt","拿、取",[W("consume","消耗"),W("assume","假定"),W("resume","恢复")]),
     "mnemonic":"sumpt=拿/用(和 consume 一家);把东西完全用掉的量,就是 consumption 消费、消耗;动词 consume。",
     "forms":[F("consume","v.","消耗")]}},
  # -ser 连接
  {"word":"assert","phonetic":"əˈsɜːt","pos":"v.","def":"断言，声称；维护(权利)","cefr":"C1","freq_rank":127,
   "sentence_en":"He asserted that he was innocent.","sentence_zh":"他坚称自己是清白的。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sert","root","连接，加入(ser)")],
     "derivation":"as(朝向)+sert(连接、放置) → 把主张摆出来 → 断言",
     "family":FAM("sert","连接、加入",[W("insert","插入"),W("series","系列"),W("desert","抛弃")]),
     "mnemonic":"sert=放/连(想 insert 插入);把观点亮出来、硬性主张,就是 assert 断言;assert oneself 维护自己权利;assertion 断言。",
     "forms":[F("assertion","n.","断言"),F("assertive","adj.","坚定自信的")]}},
  # -tempor 时间
  {"word":"temporary","phonetic":"ˈtempərəri","pos":"adj.","def":"暂时的，临时的","cefr":"B1","freq_rank":130,
   "sentence_en":"This is only a temporary solution.","sentence_zh":"这只是权宜之计。",
   "aids":{"morphemes":[M("tempor","root","时间"),M("ary","suffix","…的")],
     "derivation":"tempor(时间)+ary → 只维持一段时间的 → 暂时的",
     "family":FAM("tempor","时间",[W("temporal","时间的"),W("contemporary","当代的"),W("tempo","节奏")]),
     "mnemonic":"tempor=时间(和 contemporary 一家);只在一段时间内的,就是 temporary 暂时的;反义 permanent 永久的;temporarily 暂时地。",
     "forms":[F("temporarily","adv.","暂时地")]}},
  # -fic 做
  {"word":"sufficient","phonetic":"səˈfɪʃnt","pos":"adj.","def":"足够的，充足的","cefr":"B2","freq_rank":109,
   "sentence_en":"We have sufficient food for a week.","sentence_zh":"我们有足够一周吃的食物。",
   "aids":{"morphemes":[M("suf","prefix","在下，向上补(sub)"),M("fic","root","做"),M("ient","suffix","…的")],
     "derivation":"suf(向上补)+fic(做) → 做得够填满需求的 → 足够的",
     "family":FAM("fic/fac","做、造",[W("efficient","高效的"),W("effect","效果"),W("factory","工厂")]),
     "mnemonic":"fic=做(和 efficient 一家);做得/备得够用的,就是 sufficient 足够的;反义 insufficient;sufficiency 充足。",
     "forms":[F("sufficiently","adv.","充分地"),F("insufficient","adj.","不足的")]}},
  {"word":"efficiency","phonetic":"ɪˈfɪʃnsi","pos":"n.","def":"效率，效能","cefr":"B2","freq_rank":87,
   "sentence_en":"We need to improve efficiency.","sentence_zh":"我们需要提高效率。",
   "aids":{"morphemes":[M("ef","prefix","向外(ex)"),M("fic","root","做"),M("iency","suffix","名词后缀")],
     "derivation":"efficient(高效的)的名词 → 少投入多产出的程度 → 效率",
     "family":FAM("fic/fac","做、造",[W("efficient","高效的"),W("effect","效果"),W("sufficient","足够的")]),
     "mnemonic":"fic=做(和 efficient 一家);单位投入的产出程度,就是 efficiency 效率;energy efficiency 能效。",
     "forms":[F("efficient","adj.","高效的")]}},
  # -plaud 鼓掌/炸
  {"word":"explode","phonetic":"ɪkˈspləʊd","pos":"v.","def":"爆炸，爆发；激增","cefr":"B1","freq_rank":112,
   "sentence_en":"The bomb exploded.","sentence_zh":"炸弹爆炸了。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("plode","root","鼓掌，拍(plaud)")],
     "derivation":"ex(向外)+plode(拍、轰) → 向外猛地轰响 → 爆炸",
     "family":FAM("plaud/plod","拍、鼓掌",[W("applaud","鼓掌"),W("plausible","貌似可信的")]),
     "mnemonic":"plode=轰响(和 applaud 拍手一家);能量向外(ex-)猛地轰出来,就是 explode 爆炸;explosion 爆炸;数量'炸'开=激增。",
     "forms":[F("explosion","n.","爆炸"),F("explosive","adj.","爆炸性的")]}},
  # -scop 看
  {"word":"scope","phonetic":"skəʊp","pos":"n.","def":"范围，余地；机会","cefr":"B2","freq_rank":113,
   "sentence_en":"That's beyond the scope of this book.","sentence_zh":"那超出了本书的范围。",
   "aids":{"morphemes":[M("scop","root","看，观察"),M("e","suffix","结尾")],
     "derivation":"scop(看)→ 视野所及的范围 → 范围",
     "family":FAM("scop","看",[W("telescope","望远镜"),W("microscope","显微镜"),W("scope","范围")]),
     "mnemonic":"scop=看(想 telescope 望远镜);目力/能力所及的范围,就是 scope;发挥的余地/机会(scope for improvement)。",
     "forms":[F("scopes","n.","范围(复数)")]}},
  # -cur 关心
  {"word":"curious","phonetic":"ˈkjʊəriəs","pos":"adj.","def":"好奇的，求知的；奇怪的","cefr":"A2","freq_rank":115,
   "sentence_en":"Children are naturally curious.","sentence_zh":"孩子天生好奇。",
   "aids":{"morphemes":[M("cur","root","关心，在意(cura)"),M("ious","suffix","…的")],
     "derivation":"cur(在意)+ious → 对事事都上心想知道的 → 好奇的",
     "family":FAM("cur","关心、在意",[W("cure","治愈"),W("secure","安全的"),W("accurate","准确的")]),
     "mnemonic":"cur=在意(和 care 一家);凡事都上心、想弄明白,就是 curious 好奇的;curiosity 好奇心。",
     "forms":[F("curiosity","n.","好奇心"),F("curiously","adv.","好奇地")]}},
  # -mount 山
  {"word":"mount","phonetic":"maʊnt","pos":"v./n.","def":"登上，骑上；增加；安装；山","cefr":"B2","freq_rank":79,
   "sentence_en":"Tension is mounting.","sentence_zh":"紧张气氛在加剧。",
   "aids":{"morphemes":[M("mount","root","山，登(mons)")],
     "derivation":"拉丁 mons'山';往山上爬 → 登上;像堆山一样往上堆 → 增加",
     "family":FAM("mount","山、登",[W("mountain","山"),W("amount","数量"),W("surmount","克服")]),
     "mnemonic":"mount=山/往上(想 mountain);爬上=登上;骑上马=mount;像堆山越堆越高=增加(mounting pressure);把设备架起=安装。",
     "forms":[F("mounted","v.","过去式/过去分词"),F("mounting","adj.","不断增加的")]}},
  # 高频名词/动词(常见/词根)
  {"word":"maintenance","phonetic":"ˈmeɪntənəns","pos":"n.","def":"维护，保养；维持；抚养费","cefr":"B2","freq_rank":97,
   "sentence_en":"The car needs regular maintenance.","sentence_zh":"这辆车需要定期保养。",
   "aids":{"morphemes":[M("main","root","手(manu)"),M("ten","root","持"),M("ance","suffix","名词后缀")],
     "derivation":"maintain(用手持续把住)的名词 → 维护、保养",
     "family":FAM("tain/ten","拿、持",[W("maintain","维持"),W("contain","包含"),W("retain","保留")]),
     "mnemonic":"和 maintain(维持)一家(main 手 + ten 持);使保持良好状态的养护,就是 maintenance;车辆/系统维护。",
     "forms":[F("maintain","v.","维持")]}},
  {"word":"privacy","phonetic":"ˈprɪvəsi","pos":"n.","def":"隐私，私密；独处","cefr":"B2","freq_rank":93,
   "sentence_en":"Everyone has a right to privacy.","sentence_zh":"每个人都有隐私权。",
   "aids":{"morphemes":[M("priv","root","单个，私"),M("acy","suffix","名词后缀")],
     "derivation":"private(私人的)的名词 → 私密的状态 → 隐私",
     "family":FAM("priv","单个、剥离",[W("private","私人的"),W("privilege","特权"),W("deprive","剥夺")]),
     "mnemonic":"priv=私(和 private 一家);不愿被外人知晓的私事/独处空间,就是 privacy 隐私;invade privacy 侵犯隐私。",
     "forms":[F("private","adj.","私人的")]}},
  {"word":"guideline","phonetic":"ˈɡaɪdlaɪn","pos":"n.","def":"指导方针，准则","cefr":"B2","freq_rank":95,
   "sentence_en":"Follow the safety guidelines.","sentence_zh":"请遵循安全准则。",
   "aids":{"morphemes":[M("guide","root","引导"),M("line","root","线")],
     "derivation":"guide(引导)+line(线) → 引路的线 → 指导方针",
     "family":FAM("guid","引导",[W("guide","指导"),W("guidance","指导")]),
     "mnemonic":"guide(引导)+line(线)——给人指路的准绳,就是 guideline 指导方针;常用复数 guidelines。",
     "forms":[F("guidelines","n.","准则(复数)")]}},
  {"word":"assignment","phonetic":"əˈsaɪnmənt","pos":"n.","def":"任务，作业；分配，指派","cefr":"B1","freq_rank":122,
   "sentence_en":"The homework assignment is due Friday.","sentence_zh":"这项作业周五截止。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sign","root","记号"),M("ment","suffix","名词后缀")],
     "derivation":"assign(指派)+ment → 被指派的活 → 任务、作业",
     "family":FAM("sign","记号、标志",[W("assign","分配"),W("sign","符号"),W("design","设计")]),
     "mnemonic":"assign(分配、指派)的名词;派给你的活儿/功课,就是 assignment;动词 assign。",
     "forms":[F("assign","v.","分配")]}},
  {"word":"laboratory","phonetic":"ləˈbɒrətri","pos":"n.","def":"实验室","cefr":"B1","freq_rank":123,
   "sentence_en":"The experiment was done in a laboratory.","sentence_zh":"实验是在实验室里做的。",
   "aids":{"morphemes":[M("labor","root","劳动，工作"),M("atory","suffix","…的场所")],
     "derivation":"labor(劳作)+atory → 做研究工作的场所 → 实验室",
     "family":FAM("labor","劳动",[W("labor","劳动"),W("collaborate","合作"),W("elaborate","详尽的")]),
     "mnemonic":"labor=劳动(想 labor 劳作);做科研'劳作'的地方,就是 laboratory(常缩 lab);labor 劳动。",
     "forms":[F("laboratories","n.","实验室(复数)")]}},
  {"word":"demonstration","phonetic":"ˌdemənˈstreɪʃən","pos":"n.","def":"演示，示范；示威","cefr":"B2","freq_rank":124,
   "sentence_en":"He gave a demonstration of the machine.","sentence_zh":"他演示了这台机器。",
   "aids":{"morphemes":[M("de","prefix","彻底"),M("monstr","root","显示，指出"),M("ation","suffix","名词后缀")],
     "derivation":"demonstrate(彻底显示)+ion → 演示/示威的行为 → 演示",
     "family":FAM("monstr/mon","显示、警告",[W("demonstrate","演示"),W("monster","怪物"),W("monitor","监视器")]),
     "mnemonic":"monstr=显示(和 demonstrate 一家);把用法摆给人看=演示;把诉求摆给社会看=示威,都是 demonstration。",
     "forms":[F("demonstrate","v.","演示；示威")]}},
  {"word":"medication","phonetic":"ˌmedɪˈkeɪʃən","pos":"n.","def":"药物；药物治疗","cefr":"B2","freq_rank":129,
   "sentence_en":"He is on medication for his heart.","sentence_zh":"他在服用心脏方面的药物。",
   "aids":{"morphemes":[M("medic","root","医治"),M("ation","suffix","名词后缀")],
     "derivation":"medic(医治)+ation → 用来医治的东西 → 药物",
     "family":FAM("medic","医治",[W("medical","医学的"),W("medicine","药"),W("remedy","疗法")]),
     "mnemonic":"medic=医(和 medical 一家);医生开来治病的药,就是 medication;on medication 在服药。",
     "forms":[F("medications","n.","药物(复数)")]}},
  {"word":"ratio","phonetic":"ˈreɪʃiəʊ","pos":"n.","def":"比率，比例","cefr":"B2","freq_rank":105,
   "sentence_en":"The ratio of boys to girls is 2:1.","sentence_zh":"男女比例是2:1。",
   "aids":{"morphemes":[M("rat","root","计算，理性(ratus)"),M("io","suffix","名词后缀")],
     "derivation":"拉丁 ratio'计算、比值';两数相比的值 → 比率",
     "family":FAM("rat","计算、理性",[W("rate","比率"),W("rational","理性的"),W("ration","定量")]),
     "mnemonic":"rat=计算(和 rate/rational 一家);两个量相除得到的比值,就是 ratio 比率;写作 2:1。",
     "forms":[F("ratios","n.","比率(复数)")]}},
  {"word":"membership","phonetic":"ˈmembəʃɪp","pos":"n.","def":"会员资格；全体会员","cefr":"B1","freq_rank":104,
   "sentence_en":"Membership is free for students.","sentence_zh":"学生免费入会。",
   "aids":{"morphemes":[M("member","root","成员"),M("ship","suffix","…的身份")],
     "derivation":"member(成员)+ship → 成为成员的身份 → 会员资格",
     "family":FAM("member","成员、肢体",[W("member","成员"),W("remember","记得")]),
     "mnemonic":"member(成员)+ship(身份,如 friendship);当会员的资格,或全体会员,就是 membership。",
     "forms":[F("member","n.","成员")]}},
  # 高频形容词/副词
  {"word":"sophisticated","phonetic":"səˈfɪstɪkeɪtɪd","pos":"adj.","def":"复杂精密的；老练的，见多识广的","cefr":"C1","freq_rank":101,
   "sentence_en":"It's a sophisticated piece of technology.","sentence_zh":"这是一件精密的技术设备。",
   "aids":{"morphemes":[M("soph","root","智慧"),M("isticated","suffix","…的")],
     "derivation":"soph(智慧)→ 融入智慧而变得复杂/世故的 → 精密的、老练的",
     "family":FAM("soph","智慧",[W("philosophy","哲学"),W("sophomore","大二学生")]),
     "mnemonic":"soph=智慧(和 philosophy 一家);技术'智慧'含量高=复杂精密的;人'智慧'历练深=老练世故的,都是 sophisticated。",
     "forms":[F("sophistication","n.","精密；老练")]}},
  {"word":"controversial","phonetic":"ˌkɒntrəˈvɜːʃl","pos":"adj.","def":"有争议的，引起争论的","cefr":"C1","freq_rank":106,
   "sentence_en":"It's a controversial topic.","sentence_zh":"这是个有争议的话题。",
   "aids":{"morphemes":[M("contro","prefix","相反(contra)"),M("vers","root","转"),M("ial","suffix","…的")],
     "derivation":"controversy(争议)+al → 引起争议的 → 有争议的",
     "family":FAM("vers/vert","转",[W("controversy","争议"),W("convert","转换"),W("reverse","颠倒")]),
     "mnemonic":"和 controversy(争议)一家(contra 相反 + vers 转);会让人转向对立、吵起来的,就是 controversial 有争议的。",
     "forms":[F("controversy","n.","争议")]}},
  {"word":"desperate","phonetic":"ˈdespərət","pos":"adj.","def":"绝望的，铤而走险的；极度渴望的","cefr":"B2","freq_rank":107,
   "sentence_en":"They were desperate for help.","sentence_zh":"他们极度渴望得到帮助。",
   "aids":{"morphemes":[M("de","prefix","去除，无"),M("sper","root","希望(sperare)"),M("ate","suffix","…的")],
     "derivation":"de(无)+sper(希望) → 没了希望的 → 绝望的;绝望中不顾一切 → 极度渴望",
     "family":FAM("sper","希望",[W("prosper","繁荣"),W("despair","绝望")]),
     "mnemonic":"sper=希望(反义想 despair 绝望);没(de-)了指望、走投无路的,就是 desperate;绝望到啥都愿做=极度渴望(desperate for)。",
     "forms":[F("desperately","adv.","拼命地"),F("desperation","n.","绝望")]}},
  {"word":"incredible","phonetic":"ɪnˈkredəbl","pos":"adj.","def":"难以置信的，惊人的","cefr":"B1","freq_rank":86,
   "sentence_en":"The view was incredible.","sentence_zh":"景色美得令人难以置信。",
   "aids":{"morphemes":[M("in","prefix","不"),M("cred","root","相信"),M("ible","suffix","能…的")],
     "derivation":"in(不)+cred(相信) → 令人无法相信的 → 难以置信的",
     "family":FAM("cred","相信",[W("credit","信用"),W("credible","可信的"),W("credential","证书")]),
     "mnemonic":"cred=相信(想 credit 信用);好/惊人到没法(in-)相信,就是 incredible;credible 可信的;incredibly 极其。",
     "forms":[F("incredibly","adv.","难以置信地；极其")]}},
  {"word":"organic","phonetic":"ɔːˈɡænɪk","pos":"adj.","def":"有机的；器官的；有机食品的","cefr":"B2","freq_rank":99,
   "sentence_en":"They buy organic vegetables.","sentence_zh":"他们买有机蔬菜。",
   "aids":{"morphemes":[M("organ","root","器官，生物"),M("ic","suffix","…的")],
     "derivation":"organ(器官、生物)+ic → 与生物体有关的 → 有机的",
     "family":FAM("organ","器官",[W("organ","器官"),W("organism","生物体"),W("organize","组织")]),
     "mnemonic":"organ=器官/生物(和 organism 一家);源于生物、不含化学添加的,就是 organic 有机的;organic food 有机食品。",
     "forms":[F("organically","adv.","有机地")]}},
  {"word":"wealthy","phonetic":"ˈwelθi","pos":"adj.","def":"富有的，富裕的","cefr":"B1","freq_rank":83,
   "sentence_en":"He comes from a wealthy family.","sentence_zh":"他出身富裕家庭。",
   "aids":{"morphemes":[M("wealth","root","财富"),M("y","suffix","…的")],
     "derivation":"wealth(财富)+y → 有财富的 → 富有的",
     "family":FAM("weal/well","福、财",[W("wealth","财富"),W("welfare","福利")]),
     "mnemonic":"wealth=财富(和 well 好、welfare 福利同源);钱财丰厚的,就是 wealthy 富有的;反义 poor;wealth 财富。",
     "forms":[F("wealth","n.","财富")]}},
  {"word":"mere","phonetic":"mɪə","pos":"adj.","def":"仅仅的，只不过的","cefr":"B2","freq_rank":72,
   "sentence_en":"The mere thought of it scares me.","sentence_zh":"光是想想就让我害怕。",
   "aids":{"morphemes":[M("mere","root","纯粹，仅(merus)")],
     "derivation":"拉丁 merus'纯粹的';纯粹只是 → 仅仅的",
     "family":FAM("mer","纯粹、仅",[W("merely","仅仅")]),
     "mnemonic":"mere=仅(想 merely 仅仅);强调'不过是、只是'=mere;a mere child 只是个孩子;副词 merely。",
     "forms":[F("merely","adv.","仅仅")]}},
  {"word":"slight","phonetic":"slaɪt","pos":"adj.","def":"轻微的，细小的；纤弱的","cefr":"B1","freq_rank":77,
   "sentence_en":"There was a slight delay.","sentence_zh":"有一点小延误。",
   "aids":{"morphemes":[M("slight","root","细小，平滑(古诺斯语 slēttr)")],
     "derivation":"古诺斯语'平滑、细小';程度很小的 → 轻微的",
     "family":FAM("","相关词",[W("slightly","轻微地")]),
     "mnemonic":"slight=细小;程度很轻、不明显的,就是 slight 轻微的(a slight cold 小感冒);slightly 稍微;not in the slightest 一点也不。",
     "forms":[F("slightly","adv.","稍微，轻微地")]}},
  {"word":"given","phonetic":"ˈɡɪvn","pos":"prep./adj.","def":"考虑到，鉴于；特定的，given","cefr":"B2","freq_rank":85,
   "sentence_en":"Given the circumstances, we did well.","sentence_zh":"考虑到当时的情况，我们做得不错。",
   "aids":{"morphemes":[M("giv","root","给"),M("en","suffix","过去分词")],
     "derivation":"give(给)的过去分词;'既已给定'→ 考虑到、鉴于;'被给定的'→ 特定的",
     "family":FAM("giv","给",[W("give","给"),W("forgive","原谅")]),
     "mnemonic":"given 是 give 的过去分词;'已给定这些条件'=考虑到/鉴于(given that);'规定好的某个'=特定的(at a given time)。",
     "forms":[F("give","v.","给")]}},
  # 常见词
  {"word":"counter","phonetic":"ˈkaʊntə","pos":"n./v./adj.","def":"柜台；计数器；反击，抵制；相反的","cefr":"B2","freq_rank":64,
   "sentence_en":"Pay at the counter.","sentence_zh":"在柜台付款。",
   "aids":{"morphemes":[M("counter","root","对着，反(contra);计算(count)")],
     "derivation":"一义源自 count'计数'→ 计数器/柜台(结账处);另一义源自 contra'对着'→ 反击、相反的",
     "family":FAM("counter/contra","对着、反",[W("encounter","遭遇"),W("contrast","对比"),W("contrary","相反的")]),
     "mnemonic":"counter 两源:count(数)→结账的柜台/计数器;contra(对着)→反击、抵制(counter-attack)、相反的(run counter to 与…相悖)。",
     "forms":[F("counters","n.","柜台(复数)"),F("countered","v.","反击(过去式)")]}},
  {"word":"crash","phonetic":"kræʃ","pos":"n./v.","def":"碰撞，坠毁；(系统)崩溃；暴跌","cefr":"B1","freq_rank":65,
   "sentence_en":"The plane crashed into the mountain.","sentence_zh":"飞机撞上了山。",
   "aids":{"morphemes":[M("crash","root","哗啦巨响(拟声)")],
     "derivation":"拟声词'哗啦一声撞碎';猛烈相撞 → 碰撞、坠毁",
     "family":FAM("","相关词",[W("crashing","轰响的")]),
     "mnemonic":"crash 是拟声——哐当撞碎;车/机相撞坠毁=crash;电脑'死机'=crash;股市'崩盘'暴跌=crash。",
     "forms":[F("crashed","v.","过去式/过去分词"),F("crashes","n.","碰撞(复数)")]}},
  {"word":"fault","phonetic":"fɔːlt","pos":"n.","def":"过错，责任；缺点，故障","cefr":"B1","freq_rank":67,
   "sentence_en":"It's not my fault.","sentence_zh":"这不是我的错。",
   "aids":{"morphemes":[M("fault","root","缺失(fallere 出错)")],
     "derivation":"拉丁 fallere'欺骗、出错';差错、缺失 → 过错、故障",
     "family":FAM("fal/fault","错、失",[W("false","错误的"),W("fail","失败"),W("default","默认；违约")]),
     "mnemonic":"fault 与 false/fail(出错)同源;做错该负的责=过错(my fault);机器的毛病=故障;地质'断层'也是 fault。",
     "forms":[F("faults","n.","过错(复数)"),F("faulty","adj.","有缺陷的")]}},
  {"word":"fade","phonetic":"feɪd","pos":"v.","def":"褪色，(渐渐)消失；凋谢","cefr":"B1","freq_rank":68,
   "sentence_en":"The colors faded in the sun.","sentence_zh":"颜色在阳光下褪去了。",
   "aids":{"morphemes":[M("fade","root","枯萎，变淡(古法语 fade 无味)")],
     "derivation":"古法语 fade'无味、暗淡';逐渐变淡 → 褪色、消失",
     "family":FAM("","相关词",[W("fading","渐弱的")]),
     "mnemonic":"fade=变淡;颜色变浅=褪色;声音/记忆渐弱消失=fade away;花凋谢=fade;fade in/out 淡入/淡出。",
     "forms":[F("faded","v.","过去式/过去分词"),F("fading","adj.","渐弱的")]}},
  {"word":"plot","phonetic":"plɒt","pos":"n./v.","def":"情节；阴谋；小块地；密谋，标绘","cefr":"B2","freq_rank":74,
   "sentence_en":"The plot of the movie is complex.","sentence_zh":"这部电影的情节很复杂。",
   "aids":{"morphemes":[M("plot","root","小块地；密谋(古英语 plot)")],
     "derivation":"本义'一小块地';引申'规划图'→ 情节/密谋;标点作图 → 标绘",
     "family":FAM("","相关词",[W("subplot","次要情节")]),
     "mnemonic":"plot 本义'小块地';故事的'布局'=情节;暗中的'布局'=阴谋(plot against);在坐标上标点=plot 标绘。",
     "forms":[F("plots","n.","情节(复数)"),F("plotted","v.","过去式/过去分词")]}},
  {"word":"gesture","phonetic":"ˈdʒestʃə","pos":"n./v.","def":"手势，姿态；(表示态度的)举动","cefr":"B2","freq_rank":75,
   "sentence_en":"He made a rude gesture.","sentence_zh":"他做了个粗鲁的手势。",
   "aids":{"morphemes":[M("gest","root","带来，做出"),M("ure","suffix","名词后缀")],
     "derivation":"gest(做出)+ure → 身体做出的动作 → 手势",
     "family":FAM("gest","带来、做",[W("suggest","建议"),W("digest","消化"),W("register","登记")]),
     "mnemonic":"gest=做出(和 suggest 一家);用手/身体做出的动作,就是 gesture 手势;表善意的'举动'(a nice gesture)。",
     "forms":[F("gestures","n.","手势(复数)")]}},
  {"word":"shade","phonetic":"ʃeɪd","pos":"n./v.","def":"阴凉处，树荫；色度；遮蔽","cefr":"B1","freq_rank":78,
   "sentence_en":"Let's sit in the shade.","sentence_zh":"我们坐在阴凉处吧。",
   "aids":{"morphemes":[M("shade","root","阴影(古英语 sceadu)")],
     "derivation":"古英语'影';挡光形成的暗处 → 树荫;颜色深浅 → 色度",
     "family":FAM("shad","影",[W("shadow","影子"),W("overshadow","使黯然失色")]),
     "mnemonic":"shade 与 shadow(影子)同源;挡光的凉处=树荫/阴凉;同色的不同深浅=色度(shades of blue);遮光=shade。",
     "forms":[F("shades","n.","阴凉处；色度(复数)")]}},
  {"word":"angle","phonetic":"ˈæŋɡl","pos":"n.","def":"角，角度；(看问题的)角度","cefr":"B1","freq_rank":80,
   "sentence_en":"Look at it from a different angle.","sentence_zh":"换个角度看它。",
   "aids":{"morphemes":[M("angl","root","角，弯(angulus)"),M("e","suffix","结尾")],
     "derivation":"拉丁 angulus'角、弯';两线相交处 → 角",
     "family":FAM("ang","角、弯",[W("angular","有棱角的"),W("triangle","三角形"),W("rectangle","矩形")]),
     "mnemonic":"angl=角(想 triangle 三角形);两线相交的角/角度=angle;看事情的'角度'(from this angle)。",
     "forms":[F("angles","n.","角(复数)")]}},
  {"word":"strip","phonetic":"strɪp","pos":"n./v.","def":"长条，条带；脱去，剥去","cefr":"B2","freq_rank":58,
   "sentence_en":"Cut the paper into strips.","sentence_zh":"把纸剪成长条。",
   "aids":{"morphemes":[M("strip","root","剥，长条(中古英语)")],
     "derivation":"中古英语'剥去、狭长条';剥下的/狭长的一条 → 长条;剥光 → 脱去",
     "family":FAM("","相关词",[W("stripe","条纹")]),
     "mnemonic":"strip=长条/剥;狭长的一条=a strip of;把外皮/衣服剥光=strip;comic strip 连环漫画;别和 stripe(条纹)混。",
     "forms":[F("strips","n.","长条(复数)"),F("stripped","v.","过去式/过去分词")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 18
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
