#!/usr/bin/env python
# 第十批词:约55个高频词,逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -vid 分
  {"word":"divide","phonetic":"dɪˈvaɪd","pos":"v.","def":"分开，划分；除","cefr":"A2","freq_rank":49,
   "sentence_en":"Divide the cake into eight pieces.","sentence_zh":"把蛋糕分成八块。",
   "aids":{"morphemes":[M("di","prefix","分开"),M("vid","root","分")],
     "derivation":"di(分开)+vid(分) → 分割 → 划分",
     "family":FAM("vid/vis","分、看",[W("division","分割"),W("individual","个体"),W("device","装置")]),
     "mnemonic":"vid=分;把整体一切两断,就是 divide 分开、除;名词 division;反义 unite/multiply。",
     "forms":[F("division","n.","分割"),F("divided","adj.","分裂的")]}},
  # -pos 放
  {"word":"oppose","phonetic":"əˈpəʊz","pos":"v.","def":"反对，对抗","cefr":"B1","freq_rank":51,
   "sentence_en":"Many people oppose the new law.","sentence_zh":"许多人反对这项新法律。",
   "aids":{"morphemes":[M("op","prefix","对着(ob 变体)"),M("pose","root","放置")],
     "derivation":"op(对着)+pose(放) → 站到对立面 → 反对",
     "family":FAM("pos/pose","放置",[W("opposite","对面的"),W("propose","提议"),W("expose","暴露"),W("compose","组成")]),
     "mnemonic":"pose=放;把自己放到对(op-)立面去,就是 oppose 反对;opposite 相反的;opponent 对手。",
     "forms":[F("opposite","adj.","相反的"),F("opposition","n.","反对")]}},
  {"word":"expose","phonetic":"ɪkˈspəʊz","pos":"v.","def":"暴露，使接触；揭露","cefr":"B2","freq_rank":81,
   "sentence_en":"Don't expose the film to light.","sentence_zh":"不要让胶片曝光。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("pose","root","放置")],
     "derivation":"ex(向外)+pose(放) → 放到外面 → 暴露、揭露",
     "family":FAM("pos/pose","放置",[W("oppose","反对"),W("propose","提议"),W("compose","组成"),W("impose","强加")]),
     "mnemonic":"pose=放;把隐藏的东西放到外面(ex-)去,就是 expose 暴露、揭露;be exposed to 接触到。",
     "forms":[F("exposure","n.","暴露；曝光"),F("exposed","adj.","暴露的")]}},
  # -esse 存在
  {"word":"essential","phonetic":"ɪˈsenʃəl","pos":"adj./n.","def":"必要的，本质的；要素","cefr":"B1","freq_rank":55,
   "sentence_en":"Water is essential for life.","sentence_zh":"水是生命必不可少的。",
   "aids":{"morphemes":[M("ess","root","存在，是(esse)"),M("ential","suffix","…的")],
     "derivation":"ess(存在)+ential → 关乎存在根本的 → 本质的、必要的",
     "family":FAM("ess/esse","存在、是",[W("essence","本质"),W("present","在场的"),W("absent","缺席的")]),
     "mnemonic":"ess=存在(想 essence 本质);触及事物存在根本、缺它不可的,就是 essential 必要的、本质的。",
     "forms":[F("essence","n.","本质"),F("essentially","adv.","本质上")]}},
  # -ply 折
  {"word":"employ","phonetic":"ɪmˈplɔɪ","pos":"v.","def":"雇用；使用","cefr":"B1","freq_rank":60,
   "sentence_en":"The factory employs 500 workers.","sentence_zh":"这家工厂雇用500名工人。",
   "aids":{"morphemes":[M("em","prefix","使处于(in)"),M("ploy","root","折叠，卷入(plic)")],
     "derivation":"em(使)+ploy(卷入) → 把人卷入工作中 → 雇用",
     "family":FAM("ploy/plic","折叠、卷",[W("apply","申请"),W("imply","暗示"),W("deploy","部署")]),
     "mnemonic":"ploy=卷入(plic 家族);把人卷进(em-)自己的活里干,就是 employ 雇用;employee 雇员/employer 雇主。",
     "forms":[F("employment","n.","就业"),F("employee","n.","雇员")]}},
  # -clin 倾
  {"word":"decline","phonetic":"dɪˈklaɪn","pos":"v./n.","def":"下降，衰退；婉拒","cefr":"B2","freq_rank":78,
   "sentence_en":"Sales declined last year.","sentence_zh":"去年销量下降了。",
   "aids":{"morphemes":[M("de","prefix","向下"),M("cline","root","倾斜")],
     "derivation":"de(向下)+cline(倾) → 向下倾斜 → 下降、衰退;把头偏开 → 婉拒",
     "family":FAM("clin","倾斜",[W("incline","倾向"),W("client","客户"),W("lean","倚")]),
     "mnemonic":"cline=倾(想 incline 倾斜);曲线一路向下(de-)倾=下降、衰退;把请求'偏头'推开=婉拒。",
     "forms":[F("declined","v.","过去式/过去分词")]}},
  # -vest 衣
  {"word":"invest","phonetic":"ɪnˈvest","pos":"v.","def":"投资；投入(时间/精力)","cefr":"B1","freq_rank":79,
   "sentence_en":"They invested in a new company.","sentence_zh":"他们投资了一家新公司。",
   "aids":{"morphemes":[M("in","prefix","向内，使穿上"),M("vest","root","衣服")],
     "derivation":"in(使穿上)+vest(衣) → 给钱'穿上'新用途、注入 → 投资",
     "family":FAM("vest","衣服",[W("vest","背心"),W("invest","投资"),W("investment","投资")]),
     "mnemonic":"vest=衣(想 vest 背心);给资金'披上'生利的外衣、注入某处,就是 invest 投资;investment 投资。",
     "forms":[F("investment","n.","投资"),F("investor","n.","投资者")]}},
  # -ced 走
  {"word":"succeed","phonetic":"səkˈsiːd","pos":"v.","def":"成功；继承，接替","cefr":"B1","freq_rank":85,
   "sentence_en":"She succeeded in passing the exam.","sentence_zh":"她成功通过了考试。",
   "aids":{"morphemes":[M("suc","prefix","在下，随后(sub)"),M("ceed","root","走")],
     "derivation":"suc(随后)+ceed(走) → 顺利走下去、随之而来 → 成功;接着前人走 → 继承",
     "family":FAM("ceed/cess","走",[W("proceed","前进"),W("exceed","超过"),W("success","成功"),W("process","过程")]),
     "mnemonic":"ceed=走(想 proceed 前进);一路顺利走到位=succeed 成功;紧跟前人接着走=继承(succeed to the throne)。",
     "forms":[F("success","n.","成功"),F("successful","adj.","成功的")]}},
  # -quire 寻
  {"word":"acquire","phonetic":"əˈkwaɪə","pos":"v.","def":"获得，取得；学到","cefr":"B2","freq_rank":101,
   "sentence_en":"Children acquire language quickly.","sentence_zh":"孩子学习语言很快。",
   "aids":{"morphemes":[M("ac","prefix","朝向(ad 变体)"),M("quire","root","寻求")],
     "derivation":"ac(朝向)+quire(求) → 朝目标求取到手 → 获得",
     "family":FAM("quire/quest","寻求",[W("require","要求"),W("inquire","询问"),W("request","请求")]),
     "mnemonic":"quire=求(和 require 一家);努力去求而得到、习得,就是 acquire 获得、学到;acquisition 获得。",
     "forms":[F("acquisition","n.","获得，收购")]}},
  # -pet 追求
  {"word":"compete","phonetic":"kəmˈpiːt","pos":"v.","def":"竞争，比赛","cefr":"B1","freq_rank":103,
   "sentence_en":"Small shops can't compete with big chains.","sentence_zh":"小店无法与大型连锁店竞争。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("pete","root","追求")],
     "derivation":"com(一起)+pete(追求) → 一起追同一目标 → 竞争",
     "family":FAM("pet","追求",[W("competition","竞争"),W("appetite","食欲"),W("petition","请愿")]),
     "mnemonic":"pete=追求(想 appetite 食欲);大家一起(com-)争抢同一目标,就是 compete;competition 竞争。",
     "forms":[F("competition","n.","竞争"),F("competitor","n.","竞争者")]}},
  # -vinc 征服
  {"word":"convince","phonetic":"kənˈvɪns","pos":"v.","def":"使信服，说服","cefr":"B2","freq_rank":90,
   "sentence_en":"He convinced me to join.","sentence_zh":"他说服我加入。",
   "aids":{"morphemes":[M("con","prefix","完全"),M("vince","root","征服(vinc)")],
     "derivation":"con(完全)+vince(征服) → 在道理上完全征服 → 使信服",
     "family":FAM("vinc/vict","征服",[W("victory","胜利"),W("convict","定罪"),W("evince","表明")]),
     "mnemonic":"vince=征服(想 victory 胜利);用道理彻底(con-)攻下对方,就是 convince 说服;convincing 有说服力的。",
     "forms":[F("convinced","adj.","确信的"),F("convincing","adj.","有说服力的")]}},
  # -prov 检验/有益
  {"word":"approve","phonetic":"əˈpruːv","pos":"v.","def":"批准，通过；赞成","cefr":"B1","freq_rank":98,
   "sentence_en":"The board approved the plan.","sentence_zh":"董事会批准了计划。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("prove","root","证明，检验")],
     "derivation":"ap(朝向)+prove(证明) → 认可其可行、点头 → 批准",
     "family":FAM("prov/prob","证明、检验",[W("prove","证明"),W("proof","证据"),W("probable","很可能的")]),
     "mnemonic":"prove=证明;认可某事经得起检验、点头放行,就是 approve 批准;approve of 赞成;approval 批准。",
     "forms":[F("approval","n.","批准，赞成"),F("approved","adj.","经批准的")]}},
  # -leg 法
  {"word":"legislation","phonetic":"ˌledʒɪsˈleɪʃən","pos":"n.","def":"立法；法律，法规","cefr":"C1","freq_rank":84,
   "sentence_en":"New legislation was introduced.","sentence_zh":"新法规出台了。",
   "aids":{"morphemes":[M("legis","root","法律"),M("lat","root","带，制定"),M("ion","suffix","名词后缀")],
     "derivation":"legis(法律)+lat(制定) → 制定法律 → 立法",
     "family":FAM("leg","法律",[W("legal","合法的"),W("legitimate","合法的"),W("legislator","立法者")]),
     "mnemonic":"legis=法律(和 legal 一家);把法律'带出、制定'出来的过程,就是 legislation 立法、法规。",
     "forms":[F("legislative","adj.","立法的"),F("legislator","n.","立法者")]}},
  # -chieve 头
  {"word":"achievement","phonetic":"əˈtʃiːvmənt","pos":"n.","def":"成就，成绩；达成","cefr":"B1","freq_rank":87,
   "sentence_en":"Winning the prize was a great achievement.","sentence_zh":"获奖是一项巨大成就。",
   "aids":{"morphemes":[M("a","prefix","朝向"),M("chieve","root","头，顶(chief)"),M("ment","suffix","名词后缀")],
     "derivation":"a(朝向)+chieve(头、顶) → 达到顶点、办成 → 成就",
     "family":FAM("chief/chieve","头、顶",[W("achieve","实现"),W("chief","首要的")]),
     "mnemonic":"chieve=头/顶(和 chief 一家);努力冲到顶、办成的事,就是 achievement 成就;动词 achieve 实现。",
     "forms":[F("achieve","v.","实现，取得"),F("achievements","n.","成就(复数)")]}},
  # -init 进入
  {"word":"initial","phonetic":"ɪˈnɪʃəl","pos":"adj./n.","def":"最初的；首字母","cefr":"B1","freq_rank":50,
   "sentence_en":"My initial reaction was surprise.","sentence_zh":"我最初的反应是惊讶。",
   "aids":{"morphemes":[M("in","prefix","向内，进入"),M("it","root","走"),M("ial","suffix","…的")],
     "derivation":"in(进入)+it(走) → 刚踏进、起步的 → 最初的",
     "family":FAM("it","走、行",[W("initiate","发起"),W("exit","出口"),W("transit","运输")]),
     "mnemonic":"it=走(想 exit 出口);刚迈步进(in-)门的那一步,就是 initial 最初的;名字开头那个字母=首字母。",
     "forms":[F("initially","adv.","最初"),F("initiative","n.","主动性；倡议")]}},
  # 高频形容词/副词
  {"word":"overall","phonetic":"ˌəʊvərˈɔːl","pos":"adj./adv.","def":"总体的；总的来说","cefr":"B1","freq_rank":48,
   "sentence_en":"The overall result was positive.","sentence_zh":"总体结果是积极的。",
   "aids":{"morphemes":[M("over","prefix","覆盖，全"),M("all","root","全部")],
     "derivation":"over(全)+all(全部) → 把全部盖进来看 → 总体的",
     "family":FAM("","相关词",[W("overview","概览")]),
     "mnemonic":"over(全盖)+all(全部)——把方方面面一起统看,就是 overall 总体的;放句首'总的来说'。",
     "forms":[]}},
  {"word":"multiple","phonetic":"ˈmʌltɪpl","pos":"adj./n.","def":"多重的，多个的；倍数","cefr":"B2","freq_rank":54,
   "sentence_en":"He has multiple jobs.","sentence_zh":"他身兼数职。",
   "aids":{"morphemes":[M("multi","prefix","多"),M("ple","root","折，倍(plic)")],
     "derivation":"multi(多)+ple(折) → 多重折叠、许多份 → 多重的",
     "family":FAM("multi/plic","多、折",[W("multiply","乘"),W("multitude","众多"),W("complex","复杂的")]),
     "mnemonic":"multi=多(想 multimedia 多媒体)+ple(倍);好多份、多重的,就是 multiple;数学的'倍数'也是 multiple。",
     "forms":[F("multiply","v.","乘；繁殖")]}},
  {"word":"contemporary","phonetic":"kənˈtempərəri","pos":"adj./n.","def":"当代的；同时代的(人)","cefr":"C1","freq_rank":53,
   "sentence_en":"She loves contemporary art.","sentence_zh":"她喜欢当代艺术。",
   "aids":{"morphemes":[M("con","prefix","一起，同"),M("tempor","root","时间"),M("ary","suffix","…的")],
     "derivation":"con(同)+tempor(时间) → 同一时间的 → 当代的、同时代的",
     "family":FAM("tempor","时间",[W("temporary","暂时的"),W("temporal","时间的"),W("tempo","节奏")]),
     "mnemonic":"tempor=时间(想 temporary 暂时的);和我们同处一个时代的,就是 contemporary 当代的。",
     "forms":[F("contemporaries","n.","同时代人(复数)")]}},
  {"word":"enormous","phonetic":"ɪˈnɔːməs","pos":"adj.","def":"巨大的，庞大的","cefr":"B1","freq_rank":76,
   "sentence_en":"They spent an enormous amount of money.","sentence_zh":"他们花了一大笔钱。",
   "aids":{"morphemes":[M("e","prefix","出，离"),M("norm","root","规范，标准"),M("ous","suffix","…的")],
     "derivation":"e(出)+norm(规范) → 超出常规大小的 → 巨大的",
     "family":FAM("norm","规范、标准",[W("normal","正常的"),W("norm","规范"),W("abnormal","反常的")]),
     "mnemonic":"norm=规范(和 normal 一家);大得超(e-)出常规尺度,就是 enormous 巨大的。",
     "forms":[F("enormously","adv.","巨大地")]}},
  {"word":"massive","phonetic":"ˈmæsɪv","pos":"adj.","def":"巨大的，大量的","cefr":"B2","freq_rank":77,
   "sentence_en":"There was a massive explosion.","sentence_zh":"发生了一场大爆炸。",
   "aids":{"morphemes":[M("mass","root","团，块，大量"),M("ive","suffix","…的")],
     "derivation":"mass(大量)+ive → 有大量/大块特征的 → 巨大的",
     "family":FAM("mass","团、块、大量",[W("mass","大量；质量"),W("massacre","大屠杀")]),
     "mnemonic":"mass=大块/大量;体量像一大坨那样大,就是 massive 巨大的;mass 群众/质量/大量。",
     "forms":[F("massively","adv.","大规模地")]}},
  {"word":"vast","phonetic":"vɑːst","pos":"adj.","def":"广阔的，巨大的","cefr":"B1","freq_rank":61,
   "sentence_en":"The desert covers a vast area.","sentence_zh":"沙漠覆盖着广阔的区域。",
   "aids":{"morphemes":[M("vast","root","空旷广大(vastus)")],
     "derivation":"拉丁 vastus'空旷、辽阔';一望无际的 → 广阔的",
     "family":FAM("vast","空旷、广大",[W("waste","荒芜；浪费"),W("devastate","摧毁")]),
     "mnemonic":"vast 与 waste(荒芜)同源'空旷辽阔';一望无边的,就是 vast 广阔的;the vast majority 绝大多数。",
     "forms":[F("vastly","adv.","极大地")]}},
  {"word":"upper","phonetic":"ˈʌpə","pos":"adj.","def":"上面的，较高的；上层的","cefr":"A2","freq_rank":58,
   "sentence_en":"Write your name in the upper corner.","sentence_zh":"把名字写在上角。",
   "aids":{"morphemes":[M("up","root","上"),M("per","suffix","较…的")],
     "derivation":"up(上)+per → 更靠上的 → 上面的、上层的",
     "family":FAM("up","上",[W("upward","向上的"),W("upstairs","楼上")]),
     "mnemonic":"up(上)的比较级形式;位置/等级更靠上的,就是 upper;upper class 上层;反义 lower 下面的。",
     "forms":[F("uppermost","adj.","最高的")]}},
  {"word":"creative","phonetic":"kriːˈeɪtɪv","pos":"adj.","def":"有创造力的，创造性的","cefr":"B1","freq_rank":96,
   "sentence_en":"She has a creative mind.","sentence_zh":"她思维富有创造力。",
   "aids":{"morphemes":[M("creat","root","创造，生成"),M("ive","suffix","…的")],
     "derivation":"creat(创造)+ive → 能创造的 → 有创造力的",
     "family":FAM("cre","生长、产生",[W("create","创造"),W("creation","创作"),W("creature","生物")]),
     "mnemonic":"creat=创造(和 create 一家);善于从无到有造出新东西的,就是 creative;creativity 创造力。",
     "forms":[F("creativity","n.","创造力"),F("creatively","adv.","创造性地")]}},
  {"word":"technical","phonetic":"ˈteknɪkl","pos":"adj.","def":"技术的，专业的","cefr":"B1","freq_rank":102,
   "sentence_en":"He gave technical support.","sentence_zh":"他提供了技术支持。",
   "aids":{"morphemes":[M("techn","root","技艺"),M("ical","suffix","…的")],
     "derivation":"techn(技艺)+ical → 与技术有关的 → 技术的",
     "family":FAM("techn","技艺",[W("technique","技巧"),W("technology","技术"),W("technician","技术员")]),
     "mnemonic":"techn=技艺(和 technology 一家);关于专门技术、工艺的,就是 technical;technically 技术上/严格来说。",
     "forms":[F("technically","adv.","技术上；严格来说")]}},
  {"word":"illegal","phonetic":"ɪˈliːɡl","pos":"adj.","def":"非法的，违法的","cefr":"B1","freq_rank":106,
   "sentence_en":"It is illegal to drive without a license.","sentence_zh":"无照驾驶是违法的。",
   "aids":{"morphemes":[M("il","prefix","不(in 变体)"),M("leg","root","法律"),M("al","suffix","…的")],
     "derivation":"il(不)+legal(合法的) → 不合法的 → 非法的",
     "family":FAM("leg","法律",[W("legal","合法的"),W("legislation","立法"),W("legitimate","合法的")]),
     "mnemonic":"il-(不)+legal(合法)——法律不允许的,就是 illegal;leg=法(和 legal 一家)。",
     "forms":[F("illegally","adv.","非法地")]}},
  {"word":"alternative","phonetic":"ɔːlˈtɜːnətɪv","pos":"n./adj.","def":"替代方案；供选择的","cefr":"B2","freq_rank":107,
   "sentence_en":"Is there an alternative to this plan?","sentence_zh":"这个计划有替代方案吗？",
   "aids":{"morphemes":[M("altern","root","轮流，另一(alter)"),M("ative","suffix","…的")],
     "derivation":"altern(另一)+ative → 另一个可选的 → 替代方案",
     "family":FAM("alter","另一，改变",[W("alter","改变"),W("alternate","交替"),W("alien","外来的")]),
     "mnemonic":"alter=另一个(想 alter 改变);此路不通时'另一个'选择,就是 alternative 替代方案。",
     "forms":[F("alternatively","adv.","或者，作为替代")]}},
  # 高频名词(常见/词根)
  {"word":"addition","phonetic":"əˈdɪʃən","pos":"n.","def":"增加，添加；加法","cefr":"A2","freq_rank":95,
   "sentence_en":"In addition, we offer free delivery.","sentence_zh":"此外，我们提供免费送货。",
   "aids":{"morphemes":[M("add","root","加"),M("ition","suffix","名词后缀")],
     "derivation":"add(加)+ition → 加上的动作/东西 → 增加、加法",
     "family":FAM("add/dit","加、给",[W("add","增加"),W("additional","额外的"),W("additive","添加剂")]),
     "mnemonic":"add=加;往上添的动作或东西,就是 addition;in addition (to)=此外/除…之外。",
     "forms":[F("additional","adj.","额外的")]}},
  {"word":"representative","phonetic":"ˌreprɪˈzentətɪv","pos":"n./adj.","def":"代表；有代表性的","cefr":"B2","freq_rank":69,
   "sentence_en":"She is our class representative.","sentence_zh":"她是我们的班级代表。",
   "aids":{"morphemes":[M("re","prefix","再"),M("present","root","呈现"),M("ative","suffix","…的")],
     "derivation":"represent(代表)+ative → 替人再呈现的人 → 代表",
     "family":FAM("present","呈现、在场",[W("represent","代表"),W("present","呈现"),W("presentation","展示")]),
     "mnemonic":"represent(代表)的名词/形容词;替一群人再呈现意愿的人=代表;能代表整体特征的=有代表性的。",
     "forms":[F("represent","v.","代表")]}},
  {"word":"characteristic","phonetic":"ˌkærəktəˈrɪstɪk","pos":"n./adj.","def":"特征，特性；典型的","cefr":"B2","freq_rank":88,
   "sentence_en":"Curiosity is a characteristic of children.","sentence_zh":"好奇是孩子的一个特征。",
   "aids":{"morphemes":[M("character","root","性格，特征"),M("istic","suffix","…的")],
     "derivation":"character(特征)+istic → 显出特征的 → 特性、典型的",
     "family":FAM("","相关词",[W("character","性格；特征"),W("characterize","刻画")]),
     "mnemonic":"character(特征)+istic;某物特有的属性=characteristic 特征;能代表其本色的=典型的。",
     "forms":[F("characteristics","n.","特征(复数)")]}},
  {"word":"witness","phonetic":"ˈwɪtnɪs","pos":"n./v.","def":"目击者，证人；目睹","cefr":"B1","freq_rank":63,
   "sentence_en":"She witnessed the accident.","sentence_zh":"她目击了这场事故。",
   "aids":{"morphemes":[M("wit","root","知道，看见"),M("ness","suffix","名词后缀")],
     "derivation":"wit(看见、知道)+ness → 亲眼看见知情的人 → 目击者",
     "family":FAM("wit","知道、机智",[W("wit","智慧"),W("witty","诙谐的"),W("wisdom","智慧")]),
     "mnemonic":"wit=看见/知道(想 wit 机智);亲眼看见、知道内情的人,就是 witness 证人;动词=目睹。",
     "forms":[F("witnesses","n.","证人(复数)"),F("witnessed","v.","过去式/过去分词")]}},
  {"word":"incident","phonetic":"ˈɪnsɪdənt","pos":"n.","def":"事件，事故","cefr":"B2","freq_rank":71,
   "sentence_en":"The incident was reported to police.","sentence_zh":"这起事件已报告给警方。",
   "aids":{"morphemes":[M("in","prefix","向内，上"),M("cid","root","落，降"),M("ent","suffix","名词后缀")],
     "derivation":"in(上)+cid(落) → 落到头上发生的事 → 事件",
     "family":FAM("cid/cas","落、降",[W("accident","事故"),W("coincidence","巧合"),W("occasion","场合")]),
     "mnemonic":"cid=落(和 accident 一家);正好落到头上发生的一桩事,就是 incident 事件;比 accident 中性,不一定是坏事。",
     "forms":[F("incidents","n.","事件(复数)"),F("incidental","adj.","附带的")]}},
  {"word":"sector","phonetic":"ˈsektə","pos":"n.","def":"部门，行业；扇形","cefr":"B2","freq_rank":67,
   "sentence_en":"She works in the public sector.","sentence_zh":"她在公共部门工作。",
   "aids":{"morphemes":[M("sect","root","切"),M("or","suffix","名词后缀")],
     "derivation":"sect(切)+or → 切分出来的一块 → 部门、扇形",
     "family":FAM("sect","切",[W("section","部分"),W("insect","昆虫"),W("intersect","相交")]),
     "mnemonic":"sect=切(和 section 一家);从整体切出来的一块领域,就是 sector 部门、行业;圆的'扇形'也是 sector。",
     "forms":[F("sectors","n.","部门(复数)")]}},
  {"word":"faculty","phonetic":"ˈfæklti","pos":"n.","def":"才能，官能；全体教员；(大学的)院系","cefr":"B2","freq_rank":73,
   "sentence_en":"The faculty of speech is uniquely human.","sentence_zh":"语言能力是人类特有的。",
   "aids":{"morphemes":[M("fac","root","做"),M("ulty","suffix","名词后缀")],
     "derivation":"fac(做)+ulty → 能做某事的本领 → 才能;引申'一批有本领的教员'→ 院系",
     "family":FAM("fac/fic","做",[W("facile","容易的"),W("facility","设施"),W("factory","工厂")]),
     "mnemonic":"fac=做(想 facility 便利);人做事的本领=faculty 才能/官能;大学里一批教员及其学科=院系。",
     "forms":[F("faculties","n.","才能；院系(复数)")]}},
  {"word":"personality","phonetic":"ˌpɜːsəˈnælɪti","pos":"n.","def":"个性，人格；名人","cefr":"B1","freq_rank":109,
   "sentence_en":"She has a warm personality.","sentence_zh":"她个性温暖。",
   "aids":{"morphemes":[M("person","root","人"),M("ality","suffix","名词后缀")],
     "derivation":"person(人)+ality → 一个人的独特品性 → 个性",
     "family":FAM("person","人",[W("person","人"),W("personal","个人的"),W("personnel","人员")]),
     "mnemonic":"person(人)+ality;一个人区别于他人的性格总和,就是 personality 个性、人格;电视 personality 名人。",
     "forms":[F("personalities","n.","个性(复数)")]}},
  {"word":"column","phonetic":"ˈkɒləm","pos":"n.","def":"专栏；圆柱；纵列","cefr":"B1","freq_rank":108,
   "sentence_en":"She writes a weekly newspaper column.","sentence_zh":"她每周写一篇报纸专栏。",
   "aids":{"morphemes":[M("column","root","柱(columna)")],
     "derivation":"拉丁 columna'柱';竖直如柱的一条 → 圆柱、纵列;报纸竖排的一条 → 专栏",
     "family":FAM("","相关词",[W("columnist","专栏作家")]),
     "mnemonic":"column=柱;直立的石柱=圆柱;报纸/表格竖直的一条=纵列/专栏(columnist 专栏作家)。",
     "forms":[F("columns","n.","专栏(复数)")]}},
  {"word":"immigrant","phonetic":"ˈɪmɪɡrənt","pos":"n.","def":"(外来)移民","cefr":"B2","freq_rank":105,
   "sentence_en":"Many immigrants settled in the city.","sentence_zh":"许多移民在这座城市定居。",
   "aids":{"morphemes":[M("im","prefix","向内(in)"),M("migr","root","迁移"),M("ant","suffix","…的人")],
     "derivation":"im(向内)+migr(迁移) → 迁入本国的人 → (外来)移民",
     "family":FAM("migr","迁移",[W("migrate","迁徙"),W("emigrant","移居外国者"),W("migration","迁移")]),
     "mnemonic":"migr=迁移(想 migrate);迁入(im-)本国的人=immigrant;迁出(e-)去的人=emigrant,方向相反。",
     "forms":[F("immigration","n.","移民；入境"),F("immigrants","n.","移民(复数)")]}},
  {"word":"gender","phonetic":"ˈdʒendə","pos":"n.","def":"性别","cefr":"B1","freq_rank":35,
   "sentence_en":"The survey asked about age and gender.","sentence_zh":"调查询问了年龄和性别。",
   "aids":{"morphemes":[M("gen","root","产生，种"),M("der","suffix","名词后缀")],
     "derivation":"gen(种、产生)→ 按生育角色划分的类别 → 性别",
     "family":FAM("gen","产生、种类",[W("generate","产生"),W("gene","基因"),W("genre","类型")]),
     "mnemonic":"gen=种/产生(和 gene 基因一家);按生育角色分的'种类',就是 gender 性别。",
     "forms":[F("genders","n.","性别(复数)")]}},
  {"word":"welfare","phonetic":"ˈwelfeə","pos":"n.","def":"福利，福祉；社会救济","cefr":"B2","freq_rank":47,
   "sentence_en":"The government spends money on welfare.","sentence_zh":"政府在福利上花钱。",
   "aids":{"morphemes":[M("wel","root","好(well)"),M("fare","root","行，过活")],
     "derivation":"wel(好)+fare(过活) → 过得好的状态 → 福利、福祉",
     "family":FAM("fare","行、过活",[W("farewell","告别"),W("warfare","战争"),W("fare","车费")]),
     "mnemonic":"well(好)+fare(过活,想 farewell 别时道'一路好走');让人过得好的保障,就是 welfare 福利。",
     "forms":[]}},
  {"word":"landscape","phonetic":"ˈlændskeɪp","pos":"n.","def":"风景，景色；(横向)风景画","cefr":"B1","freq_rank":36,
   "sentence_en":"The painting shows a beautiful landscape.","sentence_zh":"这幅画描绘了美丽的风景。",
   "aids":{"morphemes":[M("land","root","土地"),M("scape","root","景象，形态")],
     "derivation":"land(土地)+scape(景) → 大地呈现的景象 → 风景",
     "family":FAM("scape","景象",[W("seascape","海景"),W("escape","逃离")]),
     "mnemonic":"land(地)+scape(景);一片土地展开的景色,就是 landscape 风景;引申'整体局面'(political landscape 政治格局)。",
     "forms":[F("landscapes","n.","风景(复数)")]}},
  {"word":"conservative","phonetic":"kənˈsɜːvətɪv","pos":"adj./n.","def":"保守的；保守的人","cefr":"B2","freq_rank":38,
   "sentence_en":"He has conservative views.","sentence_zh":"他持保守观点。",
   "aids":{"morphemes":[M("con","prefix","完全"),M("serv","root","保持"),M("ative","suffix","…的")],
     "derivation":"con(完全)+serv(保持) → 力求保持原样的 → 保守的",
     "family":FAM("serv","保持、看守",[W("conserve","保存"),W("preserve","保存"),W("reserve","保留"),W("observe","观察")]),
     "mnemonic":"serv=保持(想 conserve 保存);凡事想保持旧样、不愿变,就是 conservative 保守的。",
     "forms":[F("conserve","v.","保存"),F("conservation","n.","保护")]}},
  {"word":"succeed","phonetic":"səkˈsiːd","pos":"v.","def":"成功；接替","cefr":"B1","freq_rank":85,
   "sentence_en":"Hard work helped him succeed.","sentence_zh":"努力帮助他获得成功。",
   "aids":{"morphemes":[M("suc","prefix","随后(sub)"),M("ceed","root","走")],
     "derivation":"suc(随后)+ceed(走) → 顺利走下去 → 成功","family":FAM("ceed/cess","走",[W("proceed","前进"),W("success","成功"),W("exceed","超过")]),
     "mnemonic":"ceed=走;一路顺走到位=succeed 成功;接前人走=继承。","forms":[F("success","n.","成功")]}},
  # 常见词
  {"word":"prime","phonetic":"praɪm","pos":"adj./n.","def":"首要的，最好的；全盛期","cefr":"B2","freq_rank":26,
   "sentence_en":"That is a prime example.","sentence_zh":"那是个绝佳的例子。",
   "aids":{"morphemes":[M("prim","root","第一"),M("e","suffix","结尾")],
     "derivation":"prim(第一)→ 排第一、最优的 → 首要的",
     "family":FAM("prim","第一",[W("primary","首要的"),W("primitive","原始的"),W("prince","王子")]),
     "mnemonic":"prim=第一(和 primary 一家);排第一、最优质的,就是 prime;prime minister 首相;in one's prime 全盛期。",
     "forms":[F("primarily","adv.","主要地")]}},
  {"word":"blame","phonetic":"bleɪm","pos":"v./n.","def":"责备，归咎于；责任","cefr":"B1","freq_rank":34,
   "sentence_en":"Don't blame me for your mistake.","sentence_zh":"别把你的错怪到我头上。",
   "aids":{"morphemes":[M("blame","root","责备(源自 blaspheme 亵渎)")],
     "derivation":"源自 blaspheme'亵渎、说坏话';把过错说到某人头上 → 责备、归咎",
     "family":FAM("","相关词",[W("blameless","无可指责的")]),
     "mnemonic":"blame 与 blaspheme(亵渎、诋毁)同源;把责任说到某人头上,就是 blame 责备;be to blame 该受责备。",
     "forms":[F("blamed","v.","过去式/过去分词")]}},
  {"word":"match","phonetic":"mætʃ","pos":"n./v.","def":"比赛；火柴；相配，匹敌","cefr":"A2","freq_rank":65,
   "sentence_en":"The colors match well.","sentence_zh":"这些颜色很相配。",
   "aids":{"morphemes":[M("match","root","伴侣，对手(gemaca)")],
     "derivation":"古英语'配偶、对手';旗鼓相当的一对 → 比赛、相配;另一同形词=火柴",
     "family":FAM("","相关词",[W("matching","相配的"),W("mismatch","不匹配")]),
     "mnemonic":"match=旗鼓相当的一对;两队对垒=比赛;两物相称=相配、匹敌;划着取火的小棒=火柴(另源)。",
     "forms":[F("matches","n.","比赛(复数)"),F("matched","v.","过去式/过去分词")]}},
  {"word":"muscle","phonetic":"ˈmʌsl","pos":"n.","def":"肌肉；体力","cefr":"B1","freq_rank":27,
   "sentence_en":"Exercise builds muscle.","sentence_zh":"锻炼能长肌肉。",
   "aids":{"morphemes":[M("mus","root","老鼠(musculus 小鼠)"),M("cle","suffix","小")],
     "derivation":"拉丁 musculus'小老鼠'——古人觉得肌肉隆起似小鼠钻动 → 肌肉",
     "family":FAM("","相关词",[W("muscular","肌肉发达的")]),
     "mnemonic":"muscle 源自'小老鼠'(肌肉鼓动像鼠在皮下窜);一身腱子肉,就是 muscle;muscular 肌肉发达的。",
     "forms":[F("muscles","n.","肌肉(复数)"),F("muscular","adj.","肌肉发达的")]}},
  {"word":"due","phonetic":"djuː","pos":"adj.","def":"到期的；应给的；预期的","cefr":"B1","freq_rank":33,
   "sentence_en":"The rent is due tomorrow.","sentence_zh":"房租明天到期。",
   "aids":{"morphemes":[M("due","root","应偿还(debere)")],
     "derivation":"与 debt(债)同源'应偿';到该付/该做的时候 → 到期的",
     "family":FAM("deb/due","欠、应",[W("debt","债务"),W("duty","责任")]),
     "mnemonic":"due 与 debt/duty 同源'应…';该付款了=到期的;该给的=应给的;due to=由于;the baby is due 预产期到。",
     "forms":[]}},
  {"word":"host","phonetic":"həʊst","pos":"n./v.","def":"主人；主办","cefr":"B1","freq_rank":65,
   "sentence_en":"She hosted a dinner party.","sentence_zh":"她主办了一场晚宴。",
   "aids":{"morphemes":[M("host","root","主客(hospes)")],
     "derivation":"拉丁 hospes'主客';招待客人者 → 主人","family":FAM("hosp","主客",[W("hospital","医院"),W("hotel","旅馆")]),
     "mnemonic":"host 与 hotel/hospital 同源(接待);当东道主招待、主办,就是 host。","forms":[F("hosts","n.","主人(复数)")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 10
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
