#!/usr/bin/env python
# 第三批词:约60个高频词,逐词精做 aids,追加进 data/vocab-seed.json。
# 用法: python tools/gen_seed_batch3.py  (幂等:同名词不会重复追加)
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass

HERE = os.path.dirname(os.path.abspath(__file__))
SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")

def M(text, type, gloss): return {"text": text, "type": type, "gloss": gloss}
def F(word, pos, d): return {"word": word, "pos": pos, "def": d}
def FAM(root, gloss, words): return {"root": root, "gloss": gloss, "words": words}
def W(word, gloss): return {"word": word, "def": gloss}

BATCH3 = [
  # ===== -cur 家族(跑、发生) =====
  {"word":"occur","phonetic":"əˈkɜː","pos":"v.","def":"发生；出现在脑海","cefr":"B1","freq_rank":756,
   "sentence_en":"Earthquakes occur frequently in this region.","sentence_zh":"这个地区地震频繁发生。",
   "aids":{"morphemes":[M("oc","prefix","朝向(ob 变体)"),M("cur","root","跑")],
     "derivation":"oc(朝向)+cur(跑) → 事情朝你跑来 → 发生",
     "family":FAM("cur","跑",[W("current","当前的；水流"),W("recur","再次发生"),W("excursion","远足"),W("currency","货币")]),
     "mnemonic":"cur=跑(想 current 水流);一件事朝你(oc-)跑过来撞上,就是 occur 发生;occur to sb=突然想到。",
     "forms":[F("occurred","v.","过去式/过去分词"),F("occurrence","n.","发生；事件")]}},
  # ===== -dic/-dict 家族(说)扩展 =====
  {"word":"indicate","phonetic":"ˈɪndɪkeɪt","pos":"v.","def":"表明，指示，指出","cefr":"B2","freq_rank":785,
   "sentence_en":"The results indicate a clear trend.","sentence_zh":"结果表明了一个明显的趋势。",
   "aids":{"morphemes":[M("in","prefix","向"),M("dic","root","说"),M("ate","suffix","动词后缀")],
     "derivation":"in(向)+dic(说) → 向人说明、指出 → 表明",
     "family":FAM("dic/dict","说",[W("predict","预测"),W("dictate","口述"),W("contradict","反驳"),W("dedicate","奉献")]),
     "mnemonic":"dic=说(想 predict);向人明白地说出、点出,就是 indicate 表明、指示。",
     "forms":[F("indication","n.","迹象，指示"),F("indicator","n.","指标；指示器")]}},
  # ===== -termin 家族(界限、结束) =====
  {"word":"determine","phonetic":"dɪˈtɜːmɪn","pos":"v.","def":"决定；查明；下决心","cefr":"B2","freq_rank":773,
   "sentence_en":"Your effort will determine your success.","sentence_zh":"你的努力将决定你的成功。",
   "aids":{"morphemes":[M("de","prefix","彻底"),M("termin","root","界限，边界"),M("e","suffix","结尾")],
     "derivation":"de(彻底)+termin(界限) → 彻底划定界限 → 决定、确定",
     "family":FAM("termin","界限、结束",[W("terminal","终点站"),W("terminate","终止"),W("term","期限；术语")]),
     "mnemonic":"termin=界限(想 terminal 终点);把范围彻底(de-)划死、定死,就是 determine 决定、查明。",
     "forms":[F("determined","adj.","坚定的"),F("determination","n.","决心；测定")]}},
  # ===== -spond/-spons 家族(回答、承诺) =====
  {"word":"respond","phonetic":"rɪˈspɒnd","pos":"v.","def":"回应，回答；作出反应","cefr":"B1","freq_rank":920,
   "sentence_en":"She did not respond to my email.","sentence_zh":"她没有回复我的邮件。",
   "aids":{"morphemes":[M("re","prefix","回，返"),M("spond","root","承诺，回答")],
     "derivation":"re(回)+spond(答) → 回过头来答复 → 回应",
     "family":FAM("spond/spons","承诺、回答",[W("response","回应"),W("responsible","负责的"),W("sponsor","赞助者"),W("correspond","符合；通信")]),
     "mnemonic":"spond=回答;对方来一句你回(re-)一句,就是 respond 回应;名词 response。",
     "forms":[F("response","n.","回应"),F("responsive","adj.","反应积极的")]}},
  # ===== -pact/-pel 等 =====
  {"word":"impact","phonetic":"ˈɪmpækt","pos":"n./v.","def":"影响，冲击","cefr":"B2","freq_rank":919,
   "sentence_en":"Social media has a huge impact on teenagers.","sentence_zh":"社交媒体对青少年有巨大影响。",
   "aids":{"morphemes":[M("im","prefix","向内，进入"),M("pact","root","打紧，钉牢")],
     "derivation":"im(向内)+pact(打) → 猛地撞进去 → 冲击、影响",
     "family":FAM("pact","打紧、钉牢",[W("compact","紧凑的"),W("pact","协定")]),
     "mnemonic":"pact=打紧、撞;一股力量向内(im-)狠狠撞上,就是 impact 冲击、影响。",
     "forms":[F("impacts","n.","影响(复数)"),F("impacted","adj.","受影响的")]}},
  # ===== -st/-sta 家族(站、立)扩展 =====
  {"word":"establish","phonetic":"ɪˈstæblɪʃ","pos":"v.","def":"建立，确立；查实","cefr":"B2","freq_rank":896,
   "sentence_en":"The company was established in 1990.","sentence_zh":"这家公司成立于1990年。",
   "aids":{"morphemes":[M("e","prefix","加强"),M("st","root","站，立"),M("abl","root","能"),M("ish","suffix","动词后缀")],
     "derivation":"e+st(站立) → 使稳稳立起来 → 建立、确立",
     "family":FAM("st/sta","站、立",[W("stable","稳定的"),W("constant","恒定的"),W("distance","距离"),W("status","状态")]),
     "mnemonic":"st=站;让一个机构/事实稳稳站立起来,就是 establish 建立、确立。",
     "forms":[F("established","adj.","已确立的"),F("establishment","n.","建立；机构")]}},
  {"word":"standard","phonetic":"ˈstændəd","pos":"n./adj.","def":"标准，规格；标准的","cefr":"B1","freq_rank":806,
   "sentence_en":"The product meets international standards.","sentence_zh":"该产品符合国际标准。",
   "aids":{"morphemes":[M("stand","root","站立"),M("ard","suffix","名词后缀")],
     "derivation":"stand(站立) → 立起来的旗标(供衡量) → 标准",
     "family":FAM("st/sta","站、立",[W("stand","站立"),W("stable","稳定的"),W("establish","建立")]),
     "mnemonic":"古时把军旗(standard)立在阵中作为集结/衡量的基准——立起来的那杆标尺,就是 standard 标准。",
     "forms":[F("standards","n.","标准(复数)"),F("standardize","v.","使标准化")]}},
  # ===== -ident 家族(相同) =====
  {"word":"identify","phonetic":"aɪˈdentɪfaɪ","pos":"v.","def":"识别，辨认；确定","cefr":"B2","freq_rank":770,
   "sentence_en":"Police identified the suspect from a photo.","sentence_zh":"警方通过照片辨认出了嫌疑人。",
   "aids":{"morphemes":[M("ident","root","相同"),M("i","connector","连接"),M("fy","suffix","使…(动词)")],
     "derivation":"ident(相同)+fy(使) → 认出它与已知的是同一个 → 识别",
     "family":FAM("ident","相同",[W("identity","身份"),W("identical","完全相同的"),W("identification","识别")]),
     "mnemonic":"ident=相同(想 identical 一模一样);认出'这个和那个是同一个',就是 identify 识别、确定。",
     "forms":[F("identity","n.","身份，特性"),F("identification","n.","识别；身份证明")]}},
  # ===== -form 家族扩展 =====
  {"word":"former","phonetic":"ˈfɔːmə","pos":"adj.","def":"从前的，前者的","cefr":"B1","freq_rank":442,
   "sentence_en":"The former president gave a speech.","sentence_zh":"前总统发表了演讲。",
   "aids":{"morphemes":[M("form","root","在前(fore 相关)"),M("er","suffix","较…的")],
     "derivation":"form(前)+er → 更靠前的、在前的 → 从前的、前者",
     "family":FAM("form/fore","前",[W("formerly","以前"),W("foremost","最前的")]),
     "mnemonic":"和 fore-(前,如 forehead 前额)相关;时间上更靠前的,就是 former 从前的、前者;反义 latter 后者。",
     "forms":[F("formerly","adv.","从前，以前")]}},
  {"word":"form","phonetic":"fɔːm","pos":"n./v.","def":"形式，形状；表格；形成","cefr":"A2","freq_rank":523,
   "sentence_en":"Please fill in this form.","sentence_zh":"请填写这张表格。",
   "aids":{"morphemes":[M("form","root","形状，形式")],
     "derivation":"拉丁 forma'形状'。名词=形式/表格;动词=形成、组成。",
     "family":FAM("form","形式、形状",[W("reform","改革"),W("transform","改变"),W("uniform","制服"),W("formula","公式")]),
     "mnemonic":"form=形状(词根家族的老祖宗);东西的样子=form 形式;按格式填的纸=form 表格;使成形=form 形成。",
     "forms":[F("formation","n.","形成；队形"),F("formal","adj.","正式的")]}},
  # ===== -pare 家族(准备、摆) =====
  {"word":"prepare","phonetic":"prɪˈpeə","pos":"v.","def":"准备，预备","cefr":"A2","freq_rank":774,
   "sentence_en":"We need time to prepare for the exam.","sentence_zh":"我们需要时间为考试做准备。",
   "aids":{"morphemes":[M("pre","prefix","预先"),M("pare","root","准备，摆放")],
     "derivation":"pre(预先)+pare(备) → 事先备好 → 准备",
     "family":FAM("pare/par","准备、摆",[W("repair","修理(重新备好)"),W("apparatus","设备"),W("separate","分开")]),
     "mnemonic":"pre-(预先)+pare(备)——提前把东西摆好、备齐,就是 prepare 准备。",
     "forms":[F("preparation","n.","准备"),F("prepared","adj.","有准备的")]}},
  # ===== 高频学术动词/名词(词根清晰或有好联想) =====
  {"word":"approach","phonetic":"əˈprəʊtʃ","pos":"v./n.","def":"接近；方法，途径","cefr":"B1","freq_rank":750,
   "sentence_en":"We need a new approach to this problem.","sentence_zh":"我们需要用新方法解决这个问题。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("proach","root","靠近(prope 近)")],
     "derivation":"ap(朝向)+proach(近) → 朝目标靠近 → 接近;引申'切入的路径'→方法",
     "family":FAM("prop/proach","靠近",[W("approximate","大约的"),W("proper","恰当的")]),
     "mnemonic":"proach≈近(prope);朝(ap-)某物靠近,就是 approach 接近;通向问题的那条'近路'=方法、途径。",
     "forms":[F("approaches","n.","方法(复数)"),F("approaching","adj.","即将到来的")]}},
  {"word":"individual","phonetic":"ˌɪndɪˈvɪdʒʊəl","pos":"n./adj.","def":"个人，个体；个别的","cefr":"B1","freq_rank":762,
   "sentence_en":"Each individual has different needs.","sentence_zh":"每个人的需求各不相同。",
   "aids":{"morphemes":[M("in","prefix","不"),M("divid","root","分"),M("ual","suffix","…的")],
     "derivation":"in(不)+divid(分) → 不可再分的最小单位 → 个体、个人",
     "family":FAM("divid/vid","分",[W("divide","分开"),W("division","分割"),W("individual","个体")]),
     "mnemonic":"in-(不)+divid(分)——不能再往下分的一个单位,就是 individual 个体、个人。",
     "forms":[F("individually","adv.","个别地"),F("individuals","n.","个人(复数)")]}},
  {"word":"recognize","phonetic":"ˈrekəɡnaɪz","pos":"v.","def":"认出，识别；承认","cefr":"B1","freq_rank":779,
   "sentence_en":"I didn't recognize you with your new haircut.","sentence_zh":"你换了新发型，我都没认出你。",
   "aids":{"morphemes":[M("re","prefix","再"),M("cogn","root","知道"),M("ize","suffix","使…(动词)")],
     "derivation":"re(再)+cogn(知) → 再次认知出来 → 认出、承认",
     "family":FAM("cogn/gno","知道",[W("cognitive","认知的"),W("ignore","忽视(不知)"),W("diagnose","诊断")]),
     "mnemonic":"cogn=知(想 cognitive 认知);再一次(re-)在脑中确认知道'是它',就是 recognize 认出、承认。",
     "forms":[F("recognition","n.","认出；承认"),F("recognizable","adj.","可辨认的")]}},
  {"word":"argue","phonetic":"ˈɑːɡjuː","pos":"v.","def":"争论，辩论；主张，认为","cefr":"B1","freq_rank":778,
   "sentence_en":"They often argue about money.","sentence_zh":"他们经常为钱争吵。",
   "aids":{"morphemes":[M("argu","root","使清楚，论证"),M("e","suffix","结尾")],
     "derivation":"argu(使清楚) → 摆理由把事说清 → 论证、争论",
     "family":FAM("argu","论证",[W("argument","论点；争吵"),W("arguable","有争议的")]),
     "mnemonic":"argue 是'摆道理'——为把观点说清而各执一词,就是 argue 争论/主张;名词 argument。",
     "forms":[F("argument","n.","论点；争吵"),F("arguably","adv.","可以说")]}},
  {"word":"pressure","phonetic":"ˈpreʃə","pos":"n./v.","def":"压力；施压","cefr":"B1","freq_rank":765,
   "sentence_en":"He is under a lot of pressure at work.","sentence_zh":"他在工作上承受很大压力。",
   "aids":{"morphemes":[M("press","root","压"),M("ure","suffix","名词后缀")],
     "derivation":"press(压)+ure → 压的作用/状态 → 压力",
     "family":FAM("press","压",[W("press","按压"),W("express","表达(压出来)"),W("impress","印象(压入)"),W("compress","压缩")]),
     "mnemonic":"press=压(想 press 按键);压在身上的力=pressure 压力;把想法'压'出来=express 表达。",
     "forms":[F("pressures","n.","压力(复数)"),F("pressured","adj.","有压力的")]}},
  {"word":"amount","phonetic":"əˈmaʊnt","pos":"n./v.","def":"数量，总额；总计","cefr":"A2","freq_rank":782,
   "sentence_en":"A large amount of money was spent.","sentence_zh":"花了一大笔钱。",
   "aids":{"morphemes":[M("a","prefix","朝，向"),M("mount","root","山，登上")],
     "derivation":"a(向)+mount(登高) → 累加登高的总和 → 总额、数量",
     "family":FAM("mount","山、登",[W("mountain","山"),W("mount","登上；安装"),W("surmount","克服")]),
     "mnemonic":"mount=山/往上堆;东西一点点往上堆积成一座'山'的总和,就是 amount 数量、总额。",
     "forms":[F("amounts","n.","数量(复数)"),F("amounted","v.","总计(过去式)")]}},
  {"word":"ability","phonetic":"əˈbɪlɪti","pos":"n.","def":"能力，才能","cefr":"A2","freq_rank":783,
   "sentence_en":"She has the ability to solve hard problems.","sentence_zh":"她有解决难题的能力。",
   "aids":{"morphemes":[M("abil","root","能"),M("ity","suffix","名词后缀")],
     "derivation":"abil(能)+ity → 能做某事的性质 → 能力",
     "family":FAM("abil/able","能",[W("able","能够的"),W("enable","使能够"),W("disability","残疾")]),
     "mnemonic":"abil=able(能);'能做到'这件事本身,就是 ability 能力;反义 -in 变 inability 无能。",
     "forms":[F("able","adj.","能够的"),F("abilities","n.","能力(复数)")]}},
  {"word":"analysis","phonetic":"əˈnæləsɪs","pos":"n.","def":"分析","cefr":"B2","freq_rank":811,
   "sentence_en":"The report gives a detailed analysis of the data.","sentence_zh":"报告对数据做了详细分析。",
   "aids":{"morphemes":[M("ana","prefix","彻底，分开"),M("lys","root","松开，分解"),M("is","suffix","名词后缀")],
     "derivation":"ana(分开)+lys(分解) → 把整体拆开细究 → 分析",
     "family":FAM("lys/lyt","松开、分解",[W("analyze","分析"),W("paralyze","使瘫痪"),W("analyst","分析师")]),
     "mnemonic":"lys=分解、松开;把一整块彻底(ana-)拆解开来看,就是 analysis 分析;动词 analyze,复数 analyses。",
     "forms":[F("analyze","v.","分析"),F("analyst","n.","分析师")]}},
  {"word":"compare","phonetic":"kəmˈpeə","pos":"v.","def":"比较，对照；比作","cefr":"A2","freq_rank":831,
   "sentence_en":"Compare the two pictures and find the differences.","sentence_zh":"比较这两幅图，找出不同。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("par","root","相等，配对"),M("e","suffix","结尾")],
     "derivation":"com(一起)+par(相等) → 把两者并到一起看是否相当 → 比较",
     "family":FAM("par","相等、配对",[W("pair","一对"),W("parity","同等"),W("peer","同辈"),W("compare","比较")]),
     "mnemonic":"par=相等、配对(想 pair 一对);把两样东西一起(com-)并排比对,就是 compare 比较。",
     "forms":[F("comparison","n.","比较"),F("comparable","adj.","可比较的")]}},
  {"word":"design","phonetic":"dɪˈzaɪn","pos":"n./v.","def":"设计；图样；意图","cefr":"A2","freq_rank":834,
   "sentence_en":"The building has an unusual design.","sentence_zh":"这座建筑有着不寻常的设计。",
   "aids":{"morphemes":[M("de","prefix","出，加强"),M("sign","root","记号，标记")],
     "derivation":"de(出)+sign(标记) → 把构想标画出来 → 设计",
     "family":FAM("sign","记号、标志",[W("signal","信号"),W("signature","签名"),W("significant","重要的"),W("assign","分配")]),
     "mnemonic":"sign=标记(想 signature 签名);把脑中构想用记号标画出来,就是 design 设计。",
     "forms":[F("designer","n.","设计师"),F("designed","v.","过去式/过去分词")]}},
  {"word":"section","phonetic":"ˈsekʃən","pos":"n.","def":"部分，部门；剖面","cefr":"B1","freq_rank":818,
   "sentence_en":"This section of the book is about grammar.","sentence_zh":"这本书的这一部分讲语法。",
   "aids":{"morphemes":[M("sect","root","切"),M("ion","suffix","名词后缀")],
     "derivation":"sect(切)+ion → 切下来的一块 → 部分、剖面",
     "family":FAM("sect","切",[W("insect","昆虫(身体分节)"),W("intersect","相交"),W("dissect","解剖")]),
     "mnemonic":"sect=切(想 insect 昆虫,身体一节节被切开);切下来的一块,就是 section 部分、剖面。",
     "forms":[F("sections","n.","部分(复数)"),F("sector","n.","部门，扇区")]}},
  {"word":"region","phonetic":"ˈriːdʒən","pos":"n.","def":"地区，区域；领域","cefr":"B1","freq_rank":793,
   "sentence_en":"This region is famous for its wine.","sentence_zh":"这个地区以葡萄酒闻名。",
   "aids":{"morphemes":[M("reg","root","统治，划界"),M("ion","suffix","名词后缀")],
     "derivation":"reg(统治、划界)+ion → 划定管辖的一片 → 地区",
     "family":FAM("reg","统治、划界",[W("region","地区"),W("regular","规则的"),W("regime","政权"),W("reign","统治")]),
     "mnemonic":"reg=统治、划界(想 reign 统治);被划出来统一管辖的一片地方,就是 region 地区。",
     "forms":[F("regions","n.","地区(复数)"),F("regional","adj.","地区的")]}},
  {"word":"authority","phonetic":"ɔːˈθɒrɪti","pos":"n.","def":"权力，权威；当局","cefr":"B2","freq_rank":832,
   "sentence_en":"The local authority approved the plan.","sentence_zh":"当地政府批准了这项计划。",
   "aids":{"morphemes":[M("author","root","创始者，权威"),M("ity","suffix","名词后缀")],
     "derivation":"author(创始者)+ity → 有创立/裁决之权的地位 → 权威、当局",
     "family":FAM("author","创始者",[W("author","作者"),W("authorize","授权"),W("authentic","真正的")]),
     "mnemonic":"author=作者/创始者;能一锤定音、说了算的地位,就是 authority 权威、当局。",
     "forms":[F("authorities","n.","当局(复数)"),F("authorize","v.","授权")]}},
  {"word":"strategy","phonetic":"ˈstrætɪdʒi","pos":"n.","def":"策略，战略","cefr":"B2","freq_rank":844,
   "sentence_en":"The company needs a new marketing strategy.","sentence_zh":"公司需要新的营销策略。",
   "aids":{"morphemes":[M("strateg","root","将军，统率"),M("y","suffix","名词后缀")],
     "derivation":"希腊 strategos'将军';将军统率全局之术 → 战略",
     "family":FAM("","相关词",[W("strategic","战略的"),W("strategist","战略家")]),
     "mnemonic":"词根来自'将军'(strategos);像将军统筹全局那样谋划,就是 strategy 战略、策略。",
     "forms":[F("strategic","adj.","战略的"),F("strategies","n.","策略(复数)")]}},
  {"word":"environment","phonetic":"ɪnˈvaɪərənmənt","pos":"n.","def":"环境","cefr":"B1","freq_rank":855,
   "sentence_en":"We must protect the environment.","sentence_zh":"我们必须保护环境。",
   "aids":{"morphemes":[M("en","prefix","使处于"),M("viron","root","围绕(环)"),M("ment","suffix","名词后缀")],
     "derivation":"en+viron(围绕) → 围绕在四周的一切 → 环境",
     "family":FAM("viron","围绕",[W("environmental","环境的")]),
     "mnemonic":"viron=围绕(法语 virer'转、环绕');环绕在你四周的所有条件,就是 environment 环境。",
     "forms":[F("environmental","adj.","环境的"),F("environments","n.","环境(复数)")]}},
  {"word":"impact","phonetic":"ˈɪmpækt","pos":"n./v.","def":"影响，冲击","cefr":"B2","freq_rank":919,
   "sentence_en":"Climate change impacts everyone.","sentence_zh":"气候变化影响着每个人。",
   "aids":{"morphemes":[M("im","prefix","向内"),M("pact","root","打紧，钉牢")],
     "derivation":"im(向内)+pact(打) → 撞进去 → 冲击、影响",
     "family":FAM("pact","打紧、钉牢",[W("compact","紧凑的"),W("pact","协定")]),
     "mnemonic":"pact=撞、打紧;力量向内(im-)猛撞,就是 impact 冲击、影响。","forms":[F("impacts","n.","影响(复数)")]}},
  # ===== 高频常见词 =====
  {"word":"point","phonetic":"pɔɪnt","pos":"n./v.","def":"点；要点；指向","cefr":"A1","freq_rank":211,
   "sentence_en":"That's a good point.","sentence_zh":"这一点说得好。",
   "aids":{"morphemes":[M("point","root","尖，刺")],
     "derivation":"拉丁 punctum'刺出的点'。尖端→点→要点;用尖端指→指向。",
     "family":FAM("punct/point","刺、点",[W("appoint","任命"),W("disappoint","使失望"),W("punctual","准时的")]),
     "mnemonic":"point=尖点;笔尖戳一下留个'点';谈话的'点子'=要点;用尖端一指=point 指向。",
     "forms":[F("points","n.","点(复数)"),F("pointed","adj.","尖的；尖锐的")]}},
  {"word":"however","phonetic":"haʊˈevə","pos":"adv./conj.","def":"然而，可是；无论如何","cefr":"A2","freq_rank":284,
   "sentence_en":"The plan is good; however, it is expensive.","sentence_zh":"这个计划不错，然而太贵了。",
   "aids":{"morphemes":[M("how","root","如何"),M("ever","root","无论，究竟")],
     "derivation":"how(如何)+ever(无论) → 无论怎样 → 然而、无论如何",
     "family":FAM("ever","无论、任何时候",[W("whatever","无论什么"),W("whenever","无论何时"),W("whoever","无论谁")]),
     "mnemonic":"how+ever(无论如何);承接转折时'话说回来、可是',就是 however 然而。写作衔接高频词。",
     "forms":[]}},
  {"word":"despite","phonetic":"dɪˈspaɪt","pos":"prep.","def":"尽管，不管","cefr":"B1","freq_rank":742,
   "sentence_en":"Despite the rain, they went out.","sentence_zh":"尽管下雨，他们还是出门了。",
   "aids":{"morphemes":[M("de","prefix","向下"),M("spite","root","看(spic)")],
     "derivation":"de(向下)+spite(看) → 蔑视地往下看、不顾 → 尽管",
     "family":FAM("spic/spect","看",[W("spite","恶意"),W("inspect","检查"),W("despise","鄙视")]),
     "mnemonic":"spite=看(spic);对困难'向下看、不放在眼里'地照做,就是 despite 尽管、不顾;后接名词。",
     "forms":[]}},
  {"word":"beyond","phonetic":"bɪˈjɒnd","pos":"prep./adv.","def":"超过；在…那边","cefr":"B1","freq_rank":746,
   "sentence_en":"The task was beyond his ability.","sentence_zh":"这项任务超出了他的能力。",
   "aids":{"morphemes":[M("be","prefix","加强"),M("yond","root","那边(yon)")],
     "derivation":"be+yond(那边) → 在更远的那一边 → 超过",
     "family":FAM("yon","那边",[W("yonder","那边的")]),
     "mnemonic":"yond=那边(yon);越过界线到更远'那边',就是 beyond 超过、在…之外;beyond one's ability 力所不及。",
     "forms":[]}},
  {"word":"treatment","phonetic":"ˈtriːtmənt","pos":"n.","def":"治疗；对待，处理","cefr":"B1","freq_rank":745,
   "sentence_en":"The patient responded well to treatment.","sentence_zh":"病人对治疗反应良好。",
   "aids":{"morphemes":[M("treat","root","对待，处理"),M("ment","suffix","名词后缀")],
     "derivation":"treat(对待)+ment → 对待/处理的方式 → 治疗、对待",
     "family":FAM("treat","对待、处理",[W("treat","对待；治疗"),W("treaty","条约"),W("retreat","撤退")]),
     "mnemonic":"treat=对待/医治;如何处理、医治一件事/一个人,就是 treatment 治疗、对待。",
     "forms":[F("treat","v.","对待；治疗"),F("treatments","n.","治疗(复数)")]}},
  {"word":"resource","phonetic":"rɪˈsɔːs","pos":"n.","def":"资源；办法","cefr":"B1","freq_rank":769,
   "sentence_en":"Water is a precious natural resource.","sentence_zh":"水是宝贵的自然资源。",
   "aids":{"morphemes":[M("re","prefix","再"),M("source","root","源头，涌出")],
     "derivation":"re(再)+source(源) → 可反复取用的来源 → 资源",
     "family":FAM("sourc/surg","涌起、源",[W("source","来源"),W("surge","激增"),W("resurgence","复兴")]),
     "mnemonic":"source=源头;可以一再(re-)从中取用的源泉,就是 resource 资源。",
     "forms":[F("resources","n.","资源(复数)"),F("resourceful","adj.","足智多谋的")]}},
  {"word":"career","phonetic":"kəˈrɪə","pos":"n.","def":"职业，生涯","cefr":"A2","freq_rank":741,
   "sentence_en":"She had a long career in medicine.","sentence_zh":"她在医学界有着漫长的职业生涯。",
   "aids":{"morphemes":[M("car","root","车，路(carrus)"),M("eer","suffix","名词后缀")],
     "derivation":"car(车、道) → 人生所跑的'车道' → 职业生涯",
     "family":FAM("car","车、跑",[W("car","汽车"),W("carry","运送"),W("cargo","货物")]),
     "mnemonic":"car=车/道(想 car 汽车);你人生这辆车一路跑过的轨道,就是 career 职业生涯。",
     "forms":[F("careers","n.","职业(复数)")]}},
  {"word":"fund","phonetic":"fʌnd","pos":"n./v.","def":"基金，资金；资助","cefr":"B1","freq_rank":754,
   "sentence_en":"The project is funded by the government.","sentence_zh":"该项目由政府出资。",
   "aids":{"morphemes":[M("fund","root","底，基础")],
     "derivation":"拉丁 fundus'底、基础';作为底子的钱 → 基金、资金。",
     "family":FAM("fund/found","底、基础",[W("fundamental","基础的"),W("found","创立"),W("foundation","基础，基金会")]),
     "mnemonic":"fund=底(想 fundamental 根本的);垫底、备用的那笔钱,就是 fund 基金、资金;动词=出资。",
     "forms":[F("funding","n.","资金，拨款"),F("funds","n.","资金(复数)")]}},
  {"word":"individual","phonetic":"ˌɪndɪˈvɪdʒʊəl","pos":"n./adj.","def":"个人，个体；个别的","cefr":"B1","freq_rank":762,
   "sentence_en":"We respect individual freedom.","sentence_zh":"我们尊重个人自由。",
   "aids":{"morphemes":[M("in","prefix","不"),M("divid","root","分"),M("ual","suffix","…的")],
     "derivation":"in(不)+divid(分) → 不可再分的单位 → 个体",
     "family":FAM("divid","分",[W("divide","分开"),W("division","分割")]),
     "mnemonic":"in-(不)+divid(分)——分不下去的最小单位,就是 individual 个体。","forms":[F("individually","adv.","个别地")]}},
  {"word":"character","phonetic":"ˈkærɪktə","pos":"n.","def":"性格；人物；字符","cefr":"B1","freq_rank":786,
   "sentence_en":"She has a strong character.","sentence_zh":"她性格坚强。",
   "aids":{"morphemes":[M("charact","root","刻，雕(希腊 kharakter)"),M("er","suffix","名词后缀")],
     "derivation":"charact(刻)→ 刻印在心的印记 → 性格;刻出的符号 → 字符;戏里刻画的角色 → 人物",
     "family":FAM("","相关词",[W("characteristic","特征"),W("characterize","刻画")]),
     "mnemonic":"词根意为'刻印';刻在骨子里的印记=character 性格;刻写的符号=字符;书里刻画的=人物。",
     "forms":[F("characteristic","n.","特征"),F("characters","n.","人物；字符(复数)")]}},
  {"word":"wonder","phonetic":"ˈwʌndə","pos":"v./n.","def":"想知道；惊奇；奇迹","cefr":"A2","freq_rank":790,
   "sentence_en":"I wonder what happened.","sentence_zh":"我想知道发生了什么。",
   "aids":{"morphemes":[M("wonder","root","惊奇")],
     "derivation":"古英语 wundor'奇迹、惊奇'。惊奇→好奇想知道;了不起的事→奇迹。",
     "family":FAM("","相关词",[W("wonderful","极好的"),W("wondrous","奇妙的")]),
     "mnemonic":"心里又惊又奇、忍不住想弄明白,就是 wonder 想知道/惊奇;令人惊叹的=wonderful;世界奇迹=wonder。",
     "forms":[F("wonderful","adj.","精彩的，极好的"),F("wondered","v.","过去式/过去分词")]}},
  {"word":"attack","phonetic":"əˈtæk","pos":"n./v.","def":"攻击，进攻；抨击","cefr":"A2","freq_rank":791,
   "sentence_en":"The army launched an attack at dawn.","sentence_zh":"军队在黎明发动了进攻。",
   "aids":{"morphemes":[M("at","prefix","朝向(ad 变体)"),M("tack","root","钉，扣(接触)")],
     "derivation":"at(朝向)+tack(扣、接触) → 朝对方扑上去接触 → 攻击",
     "family":FAM("tack/tact","接触、钉",[W("attach","附上"),W("contact","接触"),W("tackle","应对，抢断")]),
     "mnemonic":"tack=接触、扣(想 attach 附着);朝(at-)敌人扑上去动手,就是 attack 攻击;反义 defend 防御。",
     "forms":[F("attacks","n.","攻击(复数)"),F("attacker","n.","攻击者")]}},
  {"word":"physical","phonetic":"ˈfɪzɪkəl","pos":"adj.","def":"身体的；物质的；物理的","cefr":"B1","freq_rank":802,
   "sentence_en":"Regular physical exercise is important.","sentence_zh":"规律的身体锻炼很重要。",
   "aids":{"morphemes":[M("phys","root","自然，身体"),M("ical","suffix","…的")],
     "derivation":"phys(自然、身体)+ical → 与自然物质/身体有关的 → 身体的、物理的",
     "family":FAM("phys","自然、身体",[W("physics","物理学"),W("physician","内科医生"),W("physique","体格")]),
     "mnemonic":"phys=自然/身体(想 physics 物理);关乎肉体或物质世界的,就是 physical 身体的、物质的、物理的。",
     "forms":[F("physically","adv.","身体上；物理上"),F("physics","n.","物理学")]}},
  {"word":"general","phonetic":"ˈdʒenərəl","pos":"adj./n.","def":"总的，普遍的；将军","cefr":"A2","freq_rank":804,
   "sentence_en":"In general, the plan is good.","sentence_zh":"总的来说，这个计划不错。",
   "aids":{"morphemes":[M("gener","root","种类，产生"),M("al","suffix","…的")],
     "derivation":"gener(种类)+al → 涵盖整个种类的 → 全体的、普遍的",
     "family":FAM("gener/gen","产生、种类",[W("generate","产生"),W("generation","一代"),W("genre","类型"),W("genetic","基因的")]),
     "mnemonic":"gener=种类(想 genre 类型);适用于一整类、大多数情况的,就是 general 总的、普遍的;in general 总的来说。",
     "forms":[F("generally","adv.","一般地，通常"),F("generalize","v.","概括")]}},
  {"word":"crime","phonetic":"kraɪm","pos":"n.","def":"罪行，犯罪","cefr":"B1","freq_rank":828,
   "sentence_en":"Violent crime has decreased.","sentence_zh":"暴力犯罪有所下降。",
   "aids":{"morphemes":[M("crim","root","罪，控告"),M("e","suffix","结尾")],
     "derivation":"拉丁 crimen'控告、罪'。→ 罪行、犯罪。",
     "family":FAM("crim","罪、控告",[W("criminal","罪犯；犯罪的"),W("incriminate","归罪于")]),
     "mnemonic":"crim=罪(想 criminal 罪犯);触犯法律的行为,就是 crime 罪行;做这事的人=criminal。",
     "forms":[F("criminal","n.","罪犯"),F("crimes","n.","罪行(复数)")]}},
  {"word":"stage","phonetic":"steɪdʒ","pos":"n./v.","def":"阶段；舞台；上演","cefr":"A2","freq_rank":829,
   "sentence_en":"The project is at an early stage.","sentence_zh":"项目处于早期阶段。",
   "aids":{"morphemes":[M("stage","root","站立处，台(st)")],
     "derivation":"与 st'站'相关;可站立/停留的台或段落 → 舞台、阶段。",
     "family":FAM("st/sta","站、立",[W("stand","站立"),W("station","站"),W("stable","稳定的")]),
     "mnemonic":"和 st(站)一家;供人站上去表演的台=stage 舞台;一段可'驻停'的进程=stage 阶段。",
     "forms":[F("stages","n.","阶段(复数)"),F("staged","v.","上演(过去式)")]}},
  {"word":"various","phonetic":"ˈveəriəs","pos":"adj.","def":"各种各样的，不同的","cefr":"B1","freq_rank":859,
   "sentence_en":"The shop sells various kinds of bread.","sentence_zh":"这家店卖各种各样的面包。",
   "aids":{"morphemes":[M("vari","root","变化"),M("ous","suffix","…的")],
     "derivation":"vari(变化)+ous → 有变化、多样的 → 各种各样的",
     "family":FAM("vari","变化",[W("vary","变化"),W("variety","多样性"),W("variable","可变的"),W("various","各种的")]),
     "mnemonic":"vari=变(想 vary 变化);花样繁多、各不相同的,就是 various 各种各样的。",
     "forms":[F("vary","v.","变化"),F("variety","n.","多样性；种类")]}},
  {"word":"entire","phonetic":"ɪnˈtaɪə","pos":"adj.","def":"整个的，全部的","cefr":"B1","freq_rank":868,
   "sentence_en":"She ate the entire cake.","sentence_zh":"她把整个蛋糕都吃了。",
   "aids":{"morphemes":[M("en","prefix","不(in 变体)"),M("tire","root","触碰(tang)")],
     "derivation":"en(不)+tire(触、损) → 未被触动、完好无缺的 → 完整的、整个的",
     "family":FAM("tire/tang","触碰",[W("integrity","完整；正直"),W("intact","完整无损的"),W("tangible","可触的")]),
     "mnemonic":"与 integrity/intact 同源;'没被动过一分、完好'的,就是 entire 整个的、全部的。",
     "forms":[F("entirely","adv.","完全地"),F("entirety","n.","全部")]}},
  {"word":"claim","phonetic":"kleɪm","pos":"v./n.","def":"声称；索要，认领","cefr":"B1","freq_rank":874,
   "sentence_en":"He claims to be an expert.","sentence_zh":"他声称自己是专家。",
   "aids":{"morphemes":[M("claim","root","喊，叫(clam)")],
     "derivation":"拉丁 clamare'喊叫';大声主张 → 声称;喊着要回 → 索要、认领。",
     "family":FAM("claim/clam","喊、叫",[W("exclaim","惊呼"),W("proclaim","宣告"),W("declare","宣布")]),
     "mnemonic":"claim=喊(想 exclaim 惊呼);大声主张'是这样'=claim 声称;喊着'这是我的'=claim 认领、索赔。",
     "forms":[F("claims","n.","主张(复数)"),F("claimed","v.","过去式/过去分词")]}},
  {"word":"legal","phonetic":"ˈliːɡəl","pos":"adj.","def":"法律的；合法的","cefr":"B1","freq_rank":883,
   "sentence_en":"It is not legal to park here.","sentence_zh":"在这里停车是不合法的。",
   "aids":{"morphemes":[M("leg","root","法律"),M("al","suffix","…的")],
     "derivation":"leg(法律)+al → 与法律有关的、法律允许的 → 合法的",
     "family":FAM("leg","法律",[W("legislation","立法"),W("legitimate","合法的"),W("legal","合法的")]),
     "mnemonic":"leg=法(想 legislation 立法);合乎法律的,就是 legal 合法的;加 il- 变 illegal 非法的。",
     "forms":[F("legally","adv.","法律上，合法地"),F("illegal","adj.","非法的")]}},
  {"word":"avoid","phonetic":"əˈvɔɪd","pos":"v.","def":"避免，回避","cefr":"A2","freq_rank":908,
   "sentence_en":"Try to avoid making the same mistake.","sentence_zh":"尽量避免犯同样的错误。",
   "aids":{"morphemes":[M("a","prefix","离开"),M("void","root","空的")],
     "derivation":"a(离)+void(空) → 让开、腾空 → 避免、回避",
     "family":FAM("void/vac","空",[W("void","空的；无效的"),W("vacant","空的"),W("vacuum","真空")]),
     "mnemonic":"void=空(想 vacant 空的);把自己从某事里抽空、让开,就是 avoid 避免、回避。",
     "forms":[F("avoided","v.","过去式/过去分词"),F("avoidance","n.","回避")]}},
  {"word":"imagine","phonetic":"ɪˈmædʒɪn","pos":"v.","def":"想象，设想","cefr":"A2","freq_rank":909,
   "sentence_en":"Imagine living on the moon.","sentence_zh":"想象一下住在月球上。",
   "aids":{"morphemes":[M("imag","root","像，图像"),M("ine","suffix","动词后缀")],
     "derivation":"imag(像)+ine → 在脑中造出图像 → 想象",
     "family":FAM("imag","像、模仿",[W("image","形象"),W("imaginary","虚构的"),W("imagination","想象力")]),
     "mnemonic":"imag=像(想 image 图像);在脑海里造出一幅画面,就是 imagine 想象。",
     "forms":[F("imagination","n.","想象力"),F("imaginary","adj.","虚构的")]}},
  {"word":"theory","phonetic":"ˈθɪəri","pos":"n.","def":"理论，学说","cefr":"B1","freq_rank":918,
   "sentence_en":"In theory, the plan should work.","sentence_zh":"从理论上讲，这个计划应该行得通。",
   "aids":{"morphemes":[M("theor","root","观察，思索"),M("y","suffix","名词后缀")],
     "derivation":"希腊 theoria'观察、沉思';对事物观察思索后的系统看法 → 理论",
     "family":FAM("theor","观察、思索",[W("theoretical","理论的"),W("theorist","理论家")]),
     "mnemonic":"词根意为'观察沉思';经过反复思索归纳出的系统学说,就是 theory 理论;in theory 理论上。",
     "forms":[F("theoretical","adj.","理论的"),F("theories","n.","理论(复数)")]}},
  {"word":"management","phonetic":"ˈmænɪdʒmənt","pos":"n.","def":"管理，经营；管理层","cefr":"B1","freq_rank":906,
   "sentence_en":"Good time management is essential.","sentence_zh":"良好的时间管理至关重要。",
   "aids":{"morphemes":[M("man","root","手"),M("age","root","做"),M("ment","suffix","名词后缀")],
     "derivation":"man(手)+age → 用手操持、驾驭 → 管理",
     "family":FAM("man","手",[W("manage","管理"),W("manual","手册；手动的"),W("manufacture","制造"),W("manipulate","操纵")]),
     "mnemonic":"man=手(想 manual 手动);用手把事务操持、驾驭好,就是 management 管理;动词 manage。",
     "forms":[F("manage","v.","管理；设法做到"),F("manager","n.","经理")]}},
  {"word":"stock","phonetic":"stɒk","pos":"n./v.","def":"存货，库存；股票","cefr":"B1","freq_rank":740,
   "sentence_en":"The item is out of stock.","sentence_zh":"这件商品缺货了。",
   "aids":{"morphemes":[M("stock","root","树干，储备")],
     "derivation":"本义'树干、根株';由'根本储备'引申为存货、股本、股票。",
     "family":FAM("","相关词",[W("stockpile","囤积"),W("livestock","牲畜")]),
     "mnemonic":"stock=树干/根株→'家底储备';仓库里的家底=库存;公司的资本份额=股票;out of stock=缺货。",
     "forms":[F("stocks","n.","股票；存货(复数)"),F("stocked","v.","储备(过去式)")]}},
  {"word":"check","phonetic":"tʃek","pos":"v./n.","def":"检查，核对；制止；支票","cefr":"A1","freq_rank":854,
   "sentence_en":"Please check your answers.","sentence_zh":"请核对你的答案。",
   "aids":{"morphemes":[M("check","root","国王(棋),制止")],
     "derivation":"源自国际象棋'将军(check)'——迫使对方停手核验局面 → 制止、检查。",
     "family":FAM("","相关词",[W("checkpoint","检查站"),W("checklist","清单")]),
     "mnemonic":"来自象棋'将军'(check)——喝止对方、逼你核查局面;由此=检查、核对、制止。",
     "forms":[F("checked","v.","过去式/过去分词"),F("checking","n.","检查")]}},
  {"word":"firm","phonetic":"fɜːm","pos":"adj./n.","def":"坚定的，牢固的；公司","cefr":"B1","freq_rank":902,
   "sentence_en":"She gave a firm answer.","sentence_zh":"她给出了坚定的回答。",
   "aids":{"morphemes":[M("firm","root","坚固")],
     "derivation":"拉丁 firmus'坚固';形容词=坚定牢固;名词'签字确立的商号'→ 公司。",
     "family":FAM("firm","坚固",[W("confirm","确认"),W("affirm","断言"),W("infirm","虚弱的")]),
     "mnemonic":"firm=坚固;立场牢不可动=firm 坚定的;把它再夯实=confirm 确认;签字定下的商号=firm 公司。",
     "forms":[F("firmly","adv.","坚定地"),F("firms","n.","公司(复数)")]}},
  {"word":"trial","phonetic":"ˈtraɪəl","pos":"n.","def":"审判；试验；考验","cefr":"B2","freq_rank":898,
   "sentence_en":"The new drug is undergoing clinical trials.","sentence_zh":"这种新药正在进行临床试验。",
   "aids":{"morphemes":[M("tri","root","试(try)"),M("al","suffix","名词后缀")],
     "derivation":"tri(试)+al → 尝试/查验的过程 → 试验、审判",
     "family":FAM("tri/try","试",[W("try","尝试"),W("retry","重试")]),
     "mnemonic":"tri=try(试);对药物/被告的检验过程,就是 trial 试验、审判;trial and error 反复试错。",
     "forms":[F("trials","n.","试验(复数)"),F("trial","v.","试验")]}},
  {"word":"cell","phonetic":"sel","pos":"n.","def":"细胞；小房间；电池","cefr":"B1","freq_rank":895,
   "sentence_en":"The human body is made of cells.","sentence_zh":"人体由细胞构成。",
   "aids":{"morphemes":[M("cell","root","小室(cella)")],
     "derivation":"拉丁 cella'小室、储藏室';引申最小的'小室'→ 细胞、牢房、电池单元。",
     "family":FAM("cell","小室",[W("cellar","地窖"),W("cellular","细胞的；蜂窝的")]),
     "mnemonic":"cell=小室(想 cellar 地窖);生物最小的'小房间'=细胞;关人的小室=牢房;电的单元=电池。",
     "forms":[F("cells","n.","细胞(复数)"),F("cellular","adj.","细胞的")]}},
  {"word":"lead","phonetic":"liːd","pos":"v./n.","def":"带领，引导；领先；铅","cefr":"A2","freq_rank":318,
   "sentence_en":"She will lead the team.","sentence_zh":"她将带领这个团队。",
   "aids":{"morphemes":[M("lead","root","引导")],
     "derivation":"古英语 lǽdan'引导'。带领→领先;另一同形词 lead=铅(读 /led/)。",
     "family":FAM("","相关词",[W("leader","领导者"),W("leadership","领导力")]),
     "mnemonic":"lead=引导;走在前面带路=lead 带领、领先(过去式不规则 led);注意同形异义词 lead /led/=铅。",
     "forms":[F("led","v.","过去式/过去分词"),F("leader","n.","领导者")]}},
  {"word":"level","phonetic":"ˈlevl","pos":"n./adj.","def":"水平；级别；平的","cefr":"A2","freq_rank":338,
   "sentence_en":"Water finds its own level.","sentence_zh":"水会自己找平。",
   "aids":{"morphemes":[M("lev","root","抬起，轻(平衡)"),M("el","suffix","名词后缀")],
     "derivation":"lev(平衡、水准仪)→ 水平面、水平、级别",
     "family":FAM("lev","抬起、轻",[W("elevate","抬高"),W("elevator","电梯"),W("relevant","相关的")]),
     "mnemonic":"lev=抬/平衡(想 elevator 电梯上抬);水准仪测出的水平面=level 水平;高低层次=级别。",
     "forms":[F("levels","n.","级别(复数)"),F("leveled","v.","弄平(过去式)")]}},
  {"word":"military","phonetic":"ˈmɪlɪtəri","pos":"adj./n.","def":"军事的；军队","cefr":"B1","freq_rank":474,
   "sentence_en":"He joined the military at eighteen.","sentence_zh":"他十八岁参军。",
   "aids":{"morphemes":[M("milit","root","士兵，战斗"),M("ary","suffix","…的")],
     "derivation":"milit(士兵)+ary → 与士兵、战斗有关的 → 军事的",
     "family":FAM("milit","士兵、战斗",[W("militant","好斗的"),W("militia","民兵")]),
     "mnemonic":"milit=士兵(想 militia 民兵);和当兵打仗有关的一切,就是 military 军事的、军队。",
     "forms":[F("militant","adj.","好斗的")]}},
  {"word":"carry","phonetic":"ˈkæri","pos":"v.","def":"携带，运送；支撑","cefr":"A1","freq_rank":487,
   "sentence_en":"Can you help me carry these bags?","sentence_zh":"你能帮我拎这些包吗？",
   "aids":{"morphemes":[M("carr","root","车，运(carrus)"),M("y","suffix","结尾")],
     "derivation":"carr(车)→ 用车运 → 携带、运送",
     "family":FAM("car","车、运",[W("car","汽车"),W("cargo","货物"),W("career","生涯"),W("carriage","马车")]),
     "mnemonic":"carr=车(想 car 汽车、cargo 货物);像用车装着运走,就是 carry 携带;carry out=执行。",
     "forms":[F("carried","v.","过去式/过去分词"),F("carrier","n.","运载工具；携带者")]}},
  {"word":"focus","phonetic":"ˈfəʊkəs","pos":"n./v.","def":"焦点；集中，聚焦","cefr":"B1","freq_rank":688,
   "sentence_en":"Try to focus on your work.","sentence_zh":"尽量专注于你的工作。",
   "aids":{"morphemes":[M("focus","root","炉灶，焦点(拉丁)")],
     "derivation":"拉丁 focus'炉灶'——光/热汇聚之处 → 焦点;使汇聚 → 集中。",
     "family":FAM("","相关词",[W("focal","焦点的")]),
     "mnemonic":"focus 本义'炉灶'(火光汇聚处);光线/注意力汇到一点=focus 焦点、集中;focus on=专注于。",
     "forms":[F("focused","v.","过去式/过去分词"),F("focuses","n.","焦点(复数)")]}},
  {"word":"data","phonetic":"ˈdeɪtə","pos":"n.","def":"数据，资料","cefr":"A2","freq_rank":559,
   "sentence_en":"We need more data to decide.","sentence_zh":"我们需要更多数据才能决定。",
   "aids":{"morphemes":[M("dat","root","给出"),M("a","suffix","复数结尾")],
     "derivation":"拉丁 datum'给出之物'的复数 data → 已知给出的资料 → 数据",
     "family":FAM("dat/don","给",[W("date","日期"),W("donate","捐赠"),W("edit","编辑")]),
     "mnemonic":"dat=给(想 date 给定的日期);被给出、已知的一堆事实,就是 data 数据(本是 datum 的复数)。",
     "forms":[F("database","n.","数据库")]}},
  {"word":"course","phonetic":"kɔːs","pos":"n.","def":"课程；过程；路线","cefr":"A2","freq_rank":418,
   "sentence_en":"I'm taking an English course.","sentence_zh":"我在上一门英语课。",
   "aids":{"morphemes":[M("cours","root","跑，流(cur)"),M("e","suffix","结尾")],
     "derivation":"cours(跑)→ 跑过的路径/进程 → 路线、过程;按顺序跑的一段学习 → 课程",
     "family":FAM("cur/cours","跑、流",[W("current","当前的"),W("occur","发生"),W("excursion","远足")]),
     "mnemonic":"cours=跑(同 cur,想 current);一路跑过的路径=course 路线/过程;成套跑完的学习=course 课程;of course 当然。",
     "forms":[F("courses","n.","课程(复数)")]}},
  {"word":"event","phonetic":"ɪˈvent","pos":"n.","def":"事件，大事；比赛项目","cefr":"A2","freq_rank":525,
   "sentence_en":"The wedding was a happy event.","sentence_zh":"婚礼是一件喜事。",
   "aids":{"morphemes":[M("e","prefix","出，向外"),M("vent","root","来")],
     "derivation":"e(出)+vent(来) → 冒出来发生的事 → 事件",
     "family":FAM("vent","来",[W("invent","发明(来到心中)"),W("prevent","预防"),W("adventure","冒险"),W("convention","惯例")]),
     "mnemonic":"vent=来(想 prevent 预防);冒出来、降临的一件事,就是 event 事件;in the event of=万一。",
     "forms":[F("events","n.","事件(复数)"),F("eventual","adj.","最终的")]}},
]


def main():
    with open(SEED, encoding="utf-8") as f:
        data = json.load(f)
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH3:
        if w["word"].lower() in existing:
            skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 3
    with open(SEED, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"追加 {len(added)} 词;跳过(已存在) {len(skipped)}: {skipped}")
    print(f"seed 现共 {len(data['words'])} 词")


if __name__ == "__main__":
    main()
