#!/usr/bin/env python
# 第五批词:约55个高频词,逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -sist/-st 站
  {"word":"exist","phonetic":"ɪɡˈzɪst","pos":"v.","def":"存在，生存","cefr":"B1","freq_rank":39,
   "sentence_en":"Do you believe ghosts exist?","sentence_zh":"你相信有鬼存在吗？",
   "aids":{"morphemes":[M("ex","prefix","向外，出来"),M("ist","root","站(sist)")],
     "derivation":"ex(出来)+ist(站) → 站出来、显现在世上 → 存在",
     "family":FAM("sist/st","站、立",[W("insist","坚持"),W("resist","抵抗"),W("assist","协助"),W("consist","组成")]),
     "mnemonic":"ist=站(sist);从无中站(ist)出来(ex-)立在世上,就是 exist 存在;名词 existence。",
     "forms":[F("existence","n.","存在"),F("existing","adj.","现有的")]}},
  {"word":"resident","phonetic":"ˈrezɪdənt","pos":"n./adj.","def":"居民；居住的","cefr":"B1","freq_rank":70,
   "sentence_en":"Local residents protested the plan.","sentence_zh":"当地居民抗议这项计划。",
   "aids":{"morphemes":[M("re","prefix","反复，一直"),M("sid","root","坐"),M("ent","suffix","…的人")],
     "derivation":"re(一直)+sid(坐) → 一直坐(住)在某地的人 → 居民",
     "family":FAM("sid/sess","坐",[W("reside","居住"),W("preside","主持(坐主位)"),W("session","会期")]),
     "mnemonic":"sid=坐(想 preside 坐主席位主持);长期坐镇、住在此地的人,就是 resident 居民。",
     "forms":[F("reside","v.","居住"),F("residence","n.","住所")]}},
  {"word":"status","phonetic":"ˈsteɪtəs","pos":"n.","def":"地位，身份；状态","cefr":"B2","freq_rank":100,
   "sentence_en":"Marriage changed her legal status.","sentence_zh":"婚姻改变了她的法律身份。",
   "aids":{"morphemes":[M("stat","root","站，立"),M("us","suffix","名词后缀")],
     "derivation":"stat(站)+us → 所站的位置/状况 → 地位、状态",
     "family":FAM("st/sta","站、立",[W("state","状态"),W("statue","雕像"),W("stable","稳定的"),W("station","站")]),
     "mnemonic":"stat=站;你在社会里'站'的那个位置,就是 status 地位、身份;当前所处状况=状态。",
     "forms":[F("statuses","n.","状态(复数)")]}},
  # -sess/-sid
  {"word":"presence","phonetic":"ˈprezns","pos":"n.","def":"出席，在场；存在","cefr":"B2","freq_rank":72,
   "sentence_en":"Your presence at the meeting is required.","sentence_zh":"要求你出席会议。",
   "aids":{"morphemes":[M("pre","prefix","在前"),M("s","root","在(esse)"),M("ence","suffix","名词后缀")],
     "derivation":"pre(在前)+ess(在) → 人在跟前 → 出席、在场",
     "family":FAM("es/pres","在、是",[W("present","在场的；礼物"),W("absence","缺席")]),
     "mnemonic":"和 present(在场的)同源;人就在眼前、亲身在场,就是 presence 出席;反义 absence 缺席。",
     "forms":[F("present","adj.","在场的"),F("presences","n.","存在(复数)")]}},
  # -vis/-vid 看
  {"word":"vision","phonetic":"ˈvɪʒən","pos":"n.","def":"视力；愿景；幻象","cefr":"B2","freq_rank":63,
   "sentence_en":"The leader had a clear vision for the future.","sentence_zh":"这位领导对未来有清晰的愿景。",
   "aids":{"morphemes":[M("vis","root","看"),M("ion","suffix","名词后缀")],
     "derivation":"vis(看)+ion → 看的能力/所见 → 视力、愿景",
     "family":FAM("vis/vid","看",[W("visible","可见的"),W("visit","拜访"),W("evidence","证据"),W("supervise","监督")]),
     "mnemonic":"vis=看(想 visible);眼睛看的能力=视力;心里'看'到的未来蓝图=愿景,就是 vision。",
     "forms":[F("visual","adj.","视觉的"),F("visionary","adj.","有远见的")]}},
  # -sci 知
  {"word":"conference","phonetic":"ˈkɒnfərəns","pos":"n.","def":"会议，研讨会","cefr":"B1","freq_rank":18,
   "sentence_en":"She is attending a medical conference.","sentence_zh":"她正在参加一场医学会议。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("fer","root","带，拿"),M("ence","suffix","名词后缀")],
     "derivation":"con(一起)+fer(带) → 把大家/意见带到一起 → 会议",
     "family":FAM("fer","带、拿",[W("refer","提及"),W("offer","提供"),W("transfer","转移"),W("prefer","更喜欢")]),
     "mnemonic":"fer=带;把众人一起(con-)带到一处交流,就是 conference 会议。",
     "forms":[F("conferences","n.","会议(复数)")]}},
  # -dict/-dic 说
  {"word":"mention","phonetic":"ˈmenʃən","pos":"v./n.","def":"提到，提及","cefr":"A2","freq_rank":19,
   "sentence_en":"He mentioned your name in the report.","sentence_zh":"他在报告里提到了你的名字。",
   "aids":{"morphemes":[M("ment","root","心，想；提"),M("ion","suffix","名词后缀")],
     "derivation":"ment(想、提)+ion → 把心里想到的说出一句 → 提及",
     "family":FAM("ment","心、想",[W("mental","精神的"),W("comment","评论"),W("mentor","导师")]),
     "mnemonic":"ment=心/提及;顺口把想到的'提'一句,就是 mention;don't mention it 不客气。",
     "forms":[F("mentioned","v.","过去式/过去分词")]}},
  # -sti/-titude 高频
  {"word":"attitude","phonetic":"ˈætɪtjuːd","pos":"n.","def":"态度，看法；姿态","cefr":"A2","freq_rank":53,
   "sentence_en":"A positive attitude helps you succeed.","sentence_zh":"积极的态度有助于成功。",
   "aids":{"morphemes":[M("apt","root","适合，倾向(apt)"),M("itude","suffix","名词后缀")],
     "derivation":"与 aptitude(倾向)同源;心里对事物的倾向姿态 → 态度",
     "family":FAM("apt/att","适合、倾向",[W("apt","易于的"),W("aptitude","天资，倾向")]),
     "mnemonic":"与 aptitude(倾向)同源;你对一件事内心的倾向、摆出的姿态,就是 attitude 态度。",
     "forms":[F("attitudes","n.","态度(复数)")]}},
  # -spec 看
  {"word":"species","phonetic":"ˈspiːʃiːz","pos":"n.","def":"物种，种类","cefr":"B1","freq_rank":75,
   "sentence_en":"This species of bird is endangered.","sentence_zh":"这种鸟濒临灭绝。",
   "aids":{"morphemes":[M("spec","root","看，种类"),M("ies","suffix","名词后缀")],
     "derivation":"spec(种类)→ 按外观区分的一类 → 物种",
     "family":FAM("spec","看、种类",[W("special","特别的"),W("specific","特定的"),W("inspect","检查")]),
     "mnemonic":"spec=种类/看;按外形'看'出来归为一类的生物,就是 species 物种;单复数同形。",
     "forms":[]}},
  # 高频名词(词根清晰)
  {"word":"direction","phonetic":"dɪˈrekʃən","pos":"n.","def":"方向；指导；说明","cefr":"A2","freq_rank":11,
   "sentence_en":"We walked in the wrong direction.","sentence_zh":"我们走错了方向。",
   "aids":{"morphemes":[M("di","prefix","分开，朝"),M("rect","root","直，引导"),M("ion","suffix","名词后缀")],
     "derivation":"di(朝)+rect(引导) → 引导所朝的路 → 方向、指导",
     "family":FAM("rect","直、引导",[W("direct","直接的"),W("correct","正确的"),W("erect","竖立"),W("rectangle","矩形")]),
     "mnemonic":"rect=直/引导(想 correct 纠正到正);把路引直、指向何方,就是 direction 方向、指导。",
     "forms":[F("direct","adj.","直接的"),F("directions","n.","指示(复数)")]}},
  {"word":"institution","phonetic":"ˌɪnstɪˈtjuːʃən","pos":"n.","def":"机构；制度；惯例","cefr":"B2","freq_rank":21,
   "sentence_en":"Universities are educational institutions.","sentence_zh":"大学是教育机构。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("stitut","root","建立，站(st)"),M("ion","suffix","名词后缀")],
     "derivation":"in+stitut(建立) → 建立起来长久存在的组织/规矩 → 机构、制度",
     "family":FAM("st/stitut","站、建立",[W("constitute","构成"),W("substitute","替代"),W("statute","法令")]),
     "mnemonic":"stitut=建立(st 站的家族);建立起来长期运作的组织或规矩,就是 institution 机构、制度。",
     "forms":[F("institutional","adj.","机构的")]}},
  {"word":"property","phonetic":"ˈprɒpəti","pos":"n.","def":"财产，房产；性质，属性","cefr":"B1","freq_rank":23,
   "sentence_en":"The house is valuable property.","sentence_zh":"这栋房子是值钱的财产。",
   "aids":{"morphemes":[M("propr","root","自己的"),M("ty","suffix","名词后缀")],
     "derivation":"propr(自己的)→ 属于自己的东西 → 财产;事物'自有'的特点 → 属性",
     "family":FAM("propr","自己的",[W("proper","恰当的"),W("appropriate","适当的"),W("proprietor","业主")]),
     "mnemonic":"propr=自己的(想 proper);归自己所有的东西=财产;事物本身固有的特点=属性,都是 property。",
     "forms":[F("properties","n.","财产；属性(复数)")]}},
  {"word":"tradition","phonetic":"trəˈdɪʃən","pos":"n.","def":"传统，惯例","cefr":"B1","freq_rank":68,
   "sentence_en":"It is a family tradition to eat together.","sentence_zh":"一起吃饭是家庭传统。",
   "aids":{"morphemes":[M("tra","prefix","越过，传"),M("dit","root","给"),M("ion","suffix","名词后缀")],
     "derivation":"tra(传)+dit(给) → 一代代传交下去的 → 传统",
     "family":FAM("dit/dat","给",[W("edit","编辑"),W("add","增加"),W("betray","背叛")]),
     "mnemonic":"dit=给(拉丁 dare);跨(tra-)代交给下一辈的东西,就是 tradition 传统;形容词 traditional。",
     "forms":[F("traditional","adj.","传统的")]}},
  {"word":"conversation","phonetic":"ˌkɒnvəˈseɪʃən","pos":"n.","def":"交谈，对话","cefr":"A2","freq_rank":55,
   "sentence_en":"We had a long conversation about life.","sentence_zh":"我们就人生长谈了一番。",
   "aids":{"morphemes":[M("con","prefix","一起，相互"),M("vers","root","转，来回"),M("ation","suffix","名词后缀")],
     "derivation":"con(相互)+vers(转) → 话头在双方之间来回转 → 交谈",
     "family":FAM("vers/vert","转",[W("reverse","颠倒"),W("convert","转变"),W("version","版本"),W("universe","宇宙")]),
     "mnemonic":"vers=转(想 reverse);话题在你我之间(con-)来回转,就是 conversation 交谈。",
     "forms":[F("conversational","adj.","口语的")]}},
  {"word":"version","phonetic":"ˈvɜːʃən","pos":"n.","def":"版本；说法","cefr":"B1","freq_rank":48,
   "sentence_en":"This is the latest version of the app.","sentence_zh":"这是这款应用的最新版本。",
   "aids":{"morphemes":[M("vers","root","转，改"),M("ion","suffix","名词后缀")],
     "derivation":"vers(转、改)+ion → 转换、改写出的一种形态 → 版本、说法",
     "family":FAM("vers/vert","转",[W("convert","转变"),W("reverse","颠倒"),W("diverse","多样的")]),
     "mnemonic":"vers=转/改;同一事物改换出的一种形态,就是 version 版本;各人说法各'转'一版=说法。",
     "forms":[F("versions","n.","版本(复数)")]}},
  {"word":"relation","phonetic":"rɪˈleɪʃən","pos":"n.","def":"关系，联系；亲属","cefr":"B1","freq_rank":46,
   "sentence_en":"The two countries have good relations.","sentence_zh":"两国关系良好。",
   "aids":{"morphemes":[M("re","prefix","相互"),M("lat","root","带"),M("ion","suffix","名词后缀")],
     "derivation":"re(相互)+lat(带) → 相互牵连 → 关系",
     "family":FAM("lat","带、拿",[W("relate","使有联系"),W("translate","翻译"),W("relative","相对的；亲属")]),
     "mnemonic":"lat=带;两者相互(re-)牵带在一起,就是 relation 关系;relative 亲属/相对的。",
     "forms":[F("relations","n.","关系(复数)"),F("relationship","n.","关系")]}},
  {"word":"release","phonetic":"rɪˈliːs","pos":"v./n.","def":"释放；发布，发行","cefr":"B1","freq_rank":47,
   "sentence_en":"The band released a new album.","sentence_zh":"乐队发行了新专辑。",
   "aids":{"morphemes":[M("re","prefix","去除，反"),M("lease","root","松，放(lax)")],
     "derivation":"re(去除)+lease(松) → 松开、放开 → 释放、发布",
     "family":FAM("lax/lease","松",[W("relax","放松"),W("lease","租约(放开使用权)")]),
     "mnemonic":"lease≈松(lax,想 relax 放松);把束缚松开放走=release 释放;把作品'放'出去=发行。",
     "forms":[F("released","v.","过去式/过去分词")]}},
  {"word":"account","phonetic":"əˈkaʊnt","pos":"n./v.","def":"账户；描述，解释；(数量)占","cefr":"B1","freq_rank":39,
   "sentence_en":"She gave a detailed account of the event.","sentence_zh":"她详细描述了这件事。",
   "aids":{"morphemes":[M("ac","prefix","朝向(ad 变体)"),M("count","root","计算")],
     "derivation":"ac(朝向)+count(算) → 把数目/事情算清说明 → 账目、描述",
     "family":FAM("count/put","计算",[W("count","数"),W("discount","折扣"),W("compute","计算")]),
     "mnemonic":"count=算;把钱算清的记录=账户;把事'算'明白讲出来=描述;account for=解释/占比。",
     "forms":[F("accounts","n.","账户(复数)"),F("accountant","n.","会计")]}},
  {"word":"responsibility","phonetic":"rɪˌspɒnsəˈbɪlɪti","pos":"n.","def":"责任，职责","cefr":"B1","freq_rank":37,
   "sentence_en":"It is your responsibility to lock the door.","sentence_zh":"锁门是你的责任。",
   "aids":{"morphemes":[M("re","prefix","回"),M("spons","root","承诺，回答"),M("ibility","suffix","名词后缀")],
     "derivation":"re(回)+spons(答) → 需要对之作出回应/交代的 → 责任",
     "family":FAM("spons/spond","承诺、回答",[W("respond","回应"),W("response","回应"),W("responsible","负责的")]),
     "mnemonic":"spons=回答(想 respond);出了事要你回应、交代得起的,就是 responsibility 责任。",
     "forms":[F("responsible","adj.","负责的")]}},
  {"word":"majority","phonetic":"məˈdʒɒrɪti","pos":"n.","def":"多数，大半","cefr":"B1","freq_rank":41,
   "sentence_en":"The majority of students passed.","sentence_zh":"大多数学生都通过了。",
   "aids":{"morphemes":[M("major","root","较大的"),M("ity","suffix","名词后缀")],
     "derivation":"major(较大的)+ity → 较大的那部分 → 多数",
     "family":FAM("maj/magn","大",[W("major","主要的"),W("magnify","放大"),W("maximum","最大值")]),
     "mnemonic":"major=较大;占较大的那一部分,就是 majority 多数;反义 minority 少数。",
     "forms":[F("majorities","n.","多数(复数)")]}},
  {"word":"option","phonetic":"ˈɒpʃən","pos":"n.","def":"选择，选项","cefr":"A2","freq_rank":44,
   "sentence_en":"You have two options.","sentence_zh":"你有两个选择。",
   "aids":{"morphemes":[M("opt","root","选择"),M("ion","suffix","名词后缀")],
     "derivation":"opt(选择)+ion → 可选的一项 → 选择、选项",
     "family":FAM("opt","选择",[W("opt","选择"),W("adopt","采纳"),W("optional","可选的")]),
     "mnemonic":"opt=选(想 opt for 选择);摆出来供你挑的一项,就是 option 选项;optional 可选的。",
     "forms":[F("optional","adj.","可选的"),F("options","n.","选项(复数)")]}},
  {"word":"participant","phonetic":"pɑːˈtɪsɪpənt","pos":"n.","def":"参加者，参与者","cefr":"B2","freq_rank":45,
   "sentence_en":"All participants received a certificate.","sentence_zh":"所有参与者都获得了证书。",
   "aids":{"morphemes":[M("part","root","部分"),M("i","connector","连接"),M("cip","root","拿(cap)"),M("ant","suffix","…的人")],
     "derivation":"part(部分)+cip(拿) → 拿到一份、参与其中的人 → 参与者",
     "family":FAM("part","部分",[W("participate","参加"),W("particle","粒子"),W("partial","部分的")]),
     "mnemonic":"part(部分)+cip(拿)——在活动里'拿一份'参与进来的人,就是 participant;动词 participate。",
     "forms":[F("participate","v.","参加"),F("participation","n.","参与")]}},
  {"word":"argument","phonetic":"ˈɑːɡjumənt","pos":"n.","def":"论点，论据；争论","cefr":"B1","freq_rank":58,
   "sentence_en":"He put forward a strong argument.","sentence_zh":"他提出了有力的论据。",
   "aids":{"morphemes":[M("argu","root","论证，使清楚"),M("ment","suffix","名词后缀")],
     "derivation":"argu(论证)+ment → 论证的内容 → 论点;各执论点 → 争论",
     "family":FAM("argu","论证",[W("argue","争论"),W("arguable","有争议的")]),
     "mnemonic":"argu=论证(想 argue);摆出来支撑观点的理由=argument 论据;各摆各的=争论。",
     "forms":[F("argue","v.","争论"),F("arguments","n.","论点(复数)")]}},
  {"word":"feature","phonetic":"ˈfiːtʃə","pos":"n./v.","def":"特征，特色；由…主演","cefr":"B1","freq_rank":59,
   "sentence_en":"The phone has many new features.","sentence_zh":"这款手机有许多新功能特性。",
   "aids":{"morphemes":[M("feat","root","做，形态(fact)"),M("ure","suffix","名词后缀")],
     "derivation":"feat(做、形态)+ure → 做成的样貌特点 → 特征、特色",
     "family":FAM("fact/feat","做、造",[W("fact","事实"),W("factor","因素"),W("manufacture","制造")]),
     "mnemonic":"feat=做/形态(fact 家族);构成事物面貌的突出点,就是 feature 特征、特色;电影'由…主演'也是 feature。",
     "forms":[F("features","n.","特征(复数)"),F("featured","adj.","特约的")]}},
  {"word":"crisis","phonetic":"ˈkraɪsɪs","pos":"n.","def":"危机，紧要关头","cefr":"B2","freq_rank":61,
   "sentence_en":"The country is facing an economic crisis.","sentence_zh":"这个国家正面临经济危机。",
   "aids":{"morphemes":[M("cris","root","判断，决断"),M("is","suffix","名词后缀")],
     "derivation":"cris(决断)→ 到了必须决断成败的关口 → 危机",
     "family":FAM("cris/crit","判断、决断",[W("critical","危急的"),W("criticize","批评"),W("criterion","标准")]),
     "mnemonic":"cris=决断(和 critical 一家);形势到了要一锤定成败的紧要关头,就是 crisis 危机;复数 crises。",
     "forms":[F("critical","adj.","危急的")]}},
  {"word":"variety","phonetic":"vəˈraɪəti","pos":"n.","def":"多样性；种类","cefr":"B1","freq_rank":56,
   "sentence_en":"The shop offers a variety of goods.","sentence_zh":"这家店提供各种各样的商品。",
   "aids":{"morphemes":[M("vari","root","变化"),M("ety","suffix","名词后缀")],
     "derivation":"vari(变化)+ety → 多变多样 → 多样性、种类",
     "family":FAM("vari","变化",[W("various","各种的"),W("vary","变化"),W("variable","可变的")]),
     "mnemonic":"vari=变;花样多、种类杂,就是 variety;a variety of=各种各样的。",
     "forms":[F("various","adj.","各种的"),F("varieties","n.","种类(复数)")]}},
  {"word":"insurance","phonetic":"ɪnˈʃʊərəns","pos":"n.","def":"保险","cefr":"B1","freq_rank":60,
   "sentence_en":"Do you have health insurance?","sentence_zh":"你有医疗保险吗？",
   "aids":{"morphemes":[M("in","prefix","使"),M("sur","root","确保，安全(secur)"),M("ance","suffix","名词后缀")],
     "derivation":"in(使)+sure(确保) → 花钱使自己有保障 → 保险",
     "family":FAM("sur/secur","确保、安全",[W("sure","确定的"),W("ensure","确保"),W("assure","使确信"),W("secure","安全的")]),
     "mnemonic":"sur=确保(想 sure/ensure);花钱买个'确保无忧',就是 insurance 保险;动词 insure。",
     "forms":[F("insure","v.","给…保险"),F("insurer","n.","保险公司")]}},
  # 高频动词/名词(常见)
  {"word":"charge","phonetic":"tʃɑːdʒ","pos":"n./v.","def":"收费；指控；充电；主管","cefr":"B1","freq_rank":9,
   "sentence_en":"How much do you charge for delivery?","sentence_zh":"你们送货收多少钱？",
   "aids":{"morphemes":[M("charg","root","装载(car 车)"),M("e","suffix","结尾")],
     "derivation":"与 car(车)同源'装载';把责任/费用/电'装'上去 → 负责、收费、充电、指控",
     "family":FAM("car/charg","车、装载",[W("cargo","货物"),W("carry","携带")]),
     "mnemonic":"charge≈往车上'装载';装钱=收费;装罪名=指控;装电=充电;in charge=负责(担子装身上)。",
     "forms":[F("charges","n.","费用；指控(复数)"),F("charged","v.","过去式/过去分词")]}},
  {"word":"mention","phonetic":"ˈmenʃən","pos":"v./n.","def":"提到","cefr":"A2","freq_rank":19,
   "sentence_en":"She didn't mention the price.","sentence_zh":"她没有提到价格。",
   "aids":{"morphemes":[M("ment","root","心，提"),M("ion","suffix","名词后缀")],
     "derivation":"ment(心、提)+ion → 把想到的提一句 → 提到","family":FAM("ment","心、想",[W("mental","精神的"),W("comment","评论")]),
     "mnemonic":"ment=提及;顺口把想到的提一句,就是 mention。","forms":[F("mentioned","v.","过去式/过去分词")]}},
  {"word":"range","phonetic":"reɪndʒ","pos":"n./v.","def":"范围，幅度；(数值)分布于","cefr":"B1","freq_rank":20,
   "sentence_en":"Prices range from $10 to $50.","sentence_zh":"价格从10到50美元不等。",
   "aids":{"morphemes":[M("rang","root","排，行(rank)"),M("e","suffix","结尾")],
     "derivation":"rang(排成一行)→ 从头排到尾的一段 → 范围、幅度",
     "family":FAM("rang/rank","排、行",[W("rank","等级；排列"),W("arrange","安排")]),
     "mnemonic":"rang=排成一行(想 rank 排名);从最低到最高排开的一整条,就是 range 范围;range from A to B=从A到B不等。",
     "forms":[F("ranges","n.","范围(复数)"),F("ranging","v.","分布(现在分词)")]}},
  {"word":"detail","phonetic":"ˈdiːteɪl","pos":"n./v.","def":"细节，详情；详述","cefr":"A2","freq_rank":25,
   "sentence_en":"Tell me the details of the plan.","sentence_zh":"把计划的细节告诉我。",
   "aids":{"morphemes":[M("de","prefix","加强"),M("tail","root","切(tal)")],
     "derivation":"de+tail(切) → 切成一小块一小块的 → 细节",
     "family":FAM("tail","切",[W("tailor","裁缝(切布)"),W("retail","零售(切开卖)")]),
     "mnemonic":"tail=切(想 tailor 裁缝切布、retail 零售拆开卖);把整体切碎成一小点一小点,就是 detail 细节。",
     "forms":[F("detailed","adj.","详细的"),F("details","n.","细节(复数)")]}},
  {"word":"address","phonetic":"əˈdres","pos":"n./v.","def":"地址；演讲；处理，解决","cefr":"B1","freq_rank":29,
   "sentence_en":"We must address this problem now.","sentence_zh":"我们必须现在解决这个问题。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("dress","root","弄直，指引(direct)")],
     "derivation":"ad(朝向)+dress(指引) → 把话/精力对准某处 → 演讲、处理;信件对准的去处 → 地址",
     "family":FAM("rect/dress","直、引导",[W("direct","直接的"),W("dress","整理，穿衣")]),
     "mnemonic":"dress≈direct 对准;把讲话对准听众=演讲;把精力对准难题=处理、解决;把信对准去处=地址。",
     "forms":[F("addressed","v.","过去式/过去分词")]}},
  {"word":"debate","phonetic":"dɪˈbeɪt","pos":"n./v.","def":"辩论，争论","cefr":"B1","freq_rank":40,
   "sentence_en":"The topic caused a heated debate.","sentence_zh":"这个话题引发了激烈辩论。",
   "aids":{"morphemes":[M("de","prefix","彻底"),M("bat","root","打，击(bat)"),M("e","suffix","结尾")],
     "derivation":"de(彻底)+bat(打) → 用言辞彻底交锋 → 辩论",
     "family":FAM("bat","打、击",[W("battle","战斗"),W("combat","搏斗"),W("beat","打")]),
     "mnemonic":"bat=打(想 battle);双方用言辞彻底(de-)对打,就是 debate 辩论。",
     "forms":[F("debates","n.","辩论(复数)"),F("debated","v.","过去式/过去分词")]}},
  {"word":"target","phonetic":"ˈtɑːɡɪt","pos":"n./v.","def":"目标，靶子；以…为目标","cefr":"B1","freq_rank":76,
   "sentence_en":"We reached our sales target.","sentence_zh":"我们达到了销售目标。",
   "aids":{"morphemes":[M("targ","root","盾，靶(古法语 targe)"),M("et","suffix","小")],
     "derivation":"targe(小盾)→ 练箭时当靶用的小盾 → 靶子、目标",
     "family":FAM("","相关词",[W("targeted","有针对性的")]),
     "mnemonic":"target 原指练箭的'小盾靶';你瞄准要打中的那个点,就是 target 目标、靶子。",
     "forms":[F("targets","n.","目标(复数)"),F("targeted","adj.","有针对性的")]}},
  {"word":"demand","phonetic":"dɪˈmɑːnd","pos":"n./v.","def":"要求；需求","cefr":"B1","freq_rank":123,
   "sentence_en":"There is high demand for the product.","sentence_zh":"这种产品需求很大。",
   "aids":{"morphemes":[M("de","prefix","加强"),M("mand","root","命令")],
     "derivation":"de+mand(命令) → 强硬要求 → 要求、需求","family":FAM("mand","命令",[W("command","命令"),W("recommend","推荐")]),
     "mnemonic":"mand=命令;强势索要,就是 demand;经济学'需求'也是 demand。","forms":[F("demanding","adj.","要求高的")]}},
  {"word":"average","phonetic":"ˈævərɪdʒ","pos":"n./adj./v.","def":"平均(数)；普通的","cefr":"A2","freq_rank":80,
   "sentence_en":"The average temperature is 20 degrees.","sentence_zh":"平均气温是20度。",
   "aids":{"morphemes":[M("average","root","海损分摊(avarie)")],
     "derivation":"源自航海'海损分摊'——损失由各方平摊 → 平均;引申'中等、普通'",
     "family":FAM("","相关词",[W("averaged","平均(过去式)")]),
     "mnemonic":"词源是海运损失'大家平摊';摊匀后的中间值=average 平均;处于中间不突出=普通的。",
     "forms":[F("averages","n.","平均数(复数)")]}},
  {"word":"understanding","phonetic":"ˌʌndəˈstændɪŋ","pos":"n.","def":"理解；谅解；默契","cefr":"B1","freq_rank":79,
   "sentence_en":"They reached an understanding.","sentence_zh":"他们达成了谅解。",
   "aids":{"morphemes":[M("under","prefix","在下，彻底"),M("stand","root","站，明白"),M("ing","suffix","名词后缀")],
     "derivation":"under(彻底)+stand(站住、把握) → 站到事物根底把握住 → 理解",
     "family":FAM("st/stand","站、立",[W("understand","理解"),W("stand","站立"),W("standard","标准")]),
     "mnemonic":"understand=站(stand)到底下(under)把根底看透→理解;双方都理解到位=谅解、默契。",
     "forms":[F("understand","v.","理解")]}},
  {"word":"handle","phonetic":"ˈhændl","pos":"v./n.","def":"处理，应对；把手","cefr":"A2","freq_rank":67,
   "sentence_en":"Can you handle this situation?","sentence_zh":"你能应付这个局面吗？",
   "aids":{"morphemes":[M("hand","root","手"),M("le","suffix","小/反复")],
     "derivation":"hand(手)+le → 用手拿捏、操持 → 处理;供手握的部件 → 把手",
     "family":FAM("hand","手",[W("hand","手"),W("handful","一把"),W("handy","便利的")]),
     "mnemonic":"hand=手;用手把事拿捏妥当=handle 处理;供手握的那截=把手。",
     "forms":[F("handled","v.","过去式/过去分词"),F("handling","n.","处理")]}},
  {"word":"track","phonetic":"træk","pos":"n./v.","def":"轨道，足迹；追踪","cefr":"B1","freq_rank":51,
   "sentence_en":"The police tracked the suspect.","sentence_zh":"警方追踪了嫌疑人。",
   "aids":{"morphemes":[M("track","root","踩出的痕(trek)")],
     "derivation":"踩踏留下的痕迹 → 足迹、轨道;沿痕迹跟 → 追踪",
     "family":FAM("","相关词",[W("tracking","追踪"),W("racetrack","赛道")]),
     "mnemonic":"track=踩出的痕;留下的脚印/铺好的轨=足迹、轨道;顺着痕迹跟下去=track 追踪;on track 步入正轨。",
     "forms":[F("tracks","n.","轨道(复数)"),F("tracked","v.","过去式/过去分词")]}},
  {"word":"strike","phonetic":"straɪk","pos":"v./n.","def":"打击，撞击；罢工；(想法)突然出现","cefr":"B2","freq_rank":52,
   "sentence_en":"An idea struck me.","sentence_zh":"我突然想到一个主意。",
   "aids":{"morphemes":[M("strike","root","打，划(古英语 strican)")],
     "derivation":"本义'打、划过';猛打→打击;停工'打'掉生产→罢工;念头猛地'打'中你→突然想到",
     "family":FAM("","相关词",[W("striking","显著的"),W("stroke","一击；中风")]),
     "mnemonic":"strike=打(过去式不规则 struck);重击=打击;工人集体'罢'手=罢工;灵感猛地击中=strike 突然想到。",
     "forms":[F("struck","v.","过去式/过去分词"),F("striking","adj.","显著的")]}},
  {"word":"lack","phonetic":"læk","pos":"n./v.","def":"缺乏，不足","cefr":"A2","freq_rank":66,
   "sentence_en":"The plan failed due to a lack of money.","sentence_zh":"计划因缺钱而失败。",
   "aids":{"morphemes":[M("lack","root","缺少")],
     "derivation":"中古英语 lac'缺少'。→ 缺乏、不足。",
     "family":FAM("","相关词",[W("lacking","缺乏的"),W("lackluster","无光泽的")]),
     "mnemonic":"lack 本身=缺;需要却没有,就是 lack 缺乏;a lack of=缺少;lack in=在…方面欠缺。",
     "forms":[F("lacking","adj.","缺乏的"),F("lacked","v.","过去式/过去分词")]}},
  {"word":"screen","phonetic":"skriːn","pos":"n./v.","def":"屏幕；筛查；遮蔽","cefr":"B1","freq_rank":69,
   "sentence_en":"Look at the screen, please.","sentence_zh":"请看屏幕。",
   "aids":{"morphemes":[M("screen","root","遮挡物(古法语 escren)")],
     "derivation":"本义'遮挡的屏';引申显示画面的屏幕;像筛子那样挡掉一部分 → 筛查",
     "family":FAM("","相关词",[W("screening","筛查；放映"),W("sunscreen","防晒霜")]),
     "mnemonic":"screen=遮屏;挡光/显示的板=屏幕;像筛网滤掉不合格的=筛查;挡起来=遮蔽。",
     "forms":[F("screening","n.","筛查；放映"),F("screened","v.","过去式/过去分词")]}},
  {"word":"scale","phonetic":"skeɪl","pos":"n./v.","def":"规模；刻度，等级；秤；攀登","cefr":"B1","freq_rank":64,
   "sentence_en":"The project was done on a large scale.","sentence_zh":"这个项目是大规模进行的。",
   "aids":{"morphemes":[M("scal","root","梯子，攀(scala)"),M("e","suffix","结尾")],
     "derivation":"拉丁 scala'梯子';一级级的梯 → 刻度、等级、规模;沿梯上 → 攀登",
     "family":FAM("scal","梯、攀",[W("escalate","逐步升级"),W("escalator","自动扶梯")]),
     "mnemonic":"scala=梯子(想 escalator 扶梯);一格格的梯=刻度/等级;铺开的大'梯度'=规模;顺梯爬=攀登。",
     "forms":[F("scales","n.","刻度；秤(复数)"),F("scaled","v.","攀登(过去式)")]}},
  {"word":"willing","phonetic":"ˈwɪlɪŋ","pos":"adj.","def":"愿意的，乐意的","cefr":"A2","freq_rank":74,
   "sentence_en":"She is willing to help.","sentence_zh":"她愿意帮忙。",
   "aids":{"morphemes":[M("will","root","意愿"),M("ing","suffix","…的")],
     "derivation":"will(意愿)+ing → 心里有此意愿的 → 愿意的",
     "family":FAM("will","意愿",[W("will","意志；将要"),W("willingness","乐意"),W("goodwill","善意")]),
     "mnemonic":"will=意愿;心甘情愿有这份意愿,就是 willing;be willing to do=乐意做;反义 unwilling。",
     "forms":[F("willingness","n.","乐意"),F("unwilling","adj.","不愿意的")]}},
  {"word":"tough","phonetic":"tʌf","pos":"adj.","def":"艰难的；坚韧的；强硬的","cefr":"B1","freq_rank":26,
   "sentence_en":"It was a tough decision.","sentence_zh":"这是个艰难的决定。",
   "aids":{"morphemes":[M("tough","root","坚韧")],
     "derivation":"古英语 tōh'坚韧'。→ 咬不动的、坚韧的、艰难的、强硬的。",
     "family":FAM("","相关词",[W("toughen","使坚韧"),W("toughness","韧性")]),
     "mnemonic":"tough=韧;肉咬不动=tough;人扛得住=坚韧;事难啃=艰难;态度不让步=强硬。",
     "forms":[F("tougher","adj.","更难的(比较级)"),F("toughness","n.","韧性")]}},
  {"word":"item","phonetic":"ˈaɪtəm","pos":"n.","def":"项目，条款；一件物品","cefr":"A2","freq_rank":30,
   "sentence_en":"The first item on the list is milk.","sentence_zh":"清单上第一项是牛奶。",
   "aids":{"morphemes":[M("item","root","同样地，又(拉丁)")],
     "derivation":"拉丁 item'同样地、又';旧时清单每行以 item 起头列出 → 一项、一件",
     "family":FAM("","相关词",[W("itemize","逐项列出")]),
     "mnemonic":"旧账单每条都用 item(又一项)开头;由此 item=清单上的一项、一件物品。",
     "forms":[F("items","n.","项目(复数)")]}},
  {"word":"spot","phonetic":"spɒt","pos":"n./v.","def":"地点；斑点；发现，认出","cefr":"B1","freq_rank":65,
   "sentence_en":"I spotted him in the crowd.","sentence_zh":"我在人群中认出了他。",
   "aids":{"morphemes":[M("spot","root","点，污渍")],
     "derivation":"本义'小点、污渍';具体的一个'点'→地点;眼睛锁定那个点 → 发现、认出",
     "family":FAM("","相关词",[W("spotless","一尘不染的"),W("spotlight","聚光灯")]),
     "mnemonic":"spot=点;衣服上的点=斑点;某个具体'点'=地点;一眼锁定那点=spot 认出;on the spot 当场。",
     "forms":[F("spots","n.","地点(复数)"),F("spotted","v.","过去式/过去分词")]}},
  {"word":"score","phonetic":"skɔː","pos":"n./v.","def":"得分，分数；乐谱","cefr":"A2","freq_rank":38,
   "sentence_en":"She scored the highest in the exam.","sentence_zh":"她考试得分最高。",
   "aids":{"morphemes":[M("score","root","刻痕(古诺斯语 skor)")],
     "derivation":"本义'刻痕'——旧时用刻痕计数、记账 → 得分、分数",
     "family":FAM("","相关词",[W("scoreboard","记分牌"),W("underscore","强调；下划线")]),
     "mnemonic":"score=刻痕(旧时刻道计数);刻一道记一分,就是 score 得分、分数;乐谱各声部记在一处也叫 score。",
     "forms":[F("scores","n.","分数(复数)"),F("scored","v.","过去式/过去分词")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 5
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
