#!/usr/bin/env python
# 第十一批词(冲500最后一程,约82词):逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -spect 看
  {"word":"suspect","phonetic":"səˈspekt","pos":"v./n.","def":"怀疑；嫌疑犯","cefr":"B2","freq_rank":74,
   "sentence_en":"Police suspect he is lying.","sentence_zh":"警方怀疑他在撒谎。",
   "aids":{"morphemes":[M("su","prefix","在下(sub)"),M("spect","root","看")],
     "derivation":"su(在下)+spect(看) → 从下面偷偷打量 → 怀疑",
     "family":FAM("spect","看",[W("inspect","检查"),W("respect","尊重"),W("prospect","前景"),W("aspect","方面")]),
     "mnemonic":"spect=看;暗地里(sub-)上下打量、觉得不对劲,就是 suspect 怀疑;被这样打量的人=嫌疑犯。",
     "forms":[F("suspicion","n.","怀疑"),F("suspicious","adj.","可疑的")]}},
  {"word":"visual","phonetic":"ˈvɪʒuəl","pos":"adj.","def":"视觉的，视力的","cefr":"B1","freq_rank":97,
   "sentence_en":"The film has stunning visual effects.","sentence_zh":"这部电影视觉效果惊人。",
   "aids":{"morphemes":[M("vis","root","看"),M("ual","suffix","…的")],
     "derivation":"vis(看)+ual → 与看有关的 → 视觉的",
     "family":FAM("vis/vid","看",[W("vision","视力"),W("visible","可见的"),W("visit","拜访"),W("supervise","监督")]),
     "mnemonic":"vis=看(和 vision 一家);关乎眼睛看的,就是 visual 视觉的;visualize 使形象化。",
     "forms":[F("visualize","v.","使形象化"),F("visually","adv.","视觉上")]}},
  {"word":"observation","phonetic":"ˌɒbzəˈveɪʃən","pos":"n.","def":"观察；观测；评论","cefr":"B2","freq_rank":77,
   "sentence_en":"He made an interesting observation.","sentence_zh":"他做了一个有趣的评论。",
   "aids":{"morphemes":[M("ob","prefix","对着"),M("serv","root","看守"),M("ation","suffix","名词后缀")],
     "derivation":"observe(观察)+ation → 观察的动作/所得 → 观察、评论",
     "family":FAM("serv","看守、保持",[W("observe","观察"),W("preserve","保存"),W("reserve","保留")]),
     "mnemonic":"observe(对着仔细看)的名词;仔细看的过程,或看后说出的看法,就是 observation 观察、评论。",
     "forms":[F("observe","v.","观察")]}},
  # -quest/-quire 寻
  {"word":"request","phonetic":"rɪˈkwest","pos":"n./v.","def":"请求，要求","cefr":"B1","freq_rank":83,
   "sentence_en":"They made a request for help.","sentence_zh":"他们请求帮助。",
   "aids":{"morphemes":[M("re","prefix","再，反复"),M("quest","root","寻求")],
     "derivation":"re(反复)+quest(寻求) → 反复去求 → 请求",
     "family":FAM("quest/quire","寻求",[W("require","要求"),W("question","问题"),W("inquire","询问"),W("conquest","征服")]),
     "mnemonic":"quest=寻求(想 quest 探索);开口去求取,就是 request 请求;比 demand 客气。",
     "forms":[F("requested","v.","过去式/过去分词")]}},
  # -fin 界限/结束
  {"word":"definition","phonetic":"ˌdefɪˈnɪʃən","pos":"n.","def":"定义；清晰度","cefr":"B1","freq_rank":79,
   "sentence_en":"Look up the definition of the word.","sentence_zh":"查一下这个词的定义。",
   "aids":{"morphemes":[M("de","prefix","彻底"),M("fin","root","界限"),M("ition","suffix","名词后缀")],
     "derivation":"define(划定界限)+ition → 划清界限的说明 → 定义",
     "family":FAM("fin","界限、结束",[W("define","定义"),W("finish","完成"),W("final","最终的"),W("finite","有限的")]),
     "mnemonic":"fin=界限(和 define 一家);给词划清边界的说明,就是 definition 定义;图像'边界分明度'=清晰度。",
     "forms":[F("define","v.","定义")]}},
  # -prior 在前
  {"word":"priority","phonetic":"praɪˈɒrɪti","pos":"n.","def":"优先，优先事项","cefr":"B2","freq_rank":80,
   "sentence_en":"Safety is our top priority.","sentence_zh":"安全是我们的首要任务。",
   "aids":{"morphemes":[M("prior","root","在前的"),M("ity","suffix","名词后缀")],
     "derivation":"prior(在前的)+ity → 排在前面的资格 → 优先",
     "family":FAM("prior/prim","在前、第一",[W("prior","在前的"),W("primary","首要的"),W("prime","首要的")]),
     "mnemonic":"prior=在前(想 prior to 在…之前);排在最前、最该先办的事,就是 priority 优先事项。",
     "forms":[F("prioritize","v.","优先处理"),F("priorities","n.","优先事项(复数)")]}},
  # -cre 生
  {"word":"creation","phonetic":"kriˈeɪʃən","pos":"n.","def":"创造，创作(物)","cefr":"B1","freq_rank":81,
   "sentence_en":"The painting is his greatest creation.","sentence_zh":"这幅画是他最伟大的创作。",
   "aids":{"morphemes":[M("creat","root","创造"),M("ion","suffix","名词后缀")],
     "derivation":"create(创造)+ion → 创造的行为/成果 → 创造、创作物",
     "family":FAM("cre","生长、产生",[W("create","创造"),W("creative","有创造力的"),W("creature","生物")]),
     "mnemonic":"create(创造)的名词;从无到有造出的行为或作品,就是 creation。",
     "forms":[F("create","v.","创造")]}},
  # -grad 走/级
  {"word":"graduate","phonetic":"ˈɡrædʒueɪt","pos":"v./n.","def":"毕业；毕业生","cefr":"B1","freq_rank":82,
   "sentence_en":"She graduated from Oxford.","sentence_zh":"她从牛津毕业。",
   "aids":{"morphemes":[M("grad","root","步，级"),M("uate","suffix","动词后缀")],
     "derivation":"grad(级)+uate → 走完一级级学业、升级 → 毕业",
     "family":FAM("grad/gress","步、级",[W("grade","年级"),W("gradual","逐渐的"),W("progress","进步"),W("upgrade","升级")]),
     "mnemonic":"grad=级/步(想 grade 年级);一级级学业走到头、升上去,就是 graduate 毕业;毕业的人=毕业生。",
     "forms":[F("graduation","n.","毕业"),F("graduates","n.","毕业生(复数)")]}},
  # -cover 盖
  {"word":"recover","phonetic":"rɪˈkʌvə","pos":"v.","def":"恢复，康复；重新获得","cefr":"B1","freq_rank":89,
   "sentence_en":"It took weeks to recover from the illness.","sentence_zh":"病后康复花了几周时间。",
   "aids":{"morphemes":[M("re","prefix","再，回"),M("cover","root","盖，取得")],
     "derivation":"re(再)+cover(取得) → 重新取回(健康/失物) → 恢复",
     "family":FAM("cover","盖、取得",[W("cover","覆盖"),W("discover","发现"),W("coverage","覆盖范围")]),
     "mnemonic":"re-(再)+cover——把失去的健康/东西重新'盖'回、取回,就是 recover 恢复;recovery 康复。",
     "forms":[F("recovery","n.","恢复，康复")]}},
  # -pens 花费/挂
  {"word":"expense","phonetic":"ɪkˈspens","pos":"n.","def":"费用，花费；代价","cefr":"B1","freq_rank":90,
   "sentence_en":"Travel expenses will be paid.","sentence_zh":"差旅费用将予报销。",
   "aids":{"morphemes":[M("ex","prefix","出"),M("pens","root","称量，花(pend)")],
     "derivation":"ex(出)+pens(花) → 称量着往外掏钱 → 费用",
     "family":FAM("pens/pend","花费、悬挂",[W("expensive","昂贵的"),W("spend","花费"),W("pension","养老金")]),
     "mnemonic":"pens=花/称(想 spend);往外(ex-)掏出去的钱,就是 expense 费用;at the expense of 以…为代价。",
     "forms":[F("expensive","adj.","昂贵的"),F("expenses","n.","开支(复数)")]}},
  # -init 进入
  {"word":"initiative","phonetic":"ɪˈnɪʃətɪv","pos":"n.","def":"主动性；倡议，新方案","cefr":"C1","freq_rank":91,
   "sentence_en":"She showed great initiative.","sentence_zh":"她表现出很强的主动性。",
   "aids":{"morphemes":[M("in","prefix","进入"),M("it","root","走"),M("iative","suffix","名词后缀")],
     "derivation":"in(进入)+it(走) → 率先迈步开始 → 主动性、倡议",
     "family":FAM("it","走、行",[W("initial","最初的"),W("initiate","发起"),W("exit","出口")]),
     "mnemonic":"it=走(想 initial 最初的);率先迈第一步的劲头,就是 initiative 主动性;新发起的方案=倡议;take the initiative 采取主动。",
     "forms":[F("initiatives","n.","倡议(复数)")]}},
  # 高频动词(词根清晰)
  {"word":"emphasize","phonetic":"ˈemfəsaɪz","pos":"v.","def":"强调，着重","cefr":"B2","freq_rank":47,
   "sentence_en":"He emphasized the importance of rest.","sentence_zh":"他强调了休息的重要性。",
   "aids":{"morphemes":[M("em","prefix","使处于(en)"),M("phas","root","显示，说(phanein)"),M("ize","suffix","使…")],
     "derivation":"em(使)+phas(显示) → 使显出、凸显 → 强调",
     "family":FAM("phas/phan","显示",[W("emphasis","强调"),W("phase","阶段"),W("phenomenon","现象")]),
     "mnemonic":"phas=显示(想 phenomenon 现象=显现之物);把某点特别凸显出来,就是 emphasize 强调;名词 emphasis。",
     "forms":[F("emphasis","n.","强调，重点")]}},
  {"word":"celebrate","phonetic":"ˈselɪbreɪt","pos":"v.","def":"庆祝，庆贺","cefr":"A2","freq_rank":55,
   "sentence_en":"We celebrated her birthday.","sentence_zh":"我们庆祝了她的生日。",
   "aids":{"morphemes":[M("celebr","root","众多，著名(celeber)"),M("ate","suffix","动词后缀")],
     "derivation":"拉丁 celeber'人多、盛大';人群聚集隆重举行 → 庆祝",
     "family":FAM("celebr","众多、著名",[W("celebrity","名人"),W("celebration","庆祝")]),
     "mnemonic":"celebr=盛大热闹(想 celebrity 名人);众人聚起来热热闹闹地办,就是 celebrate 庆祝;celebration 庆典。",
     "forms":[F("celebration","n.","庆祝"),F("celebrity","n.","名人")]}},
  {"word":"assess","phonetic":"əˈses","pos":"v.","def":"评估，评定；估价","cefr":"B2","freq_rank":59,
   "sentence_en":"We need to assess the risk.","sentence_zh":"我们需要评估风险。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sess","root","坐")],
     "derivation":"as+sess(坐) → 像法官坐着估量定夺 → 评估",
     "family":FAM("sess/sid","坐",[W("assessment","评估"),W("session","会期"),W("possess","拥有")]),
     "mnemonic":"sess=坐(和 assessment 一家);沉下心'坐'着仔细估量,就是 assess 评估;名词 assessment。",
     "forms":[F("assessment","n.","评估")]}},
  {"word":"purchase","phonetic":"ˈpɜːtʃəs","pos":"v./n.","def":"购买；购买的东西","cefr":"B2","freq_rank":95,
   "sentence_en":"She purchased a new laptop.","sentence_zh":"她买了一台新笔记本电脑。",
   "aids":{"morphemes":[M("pur","prefix","向前(pro)"),M("chase","root","追，抓(cacchiare)")],
     "derivation":"pur(向前)+chase(追) → 追求到手、买下 → 购买",
     "family":FAM("chase/capt","追、抓",[W("chase","追赶"),W("capture","捕获")]),
     "mnemonic":"pur-(向前)+chase(追)——追着把它买到手,就是 purchase 购买(比 buy 正式)。",
     "forms":[F("purchased","v.","过去式/过去分词"),F("purchases","n.","购买(复数)")]}},
  {"word":"display","phonetic":"dɪˈspleɪ","pos":"v./n.","def":"展示，陈列；显示器","cefr":"B1","freq_rank":69,
   "sentence_en":"The shop displayed its new products.","sentence_zh":"商店陈列了新产品。",
   "aids":{"morphemes":[M("dis","prefix","分开，展开"),M("play","root","折叠(plic)")],
     "derivation":"dis(展开)+play(折叠) → 把折起来的摊开 → 展示",
     "family":FAM("play/plic","折叠",[W("apply","申请"),W("employ","雇用"),W("complex","复杂的")]),
     "mnemonic":"play=折叠(plic 家族,不是'玩');把卷折的东西摊(dis-)开亮出来,就是 display 展示;电子屏=显示器。",
     "forms":[F("displayed","v.","过去式/过去分词"),F("displays","n.","展示(复数)")]}},
  {"word":"schedule","phonetic":"ˈʃedjuːl","pos":"n./v.","def":"日程表，计划；安排","cefr":"B1","freq_rank":93,
   "sentence_en":"The meeting is scheduled for 3 p.m.","sentence_zh":"会议安排在下午三点。",
   "aids":{"morphemes":[M("sched","root","纸片，条(scheda)"),M("ule","suffix","小")],
     "derivation":"拉丁 scheda'纸条';写在纸条上的时间安排 → 日程表",
     "family":FAM("","相关词",[W("scheduled","预定的")]),
     "mnemonic":"schedule 原指'小纸条';纸上排好的时间计划,就是 schedule 日程;动词=安排;on schedule 按时。",
     "forms":[F("scheduled","adj.","预定的"),F("schedules","n.","日程(复数)")]}},
  # -uni 一
  {"word":"universe","phonetic":"ˈjuːnɪvɜːs","pos":"n.","def":"宇宙；领域","cefr":"B2","freq_rank":86,
   "sentence_en":"The universe is vast.","sentence_zh":"宇宙浩瀚无垠。",
   "aids":{"morphemes":[M("uni","root","一"),M("vers","root","转")],
     "derivation":"uni(一)+vers(转) → 万物合一同转的整体 → 宇宙",
     "family":FAM("vers/vert","转",[W("universal","普遍的"),W("version","版本"),W("reverse","颠倒")]),
     "mnemonic":"uni(一)+vers(转)——万物归'一'一同旋转的大整体,就是 universe 宇宙;universal 普遍的。",
     "forms":[F("universal","adj.","普遍的"),F("universes","n.","宇宙(复数)")]}},
  # 高频形容词/副词
  {"word":"excellent","phonetic":"ˈekslənt","pos":"adj.","def":"优秀的，杰出的","cefr":"A2","freq_rank":87,
   "sentence_en":"She did an excellent job.","sentence_zh":"她做得非常出色。",
   "aids":{"morphemes":[M("ex","prefix","出，超"),M("cel","root","高耸，突出"),M("lent","suffix","…的")],
     "derivation":"ex(超)+cel(高耸) → 高出众人 → 优秀的",
     "family":FAM("cel","高耸、突出",[W("excel","擅长，胜过"),W("excellence","卓越")]),
     "mnemonic":"cel=高耸(想 excel 出类拔萃);高高凸出、盖过旁人,就是 excellent 优秀的;动词 excel。",
     "forms":[F("excellence","n.","卓越"),F("excel","v.","擅长")]}},
  {"word":"dramatic","phonetic":"drəˈmætɪk","pos":"adj.","def":"戏剧性的；巨大的，惊人的","cefr":"B2","freq_rank":85,
   "sentence_en":"There was a dramatic change in the weather.","sentence_zh":"天气发生了剧烈变化。",
   "aids":{"morphemes":[M("drama","root","戏剧"),M("tic","suffix","…的")],
     "derivation":"drama(戏剧)+tic → 像戏剧一样的 → 戏剧性的、惊人的",
     "family":FAM("drama","戏剧",[W("drama","戏剧"),W("dramatize","改编成戏")]),
     "mnemonic":"drama=戏剧;像戏一样起伏强烈、出人意料的,就是 dramatic 戏剧性的、剧烈的;dramatically 显著地。",
     "forms":[F("dramatically","adv.","显著地")]}},
  {"word":"spiritual","phonetic":"ˈspɪrɪtʃuəl","pos":"adj.","def":"精神的，心灵的；宗教的","cefr":"B2","freq_rank":72,
   "sentence_en":"Meditation brings spiritual peace.","sentence_zh":"冥想带来心灵的宁静。",
   "aids":{"morphemes":[M("spirit","root","精神，气息"),M("ual","suffix","…的")],
     "derivation":"spirit(精神)+ual → 与精神心灵有关的 → 精神的",
     "family":FAM("spir","呼吸、精神",[W("spirit","精神"),W("inspire","激励"),W("respire","呼吸")]),
     "mnemonic":"spirit=精神/气息(想 inspire 吸气→激励);关乎内心、灵魂层面的,就是 spiritual 精神的。",
     "forms":[F("spiritually","adv.","精神上")]}},
  {"word":"limited","phonetic":"ˈlɪmɪtɪd","pos":"adj.","def":"有限的，受限的","cefr":"B1","freq_rank":49,
   "sentence_en":"We have limited time.","sentence_zh":"我们时间有限。",
   "aids":{"morphemes":[M("limit","root","界限"),M("ed","suffix","…的")],
     "derivation":"limit(界限)+ed → 被划了界的 → 有限的",
     "family":FAM("limit/limin","界限、门槛",[W("limit","限制"),W("eliminate","消除"),W("preliminary","预备的")]),
     "mnemonic":"limit=界限;被框在界限内、不多的,就是 limited 有限的;Ltd.=有限责任公司。",
     "forms":[F("limit","n.","限制"),F("limitation","n.","局限")]}},
  {"word":"violent","phonetic":"ˈvaɪələnt","pos":"adj.","def":"暴力的；猛烈的","cefr":"B1","freq_rank":99,
   "sentence_en":"There was a violent storm.","sentence_zh":"发生了一场猛烈的暴风雨。",
   "aids":{"morphemes":[M("viol","root","强力，侵犯"),M("ent","suffix","…的")],
     "derivation":"viol(强力)+ent → 使用强力的 → 暴力的、猛烈的",
     "family":FAM("viol","强力、侵犯",[W("violence","暴力"),W("violate","违反")]),
     "mnemonic":"viol=强力(和 violence 一家);诉诸武力的、来势凶猛的,就是 violent;violence 暴力(名词)。",
     "forms":[F("violence","n.","暴力"),F("violently","adv.","猛烈地")]}},
  {"word":"rural","phonetic":"ˈrʊərəl","pos":"adj.","def":"乡村的，农村的","cefr":"B1","freq_rank":53,
   "sentence_en":"They live in a rural area.","sentence_zh":"他们住在农村地区。",
   "aids":{"morphemes":[M("rur","root","乡村，田野(rus)"),M("al","suffix","…的")],
     "derivation":"rur(田野)+al → 与田野有关的 → 乡村的",
     "family":FAM("rur","乡村、田野",[W("rustic","乡土的")]),
     "mnemonic":"rur=田野(拉丁 rus);属于田园乡下的,就是 rural;反义 urban 城市的(两个一起记)。",
     "forms":[]}},
  {"word":"guilty","phonetic":"ˈɡɪlti","pos":"adj.","def":"有罪的；内疚的","cefr":"B1","freq_rank":63,
   "sentence_en":"He felt guilty about lying.","sentence_zh":"他因撒谎而感到内疚。",
   "aids":{"morphemes":[M("guilt","root","罪，过失"),M("y","suffix","…的")],
     "derivation":"guilt(罪、过失)+y → 有罪的、有过失感的 → 内疚的",
     "family":FAM("","相关词",[W("guilt","罪责")]),
     "mnemonic":"guilt=罪责;犯了罪的=guilty 有罪的;心里觉得对不起=内疚的;plead guilty 认罪;反义 innocent 无罪的。",
     "forms":[F("guilt","n.","罪责；内疚")]}},
  {"word":"necessarily","phonetic":"ˈnesəsərəli","pos":"adv.","def":"必然地，一定","cefr":"B2","freq_rank":43,
   "sentence_en":"That's not necessarily true.","sentence_zh":"那不一定是真的。",
   "aids":{"morphemes":[M("ne","prefix","不"),M("cess","root","让步，走(ced)"),M("arily","suffix","…地")],
     "derivation":"ne(不)+cess(让) → 不可回避、非如此不可 → 必然地",
     "family":FAM("cess/ced","走、让",[W("necessary","必要的"),W("necessity","必需品")]),
     "mnemonic":"necessary(必要的)的副词;'不'(ne-)容退让、非得如此,就是 necessarily 必然地;not necessarily 未必。",
     "forms":[F("necessary","adj.","必要的")]}},
  {"word":"virtually","phonetic":"ˈvɜːtʃuəli","pos":"adv.","def":"几乎，实际上；虚拟地","cefr":"B2","freq_rank":60,
   "sentence_en":"The town was virtually empty.","sentence_zh":"这座镇几乎是空的。",
   "aids":{"morphemes":[M("virtu","root","效力，德性(virtus)"),M("ally","suffix","…地")],
     "derivation":"virtual(实质上的)+ly → 就实际效果而言 → 几乎、实际上",
     "family":FAM("virtu","效力、德性",[W("virtual","虚拟的；实质的"),W("virtue","美德")]),
     "mnemonic":"virtual=实质上的/虚拟的;论实际效果几乎等同,就是 virtually 几乎、实际上;也指电脑'虚拟地'。",
     "forms":[F("virtual","adj.","虚拟的；实质的")]}},
  {"word":"apart","phonetic":"əˈpɑːt","pos":"adv./adj.","def":"分开地，相隔；除…以外","cefr":"B1","freq_rank":45,
   "sentence_en":"The two towns are 10 miles apart.","sentence_zh":"这两座镇相距十英里。",
   "aids":{"morphemes":[M("a","prefix","朝，处于"),M("part","root","部分")],
     "derivation":"a(处于)+part(部分) → 各成一部分、分开 → 分开地",
     "family":FAM("part","部分",[W("partial","部分的"),W("depart","离开"),W("apartment","公寓")]),
     "mnemonic":"part=部分;各自成一块、彼此隔开,就是 apart 分开地;apart from=除…之外/此外;fall apart 散架。",
     "forms":[]}},
  {"word":"barely","phonetic":"ˈbeəli","pos":"adv.","def":"几乎不；仅仅","cefr":"B1","freq_rank":46,
   "sentence_en":"I could barely hear her.","sentence_zh":"我几乎听不见她的声音。",
   "aids":{"morphemes":[M("bare","root","赤裸，仅有"),M("ly","suffix","…地")],
     "derivation":"bare(仅有)+ly → 仅仅够着、勉强 → 几乎不",
     "family":FAM("bare","赤裸、仅有",[W("bare","赤裸的"),W("barefoot","赤脚的")]),
     "mnemonic":"bare=仅有/光秃;只勉强够到那么一点点,就是 barely 几乎不、仅仅;barely enough 勉强够。",
     "forms":[]}},
  {"word":"merely","phonetic":"ˈmɪəli","pos":"adv.","def":"仅仅，只不过","cefr":"B1","freq_rank":50,
   "sentence_en":"It was merely a joke.","sentence_zh":"那只不过是个玩笑。",
   "aids":{"morphemes":[M("mere","root","纯粹，仅"),M("ly","suffix","…地")],
     "derivation":"mere(纯粹、仅)+ly → 只不过 → 仅仅",
     "family":FAM("mere","纯粹、仅",[W("mere","仅仅的")]),
     "mnemonic":"mere=仅仅的(a mere child 只是个孩子);强调'不过如此',就是 merely 仅仅、只不过。",
     "forms":[F("mere","adj.","仅仅的")]}},
  {"word":"beneath","phonetic":"bɪˈniːθ","pos":"prep./adv.","def":"在…下方；低于","cefr":"B1","freq_rank":48,
   "sentence_en":"The keys were beneath the newspaper.","sentence_zh":"钥匙在报纸下面。",
   "aids":{"morphemes":[M("be","prefix","加强"),M("neath","root","下面(nether)")],
     "derivation":"be+neath(下) → 在下方 → 在…下方",
     "family":FAM("neath/nether","下",[W("underneath","在下面"),W("nether","下方的")]),
     "mnemonic":"neath=下(想 underneath 在…底下);位于某物之下,就是 beneath;也表'低于…身份'(beneath him 有失身份)。",
     "forms":[]}},
  {"word":"unfortunately","phonetic":"ʌnˈfɔːtʃunətli","pos":"adv.","def":"不幸地，遗憾的是","cefr":"A2","freq_rank":54,
   "sentence_en":"Unfortunately, the show was cancelled.","sentence_zh":"遗憾的是，演出取消了。",
   "aids":{"morphemes":[M("un","prefix","不"),M("fortun","root","运气"),M("ately","suffix","…地")],
     "derivation":"un(不)+fortune(运气) → 运气不好地 → 不幸地",
     "family":FAM("fortun","运气",[W("fortune","运气；财富"),W("fortunate","幸运的"),W("misfortune","不幸")]),
     "mnemonic":"fortun=运气(想 fortune);运气'不'(un-)好、令人惋惜,就是 unfortunately 遗憾的是;反义 fortunately。",
     "forms":[F("fortunate","adj.","幸运的")]}},
  # 高频名词(常见/词根)
  {"word":"signal","phonetic":"ˈsɪɡnl","pos":"n./v.","def":"信号；示意","cefr":"B1","freq_rank":66,
   "sentence_en":"The green light is a signal to go.","sentence_zh":"绿灯是通行的信号。",
   "aids":{"morphemes":[M("sign","root","记号，标志"),M("al","suffix","名词后缀")],
     "derivation":"sign(记号)+al → 传递信息的记号 → 信号",
     "family":FAM("sign","记号、标志",[W("sign","符号"),W("signature","签名"),W("significant","重要的"),W("design","设计")]),
     "mnemonic":"sign=记号(和 sign 一家);用来传达意思的记号/动作,就是 signal 信号;打手势示意也是 signal。",
     "forms":[F("signals","n.","信号(复数)"),F("signaled","v.","过去式/过去分词")]}},
  {"word":"assistance","phonetic":"əˈsɪstəns","pos":"n.","def":"帮助，协助","cefr":"B1","freq_rank":67,
   "sentence_en":"She offered her assistance.","sentence_zh":"她提供了帮助。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sist","root","站"),M("ance","suffix","名词后缀")],
     "derivation":"as(朝向)+sist(站) → 站到旁边帮忙 → 协助",
     "family":FAM("sist","站",[W("assist","协助"),W("insist","坚持"),W("resist","抵抗"),W("exist","存在")]),
     "mnemonic":"sist=站(和 assist 一家);站到你身旁搭把手,就是 assistance 帮助;assistant 助手。",
     "forms":[F("assist","v.","协助"),F("assistant","n.","助手")]}},
  {"word":"asset","phonetic":"ˈæset","pos":"n.","def":"资产；有价值的人/物","cefr":"B2","freq_rank":70,
   "sentence_en":"Her experience is a great asset.","sentence_zh":"她的经验是一大财富。",
   "aids":{"morphemes":[M("as","prefix","朝向"),M("set","root","足够(satis)")],
     "derivation":"源自 assets'足以偿债的财物';有价值可动用的东西 → 资产",
     "family":FAM("","相关词",[W("assets","资产")]),
     "mnemonic":"asset 源自'足以抵债的财物';可变现、有价值的东西或人才,就是 asset 资产;总以复数 assets 表财产。",
     "forms":[F("assets","n.","资产(复数)")]}},
  {"word":"depression","phonetic":"dɪˈpreʃən","pos":"n.","def":"抑郁；萧条；洼地","cefr":"B2","freq_rank":71,
   "sentence_en":"He suffers from depression.","sentence_zh":"他患有抑郁症。",
   "aids":{"morphemes":[M("de","prefix","向下"),M("press","root","压"),M("ion","suffix","名词后缀")],
     "derivation":"de(向下)+press(压) → 往下压 → 情绪低落=抑郁;经济下压=萧条;地面下压=洼地",
     "family":FAM("press","压",[W("press","压"),W("pressure","压力"),W("express","表达"),W("impress","使印象深")]),
     "mnemonic":"press=压;情绪被向下(de-)压住=抑郁;经济被压=萧条;地被压低=洼地,都是 depression。",
     "forms":[F("depressed","adj.","沮丧的"),F("depressing","adj.","令人沮丧的")]}},
  {"word":"payment","phonetic":"ˈpeɪmənt","pos":"n.","def":"付款，支付(的款项)","cefr":"B1","freq_rank":78,
   "sentence_en":"Payment is due within 30 days.","sentence_zh":"须在30天内付款。",
   "aids":{"morphemes":[M("pay","root","付"),M("ment","suffix","名词后缀")],
     "derivation":"pay(付)+ment → 付钱的行为/款项 → 付款",
     "family":FAM("pay/pac","付、平息",[W("pay","支付"),W("payable","应付的")]),
     "mnemonic":"pay(付)的名词;付出的钱或付钱这件事,就是 payment;down payment 首付。",
     "forms":[F("pay","v.","支付")]}},
  {"word":"therapy","phonetic":"ˈθerəpi","pos":"n.","def":"治疗，疗法","cefr":"B2","freq_rank":92,
   "sentence_en":"She is having physical therapy.","sentence_zh":"她正在接受物理治疗。",
   "aids":{"morphemes":[M("therap","root","治疗，照料"),M("y","suffix","名词后缀")],
     "derivation":"希腊 therapeia'照料、治疗';(尤指非手术的)调理康复 → 疗法",
     "family":FAM("therap","治疗",[W("therapist","治疗师"),W("chemotherapy","化疗")]),
     "mnemonic":"therap=治疗;(常指心理/物理等)调理康复的方法,就是 therapy;therapist 治疗师。",
     "forms":[F("therapist","n.","治疗师"),F("therapies","n.","疗法(复数)")]}},
  {"word":"climate","phonetic":"ˈklaɪmɪt","pos":"n.","def":"气候；风气，氛围","cefr":"B1","freq_rank":76,
   "sentence_en":"The climate is changing.","sentence_zh":"气候正在变化。",
   "aids":{"morphemes":[M("clim","root","倾斜(纬度带)"),M("ate","suffix","名词后缀")],
     "derivation":"希腊 klima'地带倾斜';不同纬度带的天气常态 → 气候",
     "family":FAM("clin/clim","倾斜",[W("incline","倾向"),W("decline","下降")]),
     "mnemonic":"clim=地带倾斜(纬度不同气候不同);某地区长期的天气常态,就是 climate 气候;引申社会'风气'(political climate)。",
     "forms":[F("climates","n.","气候(复数)")]}},
  {"word":"scholar","phonetic":"ˈskɒlə","pos":"n.","def":"学者；奖学金获得者","cefr":"B2","freq_rank":75,
   "sentence_en":"He is a respected scholar.","sentence_zh":"他是位受人尊敬的学者。",
   "aids":{"morphemes":[M("schol","root","学校，学问"),M("ar","suffix","…的人")],
     "derivation":"schol(学问)+ar → 做学问的人 → 学者",
     "family":FAM("schol","学校、学问",[W("school","学校"),W("scholarship","奖学金"),W("scholastic","学业的")]),
     "mnemonic":"schol=学问(和 school 一家);专做学问的人,就是 scholar 学者;scholarship 奖学金/学术。",
     "forms":[F("scholarship","n.","奖学金；学术")]}},
  {"word":"judgment","phonetic":"ˈdʒʌdʒmənt","pos":"n.","def":"判断(力)；裁决","cefr":"B2","freq_rank":37,
   "sentence_en":"Use your own judgment.","sentence_zh":"用你自己的判断。",
   "aids":{"morphemes":[M("judg","root","判断，法官(jud)"),M("ment","suffix","名词后缀")],
     "derivation":"judge(判断)+ment → 判断的能力/结果 → 判断、裁决",
     "family":FAM("jud/jur","判断、法",[W("judge","法官；判断"),W("justice","正义"),W("prejudice","偏见")]),
     "mnemonic":"judg=判断(和 judge 一家);权衡后做出的判定,就是 judgment(英式 judgement);法庭的裁决也是 judgment。",
     "forms":[F("judge","v.","判断")]}},
  {"word":"height","phonetic":"haɪt","pos":"n.","def":"高度；身高；顶点","cefr":"A2","freq_rank":57,
   "sentence_en":"What is the height of the building?","sentence_zh":"这栋楼有多高？",
   "aids":{"morphemes":[M("high","root","高"),M("t","suffix","名词后缀")],
     "derivation":"high(高)的名词形式 → 高度",
     "family":FAM("high","高",[W("high","高的"),W("highness","殿下")]),
     "mnemonic":"height 是 high(高)的名词;有多高=height 高度/身高;事物的顶峰(the height of summer 盛夏)。",
     "forms":[F("heights","n.","高度(复数)")]}},
  {"word":"physician","phonetic":"fɪˈzɪʃən","pos":"n.","def":"(内科)医生","cefr":"B2","freq_rank":58,
   "sentence_en":"Consult your physician first.","sentence_zh":"请先咨询你的医生。",
   "aids":{"morphemes":[M("phys","root","自然，身体"),M("ician","suffix","…的专业人员")],
     "derivation":"phys(身体)+ician → 研究人体、治病的人 → 内科医生",
     "family":FAM("phys","自然、身体",[W("physical","身体的"),W("physics","物理"),W("physique","体格")]),
     "mnemonic":"phys=身体(和 physical 一家);诊治身体疾病的专业人员,就是 physician 内科医生(对照 surgeon 外科医生)。",
     "forms":[F("physicians","n.","医生(复数)")]}},
  {"word":"curriculum","phonetic":"kəˈrɪkjuləm","pos":"n.","def":"课程，全部课程","cefr":"B2","freq_rank":65,
   "sentence_en":"Maths is part of the curriculum.","sentence_zh":"数学是课程的一部分。",
   "aids":{"morphemes":[M("curr","root","跑，进程"),M("iculum","suffix","名词后缀")],
     "derivation":"拉丁 currere'跑'——一段要'跑'完的学习进程 → 课程",
     "family":FAM("curr/cur","跑",[W("current","当前的"),W("occur","发生"),W("course","课程")]),
     "mnemonic":"curr=跑(和 course 课程一家);要一路跑完的整套学习进程,就是 curriculum 课程;复数 curricula。",
     "forms":[F("curricula","n.","课程(复数)"),F("curricular","adj.","课程的")]}},
  {"word":"household","phonetic":"ˈhaʊshəʊld","pos":"n./adj.","def":"家庭，一家人；家用的","cefr":"B1","freq_rank":44,
   "sentence_en":"The average household has two cars.","sentence_zh":"普通家庭拥有两辆车。",
   "aids":{"morphemes":[M("house","root","房子"),M("hold","root","持有")],
     "derivation":"house(房子)+hold(持有) → 同住一屋的一家人 → 家庭",
     "family":FAM("hold","持有",[W("hold","持有"),W("holder","持有者")]),
     "mnemonic":"house(房)+hold(持)——共守一屋的一家人,就是 household 家庭;household name 家喻户晓的名字。",
     "forms":[F("households","n.","家庭(复数)")]}},
  {"word":"agenda","phonetic":"əˈdʒendə","pos":"n.","def":"议程；待办事项","cefr":"B2","freq_rank":88,
   "sentence_en":"What's on the agenda today?","sentence_zh":"今天的议程是什么？",
   "aids":{"morphemes":[M("ag","root","做，行动"),M("enda","suffix","该做的(复数)")],
     "derivation":"拉丁 agenda'该做的事'(ag 做);要办的事项清单 → 议程",
     "family":FAM("ag/act","做、行动",[W("agent","代理人"),W("act","行动"),W("agency","机构")]),
     "mnemonic":"ag=做(和 agent 一家);'该做之事'的清单,就是 agenda 议程;hidden agenda 不可告人的目的。",
     "forms":[F("agendas","n.","议程(复数)")]}},
  {"word":"criminal","phonetic":"ˈkrɪmɪnl","pos":"n./adj.","def":"罪犯；犯罪的，刑事的","cefr":"B1","freq_rank":41,
   "sentence_en":"The criminal was sent to prison.","sentence_zh":"罪犯被送进了监狱。",
   "aids":{"morphemes":[M("crimin","root","罪"),M("al","suffix","…的")],
     "derivation":"crimin(罪)+al → 有罪的(人) → 罪犯、刑事的",
     "family":FAM("crim","罪",[W("crime","罪行"),W("incriminate","归罪于")]),
     "mnemonic":"crimin=罪(和 crime 一家);犯了罪的人=criminal 罪犯;与犯罪有关的=刑事的(criminal law 刑法)。",
     "forms":[F("crime","n.","罪行"),F("criminals","n.","罪犯(复数)")]}},
  {"word":"route","phonetic":"ruːt","pos":"n./v.","def":"路线，路径；发送","cefr":"B1","freq_rank":40,
   "sentence_en":"We took the fastest route.","sentence_zh":"我们走了最快的路线。",
   "aids":{"morphemes":[M("rout","root","冲开的路(rupt 破)"),M("e","suffix","结尾")],
     "derivation":"与 rupt'破、冲'同源;冲开出来的通道 → 路线",
     "family":FAM("rupt","破、冲",[W("rupture","破裂"),W("interrupt","打断"),W("route","路线")]),
     "mnemonic":"route 与 rupt(冲破)同源;冲开出来供通行的道,就是 route 路线;en route 在途中。",
     "forms":[F("routes","n.","路线(复数)")]}},
  {"word":"core","phonetic":"kɔː","pos":"n./adj.","def":"核心，要点；核心的","cefr":"B2","freq_rank":42,
   "sentence_en":"Let's get to the core of the problem.","sentence_zh":"让我们抓住问题的核心。",
   "aids":{"morphemes":[M("core","root","心，核(cor)")],
     "derivation":"与 cor'心'同源;最中心、最要紧的部分 → 核心",
     "family":FAM("cor/cord","心",[W("cordial","热忱的"),W("courage","勇气"),W("record","记录")]),
     "mnemonic":"core 与 cor(心,如 courage 勇气)同源;最中心、最要害的部分,就是 core 核心;core values 核心价值。",
     "forms":[F("cores","n.","核心(复数)")]}},
  {"word":"chest","phonetic":"tʃest","pos":"n.","def":"胸部；箱子，柜","cefr":"B1","freq_rank":26,
   "sentence_en":"He has a pain in his chest.","sentence_zh":"他胸口疼。",
   "aids":{"morphemes":[M("chest","root","箱子(cista)")],
     "derivation":"希腊 kiste'箱子';胸腔像装心肺的'箱子' → 胸部;本义'箱子'仍在(toolchest 工具箱)",
     "family":FAM("cist/chest","箱",[W("cistern","水箱")]),
     "mnemonic":"chest 本义'箱子';胸腔像装心肺的箱子=胸部;装东西的木箱=chest(chest of drawers 五斗柜)。",
     "forms":[F("chests","n.","胸部(复数)")]}},
  {"word":"limited","phonetic":"ˈlɪmɪtɪd","pos":"adj.","def":"有限的","cefr":"B1","freq_rank":49,
   "sentence_en":"Seats are limited.","sentence_zh":"座位有限。",
   "aids":{"morphemes":[M("limit","root","界限"),M("ed","suffix","…的")],
     "derivation":"limit(界限)+ed → 有界限的 → 有限的","family":FAM("limit","界限",[W("limit","限制"),W("eliminate","消除")]),
     "mnemonic":"limit=界限;被框住、数量不多的,就是 limited。","forms":[F("limitation","n.","局限")]}},
  # 常见词
  {"word":"smart","phonetic":"smɑːt","pos":"adj.","def":"聪明的；时髦的；智能的","cefr":"A2","freq_rank":34,
   "sentence_en":"That's a smart idea.","sentence_zh":"那是个聪明的主意。",
   "aids":{"morphemes":[M("smart","root","刺痛，机敏(古英语 smeortan)")],
     "derivation":"古英语'刺痛'→ 引申'机敏、伶俐'→ 聪明的;衣着利落=时髦的",
     "family":FAM("","相关词",[W("smartphone","智能手机")]),
     "mnemonic":"smart 从'刺痛'引申'脑子灵光';机灵=聪明的;穿着利落=时髦的;能联网的=智能的(smartphone)。",
     "forms":[F("smarter","adj.","更聪明的(比较级)"),F("smartly","adv.","漂亮地")]}},
  {"word":"pour","phonetic":"pɔː","pos":"v.","def":"倒，灌；倾泻；涌","cefr":"B1","freq_rank":35,
   "sentence_en":"She poured the tea.","sentence_zh":"她倒了茶。",
   "aids":{"morphemes":[M("pour","root","流出，倾倒(purare)")],
     "derivation":"古法语'滤、倒';使液体流出 → 倒、倾泻",
     "family":FAM("","相关词",[W("downpour","倾盆大雨")]),
     "mnemonic":"pour=倒/倾泻;把液体哗啦倒出=pour;大雨倾盆=it's pouring;人群涌出=pour out;downpour 暴雨。",
     "forms":[F("poured","v.","过去式/过去分词"),F("pouring","adj.","倾盆的")]}},
  {"word":"stir","phonetic":"stɜː","pos":"v./n.","def":"搅拌；激起；骚动","cefr":"B1","freq_rank":36,
   "sentence_en":"Stir the soup gently.","sentence_zh":"轻轻搅拌汤。",
   "aids":{"morphemes":[M("stir","root","搅动(古英语 styrian)")],
     "derivation":"古英语'搅动、扰动';使转动混合 → 搅拌;使情绪涌动 → 激起",
     "family":FAM("","相关词",[W("stirring","激动人心的")]),
     "mnemonic":"stir=搅动;拿勺搅匀=搅拌;搅动人心=激起(stir up trouble 挑起事端);cause a stir 引起轰动。",
     "forms":[F("stirred","v.","过去式/过去分词"),F("stirring","adj.","激动人心的")]}},
  {"word":"cast","phonetic":"kɑːst","pos":"v./n.","def":"投掷；投射；分派角色；演员阵容","cefr":"B2","freq_rank":56,
   "sentence_en":"The tree cast a long shadow.","sentence_zh":"这棵树投下长长的影子。",
   "aids":{"morphemes":[M("cast","root","投掷(古诺斯语 kasta)")],
     "derivation":"古诺斯语'抛';用力抛出 → 投掷;把光/影抛出 → 投射;给演员'派'角色 → 分派",
     "family":FAM("","相关词",[W("broadcast","广播"),W("forecast","预测")]),
     "mnemonic":"cast=抛(过去式仍是 cast);抛出=投掷;抛出光影=投射;给演员派角色=cast;一部剧全体演员=the cast。",
     "forms":[F("casts","n.","演员阵容(复数)")]}},
  {"word":"wrap","phonetic":"ræp","pos":"v./n.","def":"包，裹；缠绕","cefr":"B1","freq_rank":68,
   "sentence_en":"Wrap the gift in paper.","sentence_zh":"用纸把礼物包起来。",
   "aids":{"morphemes":[M("wrap","root","包裹(中古英语 wrappen)")],
     "derivation":"中古英语'卷、裹';用东西围绕包住 → 包、缠",
     "family":FAM("","相关词",[W("wrapper","包装纸"),W("wrapping","包装")]),
     "mnemonic":"wrap=包裹;把东西用纸/布围起来=wrap;缠绕=wrap around;wrap up 包好/收尾(总结)。",
     "forms":[F("wrapped","v.","过去式/过去分词"),F("wrapping","n.","包装")]}},
  {"word":"chip","phonetic":"tʃɪp","pos":"n./v.","def":"碎片，薄片；芯片；(把…)削出缺口","cefr":"B1","freq_rank":100,
   "sentence_en":"The computer chip is tiny.","sentence_zh":"这块电脑芯片很小。",
   "aids":{"morphemes":[M("chip","root","碎片(古英语 cipp)")],
     "derivation":"古英语'削下的小片';削凿掉的小块 → 碎片、薄片;硅片做的=芯片",
     "family":FAM("","相关词",[W("microchip","微芯片")]),
     "mnemonic":"chip=削下的小片;薯片=chips;硅做的小片=芯片;碰掉一角=chip(缺口);chip in 凑钱/插话。",
     "forms":[F("chips","n.","薯片(复数)"),F("chipped","v.","过去式/过去分词")]}},
  {"word":"fuel","phonetic":"ˈfjuːəl","pos":"n./v.","def":"燃料；给…加燃料；加剧","cefr":"B1","freq_rank":23,
   "sentence_en":"The car ran out of fuel.","sentence_zh":"汽车没油了。",
   "aids":{"morphemes":[M("fuel","root","燃料(focus 炉灶)")],
     "derivation":"与 focus'炉灶'同源;供炉灶烧的东西 → 燃料;给…添料 → 加剧",
     "family":FAM("","相关词",[W("refuel","加油")]),
     "mnemonic":"fuel 与 focus(炉灶)同源;喂给发动机/炉子烧的=燃料;给矛盾'添柴'=加剧(fuel tensions)。",
     "forms":[F("fuels","n.","燃料(复数)"),F("fueled","v.","过去式/过去分词")]}},
  {"word":"cash","phonetic":"kæʃ","pos":"n./v.","def":"现金；兑现","cefr":"A2","freq_rank":27,
   "sentence_en":"Do you pay by cash or card?","sentence_zh":"你付现金还是刷卡？",
   "aids":{"morphemes":[M("cash","root","钱箱(cassa)")],
     "derivation":"意大利 cassa'钱箱';箱里的钱 → 现金;把支票换成现金 → 兑现",
     "family":FAM("cas/cash","箱",[W("cashier","收银员")]),
     "mnemonic":"cash 源自'钱箱';手头的真金白银=现金;把支票'换出钱来'=cash 兑现;cashier 收银员。",
     "forms":[F("cashed","v.","过去式/过去分词")]}},
  {"word":"plastic","phonetic":"ˈplæstɪk","pos":"n./adj.","def":"塑料；塑料的；可塑的","cefr":"A2","freq_rank":21,
   "sentence_en":"Avoid single-use plastic.","sentence_zh":"避免使用一次性塑料。",
   "aids":{"morphemes":[M("plast","root","塑造，成形"),M("ic","suffix","…的")],
     "derivation":"plast(塑造)+ic → 可任意塑形的材料 → 塑料",
     "family":FAM("plast","塑造",[W("plaster","石膏"),W("plastic surgery","整形手术")]),
     "mnemonic":"plast=塑造(想 plastic surgery 整形);能随意捏塑成形的材料,就是 plastic 塑料;引申'可塑的'。",
     "forms":[F("plastics","n.","塑料(复数)")]}},
  {"word":"forth","phonetic":"fɔːθ","pos":"adv.","def":"向前；向外","cefr":"B2","freq_rank":31,
   "sentence_en":"From that day forth, they were friends.","sentence_zh":"从那天起，他们成了朋友。",
   "aids":{"morphemes":[M("forth","root","向前(fore)")],
     "derivation":"与 fore'前'同源;向前、向外 → forth",
     "family":FAM("fore/forth","前",[W("forward","向前"),W("further","进一步")]),
     "mnemonic":"forth 与 fore(前)一家;向前/向外,就是 forth;and so forth 等等;back and forth 来回;set forth 阐明。",
     "forms":[]}},
  {"word":"hall","phonetic":"hɔːl","pos":"n.","def":"大厅，礼堂；门厅，走廊","cefr":"A2","freq_rank":32,
   "sentence_en":"The concert is in the main hall.","sentence_zh":"音乐会在主礼堂举行。",
   "aids":{"morphemes":[M("hall","root","遮盖的大屋(古英语 heall)")],
     "derivation":"古英语'有顶的大屋';宽敞的房间 → 大厅、礼堂",
     "family":FAM("","相关词",[W("hallway","走廊")]),
     "mnemonic":"hall=大屋;举行活动的宽敞屋子=大厅/礼堂;进门的过道=门厅(hallway 走廊);city hall 市政厅。",
     "forms":[F("halls","n.","大厅(复数)")]}},
  {"word":"meanwhile","phonetic":"ˈmiːnwaɪl","pos":"adv.","def":"与此同时；期间","cefr":"B1","freq_rank":33,
   "sentence_en":"Meanwhile, I'll prepare dinner.","sentence_zh":"与此同时，我来准备晚饭。",
   "aids":{"morphemes":[M("mean","root","中间(medi)"),M("while","root","一段时间")],
     "derivation":"mean(中间)+while(时段) → 在这中间的时段 → 与此同时",
     "family":FAM("","相关词",[W("while","当…时候"),W("meantime","其间")]),
     "mnemonic":"mean(中间)+while(时段)——在两事之间的这段时间里,就是 meanwhile 与此同时;=in the meantime。",
     "forms":[]}},
  {"word":"county","phonetic":"ˈkaʊnti","pos":"n.","def":"县，郡","cefr":"B1","freq_rank":20,
   "sentence_en":"She lives in a rural county.","sentence_zh":"她住在一个乡村县。",
   "aids":{"morphemes":[M("count","root","伯爵(comes)"),M("y","suffix","名词后缀")],
     "derivation":"原指'伯爵(count)管辖的领地' → 郡、县",
     "family":FAM("","相关词",[W("count","伯爵")]),
     "mnemonic":"county 是'伯爵(count)的领地';现指行政区划的县/郡,就是 county;别和 country 国家混。",
     "forms":[F("counties","n.","县(复数)")]}},
  {"word":"studio","phonetic":"ˈstjuːdiəʊ","pos":"n.","def":"工作室，画室；演播室","cefr":"B1","freq_rank":19,
   "sentence_en":"The band recorded in a studio.","sentence_zh":"乐队在录音棚里录音。",
   "aids":{"morphemes":[M("stud","root","钻研，努力"),M("io","suffix","名词后缀")],
     "derivation":"与 study'钻研'同源;潜心创作的房间 → 工作室",
     "family":FAM("stud","钻研",[W("study","学习"),W("student","学生"),W("studious","好学的")]),
     "mnemonic":"studio 与 study 同源;艺术家/主播潜心创作的房间,就是 studio 工作室、演播室。",
     "forms":[F("studios","n.","工作室(复数)")]}},
  {"word":"regarding","phonetic":"rɪˈɡɑːdɪŋ","pos":"prep.","def":"关于，就…而言","cefr":"B1","freq_rank":96,
   "sentence_en":"I have a question regarding the schedule.","sentence_zh":"关于日程我有个问题。",
   "aids":{"morphemes":[M("re","prefix","再，回"),M("gard","root","看守，注视(guard)")],
     "derivation":"regard(注视、看待)+ing → 就…来看 → 关于",
     "family":FAM("gard/guard","看守、注视",[W("regard","看待"),W("guard","守卫"),W("reward","奖赏")]),
     "mnemonic":"gard=看/守(和 guard 一家);'就…来看'=regarding 关于;=concerning/with regard to。",
     "forms":[F("regard","v.","看待")]}},
  {"word":"plus","phonetic":"plʌs","pos":"prep./adj./n.","def":"加上；正的；优势","cefr":"A2","freq_rank":64,
   "sentence_en":"Two plus two is four.","sentence_zh":"二加二等于四。",
   "aids":{"morphemes":[M("plus","root","更多(拉丁 plus)")],
     "derivation":"拉丁 plus'更多';再添上 → 加上;数值为正 → 正的",
     "family":FAM("plu/plur","多",[W("plural","复数的"),W("surplus","盈余")]),
     "mnemonic":"plus=更多(想 plural 复数、surplus 盈余);再添上=加上(2 plus 2);带来好处的一点=a plus 优势。",
     "forms":[]}},
  {"word":"brief","phonetic":"briːf","pos":"adj./n./v.","def":"简短的；简报；给…做简报","cefr":"B1","freq_rank":94,
   "sentence_en":"Keep your answer brief.","sentence_zh":"回答尽量简短。",
   "aids":{"morphemes":[M("brief","root","短(brevis)")],
     "derivation":"拉丁 brevis'短';时间/篇幅短的 → 简短的",
     "family":FAM("brev/brief","短",[W("abbreviate","缩写"),W("abbreviation","缩写")]),
     "mnemonic":"brief=短(想 abbreviate 缩短);简短的=brief;简要情况介绍=briefing;in brief 简而言之。",
     "forms":[F("briefly","adv.","简短地"),F("briefing","n.","简报")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 11
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
