#!/usr/bin/env python
# 第二十二批(约50词,本轮收官):逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -title 头衔/权利
  {"word":"entitle","phonetic":"ɪnˈtaɪtl","pos":"v.","def":"给…权利(资格)；给…命名","cefr":"B2","freq_rank":68,
   "sentence_en":"This ticket entitles you to a free drink.","sentence_zh":"这张票让你可以免费喝一杯。",
   "aids":{"morphemes":[M("en","prefix","使…"),M("title","root","头衔，权利")],
     "derivation":"en(使)+title(权利) → 使拥有权利 → 给…权利;给以名号 → 命名",
     "family":FAM("title","头衔、权利",[W("title","标题；头衔"),W("titled","有头衔的")]),
     "mnemonic":"en-(使)+title(权利/名号)——给某人权利/资格,就是 entitle(be entitled to 有权得到);给作品定名=命名;entitlement 权利。",
     "forms":[F("entitled","adj.","有权利的"),F("entitlement","n.","权利")]}},
  # -esse 存在
  {"word":"essence","phonetic":"ˈesns","pos":"n.","def":"本质，实质；精华","cefr":"B2","freq_rank":69,
   "sentence_en":"Freedom is the essence of democracy.","sentence_zh":"自由是民主的本质。",
   "aids":{"morphemes":[M("ess","root","存在，是(esse)"),M("ence","suffix","名词后缀")],
     "derivation":"ess(存在)+ence → 使之成其所是的东西 → 本质",
     "family":FAM("ess/esse","存在、是",[W("essential","本质的"),W("present","在场的"),W("absent","缺席的")]),
     "mnemonic":"ess=存在(和 essential 一家);使事物成为它自己的根本属性,就是 essence 本质;in essence 本质上;香'精'也是 essence。",
     "forms":[F("essential","adj.","本质的")]}},
  # -vers 转
  {"word":"reverse","phonetic":"rɪˈvɜːs","pos":"v./n./adj.","def":"颠倒，翻转；倒退；相反(的)","cefr":"B2","freq_rank":80,
   "sentence_en":"They reversed their decision.","sentence_zh":"他们推翻了原来的决定。",
   "aids":{"morphemes":[M("re","prefix","反，回"),M("vers","root","转")],
     "derivation":"re(反)+vers(转) → 反转过来 → 颠倒",
     "family":FAM("vers/vert","转",[W("convert","转换"),W("version","版本"),W("universe","宇宙"),W("diverse","多样的")]),
     "mnemonic":"vers=转(和 convert 一家);反(re-)着转过来,就是 reverse 颠倒/倒车;相反的一面=the reverse;in reverse 反向。",
     "forms":[F("reversal","n.","逆转"),F("reversible","adj.","可逆的")]}},
  # -relat 带
  {"word":"correlation","phonetic":"ˌkɒrəˈleɪʃən","pos":"n.","def":"相关(性)，关联","cefr":"C1","freq_rank":83,
   "sentence_en":"There is a correlation between diet and health.","sentence_zh":"饮食与健康之间存在关联。",
   "aids":{"morphemes":[M("cor","prefix","一起(com)"),M("relat","root","带，联系"),M("ion","suffix","名词后缀")],
     "derivation":"cor(一起)+relate(联系) → 相互关联 → 相关性",
     "family":FAM("lat/relat","带、联系",[W("relate","使有联系"),W("relation","关系"),W("relative","相对的")]),
     "mnemonic":"和 relate(联系)一家;两者相互(cor-)牵连、一起变动,就是 correlation 相关性;correlate 相关联。",
     "forms":[F("correlate","v.","相关联")]}},
  # -ly 绑
  {"word":"reliable","phonetic":"rɪˈlaɪəbl","pos":"adj.","def":"可靠的，可信赖的","cefr":"B1","freq_rank":84,
   "sentence_en":"She is a reliable friend.","sentence_zh":"她是个可靠的朋友。",
   "aids":{"morphemes":[M("re","prefix","再"),M("ly","root","绑，靠(lig)"),M("able","suffix","可…的")],
     "derivation":"rely(倚靠)+able → 可以倚靠的 → 可靠的",
     "family":FAM("li/lig","绑、靠",[W("rely","依赖"),W("reliance","依赖"),W("ally","盟友")]),
     "mnemonic":"ly=靠(和 rely 一家);靠得住、值得信赖的,就是 reliable;反义 unreliable;reliability 可靠性。",
     "forms":[F("rely","v.","依赖"),F("reliability","n.","可靠性")]}},
  # -it 走
  {"word":"initiate","phonetic":"ɪˈnɪʃieɪt","pos":"v.","def":"发起，开始；使入门","cefr":"C1","freq_rank":92,
   "sentence_en":"They initiated a new project.","sentence_zh":"他们启动了一个新项目。",
   "aids":{"morphemes":[M("in","prefix","进入"),M("it","root","走"),M("iate","suffix","动词后缀")],
     "derivation":"in(进入)+it(走) → 迈步开走、领入门 → 发起",
     "family":FAM("it","走、行",[W("initial","最初的"),W("initiative","主动性"),W("exit","出口")]),
     "mnemonic":"it=走(和 initial 一家);迈出第一步开启,就是 initiate 发起;带新人入门=initiate;initiation 开始/入会。",
     "forms":[F("initiation","n.","开始；入会")]}},
  # -lect 读/选
  {"word":"lecture","phonetic":"ˈlektʃə","pos":"n./v.","def":"讲座，演讲；训诫，教训","cefr":"B1","freq_rank":93,
   "sentence_en":"I attended a lecture on history.","sentence_zh":"我听了一场历史讲座。",
   "aids":{"morphemes":[M("lect","root","读，讲"),M("ure","suffix","名词后缀")],
     "derivation":"lect(读、讲)+ure → 当众宣讲 → 讲座",
     "family":FAM("lect/leg","读、选",[W("lecturer","讲师"),W("select","挑选"),W("collect","收集")]),
     "mnemonic":"lect=读/讲(想 select 挑读);当众宣讲的一堂课=lecture 讲座;板着脸说教=训诫(give sb a lecture);lecturer 讲师。",
     "forms":[F("lecturer","n.","讲师"),F("lectures","n.","讲座(复数)")]}},
  # -mot 动
  {"word":"motivate","phonetic":"ˈməʊtɪveɪt","pos":"v.","def":"激励，激发；成为…的动机","cefr":"B2","freq_rank":97,
   "sentence_en":"Good teachers motivate their students.","sentence_zh":"好老师会激励学生。",
   "aids":{"morphemes":[M("mot","root","动"),M("iv","root",""),M("ate","suffix","动词后缀")],
     "derivation":"motive(动机)+ate → 给予动机、使动起来 → 激励",
     "family":FAM("mot/mov","动",[W("motive","动机"),W("motion","运动"),W("emotion","情绪"),W("promote","促进")]),
     "mnemonic":"mot=动(和 motive 动机一家);给人动力使其行动起来,就是 motivate 激励;motivation 积极性;motivated 有干劲的。",
     "forms":[F("motivation","n.","动机；积极性"),F("motivated","adj.","有干劲的")]}},
  # -red 归还
  {"word":"render","phonetic":"ˈrendə","pos":"v.","def":"使成为，使处于；提供，给予；呈现","cefr":"C1","freq_rank":99,
   "sentence_en":"The news rendered him speechless.","sentence_zh":"这消息使他哑口无言。",
   "aids":{"morphemes":[M("re","prefix","回，back"),M("nd","root","给(dare)"),M("er","suffix","动词后缀")],
     "derivation":"re(回)+nd(给) → 回给、致使处于某状态 → 使成为、提供",
     "family":FAM("d/dat","给",[W("render","使成为"),W("surrender","投降")]),
     "mnemonic":"和 dare/give(给)相关;把某物'弄成'某状态=render sb/sth + adj.(render useless 使无用);提供服务=render;surrender 交出/投降。",
     "forms":[F("rendered","v.","过去式/过去分词")]}},
  # -spons 承诺
  {"word":"sponsor","phonetic":"ˈspɒnsə","pos":"n./v.","def":"赞助商，发起人；赞助，主办","cefr":"B2","freq_rank":63,
   "sentence_en":"The event was sponsored by a bank.","sentence_zh":"这项活动由一家银行赞助。",
   "aids":{"morphemes":[M("spons","root","承诺，保证"),M("or","suffix","…的人")],
     "derivation":"spons(承诺、担保)+or → 承诺出资担保的人 → 赞助商",
     "family":FAM("spons/spond","承诺、回答",[W("respond","回应"),W("responsible","负责的"),W("response","回应")]),
     "mnemonic":"spons=承诺担保(和 responsible 一家);承诺出钱撑腰的一方,就是 sponsor 赞助商;动词=赞助;sponsorship 赞助。",
     "forms":[F("sponsorship","n.","赞助")]}},
  # -civ 公民
  {"word":"civilization","phonetic":"ˌsɪvəlaɪˈzeɪʃən","pos":"n.","def":"文明，文明社会","cefr":"B2","freq_rank":66,
   "sentence_en":"Ancient Egyptian civilization was advanced.","sentence_zh":"古埃及文明很先进。",
   "aids":{"morphemes":[M("civil","root","公民，城市"),M("ization","suffix","名词后缀")],
     "derivation":"civilize(使开化)+ation → 由城市公民生活发展出的高级社会形态 → 文明",
     "family":FAM("civ","公民",[W("civil","公民的"),W("civilian","平民"),W("city","城市")]),
     "mnemonic":"civ=公民/城市(和 civil 一家);由城邦公民生活演进出的高级社会,就是 civilization 文明;动词 civilize。",
     "forms":[F("civilize","v.","使开化"),F("civilized","adj.","文明的")]}},
  # -inter 内
  {"word":"interior","phonetic":"ɪnˈtɪəriə","pos":"n./adj.","def":"内部(的)，室内(的)；内地","cefr":"B2","freq_rank":73,
   "sentence_en":"The car has a leather interior.","sentence_zh":"这辆车内饰是皮革的。",
   "aids":{"morphemes":[M("inter","root","内部"),M("ior","suffix","较…的")],
     "derivation":"inter(内)的比较级 → 更靠里的 → 内部的",
     "family":FAM("inter/intern","内、之间",[W("internal","内部的"),W("internal","内部的")]),
     "mnemonic":"inter=内(和 internal 一家);里面的、室内的,就是 interior(interior design 室内设计);反义 exterior 外部的。",
     "forms":[F("interiors","n.","内部(复数)")]}},
  # -tail 切
  {"word":"retail","phonetic":"ˈriːteɪl","pos":"n./adj./v.","def":"零售(的)；零售","cefr":"B2","freq_rank":74,
   "sentence_en":"She works in retail.","sentence_zh":"她在零售业工作。",
   "aids":{"morphemes":[M("re","prefix","再，分"),M("tail","root","切")],
     "derivation":"re(分)+tail(切) → 把整批切开一点点卖 → 零售",
     "family":FAM("tail","切",[W("tailor","裁缝"),W("detail","细节"),W("curtail","缩减")]),
     "mnemonic":"tail=切(和 detail 一家);把大批货'切开'零星卖给顾客,就是 retail 零售;反义 wholesale 批发;retailer 零售商。",
     "forms":[F("retailer","n.","零售商")]}},
  # -weak 弱
  {"word":"weakness","phonetic":"ˈwiːknəs","pos":"n.","def":"虚弱；弱点，缺点；偏爱","cefr":"B1","freq_rank":75,
   "sentence_en":"Everyone has their weaknesses.","sentence_zh":"每个人都有弱点。",
   "aids":{"morphemes":[M("weak","root","弱的"),M("ness","suffix","名词后缀")],
     "derivation":"weak(弱的)+ness → 弱的状态/方面 → 虚弱、弱点",
     "family":FAM("weak","弱",[W("weak","弱的"),W("weaken","削弱")]),
     "mnemonic":"weak=弱;体虚=虚弱;短板=弱点;'难以抗拒的偏好'=a weakness for(have a weakness for chocolate);反义 strength 力量/长处。",
     "forms":[F("weak","adj.","弱的"),F("weaken","v.","削弱")]}},
  # -ploy 折/用
  {"word":"unemployment","phonetic":"ˌʌnɪmˈplɔɪmənt","pos":"n.","def":"失业；失业率","cefr":"B2","freq_rank":77,
   "sentence_en":"Unemployment is rising.","sentence_zh":"失业率正在上升。",
   "aids":{"morphemes":[M("un","prefix","不"),M("employ","root","雇用"),M("ment","suffix","名词后缀")],
     "derivation":"un(不)+employment(就业) → 没有工作 → 失业",
     "family":FAM("ploy/plic","折、用",[W("employ","雇用"),W("employment","就业"),W("employer","雇主")]),
     "mnemonic":"un-(不)+employment(就业)——没被雇用、没工作,就是 unemployment 失业;unemployed 失业的;反义 employment。",
     "forms":[F("unemployed","adj.","失业的")]}},
  # -human 人
  {"word":"humanity","phonetic":"hjuːˈmænəti","pos":"n.","def":"人类；人性；人道，博爱","cefr":"B2","freq_rank":82,
   "sentence_en":"Crimes against humanity.","sentence_zh":"反人类罪。",
   "aids":{"morphemes":[M("human","root","人"),M("ity","suffix","名词后缀")],
     "derivation":"human(人)+ity → 人的全体/人的本性 → 人类、人性",
     "family":FAM("human","人",[W("human","人类的"),W("humane","人道的"),W("humanitarian","人道主义的")]),
     "mnemonic":"human=人;全体人=人类;人的良善本性=人性/博爱,都是 humanity;the humanities 人文学科;humane 人道的。",
     "forms":[F("humane","adj.","人道的")]}},
  # -minister 管理
  {"word":"administrative","phonetic":"ədˈmɪnɪstrətɪv","pos":"adj.","def":"行政的，管理的","cefr":"B2","freq_rank":87,
   "sentence_en":"She handles administrative tasks.","sentence_zh":"她处理行政事务。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("minister","root","服务，管理"),M("ative","suffix","…的")],
     "derivation":"administer(管理)+ative → 与管理有关的 → 行政的",
     "family":FAM("minister","服务、管理",[W("administer","管理"),W("administration","行政"),W("minister","部长")]),
     "mnemonic":"和 administration(行政)一家(minister 管事);关于机构管理、行政的,就是 administrative。",
     "forms":[F("administration","n.","行政")]}},
  # -fus 倒
  {"word":"confuse","phonetic":"kənˈfjuːz","pos":"v.","def":"使困惑；混淆","cefr":"B1","freq_rank":90,
   "sentence_en":"Don't confuse me with too many details.","sentence_zh":"别用太多细节把我搞糊涂。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("fus","root","倒，流")],
     "derivation":"con(一起)+fus(倒) → 全倒到一起搅乱 → 使困惑、混淆",
     "family":FAM("fus/found","倒、流",[W("confusion","混乱"),W("refuse","拒绝"),W("confound","混淆")]),
     "mnemonic":"fus=倒(把东西倒一起搅);把人搅糊涂/把两者搞混,就是 confuse;confused 困惑的;confusing 令人困惑的。",
     "forms":[F("confused","adj.","困惑的"),F("confusion","n.","混乱")]}},
  # -crit 判断
  {"word":"criticise","phonetic":"ˈkrɪtɪsaɪz","pos":"v.","def":"批评，指责；评论","cefr":"B1","freq_rank":61,
   "sentence_en":"He criticised the government's policy.","sentence_zh":"他批评了政府的政策。",
   "aids":{"morphemes":[M("crit","root","判断，分辨"),M("icise","suffix","使…(动词)")],
     "derivation":"critic(评判者)→ 做出评判、挑毛病 → 批评",
     "family":FAM("crit","判断、分辨",[W("critic","批评家"),W("critical","批判的"),W("criterion","标准")]),
     "mnemonic":"crit=判断(和 critic 一家);评判并挑出毛病,就是 criticise(美式 criticize);criticism 批评;critic 批评家。",
     "forms":[F("criticism","n.","批评"),F("critic","n.","批评家")]}},
  # -second 第二
  {"word":"secondary","phonetic":"ˈsekəndri","pos":"adj.","def":"次要的；中等的，中学的；第二的","cefr":"B1","freq_rank":65,
   "sentence_en":"She teaches at a secondary school.","sentence_zh":"她在一所中学教书。",
   "aids":{"morphemes":[M("second","root","第二"),M("ary","suffix","…的")],
     "derivation":"second(第二)+ary → 排第二位的 → 次要的;第二阶段教育 → 中学的",
     "family":FAM("secu/sequ","跟随",[W("second","第二"),W("sequence","顺序")]),
     "mnemonic":"second=第二;排第二、不那么重要的=次要的;小学之后的第二阶段=中学的(secondary school);反义 primary 首要的/小学的。",
     "forms":[F("secondarily","adv.","其次")]}},
  # -tect 建
  {"word":"architecture","phonetic":"ˈɑːkɪtektʃə","pos":"n.","def":"建筑学，建筑风格；(计算机)体系结构","cefr":"B2","freq_rank":86,
   "sentence_en":"I love Gothic architecture.","sentence_zh":"我喜欢哥特式建筑。",
   "aids":{"morphemes":[M("archi","prefix","首，主"),M("tect","root","建造"),M("ure","suffix","名词后缀")],
     "derivation":"architect(建筑师)+ure → 建造的艺术/风格 → 建筑学",
     "family":FAM("archi/tect","首、建造",[W("architect","建筑师"),W("monarch","君主")]),
     "mnemonic":"和 architect(建筑师)一家;建造房屋的学问/风格=architecture 建筑学;系统的整体'构建方式'=体系结构。",
     "forms":[F("architect","n.","建筑师"),F("architectural","adj.","建筑的")]}},
  # -cit 激起
  {"word":"excitement","phonetic":"ɪkˈsaɪtmənt","pos":"n.","def":"兴奋，激动","cefr":"B1","freq_rank":85,
   "sentence_en":"The news caused great excitement.","sentence_zh":"这消息引起了极大兴奋。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("cit","root","召唤，激起"),M("ement","suffix","名词后缀")],
     "derivation":"excite(激起)+ment → 被激起的状态 → 兴奋",
     "family":FAM("cit","召唤、激起",[W("excite","使兴奋"),W("cite","引用"),W("recite","背诵")]),
     "mnemonic":"cit=激起(和 excite 一家);情绪被向外(ex-)激发起来,就是 excitement 兴奋;动词 excite;exciting 令人兴奋的。",
     "forms":[F("excite","v.","使兴奋"),F("exciting","adj.","令人兴奋的")]}},
  # 高频形容词/常见词
  {"word":"subtle","phonetic":"ˈsʌtl","pos":"adj.","def":"微妙的，细微的；精巧的","cefr":"B2","freq_rank":59,
   "sentence_en":"There is a subtle difference.","sentence_zh":"这里有个微妙的差别。",
   "aids":{"morphemes":[M("sub","prefix","在下"),M("tle","root","织(tela 织物)")],
     "derivation":"拉丁 subtilis'织得细密的';细到不易察觉 → 微妙的(b 不发音)",
     "family":FAM("","相关词",[W("subtlety","微妙")]),
     "mnemonic":"原义'织得极细密';细微到难以察觉、需细品的,就是 subtle 微妙的(读 /ˈsʌtl/,b 不发音);subtlety 微妙之处。",
     "forms":[F("subtlety","n.","微妙"),F("subtly","adv.","微妙地")]}},
  {"word":"harsh","phonetic":"hɑːʃ","pos":"adj.","def":"严厉的，苛刻的；刺耳的；(环境)恶劣的","cefr":"B2","freq_rank":71,
   "sentence_en":"Don't be too harsh on yourself.","sentence_zh":"别对自己太苛刻。",
   "aids":{"morphemes":[M("harsh","root","粗糙(中古英语 harsk)")],
     "derivation":"中古英语'粗糙';令人难受的粗砺 → 严厉的、刺耳的",
     "family":FAM("","相关词",[W("harshly","严厉地")]),
     "mnemonic":"harsh=粗糙难受;责罚不留情=严厉/苛刻;声音刺耳=harsh;气候/条件恶劣=harsh;harshly 严厉地。",
     "forms":[F("harshly","adv.","严厉地"),F("harshness","n.","严厉")]}},
  {"word":"ethical","phonetic":"ˈeθɪkl","pos":"adj.","def":"伦理的，道德的；合乎道德的","cefr":"B2","freq_rank":64,
   "sentence_en":"It raises ethical questions.","sentence_zh":"这引发了伦理问题。",
   "aids":{"morphemes":[M("eth","root","品性，习俗(ethos)"),M("ical","suffix","…的")],
     "derivation":"eth(品性)+ical → 关乎品行准则的 → 伦理的",
     "family":FAM("eth","品性、习俗",[W("ethics","伦理学"),W("ethos","精神特质")]),
     "mnemonic":"eth=品性(想 ethos 风气);关乎道德准则、合乎道义的,就是 ethical;ethics 伦理学;反义 unethical 不道德的。",
     "forms":[F("ethics","n.","伦理学"),F("ethically","adv.","道德上")]}},
  {"word":"classical","phonetic":"ˈklæsɪkl","pos":"adj.","def":"古典的；经典的","cefr":"B1","freq_rank":76,
   "sentence_en":"She enjoys classical music.","sentence_zh":"她喜欢古典音乐。",
   "aids":{"morphemes":[M("class","root","等级，班"),M("ical","suffix","…的")],
     "derivation":"class(第一等)→ 属于第一流传统的 → 古典的、经典的",
     "family":FAM("class","等级、班",[W("class","班级；等级"),W("classic","经典的"),W("classify","分类")]),
     "mnemonic":"class=第一等(想 first class);属于希腊罗马经典传统或最高水准的,就是 classical 古典的;classical music 古典乐。",
     "forms":[F("classic","adj./n.","经典的；经典作品")]}},
  {"word":"occasional","phonetic":"əˈkeɪʒənl","pos":"adj.","def":"偶尔的，间或的","cefr":"B1","freq_rank":88,
   "sentence_en":"We have occasional visitors.","sentence_zh":"我们偶尔有访客。",
   "aids":{"morphemes":[M("occasion","root","场合，时机"),M("al","suffix","…的")],
     "derivation":"occasion(时机)+al → 只在个别时机发生的 → 偶尔的",
     "family":FAM("cas/cid","落、降",[W("occasion","场合"),W("accident","事故"),W("incident","事件")]),
     "mnemonic":"和 occasion(时机)一家;只在个别场合、时有时无的,就是 occasional;occasionally 偶尔;反义 frequent 频繁的。",
     "forms":[F("occasionally","adv.","偶尔")]}},
  {"word":"greatly","phonetic":"ˈɡreɪtli","pos":"adv.","def":"非常，极大地","cefr":"B1","freq_rank":60,
   "sentence_en":"I greatly appreciate your help.","sentence_zh":"我非常感谢你的帮助。",
   "aids":{"morphemes":[M("great","root","大的，很"),M("ly","suffix","…地")],
     "derivation":"great(大)+ly → 大大地 → 极大地",
     "family":FAM("great","大",[W("great","伟大的"),W("greatness","伟大")]),
     "mnemonic":"great=大;程度上大大地、非常,就是 greatly(greatly improved 大为改善);多修饰动词/过去分词。",
     "forms":[F("great","adj.","伟大的")]}},
  # 常见实义词
  {"word":"blanket","phonetic":"ˈblæŋkɪt","pos":"n./v./adj.","def":"毛毯；覆盖层；覆盖；总括的","cefr":"B1","freq_rank":49,
   "sentence_en":"Snow covered the ground like a blanket.","sentence_zh":"雪像毯子一样覆盖了地面。",
   "aids":{"morphemes":[M("blank","root","白色(blanc)"),M("et","suffix","小")],
     "derivation":"源自'白色织物(未染色羊毛毯)';盖身的织物 → 毛毯;像毯子般覆盖 → 覆盖",
     "family":FAM("blanc/blank","白",[W("blank","空白的"),W("blanch","漂白")]),
     "mnemonic":"blank=白(原指未染色白毛毯);盖身取暖的=毛毯;一层覆盖物(a blanket of snow);一刀切的=blanket ban 全面禁令。",
     "forms":[F("blankets","n.","毛毯(复数)")]}},
  {"word":"corridor","phonetic":"ˈkɒrɪdɔː","pos":"n.","def":"走廊，通道","cefr":"B1","freq_rank":72,
   "sentence_en":"Her office is at the end of the corridor.","sentence_zh":"她的办公室在走廊尽头。",
   "aids":{"morphemes":[M("cor","root","跑(curr)"),M("ridor","suffix","名词后缀")],
     "derivation":"与 curr'跑'同源(可供奔走的通道);→ 走廊",
     "family":FAM("curr/cor","跑",[W("current","当前的"),W("occur","发生"),W("courier","信使")]),
     "mnemonic":"cor=跑(和 current 一家);可供来回奔走的长通道,就是 corridor 走廊;经济/交通'走廊'也是 corridor。",
     "forms":[F("corridors","n.","走廊(复数)")]}},
  {"word":"suburb","phonetic":"ˈsʌbɜːb","pos":"n.","def":"郊区，近郊","cefr":"B1","freq_rank":95,
   "sentence_en":"They live in the suburbs.","sentence_zh":"他们住在郊区。",
   "aids":{"morphemes":[M("sub","prefix","在下，靠近"),M("urb","root","城市")],
     "derivation":"sub(靠近)+urb(城市) → 紧挨城市外围的 → 郊区",
     "family":FAM("urb","城市",[W("urban","城市的"),W("urbanize","城市化")]),
     "mnemonic":"urb=城市(和 urban 一家);紧贴城市(sub-)外缘的居住区,就是 suburb 郊区;suburban 郊区的。",
     "forms":[F("suburban","adj.","郊区的"),F("suburbs","n.","郊区(复数)")]}},
  {"word":"mainstream","phonetic":"ˈmeɪnstriːm","pos":"n./adj.","def":"主流(的)","cefr":"B2","freq_rank":94,
   "sentence_en":"The idea has entered the mainstream.","sentence_zh":"这个观念已进入主流。",
   "aids":{"morphemes":[M("main","root","主要的"),M("stream","root","流")],
     "derivation":"main(主)+stream(流) → 主要的水流/潮流 → 主流",
     "family":FAM("stream","流",[W("stream","水流"),W("upstream","上游")]),
     "mnemonic":"main(主)+stream(流)——占主导的思潮/趋势,就是 mainstream 主流;mainstream media 主流媒体;反义 fringe 边缘。",
     "forms":[]}},
  {"word":"logic","phonetic":"ˈlɒdʒɪk","pos":"n.","def":"逻辑，逻辑学；条理","cefr":"B1","freq_rank":70,
   "sentence_en":"There's no logic in his argument.","sentence_zh":"他的论证毫无逻辑。",
   "aids":{"morphemes":[M("log","root","说，理，学问"),M("ic","suffix","…学")],
     "derivation":"log(理、话语)+ic → 推理的学问 → 逻辑",
     "family":FAM("log","说、理、学问",[W("logical","合逻辑的"),W("biology","生物学"),W("dialogue","对话")]),
     "mnemonic":"log=理/说(和 -logy 学问一家);推理的规则与条理,就是 logic;logical 合逻辑的;logically 逻辑上。",
     "forms":[F("logical","adj.","合逻辑的")]}},
  {"word":"melt","phonetic":"melt","pos":"v.","def":"融化，熔化；(心)软化","cefr":"B1","freq_rank":67,
   "sentence_en":"The ice is melting.","sentence_zh":"冰在融化。",
   "aids":{"morphemes":[M("melt","root","融化(古英语 meltan)")],
     "derivation":"古英语'使成液态';受热化为液体 → 融化",
     "family":FAM("","相关词",[W("molten","熔化的")]),
     "mnemonic":"melt=融化;冰雪/金属受热化开=melt;比喻心肠'软化'=melt(her heart melted);melt away 渐渐消失;molten 熔融的。",
     "forms":[F("melted","v.","过去式/过去分词"),F("molten","adj.","熔化的")]}},
  {"word":"acid","phonetic":"ˈæsɪd","pos":"n./adj.","def":"酸；酸的，酸性的；尖刻的","cefr":"B1","freq_rank":45,
   "sentence_en":"Lemon juice is acidic.","sentence_zh":"柠檬汁是酸性的。",
   "aids":{"morphemes":[M("acid","root","酸，尖(acidus)")],
     "derivation":"拉丁 acidus'酸的、尖的';酸味物质 → 酸;言辞'尖酸'→ 尖刻的",
     "family":FAM("ac/acu","尖、酸",[W("acute","尖锐的"),W("acid rain","酸雨")]),
     "mnemonic":"acid=酸/尖(和 acute 尖锐一家);pH<7 的物质=酸;言辞尖酸=acid remarks;acid rain 酸雨;acidic 酸性的。",
     "forms":[F("acidic","adj.","酸性的")]}},
  {"word":"slope","phonetic":"sləʊp","pos":"n./v.","def":"斜坡，坡度；倾斜","cefr":"B1","freq_rank":58,
   "sentence_en":"We climbed the steep slope.","sentence_zh":"我们爬上了陡坡。",
   "aids":{"morphemes":[M("slope","root","斜(古英语 aslope)")],
     "derivation":"古英语'倾斜';倾斜的地面 → 斜坡",
     "family":FAM("","相关词",[W("sloping","倾斜的")]),
     "mnemonic":"slope=斜坡;倾斜的地面/坡度=slope(ski slope 滑雪坡);表面倾斜=slope;a slippery slope 越陷越深的下坡路。",
     "forms":[F("sloping","adj.","倾斜的"),F("slopes","n.","斜坡(复数)")]}},
  {"word":"trap","phonetic":"træp","pos":"n./v.","def":"陷阱，圈套；困住，使陷入","cefr":"B1","freq_rank":100,
   "sentence_en":"They were trapped in the building.","sentence_zh":"他们被困在了大楼里。",
   "aids":{"morphemes":[M("trap","root","陷阱(古英语 træppe)")],
     "derivation":"古英语'捕兽器';使落入的装置 → 陷阱;使无法脱身 → 困住",
     "family":FAM("","相关词",[W("entrap","诱陷")]),
     "mnemonic":"trap=陷阱;捕猎的机关/圈套=trap;人被'关'住出不来=be trapped;掉入陷阱=fall into a trap;tourist trap 宰客地。",
     "forms":[F("trapped","v.","过去式/过去分词"),F("traps","n.","陷阱(复数)")]}},
  {"word":"dose","phonetic":"dəʊs","pos":"n./v.","def":"(一次)剂量，一剂；给药","cefr":"B2","freq_rank":91,
   "sentence_en":"Take one dose twice a day.","sentence_zh":"每天服用两次，每次一剂。",
   "aids":{"morphemes":[M("dos","root","给(希腊 dosis 给予)"),M("e","suffix","结尾")],
     "derivation":"希腊 dosis'给予的量';一次给的药量 → 剂量",
     "family":FAM("do/don","给",[W("donate","捐赠"),W("dose","剂量")]),
     "mnemonic":"dos=给(想 donate 给);一次给用的药量,就是 dose 剂量;overdose 过量(用药);a dose of=一剂/一点(a dose of reality)。",
     "forms":[F("doses","n.","剂量(复数)"),F("overdose","n.","过量")]}},
  {"word":"swear","phonetic":"sweə","pos":"v.","def":"发誓，宣誓；咒骂，说脏话","cefr":"B1","freq_rank":51,
   "sentence_en":"I swear I'm telling the truth.","sentence_zh":"我发誓我说的是真话。",
   "aids":{"morphemes":[M("swear","root","发誓(古英语 swerian)")],
     "derivation":"古英语'郑重声明';郑重起誓 → 发誓;不雅的'赌咒'→ 骂人",
     "family":FAM("","相关词",[W("swearword","脏话")]),
     "mnemonic":"swear=发誓(过去式 swore,过去分词 sworn);郑重起誓=swear;骂脏话=swear(swear at sb);swear by 极其信赖。",
     "forms":[F("swore","v.","过去式"),F("sworn","v.","过去分词")]}},
  {"word":"slice","phonetic":"slaɪs","pos":"n./v.","def":"薄片，一份；切(片)","cefr":"B1","freq_rank":52,
   "sentence_en":"Cut the bread into slices.","sentence_zh":"把面包切成片。",
   "aids":{"morphemes":[M("slice","root","切片(古法语 esclice 碎片)")],
     "derivation":"古法语'劈下的碎片';薄薄切下的一片 → 薄片",
     "family":FAM("","相关词",[W("slicer","切片机")]),
     "mnemonic":"slice=薄片;切下的一片面包/蛋糕=a slice of;引申'一份'(a slice of the profits 一份利润);把…切片=slice。",
     "forms":[F("sliced","v.","过去式/过去分词"),F("slices","n.","薄片(复数)")]}},
  {"word":"fold","phonetic":"fəʊld","pos":"v./n.","def":"折叠；交叉(手臂)；(企业)倒闭；褶","cefr":"B1","freq_rank":78,
   "sentence_en":"Fold the paper in half.","sentence_zh":"把纸对折。",
   "aids":{"morphemes":[M("fold","root","折(古英语 fealdan)")],
     "derivation":"古英语'折叠';弯折使重合 → 折叠",
     "family":FAM("fold","折、倍",[W("unfold","展开"),W("manifold","多种的")]),
     "mnemonic":"fold=折;把纸/衣折起=fold;两臂交叉=fold one's arms;生意撑不住'收摊'=fold;-fold 表'…倍'(tenfold 十倍)。",
     "forms":[F("folded","v.","过去式/过去分词"),F("unfold","v.","展开")]}},
  {"word":"trunk","phonetic":"trʌŋk","pos":"n.","def":"树干；躯干；(汽车)后备箱；大衣箱；象鼻","cefr":"B2","freq_rank":96,
   "sentence_en":"The elephant lifted its trunk.","sentence_zh":"大象抬起了鼻子。",
   "aids":{"morphemes":[M("trunk","root","主干(truncus)")],
     "derivation":"拉丁 truncus'树干、躯干';主体部分 → 树干、躯干",
     "family":FAM("trunc","截、干",[W("truncate","截断")]),
     "mnemonic":"trunk=主干;树的主干=trunk;人的躯干;车后'大箱'=后备箱(美式);出行大衣箱;大象的长'鼻'也叫 trunk。",
     "forms":[F("trunks","n.","树干(复数)")]}},
  {"word":"whisper","phonetic":"ˈwɪspə","pos":"v./n.","def":"耳语，低声说；私语","cefr":"B1","freq_rank":16,
   "sentence_en":"She whispered a secret to me.","sentence_zh":"她对我耳语了一个秘密。",
   "aids":{"morphemes":[M("whisper","root","低语(古英语 hwisprian 拟声)")],
     "derivation":"拟声词'嘶嘶低语';压低嗓子说 → 耳语",
     "family":FAM("","相关词",[W("whispering","耳语")]),
     "mnemonic":"whisper 拟声——嘶嘶轻声;压低声音贴耳说=whisper 耳语;in a whisper 低声地;和 shout(喊)相对。",
     "forms":[F("whispered","v.","过去式/过去分词")]}},
  {"word":"swing","phonetic":"swɪŋ","pos":"v./n.","def":"摇摆，摆动；秋千；(意见)转变","cefr":"B1","freq_rank":17,
   "sentence_en":"The children were swinging in the park.","sentence_zh":"孩子们在公园里荡秋千。",
   "aids":{"morphemes":[M("swing","root","摆动(古英语 swingan)")],
     "derivation":"古英语'挥动、摆动';来回摆 → 摇摆",
     "family":FAM("","相关词",[W("swung","摆动(过去式)")]),
     "mnemonic":"swing=摆动(过去式 swung);来回荡=swing;公园的秋千=a swing;情绪/立场大'摆动'=mood swings;in full swing 全力进行中。",
     "forms":[F("swung","v.","过去式/过去分词"),F("swings","n.","秋千(复数)")]}},
  {"word":"wander","phonetic":"ˈwɒndə","pos":"v.","def":"漫游，闲逛；走神，离题","cefr":"B1","freq_rank":42,
   "sentence_en":"They wandered around the old town.","sentence_zh":"他们在古镇里闲逛。",
   "aids":{"morphemes":[M("wand","root","转，走(wend)"),M("er","suffix","反复")],
     "derivation":"与 wend'走'同源;无目的地走 → 漫游",
     "family":FAM("wand/wend","走、转",[W("wend","前往")]),
     "mnemonic":"wander=漫无目的地走(注意与 wonder 想知道 区分);闲逛=wander;思绪飘走/离题=my mind wandered;wanderer 漫游者。",
     "forms":[F("wandered","v.","过去式/过去分词"),F("wandering","adj.","漫游的")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 22
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
