#!/usr/bin/env python
# 第四批词:约62个高频词,逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -fect/-fac/-fic 家族(做、造)
  {"word":"affect","phonetic":"əˈfekt","pos":"v.","def":"影响；(疾病)侵袭","cefr":"B1","freq_rank":700,
   "sentence_en":"The weather affects my mood.","sentence_zh":"天气会影响我的心情。",
   "aids":{"morphemes":[M("af","prefix","朝向(ad 变体)"),M("fect","root","做")],
     "derivation":"af(朝向)+fect(做) → 对某物起作用 → 影响",
     "family":FAM("fect/fac","做、造",[W("effect","效果"),W("perfect","完美的"),W("factory","工厂"),W("manufacture","制造")]),
     "mnemonic":"fect=做;朝(af-)某人某物施加作用,就是 affect 影响(动词);注意与名词 effect 效果区分:a=作用,e=结果。",
     "forms":[F("affected","adj.","受影响的"),F("affection","n.","喜爱")]}},
  {"word":"perform","phonetic":"pəˈfɔːm","pos":"v.","def":"执行，履行；表演","cefr":"B1","freq_rank":702,
   "sentence_en":"The band performed live last night.","sentence_zh":"乐队昨晚现场演出。",
   "aids":{"morphemes":[M("per","prefix","彻底"),M("form","root","做，形式")],
     "derivation":"per(彻底)+form(做) → 彻底做出来 → 执行、表演",
     "family":FAM("form","做、形式",[W("performance","表现"),W("reform","改革"),W("transform","改变")]),
     "mnemonic":"per-(彻底)+form(做)——把事情彻底做完、演出来,就是 perform 执行、表演。",
     "forms":[F("performance","n.","表演；表现"),F("performer","n.","表演者")]}},
  # -ceive/-cept 家族(拿、取)
  {"word":"concept","phonetic":"ˈkɒnsept","pos":"n.","def":"概念，观念","cefr":"B2","freq_rank":83,
   "sentence_en":"The concept of time is hard to define.","sentence_zh":"时间的概念很难定义。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("cept","root","拿，取")],
     "derivation":"con(一起)+cept(拿) → 在心里把想法聚拢抓住 → 概念",
     "family":FAM("cept/ceive","拿、取",[W("accept","接受"),W("receive","收到"),W("except","除外"),W("perceive","察觉")]),
     "mnemonic":"cept=拿(想 accept 接受);把种种想法一起(con-)抓在脑中形成的东西,就是 concept 概念。",
     "forms":[F("conceptual","adj.","概念的")]}},
  {"word":"access","phonetic":"ˈækses","pos":"n./v.","def":"通道，使用权；访问","cefr":"B2","freq_rank":767,
   "sentence_en":"Students have free access to the library.","sentence_zh":"学生可免费使用图书馆。",
   "aids":{"morphemes":[M("ac","prefix","朝向(ad 变体)"),M("cess","root","走，行进")],
     "derivation":"ac(朝向)+cess(走) → 能走近、进入 → 通道、使用权",
     "family":FAM("cess/ceed","走、行进",[W("process","过程"),W("proceed","前进"),W("success","成功"),W("exceed","超过")]),
     "mnemonic":"cess=走(想 process);能朝(ac-)某处走进去,就是 access 通道、访问权。",
     "forms":[F("accessible","adj.","可进入的"),F("accessed","v.","过去式/过去分词")]}},
  # -ject 家族扩展
  {"word":"object","phonetic":"ˈɒbdʒekt","pos":"n./v.","def":"物体，目标；反对","cefr":"B1","freq_rank":797,
   "sentence_en":"She objected to the new rule.","sentence_zh":"她反对这条新规定。",
   "aids":{"morphemes":[M("ob","prefix","对着"),M("ject","root","扔，投")],
     "derivation":"ob(对着)+ject(扔) → 扔在你面前的东西=物体;把话扔到对面 → 反对",
     "family":FAM("ject","扔、投",[W("project","项目"),W("reject","拒绝"),W("inject","注射"),W("subject","主题")]),
     "mnemonic":"ject=扔;扔在眼前挡着的东西=object 物体;把异议扔到对面(ob-)=object 反对。",
     "forms":[F("objection","n.","反对"),F("objective","n.","目标；adj.客观的")]}},
  # -press 家族扩展
  {"word":"express","phonetic":"ɪkˈspres","pos":"v./adj.","def":"表达；快速的，特快的","cefr":"B1","freq_rank":900,
   "sentence_en":"It's hard to express my feelings in words.","sentence_zh":"我很难用言语表达感受。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("press","root","压")],
     "derivation":"ex(向外)+press(压) → 把内心的东西压挤出来 → 表达",
     "family":FAM("press","压",[W("pressure","压力"),W("impress","使印象深刻"),W("compress","压缩"),W("depress","使沮丧")]),
     "mnemonic":"press=压;把心里的想法向外(ex-)压出来,就是 express 表达;引申'一压到底、直达'=特快(express train)。",
     "forms":[F("expression","n.","表达；表情"),F("expressive","adj.","富有表现力的")]}},
  # -ply/-plic 家族(折叠、重叠)
  {"word":"apply","phonetic":"əˈplaɪ","pos":"v.","def":"申请；应用；涂","cefr":"A2","freq_rank":816,
   "sentence_en":"I want to apply for this job.","sentence_zh":"我想申请这份工作。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("ply","root","折叠，贴")],
     "derivation":"ap(朝向)+ply(贴) → 把自己贴上去、投上去 → 申请;把A贴到B上 → 应用、涂",
     "family":FAM("ply/plic","折叠、贴",[W("reply","回复"),W("imply","暗示"),W("complicated","复杂的"),W("multiply","乘；繁殖")]),
     "mnemonic":"ply=折叠/贴(想 reply);把申请贴(ap-)上去=apply 申请;把规则贴到情况上=应用;把药贴上=涂。",
     "forms":[F("application","n.","申请；应用"),F("applicant","n.","申请人")]}},
  {"word":"replace","phonetic":"rɪˈpleɪs","pos":"v.","def":"取代，替换；放回","cefr":"B1","freq_rank":92,
   "sentence_en":"We need to replace the old computer.","sentence_zh":"我们需要更换旧电脑。",
   "aids":{"morphemes":[M("re","prefix","再，回"),M("place","root","放置，地方")],
     "derivation":"re(再)+place(放) → 放上另一个/放回原处 → 替换、放回",
     "family":FAM("plac/place","放置",[W("place","放；地方"),W("placement","安置"),W("displace","取代，置换")]),
     "mnemonic":"re-(再)+place(放)——在原位再放一个新的,就是 replace 取代、替换。",
     "forms":[F("replacement","n.","替换；替代品")]}},
  # -mit 家族扩展
  {"word":"admit","phonetic":"ədˈmɪt","pos":"v.","def":"承认；准许进入","cefr":"B1","freq_rank":816,
   "sentence_en":"He admitted his mistake.","sentence_zh":"他承认了自己的错误。",
   "aids":{"morphemes":[M("ad","prefix","朝向，进入"),M("mit","root","送，放")],
     "derivation":"ad(进入)+mit(放) → 放…进来 → 准许进入;放开心防 → 承认",
     "family":FAM("mit/miss","送、放",[W("submit","提交"),W("commit","投入"),W("permit","允许"),W("transmit","传送")]),
     "mnemonic":"mit=放;放某人进(ad-)门=admit 准入;放下心防承认错=admit 承认。",
     "forms":[F("admission","n.","承认；准入"),F("admitted","v.","过去式/过去分词")]}},
  # -fer 家族(带、拿)
  {"word":"refer","phonetic":"rɪˈfɜː","pos":"v.","def":"提及，涉及；参考；转介","cefr":"B1","freq_rank":81,
   "sentence_en":"The report refers to several studies.","sentence_zh":"报告提到了几项研究。",
   "aids":{"morphemes":[M("re","prefix","回，向"),M("fer","root","带，拿")],
     "derivation":"re(向)+fer(带) → 把话/注意力带向某处 → 提及、参考",
     "family":FAM("fer","带、拿",[W("offer","提供"),W("transfer","转移"),W("prefer","更喜欢"),W("differ","不同")]),
     "mnemonic":"fer=带(想 transfer 转移);把话头带(re-)向某物,就是 refer to 提及、参考。",
     "forms":[F("reference","n.","提及；参考"),F("referred","v.","过去式/过去分词")]}},
  {"word":"suffer","phonetic":"ˈsʌfə","pos":"v.","def":"遭受，忍受；受苦","cefr":"B1","freq_rank":815,
   "sentence_en":"Many people suffer from stress.","sentence_zh":"许多人饱受压力之苦。",
   "aids":{"morphemes":[M("suf","prefix","在下(sub 变体)"),M("fer","root","带，承受")],
     "derivation":"suf(在下)+fer(承受) → 在下面扛着、承受 → 遭受、受苦",
     "family":FAM("fer","带、承受",[W("offer","提供"),W("refer","提及"),W("transfer","转移")]),
     "mnemonic":"fer=承受;在重压之下(suf-)一直扛着,就是 suffer 遭受、受苦;suffer from=患有、饱受。",
     "forms":[F("suffering","n.","痛苦"),F("suffered","v.","过去式/过去分词")]}},
  # -sist/-sta 稳
  {"word":"assume","phonetic":"əˈsjuːm","pos":"v.","def":"假定，认为；承担；呈现","cefr":"B2","freq_rank":817,
   "sentence_en":"I assume you have read the book.","sentence_zh":"我认为你已经读过这本书了。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sume","root","拿，取")],
     "derivation":"as(朝向)+sume(拿) → 先拿来当作前提 → 假定;拿过来 → 承担",
     "family":FAM("sume/sum","拿、取",[W("consume","消耗"),W("resume","恢复；简历"),W("presume","假定")]),
     "mnemonic":"sume=拿(想 consume 消耗);不加验证先拿来当真=assume 假定;把责任拿过来=承担。",
     "forms":[F("assumption","n.","假定，设想")]}},
  {"word":"consumer","phonetic":"kənˈsjuːmə","pos":"n.","def":"消费者，用户","cefr":"B1","freq_rank":50,
   "sentence_en":"Consumers want better prices.","sentence_zh":"消费者希望价格更优惠。",
   "aids":{"morphemes":[M("con","prefix","完全"),M("sume","root","拿，用"),M("er","suffix","…的人")],
     "derivation":"con(完全)+sume(用) → 把东西买来用掉的人 → 消费者",
     "family":FAM("sume/sum","拿、用",[W("consume","消耗"),W("assume","假定"),W("resume","恢复")]),
     "mnemonic":"con-(完全)+sume(用光)+er(人)——把商品买来用掉的人,就是 consumer 消费者;动词 consume。",
     "forms":[F("consume","v.","消耗，消费"),F("consumption","n.","消费；消耗")]}},
  # -tend 家族(伸)扩展
  {"word":"tend","phonetic":"tend","pos":"v.","def":"倾向于；照料","cefr":"B1","freq_rank":846,
   "sentence_en":"People tend to eat more in winter.","sentence_zh":"人们冬天往往吃得更多。",
   "aids":{"morphemes":[M("tend","root","伸展")],
     "derivation":"tend(伸) → 心朝某方向伸 → 倾向;把心伸向某物照看 → 照料",
     "family":FAM("tend/tens","伸展",[W("extend","延伸"),W("intend","打算"),W("attend","出席"),W("tension","紧张")]),
     "mnemonic":"tend=伸;心思总朝一个方向伸过去,就是 tend to 倾向于;把关注伸向某物=照料。",
     "forms":[F("tendency","n.","倾向"),F("tended","v.","过去式/过去分词")]}},
  {"word":"attend","phonetic":"əˈtend","pos":"v.","def":"出席，参加；照料","cefr":"B1","freq_rank":88,
   "sentence_en":"Over 200 people attended the meeting.","sentence_zh":"两百多人出席了会议。",
   "aids":{"morphemes":[M("at","prefix","朝向(ad 变体)"),M("tend","root","伸展")],
     "derivation":"at(朝向)+tend(伸) → 把身心朝某处伸去 → 出席、专心照料",
     "family":FAM("tend/tens","伸展",[W("tend","倾向"),W("extend","延伸"),W("intend","打算"),W("attention","注意")]),
     "mnemonic":"tend=伸;把人朝(at-)现场伸过去=attend 出席;把心思伸向某人=照料。",
     "forms":[F("attendance","n.","出席(人数)"),F("attendant","n.","服务员")]}},
  {"word":"intend","phonetic":"ɪnˈtend","pos":"v.","def":"打算，意图","cefr":"B1","freq_rank":1100,
   "sentence_en":"I intend to travel next year.","sentence_zh":"我打算明年去旅行。",
   "aids":{"morphemes":[M("in","prefix","向内，朝"),M("tend","root","伸展")],
     "derivation":"in(朝)+tend(伸) → 心朝目标伸过去 → 打算、意图",
     "family":FAM("tend/tens","伸展",[W("tend","倾向"),W("attend","出席"),W("extend","延伸"),W("intense","强烈的")]),
     "mnemonic":"tend=伸;把心意朝(in-)某目标伸出去,就是 intend 打算;名词 intention 意图。",
     "forms":[F("intention","n.","意图，打算"),F("intended","adj.","预期的")]}},
  # -serve 家族
  {"word":"observe","phonetic":"əbˈzɜːv","pos":"v.","def":"观察；遵守；评论","cefr":"B1","freq_rank":125,
   "sentence_en":"Scientists observe the stars.","sentence_zh":"科学家观察星星。",
   "aids":{"morphemes":[M("ob","prefix","对着，加强"),M("serve","root","看守，保持")],
     "derivation":"ob(对着)+serve(看守) → 对着仔细看守 → 观察;守着规矩 → 遵守",
     "family":FAM("serve","看守、保持",[W("serve","服务"),W("preserve","保存"),W("reserve","保留"),W("conserve","节约")]),
     "mnemonic":"serve=看守(不只是'服务');对着(ob-)一样东西盯着看=observe 观察;守着规则=遵守。",
     "forms":[F("observation","n.","观察"),F("observer","n.","观察者")]}},
  # 高频学术名词/形容词
  {"word":"potential","phonetic":"pəˈtenʃəl","pos":"n./adj.","def":"潜力；潜在的，可能的","cefr":"B2","freq_rank":114,
   "sentence_en":"She has great potential as an artist.","sentence_zh":"她有成为艺术家的巨大潜力。",
   "aids":{"morphemes":[M("pot","root","有力，能"),M("ent","suffix","…的"),M("ial","suffix","…的")],
     "derivation":"pot(能)+ential → 有能力但尚未发挥的 → 潜在的、潜力",
     "family":FAM("pot","有力、能",[W("potent","强有力的"),W("power","力量"),W("possible","可能的")]),
     "mnemonic":"pot=能(想 potent 强效的、power 力量);藏着还没使出来的能量,就是 potential 潜力、潜在的。",
     "forms":[F("potentially","adv.","潜在地，可能地")]}},
  {"word":"independent","phonetic":"ˌɪndɪˈpendənt","pos":"adj.","def":"独立的，自主的","cefr":"B1","freq_rank":116,
   "sentence_en":"She is financially independent.","sentence_zh":"她在经济上独立。",
   "aids":{"morphemes":[M("in","prefix","不"),M("de","prefix","向下"),M("pend","root","悬挂"),M("ent","suffix","…的")],
     "derivation":"in(不)+depend(依赖) → 不依赖别人 → 独立的",
     "family":FAM("pend/pens","悬挂",[W("depend","依赖"),W("suspend","悬挂；暂停"),W("pending","待定的")]),
     "mnemonic":"pend=挂(想 depend 挂靠着依赖);in-(不)去挂靠别人,就是 independent 独立的;反义 dependent。",
     "forms":[F("independence","n.","独立"),F("independently","adv.","独立地")]}},
  {"word":"previous","phonetic":"ˈpriːviəs","pos":"adj.","def":"以前的，先前的","cefr":"B1","freq_rank":120,
   "sentence_en":"In the previous chapter, we discussed grammar.","sentence_zh":"在前一章，我们讨论了语法。",
   "aids":{"morphemes":[M("pre","prefix","在前"),M("vi","root","路，走"),M("ous","suffix","…的")],
     "derivation":"pre(在前)+vi(路) → 走在前面的 → 先前的",
     "family":FAM("vi/via","路、走",[W("via","经由"),W("obvious","明显的"),W("previous","先前的")]),
     "mnemonic":"pre-(前)+vi(路)——在这条路之前那一段,就是 previous 以前的;反义 next/following。",
     "forms":[F("previously","adv.","以前，先前")]}},
  {"word":"original","phonetic":"əˈrɪdʒənl","pos":"adj./n.","def":"最初的；原创的；原件","cefr":"B1","freq_rank":74,
   "sentence_en":"This is the original version.","sentence_zh":"这是最初的版本。",
   "aids":{"morphemes":[M("origin","root","起源"),M("al","suffix","…的")],
     "derivation":"origin(起源)+al → 与起源有关的 → 最初的、原创的",
     "family":FAM("ori","升起、起源",[W("origin","起源"),W("originate","起源于"),W("orient","东方；定向")]),
     "mnemonic":"origin=起源;处于最开头、别人没做过的,就是 original 最初的、原创的。",
     "forms":[F("origin","n.","起源"),F("originally","adv.","起初，原来")]}},
  {"word":"effective","phonetic":"ɪˈfektɪv","pos":"adj.","def":"有效的，起作用的","cefr":"B1","freq_rank":73,
   "sentence_en":"This is an effective way to learn.","sentence_zh":"这是一种有效的学习方法。",
   "aids":{"morphemes":[M("ef","prefix","向外(ex 变体)"),M("fect","root","做"),M("ive","suffix","…的")],
     "derivation":"ef(向外)+fect(做) → 能做出效果来的 → 有效的",
     "family":FAM("fect/fac","做、造",[W("effect","效果"),W("affect","影响"),W("perfect","完美的")]),
     "mnemonic":"fect=做;能做出实际效果(effect)的,就是 effective 有效的;副词 effectively。",
     "forms":[F("effectively","adv.","有效地；实际上"),F("effectiveness","n.","有效性")]}},
  {"word":"positive","phonetic":"ˈpɒzətɪv","pos":"adj.","def":"积极的；肯定的；正的","cefr":"B1","freq_rank":48,
   "sentence_en":"Try to keep a positive attitude.","sentence_zh":"尽量保持积极的态度。",
   "aids":{"morphemes":[M("pos","root","放，确定"),M("itive","suffix","…的")],
     "derivation":"pos(确定地放下)+itive → 明确设定、肯定的 → 积极的、正的",
     "family":FAM("pos/pon","放置",[W("position","位置"),W("compose","组成"),W("impose","强加"),W("expose","暴露")]),
     "mnemonic":"pos=放定;把话说死、明确肯定=positive 肯定的;心态'正向设定'=积极的;数轴正方向=正的。",
     "forms":[F("positively","adv.","积极地；肯定地")]}},
  {"word":"critical","phonetic":"ˈkrɪtɪkəl","pos":"adj.","def":"批判的；关键的；危急的","cefr":"B2","freq_rank":70,
   "sentence_en":"The next few days are critical.","sentence_zh":"接下来几天至关重要。",
   "aids":{"morphemes":[M("crit","root","判断，分辨"),M("ical","suffix","…的")],
     "derivation":"crit(判断)+ical → 善于判断挑剔的 → 批判的;到了要判定的关口 → 关键的、危急的",
     "family":FAM("crit/cris","判断、分辨",[W("criticize","批评"),W("crisis","危机"),W("criterion","标准")]),
     "mnemonic":"crit=判断(想 criticize 批评、crisis 危机);爱挑剔评判=批判的;判定成败的紧要关头=关键的、危急的。",
     "forms":[F("critically","adv.","批判地；危急地"),F("criticism","n.","批评")]}},
  {"word":"specific","phonetic":"spəˈsɪfɪk","pos":"adj.","def":"具体的，明确的；特定的","cefr":"B1","freq_rank":27,
   "sentence_en":"Can you be more specific?","sentence_zh":"你能说得更具体些吗？",
   "aids":{"morphemes":[M("spec","root","看，种类"),M("ific","suffix","…的")],
     "derivation":"spec(看/种类)+ific → 能一眼分辨出的某一种 → 特定的、具体的",
     "family":FAM("spec","看、种类",[W("species","物种"),W("special","特别的"),W("inspect","检查"),W("aspect","方面")]),
     "mnemonic":"spec=看/种类(想 species 物种);明确指定的某一种、看得清清楚楚的,就是 specific 具体的、特定的。",
     "forms":[F("specifically","adv.","specifically 明确地"),F("specify","v.","具体说明")]}},
  {"word":"various","phonetic":"ˈveəriəs","pos":"adj.","def":"各种各样的","cefr":"B1","freq_rank":85,
   "sentence_en":"They discussed various options.","sentence_zh":"他们讨论了各种选择。",
   "aids":{"morphemes":[M("vari","root","变化"),M("ous","suffix","…的")],
     "derivation":"vari(变化)+ous → 多变多样的 → 各种各样的",
     "family":FAM("vari","变化",[W("vary","变化"),W("variety","多样"),W("variable","可变的")]),
     "mnemonic":"vari=变;花样繁多各不相同,就是 various。","forms":[F("variety","n.","多样性")]}},
  {"word":"global","phonetic":"ˈɡləʊbl","pos":"adj.","def":"全球的；全面的","cefr":"B1","freq_rank":66,
   "sentence_en":"Climate change is a global problem.","sentence_zh":"气候变化是全球性问题。",
   "aids":{"morphemes":[M("glob","root","球，团"),M("al","suffix","…的")],
     "derivation":"glob(球)+al → 涉及整个地球的 → 全球的",
     "family":FAM("glob","球、团",[W("globe","地球仪"),W("global","全球的")]),
     "mnemonic":"glob=球(想 globe 地球仪);覆盖整个地球那么大范围的,就是 global 全球的。",
     "forms":[F("globally","adv.","全球地"),F("globe","n.","地球；球体")]}},
  {"word":"normal","phonetic":"ˈnɔːml","pos":"adj./n.","def":"正常的，标准的","cefr":"A2","freq_rank":102,
   "sentence_en":"His temperature is back to normal.","sentence_zh":"他的体温恢复正常了。",
   "aids":{"morphemes":[M("norm","root","规范，标准"),M("al","suffix","…的")],
     "derivation":"norm(规范)+al → 合乎规范的 → 正常的",
     "family":FAM("norm","规范、标准",[W("norm","规范"),W("enormous","巨大的(超出规范)"),W("abnormal","反常的")]),
     "mnemonic":"norm=规范(木匠的角尺);合乎标准尺度的,就是 normal 正常的;超出规范 e-norm-ous=巨大;偏离规范 ab-normal=反常。",
     "forms":[F("normally","adv.","通常，正常地")]}},
  {"word":"complete","phonetic":"kəmˈpliːt","pos":"adj./v.","def":"完整的，完全的；完成","cefr":"A2","freq_rank":98,
   "sentence_en":"Please complete the form.","sentence_zh":"请填完这张表格。",
   "aids":{"morphemes":[M("com","prefix","完全"),M("plete","root","满，填(ple)")],
     "derivation":"com(完全)+plete(填满) → 完全填满 → 完整的、完成",
     "family":FAM("ple/plet","满、填",[W("complement","补充"),W("supplement","补充"),W("plenty","丰富"),W("accomplish","完成")]),
     "mnemonic":"plete=填满(想 plenty 充足);完全(com-)填满、无缺口,就是 complete 完整的、完成。",
     "forms":[F("completely","adv.","完全地"),F("completion","n.","完成")]}},
  {"word":"immediately","phonetic":"ɪˈmiːdiətli","pos":"adv.","def":"立即，马上；紧接地","cefr":"B1","freq_rank":76,
   "sentence_en":"Call me immediately if there is a problem.","sentence_zh":"有问题马上打电话给我。",
   "aids":{"morphemes":[M("im","prefix","不"),M("medi","root","中间"),M("ate","suffix","…的"),M("ly","suffix","地")],
     "derivation":"im(不)+medi(中间) → 中间不隔任何东西 → 立即、紧接",
     "family":FAM("medi","中间",[W("medium","媒介；中等"),W("middle","中间"),W("intermediate","中级的")]),
     "mnemonic":"medi=中间(想 medium 媒介);中间不夹一点缝隙、零延迟,就是 immediately 立即、紧接着。",
     "forms":[F("immediate","adj.","立即的；直接的")]}},
  {"word":"therefore","phonetic":"ˈðeəfɔː","pos":"adv.","def":"因此，所以","cefr":"B1","freq_rank":84,
   "sentence_en":"He was ill and therefore stayed home.","sentence_zh":"他病了，因此待在家里。",
   "aids":{"morphemes":[M("there","root","那，那里"),M("fore","root","为此，前")],
     "derivation":"there(那)+fore(为此) → 为那个缘故 → 因此",
     "family":FAM("","相关词",[W("thereby","因此，从而"),W("therein","在其中")]),
     "mnemonic":"字面'为那(there)个缘故(fore)';表示逻辑结论'所以',就是 therefore;写作论证高频衔接词。",
     "forms":[]}},
  {"word":"throughout","phonetic":"θruːˈaʊt","pos":"prep./adv.","def":"贯穿，遍及；自始至终","cefr":"B1","freq_rank":28,
   "sentence_en":"It rained throughout the night.","sentence_zh":"整夜都在下雨。",
   "aids":{"morphemes":[M("through","root","穿过"),M("out","root","完全，彻底")],
     "derivation":"through(穿过)+out(彻底) → 从头到尾彻底穿过 → 贯穿、遍及",
     "family":FAM("","相关词",[W("through","穿过"),W("throughput","吞吐量")]),
     "mnemonic":"through(穿过)+out(彻底)——从这头彻底贯到那头,就是 throughout 贯穿、自始至终。",
     "forms":[]}},
  # 高频动词(常见但值得记)
  {"word":"improve","phonetic":"ɪmˈpruːv","pos":"v.","def":"改善，提高","cefr":"A2","freq_rank":33,
   "sentence_en":"I want to improve my English.","sentence_zh":"我想提高我的英语。",
   "aids":{"morphemes":[M("im","prefix","向内，使"),M("prove","root","有益，获利(prod)")],
     "derivation":"im(使)+prove(有益) → 使更有益、更好 → 改善",
     "family":FAM("prof/prov","有益、获利",[W("profit","利润"),W("prove","证明")]),
     "mnemonic":"prove 这里含'获益'之意(法语 prou 益处);使事情往有益方向变,就是 improve 改善、提高。",
     "forms":[F("improvement","n.","改善，进步"),F("improved","adj.","改进的")]}},
  {"word":"discover","phonetic":"dɪˈskʌvə","pos":"v.","def":"发现，找到","cefr":"A2","freq_rank":21,
   "sentence_en":"Columbus discovered a new route.","sentence_zh":"哥伦布发现了一条新航线。",
   "aids":{"morphemes":[M("dis","prefix","去除，打开"),M("cover","root","覆盖")],
     "derivation":"dis(去除)+cover(盖) → 揭开盖子 → 发现",
     "family":FAM("cover","盖",[W("cover","覆盖"),W("recover","恢复"),W("discovery","发现")]),
     "mnemonic":"dis-(去掉)+cover(盖子)——把盖着的东西揭开看到,就是 discover 发现。",
     "forms":[F("discovery","n.","发现"),F("discovered","v.","过去式/过去分词")]}},
  {"word":"examine","phonetic":"ɪɡˈzæmɪn","pos":"v.","def":"检查，仔细观察；考核","cefr":"B1","freq_rank":87,
   "sentence_en":"The doctor examined the patient.","sentence_zh":"医生给病人做了检查。",
   "aids":{"morphemes":[M("exam","root","称量，检验"),M("ine","suffix","动词后缀")],
     "derivation":"拉丁 examen'秤舌、检验';放到天平上称量 → 仔细检查、考核",
     "family":FAM("","相关词",[W("exam","考试"),W("examination","检查；考试")]),
     "mnemonic":"想象把东西放天平上一点点称量核对,就是 examine 检查、考核;名词 exam/examination。",
     "forms":[F("examination","n.","检查；考试"),F("examiner","n.","主考人")]}},
  {"word":"announce","phonetic":"əˈnaʊns","pos":"v.","def":"宣布，宣告；预告","cefr":"B1","freq_rank":85,
   "sentence_en":"They announced the results yesterday.","sentence_zh":"他们昨天公布了结果。",
   "aids":{"morphemes":[M("an","prefix","朝向(ad 变体)"),M("nounce","root","报告，通知")],
     "derivation":"an(朝向)+nounce(报告) → 向众人报告 → 宣布",
     "family":FAM("nounce/nunci","报告、说",[W("pronounce","发音；宣告"),W("denounce","谴责"),W("renounce","放弃")]),
     "mnemonic":"nounce=报告(想 pronounce 宣告);向大家(an-)正式报告一件事,就是 announce 宣布。",
     "forms":[F("announcement","n.","公告，宣布")]}},
  {"word":"encourage","phonetic":"ɪnˈkʌrɪdʒ","pos":"v.","def":"鼓励，激励；促进","cefr":"A2","freq_rank":93,
   "sentence_en":"My teacher encouraged me to try again.","sentence_zh":"老师鼓励我再试一次。",
   "aids":{"morphemes":[M("en","prefix","使…"),M("courage","root","勇气")],
     "derivation":"en(使)+courage(勇气) → 使有勇气 → 鼓励",
     "family":FAM("cour/cord","心",[W("courage","勇气"),W("cordial","热忱的"),W("core","核心")]),
     "mnemonic":"en-(使)+courage(勇气)——给人注入勇气,就是 encourage 鼓励;反义 dis- 变 discourage 使泄气。",
     "forms":[F("encouragement","n.","鼓励"),F("encouraging","adj.","鼓舞人心的")]}},
  {"word":"deliver","phonetic":"dɪˈlɪvə","pos":"v.","def":"递送，交付；发表；接生","cefr":"B1","freq_rank":124,
   "sentence_en":"They deliver pizza to your door.","sentence_zh":"他们把披萨送到你家门口。",
   "aids":{"morphemes":[M("de","prefix","去除，离"),M("liver","root","自由(liber)")],
     "derivation":"de(离)+liver(自由) → 使离手、放走送出 → 递送、交付",
     "family":FAM("liber","自由",[W("liberate","解放"),W("liberty","自由"),W("liberal","自由的")]),
     "mnemonic":"liver≈自由(liber,想 liberty);把东西从手里'放'出去送到目的地,就是 deliver 递送、交付。",
     "forms":[F("delivery","n.","递送；分娩"),F("delivered","v.","过去式/过去分词")]}},
  {"word":"emerge","phonetic":"ɪˈmɜːdʒ","pos":"v.","def":"浮现，出现；显露","cefr":"B2","freq_rank":130,
   "sentence_en":"The sun emerged from behind the clouds.","sentence_zh":"太阳从云后露了出来。",
   "aids":{"morphemes":[M("e","prefix","向外"),M("merge","root","沉，浸")],
     "derivation":"e(向外)+merge(浸没) → 从水/隐蔽中冒出来 → 浮现、出现",
     "family":FAM("merg","沉、浸",[W("merge","合并；沉没"),W("submerge","淹没"),W("immerse","使沉浸")]),
     "mnemonic":"merge=浸没(反义想 submerge 淹没);从水里/暗处向外(e-)冒头,就是 emerge 浮现、出现。",
     "forms":[F("emergence","n.","出现"),F("emerging","adj.","新兴的")]}},
  {"word":"relate","phonetic":"rɪˈleɪt","pos":"v.","def":"使有联系；讲述；相处","cefr":"B1","freq_rank":56,
   "sentence_en":"The two events are closely related.","sentence_zh":"这两个事件密切相关。",
   "aids":{"morphemes":[M("re","prefix","回，相互"),M("late","root","带，拿(lat)")],
     "derivation":"re(相互)+late(带) → 把两者带到一起 → 使有联系",
     "family":FAM("lat","带、拿",[W("relation","关系"),W("translate","翻译"),W("collate","校对")]),
     "mnemonic":"late=带(拉丁 latus);把两件事往一起带、牵上线,就是 relate 使有联系;relate to=与…相关/有共鸣。",
     "forms":[F("relation","n.","关系"),F("related","adj.","相关的")]}},
  {"word":"demand","phonetic":"dɪˈmɑːnd","pos":"n./v.","def":"要求；需求","cefr":"B1","freq_rank":123,
   "sentence_en":"Workers demanded higher pay.","sentence_zh":"工人们要求提高工资。",
   "aids":{"morphemes":[M("de","prefix","加强"),M("mand","root","命令，交付")],
     "derivation":"de(加强)+mand(命令) → 强硬地命令要 → 要求",
     "family":FAM("mand","命令",[W("command","命令"),W("recommend","推荐"),W("mandatory","强制的")]),
     "mnemonic":"mand=命令(想 command);强势(de-)地下令索要,就是 demand 要求;经济学的'需求'也是 demand。",
     "forms":[F("demands","n.","要求(复数)"),F("demanding","adj.","要求高的")]}},
  {"word":"reveal","phonetic":"rɪˈviːl","pos":"v.","def":"揭示，透露；显示","cefr":"B1","freq_rank":12,
   "sentence_en":"The study reveals surprising results.","sentence_zh":"这项研究揭示了惊人的结果。",
   "aids":{"morphemes":[M("re","prefix","反，去除"),M("veal","root","面纱，遮盖(vel)")],
     "derivation":"re(去除)+veal(面纱) → 揭开面纱 → 揭示、透露",
     "family":FAM("vel","遮盖、面纱",[W("veil","面纱"),W("develop","展开(de-vel)")]),
     "mnemonic":"veal≈veil 面纱;把盖着的面纱揭掉(re-),就是 reveal 揭示、透露;反义 conceal 隐藏。",
     "forms":[F("revealing","adj.","揭露真相的"),F("revelation","n.","揭示")]}},
  {"word":"challenge","phonetic":"ˈtʃælɪndʒ","pos":"n./v.","def":"挑战；质疑","cefr":"B1","freq_rank":29,
   "sentence_en":"Learning a language is a challenge.","sentence_zh":"学一门语言是个挑战。",
   "aids":{"morphemes":[M("challeng","root","控告，挑衅(calumnia)"),M("e","suffix","结尾")],
     "derivation":"源自'控告、挑衅';公开叫板要人应战 → 挑战、质疑",
     "family":FAM("","相关词",[W("challenging","有挑战性的"),W("challenger","挑战者")]),
     "mnemonic":"想象当众下战书叫板——既指'挑战'难题,也指'质疑'某说法,就是 challenge。",
     "forms":[F("challenging","adj.","有挑战性的"),F("challenges","n.","挑战(复数)")]}},
  {"word":"replace","phonetic":"rɪˈpleɪs","pos":"v.","def":"取代，替换","cefr":"B1","freq_rank":92,
   "sentence_en":"Machines are replacing human workers.","sentence_zh":"机器正在取代人工。",
   "aids":{"morphemes":[M("re","prefix","再"),M("place","root","放置")],
     "derivation":"re(再)+place(放) → 在原位再放个新的 → 取代",
     "family":FAM("plac/place","放置",[W("place","放"),W("displace","置换")]),
     "mnemonic":"re-(再)+place(放)——原位换上新的,就是 replace 取代。","forms":[F("replacement","n.","替代品")]}},
  # 高频名词
  {"word":"statement","phonetic":"ˈsteɪtmənt","pos":"n.","def":"陈述，声明；报表","cefr":"B1","freq_rank":9,
   "sentence_en":"The minister made a public statement.","sentence_zh":"部长发表了公开声明。",
   "aids":{"morphemes":[M("state","root","陈述，状态"),M("ment","suffix","名词后缀")],
     "derivation":"state(陈述)+ment → 陈述出来的话 → 声明",
     "family":FAM("st/sta","站、立、定",[W("state","陈述；状态"),W("status","状态"),W("statue","雕像")]),
     "mnemonic":"state=陈述(把立场'立'明);正式说出的一段话,就是 statement 陈述、声明。",
     "forms":[F("state","v.","陈述"),F("statements","n.","声明(复数)")]}},
  {"word":"purpose","phonetic":"ˈpɜːpəs","pos":"n.","def":"目的，意图；用途","cefr":"A2","freq_rank":37,
   "sentence_en":"What is the purpose of this meeting?","sentence_zh":"这次会议的目的是什么？",
   "aids":{"morphemes":[M("pur","prefix","向前(pro)"),M("pose","root","放置")],
     "derivation":"pur(向前)+pose(放) → 心里预先摆好的目标 → 目的",
     "family":FAM("pos/pose","放置",[W("propose","提议"),W("suppose","假设"),W("impose","强加"),W("expose","暴露")]),
     "mnemonic":"pose=放;把目标预先(pur-)摆在前面,就是 purpose 目的;on purpose 故意。",
     "forms":[F("purposes","n.","目的(复数)"),F("purposeful","adj.","有目的的")]}},
  {"word":"surface","phonetic":"ˈsɜːfɪs","pos":"n./adj.","def":"表面；表面的","cefr":"A2","freq_rank":38,
   "sentence_en":"The surface of the lake was calm.","sentence_zh":"湖面很平静。",
   "aids":{"morphemes":[M("sur","prefix","在上"),M("face","root","脸，面")],
     "derivation":"sur(在上)+face(面) → 在上面的那一层面 → 表面",
     "family":FAM("face/fic","脸、面",[W("face","脸"),W("surface","表面"),W("facade","外表")]),
     "mnemonic":"sur-(在上)+face(面)——最上面朝外的那层'脸',就是 surface 表面;引申'肤浅的'。",
     "forms":[F("surfaces","n.","表面(复数)")]}},
  {"word":"pattern","phonetic":"ˈpætən","pos":"n.","def":"模式，规律；图案；范例","cefr":"B1","freq_rank":40,
   "sentence_en":"There is a clear pattern in the data.","sentence_zh":"数据中有明显的规律。",
   "aids":{"morphemes":[M("patr","root","父亲，范本"),M("n","suffix","结尾")],
     "derivation":"与 patron(赞助者、范本)同源;可反复照着做的范本 → 模式、图案",
     "family":FAM("patr","父亲、范本",[W("patron","赞助人"),W("paternal","父亲的")]),
     "mnemonic":"与 pattern≈patron(范本、原型)同源;可以反复套用的样板/规律,就是 pattern 模式、图案。",
     "forms":[F("patterns","n.","模式(复数)")]}},
  {"word":"element","phonetic":"ˈelɪmənt","pos":"n.","def":"元素，要素；成分","cefr":"B1","freq_rank":99,
   "sentence_en":"Trust is a key element of friendship.","sentence_zh":"信任是友谊的关键要素。",
   "aids":{"morphemes":[M("element","root","基本组成(拉丁 elementum)")],
     "derivation":"拉丁 elementum'基本成分';构成事物的基本单位 → 元素、要素",
     "family":FAM("","相关词",[W("elementary","基本的，初级的"),W("elemental","基本的")]),
     "mnemonic":"element=基本组成单位;化学的'元素'、构成整体的'要素',都是 element;初级的=elementary。",
     "forms":[F("elements","n.","要素(复数)"),F("elementary","adj.","基本的，初级的")]}},
  {"word":"solution","phonetic":"səˈluːʃən","pos":"n.","def":"解决办法；溶液","cefr":"B1","freq_rank":103,
   "sentence_en":"There is no easy solution to this problem.","sentence_zh":"这个问题没有简单的解决办法。",
   "aids":{"morphemes":[M("solu","root","松开，解开"),M("tion","suffix","名词后缀")],
     "derivation":"solu(解开)+tion → 把难题解开 → 解决办法;把固体'解散'于液体 → 溶液",
     "family":FAM("solv/solu","松开、解开",[W("solve","解决"),W("resolve","解决；决心"),W("dissolve","溶解")]),
     "mnemonic":"solu=解开(想 solve);把纠结的问题解开=solution 办法;把糖'解开'进水=溶液。",
     "forms":[F("solve","v.","解决"),F("solutions","n.","解决办法(复数)")]}},
  {"word":"conflict","phonetic":"ˈkɒnflɪkt","pos":"n./v.","def":"冲突，矛盾；抵触","cefr":"B2","freq_rank":91,
   "sentence_en":"There is a conflict between the two groups.","sentence_zh":"两个群体之间存在冲突。",
   "aids":{"morphemes":[M("con","prefix","一起，相互"),M("flict","root","打，击")],
     "derivation":"con(相互)+flict(打) → 互相打起来 → 冲突",
     "family":FAM("flict","打、击",[W("inflict","使遭受"),W("afflict","折磨")]),
     "mnemonic":"flict=打(想 inflict 施加打击);双方互相(con-)打起来、对着干,就是 conflict 冲突、矛盾。",
     "forms":[F("conflicts","n.","冲突(复数)"),F("conflicting","adj.","矛盾的")]}},
  {"word":"survey","phonetic":"ˈsɜːveɪ","pos":"n./v.","def":"调查；勘测；概览","cefr":"B1","freq_rank":109,
   "sentence_en":"We conducted a survey of 500 people.","sentence_zh":"我们对500人进行了调查。",
   "aids":{"morphemes":[M("sur","prefix","在上，越过"),M("vey","root","看(vid)")],
     "derivation":"sur(在上)+vey(看) → 从高处总览地看 → 概览、勘测、调查",
     "family":FAM("vey/vid/vis","看",[W("view","看法"),W("review","回顾"),W("vision","视力")]),
     "mnemonic":"vey=看(同 view);站高处(sur-)把全局看一遍,就是 survey 概览、调查、勘测。",
     "forms":[F("surveys","n.","调查(复数)"),F("surveyor","n.","勘测员")]}},
  {"word":"attempt","phonetic":"əˈtempt","pos":"n./v.","def":"尝试，企图","cefr":"B1","freq_rank":105,
   "sentence_en":"She made an attempt to break the record.","sentence_zh":"她尝试打破纪录。",
   "aids":{"morphemes":[M("at","prefix","朝向(ad 变体)"),M("tempt","root","试探")],
     "derivation":"at(朝向)+tempt(试) → 朝目标试一把 → 尝试、企图",
     "family":FAM("tempt","试探",[W("tempt","引诱"),W("temptation","诱惑")]),
     "mnemonic":"tempt=试探(想 tempt 引诱去试);朝(at-)一件难事伸手试一下,就是 attempt 尝试、企图。",
     "forms":[F("attempts","n.","尝试(复数)"),F("attempted","adj.","未遂的")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 4
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
