#!/usr/bin/env python
# 第八批词:约55个高频词,逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -sequ 跟随
  {"word":"consequence","phonetic":"ˈkɒnsɪkwəns","pos":"n.","def":"结果，后果；重要性","cefr":"B2","freq_rank":40,
   "sentence_en":"Actions have consequences.","sentence_zh":"行为是有后果的。",
   "aids":{"morphemes":[M("con","prefix","一起，随"),M("sequ","root","跟随"),M("ence","suffix","名词后缀")],
     "derivation":"con(随)+sequ(跟) → 随之而来的东西 → 结果、后果",
     "family":FAM("sequ/secut","跟随",[W("sequence","顺序"),W("consequent","随之发生的"),W("subsequent","随后的")]),
     "mnemonic":"sequ=跟随(想 sequence 序列);紧跟一件事之后到来的,就是 consequence 后果;as a consequence 因此。",
     "forms":[F("consequent","adj.","随之发生的"),F("consequently","adv.","因此")]}},
  # -pos 放 扩展
  {"word":"propose","phonetic":"prəˈpəʊz","pos":"v.","def":"提议，建议；求婚","cefr":"B1","freq_rank":59,
   "sentence_en":"I propose a new plan.","sentence_zh":"我提议一个新计划。",
   "aids":{"morphemes":[M("pro","prefix","向前"),M("pose","root","放置")],
     "derivation":"pro(向前)+pose(放) → 把想法摆到前面 → 提议",
     "family":FAM("pos/pose","放置",[W("purpose","目的"),W("suppose","假设"),W("impose","强加"),W("expose","暴露")]),
     "mnemonic":"pose=放;把方案往前(pro-)一摆,就是 propose 提议;向对方'摆出'终身之约=求婚。",
     "forms":[F("proposal","n.","提议"),F("proposed","v.","过去式/过去分词")]}},
  {"word":"proposal","phonetic":"prəˈpəʊzl","pos":"n.","def":"提议，计划；求婚","cefr":"B1","freq_rank":39,
   "sentence_en":"The committee rejected the proposal.","sentence_zh":"委员会否决了这项提议。",
   "aids":{"morphemes":[M("pro","prefix","向前"),M("pos","root","放置"),M("al","suffix","名词后缀")],
     "derivation":"pro(向前)+pos(放) → 摆到前面的方案 → 提议",
     "family":FAM("pos/pose","放置",[W("propose","提议"),W("purpose","目的"),W("expose","暴露")]),
     "mnemonic":"propose(提议)的名词;摆出来供人考虑的方案,就是 proposal 提议、计划。",
     "forms":[F("proposals","n.","提议(复数)")]}},
  # -clude 关
  {"word":"conclusion","phonetic":"kənˈkluːʒən","pos":"n.","def":"结论；结尾","cefr":"B2","freq_rank":51,
   "sentence_en":"We reached the same conclusion.","sentence_zh":"我们得出了相同的结论。",
   "aids":{"morphemes":[M("con","prefix","完全"),M("clus","root","关闭"),M("ion","suffix","名词后缀")],
     "derivation":"con(完全)+clus(关) → 收尾关合、下定论 → 结论、结尾",
     "family":FAM("clud/clus","关闭",[W("conclude","得出结论"),W("include","包括"),W("exclude","排除")]),
     "mnemonic":"clus=关(和 conclude 一家);把讨论完全关合、定下的看法,就是 conclusion 结论;in conclusion 总之。",
     "forms":[F("conclude","v.","得出结论"),F("conclusive","adj.","决定性的")]}},
  # -gen 产生
  {"word":"generate","phonetic":"ˈdʒenəreɪt","pos":"v.","def":"产生，生成；发电","cefr":"B2","freq_rank":58,
   "sentence_en":"Solar panels generate electricity.","sentence_zh":"太阳能板发电。",
   "aids":{"morphemes":[M("gener","root","产生，种"),M("ate","suffix","动词后缀")],
     "derivation":"gener(产生)+ate → 使产生 → 生成、发电",
     "family":FAM("gen/gener","产生、种类",[W("general","普遍的"),W("generation","一代"),W("genetic","基因的"),W("genre","类型")]),
     "mnemonic":"gener=产生(想 generation 一代人);使某物凭空产生出来,就是 generate 产生、发电;generator 发电机。",
     "forms":[F("generation","n.","产生；一代"),F("generator","n.","发电机")]}},
  # -cap/-cept 拿
  {"word":"capacity","phonetic":"kəˈpæsɪti","pos":"n.","def":"容量；能力；身份","cefr":"B2","freq_rank":88,
   "sentence_en":"The stadium has a capacity of 50,000.","sentence_zh":"这座体育场可容纳五万人。",
   "aids":{"morphemes":[M("cap","root","拿，容纳"),M("acity","suffix","名词后缀")],
     "derivation":"cap(容纳)+acity → 能容纳/胜任的量 → 容量、能力",
     "family":FAM("cap/cept","拿、容纳",[W("capable","有能力的"),W("capture","捕获"),W("accept","接受"),W("capacity","容量")]),
     "mnemonic":"cap=容纳(想 capable 能干);能装多少、能胜任多少,就是 capacity 容量、能力。",
     "forms":[F("capable","adj.","有能力的")]}},
  {"word":"capture","phonetic":"ˈkæptʃə","pos":"v./n.","def":"俘获，捕捉；夺得","cefr":"B1","freq_rank":66,
   "sentence_en":"The photo captured the moment.","sentence_zh":"这张照片捕捉到了那个瞬间。",
   "aids":{"morphemes":[M("capt","root","拿，抓"),M("ure","suffix","名词后缀")],
     "derivation":"capt(抓)+ure → 抓住、擒住 → 俘获、捕捉",
     "family":FAM("cap/capt","拿、抓",[W("captive","俘虏"),W("capable","有能力的"),W("accept","接受")]),
     "mnemonic":"capt=抓(和 captive 俘虏一家);一把抓住、擒获,就是 capture 俘获、捕捉。",
     "forms":[F("captured","v.","过去式/过去分词"),F("captive","n.","俘虏")]}},
  # -pon/-pos 放
  {"word":"component","phonetic":"kəmˈpəʊnənt","pos":"n./adj.","def":"组成部分，部件；组成的","cefr":"B2","freq_rank":84,
   "sentence_en":"Each component must be tested.","sentence_zh":"每个部件都必须测试。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("pon","root","放置"),M("ent","suffix","…的")],
     "derivation":"com(一起)+pon(放) → 放到一起构成整体的一块 → 组成部分",
     "family":FAM("pon/pos","放置",[W("compose","组成"),W("opponent","对手"),W("postpone","推迟")]),
     "mnemonic":"pon=放(和 compose 组成一家);和别的一起(com-)放进来构成整体的一块,就是 component 部件。",
     "forms":[F("components","n.","部件(复数)")]}},
  # -tend/-tent 伸
  {"word":"extent","phonetic":"ɪkˈstent","pos":"n.","def":"程度，范围","cefr":"B2","freq_rank":83,
   "sentence_en":"To what extent do you agree?","sentence_zh":"你在多大程度上同意？",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("tent","root","伸展")],
     "derivation":"ex(向外)+tent(伸) → 伸展开的幅度 → 程度、范围",
     "family":FAM("tend/tent","伸展",[W("extend","延伸"),W("intend","打算"),W("tension","紧张")]),
     "mnemonic":"tent=伸;向外伸展到多大,就是 extent 程度、范围;to some extent 在某种程度上。",
     "forms":[F("extend","v.","延伸")]}},
  # -sure 确保
  {"word":"ensure","phonetic":"ɪnˈʃʊə","pos":"v.","def":"确保，保证","cefr":"B2","freq_rank":82,
   "sentence_en":"Please ensure the door is locked.","sentence_zh":"请确保门锁好了。",
   "aids":{"morphemes":[M("en","prefix","使"),M("sure","root","确定")],
     "derivation":"en(使)+sure(确定) → 使确定无疑 → 确保",
     "family":FAM("sur/secur","确保、安全",[W("sure","确定的"),W("assure","使确信"),W("insure","保险"),W("secure","安全的")]),
     "mnemonic":"en-(使)+sure(确定)——让事情确定发生,就是 ensure 确保;别和 insure(保险)/assure(使人放心)混。",
     "forms":[F("ensured","v.","过去式/过去分词")]}},
  # -preci 价值
  {"word":"appreciate","phonetic":"əˈpriːʃieɪt","pos":"v.","def":"欣赏；感激；理解；增值","cefr":"B2","freq_rank":77,
   "sentence_en":"I really appreciate your help.","sentence_zh":"我非常感激你的帮助。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("preci","root","价值，价格"),M("ate","suffix","动词后缀")],
     "derivation":"ap(朝向)+preci(价值) → 看重其价值 → 欣赏、感激",
     "family":FAM("preci","价值、价格",[W("precious","珍贵的"),W("price","价格"),W("praise","赞扬")]),
     "mnemonic":"preci=价值(想 precious 珍贵、price 价格);看重某物/某人的价值,就是 appreciate 欣赏、感激;资产'涨价值'=增值。",
     "forms":[F("appreciation","n.","欣赏；感激"),F("appreciated","v.","过去式/过去分词")]}},
  # -lect 选
  {"word":"select","phonetic":"sɪˈlekt","pos":"v./adj.","def":"挑选，选择；精选的","cefr":"B1","freq_rank":75,
   "sentence_en":"Select the correct answer.","sentence_zh":"选出正确答案。",
   "aids":{"morphemes":[M("se","prefix","分开，离"),M("lect","root","选，收")],
     "derivation":"se(分开)+lect(选) → 从中挑出分开 → 挑选",
     "family":FAM("lect/leg","选、收",[W("collect","收集"),W("elect","选举"),W("neglect","忽视")]),
     "mnemonic":"lect=选;把中意的从一堆里分(se-)出来,就是 select 挑选;selection 选择。",
     "forms":[F("selection","n.","选择"),F("selected","adj.","精选的")]}},
  # -clar 清楚
  {"word":"declare","phonetic":"dɪˈkleə","pos":"v.","def":"宣布，声明；申报","cefr":"B2","freq_rank":76,
   "sentence_en":"They declared independence.","sentence_zh":"他们宣布独立。",
   "aids":{"morphemes":[M("de","prefix","加强，完全"),M("clar","root","清楚")],
     "derivation":"de(完全)+clar(清楚) → 把话讲得一清二楚 → 宣布、声明",
     "family":FAM("clar","清楚",[W("clear","清楚的"),W("clarify","澄清"),W("clarity","清晰")]),
     "mnemonic":"clar=清楚(想 clear);把立场彻底(de-)讲清楚公开,就是 declare 宣布;过海关'申报'也是 declare。",
     "forms":[F("declaration","n.","宣言，声明")]}},
  # -mend
  {"word":"recommend","phonetic":"ˌrekəˈmend","pos":"v.","def":"推荐，建议","cefr":"B1","freq_rank":57,
   "sentence_en":"Can you recommend a good book?","sentence_zh":"你能推荐一本好书吗？",
   "aids":{"morphemes":[M("re","prefix","再，加强"),M("com","prefix","一起"),M("mend","root","委托，交付(mand)")],
     "derivation":"re+com+mend(交付) → 郑重地把好东西托付/引荐给人 → 推荐",
     "family":FAM("mand/mend","命令、交付",[W("command","命令"),W("demand","要求"),W("mandatory","强制的")]),
     "mnemonic":"mend=交付(mand 家族);把好东西郑重托付、引荐给你,就是 recommend 推荐;名词 recommendation。",
     "forms":[F("recommendation","n.","推荐"),F("recommended","adj.","推荐的")]}},
  # -not 知/标记
  {"word":"notion","phonetic":"ˈnəʊʃən","pos":"n.","def":"概念，观念；想法","cefr":"B2","freq_rank":65,
   "sentence_en":"He has no notion of the danger.","sentence_zh":"他对危险毫无概念。",
   "aids":{"morphemes":[M("not","root","知道，标记"),M("ion","suffix","名词后缀")],
     "derivation":"not(知)+ion → 心里知道的一个念头 → 概念、想法",
     "family":FAM("not","知道、标记",[W("note","笔记"),W("notice","注意"),W("notable","著名的")]),
     "mnemonic":"not=知(想 notice 注意到);脑中形成的一个认识、念头,就是 notion 概念、想法。",
     "forms":[F("notions","n.","概念(复数)")]}},
  # -un 一
  {"word":"union","phonetic":"ˈjuːnjən","pos":"n.","def":"联合，联盟；工会","cefr":"B1","freq_rank":50,
   "sentence_en":"The workers formed a union.","sentence_zh":"工人们组建了工会。",
   "aids":{"morphemes":[M("un","root","一"),M("ion","suffix","名词后缀")],
     "derivation":"un(一)+ion → 合成一体 → 联合、联盟",
     "family":FAM("uni/un","一",[W("unite","联合"),W("unity","团结"),W("unique","独特的"),W("universe","宇宙")]),
     "mnemonic":"un=一(想 unite 联合);多方合成'一'个整体,就是 union 联合、联盟;工人合一=工会 trade union。",
     "forms":[F("unite","v.","联合"),F("unions","n.","工会(复数)")]}},
  {"word":"unique","phonetic":"juːˈniːk","pos":"adj.","def":"独特的，独一无二的","cefr":"B1","freq_rank":70,
   "sentence_en":"Every fingerprint is unique.","sentence_zh":"每个人的指纹都是独一无二的。",
   "aids":{"morphemes":[M("uni","root","一"),M("que","suffix","结尾")],
     "derivation":"uni(一)+que → 仅此一个 → 独一无二的",
     "family":FAM("uni","一",[W("unit","单位"),W("unite","联合"),W("universal","普遍的")]),
     "mnemonic":"uni=一(想 unit 单位);世上仅此一份、别无分店,就是 unique 独特的。",
     "forms":[F("uniquely","adv.","独特地")]}},
  # -tern 内
  {"word":"internal","phonetic":"ɪnˈtɜːnl","pos":"adj.","def":"内部的；国内的","cefr":"B2","freq_rank":71,
   "sentence_en":"The company has internal problems.","sentence_zh":"公司存在内部问题。",
   "aids":{"morphemes":[M("intern","root","内部"),M("al","suffix","…的")],
     "derivation":"intern(内)+al → 里面的 → 内部的",
     "family":FAM("inter/intern","内、之间",[W("interior","内部的"),W("internal","内部的")]),
     "mnemonic":"intern=内(想 interior 内部);属于里面的、机构内部的,就是 internal;反义 external 外部的。",
     "forms":[F("internally","adv.","内部地")]}},
  # -loc 地方
  {"word":"location","phonetic":"ləʊˈkeɪʃən","pos":"n.","def":"位置，地点","cefr":"B1","freq_rank":20,
   "sentence_en":"The shop is in a good location.","sentence_zh":"这家店位置很好。",
   "aids":{"morphemes":[M("loc","root","地方"),M("ation","suffix","名词后缀")],
     "derivation":"loc(地方)+ation → 所处的地方 → 位置",
     "family":FAM("loc","地方",[W("local","当地的"),W("locate","定位"),W("locale","场所")]),
     "mnemonic":"loc=地方(想 local 当地的);某物所在的那个地点,就是 location 位置。",
     "forms":[F("locate","v.","定位"),F("local","adj.","当地的")]}},
  {"word":"locate","phonetic":"ləʊˈkeɪt","pos":"v.","def":"定位，找出；使位于","cefr":"B2","freq_rank":55,
   "sentence_en":"We couldn't locate the file.","sentence_zh":"我们找不到那个文件。",
   "aids":{"morphemes":[M("loc","root","地方"),M("ate","suffix","动词后缀")],
     "derivation":"loc(地方)+ate → 确定/安置在某地 → 定位、使位于",
     "family":FAM("loc","地方",[W("location","位置"),W("local","当地的"),W("allocate","分配")]),
     "mnemonic":"loc=地方;找出/确定某物在哪个地方,就是 locate 定位;be located in 位于。",
     "forms":[F("located","adj.","位于…的"),F("location","n.","位置")]}},
  # -nect 连
  {"word":"connect","phonetic":"kəˈnekt","pos":"v.","def":"连接，联系","cefr":"A2","freq_rank":44,
   "sentence_en":"Connect the printer to the computer.","sentence_zh":"把打印机连到电脑上。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("nect","root","系，绑")],
     "derivation":"con(一起)+nect(系) → 系到一起 → 连接",
     "family":FAM("nect","系、绑",[W("connection","连接"),W("connective","连接的")]),
     "mnemonic":"nect=系;把两头系(nect)到一起(con-),就是 connect 连接;反义 disconnect 断开。",
     "forms":[F("connected","adj.","连接的"),F("connection","n.","连接")]}},
  # -tract/-tras 站/拉
  {"word":"contrast","phonetic":"ˈkɒntrɑːst","pos":"n./v.","def":"对比，对照；差异","cefr":"B2","freq_rank":85,
   "sentence_en":"There is a sharp contrast between them.","sentence_zh":"它们之间有鲜明的对比。",
   "aids":{"morphemes":[M("contra","prefix","相反"),M("st","root","站")],
     "derivation":"contra(相反)+st(站) → 相反地站着比 → 对比",
     "family":FAM("st/sta","站、立",[W("stand","站立"),W("stable","稳定的"),W("constant","恒定的")]),
     "mnemonic":"contra(相反)+st(站)——把两者对立着摆出来比,就是 contrast 对比;in contrast 相比之下;by contrast 对比来看。",
     "forms":[F("contrasts","n.","对比(复数)"),F("contrasting","adj.","对比的")]}},
  # 高频名词/动词(常见但值得记)
  {"word":"balance","phonetic":"ˈbæləns","pos":"n./v.","def":"平衡；余额；使平衡","cefr":"B1","freq_rank":41,
   "sentence_en":"Try to keep a work-life balance.","sentence_zh":"尽量保持工作与生活的平衡。",
   "aids":{"morphemes":[M("bi","prefix","二"),M("lanc","root","盘，秤(lanx)"),M("e","suffix","结尾")],
     "derivation":"bi(二)+lanc(秤盘) → 天平两个盘相等 → 平衡",
     "family":FAM("","相关词",[W("balanced","平衡的"),W("imbalance","不平衡")]),
     "mnemonic":"想象天平的'两(bi)个秤盘(lanc)'一样重,就是 balance 平衡;账上剩下的'配平数'=余额。",
     "forms":[F("balanced","adj.","平衡的"),F("balances","n.","余额(复数)")]}},
  {"word":"adopt","phonetic":"əˈdɒpt","pos":"v.","def":"采用；收养；正式通过","cefr":"B1","freq_rank":42,
   "sentence_en":"They adopted a new policy.","sentence_zh":"他们采用了新政策。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("opt","root","选择")],
     "derivation":"ad(朝向)+opt(选) → 主动选来纳为己用 → 采用、收养",
     "family":FAM("opt","选择",[W("option","选择"),W("optional","可选的"),W("opt","选择")]),
     "mnemonic":"opt=选(想 option 选项);挑选过来纳为己有=adopt 采用;把孩子选来当自家的=收养。",
     "forms":[F("adoption","n.","采用；收养"),F("adopted","adj.","被收养的")]}},
  {"word":"minority","phonetic":"maɪˈnɒrɪti","pos":"n.","def":"少数；少数民族","cefr":"B2","freq_rank":43,
   "sentence_en":"Only a minority disagreed.","sentence_zh":"只有少数人不同意。",
   "aids":{"morphemes":[M("minor","root","较小的"),M("ity","suffix","名词后缀")],
     "derivation":"minor(较小)+ity → 较小的那部分 → 少数",
     "family":FAM("min","小",[W("minor","次要的"),W("minimum","最小值"),W("diminish","减少")]),
     "mnemonic":"minor=较小(反义 major);占较小的那部分,就是 minority 少数;反义 majority 多数。",
     "forms":[F("minorities","n.","少数民族(复数)")]}},
  {"word":"organize","phonetic":"ˈɔːɡənaɪz","pos":"v.","def":"组织，安排","cefr":"A2","freq_rank":46,
   "sentence_en":"She organized the whole event.","sentence_zh":"她组织了整个活动。",
   "aids":{"morphemes":[M("organ","root","器官，工具"),M("ize","suffix","使…(动词)")],
     "derivation":"organ(器官)+ize → 使像器官一样各司其职、协调运作 → 组织",
     "family":FAM("organ","器官、工具",[W("organ","器官"),W("organic","有机的"),W("organism","生物体")]),
     "mnemonic":"organ=器官;让各部分像身体器官那样协调配合,就是 organize 组织;名词 organization。",
     "forms":[F("organization","n.","组织，机构"),F("organized","adj.","有条理的")]}},
  {"word":"regional","phonetic":"ˈriːdʒənl","pos":"adj.","def":"地区的，区域的","cefr":"B1","freq_rank":47,
   "sentence_en":"There are regional differences in food.","sentence_zh":"食物存在地区差异。",
   "aids":{"morphemes":[M("region","root","地区"),M("al","suffix","…的")],
     "derivation":"region(地区)+al → 与地区有关的 → 地区的",
     "family":FAM("reg","统治、划界",[W("region","地区"),W("regular","规则的"),W("reign","统治")]),
     "mnemonic":"region(地区)+al——属于某一地区、地方性的,就是 regional。",
     "forms":[F("region","n.","地区")]}},
  {"word":"code","phonetic":"kəʊd","pos":"n./v.","def":"代码，密码；准则；编码","cefr":"B1","freq_rank":48,
   "sentence_en":"Enter your PIN code.","sentence_zh":"请输入你的密码。",
   "aids":{"morphemes":[M("cod","root","书板，法典(codex)"),M("e","suffix","结尾")],
     "derivation":"拉丁 codex'法典、书板';成套的规则/符号系统 → 法典、代码",
     "family":FAM("cod","书板、法典",[W("codex","古抄本"),W("encode","编码"),W("decode","解码")]),
     "mnemonic":"code 源自'法典 codex';一套规则=行为准则(dress code);一套符号=代码/密码;转成符号=编码。",
     "forms":[F("codes","n.","代码(复数)"),F("coding","n.","编码")]}},
  {"word":"acknowledge","phonetic":"əkˈnɒlɪdʒ","pos":"v.","def":"承认；告知收悉；答谢","cefr":"B2","freq_rank":49,
   "sentence_en":"He acknowledged his mistake.","sentence_zh":"他承认了自己的错误。",
   "aids":{"morphemes":[M("ac","prefix","朝向(ad 变体)"),M("knowledge","root","知道，认识")],
     "derivation":"ac(朝向)+knowledge(知) → 公开表示知道、认账 → 承认",
     "family":FAM("know","知道",[W("knowledge","知识"),W("know","知道")]),
     "mnemonic":"ac-+knowledge(知)——把'我知道/我认了'摆出来,就是 acknowledge 承认;收到邮件回一句=告知收悉。",
     "forms":[F("acknowledgement","n.","承认；致谢")]}},
  {"word":"trend","phonetic":"trend","pos":"n./v.","def":"趋势，倾向；走向","cefr":"B1","freq_rank":60,
   "sentence_en":"There is a growing trend toward online shopping.","sentence_zh":"网购的趋势日益增长。",
   "aids":{"morphemes":[M("trend","root","转，旋(古英语 trendan)")],
     "derivation":"古英语'旋转、转向';事物发展转向的方向 → 趋势",
     "family":FAM("","相关词",[W("trendy","时髦的"),W("trending","热门的")]),
     "mnemonic":"trend=转向;事物发展朝哪个方向'转',就是 trend 趋势;trendy 时髦的(顺应潮流)。",
     "forms":[F("trends","n.","趋势(复数)"),F("trendy","adj.","时髦的")]}},
  {"word":"profit","phonetic":"ˈprɒfɪt","pos":"n./v.","def":"利润，收益；获益","cefr":"B1","freq_rank":63,
   "sentence_en":"The company made a big profit.","sentence_zh":"公司获得了巨额利润。",
   "aids":{"morphemes":[M("pro","prefix","向前"),M("fit","root","做(fic)")],
     "derivation":"pro(向前)+fit(做) → 做出来往前多出的部分 → 利润",
     "family":FAM("fic/fit","做",[W("benefit","益处"),W("profitable","有利可图的")]),
     "mnemonic":"pro-(向前)+fit(做)——做买卖后往前多出来的钱,就是 profit 利润;profitable 赚钱的。",
     "forms":[F("profitable","adj.","有利可图的"),F("profits","n.","利润(复数)")]}},
  {"word":"content","phonetic":"ˈkɒntent","pos":"n.","def":"内容；含量","cefr":"B1","freq_rank":74,
   "sentence_en":"The content of the book is excellent.","sentence_zh":"这本书的内容很棒。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("tent","root","拿，含(tain)")],
     "derivation":"con(一起)+tent(含) → 里面所含的东西 → 内容",
     "family":FAM("tain/tent","拿、含",[W("contain","包含"),W("maintain","维持"),W("container","容器")]),
     "mnemonic":"tent=含(和 contain 一家);容器/文本里所含(con-tain)的东西,就是 content 内容;另读 /kənˈtent/=满足的。",
     "forms":[F("contents","n.","目录；内容(复数)")]}},
  {"word":"shift","phonetic":"ʃɪft","pos":"n./v.","def":"转变，转移；轮班","cefr":"B1","freq_rank":53,
   "sentence_en":"There has been a shift in public opinion.","sentence_zh":"公众舆论发生了转变。",
   "aids":{"morphemes":[M("shift","root","移动，安排(古英语 sciftan)")],
     "derivation":"古英语'分配、移动';位置/状态的挪动 → 转移;轮流分配的工时 → 轮班",
     "family":FAM("","相关词",[W("shifting","变动的")]),
     "mnemonic":"shift=挪动;立场/重心一挪=转变、转移;工人轮流换的一段工时=轮班(night shift 夜班)。",
     "forms":[F("shifts","n.","轮班(复数)"),F("shifted","v.","过去式/过去分词")]}},
  {"word":"link","phonetic":"lɪŋk","pos":"n./v.","def":"链接，联系；环节","cefr":"A2","freq_rank":72,
   "sentence_en":"Click the link to continue.","sentence_zh":"点击链接以继续。",
   "aids":{"morphemes":[M("link","root","环，节(古诺斯语 hlenkr)")],
     "derivation":"本义'链条上的一环';把两环扣起 → 连接、联系",
     "family":FAM("","相关词",[W("linkage","连接"),W("hyperlink","超链接")]),
     "mnemonic":"link=链条的一环;一环扣一环把两头连起来,就是 link 链接、联系;网页的 link 超链接。",
     "forms":[F("linked","v.","过去式/过去分词"),F("links","n.","链接(复数)")]}},
  {"word":"stress","phonetic":"stres","pos":"n./v.","def":"压力；强调；重音","cefr":"B1","freq_rank":73,
   "sentence_en":"She is under a lot of stress.","sentence_zh":"她承受着很大压力。",
   "aids":{"morphemes":[M("stress","root","拉紧(district/strict 的 str)")],
     "derivation":"与 strict/string'拉紧'同源;绷紧施压 → 压力;说话时'加重'某处 → 强调、重音",
     "family":FAM("strict/string","拉紧",[W("strict","严格的"),W("restrict","限制"),W("string","线")]),
     "mnemonic":"str=拉紧(和 strict 一家);绷在身上的紧张=压力;把话某处'绷紧'加重=强调、重音。",
     "forms":[F("stressed","adj.","有压力的"),F("stressful","adj.","压力大的")]}},
  {"word":"outcome","phonetic":"ˈaʊtkʌm","pos":"n.","def":"结果，结局","cefr":"B1","freq_rank":81,
   "sentence_en":"We are hopeful about the outcome.","sentence_zh":"我们对结果抱有希望。",
   "aids":{"morphemes":[M("out","prefix","出来"),M("come","root","来")],
     "derivation":"out(出来)+come(来) → 最后出来的东西 → 结果",
     "family":FAM("","相关词",[W("income","收入(进来的)"),W("outgoing","外出的")]),
     "mnemonic":"out(出)+come(来)——一件事最终'出来'的东西,就是 outcome 结果;对照 income 收入(往里来的钱)。",
     "forms":[F("outcomes","n.","结果(复数)")]}},
  {"word":"launch","phonetic":"lɔːntʃ","pos":"v./n.","def":"发射；发起；(产品)推出","cefr":"B2","freq_rank":80,
   "sentence_en":"They will launch the product next month.","sentence_zh":"他们将于下月推出该产品。",
   "aids":{"morphemes":[M("launch","root","投掷，使冲出(lance 长矛)")],
     "derivation":"与 lance(长矛)同源'投掷';猛地送出去 → 发射、发起、推出",
     "family":FAM("lanc","矛、投",[W("lance","长矛")]),
     "mnemonic":"launch 与 lance(长矛)同源'投出';把火箭/活动/产品猛地送出去,就是 launch 发射、发起、推出。",
     "forms":[F("launched","v.","过去式/过去分词"),F("launches","n.","发射(复数)")]}},
  {"word":"revenue","phonetic":"ˈrevɪnjuː","pos":"n.","def":"收入，收益；税收","cefr":"B2","freq_rank":54,
   "sentence_en":"Advertising is their main source of revenue.","sentence_zh":"广告是他们的主要收入来源。",
   "aids":{"morphemes":[M("re","prefix","回"),M("ven","root","来"),M("ue","suffix","结尾")],
     "derivation":"re(回)+ven(来) → 回流进来的钱 → 收入、税收",
     "family":FAM("ven","来",[W("event","事件"),W("prevent","预防"),W("avenue","大道"),W("invent","发明")]),
     "mnemonic":"ven=来(想 event);'回(re-)来'到手的钱,就是 revenue 收入;政府收回的税=税收。",
     "forms":[F("revenues","n.","收入(复数)")]}},
  {"word":"appearance","phonetic":"əˈpɪərəns","pos":"n.","def":"外表，外观；出现","cefr":"B1","freq_rank":56,
   "sentence_en":"Don't judge by appearance.","sentence_zh":"不要以貌取人。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("pear","root","出现，可见"),M("ance","suffix","名词后缀")],
     "derivation":"appear(出现)+ance → 显现出来的样子 → 外表、出现",
     "family":FAM("par/pear","出现、可见",[W("appear","出现"),W("apparent","明显的"),W("transparent","透明的")]),
     "mnemonic":"appear(出现)的名词;呈现在人眼前的样子,就是 appearance 外表、外观;first appearance 首次露面。",
     "forms":[F("appearances","n.","外表(复数)")]}},
  {"word":"circumstance","phonetic":"ˈsɜːkəmstəns","pos":"n.","def":"情况，环境；境遇","cefr":"B2","freq_rank":90,
   "sentence_en":"Under no circumstances should you give up.","sentence_zh":"无论如何你都不应放弃。",
   "aids":{"morphemes":[M("circum","prefix","周围"),M("st","root","站"),M("ance","suffix","名词后缀")],
     "derivation":"circum(周围)+st(站) → 环绕在你四周站着的条件 → 情况、环境",
     "family":FAM("circum","周围",[W("circle","圆"),W("circuit","环路"),W("circulate","循环")]),
     "mnemonic":"circum=周围(想 circle 圆)+st(站)——围在你四周的一切状况,就是 circumstance 情况、境遇。",
     "forms":[F("circumstances","n.","情况(复数)")]}},
  # 常见词
  {"word":"aware","phonetic":"əˈweə","pos":"adj.","def":"意识到的，知道的","cefr":"B1","freq_rank":21,
   "sentence_en":"Are you aware of the risks?","sentence_zh":"你意识到风险了吗？",
   "aids":{"morphemes":[M("a","prefix","加强"),M("ware","root","警觉，看(wary)")],
     "derivation":"a+ware(警觉) → 警觉察知的 → 意识到的",
     "family":FAM("ware/wary","警觉、看守",[W("beware","当心"),W("wary","谨慎的"),W("warn","警告")]),
     "mnemonic":"ware=警觉(想 beware 当心、wary 谨慎);对某事保持警觉、心里有数,就是 aware;be aware of 意识到。",
     "forms":[F("awareness","n.","意识，觉察")]}},
  {"word":"moral","phonetic":"ˈmɒrəl","pos":"adj./n.","def":"道德的；道德，寓意","cefr":"B1","freq_rank":23,
   "sentence_en":"It raises a moral question.","sentence_zh":"这引出了一个道德问题。",
   "aids":{"morphemes":[M("mor","root","风俗，品行(mores)"),M("al","suffix","…的")],
     "derivation":"拉丁 mores'风俗、品行';合乎品行规范的 → 道德的",
     "family":FAM("mor","风俗、品行",[W("morality","道德"),W("morale","士气")]),
     "mnemonic":"mor=品行/风俗(拉丁 mores);关乎善恶品行的,就是 moral 道德的;故事的'寓意'=the moral。",
     "forms":[F("morality","n.","道德"),F("morally","adv.","道德上")]}},
  {"word":"chief","phonetic":"tʃiːf","pos":"adj./n.","def":"主要的；首领，长官","cefr":"B1","freq_rank":22,
   "sentence_en":"That is our chief concern.","sentence_zh":"那是我们的主要关切。",
   "aids":{"morphemes":[M("chief","root","头(caput)")],
     "derivation":"拉丁 caput'头';排在头位的 → 主要的;头领 → 首领",
     "family":FAM("cap/chief","头",[W("capital","首都"),W("captain","船长"),W("chef","厨师长")]),
     "mnemonic":"chief 源自'头(caput)';位居头位的=主要的;当头的人=首领(chief 与 chef 厨师长同源)。",
     "forms":[F("chiefly","adv.","主要地"),F("chiefs","n.","首领(复数)")]}},
  {"word":"fair","phonetic":"feə","pos":"adj./n.","def":"公平的；相当的；集市；晴朗的","cefr":"A2","freq_rank":25,
   "sentence_en":"It's not fair!","sentence_zh":"这不公平！",
   "aids":{"morphemes":[M("fair","root","美好，公正(古英语 fæger)")],
     "derivation":"古英语'美好、洁净';引申公正、尚可、晴好",
     "family":FAM("","相关词",[W("fairly","相当地"),W("fairness","公平"),W("unfair","不公平的")]),
     "mnemonic":"fair 本义'美好洁净';待人不偏=公平;成绩尚可=相当的;天气好=晴朗;另义'集市'(book fair)。",
     "forms":[F("fairly","adv.","相当地；公平地"),F("fairness","n.","公平")]}},
  {"word":"hire","phonetic":"ˈhaɪə","pos":"v./n.","def":"雇用；租用","cefr":"A2","freq_rank":26,
   "sentence_en":"They hired a new manager.","sentence_zh":"他们雇了一位新经理。",
   "aids":{"morphemes":[M("hire","root","雇，租(古英语 hyrian)")],
     "derivation":"古英语'付酬使用';付钱用人 → 雇用;付钱用物 → 租用",
     "family":FAM("","相关词",[W("hiring","招聘"),W("hired","被雇的")]),
     "mnemonic":"hire=付钱使用;付酬请人干活=雇用;付费用东西=租用(hire a car 租车)。",
     "forms":[F("hired","v.","过去式/过去分词"),F("hiring","n.","招聘")]}},
  {"word":"circle","phonetic":"ˈsɜːkl","pos":"n./v.","def":"圆；圈子；环绕","cefr":"A2","freq_rank":27,
   "sentence_en":"Draw a circle on the paper.","sentence_zh":"在纸上画一个圆。",
   "aids":{"morphemes":[M("circ","root","环，圈"),M("le","suffix","小")],
     "derivation":"circ(环)+le → 小小的环 → 圆、圈",
     "family":FAM("circ","环、圈",[W("circuit","环路"),W("circulate","循环"),W("circus","马戏团(圆场)")]),
     "mnemonic":"circ=环(想 circus 圆形马戏场);一圈闭合的线=圆;一群相熟的人=圈子(social circle)。",
     "forms":[F("circles","n.","圈子(复数)"),F("circular","adj.","圆形的")]}},
  {"word":"otherwise","phonetic":"ˈʌðəwaɪz","pos":"adv.","def":"否则；另外；在其他方面","cefr":"B1","freq_rank":31,
   "sentence_en":"Hurry, otherwise we'll be late.","sentence_zh":"快点，否则我们要迟到了。",
   "aids":{"morphemes":[M("other","root","其他"),M("wise","root","方式，方向")],
     "derivation":"other(其他)+wise(方式) → 以其他方式、若非如此 → 否则",
     "family":FAM("wise","方式、方向",[W("likewise","同样地"),W("clockwise","顺时针")]),
     "mnemonic":"other(其他)+wise(方式,如 clockwise)——若换个样、若非如此,就是 otherwise 否则、另外。",
     "forms":[]}},
  {"word":"extra","phonetic":"ˈekstrə","pos":"adj./adv./n.","def":"额外的；特别地；额外之物","cefr":"A2","freq_rank":33,
   "sentence_en":"There is no extra charge.","sentence_zh":"没有额外费用。",
   "aids":{"morphemes":[M("extra","root","以外，超出")],
     "derivation":"拉丁 extra'在…之外';超出常规之外的 → 额外的",
     "family":FAM("extra/exter","以外",[W("extraordinary","非凡的"),W("external","外部的"),W("extreme","极端的")]),
     "mnemonic":"extra=以外(想 extraordinary 超出寻常=非凡);正常之外多加的,就是 extra 额外的。",
     "forms":[]}},
  {"word":"emotional","phonetic":"ɪˈməʊʃənl","pos":"adj.","def":"情绪的，情感的；易动感情的","cefr":"B1","freq_rank":37,
   "sentence_en":"It was an emotional moment.","sentence_zh":"那是个动情的时刻。",
   "aids":{"morphemes":[M("e","prefix","向外"),M("mot","root","动"),M("ional","suffix","…的")],
     "derivation":"e(向外)+mot(动) → 内心波动外露的 → 情绪的",
     "family":FAM("mot/mov","动",[W("emotion","情绪"),W("motion","运动"),W("motive","动机")]),
     "mnemonic":"mot=动(和 emotion 一家);内心被搅动、易外露的,就是 emotional 情绪的、易动感情的。",
     "forms":[F("emotion","n.","情绪"),F("emotionally","adv.","情绪上")]}},
  {"word":"commitment","phonetic":"kəˈmɪtmənt","pos":"n.","def":"承诺，投入；义务","cefr":"B2","freq_rank":36,
   "sentence_en":"Marriage is a big commitment.","sentence_zh":"婚姻是一项重大承诺。",
   "aids":{"morphemes":[M("com","prefix","完全"),M("mit","root","送，交付"),M("ment","suffix","名词后缀")],
     "derivation":"commit(投入、承诺)+ment → 投入承诺的状态 → 承诺、义务",
     "family":FAM("mit/miss","送、交付",[W("commit","投入"),W("submit","提交"),W("mission","任务")]),
     "mnemonic":"commit(把自己完全交付)的名词;许下并全力投入的责任,就是 commitment 承诺、投入。",
     "forms":[F("commit","v.","投入；承诺")]}},
  {"word":"stuff","phonetic":"stʌf","pos":"n./v.","def":"东西，物品；填塞","cefr":"A2","freq_rank":11,
   "sentence_en":"Put your stuff over there.","sentence_zh":"把你的东西放那边。",
   "aids":{"morphemes":[M("stuff","root","填料(古法语 estoffe 布料)")],
     "derivation":"古法语'布料、材料';泛指材料、东西;把料塞进去 → 填塞",
     "family":FAM("","相关词",[W("stuffing","填料"),W("stuffed","塞满的")]),
     "mnemonic":"stuff=材料/东西(口语泛指'玩意儿');把馅料塞进火鸡=stuff 填塞(stuffed 塞满的/吃撑的)。",
     "forms":[F("stuffed","adj.","塞满的"),F("stuffing","n.","填料")]}},
  {"word":"aware","phonetic":"əˈweə","pos":"adj.","def":"意识到的","cefr":"B1","freq_rank":21,
   "sentence_en":"I was not aware of that rule.","sentence_zh":"我没意识到那条规则。",
   "aids":{"morphemes":[M("a","prefix","加强"),M("ware","root","警觉")],
     "derivation":"a+ware(警觉) → 察知的 → 意识到的","family":FAM("ware","警觉",[W("beware","当心"),W("wary","谨慎的")]),
     "mnemonic":"ware=警觉;心里有数、察觉到,就是 aware。","forms":[F("awareness","n.","意识")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 8
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
