#!/usr/bin/env python
# 第十九批(约55词,冲过950收官本轮):逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -sol 松/单独
  {"word":"absolute","phonetic":"ˈæbsəluːt","pos":"adj.","def":"绝对的，完全的；专制的","cefr":"B2","freq_rank":90,
   "sentence_en":"That's an absolute lie.","sentence_zh":"那是彻头彻尾的谎言。",
   "aids":{"morphemes":[M("ab","prefix","离开"),M("solut","root","松开，解开"),M("e","suffix","结尾")],
     "derivation":"ab(离)+solut(松开) → 不受任何束缚的 → 绝对的",
     "family":FAM("solv/solu","松开、解开",[W("solve","解决"),W("solution","解决办法"),W("dissolve","溶解")]),
     "mnemonic":"solut=松开(和 solve 一家);挣脱一切限制、无条件的,就是 absolute 绝对的;absolutely 绝对地。",
     "forms":[F("absolutely","adv.","绝对地")]}},
  # -compan/-pan 面包(同伴)
  {"word":"accompany","phonetic":"əˈkʌmpəni","pos":"v.","def":"陪伴，伴随；为…伴奏","cefr":"B2","freq_rank":22,
   "sentence_en":"She accompanied him to the airport.","sentence_zh":"她陪他去了机场。",
   "aids":{"morphemes":[M("ac","prefix","朝向(ad 变体)"),M("compan","root","同伴"),M("y","suffix","动词后缀")],
     "derivation":"ac+compan(同伴) → 结伴而行 → 陪伴",
     "family":FAM("compan/pan","同伴、面包",[W("company","公司；陪伴"),W("companion","同伴")]),
     "mnemonic":"compan=同伴(和 company 一家,原义'分面包的人');作伴同行,就是 accompany 陪伴;伴随发生;为歌唱伴奏。",
     "forms":[F("accompanied","v.","过去式/过去分词")]}},
  # -migr 迁移
  {"word":"immigration","phonetic":"ˌɪmɪˈɡreɪʃən","pos":"n.","def":"移民，移居(入境)","cefr":"B2","freq_rank":21,
   "sentence_en":"Immigration has shaped this country.","sentence_zh":"移民塑造了这个国家。",
   "aids":{"morphemes":[M("im","prefix","向内(in)"),M("migr","root","迁移"),M("ation","suffix","名词后缀")],
     "derivation":"im(向内)+migr(迁移) → 迁入本国 → (入境)移民",
     "family":FAM("migr","迁移",[W("migrate","迁徙"),W("immigrant","移民"),W("emigrate","移居外国")]),
     "mnemonic":"migr=迁移(想 migrate);迁入(im-)本国,就是 immigration;迁出(e-)去=emigration,方向相反。",
     "forms":[F("immigrant","n.","移民")]}},
  # -stroy/-struct
  {"word":"stroke","phonetic":"strəʊk","pos":"n./v.","def":"击，划；中风；抚摸；一笔","cefr":"B2","freq_rank":80,
   "sentence_en":"He had a stroke last year.","sentence_zh":"他去年中风了。",
   "aids":{"morphemes":[M("stroke","root","打，击(strike)")],
     "derivation":"与 strike'打'同源;一击/一划 → 笔划、划水;脑血管'突袭'一击 → 中风",
     "family":FAM("strik/stroke","打、击",[W("strike","打击"),W("struck","击打(过去式)")]),
     "mnemonic":"stroke 与 strike(打)一家;一笔一划=a stroke;划水一下=stroke;脑血管突然一'击'=中风;轻轻抚摸也是 stroke。",
     "forms":[F("strokes","n.","笔划(复数)")]}},
  # -pel 推
  {"word":"delay","phonetic":"dɪˈleɪ","pos":"n./v.","def":"延迟，耽搁","cefr":"B1","freq_rank":79,
   "sentence_en":"The flight was delayed by two hours.","sentence_zh":"航班延误了两小时。",
   "aids":{"morphemes":[M("de","prefix","离，加强"),M("lay","root","放，留(laisser 放任)")],
     "derivation":"de+lay(放置、留) → 放着不办、拖后 → 延迟",
     "family":FAM("lay/lax","放、松",[W("relay","接力"),W("relax","放松")]),
     "mnemonic":"lay=放/留;把事往后一放、拖着,就是 delay 延迟;without delay 立即;delayed 延误的。",
     "forms":[F("delayed","adj.","延误的"),F("delays","n.","延误(复数)")]}},
  # 高频名词/动词(常见/词根)
  {"word":"pollution","phonetic":"pəˈluːʃən","pos":"n.","def":"污染","cefr":"B1","freq_rank":66,
   "sentence_en":"Air pollution is a serious problem.","sentence_zh":"空气污染是个严重问题。",
   "aids":{"morphemes":[M("pol","prefix","加强"),M("lut","root","泥，脏(luere)"),M("ion","suffix","名词后缀")],
     "derivation":"pollute(弄脏)+ion → 弄脏环境 → 污染",
     "family":FAM("lut","泥、脏",[W("pollute","污染"),W("dilute","稀释")]),
     "mnemonic":"lut=脏;把环境弄脏,就是 pollution 污染;动词 pollute;pollutant 污染物;water pollution 水污染。",
     "forms":[F("pollute","v.","污染"),F("pollutant","n.","污染物")]}},
  {"word":"assistant","phonetic":"əˈsɪstənt","pos":"n./adj.","def":"助手，助理；辅助的","cefr":"A2","freq_rank":54,
   "sentence_en":"She works as a personal assistant.","sentence_zh":"她做私人助理。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sist","root","站"),M("ant","suffix","…的人")],
     "derivation":"assist(站旁帮忙)+ant → 帮忙的人 → 助手",
     "family":FAM("sist","站",[W("assist","协助"),W("insist","坚持"),W("resist","抵抗"),W("consist","组成")]),
     "mnemonic":"sist=站(和 assist 一家);站你身旁搭手的人,就是 assistant 助手;shop assistant 店员;动词 assist。",
     "forms":[F("assistants","n.","助手(复数)")]}},
  {"word":"deficit","phonetic":"ˈdefɪsɪt","pos":"n.","def":"赤字，逆差；不足","cefr":"C1","freq_rank":18,
   "sentence_en":"The budget deficit grew.","sentence_zh":"预算赤字扩大了。",
   "aids":{"morphemes":[M("de","prefix","向下，缺"),M("fic","root","做"),M("it","suffix","结尾")],
     "derivation":"de(缺)+fic(做) → 做出来还差、亏空 → 赤字",
     "family":FAM("fic/fac","做、造",[W("deficient","不足的"),W("efficient","高效的"),W("effect","效果")]),
     "mnemonic":"fic=做(和 deficient 不足一家);账上'差'一块、亏空的,就是 deficit 赤字;trade deficit 贸易逆差;反义 surplus。",
     "forms":[F("deficient","adj.","不足的")]}},
  {"word":"personnel","phonetic":"ˌpɜːsəˈnel","pos":"n.","def":"(全体)人员；人事部门","cefr":"B2","freq_rank":19,
   "sentence_en":"All personnel must wear ID badges.","sentence_zh":"所有人员必须佩戴工牌。",
   "aids":{"morphemes":[M("person","root","人"),M("nel","suffix","名词后缀")],
     "derivation":"person(人)→ 一个机构的全体人 → 人员",
     "family":FAM("person","人",[W("person","人"),W("personal","个人的"),W("personality","个性")]),
     "mnemonic":"person=人(注意 personnel 双n,重音在后,别和 personal 混);一个组织的全体职员,就是 personnel 人员/人事。",
     "forms":[]}},
  {"word":"respondent","phonetic":"rɪˈspɒndənt","pos":"n.","def":"(调查)受访者；被告","cefr":"C1","freq_rank":30,
   "sentence_en":"Most respondents agreed.","sentence_zh":"大多数受访者表示同意。",
   "aids":{"morphemes":[M("re","prefix","回"),M("spond","root","承诺，回答"),M("ent","suffix","…的人")],
     "derivation":"respond(回答)+ent → 作出回答的人 → 受访者",
     "family":FAM("spond/spons","承诺、回答",[W("respond","回应"),W("response","回应"),W("responsible","负责的")]),
     "mnemonic":"spond=回答(和 respond 一家);在问卷/诉讼中作答的一方,就是 respondent 受访者/被告。",
     "forms":[F("respondents","n.","受访者(复数)")]}},
  {"word":"historian","phonetic":"hɪˈstɔːriən","pos":"n.","def":"历史学家","cefr":"B1","freq_rank":31,
   "sentence_en":"The historian wrote about ancient Rome.","sentence_zh":"这位历史学家研究古罗马。",
   "aids":{"morphemes":[M("histor","root","历史，探究"),M("ian","suffix","…的人")],
     "derivation":"histor(历史)+ian → 研究历史的人 → 历史学家",
     "family":FAM("histor","历史",[W("history","历史"),W("historic","历史性的"),W("historical","历史的")]),
     "mnemonic":"histor=历史(和 history 一家);专门研究历史的人,就是 historian;-ian 表'人'(如 musician)。",
     "forms":[F("historians","n.","历史学家(复数)")]}},
  {"word":"concert","phonetic":"ˈkɒnsət","pos":"n.","def":"音乐会，演奏会；一致","cefr":"A2","freq_rank":28,
   "sentence_en":"We went to a rock concert.","sentence_zh":"我们去了一场摇滚音乐会。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("cert","root","竞争，努力(certare)")],
     "derivation":"con(一起)+cert(努力) → 众人协力合奏 → 音乐会;协力一致 → 一致",
     "family":FAM("cert","竞争、努力",[W("certain","确定的"),W("concert","音乐会")]),
     "mnemonic":"con(一起)+cert(努力)——众乐手协力同台演奏,就是 concert 音乐会;in concert 一致地/联合。",
     "forms":[F("concerts","n.","音乐会(复数)")]}},
  {"word":"fiction","phonetic":"ˈfɪkʃən","pos":"n.","def":"小说；虚构，杜撰","cefr":"B1","freq_rank":59,
   "sentence_en":"She writes science fiction.","sentence_zh":"她写科幻小说。",
   "aids":{"morphemes":[M("fict","root","做，捏造(fingere)"),M("ion","suffix","名词后缀")],
     "derivation":"fict(捏造)+ion → 编造出来的故事 → 小说、虚构",
     "family":FAM("fict/fig","做、塑造",[W("figure","图形"),W("fictional","虚构的")]),
     "mnemonic":"fict=捏造(拉丁 fingere 塑);虚构编出的故事,就是 fiction 小说;反义 non-fiction 纪实;fictional 虚构的。",
     "forms":[F("fictional","adj.","虚构的")]}},
  {"word":"galaxy","phonetic":"ˈɡæləksi","pos":"n.","def":"星系，银河","cefr":"B2","freq_rank":71,
   "sentence_en":"Our galaxy is called the Milky Way.","sentence_zh":"我们的星系叫银河系。",
   "aids":{"morphemes":[M("galax","root","乳，奶(希腊 gala)"),M("y","suffix","名词后缀")],
     "derivation":"希腊 gala'奶'(银河似洒出的乳带,Milky Way);→ 星系、银河",
     "family":FAM("galact","乳",[W("galactic","星系的")]),
     "mnemonic":"galax=奶(希腊 gala,银河=Milky Way 奶路);由乳白光带引申的恒星系统,就是 galaxy 星系。",
     "forms":[F("galaxies","n.","星系(复数)")]}},
  {"word":"scandal","phonetic":"ˈskændl","pos":"n.","def":"丑闻；流言，反感","cefr":"B2","freq_rank":73,
   "sentence_en":"The scandal ruined his career.","sentence_zh":"这桩丑闻毁了他的事业。",
   "aids":{"morphemes":[M("scandal","root","绊脚石，陷阱(skandalon)")],
     "derivation":"希腊 skandalon'绊脚石';令人绊倒、蒙羞之事 → 丑闻",
     "family":FAM("","相关词",[W("scandalous","可耻的")]),
     "mnemonic":"scandal 原义'绊脚石';让人栽跟头、蒙羞的丑事,就是 scandal 丑闻;scandalous 骇人听闻的。",
     "forms":[F("scandals","n.","丑闻(复数)")]}},
  {"word":"horizon","phonetic":"həˈraɪzn","pos":"n.","def":"地平线；眼界，视野","cefr":"B2","freq_rank":81,
   "sentence_en":"The sun sank below the horizon.","sentence_zh":"太阳沉到地平线下。",
   "aids":{"morphemes":[M("horiz","root","界限，分界(horizein)"),M("on","suffix","结尾")],
     "derivation":"希腊 horizein'划界';天地相接的分界线 → 地平线;引申'眼界'",
     "family":FAM("","相关词",[W("horizontal","水平的")]),
     "mnemonic":"天地相接的那条界线=horizon 地平线;引申见识范围=眼界(broaden one's horizons 开阔眼界);horizontal 水平的。",
     "forms":[F("horizons","n.","眼界(复数)"),F("horizontal","adj.","水平的")]}},
  # 高频形容词/副词
  {"word":"brilliant","phonetic":"ˈbrɪliənt","pos":"adj.","def":"极好的；才华横溢的；明亮的","cefr":"B1","freq_rank":87,
   "sentence_en":"That's a brilliant idea.","sentence_zh":"这主意太棒了。",
   "aids":{"morphemes":[M("brill","root","闪耀，发光(beryllus 绿宝石)"),M("iant","suffix","…的")],
     "derivation":"brill(发光)+iant → 光彩夺目的 → 明亮的;引申'出色的、才华横溢的'",
     "family":FAM("","相关词",[W("brilliance","才华；光辉")]),
     "mnemonic":"brill=闪耀(源自绿宝石的光);光彩夺目=明亮的;才智'闪光'=才华横溢的;口语'太棒了'=brilliant!。",
     "forms":[F("brilliance","n.","才华；光辉")]}},
  {"word":"ongoing","phonetic":"ˈɒnɡəʊɪŋ","pos":"adj.","def":"持续进行的，不间断的","cefr":"B2","freq_rank":68,
   "sentence_en":"The investigation is ongoing.","sentence_zh":"调查正在进行中。",
   "aids":{"morphemes":[M("on","prefix","持续"),M("going","root","进行")],
     "derivation":"on(持续)+going(进行) → 一直进行着 → 持续进行的",
     "family":FAM("go","走、进行",[W("go","走"),W("undergoing","正在经历的")]),
     "mnemonic":"on(不停)+going(进行)——正在进行、还没结束的,就是 ongoing 持续进行的;ongoing process 持续过程。",
     "forms":[]}},
  {"word":"regardless","phonetic":"rɪˈɡɑːdləs","pos":"adv./adj.","def":"不管，不顾","cefr":"B2","freq_rank":64,
   "sentence_en":"We'll go regardless of the weather.","sentence_zh":"不管天气如何，我们都去。",
   "aids":{"morphemes":[M("regard","root","关注，理会"),M("less","suffix","无…的")],
     "derivation":"regard(理会)+less(无) → 不予理会 → 不管、不顾",
     "family":FAM("gard/guard","看守、关注",[W("regard","看待"),W("guard","守卫"),W("reward","奖赏")]),
     "mnemonic":"regard(理会)+less(无);对困难'不予理会'地照做,就是 regardless;regardless of=不管…。",
     "forms":[]}},
  {"word":"mainly","phonetic":"ˈmeɪnli","pos":"adv.","def":"主要地，大多","cefr":"B1","freq_rank":62,
   "sentence_en":"The audience was mainly students.","sentence_zh":"观众主要是学生。",
   "aids":{"morphemes":[M("main","root","主要的"),M("ly","suffix","…地")],
     "derivation":"main(主要的)+ly → 主要地",
     "family":FAM("main","主要",[W("main","主要的"),W("mainstream","主流")]),
     "mnemonic":"main=主要(想 mainstream 主流);占大头、主要来说,就是 mainly;=mostly/chiefly。",
     "forms":[F("main","adj.","主要的")]}},
  {"word":"naturally","phonetic":"ˈnætʃrəli","pos":"adv.","def":"自然地；天生地；当然","cefr":"A2","freq_rank":61,
   "sentence_en":"Naturally, she was upset.","sentence_zh":"她自然是不高兴了。",
   "aids":{"morphemes":[M("natur","root","自然，出生"),M("ally","suffix","…地")],
     "derivation":"natural(自然的)+ly → 出于本性/理所当然地 → 自然地",
     "family":FAM("nat","出生、自然",[W("nature","自然"),W("natural","自然的"),W("native","本地的")]),
     "mnemonic":"和 nature/natural 一家(nat 出生);顺其本性、理所当然地,就是 naturally 自然地/当然。",
     "forms":[F("natural","adj.","自然的")]}},
  {"word":"briefly","phonetic":"ˈbriːfli","pos":"adv.","def":"简短地；短暂地","cefr":"B1","freq_rank":69,
   "sentence_en":"Let me explain briefly.","sentence_zh":"让我简短说明一下。",
   "aids":{"morphemes":[M("brief","root","短"),M("ly","suffix","…地")],
     "derivation":"brief(简短的)+ly → 简短地",
     "family":FAM("brev/brief","短",[W("brief","简短的"),W("abbreviate","缩写")]),
     "mnemonic":"brief=短(想 abbreviate 缩短);简明扼要地/短暂地,就是 briefly;briefly speaking 简言之。",
     "forms":[F("brief","adj.","简短的")]}},
  {"word":"historic","phonetic":"hɪˈstɒrɪk","pos":"adj.","def":"具有历史意义的，历史性的","cefr":"B2","freq_rank":26,
   "sentence_en":"It was a historic moment.","sentence_zh":"那是个历史性时刻。",
   "aids":{"morphemes":[M("histor","root","历史"),M("ic","suffix","…的")],
     "derivation":"histor(历史)+ic → 载入史册的 → 历史性的",
     "family":FAM("histor","历史",[W("history","历史"),W("historian","历史学家"),W("historical","历史的")]),
     "mnemonic":"histor=历史;区分:historic=有历史意义的(重大);historical=历史上的/关于历史的(a historical novel)。",
     "forms":[F("historical","adj.","历史的")]}},
  {"word":"biological","phonetic":"ˌbaɪəˈlɒdʒɪkl","pos":"adj.","def":"生物的，生物学的","cefr":"B2","freq_rank":33,
   "sentence_en":"They study biological processes.","sentence_zh":"他们研究生物过程。",
   "aids":{"morphemes":[M("bio","root","生命"),M("log","root","学问，说"),M("ical","suffix","…的")],
     "derivation":"bio(生命)+log(学问) → 关于生命科学的 → 生物学的",
     "family":FAM("bio","生命",[W("biology","生物学"),W("biography","传记"),W("antibiotic","抗生素")]),
     "mnemonic":"bio=生命(想 biology 生物学)+log(学);与生物、生命科学有关的,就是 biological;biology 生物学。",
     "forms":[F("biology","n.","生物学")]}},
  {"word":"clinical","phonetic":"ˈklɪnɪkl","pos":"adj.","def":"临床的；冷静客观的","cefr":"B2","freq_rank":37,
   "sentence_en":"The drug is in clinical trials.","sentence_zh":"这种药正在临床试验中。",
   "aids":{"morphemes":[M("clin","root","床，倾斜(kline)"),M("ical","suffix","…的")],
     "derivation":"clin(床)+ical → 病床边的、实地诊治的 → 临床的",
     "family":FAM("clin","床、倾斜",[W("clinic","诊所"),W("incline","倾斜"),W("recline","斜倚")]),
     "mnemonic":"clin=床(病床;和 clinic 诊所一家);在病床边实际诊治的,就是 clinical;clinical trial 临床试验。",
     "forms":[F("clinic","n.","诊所")]}},
  # 常见名词(实义)
  {"word":"missile","phonetic":"ˈmɪsaɪl","pos":"n.","def":"导弹，飞弹；投射物","cefr":"B2","freq_rank":13,
   "sentence_en":"The missile hit its target.","sentence_zh":"导弹击中了目标。",
   "aids":{"morphemes":[M("miss","root","送，投"),M("ile","suffix","可…的")],
     "derivation":"miss(投)+ile → 可投射发射的东西 → 导弹",
     "family":FAM("mit/miss","送、投",[W("submit","提交"),W("emit","发出"),W("mission","任务"),W("transmit","传送")]),
     "mnemonic":"miss=投(和 emit 发出一家);能发射投出去打击目标的,就是 missile 导弹;guided missile 制导导弹。",
     "forms":[F("missiles","n.","导弹(复数)")]}},
  {"word":"telescope","phonetic":"ˈtelɪskəʊp","pos":"n.","def":"望远镜","cefr":"B1","freq_rank":58,
   "sentence_en":"He looked at the stars through a telescope.","sentence_zh":"他用望远镜看星星。",
   "aids":{"morphemes":[M("tele","prefix","远"),M("scop","root","看"),M("e","suffix","结尾")],
     "derivation":"tele(远)+scop(看) → 看远处的仪器 → 望远镜",
     "family":FAM("scop","看",[W("microscope","显微镜"),W("scope","范围"),W("telephone","电话")]),
     "mnemonic":"tele(远,想 telephone 电话)+scop(看)——看远方的仪器,就是 telescope 望远镜;看微小的=microscope 显微镜。",
     "forms":[F("telescopes","n.","望远镜(复数)")]}},
  {"word":"chamber","phonetic":"ˈtʃeɪmbə","pos":"n.","def":"室，房间；(身体/器官的)腔；议院","cefr":"B2","freq_rank":50,
   "sentence_en":"The heart has four chambers.","sentence_zh":"心脏有四个腔。",
   "aids":{"morphemes":[M("chamber","root","房间(camera 拱室)")],
     "derivation":"拉丁 camera'拱顶房间';封闭的室 → 房间、腔",
     "family":FAM("camer/chamber","房间",[W("camera","相机(暗室)"),W("comrade","同志(同住)")]),
     "mnemonic":"chamber 与 camera(暗室)同源;封闭的室=房间/腔(heart chamber 心腔);立法'议院'=chamber(the lower chamber)。",
     "forms":[F("chambers","n.","室(复数)")]}},
  {"word":"furniture","phonetic":"ˈfɜːnɪtʃə","pos":"n.","def":"家具(总称)","cefr":"A2","freq_rank":51,
   "sentence_en":"We bought new furniture.","sentence_zh":"我们买了新家具。",
   "aids":{"morphemes":[M("furnish","root","供应，装备"),M("ture","suffix","名词后缀")],
     "derivation":"furnish(布置、供应)+ture → 布置房间的用具 → 家具",
     "family":FAM("furn","供应、装备",[W("furnish","布置")]),
     "mnemonic":"和 furnish(布置房间)一家;摆设房间的桌椅床柜,就是 furniture(不可数,a piece of furniture 一件家具)。",
     "forms":[]}},
  {"word":"nerve","phonetic":"nɜːv","pos":"n.","def":"神经；勇气，胆量","cefr":"B2","freq_rank":75,
   "sentence_en":"It takes nerve to speak in public.","sentence_zh":"当众讲话需要勇气。",
   "aids":{"morphemes":[M("nerv","root","筋，神经(nervus)"),M("e","suffix","结尾")],
     "derivation":"拉丁 nervus'筋、腱';传导感觉的组织 → 神经;引申'胆量'",
     "family":FAM("nerv","神经、筋",[W("nervous","紧张的"),W("nerve-racking","令人紧张的")]),
     "mnemonic":"nerv=神经(想 nervous 紧张的);传导信号的神经;引申'钢筋般的胆量'=勇气(have the nerve to);get on one's nerves 惹恼。",
     "forms":[F("nervous","adj.","紧张的"),F("nerves","n.","神经(复数)")]}},
  {"word":"trick","phonetic":"trɪk","pos":"n./v.","def":"诡计，花招；戏法；诀窍；欺骗","cefr":"B1","freq_rank":74,
   "sentence_en":"He played a trick on me.","sentence_zh":"他捉弄了我。",
   "aids":{"morphemes":[M("trick","root","欺骗，花招(古法语 trique)")],
     "derivation":"古法语'欺诈、花招';耍手段 → 诡计、戏法",
     "family":FAM("","相关词",[W("tricky","棘手的"),W("trickster","骗子")]),
     "mnemonic":"trick=花招;骗人的诡计/魔术戏法/窍门都是 trick;trick sb into 骗某人做;tricky 棘手的;do the trick 奏效。",
     "forms":[F("tricks","n.","诡计(复数)"),F("tricky","adj.","棘手的")]}},
  {"word":"load","phonetic":"ləʊd","pos":"n./v.","def":"负荷，负载；装载；(计算机)载入","cefr":"B1","freq_rank":65,
   "sentence_en":"The truck carried a heavy load.","sentence_zh":"卡车载着沉重的货物。",
   "aids":{"morphemes":[M("load","root","负担(古英语 lād 路，运载)")],
     "derivation":"古英语'运载、担子';装上的重物/工作量 → 负荷;把货装上 → 装载",
     "family":FAM("","相关词",[W("upload","上传"),W("download","下载"),W("overload","超载")]),
     "mnemonic":"load=装载/负担;车上的货=load;工作量=workload;把货装上/把程序调入=load;download 下载。",
     "forms":[F("loaded","adj.","装满的"),F("loads","n.","负荷(复数)")]}},
  {"word":"tube","phonetic":"tjuːb","pos":"n.","def":"管，管子；(伦敦)地铁；电子管","cefr":"A2","freq_rank":29,
   "sentence_en":"A tube of toothpaste.","sentence_zh":"一管牙膏。",
   "aids":{"morphemes":[M("tube","root","管(tubus)")],
     "derivation":"拉丁 tubus'管';中空的长管 → 管子",
     "family":FAM("tub","管",[W("tubular","管状的"),W("tubing","管道")]),
     "mnemonic":"tube=管;中空的管子(a tube of=一管);伦敦地铁俗称 the Tube(隧道管);test tube 试管。",
     "forms":[F("tubes","n.","管子(复数)")]}},
  {"word":"shell","phonetic":"ʃel","pos":"n./v.","def":"壳，贝壳；外形，框架；炮弹","cefr":"B1","freq_rank":32,
   "sentence_en":"The turtle hid in its shell.","sentence_zh":"乌龟躲进了壳里。",
   "aids":{"morphemes":[M("shell","root","壳(古英语 scell)")],
     "derivation":"古英语'外壳';坚硬的外层 → 壳;中空外壳般的弹 → 炮弹",
     "family":FAM("shell/scale","壳、片",[W("shellfish","贝类")]),
     "mnemonic":"shell=壳;贝壳/蛋壳/坚果壳都是 shell;建筑的外'壳'=框架;打出去的空心'壳'=炮弹;剥壳=shell。",
     "forms":[F("shells","n.","壳(复数)")]}},
  {"word":"belt","phonetic":"belt","pos":"n.","def":"腰带，带子；地带","cefr":"A2","freq_rank":20,
   "sentence_en":"Fasten your seat belt.","sentence_zh":"系好安全带。",
   "aids":{"morphemes":[M("belt","root","带(古英语 belt)")],
     "derivation":"古英语'带';束在腰上的带 → 腰带;条状区域 → 地带",
     "family":FAM("","相关词",[W("seatbelt","安全带")]),
     "mnemonic":"belt=带;系腰的=腰带;车上的=安全带(seat belt);一条区域=地带(the Rust Belt 铁锈地带)。",
     "forms":[F("belts","n.","带子(复数)")]}},
  {"word":"gear","phonetic":"ɡɪə","pos":"n./v.","def":"齿轮，排挡；装备，用具；使适合","cefr":"B2","freq_rank":41,
   "sentence_en":"Put the car into first gear.","sentence_zh":"把车挂到一挡。",
   "aids":{"morphemes":[M("gear","root","装备(古诺斯语 gervi)")],
     "derivation":"古诺斯语'装备';传动的齿轮/一套用具 → 齿轮、装备",
     "family":FAM("","相关词",[W("gearbox","变速箱")]),
     "mnemonic":"gear=齿轮/装备;传动齿轮、汽车排挡=gear;做某事的整套用具=gear(camping gear 露营装备);gear...to 使适合。",
     "forms":[F("gears","n.","齿轮(复数)"),F("geared","v.","过去式/过去分词")]}},
  {"word":"crack","phonetic":"kræk","pos":"n./v.","def":"裂缝；破裂声；(使)裂开；破解","cefr":"B1","freq_rank":70,
   "sentence_en":"There's a crack in the wall.","sentence_zh":"墙上有条裂缝。",
   "aids":{"morphemes":[M("crack","root","裂开，爆响(拟声)")],
     "derivation":"拟声'咔嚓裂开';裂开/爆响 → 裂缝、破裂声",
     "family":FAM("","相关词",[W("cracker","饼干；爆竹")]),
     "mnemonic":"crack=咔嚓裂;墙的裂缝、鞭子的爆响都是 crack;把难题/密码'攻破'=crack(crack a code);crack down on 严打。",
     "forms":[F("cracked","v.","过去式/过去分词"),F("cracks","n.","裂缝(复数)")]}},
  {"word":"blade","phonetic":"bleɪd","pos":"n.","def":"刀刃，刀片；(草)叶片；桨叶","cefr":"B2","freq_rank":84,
   "sentence_en":"The knife has a sharp blade.","sentence_zh":"这把刀刀刃很锋利。",
   "aids":{"morphemes":[M("blade","root","叶，刃(古英语 blæd)")],
     "derivation":"古英语'叶片';扁平锋利的部分 → 刀刃、叶片",
     "family":FAM("","相关词",[W("shoulder blade","肩胛骨")]),
     "mnemonic":"blade=扁平的刃/叶;刀的锋利部分=刀刃;一片草叶=a blade of grass;螺旋桨/风扇的桨叶=blade。",
     "forms":[F("blades","n.","刀刃(复数)")]}},
  {"word":"pitch","phonetic":"pɪtʃ","pos":"n./v.","def":"球场；音高；(推销)说辞；投掷；搭(帐篷)","cefr":"B2","freq_rank":85,
   "sentence_en":"The players ran onto the pitch.","sentence_zh":"球员们跑进球场。",
   "aids":{"morphemes":[M("pitch","root","投，钉(中古英语 picchen)")],
     "derivation":"中古英语'钉入、投';投掷/定点 → 投;定下音的高低 → 音高;划定的场地 → 球场",
     "family":FAM("","相关词",[W("pitcher","投手")]),
     "mnemonic":"pitch 多义:划定的运动场=球场;声音高低=音高;投球=pitch(pitcher 投手);搭帐篷=pitch a tent;推销说辞=sales pitch。",
     "forms":[F("pitches","n.","球场(复数)"),F("pitched","v.","过去式/过去分词")]}},
  {"word":"glove","phonetic":"ɡlʌv","pos":"n.","def":"手套","cefr":"A2","freq_rank":77,
   "sentence_en":"Wear gloves in the cold.","sentence_zh":"天冷戴手套。",
   "aids":{"morphemes":[M("glove","root","手套(古英语 glōf)")],
     "derivation":"古英语'手套';套在手上分指的织物 → 手套",
     "family":FAM("","相关词",[W("glover","手套匠")]),
     "mnemonic":"glove=手套(分指的,连指的叫 mitten);保暖/防护戴的=gloves;fit like a glove 非常合身;boxing gloves 拳套。",
     "forms":[F("gloves","n.","手套(复数)")]}},
  {"word":"barrel","phonetic":"ˈbærəl","pos":"n.","def":"桶；(枪)管；一桶的量","cefr":"B2","freq_rank":76,
   "sentence_en":"A barrel of oil.","sentence_zh":"一桶石油。",
   "aids":{"morphemes":[M("barr","root","棒，条(bar)"),M("el","suffix","小")],
     "derivation":"与 bar(条/棒)相关;木条箍成的圆桶 → 桶",
     "family":FAM("bar","棒、条",[W("bar","棒；栏"),W("barrier","屏障")]),
     "mnemonic":"barr=木条(和 bar 一家);木条箍成的大圆桶=barrel;石油计量单位'桶';枪的'管'也叫 barrel。",
     "forms":[F("barrels","n.","桶(复数)")]}},
  {"word":"helicopter","phonetic":"ˈhelɪkɒptə","pos":"n.","def":"直升机","cefr":"B1","freq_rank":78,
   "sentence_en":"A helicopter flew overhead.","sentence_zh":"一架直升机从头顶飞过。",
   "aids":{"morphemes":[M("helico","root","螺旋(helix)"),M("pter","root","翅膀(希腊 pteron)")],
     "derivation":"helico(螺旋)+pter(翅膀) → 螺旋翼飞行器 → 直升机",
     "family":FAM("pter","翅膀",[W("pterodactyl","翼手龙")]),
     "mnemonic":"helico=螺旋(想 helix 螺旋)+pter(翅膀,想 pterodactyl 翼龙);靠螺旋桨翼升降的,就是 helicopter 直升机(口语 chopper)。",
     "forms":[F("helicopters","n.","直升机(复数)")]}},
  {"word":"leather","phonetic":"ˈleðə","pos":"n.","def":"皮革，皮制品","cefr":"B1","freq_rank":67,
   "sentence_en":"She wore a leather jacket.","sentence_zh":"她穿着皮夹克。",
   "aids":{"morphemes":[M("leather","root","皮革(古英语 leþer)")],
     "derivation":"古英语'兽皮';鞣制过的兽皮 → 皮革",
     "family":FAM("","相关词",[W("leathery","皮革般的")]),
     "mnemonic":"leather=皮革;鞣制的兽皮做的东西=leather(genuine leather 真皮);leather shoes 皮鞋;leathery 皮革般粗硬的。",
     "forms":[]}},
  {"word":"silver","phonetic":"ˈsɪlvə","pos":"n./adj.","def":"银；银器；银色的","cefr":"A2","freq_rank":23,
   "sentence_en":"She won a silver medal.","sentence_zh":"她赢得了银牌。",
   "aids":{"morphemes":[M("silver","root","银(古英语 seolfor)")],
     "derivation":"古英语'银';贵金属银 → 银;银色 → 银色的",
     "family":FAM("","相关词",[W("silverware","银器")]),
     "mnemonic":"silver=银;金属银/银币/银器=silver;第二名的=银牌 silver medal;银白色的=silver;silverware 银餐具。",
     "forms":[F("silvery","adj.","银色的")]}},
  {"word":"pregnant","phonetic":"ˈpreɡnənt","pos":"adj.","def":"怀孕的；意味深长的","cefr":"B1","freq_rank":46,
   "sentence_en":"She is six months pregnant.","sentence_zh":"她怀孕六个月了。",
   "aids":{"morphemes":[M("pre","prefix","在前，预先"),M("gn","root","生(gen)"),M("ant","suffix","…的")],
     "derivation":"pre(预先)+gn(生) → 即将生育的 → 怀孕的",
     "family":FAM("gen/gn","产生、生",[W("generate","产生"),W("gene","基因"),W("native","天生的")]),
     "mnemonic":"gn=生(和 generate 一家);肚里孕育着即将出生的生命,就是 pregnant 怀孕的;pregnancy 怀孕。",
     "forms":[F("pregnancy","n.","怀孕")]}},
  {"word":"snap","phonetic":"snæp","pos":"v./n.","def":"啪地折断；猛咬；抢购；(拍)快照；厉声说","cefr":"B2","freq_rank":40,
   "sentence_en":"The branch snapped.","sentence_zh":"树枝啪地断了。",
   "aids":{"morphemes":[M("snap","root","啪地咬/断(拟声)")],
     "derivation":"拟声'啪';突然咔嚓折断/咬 → 折断、猛咬",
     "family":FAM("","相关词",[W("snapshot","快照")]),
     "mnemonic":"snap=啪地一下;树枝啪断/狗猛咬/情绪突然爆发厉声说,都是 snap;抢购=snap up;拍快照=snapshot。",
     "forms":[F("snapped","v.","过去式/过去分词")]}},
  {"word":"wage","phonetic":"weɪdʒ","pos":"n./v.","def":"工资(尤指周薪)；发动(战争等)","cefr":"B1","freq_rank":38,
   "sentence_en":"They demanded higher wages.","sentence_zh":"他们要求提高工资。",
   "aids":{"morphemes":[M("wage","root","抵押，报酬(gage)")],
     "derivation":"与 gage/wed'抵押、担保'相关;付给劳动的报酬 → 工资;'投入、担保去做'→ 发动",
     "family":FAM("wag/gage","担保、抵押",[W("engage","从事"),W("mortgage","抵押贷款")]),
     "mnemonic":"wage 与 gage(担保)相关;按劳付的报酬(尤周薪)=wages;'投入'去打=wage war 发动战争。",
     "forms":[F("wages","n.","工资(复数)")]}},
  {"word":"stake","phonetic":"steɪk","pos":"n./v.","def":"股份，利害关系；赌注；桩；以…打赌","cefr":"C1","freq_rank":39,
   "sentence_en":"Their lives are at stake.","sentence_zh":"他们的性命危在旦夕。",
   "aids":{"morphemes":[M("stake","root","桩(古英语 staca)")],
     "derivation":"古英语'木桩';打桩圈地→有份额/利害;下注押的钱→赌注",
     "family":FAM("st/stake","站、桩",[W("stack","堆")]),
     "mnemonic":"stake=木桩;打桩圈占→有份额(a stake in the company 股份/利害);赌桌押的钱=赌注;at stake 危如累卵;stakeholder 利益相关者。",
     "forms":[F("stakes","n.","股份；赌注(复数)")]}},
  {"word":"bury","phonetic":"ˈberi","pos":"v.","def":"埋葬，掩埋；埋藏","cefr":"B1","freq_rank":17,
   "sentence_en":"They buried the treasure.","sentence_zh":"他们把宝藏埋了起来。",
   "aids":{"morphemes":[M("bury","root","埋(古英语 byrgan)")],
     "derivation":"古英语'藏、埋';盖上土/藏起 → 埋葬、埋藏",
     "family":FAM("bur","藏、堡",[W("burial","埋葬")]),
     "mnemonic":"bury=埋(注意读 /ˈberi/ 同 berry);把死者/东西盖土藏起,就是 bury;burial 葬礼;bury oneself in 埋头于。",
     "forms":[F("buried","v.","过去式/过去分词"),F("burial","n.","埋葬")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 19
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
