#!/usr/bin/env python
# 第十五批(约50词):逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -ced 走
  {"word":"proceed","phonetic":"prəˈsiːd","pos":"v.","def":"继续进行；行进","cefr":"B2","freq_rank":83,
   "sentence_en":"Please proceed to the next question.","sentence_zh":"请继续下一题。",
   "aids":{"morphemes":[M("pro","prefix","向前"),M("ceed","root","走")],
     "derivation":"pro(向前)+ceed(走) → 向前走下去 → 继续进行",
     "family":FAM("ceed/cess","走",[W("process","过程"),W("exceed","超过"),W("succeed","成功"),W("access","通道")]),
     "mnemonic":"ceed=走(和 process 一家);向前(pro-)走下去,就是 proceed 继续进行;proceeds(n.)收益。",
     "forms":[F("procedure","n.","程序"),F("proceeding","n.","议程")]}},
  # -put 想/算
  {"word":"dispute","phonetic":"dɪˈspjuːt","pos":"n./v.","def":"争论，争端；质疑","cefr":"B2","freq_rank":86,
   "sentence_en":"The two countries have a border dispute.","sentence_zh":"两国有边界争端。",
   "aids":{"morphemes":[M("dis","prefix","分开，相反"),M("pute","root","想，认为")],
     "derivation":"dis(相反)+pute(想) → 各想各的、意见相左 → 争论",
     "family":FAM("put","想、算",[W("compute","计算"),W("reputation","名声"),W("deputy","代理人")]),
     "mnemonic":"pute=想(想 compute 计算);各执己见、想法对立,就是 dispute 争论;质疑其真实性也用 dispute。",
     "forms":[F("disputed","adj.","有争议的"),F("disputes","n.","争端(复数)")]}},
  # -pand 展
  {"word":"expansion","phonetic":"ɪkˈspænʃən","pos":"n.","def":"扩张，膨胀；扩展","cefr":"B2","freq_rank":99,
   "sentence_en":"The company's expansion created jobs.","sentence_zh":"公司的扩张创造了就业。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("pans","root","展开"),M("ion","suffix","名词后缀")],
     "derivation":"expand(向外展开)+ion → 扩大的过程 → 扩张",
     "family":FAM("pand/pans","展开",[W("expand","扩大"),W("expanse","广阔")]),
     "mnemonic":"pans=展开(和 expand 一家);向外铺展变大,就是 expansion 扩张;反义 contraction 收缩。",
     "forms":[F("expand","v.","扩大")]}},
  # -pret 说明
  {"word":"interpret","phonetic":"ɪnˈtɜːprɪt","pos":"v.","def":"解释，理解；口译","cefr":"B2","freq_rank":109,
   "sentence_en":"How do you interpret this poem?","sentence_zh":"你怎么理解这首诗？",
   "aids":{"morphemes":[M("inter","prefix","在…之间"),M("pret","root","说明")],
     "derivation":"inter(之间)+pret(说明) → 在双方之间说明 → 解释、口译",
     "family":FAM("pret","说明",[W("interpretation","解释"),W("interpreter","口译员")]),
     "mnemonic":"在双方之间(inter-)牵线说明,就是 interpret 解释/口译;interpreter 口译员;interpretation 解读。",
     "forms":[F("interpretation","n.","解释"),F("interpreter","n.","口译员")]}},
  # -lat 带
  {"word":"translate","phonetic":"trænsˈleɪt","pos":"v.","def":"翻译；转化","cefr":"B1","freq_rank":97,
   "sentence_en":"Can you translate this into English?","sentence_zh":"你能把这个翻译成英文吗？",
   "aids":{"morphemes":[M("trans","prefix","跨越"),M("lat","root","带")],
     "derivation":"trans(跨越)+lat(带) → 跨语言带过去 → 翻译",
     "family":FAM("lat","带、拿",[W("relate","使有联系"),W("relative","亲属"),W("collate","校对")]),
     "mnemonic":"lat=带(想 relate);把意思跨(trans-)语言带过去,就是 translate 翻译;translation 翻译;translator 译者。",
     "forms":[F("translation","n.","翻译"),F("translator","n.","译者")]}},
  # -tain 持
  {"word":"retain","phonetic":"rɪˈteɪn","pos":"v.","def":"保持，保留；记住","cefr":"B2","freq_rank":94,
   "sentence_en":"The soil retains water well.","sentence_zh":"这种土壤保水性好。",
   "aids":{"morphemes":[M("re","prefix","回，back"),M("tain","root","拿，持")],
     "derivation":"re(往回)+tain(持) → 往回把住、留着 → 保持",
     "family":FAM("tain/ten","拿、持",[W("contain","包含"),W("maintain","维持"),W("obtain","获得"),W("sustain","支撑")]),
     "mnemonic":"tain=持(和 contain 一家);往回(re-)攥住不放,就是 retain 保持、保留;retention 保持。",
     "forms":[F("retention","n.","保持，保留")]}},
  # -struct 建
  {"word":"destruction","phonetic":"dɪˈstrʌkʃən","pos":"n.","def":"破坏，毁灭","cefr":"B2","freq_rank":81,
   "sentence_en":"The storm caused massive destruction.","sentence_zh":"这场风暴造成了巨大破坏。",
   "aids":{"morphemes":[M("de","prefix","向下，去除"),M("struct","root","建，堆叠"),M("ion","suffix","名词后缀")],
     "derivation":"de(去除)+struct(建) → 把建起来的拆毁 → 破坏",
     "family":FAM("struct","建、堆叠",[W("construct","建造"),W("structure","结构"),W("instruct","指导"),W("destroy","摧毁")]),
     "mnemonic":"struct=建(反义想 construct 建造);把搭好的往下(de-)拆掉,就是 destruction 破坏;动词 destroy。",
     "forms":[F("destroy","v.","摧毁"),F("destructive","adj.","破坏性的")]}},
  # -fect 做
  {"word":"infection","phonetic":"ɪnˈfekʃən","pos":"n.","def":"感染，传染(病)","cefr":"B2","freq_rank":82,
   "sentence_en":"The wound got an infection.","sentence_zh":"伤口感染了。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("fect","root","做"),M("ion","suffix","名词后缀")],
     "derivation":"in(向内)+fect(做) → 病菌钻进体内作乱 → 感染",
     "family":FAM("fect/fac","做、造",[W("affect","影响"),W("effect","效果"),W("infect","传染"),W("perfect","完美的")]),
     "mnemonic":"fect=做(和 affect 一家);病菌钻进(in-)体内'作'乱,就是 infection 感染;动词 infect;infectious 传染性的。",
     "forms":[F("infect","v.","传染"),F("infectious","adj.","传染性的")]}},
  # -cap 拿
  {"word":"occupy","phonetic":"ˈɒkjupaɪ","pos":"v.","def":"占据，占用；占领；使忙碌","cefr":"B2","freq_rank":91,
   "sentence_en":"The bed occupies half the room.","sentence_zh":"这张床占了半个房间。",
   "aids":{"morphemes":[M("oc","prefix","朝向(ob)"),M("cup","root","拿(cap)"),M("y","suffix","动词后缀")],
     "derivation":"oc(朝向)+cup(拿) → 拿住、占住 → 占据",
     "family":FAM("cap/cup","拿、抓",[W("capture","捕获"),W("capable","有能力的"),W("accept","接受")]),
     "mnemonic":"cup=拿(cap 家族);把空间/时间'拿'住占着,就是 occupy 占据;occupation 职业/占领;occupied 被占用的。",
     "forms":[F("occupation","n.","职业；占领"),F("occupied","adj.","被占用的")]}},
  # -contra 对
  {"word":"encounter","phonetic":"ɪnˈkaʊntə","pos":"v./n.","def":"遭遇，偶遇；遇到(困难)","cefr":"B2","freq_rank":92,
   "sentence_en":"We encountered many problems.","sentence_zh":"我们遇到了许多问题。",
   "aids":{"morphemes":[M("en","prefix","使处于"),M("counter","root","对着，反(contra)")],
     "derivation":"en(使)+counter(对着) → 迎面碰上 → 遭遇",
     "family":FAM("counter/contra","对着、反",[W("counter","柜台；反击"),W("contrary","相反的"),W("contrast","对比")]),
     "mnemonic":"counter=对着(想 counter 反击);迎面(en-)撞上人或麻烦,就是 encounter 遭遇、偶遇。",
     "forms":[F("encounters","n.","遭遇(复数)"),F("encountered","v.","过去式/过去分词")]}},
  # -come 来
  {"word":"overcome","phonetic":"ˌəʊvəˈkʌm","pos":"v.","def":"克服，战胜；(情绪)压倒","cefr":"B2","freq_rank":88,
   "sentence_en":"She overcame her fear of heights.","sentence_zh":"她克服了恐高。",
   "aids":{"morphemes":[M("over","prefix","越过，压过"),M("come","root","来")],
     "derivation":"over(压过)+come → 压过、越过障碍 → 克服",
     "family":FAM("come","来",[W("income","收入"),W("outcome","结果"),W("welcome","欢迎")]),
     "mnemonic":"over(压过)+come——从困难上'压'过去、越过它,就是 overcome 克服(不规则:overcame/overcome)。",
     "forms":[F("overcame","v.","过去式"),F("overcoming","v.","现在分词")]}},
  # -mark 记号
  {"word":"remarkable","phonetic":"rɪˈmɑːkəbl","pos":"adj.","def":"非凡的，显著的，引人注目的","cefr":"B2","freq_rank":89,
   "sentence_en":"She made remarkable progress.","sentence_zh":"她取得了显著进步。",
   "aids":{"morphemes":[M("re","prefix","再，加强"),M("mark","root","记号，注意"),M("able","suffix","值得…的")],
     "derivation":"re(加强)+mark(注意)+able → 值得一再注目的 → 非凡的",
     "family":FAM("mark","记号、注意",[W("mark","标记"),W("remark","评论"),W("marker","标记物")]),
     "mnemonic":"mark=注意(和 remark 评说一家);好到值得反复注目、议论,就是 remarkable 非凡的;remarkably 显著地。",
     "forms":[F("remarkably","adv.","显著地"),F("remark","n.","评论")]}},
  # -bound 边界
  {"word":"boundary","phonetic":"ˈbaʊndri","pos":"n.","def":"边界，分界线","cefr":"B2","freq_rank":118,
   "sentence_en":"The river forms the boundary.","sentence_zh":"这条河形成了边界。",
   "aids":{"morphemes":[M("bound","root","界限，限制"),M("ary","suffix","名词后缀")],
     "derivation":"bound(界限)+ary → 划界的线 → 边界",
     "family":FAM("bound","界限",[W("bound","界限；范围"),W("boundless","无边的")]),
     "mnemonic":"bound=界限;划出范围的那条线,就是 boundary 边界;out of bounds 禁区;boundless 无边的。",
     "forms":[F("boundaries","n.","边界(复数)")]}},
  # -mot 动
  {"word":"remote","phonetic":"rɪˈməʊt","pos":"adj.","def":"遥远的，偏远的；疏远的；遥控的","cefr":"B2","freq_rank":119,
   "sentence_en":"They live in a remote village.","sentence_zh":"他们住在偏远的村子。",
   "aids":{"morphemes":[M("re","prefix","向后，离"),M("mote","root","动(mov)")],
     "derivation":"re(离)+mote(动) → 移开老远 → 遥远的",
     "family":FAM("mot/mov","动",[W("move","移动"),W("motion","运动"),W("promote","促进"),W("remove","移开")]),
     "mnemonic":"mote=动(和 move 一家);挪(re-)得老远的,就是 remote 遥远的;remote control 遥控器;remotely 遥远地。",
     "forms":[F("remotely","adv.","遥远地；丝毫")]}},
  # -oper 工作
  {"word":"cooperation","phonetic":"kəʊˌɒpəˈreɪʃən","pos":"n.","def":"合作，协作","cefr":"B2","freq_rank":72,
   "sentence_en":"Thank you for your cooperation.","sentence_zh":"感谢您的配合。",
   "aids":{"morphemes":[M("co","prefix","一起"),M("oper","root","工作"),M("ation","suffix","名词后缀")],
     "derivation":"co(一起)+oper(工作) → 一起干活 → 合作",
     "family":FAM("oper","工作",[W("operate","操作"),W("operation","运作"),W("cooperate","合作")]),
     "mnemonic":"oper=工作(和 operate 一家);大家一起(co-)干活配合,就是 cooperation 合作;动词 cooperate。",
     "forms":[F("cooperate","v.","合作"),F("cooperative","adj.","合作的")]}},
  # -volu 卷
  {"word":"revolution","phonetic":"ˌrevəˈluːʃən","pos":"n.","def":"革命，变革；旋转","cefr":"B2","freq_rank":107,
   "sentence_en":"The Industrial Revolution changed society.","sentence_zh":"工业革命改变了社会。",
   "aids":{"morphemes":[M("re","prefix","再，反"),M("volu","root","卷，转"),M("tion","suffix","名词后缀")],
     "derivation":"re(反复)+volu(转) → 彻底翻转 → 革命;循环转动=旋转",
     "family":FAM("volv/volu","卷、转",[W("revolve","旋转"),W("involve","涉及"),W("evolve","进化"),W("volume","卷")]),
     "mnemonic":"volu=转(想 revolve 旋转);社会来个彻底翻转=革命;天体转一圈=旋转(一转=one revolution)。",
     "forms":[F("revolutionary","adj.","革命性的")]}},
  # -plic 折
  {"word":"complicated","phonetic":"ˈkɒmplɪkeɪtɪd","pos":"adj.","def":"复杂的，难懂的","cefr":"B1","freq_rank":105,
   "sentence_en":"The instructions are too complicated.","sentence_zh":"说明太复杂了。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("plic","root","折叠"),M("ated","suffix","…的")],
     "derivation":"com(一起)+plic(折) → 折来折去缠在一起 → 复杂的",
     "family":FAM("plic/ply","折叠",[W("apply","申请"),W("imply","暗示"),W("complex","复杂的"),W("multiply","乘")]),
     "mnemonic":"plic=折(和 complex 一家);层层折叠、缠成一团,就是 complicated 复杂的;动词 complicate 使复杂。",
     "forms":[F("complicate","v.","使复杂"),F("complication","n.","复杂；并发症")]}},
  {"word":"concentration","phonetic":"ˌkɒnsənˈtreɪʃən","pos":"n.","def":"专注，集中；浓度","cefr":"B2","freq_rank":106,
   "sentence_en":"The task requires great concentration.","sentence_zh":"这项任务需要高度专注。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("centr","root","中心"),M("ation","suffix","名词后缀")],
     "derivation":"concentrate(聚到中心)+ion → 集中的状态 → 专注、浓度",
     "family":FAM("centr","中心",[W("concentrate","集中"),W("center","中心"),W("central","中央的")]),
     "mnemonic":"centr=中心(和 concentrate 一家);注意力/物质汇于一点,就是 concentration 专注、浓度。",
     "forms":[F("concentrate","v.","集中")]}},
  # -gen 产生
  {"word":"genetic","phonetic":"dʒɪˈnetɪk","pos":"adj.","def":"基因的，遗传的","cefr":"B2","freq_rank":93,
   "sentence_en":"The disease is genetic.","sentence_zh":"这种病是遗传的。",
   "aids":{"morphemes":[M("gen","root","产生，种"),M("etic","suffix","…的")],
     "derivation":"gen(产生、种)+etic → 与遗传/基因有关的 → 遗传的",
     "family":FAM("gen","产生、种类",[W("gene","基因"),W("generate","产生"),W("generation","一代"),W("gender","性别")]),
     "mnemonic":"gen=产生/种(和 gene 基因一家);经基因遗传下来的,就是 genetic;genetics 遗传学。",
     "forms":[F("genetics","n.","遗传学"),F("genetically","adv.","基因上")]}},
  # -cent 激励
  {"word":"incentive","phonetic":"ɪnˈsentɪv","pos":"n.","def":"激励，动机，诱因","cefr":"C1","freq_rank":95,
   "sentence_en":"Bonuses are a good incentive.","sentence_zh":"奖金是很好的激励。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("cent","root","唱，激起(cantare)"),M("ive","suffix","名词后缀")],
     "derivation":"in(向内)+cent(激起) → 从内心激起干劲的东西 → 激励",
     "family":FAM("cant/cent","唱、激起",[W("chant","吟唱"),W("accent","口音")]),
     "mnemonic":"cent=激起(想 accent 重音、chant 吟唱);从内心把干劲'激'起来的东西,就是 incentive 激励、诱因。",
     "forms":[F("incentives","n.","激励(复数)")]}},
  # -cur 精确
  {"word":"accurate","phonetic":"ˈækjurət","pos":"adj.","def":"准确的，精确的","cefr":"B1","freq_rank":96,
   "sentence_en":"The measurements must be accurate.","sentence_zh":"测量必须精确。",
   "aids":{"morphemes":[M("ac","prefix","朝向(ad 变体)"),M("cur","root","关心，仔细(cura)"),M("ate","suffix","…的")],
     "derivation":"ac(朝向)+cur(仔细) → 用心做到分毫不差 → 准确的",
     "family":FAM("cur","关心、仔细",[W("cure","治愈"),W("secure","安全的"),W("curious","好奇的")]),
     "mnemonic":"cur=仔细/用心(想 care);下足功夫做到分毫不差,就是 accurate 准确的;accuracy 准确性;反义 inaccurate。",
     "forms":[F("accuracy","n.","准确性"),F("accurately","adv.","准确地")]}},
  # -sort 抽签/种类
  {"word":"resort","phonetic":"rɪˈzɔːt","pos":"n./v.","def":"度假胜地；求助，诉诸","cefr":"B2","freq_rank":80,
   "sentence_en":"We stayed at a beach resort.","sentence_zh":"我们住在海滨度假胜地。",
   "aids":{"morphemes":[M("re","prefix","再，反复"),M("sort","root","出去(sortir)")],
     "derivation":"re(反复)+sort(出去、去) → 人们反复前往之地 → 胜地;不得已'转而去'某手段 → 诉诸",
     "family":FAM("sort","出、种类",[W("sort","分类"),W("assort","分类")]),
     "mnemonic":"sort=去(法语 sortir 出去);大家反复去玩的地方=度假胜地;无奈'转而去'某办法=resort to 诉诸;last resort 最后手段。",
     "forms":[F("resorts","n.","胜地(复数)")]}},
  # -sub 实
  {"word":"substantial","phonetic":"səbˈstænʃl","pos":"adj.","def":"大量的，可观的；实质的，坚实的","cefr":"C1","freq_rank":42,
   "sentence_en":"They made a substantial profit.","sentence_zh":"他们获得了可观的利润。",
   "aids":{"morphemes":[M("sub","prefix","在下"),M("st","root","站"),M("antial","suffix","…的")],
     "derivation":"sub(在下)+st(站) → 有底子撑着的 → 实质的、大量的",
     "family":FAM("st/sta","站、立",[W("substance","物质"),W("stand","站立"),W("stable","稳定的")]),
     "mnemonic":"和 substance(实质)一家;底子厚、分量足的,就是 substantial 大量的/实质的;substantially 大幅地。",
     "forms":[F("substantially","adv.","大幅地；实质上")]}},
  # -spec 专
  {"word":"specialist","phonetic":"ˈspeʃəlɪst","pos":"n.","def":"专家，专科医生","cefr":"B2","freq_rank":43,
   "sentence_en":"She is a heart specialist.","sentence_zh":"她是心脏科专家。",
   "aids":{"morphemes":[M("special","root","特别的，专门的"),M("ist","suffix","…的人")],
     "derivation":"special(专门)+ist → 专攻某领域的人 → 专家",
     "family":FAM("spec","看、种类",[W("special","特别的"),W("specialize","专门研究"),W("species","物种")]),
     "mnemonic":"special(专门)+ist(人);专攻一门的人,就是 specialist 专家;动词 specialize 专攻;反义 generalist。",
     "forms":[F("specialize","v.","专攻"),F("specialty","n.","专长")]}},
  # 高频名词/动词(常见/词根)
  {"word":"approval","phonetic":"əˈpruːvl","pos":"n.","def":"批准，赞成","cefr":"B1","freq_rank":44,
   "sentence_en":"The plan needs official approval.","sentence_zh":"这个计划需要官方批准。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("prov","root","证明，检验"),M("al","suffix","名词后缀")],
     "derivation":"approve(认可放行)+al → 认可、放行 → 批准",
     "family":FAM("prov/prob","证明、检验",[W("approve","批准"),W("prove","证明"),W("probable","很可能的")]),
     "mnemonic":"approve(批准)的名词;点头放行、认可,就是 approval;seal of approval 认可;反义 disapproval。",
     "forms":[F("approve","v.","批准")]}},
  {"word":"recommendation","phonetic":"ˌrekəmenˈdeɪʃən","pos":"n.","def":"推荐，建议；推荐信","cefr":"B1","freq_rank":114,
   "sentence_en":"I bought it on her recommendation.","sentence_zh":"我是听了她的推荐才买的。",
   "aids":{"morphemes":[M("re","prefix","加强"),M("commend","root","委托，称赞(mand)"),M("ation","suffix","名词后缀")],
     "derivation":"recommend(引荐)+ation → 引荐、建议 → 推荐",
     "family":FAM("mand/mend","命令、交付",[W("recommend","推荐"),W("command","命令"),W("demand","要求")]),
     "mnemonic":"recommend(推荐)的名词;郑重引荐、给的建议,就是 recommendation;letter of recommendation 推荐信。",
     "forms":[F("recommend","v.","推荐")]}},
  {"word":"exhibition","phonetic":"ˌeksɪˈbɪʃən","pos":"n.","def":"展览，展览会；表现","cefr":"B1","freq_rank":29,
   "sentence_en":"We visited an art exhibition.","sentence_zh":"我们参观了一个艺术展。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("hib","root","拿，持(hab)"),M("ition","suffix","名词后缀")],
     "derivation":"ex(向外)+hib(拿) → 把东西拿出来给人看 → 展览",
     "family":FAM("hab/hib","拿、持",[W("exhibit","展出"),W("prohibit","禁止"),W("habit","习惯")]),
     "mnemonic":"hib=拿(想 prohibit 拿住不许=禁止);把作品向外(ex-)拿出展示,就是 exhibition 展览;动词 exhibit。",
     "forms":[F("exhibit","v.","展出"),F("exhibitions","n.","展览(复数)")]}},
  {"word":"ceremony","phonetic":"ˈserɪməni","pos":"n.","def":"典礼，仪式","cefr":"B1","freq_rank":74,
   "sentence_en":"The wedding ceremony was beautiful.","sentence_zh":"婚礼仪式很美。",
   "aids":{"morphemes":[M("cere","root","神圣(caerimonia)"),M("mony","suffix","名词后缀")],
     "derivation":"拉丁 caerimonia'神圣礼仪';庄重的礼节 → 典礼",
     "family":FAM("","相关词",[W("ceremonial","仪式的")]),
     "mnemonic":"庄重神圣的礼节流程,就是 ceremony 典礼、仪式;opening ceremony 开幕式;ceremonial 仪式性的。",
     "forms":[F("ceremonies","n.","仪式(复数)"),F("ceremonial","adj.","仪式的")]}},
  {"word":"mechanism","phonetic":"ˈmekənɪzm","pos":"n.","def":"机制，机理；机械装置","cefr":"B2","freq_rank":77,
   "sentence_en":"The body has a defense mechanism.","sentence_zh":"人体有一套防御机制。",
   "aids":{"morphemes":[M("mechan","root","机械，装置"),M("ism","suffix","名词后缀")],
     "derivation":"mechan(机械)+ism → 运作的构造/原理 → 机制",
     "family":FAM("mechan","机械",[W("mechanic","机械师"),W("mechanical","机械的"),W("machine","机器")]),
     "mnemonic":"mechan=机械(想 machine);事物内部如机器般运作的构造/原理,就是 mechanism 机制。",
     "forms":[F("mechanical","adj.","机械的"),F("mechanisms","n.","机制(复数)")]}},
  {"word":"penalty","phonetic":"ˈpenlti","pos":"n.","def":"处罚，罚款；点球","cefr":"B2","freq_rank":79,
   "sentence_en":"There is a penalty for late payment.","sentence_zh":"逾期付款要罚款。",
   "aids":{"morphemes":[M("pen","root","惩罚(poena)"),M("alty","suffix","名词后缀")],
     "derivation":"pen(惩罚)+alty → 惩罚(款) → 处罚",
     "family":FAM("pen/pun","惩罚",[W("punish","惩罚"),W("penal","刑罚的"),W("repent","忏悔")]),
     "mnemonic":"pen=惩罚(和 punish 一家);违规要受的处罚/罚款,就是 penalty;足球的'点球'也是 penalty。",
     "forms":[F("penalties","n.","处罚(复数)")]}},
  {"word":"guarantee","phonetic":"ˌɡærənˈtiː","pos":"v./n.","def":"保证，担保；保修","cefr":"B1","freq_rank":116,
   "sentence_en":"We guarantee next-day delivery.","sentence_zh":"我们保证次日送达。",
   "aids":{"morphemes":[M("guarant","root","担保(warrant)"),M("ee","suffix","结尾")],
     "derivation":"与 warrant(保证)同源;打包票 → 保证",
     "family":FAM("guar/war","保证、看守",[W("warrant","授权；保证"),W("guard","守卫"),W("warranty","保修单")]),
     "mnemonic":"guarantee 与 warrant/guard(保、守)同源;拍板打包票,就是 guarantee 保证;质量保修=warranty。",
     "forms":[F("guaranteed","adj.","保证的"),F("guarantees","n.","保证(复数)")]}},
  {"word":"statistics","phonetic":"stəˈtɪstɪks","pos":"n.","def":"统计数据；统计学","cefr":"B2","freq_rank":90,
   "sentence_en":"The statistics show a clear trend.","sentence_zh":"这些统计数据显示出明显趋势。",
   "aids":{"morphemes":[M("stat","root","国家，状态(state)"),M("istics","suffix","…学")],
     "derivation":"最初指'关于国家状况的数据';数据的收集分析 → 统计",
     "family":FAM("stat/st","状态、站",[W("state","国家；状态"),W("status","状态"),W("statistic","统计量")]),
     "mnemonic":"stat=国家/状态(想 state);原指国家状况的数据,现泛指 statistics 统计数据/统计学;statistical 统计的。",
     "forms":[F("statistical","adj.","统计的"),F("statistic","n.","统计量")]}},
  {"word":"detect","phonetic":"dɪˈtekt","pos":"v.","def":"察觉，发现；检测","cefr":"B2","freq_rank":113,
   "sentence_en":"The alarm detects smoke.","sentence_zh":"警报器能检测烟雾。",
   "aids":{"morphemes":[M("de","prefix","去除，揭开"),M("tect","root","盖(teg)")],
     "derivation":"de(揭开)+tect(盖) → 揭开盖子看出来 → 察觉、发现",
     "family":FAM("teg/tect","盖",[W("protect","保护(盖住)"),W("detective","侦探")]),
     "mnemonic":"tect=盖(想 protect 盖住保护);把盖着的揭(de-)开发现,就是 detect;detective 侦探;detector 探测器。",
     "forms":[F("detection","n.","察觉；检测"),F("detective","n.","侦探")]}},
  {"word":"champion","phonetic":"ˈtʃæmpiən","pos":"n./v.","def":"冠军；拥护者；捍卫","cefr":"B1","freq_rank":110,
   "sentence_en":"She is the world champion.","sentence_zh":"她是世界冠军。",
   "aids":{"morphemes":[M("champ","root","田野，战场(campus)"),M("ion","suffix","…的人")],
     "derivation":"与 camp/campus'战场'同源;战场上取胜的人 → 冠军;为某事而战 → 捍卫",
     "family":FAM("camp","田野、战场",[W("camp","营地"),W("campaign","战役"),W("campus","校园")]),
     "mnemonic":"champ 与 camp(战场)同源;在赛场'战'胜众人的=冠军;为某主张而战=champion 捍卫、拥护。",
     "forms":[F("championship","n.","锦标赛；冠军头衔")]}},
  {"word":"tremendous","phonetic":"trɪˈmendəs","pos":"adj.","def":"巨大的，极大的；极好的","cefr":"B2","freq_rank":115,
   "sentence_en":"They made a tremendous effort.","sentence_zh":"他们付出了巨大努力。",
   "aids":{"morphemes":[M("tremend","root","令人发抖(tremere)"),M("ous","suffix","…的")],
     "derivation":"tremend(令人发抖)+ous → 大/强到令人震颤的 → 巨大的",
     "family":FAM("trem","颤抖",[W("tremble","发抖"),W("tremor","震颤")]),
     "mnemonic":"tremend=令人发抖(想 tremble 颤抖);大到/好到令人震撼,就是 tremendous 巨大的、极好的。",
     "forms":[F("tremendously","adv.","极大地")]}},
  # 常见词
  {"word":"relative","phonetic":"ˈrelətɪv","pos":"n./adj.","def":"亲戚；相对的，比较的","cefr":"B1","freq_rank":21,
   "sentence_en":"He is a distant relative.","sentence_zh":"他是个远亲。",
   "aids":{"morphemes":[M("re","prefix","相互"),M("lat","root","带"),M("ive","suffix","…的")],
     "derivation":"relate(相互牵连)+ive → 有关联的 → 相对的;有血缘关联的人 → 亲戚",
     "family":FAM("lat","带、拿",[W("relate","使有联系"),W("relation","关系"),W("translate","翻译")]),
     "mnemonic":"lat=带(和 relate 一家);彼此关联的=相对的/比较的;有亲缘关联的人=亲戚;relatively 相对地。",
     "forms":[F("relatively","adv.","相对地")]}},
  {"word":"install","phonetic":"ɪnˈstɔːl","pos":"v.","def":"安装，安置；使就职","cefr":"B1","freq_rank":34,
   "sentence_en":"They installed a new heating system.","sentence_zh":"他们安装了新的供暖系统。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("stall","root","位置，座(stall 隔间)")],
     "derivation":"in(向内)+stall(位置) → 放到该在的位置上 → 安装",
     "family":FAM("stall/st","位置、站",[W("stall","摊位；隔间"),W("install","安装")]),
     "mnemonic":"stall=位置/隔间;把设备/程序放进(in-)该在的位子,就是 install 安装;installation 安装。",
     "forms":[F("installation","n.","安装"),F("installed","v.","过去式/过去分词")]}},
  {"word":"weigh","phonetic":"weɪ","pos":"v.","def":"称重；重达；权衡，考虑","cefr":"A2","freq_rank":33,
   "sentence_en":"Please weigh the parcel.","sentence_zh":"请称一下包裹的重量。",
   "aids":{"morphemes":[M("weigh","root","称，负重(古英语 wegan)")],
     "derivation":"古英语'搬运、有重量';量出轻重 → 称重;心里掂量轻重 → 权衡",
     "family":FAM("weigh","重",[W("weight","重量"),W("outweigh","比…重要")]),
     "mnemonic":"weigh=称重(名词 weight);放秤上量=称重;心里'掂量'利弊=weigh 权衡;weigh up 权衡;outweigh 胜过。",
     "forms":[F("weight","n.","重量"),F("weighed","v.","过去式/过去分词")]}},
  {"word":"switch","phonetic":"swɪtʃ","pos":"n./v.","def":"开关；转变，转换","cefr":"B1","freq_rank":57,
   "sentence_en":"Switch off the light.","sentence_zh":"把灯关掉。",
   "aids":{"morphemes":[M("switch","root","抽条，转换(中古英语)")],
     "derivation":"本义'柔软的鞭条(可拨动)';拨动开合 → 开关;拨来拨去 → 转换",
     "family":FAM("","相关词",[W("switchboard","交换台")]),
     "mnemonic":"switch=拨杆;拨动通断的=开关;从A拨到B=switch 转换(switch to);switch on/off 开/关。",
     "forms":[F("switched","v.","过去式/过去分词"),F("switches","n.","开关(复数)")]}},
  {"word":"embrace","phonetic":"ɪmˈbreɪs","pos":"v./n.","def":"拥抱；欣然接受；包含","cefr":"B2","freq_rank":28,
   "sentence_en":"They embraced new technology.","sentence_zh":"他们欣然接受了新技术。",
   "aids":{"morphemes":[M("em","prefix","使处于(in)"),M("brace","root","手臂(bracchium)")],
     "derivation":"em(使)+brace(手臂) → 用双臂环抱 → 拥抱;张开怀抱迎接 → 接受",
     "family":FAM("brace/brac","手臂",[W("bracelet","手镯"),W("brace","支撑")]),
     "mnemonic":"brace=手臂(想 bracelet 手镯);张开双臂搂住=拥抱;敞开怀抱迎接新事物=embrace 欣然接受。",
     "forms":[F("embraced","v.","过去式/过去分词")]}},
  {"word":"bind","phonetic":"baɪnd","pos":"v.","def":"捆绑，束缚；约束；装订","cefr":"B2","freq_rank":31,
   "sentence_en":"They bound the books with string.","sentence_zh":"他们用绳子把书捆起来。",
   "aids":{"morphemes":[M("bind","root","捆(古英语 bindan)")],
     "derivation":"古英语'捆、系';绑到一起 → 捆绑;规则'绑住'人 → 约束",
     "family":FAM("bind/band","捆、带",[W("band","带子；乐队"),W("bond","纽带"),W("bundle","捆")]),
     "mnemonic":"bind=捆(过去式 bound);用绳绑=捆绑;合同'绑住'双方=约束;把书页绑成册=装订;binding 有约束力的。",
     "forms":[F("bound","v.","过去式/过去分词"),F("binding","adj.","有约束力的")]}},
  {"word":"draft","phonetic":"drɑːft","pos":"n./v.","def":"草稿，草案；起草；征兵","cefr":"B2","freq_rank":64,
   "sentence_en":"This is just a first draft.","sentence_zh":"这只是初稿。",
   "aids":{"morphemes":[M("draft","root","拉，抽(draw)")],
     "derivation":"与 draw'拉、画'同源;'抽拉'出来的初稿/汇票;'抽调'人入伍=征兵",
     "family":FAM("draft/draw","拉、画",[W("draw","画；拉"),W("drag","拖")]),
     "mnemonic":"draft 与 draw(拉/画)同源;先'拉'个大概=草稿/草案;'抽调'人服兵役=征兵;一股'抽'过的气流=draft。",
     "forms":[F("drafts","n.","草稿(复数)"),F("drafted","v.","过去式/过去分词")]}},
  {"word":"rank","phonetic":"ræŋk","pos":"n./v.","def":"等级，军衔；排名，位列","cefr":"B1","freq_rank":67,
   "sentence_en":"She holds a high rank in the army.","sentence_zh":"她在军中军衔很高。",
   "aids":{"morphemes":[M("rank","root","行列(古法语 renc)")],
     "derivation":"古法语'一排、行列';排成的等级 → 等级、军衔;按高低排 → 排名",
     "family":FAM("rank/rang","排、行",[W("range","范围"),W("arrange","安排")]),
     "mnemonic":"rank=行列(和 range 一家);一排排分出的高低=等级/军衔;按标准排序=rank 排名(ranked #1)。",
     "forms":[F("ranks","n.","等级(复数)"),F("ranking","n.","排名")]}},
  {"word":"yield","phonetic":"jiːld","pos":"v./n.","def":"产出，出产；屈服，让步；产量","cefr":"B2","freq_rank":68,
   "sentence_en":"The farm yields a good crop.","sentence_zh":"这个农场收成不错。",
   "aids":{"morphemes":[M("yield","root","付出，产出(古英语 gieldan 偿付)")],
     "derivation":"古英语'偿付、产出';土地'付出'收成 → 产出;向压力'付出'=屈服",
     "family":FAM("","相关词",[W("yielding","柔顺的")]),
     "mnemonic":"yield=付出/产出;土地产出收成=yield 产量;顶不住而'交出'=屈服、让步(yield to);路牌 YIELD=让行。",
     "forms":[F("yields","n.","产量(复数)"),F("yielded","v.","过去式/过去分词")]}},
  {"word":"innocent","phonetic":"ˈɪnəsnt","pos":"adj.","def":"无辜的，清白的；天真的","cefr":"B1","freq_rank":117,
   "sentence_en":"He was found innocent.","sentence_zh":"他被判无罪。",
   "aids":{"morphemes":[M("in","prefix","不"),M("noc","root","伤害(noc)"),M("ent","suffix","…的")],
     "derivation":"in(不)+noc(伤害) → 没做伤害之事的 → 无辜的",
     "family":FAM("noc/nox","伤害",[W("innocence","清白"),W("noxious","有害的")]),
     "mnemonic":"noc=伤害(想 noxious 有害的);没干坏事、不害人的,就是 innocent 无辜的/天真的;反义 guilty 有罪的。",
     "forms":[F("innocence","n.","清白，无辜")]}},
  {"word":"profile","phonetic":"ˈprəʊfaɪl","pos":"n./v.","def":"简介，概况；侧面，轮廓","cefr":"B2","freq_rank":76,
   "sentence_en":"Update your online profile.","sentence_zh":"更新你的在线个人简介。",
   "aids":{"morphemes":[M("pro","prefix","向前"),M("file","root","线，纺(filum)")],
     "derivation":"pro(向前)+file(线) → 沿轮廓画出的线条 → 侧面轮廓;引申个人'轮廓'介绍 → 简介",
     "family":FAM("fil","线",[W("file","文件；档案"),W("filament","细丝")]),
     "mnemonic":"file=线(想 filament 灯丝);沿边勾出的线条=侧面轮廓;把某人'轮廓'性情况写出=profile 简介;high profile 高调。",
     "forms":[F("profiles","n.","简介(复数)")]}},
  {"word":"string","phonetic":"strɪŋ","pos":"n./v.","def":"细绳，线；一串；(乐器)弦；字符串","cefr":"B1","freq_rank":75,
   "sentence_en":"Tie it with a string.","sentence_zh":"用绳子把它系好。",
   "aids":{"morphemes":[M("string","root","拉紧的线(古英语 streng)")],
     "derivation":"与 strong/strict'拉紧'同源;绷紧的细线 → 弦、线;串起来的一列 → 一串",
     "family":FAM("str","拉紧",[W("strong","强壮的"),W("strict","严格的"),W("stretch","伸展")]),
     "mnemonic":"str=拉紧(和 strong 一家);绷紧的细线=弦/绳;串成一列=a string of;编程里一串字符=string 字符串。",
     "forms":[F("strings","n.","弦(复数)"),F("strung","v.","过去式/过去分词")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 15
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
