#!/usr/bin/env python
# 第二批词:约55个高频词,逐词精做 aids,追加进 data/vocab-seed.json。
# 结构:BATCH2 是 [{word, phonetic, pos, def, sentence_en, sentence_zh, cefr, freq_rank, aids}]。
# 用法: python tools/gen_seed_batch2.py  (幂等:同名词不会重复追加)
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass

HERE = os.path.dirname(os.path.abspath(__file__))
SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")

def M(text, type, gloss): return {"text": text, "type": type, "gloss": gloss}
def F(word, pos, d): return {"word": word, "pos": pos, "def": d}
def FAM(root, gloss, words): return {"root": root, "gloss": gloss, "words": words}
def W(word, gloss): return {"word": word, "def": gloss}

BATCH2 = [
  # ===== -tain / -ten 家族(拿、持) =====
  {"word":"contain","phonetic":"kənˈteɪn","pos":"v.","def":"包含，容纳；控制","cefr":"B1","freq_rank":931,
   "sentence_en":"This bottle contains two litres of water.","sentence_zh":"这个瓶子装两升水。",
   "aids":{"morphemes":[M("con","prefix","一起，共同"),M("tain","root","拿，持")],
     "derivation":"con(一起)+tain(拿) → 把东西一起拿在里面 → 包含",
     "family":FAM("tain/ten","拿、持",[W("maintain","维持"),W("obtain","获得"),W("sustain","维持，支撑"),W("retain","保留")]),
     "mnemonic":"tain=拿住(想 container 容器);把一堆东西一起(con-)拿在里面,就是 contain 包含。",
     "forms":[F("container","n.","容器"),F("contained","v.","过去式/过去分词")]}},
  {"word":"maintain","phonetic":"meɪnˈteɪn","pos":"v.","def":"维持，保持；维修；主张","cefr":"B2","freq_rank":922,
   "sentence_en":"It is hard to maintain a healthy diet while travelling.","sentence_zh":"旅途中很难保持健康饮食。",
   "aids":{"morphemes":[M("main","root","手(manu 变体)"),M("tain","root","拿，持")],
     "derivation":"main(手)+tain(持) → 用手持续把住 → 维持",
     "family":FAM("tain/ten","拿、持",[W("contain","包含"),W("obtain","获得"),W("sustain","支撑"),W("detain","拘留")]),
     "mnemonic":"main(手)+tain(持)——用手一直把着不松,就是 maintain 维持、保养。",
     "forms":[F("maintenance","n.","维护，保养"),F("maintained","v.","过去式/过去分词")]}},
  {"word":"obtain","phonetic":"əbˈteɪn","pos":"v.","def":"获得，得到","cefr":"B2","freq_rank":1595,
   "sentence_en":"You can obtain a visa at the embassy.","sentence_zh":"你可以在大使馆获得签证。",
   "aids":{"morphemes":[M("ob","prefix","朝向，加强"),M("tain","root","拿，持")],
     "derivation":"ob(朝向)+tain(拿) → 伸手朝它拿过来 → 获得",
     "family":FAM("tain/ten","拿、持",[W("contain","包含"),W("maintain","维持"),W("sustain","支撑"),W("retain","保留")]),
     "mnemonic":"ob-(朝着)+tain(拿)——朝目标伸手把它拿到手,就是 obtain 获得。",
     "forms":[F("obtained","v.","过去式/过去分词"),F("obtainable","adj.","可获得的")]}},
  {"word":"sustain","phonetic":"səˈsteɪn","pos":"v.","def":"维持，支撑；忍受","cefr":"B2","freq_rank":2986,
   "sentence_en":"The economy cannot sustain such rapid growth forever.","sentence_zh":"经济无法永远维持如此高速的增长。",
   "aids":{"morphemes":[M("sus","prefix","在下(sub 变体)"),M("tain","root","拿，持")],
     "derivation":"sus(在下)+tain(持) → 从下面托住 → 支撑、维持",
     "family":FAM("tain/ten","拿、持",[W("contain","包含"),W("maintain","维持"),W("obtain","获得")]),
     "mnemonic":"sus-(在下)+tain(托)——从底下一直托着不让它塌,就是 sustain 支撑、维持。",
     "forms":[F("sustainable","adj.","可持续的"),F("sustainability","n.","可持续性")]}},
  # ===== -tract 家族(拉、拽) =====
  {"word":"attract","phonetic":"əˈtrækt","pos":"v.","def":"吸引","cefr":"B1","freq_rank":1867,
   "sentence_en":"Bright colours attract bees to flowers.","sentence_zh":"鲜艳的颜色把蜜蜂吸引到花上。",
   "aids":{"morphemes":[M("at","prefix","朝向(ad 变体)"),M("tract","root","拉，拽")],
     "derivation":"at(朝向)+tract(拉) → 把…往自己这边拉 → 吸引",
     "family":FAM("tract","拉、拽",[W("extract","提取(拉出)"),W("contract","合同；收缩"),W("distract","分心(拉开)"),W("subtract","减去")]),
     "mnemonic":"tract=拉(想 tractor 拖拉机);朝(at-)自己方向把人往这拉,就是 attract 吸引。",
     "forms":[F("attraction","n.","吸引；吸引力"),F("attractive","adj.","有吸引力的")]}},
  {"word":"extract","phonetic":"ɪkˈstrækt","pos":"v.","def":"提取，抽取；摘录","cefr":"B2","freq_rank":4971,
   "sentence_en":"Oil is extracted from these seeds.","sentence_zh":"油是从这些种子里提取的。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("tract","root","拉，拽")],
     "derivation":"ex(向外)+tract(拉) → 往外拉出来 → 提取",
     "family":FAM("tract","拉、拽",[W("attract","吸引"),W("contract","合同；收缩"),W("distract","分心"),W("abstract","抽象的；摘要")]),
     "mnemonic":"ex-(向外)+tract(拉)——费劲把东西往外拉出来,就是 extract 提取。",
     "forms":[F("extraction","n.","提取；抽出"),F("extracted","v.","过去式/过去分词")]}},
  {"word":"contract","phonetic":"ˈkɒntrækt","pos":"n./v.","def":"合同；收缩","cefr":"B2","freq_rank":1269,
   "sentence_en":"They signed a two-year contract.","sentence_zh":"他们签了一份两年的合同。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("tract","root","拉，拽")],
     "derivation":"con(一起)+tract(拉) → 双方拉到一起(定下) → 合约;引申拉紧→收缩",
     "family":FAM("tract","拉、拽",[W("attract","吸引"),W("extract","提取"),W("distract","分心"),W("abstract","抽象的")]),
     "mnemonic":"con-(一起)+tract(拉)——把双方拉到一起签字定下,就是 contract 合同;肌肉往一起拉=收缩。",
     "forms":[F("contractor","n.","承包商"),F("contraction","n.","收缩")]}},
  {"word":"distract","phonetic":"dɪˈstrækt","pos":"v.","def":"使分心，转移注意力","cefr":"B2","freq_rank":4498,
   "sentence_en":"Loud music distracts me from studying.","sentence_zh":"大声的音乐使我学习分心。",
   "aids":{"morphemes":[M("dis","prefix","分开，离"),M("tract","root","拉，拽")],
     "derivation":"dis(分开)+tract(拉) → 把注意力拉开 → 分心",
     "family":FAM("tract","拉、拽",[W("attract","吸引"),W("extract","提取"),W("contract","合同"),W("subtract","减去")]),
     "mnemonic":"dis-(分开)+tract(拉)——把你的注意力往别处一拉扯开,就是 distract 使分心。",
     "forms":[F("distraction","n.","分心的事物"),F("distracted","adj.","分心的")]}},
  {"word":"abstract","phonetic":"ˈæbstrækt","pos":"adj./n.","def":"抽象的；摘要","cefr":"C1","freq_rank":4007,
   "sentence_en":"Love is an abstract concept.","sentence_zh":"爱是一个抽象的概念。",
   "aids":{"morphemes":[M("abs","prefix","离开"),M("tract","root","拉，拽")],
     "derivation":"abs(离开)+tract(拉) → 把概念从具体事物中抽拉出来 → 抽象",
     "family":FAM("tract","拉、拽",[W("attract","吸引"),W("extract","提取"),W("contract","合同")]),
     "mnemonic":"abs-(离开)+tract(拉)——把概念从具体东西里抽离拉出,只剩纯观念,就是 abstract 抽象。",
     "forms":[F("abstraction","n.","抽象；抽象概念")]}},
  # ===== -duce/-duct 家族(引导、带) =====
  {"word":"conduct","phonetic":"kənˈdʌkt","pos":"v./n.","def":"实施，进行；举止；传导","cefr":"B2","freq_rank":1162,
   "sentence_en":"Scientists conducted an experiment.","sentence_zh":"科学家进行了一项实验。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("duct","root","引导，带")],
     "derivation":"con(一起)+duct(引导) → 把大家/流程一起引导下去 → 实施、指挥",
     "family":FAM("duct/duce","引导、带",[W("introduce","介绍"),W("reduce","减少"),W("produce","生产"),W("educate","教育")]),
     "mnemonic":"duct=引导(想 conductor 指挥/导体);把整件事一起(con-)引领着做下去,就是 conduct 实施、指挥。",
     "forms":[F("conductor","n.","指挥；导体"),F("conduction","n.","传导")]}},
  {"word":"introduce","phonetic":"ˌɪntrəˈdjuːs","pos":"v.","def":"介绍；引入，采用","cefr":"A2","freq_rank":1225,
   "sentence_en":"Let me introduce you to my colleague.","sentence_zh":"让我把你介绍给我的同事。",
   "aids":{"morphemes":[M("intro","prefix","向内，入内"),M("duce","root","引导，带")],
     "derivation":"intro(向内)+duce(带) → 把人/事物带入其中 → 介绍、引入",
     "family":FAM("duct/duce","引导、带",[W("conduct","实施"),W("reduce","减少"),W("produce","生产"),W("educate","教育")]),
     "mnemonic":"intro-(往里)+duce(带)——把一个人带进这个圈子,就是 introduce 介绍;把新东西带进来=引入。",
     "forms":[F("introduction","n.","介绍；引言"),F("introductory","adj.","引导的，入门的")]}},
  {"word":"promote","phonetic":"prəˈməʊt","pos":"v.","def":"促进；晋升；推广","cefr":"B2","freq_rank":1328,
   "sentence_en":"Exercise promotes good health.","sentence_zh":"锻炼促进健康。",
   "aids":{"morphemes":[M("pro","prefix","向前"),M("mot","root","动"),M("e","suffix","动词结尾")],
     "derivation":"pro(向前)+mot(动) → 推着向前动 → 促进、晋升",
     "family":FAM("mot/mov","动",[W("motive","动机"),W("emotion","情绪"),W("remove","移开"),W("motion","运动")]),
     "mnemonic":"mot=动(想 motor 马达);把事情/人往前(pro-)推动,就是 promote 促进、晋升。",
     "forms":[F("promotion","n.","促进；晋升；促销")]}},
  # ===== -mot/-mov 家族(动) =====
  {"word":"remove","phonetic":"rɪˈmuːv","pos":"v.","def":"移开，去除","cefr":"A2","freq_rank":876,
   "sentence_en":"Please remove your shoes before entering.","sentence_zh":"进门前请脱鞋。",
   "aids":{"morphemes":[M("re","prefix","向后，离开"),M("move","root","移动")],
     "derivation":"re(离开)+move(移) → 移走 → 去除",
     "family":FAM("mov/mot","动",[W("motion","运动"),W("motive","动机"),W("promote","促进"),W("emotion","情绪")]),
     "mnemonic":"re-(离开)+move(移)——把东西移开、拿走,就是 remove 去除。",
     "forms":[F("removal","n.","移除，搬迁"),F("removable","adj.","可移除的")]}},
  {"word":"motive","phonetic":"ˈməʊtɪv","pos":"n.","def":"动机，目的","cefr":"B2","freq_rank":3578,
   "sentence_en":"The police could not find a motive for the crime.","sentence_zh":"警方找不到犯罪的动机。",
   "aids":{"morphemes":[M("mot","root","动"),M("ive","suffix","…的(名词)")],
     "derivation":"mot(动)+ive → 使人行动的东西 → 动机",
     "family":FAM("mot/mov","动",[W("motion","运动"),W("emotion","情绪"),W("promote","促进"),W("remove","移开")]),
     "mnemonic":"mot=动;驱使你行动的内在理由,就是 motive 动机。",
     "forms":[F("motivate","v.","激励"),F("motivation","n.","动机，积极性")]}},
  {"word":"emotion","phonetic":"ɪˈməʊʃən","pos":"n.","def":"情绪，情感","cefr":"B1","freq_rank":2117,
   "sentence_en":"She spoke with great emotion.","sentence_zh":"她带着强烈的情感说话。",
   "aids":{"morphemes":[M("e","prefix","向外(ex 变体)"),M("mot","root","动"),M("ion","suffix","名词后缀")],
     "derivation":"e(向外)+mot(动) → 内心向外涌动 → 情绪",
     "family":FAM("mot/mov","动",[W("motive","动机"),W("motion","运动"),W("promote","促进")]),
     "mnemonic":"e-(向外)+mot(动)——内心被搅动、向外流露出来的波动,就是 emotion 情绪。",
     "forms":[F("emotional","adj.","情绪的，情感的")]}},
  # ===== -mit/-miss 家族(送、派) =====
  {"word":"transmit","phonetic":"trænsˈmɪt","pos":"v.","def":"传送，传播，传染","cefr":"B2","freq_rank":4836,
   "sentence_en":"The disease is transmitted by mosquitoes.","sentence_zh":"这种病由蚊子传播。",
   "aids":{"morphemes":[M("trans","prefix","跨越，横过"),M("mit","root","送")],
     "derivation":"trans(跨越)+mit(送) → 送到另一处 → 传送、传播",
     "family":FAM("mit/miss","送、派",[W("submit","提交"),W("commit","犯，投入"),W("mission","任务"),W("permit","允许")]),
     "mnemonic":"mit=送;跨越(trans-)距离把信号/病送过去,就是 transmit 传送、传染。",
     "forms":[F("transmission","n.","传送；传播；变速器")]}},
  {"word":"commit","phonetic":"kəˈmɪt","pos":"v.","def":"犯（错/罪）；承诺，投入","cefr":"B2","freq_rank":1394,
   "sentence_en":"He committed himself to finishing the project.","sentence_zh":"他承诺要完成这个项目。",
   "aids":{"morphemes":[M("com","prefix","一起，完全"),M("mit","root","送")],
     "derivation":"com(完全)+mit(送) → 把自己完全交送出去 → 投入、承诺;交送坏事→犯罪",
     "family":FAM("mit/miss","送、派",[W("submit","提交"),W("transmit","传送"),W("mission","任务"),W("permit","允许")]),
     "mnemonic":"com-(完全)+mit(交送)——把自己完全交付给某事,就是 commit 投入、承诺;交出去干坏事=commit a crime 犯罪。",
     "forms":[F("commitment","n.","承诺，投入"),F("committed","adj.","尽心尽力的")]}},
  {"word":"mission","phonetic":"ˈmɪʃən","pos":"n.","def":"任务，使命；代表团","cefr":"B1","freq_rank":1095,
   "sentence_en":"Their mission was to rescue the hostages.","sentence_zh":"他们的任务是营救人质。",
   "aids":{"morphemes":[M("miss","root","送，派"),M("ion","suffix","名词后缀")],
     "derivation":"miss(派)+ion → 被派遣去做的事 → 任务、使命",
     "family":FAM("mit/miss","送、派",[W("submit","提交"),W("commit","投入"),W("transmit","传送"),W("permit","允许")]),
     "mnemonic":"miss=派(同 mit);被派遣出去必须完成的差事,就是 mission 任务、使命。",
     "forms":[F("missionary","n.","传教士")]}},
  # ===== -struct 家族(建) + 高频独立词 =====
  {"word":"structure","phonetic":"ˈstrʌktʃə","pos":"n./v.","def":"结构，构造；建筑物","cefr":"B1","freq_rank":950,
   "sentence_en":"The essay has a clear structure.","sentence_zh":"这篇文章结构清晰。",
   "aids":{"morphemes":[M("struct","root","建，堆叠"),M("ure","suffix","名词后缀")],
     "derivation":"struct(建)+ure → 建造起来的样式 → 结构",
     "family":FAM("struct","建、堆叠",[W("construct","建造"),W("instruct","指导"),W("destruction","破坏"),W("instrument","工具")]),
     "mnemonic":"struct=搭建(想 construct);东西被搭建起来的骨架方式,就是 structure 结构。",
     "forms":[F("structural","adj.","结构的"),F("structured","adj.","有条理的")]}},
  {"word":"instrument","phonetic":"ˈɪnstrʊmənt","pos":"n.","def":"工具，仪器；乐器","cefr":"B1","freq_rank":1611,
   "sentence_en":"The violin is a beautiful instrument.","sentence_zh":"小提琴是一件美妙的乐器。",
   "aids":{"morphemes":[M("in","prefix","在内，用于"),M("stru","root","建，装备"),M("ment","suffix","名词后缀")],
     "derivation":"in+stru(装备)+ment → 用来装备做事的东西 → 工具、器械",
     "family":FAM("struct/stru","建、装备",[W("structure","结构"),W("construct","建造"),W("instruct","指导")]),
     "mnemonic":"和 structure/construct 同根(stru 建、装备);帮你搭建、做事的器械或乐器,就是 instrument。",
     "forms":[F("instrumental","adj.","起重要作用的；器乐的")]}},
  # ===== -tain/-ten 之外的高频学术词 =====
  {"word":"distance","phonetic":"ˈdɪstəns","pos":"n.","def":"距离，远方","cefr":"A2","freq_rank":1235,
   "sentence_en":"The station is within walking distance.","sentence_zh":"车站在步行距离之内。",
   "aids":{"morphemes":[M("di","prefix","分开"),M("st","root","站，立"),M("ance","suffix","名词后缀")],
     "derivation":"di(分开)+st(站)+ance → 两点分开站着的间隔 → 距离",
     "family":FAM("st/sta","站、立",[W("stand","站立"),W("stable","稳定的"),W("constant","不变的"),W("station","车站")]),
     "mnemonic":"st=站(想 stand);两个点分开(di-)各站一边,中间的间隔就是 distance 距离。",
     "forms":[F("distant","adj.","遥远的")]}},
  {"word":"constant","phonetic":"ˈkɒnstənt","pos":"adj./n.","def":"不断的，恒定的；常数","cefr":"B2","freq_rank":2386,
   "sentence_en":"She lives in constant fear of failure.","sentence_zh":"她生活在对失败的持续恐惧中。",
   "aids":{"morphemes":[M("con","prefix","一起，完全"),M("st","root","站，立"),M("ant","suffix","…的")],
     "derivation":"con(完全)+st(站) → 稳稳站住不动 → 恒定、持续不断",
     "family":FAM("st/sta","站、立",[W("stable","稳定的"),W("distance","距离"),W("stand","站立"),W("status","状态")]),
     "mnemonic":"st=站;完全(con-)站定不挪窝,就是 constant 恒定、持续不断。",
     "forms":[F("constantly","adv.","不断地，经常地")]}},
  {"word":"security","phonetic":"sɪˈkjʊərɪti","pos":"n.","def":"安全；保障","cefr":"B1","freq_rank":661,
   "sentence_en":"Airport security is very strict.","sentence_zh":"机场安检非常严格。",
   "aids":{"morphemes":[M("se","prefix","离开，脱离"),M("cur","root","担心，忧虑"),M("ity","suffix","名词后缀")],
     "derivation":"se(脱离)+cur(担心) → 脱离忧虑的状态 → 安全",
     "family":FAM("cur","担心、关心",[W("secure","安全的"),W("cure","治愈"),W("curious","好奇的")]),
     "mnemonic":"cur=担心;脱离(se-)了担忧,没什么可怕的了,就是 security 安全。",
     "forms":[F("secure","adj.","安全的；牢固的")]}},
  {"word":"significant","phonetic":"sɪɡˈnɪfɪkənt","pos":"adj.","def":"重要的，重大的；有意义的","cefr":"B2","freq_rank":719,
   "sentence_en":"There was a significant increase in sales.","sentence_zh":"销售额有显著增长。",
   "aids":{"morphemes":[M("sign","root","记号，标志"),M("i","connector","连接"),M("fic","root","做"),M("ant","suffix","…的")],
     "derivation":"sign(记号)+fic(做) → 做出了记号的、值得标记的 → 重要的、有意义的",
     "family":FAM("sign","记号、标志",[W("signal","信号"),W("signature","签名"),W("design","设计"),W("assign","分配")]),
     "mnemonic":"sign=记号;重要到需要专门做个记号标出来,就是 significant 重要的、显著的。",
     "forms":[F("significantly","adv.","显著地"),F("significance","n.","重要性；意义")]}},
  {"word":"response","phonetic":"rɪˈspɒns","pos":"n.","def":"回应，反应，回答","cefr":"B1","freq_rank":725,
   "sentence_en":"We received a positive response to our proposal.","sentence_zh":"我们的提案得到了积极回应。",
   "aids":{"morphemes":[M("re","prefix","回，返"),M("spons","root","承诺，回答"),M("e","suffix","名词结尾")],
     "derivation":"re(回)+spons(答) → 回过头来答复 → 回应",
     "family":FAM("spons/spond","承诺、回答",[W("respond","回应"),W("responsible","负责的"),W("sponsor","赞助者")]),
     "mnemonic":"spons=回答(想 respond);对方抛来一句,你回(re-)一句,就是 response 回应。",
     "forms":[F("respond","v.","回应"),F("responsive","adj.","反应积极的")]}},
  {"word":"attention","phonetic":"əˈtenʃən","pos":"n.","def":"注意，注意力","cefr":"A2","freq_rank":591,
   "sentence_en":"Please pay attention to the instructions.","sentence_zh":"请注意这些说明。",
   "aids":{"morphemes":[M("at","prefix","朝向(ad 变体)"),M("tent","root","伸展"),M("ion","suffix","名词后缀")],
     "derivation":"at(朝向)+tent(伸) → 把心神朝某处伸过去 → 注意",
     "family":FAM("tend/tent","伸展",[W("tend","倾向"),W("intend","打算"),W("extend","延伸"),W("tension","紧张")]),
     "mnemonic":"tent=伸(想 extend 延伸);把注意力朝(at-)一个方向伸过去、绷住,就是 attention 注意力。",
     "forms":[F("attentive","adj.","专注的，留心的")]}},
  {"word":"performance","phonetic":"pəˈfɔːməns","pos":"n.","def":"表现；表演；性能","cefr":"B1","freq_rank":675,
   "sentence_en":"The team's performance improved this season.","sentence_zh":"球队本赛季表现有所提升。",
   "aids":{"morphemes":[M("per","prefix","彻底，完全"),M("form","root","形式，做"),M("ance","suffix","名词后缀")],
     "derivation":"per(彻底)+form(做) → 彻底做出来、执行到位 → 表现、表演",
     "family":FAM("form","形式、做",[W("perform","执行；表演"),W("reform","改革"),W("transform","改变"),W("uniform","制服")]),
     "mnemonic":"per-(彻底)+form(做)——把事情彻底做出来、演出来,就是 performance 表现、表演、性能。",
     "forms":[F("perform","v.","执行；表演"),F("performer","n.","表演者")]}},
  {"word":"concern","phonetic":"kənˈsɜːn","pos":"n./v.","def":"担心，关切；涉及","cefr":"B1","freq_rank":717,
   "sentence_en":"There is growing concern about air pollution.","sentence_zh":"人们对空气污染越来越担忧。",
   "aids":{"morphemes":[M("con","prefix","一起，完全"),M("cern","root","筛，辨别")],
     "derivation":"con(完全)+cern(辨别) → 反复琢磨、放心不下 → 担心;引申'与…有关'",
     "family":FAM("cern/cret","筛、辨别",[W("discern","辨别"),W("secret","秘密(分开藏)"),W("certain","确定的")]),
     "mnemonic":"cern=辨别、筛(想 discern);一件事让你反复过筛、放不下,就是 concern 担心、关切。",
     "forms":[F("concerned","adj.","担心的；有关的"),F("concerning","prep.","关于")]}},
  # ===== 高频常见词(词根清晰或有好联想) =====
  {"word":"issue","phonetic":"ˈɪʃuː","pos":"n./v.","def":"问题，议题；发行，发布","cefr":"B1","freq_rank":248,
   "sentence_en":"We need to discuss this issue at the meeting.","sentence_zh":"我们需要在会上讨论这个问题。",
   "aids":{"morphemes":[M("iss","root","出去(exit 同源)"),M("ue","suffix","结尾")],
     "derivation":"iss(出去) → 冒出来的事 → 议题;放出去 → 发行",
     "family":FAM("it/iss","走、出",[W("exit","出口"),W("initial","最初的"),W("transit","运输，通过")]),
     "mnemonic":"iss 与'出去'同源;冒出来待解决的事=issue 问题;把报刊放出去=issue 发行。",
     "forms":[F("issued","v.","过去式/过去分词"),F("issues","n.","问题；各期(复数)")]}},
  {"word":"service","phonetic":"ˈsɜːvɪs","pos":"n.","def":"服务；公共设施","cefr":"A2","freq_rank":263,
   "sentence_en":"The hotel offers excellent service.","sentence_zh":"这家酒店提供优质服务。",
   "aids":{"morphemes":[M("serv","root","服务，伺候"),M("ice","suffix","名词后缀")],
     "derivation":"serv(服务)+ice → 服务这件事 → 服务",
     "family":FAM("serv","服务、保持",[W("serve","服务"),W("servant","仆人"),W("preserve","保存"),W("reserve","预订")]),
     "mnemonic":"serv=服务(想 serve 上菜、发球);为别人做事这件事,就是 service 服务。",
     "forms":[F("serve","v.","服务；供应"),F("services","n.","服务(复数)")]}},
  {"word":"community","phonetic":"kəˈmjuːnɪti","pos":"n.","def":"社区，社群；共同体","cefr":"B1","freq_rank":296,
   "sentence_en":"She is active in the local community.","sentence_zh":"她积极参与当地社区活动。",
   "aids":{"morphemes":[M("commun","root","共同，公共"),M("ity","suffix","名词后缀")],
     "derivation":"commun(共同)+ity → 共同生活的一群人 → 社区",
     "family":FAM("commun","共同",[W("common","共同的"),W("communicate","交流"),W("communist","共产主义的")]),
     "mnemonic":"commun=共同(想 common 共同的、communicate 交流);共享同一片地方的人群,就是 community 社区。",
     "forms":[F("communities","n.","社区(复数)")]}},
  {"word":"remain","phonetic":"rɪˈmeɪn","pos":"v.","def":"保持，仍是；剩余，留下","cefr":"B1","freq_rank":426,
   "sentence_en":"Despite the setback, she remained calm.","sentence_zh":"尽管遇到挫折，她依然保持冷静。",
   "aids":{"morphemes":[M("re","prefix","向后，仍"),M("main","root","留，停")],
     "derivation":"re(仍)+main(留) → 仍旧留在原处/原状 → 保持、剩余",
     "family":FAM("main/man","留、停留",[W("mansion","大宅(久居之所)"),W("permanent","永久的")]),
     "mnemonic":"别人走了它还(re-)留(main)在那儿,就是 remain 剩下、保持不变。",
     "forms":[F("remaining","adj.","剩余的"),F("remains","n.","剩余物；遗迹")]}},
  {"word":"develop","phonetic":"dɪˈveləp","pos":"v.","def":"发展，开发；(使)成长；冲洗(照片)","cefr":"A2","freq_rank":484,
   "sentence_en":"The company plans to develop new products.","sentence_zh":"公司计划开发新产品。",
   "aids":{"morphemes":[M("de","prefix","解开，展开"),M("velop","root","包裹")],
     "derivation":"de(解开)+velop(包) → 把包裹解开、展开 → 发展、显影",
     "family":FAM("velop","包裹",[W("envelope","信封(包起来)"),W("developer","开发者")]),
     "mnemonic":"velop=包(想 envelope 信封);把卷着的东西一层层解开(de-)铺展开,就是 develop 发展;把胶卷展开成像=显影。",
     "forms":[F("development","n.","发展，开发"),F("developing","adj.","发展中的")]}},
  {"word":"figure","phonetic":"ˈfɪɡə","pos":"n./v.","def":"数字；人物；图形；认为，估计","cefr":"B1","freq_rank":552,
   "sentence_en":"Sales figures rose sharply.","sentence_zh":"销售数字急剧上升。",
   "aids":{"morphemes":[M("fig","root","塑形，捏"),M("ure","suffix","名词后缀")],
     "derivation":"fig(塑形)+ure → 塑造出的形状/形象 → 图形、身形、人物",
     "family":FAM("fig","塑形",[W("figurative","比喻的"),W("configure","配置")]),
     "mnemonic":"fig=塑形;被塑造出来的形状(图形)、身形(人物)、或写出来的形(数字),都是 figure。短语 figure out=琢磨出。",
     "forms":[F("figures","n.","数字(复数)"),F("figured","v.","过去式/过去分词")]}},
  {"word":"current","phonetic":"ˈkʌrənt","pos":"adj./n.","def":"当前的，现行的；水流，电流","cefr":"B1","freq_rank":652,
   "sentence_en":"The current situation is improving.","sentence_zh":"目前的形势正在好转。",
   "aids":{"morphemes":[M("curr","root","跑，流"),M("ent","suffix","…的")],
     "derivation":"curr(跑、流)+ent → 正在流动/正在进行的 → 当前的;流动的水=水流",
     "family":FAM("curr/cur","跑、流",[W("occur","发生(跑到眼前)"),W("recur","再发生"),W("currency","货币(流通物)")]),
     "mnemonic":"curr=流、跑(想 currency 流通的货币);此刻正在流动、正在进行的,就是 current 当前的;水的流动=current 水流。",
     "forms":[F("currently","adv.","目前，现在"),F("currency","n.","货币")]}},
  {"word":"appear","phonetic":"əˈpɪə","pos":"v.","def":"出现，显得；出庭","cefr":"A2","freq_rank":395,
   "sentence_en":"A rainbow appeared after the rain.","sentence_zh":"雨后出现了一道彩虹。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("pear","root","出现，可见(par)")],
     "derivation":"ap(朝向)+pear(可见) → 朝眼前显现 → 出现",
     "family":FAM("par/pear","出现、可见",[W("apparent","明显的"),W("transparent","透明的"),W("appearance","外貌")]),
     "mnemonic":"pear≈可见(par);事物朝(ap-)你眼前一冒出来,就是 appear 出现;反义 disappear 消失。",
     "forms":[F("appearance","n.","外貌；出现"),F("apparent","adj.","明显的")]}},
  {"word":"cover","phonetic":"ˈkʌvə","pos":"v./n.","def":"覆盖；涵盖；封面；掩护","cefr":"A2","freq_rank":560,
   "sentence_en":"Snow covered the mountains.","sentence_zh":"雪覆盖了群山。",
   "aids":{"morphemes":[M("co","prefix","完全，一起"),M("ver","root","盖(cooperire)")],
     "derivation":"完全盖住 → 覆盖;引申'涵盖、掩护、封面'",
     "family":FAM("cover","盖",[W("discover","发现(揭开盖子)"),W("recover","恢复；重新盖上")]),
     "mnemonic":"把东西整个盖住=cover 覆盖;揭开盖子(dis-)=discover 发现。一词多义:涵盖内容、封面、掩护。",
     "forms":[F("coverage","n.","覆盖范围；报道"),F("covered","v.","过去式/过去分词")]}},
  {"word":"force","phonetic":"fɔːs","pos":"n./v.","def":"力量；武力；强迫","cefr":"A2","freq_rank":372,
   "sentence_en":"They used force to open the door.","sentence_zh":"他们用蛮力把门打开。",
   "aids":{"morphemes":[M("forc","root","力量，强(fort)"),M("e","suffix","结尾")],
     "derivation":"forc(力)+e → 力量;施力使人就范 → 强迫",
     "family":FAM("fort/forc","力量、强",[W("effort","努力"),W("fort","堡垒"),W("comfort","安慰(给力量)"),W("enforce","执行，强制")]),
     "mnemonic":"forc=力(想 fort 坚固的堡垒);强大的力量=force;用力逼人做=force 强迫。",
     "forms":[F("forced","adj.","被迫的，强迫的"),F("forceful","adj.","强有力的")]}},
  {"word":"effort","phonetic":"ˈefət","pos":"n.","def":"努力，尽力","cefr":"A2","freq_rank":454,
   "sentence_en":"It took a lot of effort to finish on time.","sentence_zh":"按时完成花了很大努力。",
   "aids":{"morphemes":[M("ef","prefix","向外(ex 变体)"),M("fort","root","力量，强")],
     "derivation":"ef(向外)+fort(力) → 把力气使出来 → 努力",
     "family":FAM("fort/forc","力量、强",[W("force","力量"),W("comfort","安慰"),W("fortitude","坚毅"),W("enforce","强制")]),
     "mnemonic":"fort=力(同 force);把力气向外(ef-)使出去,就是 effort 努力。",
     "forms":[F("effortless","adj.","不费力的"),F("efforts","n.","努力(复数)")]}},
  {"word":"interest","phonetic":"ˈɪntrəst","pos":"n./v.","def":"兴趣；利益；利息","cefr":"A2","freq_rank":416,
   "sentence_en":"She has a strong interest in art.","sentence_zh":"她对艺术有浓厚的兴趣。",
   "aids":{"morphemes":[M("inter","prefix","在…之间"),M("est","root","存在，是(esse)")],
     "derivation":"inter(之间)+est(存在) → 与你切身相关、卡在你和事之间的牵连 → 利益、兴趣",
     "family":FAM("est/esse","存在、是",[W("essence","本质"),W("present","在场的"),W("absent","缺席的")]),
     "mnemonic":"字面'处于…之间(inter-)的关系'——与你利害相关,便产生 interest 兴趣/利益;钱生的利=利息。",
     "forms":[F("interested","adj.","感兴趣的"),F("interesting","adj.","有趣的")]}},
  {"word":"major","phonetic":"ˈmeɪdʒə","pos":"adj./n./v.","def":"主要的，重大的；主修","cefr":"B1","freq_rank":444,
   "sentence_en":"Pollution is a major problem.","sentence_zh":"污染是一个重大问题。",
   "aids":{"morphemes":[M("maj","root","大(magn)"),M("or","suffix","较…的")],
     "derivation":"maj(大)+or(比较) → 更大的 → 主要的、重大的",
     "family":FAM("maj/magn","大",[W("majority","多数"),W("magnify","放大"),W("maximum","最大值"),W("master","主人")]),
     "mnemonic":"maj=大(想 magnify 放大、majority 多数);更大更重要的,就是 major 主要的;反义 minor 次要的。",
     "forms":[F("majority","n.","多数，大部分")]}},
  {"word":"economic","phonetic":"ˌiːkəˈnɒmɪk","pos":"adj.","def":"经济的，经济学的","cefr":"B2","freq_rank":453,
   "sentence_en":"The country is facing an economic crisis.","sentence_zh":"该国正面临经济危机。",
   "aids":{"morphemes":[M("eco","root","家，环境"),M("nom","root","管理，法则"),M("ic","suffix","…的")],
     "derivation":"eco(家)+nom(管理) → 持家理财之道 → 经济的",
     "family":FAM("eco","家、环境",[W("economy","经济"),W("ecology","生态学"),W("economical","节约的")]),
     "mnemonic":"eco=家(同 ecology 生态);nom=管理(想 astronomy 天文'管星');管好一家/一国的钱财,就是 economic 经济的。",
     "forms":[F("economy","n.","经济"),F("economical","adj.","节约的")]}},
  {"word":"material","phonetic":"məˈtɪəriəl","pos":"n./adj.","def":"材料，原料；物质的","cefr":"B1","freq_rank":641,
   "sentence_en":"Wood is a natural building material.","sentence_zh":"木材是一种天然建筑材料。",
   "aids":{"morphemes":[M("mater","root","母亲，来源"),M("ial","suffix","…的(名词)")],
     "derivation":"mater(母,引申'本源之物')+ial → 构成事物的本源之物 → 材料",
     "family":FAM("mater/matr","母亲、来源",[W("maternal","母亲的"),W("matrix","母体，矩阵")]),
     "mnemonic":"mater=母亲/本源(想 maternal 母亲的);构成东西的'母体'原料,就是 material 材料。",
     "forms":[F("materials","n.","材料(复数)")]}},
  {"word":"medical","phonetic":"ˈmedɪkəl","pos":"adj.","def":"医学的，医疗的","cefr":"A2","freq_rank":646,
   "sentence_en":"She needs urgent medical attention.","sentence_zh":"她需要紧急医疗救治。",
   "aids":{"morphemes":[M("medic","root","医治"),M("al","suffix","…的")],
     "derivation":"medic(医治)+al → 与医治有关的 → 医学的",
     "family":FAM("medic","医治",[W("medicine","药；医学"),W("medication","药物"),W("remedy","补救，疗法")]),
     "mnemonic":"medic=医(想 medicine 药);和治病有关的一切,就是 medical 医学的。",
     "forms":[F("medicine","n.","药；医学"),F("medically","adv.","医学上")]}},
  {"word":"private","phonetic":"ˈpraɪvɪt","pos":"adj./n.","def":"私人的，私密的；私营的","cefr":"A2","freq_rank":672,
   "sentence_en":"This is a private conversation.","sentence_zh":"这是一次私人谈话。",
   "aids":{"morphemes":[M("priv","root","单个，剥离"),M("ate","suffix","…的")],
     "derivation":"priv(单个)+ate → 属于个人、与公众分开的 → 私人的",
     "family":FAM("priv","单个、剥离",[W("privacy","隐私"),W("privilege","特权"),W("deprive","剥夺")]),
     "mnemonic":"priv=个人/剥离(想 privacy 隐私);从公众里单拎出来只属于个人的,就是 private 私人的;反义 public。",
     "forms":[F("privacy","n.","隐私"),F("privately","adv.","私下地")]}},
  {"word":"natural","phonetic":"ˈnætʃərəl","pos":"adj.","def":"自然的，天然的；天生的","cefr":"A2","freq_rank":715,
   "sentence_en":"The park protects natural habitats.","sentence_zh":"这个公园保护自然栖息地。",
   "aids":{"morphemes":[M("nat","root","出生"),M("ur","connector","连接"),M("al","suffix","…的")],
     "derivation":"nat(出生)+al → 与生俱来、天生如此的 → 自然的、天然的",
     "family":FAM("nat","出生",[W("nature","自然；本性"),W("native","本地的，天生的"),W("nation","国家"),W("innate","天生的")]),
     "mnemonic":"nat=出生(想 native 天生的、nature 自然);生下来本就如此、非人工的,就是 natural 自然的。",
     "forms":[F("nature","n.","自然；本性"),F("naturally","adv.","自然地")]}},
  {"word":"personal","phonetic":"ˈpɜːsənl","pos":"adj.","def":"个人的，私人的；亲自的","cefr":"A2","freq_rank":580,
   "sentence_en":"These are my personal belongings.","sentence_zh":"这些是我的私人物品。",
   "aids":{"morphemes":[M("person","root","人"),M("al","suffix","…的")],
     "derivation":"person(人)+al → 属于个人的 → 个人的",
     "family":FAM("person","人",[W("person","人"),W("personality","个性"),W("personnel","人员")]),
     "mnemonic":"person(人)+al——只属于某个人自己的,就是 personal 个人的、私人的。",
     "forms":[F("personality","n.","个性，人格"),F("personally","adv.","就个人而言；亲自")]}},
  {"word":"image","phonetic":"ˈɪmɪdʒ","pos":"n.","def":"形象；图像；影像","cefr":"B1","freq_rank":555,
   "sentence_en":"The company wants to improve its public image.","sentence_zh":"公司想改善其公众形象。",
   "aids":{"morphemes":[M("imag","root","模仿，像"),M("e","suffix","结尾")],
     "derivation":"imag(像) → 模仿出来的样子 → 形象、图像",
     "family":FAM("imag","像、模仿",[W("imagine","想象"),W("imaginary","虚构的"),W("imagination","想象力")]),
     "mnemonic":"imag=像(想 imagine 在脑中成像);模仿真实做出的样子,就是 image 形象、图像。",
     "forms":[F("imagine","v.","想象"),F("imagery","n.","意象")]}},
  {"word":"campaign","phonetic":"kæmˈpeɪn","pos":"n./v.","def":"运动，活动；战役；竞选","cefr":"B2","freq_rank":640,
   "sentence_en":"They launched a campaign against plastic waste.","sentence_zh":"他们发起了一场反对塑料垃圾的运动。",
   "aids":{"morphemes":[M("camp","root","田野，营地"),M("aign","suffix","结尾")],
     "derivation":"camp(田野/营地) → 古时军队在野外扎营作战 → 战役 → 有组织的运动",
     "family":FAM("camp","田野、营地",[W("camp","营地"),W("champion","冠军(战场取胜者)")]),
     "mnemonic":"camp=野外营地;古时大军在田野扎营打仗=campaign 战役;引申为有组织的宣传/竞选运动。",
     "forms":[F("campaigns","n.","运动(复数)"),F("campaigner","n.","活动家")]}},
  {"word":"seek","phonetic":"siːk","pos":"v.","def":"寻找，寻求；试图","cefr":"B1","freq_rank":668,
   "sentence_en":"Many people seek advice before investing.","sentence_zh":"许多人投资前会寻求建议。",
   "aids":{"morphemes":[M("seek","root","寻找")],
     "derivation":"古英语 sēcan '寻找'。过去式不规则:sought。",
     "family":FAM("","相关词",[W("seeker","寻求者"),W("sought-after","抢手的")]),
     "mnemonic":"seek 本身就是'找';注意过去式是 sought(不规则),别写成 seeked。短语 seek out=找出。",
     "forms":[F("sought","v.","过去式/过去分词"),F("seeker","n.","寻求者")]}},
  {"word":"goal","phonetic":"ɡəʊl","pos":"n.","def":"目标；球门，进球","cefr":"A2","freq_rank":681,
   "sentence_en":"Her goal is to become a doctor.","sentence_zh":"她的目标是成为一名医生。",
   "aids":{"morphemes":[M("goal","root","目标，终点")],
     "derivation":"原指赛跑'终点线',引申为要达到的目标;球类里的'球门'。",
     "family":FAM("","相关词",[W("goalkeeper","守门员"),W("goalpost","球门柱")]),
     "mnemonic":"想象跑道尽头的终点线,或球场的球门——你全力奔向的那个点,就是 goal 目标。",
     "forms":[F("goals","n.","目标(复数)")]}},
  {"word":"couple","phonetic":"ˈkʌpl","pos":"n./v.","def":"一对，夫妇；几个；连接","cefr":"A2","freq_rank":531,
   "sentence_en":"A couple of friends came to visit.","sentence_zh":"几个朋友来做客。",
   "aids":{"morphemes":[M("coupl","root","连接，成对(cop)"),M("e","suffix","结尾")],
     "derivation":"coupl(连接) → 连在一起的两个 → 一对、夫妇",
     "family":FAM("cop/coupl","连接",[W("couple","一对"),W("cooperate","合作")]),
     "mnemonic":"把两个连(coupl)在一起,就是 couple 一对、夫妇;口语 a couple of=两三个。",
     "forms":[F("coupled","v.","连接(过去式)")]}},
  {"word":"subject","phonetic":"ˈsʌbdʒekt","pos":"n./adj./v.","def":"主题，学科；主语；使遭受","cefr":"B1","freq_rank":670,
   "sentence_en":"Maths is my favourite subject.","sentence_zh":"数学是我最喜欢的科目。",
   "aids":{"morphemes":[M("sub","prefix","在下"),M("ject","root","扔，投")],
     "derivation":"sub(在下)+ject(扔) → 置于下方讨论/管辖的 → 主题、臣民;使处于…之下 → 使遭受",
     "family":FAM("ject","扔、投",[W("project","项目"),W("reject","拒绝"),W("inject","注射"),W("object","物体；反对")]),
     "mnemonic":"ject=扔(想 reject);被摆在(sub-下方)台面上供讨论的,就是 subject 主题、学科;被置于统治之下=臣民/使遭受。",
     "forms":[F("subjective","adj.","主观的"),F("subjects","n.","科目(复数)")]}},
  {"word":"series","phonetic":"ˈsɪəriːz","pos":"n.","def":"系列，连续；丛书","cefr":"B1","freq_rank":718,
   "sentence_en":"We watched a series of documentaries.","sentence_zh":"我们看了一系列纪录片。",
   "aids":{"morphemes":[M("seri","root","连接，串"),M("es","suffix","结尾")],
     "derivation":"seri(串)+es → 一个接一个串起来 → 系列",
     "family":FAM("ser","连接、串",[W("serial","连续的，系列的"),W("insert","插入")]),
     "mnemonic":"seri=串(想 serial 连续剧);一个接一个串成一条,就是 series 系列;单复数同形。",
     "forms":[F("serial","adj.","连续的；系列的")]}},
  {"word":"board","phonetic":"bɔːd","pos":"n./v.","def":"板；董事会；膳食；登(车/船/机)","cefr":"A2","freq_rank":667,
   "sentence_en":"Passengers may now board the plane.","sentence_zh":"乘客现在可以登机了。",
   "aids":{"morphemes":[M("board","root","木板")],
     "derivation":"本义'木板';引申:围桌而坐的一群人=董事会;上'船板'=登船/登机。",
     "family":FAM("","相关词",[W("aboard","在船/车上"),W("keyboard","键盘"),W("blackboard","黑板")]),
     "mnemonic":"board=木板;一块块板→黑板/告示板;围着会议桌(board)的人=董事会;踏上船板=board 登机/船。",
     "forms":[F("boarding","n.","登机；寄宿"),F("aboard","adv.","在(车船机)上")]}},
  {"word":"agency","phonetic":"ˈeɪdʒənsi","pos":"n.","def":"代理机构，中介；(政府)局","cefr":"B2","freq_rank":694,
   "sentence_en":"She found a job through an agency.","sentence_zh":"她通过中介找到了工作。",
   "aids":{"morphemes":[M("ag","root","做，行动"),M("ency","suffix","名词后缀")],
     "derivation":"ag(做)+ency → 替人做事的机构 → 代理机构",
     "family":FAM("ag/act","做、行动",[W("agent","代理人"),W("act","行动"),W("agenda","议程"),W("active","积极的")]),
     "mnemonic":"ag=做(想 agent 代理人、act 行动);替你出面办事的机构,就是 agency 代理机构、中介。",
     "forms":[F("agent","n.","代理人，特工"),F("agencies","n.","机构(复数)")]}},
  {"word":"administration","phonetic":"ədˌmɪnɪˈstreɪʃən","pos":"n.","def":"管理，行政；政府","cefr":"B2","freq_rank":635,
   "sentence_en":"He works in business administration.","sentence_zh":"他从事工商管理工作。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("minister","root","服务，管理"),M("ation","suffix","名词后缀")],
     "derivation":"ad(朝向)+minister(服务、管理) → 主持服务与管理 → 行政、管理",
     "family":FAM("minister","服务、管理",[W("minister","部长"),W("administer","管理，执行")]),
     "mnemonic":"minister=部长/管事(动词'管理');主持管理这件事,就是 administration 行政、管理(也指某届政府)。",
     "forms":[F("administer","v.","管理，执行"),F("administrative","adj.","行政的")]}},
]


def main():
    with open(SEED, encoding="utf-8") as f:
        data = json.load(f)
    existing = {w["word"].lower() for w in data["words"]}
    added = []
    skipped = []
    for w in BATCH2:
        if w["word"].lower() in existing:
            skipped.append(w["word"]); continue
        data["words"].append(w)
        existing.add(w["word"].lower())
        added.append(w["word"])
    data["meta"]["generated_batches"] = 2
    with open(SEED, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"追加 {len(added)} 词;跳过(已存在) {len(skipped)}: {skipped}")
    print(f"seed 现共 {len(data['words'])} 词")


if __name__ == "__main__":
    main()
