#!/usr/bin/env python
# 第十四批(约52词):逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -ject 扔
  {"word":"objective","phonetic":"əbˈdʒektɪv","pos":"n./adj.","def":"目标；客观的","cefr":"B2","freq_rank":23,
   "sentence_en":"Our main objective is to cut costs.","sentence_zh":"我们的主要目标是削减成本。",
   "aids":{"morphemes":[M("ob","prefix","对着"),M("ject","root","扔，投"),M("ive","suffix","…的")],
     "derivation":"ob(对着)+ject(投) → 投在眼前作靶子的 → 目标;不掺主观的 → 客观的",
     "family":FAM("ject","扔、投",[W("object","物体；反对"),W("project","项目"),W("reject","拒绝"),W("inject","注射")]),
     "mnemonic":"ject=扔(和 object 一家);摆在眼前当靶子瞄的=objective 目标;只看外物不掺私见=客观的;反义 subjective。",
     "forms":[F("objectively","adv.","客观地"),F("objectives","n.","目标(复数)")]}},
  # -mens 测量
  {"word":"dimension","phonetic":"daɪˈmenʃən","pos":"n.","def":"维度，方面；尺寸","cefr":"B2","freq_rank":28,
   "sentence_en":"The problem has a political dimension.","sentence_zh":"这个问题有政治层面。",
   "aids":{"morphemes":[M("di","prefix","分开(dis)"),M("mens","root","测量"),M("ion","suffix","名词后缀")],
     "derivation":"di(分)+mens(测量) → 分别量出的方向/尺度 → 维度、尺寸",
     "family":FAM("mens/meter","测量",[W("measure","测量"),W("immense","巨大的(无法测量)"),W("dimension","维度")]),
     "mnemonic":"mens=测量(想 measure);沿不同方向量出的度=dimension 维度;引申'方面';具体量出的大小=尺寸。",
     "forms":[F("dimensions","n.","尺寸(复数)"),F("dimensional","adj.","维度的")]}},
  # -front 前额/面
  {"word":"confront","phonetic":"kənˈfrʌnt","pos":"v.","def":"面对，对抗；使对质","cefr":"B2","freq_rank":27,
   "sentence_en":"We must confront the problem directly.","sentence_zh":"我们必须直面这个问题。",
   "aids":{"morphemes":[M("con","prefix","一起，面对面"),M("front","root","前额，正面")],
     "derivation":"con(面对面)+front(正面) → 正面相对 → 面对、对抗",
     "family":FAM("front","前额、正面",[W("front","前面"),W("frontier","边疆"),W("affront","冒犯")]),
     "mnemonic":"front=正面(想 front 前面);正面(con-)顶上去、迎难而上,就是 confront 面对、对抗。",
     "forms":[F("confrontation","n.","对抗"),F("confronted","v.","过去式/过去分词")]}},
  # -phan 显现
  {"word":"phenomenon","phonetic":"fɪˈnɒmɪnən","pos":"n.","def":"现象；非凡的人/事","cefr":"B2","freq_rank":41,
   "sentence_en":"Rainbows are a natural phenomenon.","sentence_zh":"彩虹是一种自然现象。",
   "aids":{"morphemes":[M("pheno","root","显现(phan)"),M("menon","suffix","名词后缀")],
     "derivation":"phan(显现)→ 显现出来被观察到的 → 现象",
     "family":FAM("phan/phas","显现",[W("emphasize","强调"),W("phase","阶段"),W("fantasy","幻想")]),
     "mnemonic":"phan=显现(和 emphasize 一家);展现在眼前、可观察到的事,就是 phenomenon 现象;复数 phenomena。",
     "forms":[F("phenomena","n.","现象(复数)"),F("phenomenal","adj.","非凡的")]}},
  # -ven 来
  {"word":"convention","phonetic":"kənˈvenʃən","pos":"n.","def":"惯例，习俗；大会；公约","cefr":"B2","freq_rank":43,
   "sentence_en":"It's a social convention to shake hands.","sentence_zh":"握手是一种社交惯例。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("ven","root","来"),M("tion","suffix","名词后缀")],
     "derivation":"con(一起)+ven(来) → 大家一起来聚/共同来遵守 → 大会、惯例",
     "family":FAM("ven","来",[W("event","事件"),W("prevent","预防"),W("invent","发明"),W("avenue","大道")]),
     "mnemonic":"ven=来(想 event);众人一起来开的会=大会;共同来遵守的规矩=惯例、公约,都是 convention。",
     "forms":[F("conventional","adj.","传统的")]}},
  {"word":"conventional","phonetic":"kənˈvenʃənl","pos":"adj.","def":"传统的，常规的","cefr":"B2","freq_rank":79,
   "sentence_en":"He prefers conventional methods.","sentence_zh":"他偏爱常规方法。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("ven","root","来"),M("tional","suffix","…的")],
     "derivation":"convention(惯例)+al → 合乎惯例的 → 传统的、常规的",
     "family":FAM("ven","来",[W("convention","惯例"),W("prevent","预防"),W("invent","发明")]),
     "mnemonic":"convention(惯例)的形容词;沿袭老规矩、不新奇的,就是 conventional;反义 unconventional/novel。",
     "forms":[F("conventionally","adv.","照惯例地")]}},
  {"word":"intention","phonetic":"ɪnˈtenʃən","pos":"n.","def":"意图，打算","cefr":"B1","freq_rank":64,
   "sentence_en":"I have no intention of leaving.","sentence_zh":"我没有离开的打算。",
   "aids":{"morphemes":[M("in","prefix","向"),M("tent","root","伸展"),M("ion","suffix","名词后缀")],
     "derivation":"in(向)+tent(伸) → 心朝目标伸过去 → 意图",
     "family":FAM("tend/tent","伸展",[W("intend","打算"),W("tend","倾向"),W("attend","出席"),W("extend","延伸")]),
     "mnemonic":"tent=伸(和 intend 一家);心意朝某目标伸出去,就是 intention 意图;good intentions 好意。",
     "forms":[F("intend","v.","打算"),F("intentional","adj.","故意的")]}},
  # -sist 站
  {"word":"resist","phonetic":"rɪˈzɪst","pos":"v.","def":"抵抗，抵制；忍住","cefr":"B1","freq_rank":42,
   "sentence_en":"I couldn't resist the chocolate.","sentence_zh":"我没能忍住不吃巧克力。",
   "aids":{"morphemes":[M("re","prefix","反"),M("sist","root","站")],
     "derivation":"re(反)+sist(站) → 反着站住顶回去 → 抵抗",
     "family":FAM("sist","站",[W("insist","坚持"),W("consist","组成"),W("assist","协助"),W("exist","存在")]),
     "mnemonic":"sist=站;顶着反(re-)方向站稳不退,就是 resist 抵抗;忍住诱惑也用 resist;resistance 抵抗。",
     "forms":[F("resistance","n.","抵抗"),F("resistant","adj.","有抵抗力的")]}},
  {"word":"assist","phonetic":"əˈsɪst","pos":"v.","def":"协助，帮助","cefr":"B1","freq_rank":45,
   "sentence_en":"A nurse assisted the doctor.","sentence_zh":"一名护士协助医生。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sist","root","站")],
     "derivation":"as(朝向)+sist(站) → 站到旁边帮忙 → 协助",
     "family":FAM("sist","站",[W("insist","坚持"),W("resist","抵抗"),W("consist","组成"),W("exist","存在")]),
     "mnemonic":"sist=站;站到你身旁(as-)搭把手,就是 assist 协助;assistance 帮助/assistant 助手。",
     "forms":[F("assistance","n.","帮助"),F("assistant","n.","助手")]}},
  # -stor 站/储
  {"word":"restore","phonetic":"rɪˈstɔː","pos":"v.","def":"恢复，修复；归还","cefr":"B2","freq_rank":74,
   "sentence_en":"They restored the old building.","sentence_zh":"他们修复了这座旧建筑。",
   "aids":{"morphemes":[M("re","prefix","再，回"),M("store","root","建立，站(staur)")],
     "derivation":"re(再)+store(立) → 重新立起、复原 → 恢复、修复",
     "family":FAM("staur/store","站、立",[W("store","储存"),W("restaurant","餐厅(恢复元气处)")]),
     "mnemonic":"store≈立/复(想 restaurant 让人'恢复'元气的地方);把旧貌重新(re-)立起来,就是 restore 修复、恢复。",
     "forms":[F("restoration","n.","修复，恢复")]}},
  # -sign 记号
  {"word":"assign","phonetic":"əˈsaɪn","pos":"v.","def":"分配，指派；赋值","cefr":"B2","freq_rank":104,
   "sentence_en":"The teacher assigned homework.","sentence_zh":"老师布置了作业。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sign","root","记号，标记")],
     "derivation":"as(朝向)+sign(标记) → 标记归给某人 → 分配、指派",
     "family":FAM("sign","记号、标志",[W("sign","符号"),W("signal","信号"),W("design","设计"),W("signature","签名")]),
     "mnemonic":"sign=标记(和 sign 一家);给某人贴上'归你办'的标记,就是 assign 分配、指派;assignment 任务。",
     "forms":[F("assignment","n.","任务；作业"),F("assigned","v.","过去式/过去分词")]}},
  # -corpor 身体
  {"word":"incorporate","phonetic":"ɪnˈkɔːpəreɪt","pos":"v.","def":"合并，纳入；组成公司","cefr":"C1","freq_rank":97,
   "sentence_en":"We incorporated your ideas into the plan.","sentence_zh":"我们把你的想法纳入了计划。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("corpor","root","身体，团体"),M("ate","suffix","动词后缀")],
     "derivation":"in(向内)+corpor(身体) → 并入一个整体 → 合并、纳入",
     "family":FAM("corpor/corp","身体、团体",[W("corporate","公司的"),W("corporation","公司"),W("corpse","尸体")]),
     "mnemonic":"corpor=身体/整体(和 corporate 一家);把新东西并入(in-)一个整体,就是 incorporate 纳入、合并。",
     "forms":[F("incorporation","n.","合并；公司组建")]}},
  # -voc 叫
  {"word":"advocate","phonetic":"ˈædvəkeɪt","pos":"v./n.","def":"提倡，主张；拥护者","cefr":"C1","freq_rank":111,
   "sentence_en":"She advocates for animal rights.","sentence_zh":"她倡导动物权利。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("voc","root","叫，声音"),M("ate","suffix","动词后缀")],
     "derivation":"ad(朝向)+voc(叫) → 为某事出声疾呼 → 提倡",
     "family":FAM("voc/vok","叫、声音",[W("vocal","嗓音的"),W("voice","声音"),W("provoke","激起"),W("advocate","提倡")]),
     "mnemonic":"voc=叫(想 voice 声音);为某主张公开发声力挺,就是 advocate 提倡;发声支持的人=拥护者。",
     "forms":[F("advocacy","n.","拥护，提倡")]}},
  # -sure 确保
  {"word":"assure","phonetic":"əˈʃʊə","pos":"v.","def":"向…保证，使确信","cefr":"B2","freq_rank":85,
   "sentence_en":"I assure you it's safe.","sentence_zh":"我向你保证这是安全的。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sure","root","确定")],
     "derivation":"as(朝向)+sure(确定) → 让某人确定放心 → 使确信",
     "family":FAM("sur/secur","确保、安全",[W("sure","确定的"),W("ensure","确保"),W("insure","保险"),W("secure","安全的")]),
     "mnemonic":"sure=确定;拍胸脯让对方(as-)放心,就是 assure 使确信;区分 ensure(确保事情)/insure(买保险)。",
     "forms":[F("assurance","n.","保证；确信")]}},
  {"word":"secure","phonetic":"sɪˈkjʊə","pos":"adj./v.","def":"安全的，牢固的；获得，保障","cefr":"B2","freq_rank":50,
   "sentence_en":"Make sure the door is secure.","sentence_zh":"确保门是锁牢的。",
   "aids":{"morphemes":[M("se","prefix","离开，脱离"),M("cure","root","担心")],
     "derivation":"se(脱离)+cure(担心) → 脱离忧虑的 → 安全的",
     "family":FAM("cure","担心、关心",[W("security","安全"),W("cure","治愈"),W("curious","好奇的")]),
     "mnemonic":"cure=担心(想 security);脱离(se-)了担忧、稳当,就是 secure 安全的;设法弄牢/弄到手=secure 获得。",
     "forms":[F("security","n.","安全"),F("securely","adv.","牢固地")]}},
  # -cogn 知
  {"word":"recognition","phonetic":"ˌrekəɡˈnɪʃən","pos":"n.","def":"认出，识别；承认，认可","cefr":"B2","freq_rank":37,
   "sentence_en":"She received recognition for her work.","sentence_zh":"她的工作获得了认可。",
   "aids":{"morphemes":[M("re","prefix","再"),M("cogn","root","知道"),M("ition","suffix","名词后缀")],
     "derivation":"recognize(再认知)+ion → 认出/认可的行为 → 识别、认可",
     "family":FAM("cogn/gno","知道",[W("recognize","认出"),W("cognitive","认知的"),W("ignore","忽视"),W("diagnose","诊断")]),
     "mnemonic":"cogn=知(和 recognize 一家);再一次确认知道=识别;公开表示认知其价值=认可,都是 recognition。",
     "forms":[F("recognize","v.","认出")]}},
  # -neg 否
  {"word":"negotiate","phonetic":"nɪˈɡəʊʃieɪt","pos":"v.","def":"谈判，协商；顺利通过","cefr":"B2","freq_rank":72,
   "sentence_en":"They negotiated a better price.","sentence_zh":"他们谈成了更好的价格。",
   "aids":{"morphemes":[M("neg","prefix","不"),M("oti","root","悠闲(otium)"),M("ate","suffix","动词后缀")],
     "derivation":"neg(不)+oti(悠闲) → 不得闲、忙于做生意商谈 → 谈判",
     "family":FAM("neg","否定",[W("negative","否定的"),W("neglect","忽视"),W("deny","否认")]),
     "mnemonic":"neg(不)+oti(闲)——'不得空闲'地忙着讨价还价,就是 negotiate 谈判;negotiation 谈判。",
     "forms":[F("negotiation","n.","谈判")]}},
  # -order 秩序
  {"word":"disorder","phonetic":"dɪsˈɔːdə","pos":"n.","def":"混乱，杂乱；失调，疾病","cefr":"B2","freq_rank":15,
   "sentence_en":"The room was in complete disorder.","sentence_zh":"房间里一片狼藉。",
   "aids":{"morphemes":[M("dis","prefix","不，反"),M("order","root","秩序")],
     "derivation":"dis(不)+order(秩序) → 没有秩序 → 混乱;身体秩序乱=失调、疾病",
     "family":FAM("order","秩序",[W("order","秩序；命令"),W("ordinary","普通的"),W("orderly","有序的")]),
     "mnemonic":"dis-(不)+order(秩序)——毫无条理,就是 disorder 混乱;身体机能'失序'=失调/疾病(sleep disorder 睡眠障碍)。",
     "forms":[F("disorders","n.","失调(复数)")]}},
  {"word":"extraordinary","phonetic":"ɪkˈstrɔːdnri","pos":"adj.","def":"非凡的，异常的","cefr":"B2","freq_rank":113,
   "sentence_en":"She has an extraordinary talent.","sentence_zh":"她有非凡的天赋。",
   "aids":{"morphemes":[M("extra","prefix","以外"),M("ordinary","root","普通的")],
     "derivation":"extra(以外)+ordinary(普通) → 超出普通之外的 → 非凡的",
     "family":FAM("ordin/order","秩序、常规",[W("ordinary","普通的"),W("order","秩序"),W("coordinate","协调")]),
     "mnemonic":"extra(以外)+ordinary(普通)——超出寻常范围的,就是 extraordinary 非凡的;反义 ordinary 普通的。",
     "forms":[F("extraordinarily","adv.","非凡地")]}},
  # -vis 看
  {"word":"provision","phonetic":"prəˈvɪʒən","pos":"n.","def":"供应，提供；条款；预备","cefr":"C1","freq_rank":106,
   "sentence_en":"The provision of clean water is vital.","sentence_zh":"清洁水的供应至关重要。",
   "aids":{"morphemes":[M("pro","prefix","预先"),M("vis","root","看"),M("ion","suffix","名词后缀")],
     "derivation":"pro(预先)+vis(看) → 预先看到并备好 → 供应、预备;合同里预先看定的=条款",
     "family":FAM("vis/vid","看",[W("provide","提供"),W("vision","视力"),W("visible","可见的"),W("supervise","监督")]),
     "mnemonic":"vis=看(和 provide 一家);预先(pro-)看到需要并备好、供给,就是 provision;合同预定的=条款。",
     "forms":[F("provisions","n.","条款；给养(复数)")]}},
  # -sens 感觉
  {"word":"sensitive","phonetic":"ˈsensətɪv","pos":"adj.","def":"敏感的；灵敏的；体贴的","cefr":"B2","freq_rank":58,
   "sentence_en":"She is sensitive to criticism.","sentence_zh":"她对批评很敏感。",
   "aids":{"morphemes":[M("sens","root","感觉"),M("itive","suffix","…的")],
     "derivation":"sens(感觉)+itive → 感觉灵敏的 → 敏感的",
     "family":FAM("sens/sent","感觉",[W("sense","感觉"),W("sensible","明智的"),W("sensation","感觉"),W("consent","同意")]),
     "mnemonic":"sens=感觉(想 sense);对刺激反应强、感觉灵的,就是 sensitive 敏感的;sensitivity 敏感度。",
     "forms":[F("sensitivity","n.","敏感性")]}},
  # -mix 混
  {"word":"mixture","phonetic":"ˈmɪkstʃə","pos":"n.","def":"混合物，混合","cefr":"B1","freq_rank":26,
   "sentence_en":"Air is a mixture of gases.","sentence_zh":"空气是多种气体的混合物。",
   "aids":{"morphemes":[M("mix","root","混合"),M("ture","suffix","名词后缀")],
     "derivation":"mix(混合)+ture → 混到一起的东西 → 混合物",
     "family":FAM("mix/misc","混合",[W("mix","混合"),W("miscellaneous","混杂的")]),
     "mnemonic":"mix=混;搅到一起的一堆,就是 mixture 混合物;a mixture of=…的混合。",
     "forms":[F("mix","v.","混合"),F("mixtures","n.","混合物(复数)")]}},
  # -pli 含
  {"word":"implication","phonetic":"ˌɪmplɪˈkeɪʃən","pos":"n.","def":"影响，可能的后果；暗示，含义","cefr":"C1","freq_rank":34,
   "sentence_en":"Consider the implications of your decision.","sentence_zh":"考虑一下你决定的影响。",
   "aids":{"morphemes":[M("im","prefix","向内"),M("plic","root","折叠，卷"),M("ation","suffix","名词后缀")],
     "derivation":"im(向内)+plic(折) → 折叠隐含在里面的 → 暗示、内在后果",
     "family":FAM("plic/ply","折叠、卷",[W("imply","暗示"),W("apply","申请"),W("complicated","复杂的"),W("multiply","乘")]),
     "mnemonic":"plic=折(和 imply 一家);折卷在内、没明说的东西=含义/暗示;牵连出的连锁后果=影响,都是 implication。",
     "forms":[F("imply","v.","暗示"),F("implications","n.","影响(复数)")]}},
  # -part 部分
  {"word":"apparent","phonetic":"əˈpærənt","pos":"adj.","def":"明显的；表面上的","cefr":"B2","freq_rank":55,
   "sentence_en":"It was apparent that she was tired.","sentence_zh":"很明显她累了。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("par","root","出现，可见"),M("ent","suffix","…的")],
     "derivation":"ap(朝向)+par(可见) → 显现在眼前的 → 明显的",
     "family":FAM("par/pear","出现、可见",[W("appear","出现"),W("appearance","外表"),W("transparent","透明的")]),
     "mnemonic":"par=可见(和 appear 一家);一看就清楚的=明显的;仅表面看似如此的=表面上的(apparent reason)。",
     "forms":[F("apparently","adv.","显然；据说")]}},
  # 高频名词/动词
  {"word":"reputation","phonetic":"ˌrepjuˈteɪʃən","pos":"n.","def":"名声，声誉","cefr":"B2","freq_rank":25,
   "sentence_en":"The company has a good reputation.","sentence_zh":"这家公司声誉良好。",
   "aids":{"morphemes":[M("re","prefix","再三"),M("put","root","想，认为"),M("ation","suffix","名词后缀")],
     "derivation":"re(再三)+put(认为) → 大家反复评说认定的 → 名声",
     "family":FAM("put","想、算",[W("compute","计算"),W("dispute","争论"),W("reputation","名声")]),
     "mnemonic":"put=想/认为(想 compute 计算);众人反复评说、公认的评价,就是 reputation 名声。",
     "forms":[F("reputable","adj.","有信誉的")]}},
  {"word":"consideration","phonetic":"kənˌsɪdəˈreɪʃən","pos":"n.","def":"考虑，思考；体贴","cefr":"B2","freq_rank":49,
   "sentence_en":"Take all factors into consideration.","sentence_zh":"把所有因素都考虑进去。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("sider","root","星"),M("ation","suffix","名词后缀")],
     "derivation":"consider(观星思量)+ation → 仔细思量 → 考虑",
     "family":FAM("sider","星",[W("consider","考虑"),W("desire","渴望"),W("sidereal","恒星的")]),
     "mnemonic":"sider=星(古人观星思量);把事情反复掂量,就是 consideration 考虑;take into consideration 考虑到。",
     "forms":[F("consider","v.","考虑")]}},
  {"word":"assumption","phonetic":"əˈsʌmpʃən","pos":"n.","def":"假设，臆断；承担","cefr":"B2","freq_rank":101,
   "sentence_en":"Your argument is based on a false assumption.","sentence_zh":"你的论点基于错误的假设。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sumpt","root","拿，取(sume)"),M("ion","suffix","名词后缀")],
     "derivation":"assume(拿来当前提)+ion → 未经验证就采信的 → 假设",
     "family":FAM("sume/sumpt","拿、取",[W("assume","假定"),W("consume","消耗"),W("resume","恢复；简历")]),
     "mnemonic":"sumpt=拿(和 assume 一家);不加证明先拿来当真的东西,就是 assumption 假设;make an assumption 假设。",
     "forms":[F("assume","v.","假定")]}},
  {"word":"impression","phonetic":"ɪmˈpreʃən","pos":"n.","def":"印象，感想；印记","cefr":"B1","freq_rank":70,
   "sentence_en":"He made a good impression on the interviewer.","sentence_zh":"他给面试官留下了好印象。",
   "aids":{"morphemes":[M("im","prefix","向内"),M("press","root","压"),M("ion","suffix","名词后缀")],
     "derivation":"im(向内)+press(压) → 压印进心里的 → 印象、印记",
     "family":FAM("press","压",[W("press","压"),W("express","表达"),W("pressure","压力"),W("depress","使沮丧")]),
     "mnemonic":"press=压(想 impress 使印象深);人/事在心里'压'下的痕迹,就是 impression 印象;first impression 第一印象。",
     "forms":[F("impress","v.","使印象深刻"),F("impressive","adj.","令人印象深刻的")]}},
  {"word":"recipe","phonetic":"ˈresɪpi","pos":"n.","def":"食谱，配方；秘诀","cefr":"B1","freq_rank":59,
   "sentence_en":"This is my grandmother's recipe.","sentence_zh":"这是我祖母的食谱。",
   "aids":{"morphemes":[M("re","prefix","回，取"),M("cip","root","拿(cap)"),M("e","suffix","结尾")],
     "derivation":"拉丁 recipe'取(药)'(医嘱头语);取用配料的说明 → 配方、食谱",
     "family":FAM("cip/cept","拿、取",[W("receive","收到"),W("accept","接受"),W("recipient","接受者")]),
     "mnemonic":"cip=拿(和 receive 一家);告诉你'取哪些料、怎么配'的说明,就是 recipe 食谱;a recipe for success 成功秘诀。",
     "forms":[F("recipes","n.","食谱(复数)")]}},
  {"word":"consultant","phonetic":"kənˈsʌltənt","pos":"n.","def":"顾问，咨询师","cefr":"B2","freq_rank":47,
   "sentence_en":"They hired a business consultant.","sentence_zh":"他们聘请了一位商业顾问。",
   "aids":{"morphemes":[M("consult","root","商议，请教"),M("ant","suffix","…的人")],
     "derivation":"consult(咨询)+ant → 供人咨询请教的人 → 顾问",
     "family":FAM("consult","商议",[W("consult","咨询"),W("consultation","咨询")]),
     "mnemonic":"consult=咨询请教;专供你请教、出主意的人,就是 consultant 顾问;动词 consult 咨询。",
     "forms":[F("consult","v.","咨询"),F("consultation","n.","咨询")]}},
  {"word":"administrator","phonetic":"ədˈmɪnɪstreɪtə","pos":"n.","def":"管理员，行政人员","cefr":"B2","freq_rank":48,
   "sentence_en":"The system administrator fixed the issue.","sentence_zh":"系统管理员解决了问题。",
   "aids":{"morphemes":[M("administr","root","管理"),M("ator","suffix","…的人")],
     "derivation":"administer(管理)+ator → 管理的人 → 管理员",
     "family":FAM("minister","服务、管理",[W("administer","管理"),W("administration","行政"),W("minister","部长")]),
     "mnemonic":"和 administration(行政)一家;负责管理运作的人,就是 administrator 管理员;admin 是它的缩写。",
     "forms":[F("administer","v.","管理"),F("administrative","adj.","行政的")]}},
  {"word":"enterprise","phonetic":"ˈentəpraɪz","pos":"n.","def":"企业；事业；进取心","cefr":"B2","freq_rank":54,
   "sentence_en":"She runs a small enterprise.","sentence_zh":"她经营着一家小企业。",
   "aids":{"morphemes":[M("enter","prefix","在…之间(inter)"),M("prise","root","抓取(prehend)")],
     "derivation":"enter(之间)+prise(抓) → 从中抓住机会去做的事 → 事业、企业",
     "family":FAM("prise/prehend","抓取",[W("comprise","包含"),W("surprise","惊讶"),W("prison","监狱")]),
     "mnemonic":"prise=抓(想 surprise 冷不防抓住);抓住机会开创的一摊事业/公司,就是 enterprise;也指'进取心'。",
     "forms":[F("enterprises","n.","企业(复数)")]}},
  {"word":"diversity","phonetic":"daɪˈvɜːsɪti","pos":"n.","def":"多样性，差异","cefr":"B2","freq_rank":68,
   "sentence_en":"The city celebrates cultural diversity.","sentence_zh":"这座城市推崇文化多样性。",
   "aids":{"morphemes":[M("di","prefix","分开(dis)"),M("vers","root","转，方向"),M("ity","suffix","名词后缀")],
     "derivation":"di(分开)+vers(转) → 各自转向不同 → 多样性",
     "family":FAM("vers/vert","转",[W("diverse","多样的"),W("reverse","颠倒"),W("convert","转变"),W("version","版本")]),
     "mnemonic":"vers=转(想 diverse 多样的);各自朝不同方向、种类繁多,就是 diversity 多样性;biodiversity 生物多样性。",
     "forms":[F("diverse","adj.","多样的")]}},
  {"word":"channel","phonetic":"ˈtʃænl","pos":"n./v.","def":"频道；渠道；海峡；引导","cefr":"B1","freq_rank":65,
   "sentence_en":"Change the TV channel.","sentence_zh":"换个电视频道。",
   "aids":{"morphemes":[M("chan","root","管，沟(canna 芦苇管)"),M("nel","suffix","小")],
     "derivation":"与 canal(运河)同源'管道';水/信息流过的道 → 渠道、频道、海峡",
     "family":FAM("can/chan","管、沟",[W("canal","运河"),W("cannon","大炮(管状)")]),
     "mnemonic":"channel 与 canal(运河)同源;水流的沟=海峡;信息流的道=频道/渠道;把资源'导'向某处=channel 引导。",
     "forms":[F("channels","n.","渠道(复数)")]}},
  {"word":"barrier","phonetic":"ˈbæriə","pos":"n.","def":"障碍，屏障；栅栏","cefr":"B2","freq_rank":103,
   "sentence_en":"Language can be a barrier.","sentence_zh":"语言可能是一种障碍。",
   "aids":{"morphemes":[M("barr","root","横木，栅(bar)"),M("ier","suffix","名词后缀")],
     "derivation":"bar(横木)+ier → 拦路的横木 → 障碍",
     "family":FAM("bar","横木、栅",[W("bar","栏杆"),W("barrel","桶"),W("embarrass","使尴尬")]),
     "mnemonic":"bar=横木(和 bar 一家);拦在中间挡路的东西,就是 barrier 障碍、屏障;trade barrier 贸易壁垒。",
     "forms":[F("barriers","n.","障碍(复数)")]}},
  {"word":"council","phonetic":"ˈkaʊnsl","pos":"n.","def":"委员会，理事会；议会","cefr":"B2","freq_rank":105,
   "sentence_en":"The city council approved the plan.","sentence_zh":"市议会批准了计划。",
   "aids":{"morphemes":[M("coun","prefix","一起(con)"),M("cil","root","召集(cal)")],
     "derivation":"con(一起)+cil(召集) → 召集到一起议事的一群人 → 委员会",
     "family":FAM("cil/cal","召集",[W("counsel","建议(另义)"),W("reconcile","调和")]),
     "mnemonic":"召集(cil)大家一起(coun-)开会议事的团体,就是 council 委员会;别和 counsel(劝告)混。",
     "forms":[F("councils","n.","委员会(复数)")]}},
  {"word":"utility","phonetic":"juːˈtɪlɪti","pos":"n.","def":"效用，实用；公用事业","cefr":"B2","freq_rank":88,
   "sentence_en":"The tool has great utility.","sentence_zh":"这个工具很实用。",
   "aids":{"morphemes":[M("util","root","使用，有用(uti)"),M("ity","suffix","名词后缀")],
     "derivation":"util(有用)+ity → 有用的性质 → 效用",
     "family":FAM("ut/us","使用",[W("use","使用"),W("useful","有用的"),W("utilize","利用")]),
     "mnemonic":"util=有用(和 use 一家);实际用处、效用,就是 utility;水电气等'公用事业'=utilities;utilize 利用。",
     "forms":[F("utilize","v.","利用"),F("utilities","n.","公用事业(复数)")]}},
  {"word":"routine","phonetic":"ruːˈtiːn","pos":"n./adj.","def":"常规，例行公事；日常的","cefr":"B1","freq_rank":92,
   "sentence_en":"Exercise is part of my daily routine.","sentence_zh":"锻炼是我日常的一部分。",
   "aids":{"morphemes":[M("rout","root","路(route)"),M("ine","suffix","名词后缀")],
     "derivation":"与 route(路线)同源;走熟了的老路 → 惯常做法 → 常规",
     "family":FAM("rout/rupt","路、冲",[W("route","路线"),W("rout","溃败")]),
     "mnemonic":"routine 与 route(路)同源;走顺了的老套路、每天照做的事,就是 routine 常规、例行;daily routine 日常。",
     "forms":[F("routinely","adv.","例行地")]}},
  # 高频形容词/常见词
  {"word":"crucial","phonetic":"ˈkruːʃl","pos":"adj.","def":"至关重要的，决定性的","cefr":"B2","freq_rank":20,
   "sentence_en":"This is a crucial moment.","sentence_zh":"这是关键时刻。",
   "aids":{"morphemes":[M("cruc","root","十字，交叉"),M("ial","suffix","…的")],
     "derivation":"cruc(十字路口)+ial → 处于关键岔口的 → 决定性的",
     "family":FAM("cruc","十字、交叉",[W("cross","十字"),W("crucify","钉十字架"),W("crossroad","十字路口")]),
     "mnemonic":"cruc=十字(想 cross);站在十字路口、走哪条定成败,就是 crucial 至关重要的。",
     "forms":[F("crucially","adv.","关键地")]}},
  {"word":"capable","phonetic":"ˈkeɪpəbl","pos":"adj.","def":"有能力的，能干的","cefr":"B1","freq_rank":19,
   "sentence_en":"She is capable of great things.","sentence_zh":"她能成就大事。",
   "aids":{"morphemes":[M("cap","root","拿，容纳"),M("able","suffix","能…的")],
     "derivation":"cap(容纳)+able → 装得下、担得起的 → 有能力的",
     "family":FAM("cap/cept","拿、容纳",[W("capacity","容量"),W("capture","捕获"),W("accept","接受")]),
     "mnemonic":"cap=容纳/拿得起(想 capacity 容量);担得起、做得来的,就是 capable;be capable of 能够;capability 能力。",
     "forms":[F("capability","n.","能力"),F("capably","adv.","能干地")]}},
  {"word":"permanent","phonetic":"ˈpɜːmənənt","pos":"adj.","def":"永久的，永恒的；固定的","cefr":"B2","freq_rank":40,
   "sentence_en":"He found a permanent job.","sentence_zh":"他找到了一份固定工作。",
   "aids":{"morphemes":[M("per","prefix","始终，贯穿"),M("man","root","停留(main)"),M("ent","suffix","…的")],
     "derivation":"per(始终)+man(停留) → 始终留存的 → 永久的",
     "family":FAM("man/main","停留",[W("remain","保持"),W("mansion","大宅")]),
     "mnemonic":"man=停留(和 remain 一家);自始至终(per-)留着不变的,就是 permanent 永久的;反义 temporary 暂时的。",
     "forms":[F("permanently","adv.","永久地")]}},
  {"word":"reasonable","phonetic":"ˈriːznəbl","pos":"adj.","def":"合理的；通情达理的；公道的","cefr":"B1","freq_rank":60,
   "sentence_en":"That's a reasonable price.","sentence_zh":"那价格很公道。",
   "aids":{"morphemes":[M("reason","root","理由，理性"),M("able","suffix","…的")],
     "derivation":"reason(理性)+able → 合乎理性的 → 合理的",
     "family":FAM("reason","理由、理性",[W("reason","理由"),W("rational","理性的")]),
     "mnemonic":"reason=理;讲道理、说得通的=合理的/通情达理的;价格不离谱=公道的,都是 reasonable;反义 unreasonable。",
     "forms":[F("reason","n.","理由"),F("reasonably","adv.","合理地")]}},
  {"word":"aggressive","phonetic":"əˈɡresɪv","pos":"adj.","def":"好斗的，侵略性的；有进取心的","cefr":"B2","freq_rank":62,
   "sentence_en":"He has an aggressive personality.","sentence_zh":"他性格好斗。",
   "aids":{"morphemes":[M("ag","prefix","朝向(ad 变体)"),M("gress","root","走，步"),M("ive","suffix","…的")],
     "derivation":"ag(朝向)+gress(走) → 主动朝人步步进逼的 → 好斗的、进取的",
     "family":FAM("gress/grad","走、步",[W("progress","进步"),W("congress","国会"),W("gradual","逐渐的")]),
     "mnemonic":"gress=走(想 progress 前进);步步朝人逼上去,就是 aggressive 好斗的;褒义指'积极进取的'。",
     "forms":[F("aggression","n.","侵略；攻击性")]}},
  {"word":"ultimate","phonetic":"ˈʌltɪmət","pos":"adj./n.","def":"最终的，根本的；终极","cefr":"B2","freq_rank":98,
   "sentence_en":"Our ultimate goal is world peace.","sentence_zh":"我们的最终目标是世界和平。",
   "aids":{"morphemes":[M("ultim","root","最后(ultimus)"),M("ate","suffix","…的")],
     "derivation":"ultim(最后)+ate → 最末、最根本的 → 最终的",
     "family":FAM("ult","最后、超过",[W("ultimatum","最后通牒"),W("ulterior","别有用心的")]),
     "mnemonic":"ultim=最后(想 ultimatum 最后通牒);排在最末、最根本的,就是 ultimate 最终的;ultimately 最终。",
     "forms":[F("ultimately","adv.","最终")]}},
  {"word":"electronic","phonetic":"ɪlekˈtrɒnɪk","pos":"adj.","def":"电子的","cefr":"B1","freq_rank":24,
   "sentence_en":"I read electronic books.","sentence_zh":"我读电子书。",
   "aids":{"morphemes":[M("electron","root","电子"),M("ic","suffix","…的")],
     "derivation":"electron(电子)+ic → 与电子有关的 → 电子的",
     "family":FAM("electr","电",[W("electric","电的"),W("electricity","电"),W("electron","电子")]),
     "mnemonic":"electron=电子(想 electric 电的);靠电子元件运作的,就是 electronic;e- 前缀(email)就来自它。",
     "forms":[F("electronics","n.","电子学；电子设备")]}},
  {"word":"approximately","phonetic":"əˈprɒksɪmətli","pos":"adv.","def":"大约，大致","cefr":"B2","freq_rank":13,
   "sentence_en":"It takes approximately two hours.","sentence_zh":"大约需要两小时。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("proxim","root","最近的"),M("ately","suffix","…地")],
     "derivation":"ap(朝向)+proxim(最近) → 接近某数地 → 大约",
     "family":FAM("proxim/prop","近",[W("approach","接近"),W("proximity","邻近"),W("approximate","近似的")]),
     "mnemonic":"proxim=最近(和 approach 一家);贴近某个数、差不离地,就是 approximately 大约;≈符号读 approximately。",
     "forms":[F("approximate","adj.","近似的")]}},
  {"word":"nevertheless","phonetic":"ˌnevəðəˈles","pos":"adv./conj.","def":"然而，尽管如此","cefr":"B2","freq_rank":89,
   "sentence_en":"It was hard; nevertheless, they succeeded.","sentence_zh":"这很难，然而他们成功了。",
   "aids":{"morphemes":[M("never","root","从不"),M("the","connector","连接"),M("less","root","更少，不")],
     "derivation":"never+the+less'并不因此更少' → 尽管如此仍然 → 然而",
     "family":FAM("","相关词",[W("nonetheless","尽管如此")]),
     "mnemonic":"字面'never the less'——'并不因此打折扣';承接转折'尽管如此、然而',就是 nevertheless;=nonetheless。",
     "forms":[]}},
  # 常见名词
  {"word":"award","phonetic":"əˈwɔːd","pos":"n./v.","def":"奖(品)；授予；裁定","cefr":"B1","freq_rank":86,
   "sentence_en":"She won an award for her film.","sentence_zh":"她凭这部电影获奖。",
   "aids":{"morphemes":[M("a","prefix","加强"),M("ward","root","看守，判定(guard)")],
     "derivation":"与 ward/guard'看守、裁定'相关;经裁定给予 → 授予、奖",
     "family":FAM("ward/guard","看守、判定",[W("reward","奖赏"),W("guard","守卫"),W("regard","看待")]),
     "mnemonic":"ward=判定(和 reward 一家);经评判正式给予的荣誉,就是 award 奖;动词=授予/裁定。",
     "forms":[F("awards","n.","奖项(复数)"),F("awarded","v.","过去式/过去分词")]}},
  {"word":"origin","phonetic":"ˈɒrɪdʒɪn","pos":"n.","def":"起源，起因；出身","cefr":"B2","freq_rank":77,
   "sentence_en":"The word has a Latin origin.","sentence_zh":"这个词源自拉丁语。",
   "aids":{"morphemes":[M("ori","root","升起，开始"),M("gin","suffix","名词后缀")],
     "derivation":"ori(升起)+gin → 事物升起、开端处 → 起源",
     "family":FAM("ori","升起、起源",[W("original","最初的"),W("originate","起源于"),W("orient","东方；定向")]),
     "mnemonic":"ori=升起(想 orient 太阳升起的东方);事物最初冒头的地方,就是 origin 起源;original 最初的。",
     "forms":[F("original","adj.","最初的"),F("originate","v.","起源于")]}},
  {"word":"impression","phonetic":"ɪmˈpreʃən","pos":"n.","def":"印象","cefr":"B1","freq_rank":70,
   "sentence_en":"What was your first impression?","sentence_zh":"你的第一印象是什么？",
   "aids":{"morphemes":[M("im","prefix","向内"),M("press","root","压"),M("ion","suffix","名词后缀")],
     "derivation":"im(向内)+press(压) → 压印进心里 → 印象","family":FAM("press","压",[W("express","表达"),W("pressure","压力")]),
     "mnemonic":"press=压;在心里'压'下的痕迹,就是 impression 印象。","forms":[F("impressive","adj.","令人印象深刻的")]}},
  {"word":"channel","phonetic":"ˈtʃænl","pos":"n.","def":"频道；渠道；海峡","cefr":"B1","freq_rank":65,
   "sentence_en":"News reached us through official channels.","sentence_zh":"消息通过官方渠道传到我们这。",
   "aids":{"morphemes":[M("chan","root","管，沟"),M("nel","suffix","小")],
     "derivation":"与 canal(运河)同源;流动的道 → 渠道、频道","family":FAM("can/chan","管、沟",[W("canal","运河")]),
     "mnemonic":"channel 与 canal 同源;信息/水流经的道,就是 channel 渠道、频道。","forms":[F("channels","n.","渠道(复数)")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 14
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
