#!/usr/bin/env python
# 第六批词:约55个高频词,逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -sist 站
  {"word":"insist","phonetic":"ɪnˈsɪst","pos":"v.","def":"坚持，坚决主张","cefr":"B1","freq_rank":58,
   "sentence_en":"She insisted on paying for dinner.","sentence_zh":"她坚持要付晚餐钱。",
   "aids":{"morphemes":[M("in","prefix","在上，向"),M("sist","root","站")],
     "derivation":"in(向)+sist(站) → 站定在自己立场上不动 → 坚持",
     "family":FAM("sist","站",[W("exist","存在"),W("resist","抵抗"),W("assist","协助"),W("consist","组成")]),
     "mnemonic":"sist=站;死死站(sist)在自己立场上(in-)不挪,就是 insist 坚持;insist on=坚持要。",
     "forms":[F("insistence","n.","坚持"),F("insisted","v.","过去式/过去分词")]}},
  # -tribute 给
  {"word":"contribute","phonetic":"kənˈtrɪbjuːt","pos":"v.","def":"贡献；捐助；投稿","cefr":"B2","freq_rank":40,
   "sentence_en":"Everyone contributed ideas to the project.","sentence_zh":"每个人都为项目贡献了想法。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("tribute","root","给予")],
     "derivation":"con(一起)+tribute(给) → 一起拿出来给 → 贡献、捐助",
     "family":FAM("tribute","给予",[W("distribute","分发"),W("attribute","归因于"),W("tribute","贡品")]),
     "mnemonic":"tribute=给(想 tribute 贡品);和大家一起(con-)拿出一份给出去,就是 contribute 贡献。",
     "forms":[F("contribution","n.","贡献"),F("contributor","n.","贡献者")]}},
  # -flu 流
  {"word":"influence","phonetic":"ˈɪnfluəns","pos":"n./v.","def":"影响(力)","cefr":"B1","freq_rank":71,
   "sentence_en":"Parents have a big influence on children.","sentence_zh":"父母对孩子有很大影响。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("flu","root","流"),M("ence","suffix","名词后缀")],
     "derivation":"in(向内)+flu(流) → 无形地流入、渗入 → 影响",
     "family":FAM("flu","流",[W("fluent","流利的"),W("flow","流动"),W("fluid","液体"),W("influenza","流感")]),
     "mnemonic":"flu=流(想 fluent 流利);一种力量悄悄'流'进(in-)你心里改变你,就是 influence 影响。",
     "forms":[F("influential","adj.","有影响力的"),F("influenced","v.","过去式/过去分词")]}},
  # -spect/-spic 看
  {"word":"aspect","phonetic":"ˈæspekt","pos":"n.","def":"方面；外观","cefr":"B1","freq_rank":57,
   "sentence_en":"We considered every aspect of the plan.","sentence_zh":"我们考虑了计划的每个方面。",
   "aids":{"morphemes":[M("a","prefix","朝向(ad 变体)"),M("spect","root","看")],
     "derivation":"a(朝向)+spect(看) → 朝某个角度看到的那一面 → 方面",
     "family":FAM("spect","看",[W("respect","尊重"),W("inspect","检查"),W("prospect","前景"),W("suspect","怀疑")]),
     "mnemonic":"spect=看;从一个角度(a-)看过去呈现的那一面,就是 aspect 方面。",
     "forms":[F("aspects","n.","方面(复数)")]}},
  {"word":"perspective","phonetic":"pəˈspektɪv","pos":"n.","def":"视角，观点；透视","cefr":"B2","freq_rank":78,
   "sentence_en":"Try to see it from my perspective.","sentence_zh":"试着从我的角度来看。",
   "aids":{"morphemes":[M("per","prefix","穿过"),M("spect","root","看"),M("ive","suffix","名词后缀")],
     "derivation":"per(穿过)+spect(看) → 透过某一角度看 → 视角、观点",
     "family":FAM("spect","看",[W("aspect","方面"),W("respect","尊重"),W("inspect","检查"),W("spectator","观众")]),
     "mnemonic":"per-(穿过)+spect(看)——透过某个立场看过去,就是 perspective 视角、观点。",
     "forms":[F("perspectives","n.","视角(复数)")]}},
  # -mon 展示/警告
  {"word":"demonstrate","phonetic":"ˈdemənstreɪt","pos":"v.","def":"证明，演示；示威","cefr":"B2","freq_rank":65,
   "sentence_en":"He demonstrated how the machine works.","sentence_zh":"他演示了机器如何运作。",
   "aids":{"morphemes":[M("de","prefix","彻底，加强"),M("monstr","root","显示，指出"),M("ate","suffix","动词后缀")],
     "derivation":"de(彻底)+monstr(显示) → 彻底显示给人看 → 证明、演示",
     "family":FAM("monstr/mon","显示、警告",[W("monster","怪物(不祥之兆)"),W("monitor","监视器"),W("summon","召唤")]),
     "mnemonic":"monstr=显示(想 monster 显现的凶兆);彻底(de-)摆出来给人看,就是 demonstrate 演示、证明。",
     "forms":[F("demonstration","n.","演示；示威"),F("demonstrated","v.","过去式/过去分词")]}},
  # -ced/-cede 走
  {"word":"procedure","phonetic":"prəˈsiːdʒə","pos":"n.","def":"程序，步骤；手续","cefr":"B2","freq_rank":62,
   "sentence_en":"Follow the correct procedure.","sentence_zh":"请遵循正确的程序。",
   "aids":{"morphemes":[M("pro","prefix","向前"),M("ced","root","走"),M("ure","suffix","名词后缀")],
     "derivation":"pro(向前)+ced(走) → 一步步往前走的步骤 → 程序",
     "family":FAM("ced/ceed","走",[W("proceed","前进"),W("process","过程"),W("exceed","超过"),W("precede","先于")]),
     "mnemonic":"ced=走(想 proceed 前进);一步步向前走的固定步骤,就是 procedure 程序、手续。",
     "forms":[F("procedures","n.","程序(复数)"),F("procedural","adj.","程序上的")]}},
  # -ident 同
  {"word":"identity","phonetic":"aɪˈdentɪti","pos":"n.","def":"身份；一致性","cefr":"B2","freq_rank":46,
   "sentence_en":"The thief stole her identity.","sentence_zh":"窃贼盗用了她的身份。",
   "aids":{"morphemes":[M("ident","root","相同"),M("ity","suffix","名词后缀")],
     "derivation":"ident(相同)+ity → 与'本人'完全同一 → 身份",
     "family":FAM("ident","相同",[W("identify","识别"),W("identical","完全相同的"),W("identification","身份证明")]),
     "mnemonic":"ident=相同;能证明'你就是你本人'的那套标识,就是 identity 身份。",
     "forms":[F("identities","n.","身份(复数)")]}},
  # -cip 拿/首
  {"word":"principle","phonetic":"ˈprɪnsɪpl","pos":"n.","def":"原则，原理","cefr":"B2","freq_rank":49,
   "sentence_en":"He refused on principle.","sentence_zh":"他出于原则拒绝了。",
   "aids":{"morphemes":[M("prin","root","第一，首(prim)"),M("cip","root","拿"),M("le","suffix","名词后缀")],
     "derivation":"prin(第一)+cip(拿) → 摆在第一位、作根本依据的 → 原则、原理",
     "family":FAM("prim/prin","第一、首",[W("primary","首要的"),W("prince","王子(第一位)"),W("principal","主要的；校长")]),
     "mnemonic":"prin=第一(想 prince 王子);放在第一位、做根本准绳的,就是 principle 原则;别和 principal(校长/主要的)混。",
     "forms":[F("principles","n.","原则(复数)")]}},
  # -viv/-surv 活
  {"word":"survive","phonetic":"səˈvaɪv","pos":"v.","def":"幸存，存活；比…活得长","cefr":"B1","freq_rank":50,
   "sentence_en":"Only a few passengers survived the crash.","sentence_zh":"只有少数乘客在事故中幸存。",
   "aids":{"morphemes":[M("sur","prefix","超过，在上"),M("vive","root","活")],
     "derivation":"sur(超过)+vive(活) → 活过了(灾难/别人) → 幸存",
     "family":FAM("viv","活",[W("survival","幸存"),W("revive","复活"),W("vivid","生动的"),W("vital","至关重要的")]),
     "mnemonic":"vive=活(想 vivid 栩栩如生);灾难过后还活着、活过头(sur-),就是 survive 幸存。",
     "forms":[F("survival","n.","幸存"),F("survivor","n.","幸存者")]}},
  # -lect/-leg 选/收
  {"word":"collect","phonetic":"kəˈlekt","pos":"v.","def":"收集，聚集；领取","cefr":"A2","freq_rank":44,
   "sentence_en":"She collects old coins.","sentence_zh":"她收集旧硬币。",
   "aids":{"morphemes":[M("col","prefix","一起"),M("lect","root","选，收")],
     "derivation":"col(一起)+lect(收) → 把东西挑收到一起 → 收集",
     "family":FAM("lect/leg","选、收",[W("select","挑选"),W("elect","选举"),W("collection","收藏")]),
     "mnemonic":"lect=选/收(想 select 挑选);把散的东西一起(col-)挑收拢来,就是 collect 收集。",
     "forms":[F("collection","n.","收藏，收集"),F("collector","n.","收藏者")]}},
  {"word":"collection","phonetic":"kəˈlekʃən","pos":"n.","def":"收藏(品)；募集","cefr":"B1","freq_rank":21,
   "sentence_en":"The museum has a fine art collection.","sentence_zh":"这家博物馆有精美的艺术收藏。",
   "aids":{"morphemes":[M("col","prefix","一起"),M("lect","root","选，收"),M("ion","suffix","名词后缀")],
     "derivation":"col(一起)+lect(收) → 收集到一起的一批东西 → 收藏",
     "family":FAM("lect/leg","选、收",[W("collect","收集"),W("select","挑选"),W("elect","选举")]),
     "mnemonic":"collect(收集)+ion——收拢到一起的一批东西,就是 collection 收藏、藏品。",
     "forms":[F("collections","n.","收藏(复数)")]}},
  # -soci 同伴
  {"word":"associate","phonetic":"əˈsəʊʃieɪt","pos":"v./n.","def":"联想；交往；伙伴","cefr":"B2","freq_rank":55,
   "sentence_en":"I associate summer with the beach.","sentence_zh":"我把夏天和海滩联系在一起。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("soci","root","同伴，结交"),M("ate","suffix","动词后缀")],
     "derivation":"as(朝向)+soci(同伴) → 结为同伴、拉到一起 → 联系、交往",
     "family":FAM("soci","同伴、社会",[W("social","社会的"),W("society","社会"),W("sociable","好交际的")]),
     "mnemonic":"soci=同伴(想 social 社交);把两者结成'伙伴'拉到一起=associate 联想;与人结伴=交往。",
     "forms":[F("association","n.","协会；联系"),F("associated","adj.","相关的")]}},
  # -oper 工作
  {"word":"operate","phonetic":"ˈɒpəreɪt","pos":"v.","def":"操作，运转；动手术","cefr":"B1","freq_rank":38,
   "sentence_en":"Do you know how to operate this machine?","sentence_zh":"你知道怎么操作这台机器吗？",
   "aids":{"morphemes":[M("oper","root","工作"),M("ate","suffix","动词后缀")],
     "derivation":"oper(工作)+ate → 使运作、动手做 → 操作、运转",
     "family":FAM("oper","工作",[W("operation","操作；手术"),W("cooperate","合作"),W("operator","操作员")]),
     "mnemonic":"oper=工作(想 cooperate 一起工作=合作);使机器/系统工作起来,就是 operate 操作;医生给病人'动工'=动手术。",
     "forms":[F("operation","n.","操作；手术"),F("operator","n.","操作员")]}},
  # -equ 相等
  {"word":"equipment","phonetic":"ɪˈkwɪpmənt","pos":"n.","def":"设备，装备","cefr":"B1","freq_rank":54,
   "sentence_en":"The lab has modern equipment.","sentence_zh":"实验室有现代化的设备。",
   "aids":{"morphemes":[M("equip","root","装备(古法语 esquiper 装船)"),M("ment","suffix","名词后缀")],
     "derivation":"equip(装备)+ment → 装备好的东西 → 设备",
     "family":FAM("","相关词",[W("equip","装备"),W("equipped","装备好的")]),
     "mnemonic":"equip 本义'给船配齐装备';配齐做事所需的家伙,就是 equipment 设备(不可数);动词 equip。",
     "forms":[F("equip","v.","装备"),F("equipped","adj.","配备…的")]}},
  # -pet 追求
  {"word":"competition","phonetic":"ˌkɒmpəˈtɪʃən","pos":"n.","def":"竞争，比赛","cefr":"B1","freq_rank":52,
   "sentence_en":"There is fierce competition for jobs.","sentence_zh":"求职竞争激烈。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("pet","root","追求"),M("ition","suffix","名词后缀")],
     "derivation":"com(一起)+pet(追求) → 一起追同一目标 → 竞争",
     "family":FAM("pet","追求",[W("compete","竞争"),W("appetite","食欲"),W("petition","请愿")]),
     "mnemonic":"pet=追求(想 appetite 食欲=追求食物);大家一起(com-)争抢同一目标,就是 competition 竞争。",
     "forms":[F("compete","v.","竞争"),F("competitive","adj.","有竞争力的")]}},
  # -tech 技艺
  {"word":"technique","phonetic":"tekˈniːk","pos":"n.","def":"技巧，技术；方法","cefr":"B1","freq_rank":48,
   "sentence_en":"She uses a special painting technique.","sentence_zh":"她使用一种特别的绘画技巧。",
   "aids":{"morphemes":[M("techn","root","技艺"),M("ique","suffix","名词后缀")],
     "derivation":"希腊 techne'技艺';具体做事的手法 → 技巧",
     "family":FAM("techn","技艺",[W("technology","技术"),W("technical","技术的"),W("technician","技术员")]),
     "mnemonic":"techn=技艺(想 technology 科技);做某事的具体手法、门道,就是 technique 技巧。",
     "forms":[F("technical","adj.","技术的"),F("techniques","n.","技巧(复数)")]}},
  # 高频名词/动词
  {"word":"advantage","phonetic":"ədˈvɑːntɪdʒ","pos":"n.","def":"优势，好处","cefr":"B1","freq_rank":35,
   "sentence_en":"Speaking two languages is an advantage.","sentence_zh":"会说两种语言是一种优势。",
   "aids":{"morphemes":[M("advant","root","在前(advance 前进)"),M("age","suffix","名词后缀")],
     "derivation":"与 advance(前进)同源;走在别人前面的有利位置 → 优势",
     "family":FAM("van/vance","前",[W("advance","前进"),W("vanguard","先锋")]),
     "mnemonic":"与 advance(前进)一家;比别人往前一步的有利之处,就是 advantage 优势;反义 disadvantage 劣势;take advantage of 利用。",
     "forms":[F("advantages","n.","优势(复数)"),F("advantageous","adj.","有利的")]}},
  {"word":"basis","phonetic":"ˈbeɪsɪs","pos":"n.","def":"基础，根据；方式","cefr":"B2","freq_rank":37,
   "sentence_en":"We meet on a regular basis.","sentence_zh":"我们定期见面。",
   "aids":{"morphemes":[M("bas","root","底，基"),M("is","suffix","名词后缀")],
     "derivation":"bas(底)+is → 垫底的东西 → 基础",
     "family":FAM("bas","底、基",[W("base","基础"),W("basic","基本的"),W("basement","地下室")]),
     "mnemonic":"bas=底(想 base 基座);垫在最底下作依托的,就是 basis 基础;on a...basis=以…方式;复数 bases。",
     "forms":[F("base","n.","基础"),F("basic","adj.","基本的")]}},
  {"word":"sample","phonetic":"ˈsɑːmpl","pos":"n./v.","def":"样品，样本；抽样","cefr":"B1","freq_rank":39,
   "sentence_en":"They tested a sample of the water.","sentence_zh":"他们检测了一份水样。",
   "aids":{"morphemes":[M("sample","root","取样(example 的变体)")],
     "derivation":"与 example(例子)同源;从整体取出的一小份代表 → 样本",
     "family":FAM("empt/ample","取",[W("example","例子"),W("exemplary","典范的")]),
     "mnemonic":"sample≈example 的表亲;从一大批里取出的一小份代表,就是 sample 样品、样本。",
     "forms":[F("samples","n.","样品(复数)"),F("sampling","n.","抽样")]}},
  {"word":"additional","phonetic":"əˈdɪʃənl","pos":"adj.","def":"额外的，附加的","cefr":"B1","freq_rank":45,
   "sentence_en":"There is an additional charge for delivery.","sentence_zh":"送货需另外收费。",
   "aids":{"morphemes":[M("add","root","加"),M("ition","suffix","名词"),M("al","suffix","…的")],
     "derivation":"add(加)+itional → 加上去的 → 额外的",
     "family":FAM("add/dit","加、给",[W("add","增加"),W("addition","增加"),W("additive","添加剂")]),
     "mnemonic":"add=加;在原有基础上再加上去的,就是 additional 额外的、附加的。",
     "forms":[F("addition","n.","增加"),F("additionally","adv.","此外")]}},
  {"word":"faith","phonetic":"feɪθ","pos":"n.","def":"信任，信心；信仰","cefr":"B1","freq_rank":47,
   "sentence_en":"I have faith in you.","sentence_zh":"我对你有信心。",
   "aids":{"morphemes":[M("faith","root","信任(fid)")],
     "derivation":"与 fid'信任'同源;坚定的相信 → 信任、信仰",
     "family":FAM("fid/faith","信任",[W("faithful","忠实的"),W("confide","倾诉；信任"),W("fidelity","忠诚")]),
     "mnemonic":"faith 与 fid(信任,如 confide 吐露信任)同源;打心底相信,就是 faith 信任、信仰;faithful 忠实的。",
     "forms":[F("faithful","adj.","忠实的")]}},
  {"word":"belief","phonetic":"bɪˈliːf","pos":"n.","def":"信念，相信；信仰","cefr":"B1","freq_rank":64,
   "sentence_en":"It is my belief that honesty matters.","sentence_zh":"我坚信诚实很重要。",
   "aids":{"morphemes":[M("be","prefix","加强"),M("lief","root","爱，信(lieve)")],
     "derivation":"be+lieve(信) 的名词 → 所相信的东西 → 信念",
     "family":FAM("liev/lief","信、爱",[W("believe","相信"),W("believable","可信的")]),
     "mnemonic":"belief 是 believe(相信)的名词;心里认定为真的东西,就是 belief 信念;注意拼写 -ief。",
     "forms":[F("believe","v.","相信"),F("beliefs","n.","信念(复数)")]}},
  {"word":"review","phonetic":"rɪˈvjuː","pos":"n./v.","def":"复习；回顾；评论","cefr":"A2","freq_rank":68,
   "sentence_en":"Let's review what we learned today.","sentence_zh":"我们复习一下今天学的内容。",
   "aids":{"morphemes":[M("re","prefix","再"),M("view","root","看")],
     "derivation":"re(再)+view(看) → 再看一遍 → 复习、回顾、评论",
     "family":FAM("view/vis","看",[W("view","看法"),W("preview","预览"),W("interview","面试")]),
     "mnemonic":"view=看;再(re-)看一遍学过的=复习;回头看=回顾;看完写感想=评论,都是 review。",
     "forms":[F("reviews","n.","评论(复数)"),F("reviewer","n.","评论者")]}},
  {"word":"engage","phonetic":"ɪnˈɡeɪdʒ","pos":"v.","def":"从事；吸引；使参与；订婚","cefr":"B2","freq_rank":69,
   "sentence_en":"The book engages the reader's attention.","sentence_zh":"这本书吸引读者的注意力。",
   "aids":{"morphemes":[M("en","prefix","使处于"),M("gage","root","抵押，保证")],
     "derivation":"en(使)+gage(保证、束缚) → 使投入其中、束住 → 从事、使参与",
     "family":FAM("gage","保证、抵押",[W("gauge","measure；标准"),W("mortgage","抵押贷款")]),
     "mnemonic":"gage=保证/束缚(想 mortgage 抵押);使人投入、被牵住,就是 engage 从事、吸引;engaged 订婚的/忙碌的。",
     "forms":[F("engagement","n.","约定；订婚"),F("engaging","adj.","有魅力的")]}},
  {"word":"document","phonetic":"ˈdɒkjumənt","pos":"n./v.","def":"文件，文档；记录","cefr":"B1","freq_rank":70,
   "sentence_en":"Please sign this document.","sentence_zh":"请在这份文件上签字。",
   "aids":{"morphemes":[M("doc","root","教，示"),M("ument","suffix","名词后缀")],
     "derivation":"doc(教、示)+ument → 用来说明/证明的东西 → 文件",
     "family":FAM("doc","教、示",[W("doctor","博士"),W("doctrine","教义"),W("document","文件")]),
     "mnemonic":"doc=教/示(想 doctor 博士);载明信息、可作凭证的东西,就是 document 文件;动词=记录。",
     "forms":[F("documents","n.","文件(复数)"),F("documentary","n.","纪录片")]}},
  {"word":"ignore","phonetic":"ɪɡˈnɔː","pos":"v.","def":"忽视，不理会","cefr":"B1","freq_rank":63,
   "sentence_en":"Don't ignore the warning signs.","sentence_zh":"不要忽视警告信号。",
   "aids":{"morphemes":[M("i","prefix","不(in 变体)"),M("gnor","root","知道(gno)")],
     "derivation":"i(不)+gnor(知) → 装作不知道 → 忽视",
     "family":FAM("gno/gnor","知道",[W("recognize","认出"),W("diagnose","诊断"),W("ignorant","无知的")]),
     "mnemonic":"gnor=知(和 recognize 一家);故意'不去知道、当没看见',就是 ignore 忽视;ignorant 无知的。",
     "forms":[F("ignorance","n.","无知"),F("ignored","v.","过去式/过去分词")]}},
  {"word":"threaten","phonetic":"ˈθretn","pos":"v.","def":"威胁，恐吓；预示凶兆","cefr":"B1","freq_rank":72,
   "sentence_en":"Rising seas threaten coastal cities.","sentence_zh":"海平面上升威胁着沿海城市。",
   "aids":{"morphemes":[M("threat","root","威胁"),M("en","suffix","使…(动词)")],
     "derivation":"threat(威胁)+en → 发出威胁 → 威胁",
     "family":FAM("","相关词",[W("threat","威胁"),W("threatening","威胁性的")]),
     "mnemonic":"threaten 是 threat(威胁)的动词;放话或形势要加害于你,就是 threaten 威胁;-en 是'使'的后缀。",
     "forms":[F("threat","n.","威胁"),F("threatening","adj.","威胁性的")]}},
  {"word":"deny","phonetic":"dɪˈnaɪ","pos":"v.","def":"否认；拒绝给予","cefr":"B1","freq_rank":76,
   "sentence_en":"He denied stealing the money.","sentence_zh":"他否认偷了钱。",
   "aids":{"morphemes":[M("de","prefix","否，离"),M("ny","root","说不(neg)")],
     "derivation":"de(否)+ny(说不) → 说'不是这样' → 否认",
     "family":FAM("neg/ny","否定",[W("negative","否定的"),W("neglect","忽视"),W("renegade","叛徒")]),
     "mnemonic":"和 negative(否定)一家;一口咬定'不是、没有',就是 deny 否认;反义 admit 承认。",
     "forms":[F("denial","n.","否认"),F("denied","v.","过去式/过去分词")]}},
  {"word":"native","phonetic":"ˈneɪtɪv","pos":"adj./n.","def":"本地的；天生的；本地人","cefr":"B1","freq_rank":75,
   "sentence_en":"She is a native English speaker.","sentence_zh":"她的母语是英语。",
   "aids":{"morphemes":[M("nat","root","出生"),M("ive","suffix","…的")],
     "derivation":"nat(出生)+ive → 与出生地/生俱来有关的 → 本地的、天生的",
     "family":FAM("nat","出生",[W("nature","自然；本性"),W("nation","国家"),W("natural","自然的"),W("innate","天生的")]),
     "mnemonic":"nat=出生(想 nation 国家);在此出生的=本地的;生来就有的=天生的,就是 native;native speaker 母语者。",
     "forms":[F("natives","n.","本地人(复数)")]}},
  {"word":"gather","phonetic":"ˈɡæðə","pos":"v.","def":"聚集，收集；推断","cefr":"A2","freq_rank":53,
   "sentence_en":"A crowd gathered outside.","sentence_zh":"外面聚集了一群人。",
   "aids":{"morphemes":[M("gather","root","聚(together 相关)")],
     "derivation":"与 together(一起)同源;使聚到一起 → 聚集;把线索聚拢 → 推断",
     "family":FAM("","相关词",[W("together","一起"),W("gathering","聚会")]),
     "mnemonic":"gather 与 together 同源;把人/物聚到一处=聚集;把信息聚拢得出结论=推断(I gather 我猜想)。",
     "forms":[F("gathered","v.","过去式/过去分词"),F("gathering","n.","聚会")]}},
  {"word":"settle","phonetic":"ˈsetl","pos":"v.","def":"解决；定居；安顿；平静","cefr":"B1","freq_rank":42,
   "sentence_en":"They settled the dispute peacefully.","sentence_zh":"他们和平解决了争端。",
   "aids":{"morphemes":[M("set","root","放，坐(sit)"),M("tle","suffix","反复")],
     "derivation":"与 set/sit(放、坐)同源;使落定、坐稳 → 解决、定居、安定",
     "family":FAM("set/sit","放、坐",[W("set","放置"),W("seat","座位"),W("session","会期")]),
     "mnemonic":"settle 与 set/sit 一家;让纷争落地=解决;让人坐稳扎根=定居;让情绪落定=平静。",
     "forms":[F("settlement","n.","解决；定居点"),F("settled","adj.","稳定的")]}},
  {"word":"block","phonetic":"blɒk","pos":"n./v.","def":"街区；块；阻挡，封锁","cefr":"A2","freq_rank":41,
   "sentence_en":"A fallen tree blocked the road.","sentence_zh":"一棵倒下的树挡住了路。",
   "aids":{"morphemes":[M("block","root","大块(荷兰语 blok)")],
     "derivation":"本义'大块木/石';用大块堵住 → 阻挡;方块状的一片 → 街区、块",
     "family":FAM("","相关词",[W("blockade","封锁"),W("roadblock","路障")]),
     "mnemonic":"block=大块;拿大块堵路=阻挡、封锁;方块状的一段=街区/块;blockbuster 大片。",
     "forms":[F("blocked","v.","过去式/过去分词"),F("blocks","n.","街区(复数)")]}},
  {"word":"border","phonetic":"ˈbɔːdə","pos":"n./v.","def":"边界，边缘；接壤","cefr":"B1","freq_rank":51,
   "sentence_en":"They crossed the border at night.","sentence_zh":"他们在夜间越过了边界。",
   "aids":{"morphemes":[M("bord","root","边(board 边缘)"),M("er","suffix","名词后缀")],
     "derivation":"与 board(板/边)同源;最外一条边 → 边界",
     "family":FAM("bord/board","边",[W("board","板；边"),W("aboard","在…上")]),
     "mnemonic":"border 与 board(边缘)同源;两国/两块地相接的那条边线,就是 border 边界;border on=与…接壤/近乎。",
     "forms":[F("borders","n.","边界(复数)"),F("borderline","n.","分界线")]}},
  {"word":"comment","phonetic":"ˈkɒment","pos":"n./v.","def":"评论，评价；注释","cefr":"B1","freq_rank":60,
   "sentence_en":"She made no comment on the news.","sentence_zh":"她对这条新闻不予置评。",
   "aids":{"morphemes":[M("com","prefix","加强"),M("ment","root","心，想")],
     "derivation":"com+ment(想) → 把想法说出来 → 评论",
     "family":FAM("ment","心、想",[W("mental","精神的"),W("mention","提到"),W("mentor","导师")]),
     "mnemonic":"ment=想(想 mental 心智);把心里的看法说出来,就是 comment 评论;no comment 无可奉告。",
     "forms":[F("comments","n.","评论(复数)"),F("commentary","n.","评论，解说")]}},
  {"word":"responsible","phonetic":"rɪˈspɒnsəbl","pos":"adj.","def":"负责的；有责任心的","cefr":"B1","freq_rank":61,
   "sentence_en":"Who is responsible for this mess?","sentence_zh":"谁该为这团糟负责？",
   "aids":{"morphemes":[M("re","prefix","回"),M("spons","root","承诺，回答"),M("ible","suffix","能…的")],
     "derivation":"re(回)+spons(答) → 需要回应/交代的 → 负责的",
     "family":FAM("spons/spond","承诺、回答",[W("respond","回应"),W("response","回应"),W("responsibility","责任")]),
     "mnemonic":"spons=回答;出了事得回应、交代得起的,就是 responsible 负责的;be responsible for=对…负责。",
     "forms":[F("responsibility","n.","责任"),F("responsibly","adv.","负责地")]}},
  {"word":"annual","phonetic":"ˈænjuəl","pos":"adj.","def":"每年的，年度的","cefr":"B1","freq_rank":59,
   "sentence_en":"The company holds an annual meeting.","sentence_zh":"公司每年召开一次年会。",
   "aids":{"morphemes":[M("ann","root","年"),M("ual","suffix","…的")],
     "derivation":"ann(年)+ual → 每年一次的 → 年度的",
     "family":FAM("ann/enn","年",[W("anniversary","周年纪念"),W("annually","每年"),W("biennial","两年一次的")]),
     "mnemonic":"ann=年(想 anniversary 周年);一年一度的,就是 annual;anniversary 周年纪念日。",
     "forms":[F("annually","adv.","每年")]}},
  {"word":"female","phonetic":"ˈfiːmeɪl","pos":"adj./n.","def":"女性的，雌性的；女性","cefr":"A2","freq_rank":73,
   "sentence_en":"The female bird builds the nest.","sentence_zh":"雌鸟筑巢。",
   "aids":{"morphemes":[M("femal","root","女性(femella 小女子)"),M("e","suffix","结尾")],
     "derivation":"拉丁 femella'小女子';指女性、雌性(拼写受 male 影响)",
     "family":FAM("femin","女性",[W("feminine","女性的"),W("feminism","女权主义")]),
     "mnemonic":"femal 源自'小女子';指女性/雌性,就是 female;和 male(男/雄)配对记;feminine 女性化的。",
     "forms":[F("females","n.","女性(复数)")]}},
  {"word":"background","phonetic":"ˈbækɡraʊnd","pos":"n.","def":"背景；出身经历","cefr":"B1","freq_rank":74,
   "sentence_en":"Tell me about your educational background.","sentence_zh":"跟我说说你的教育背景。",
   "aids":{"morphemes":[M("back","root","后"),M("ground","root","地面，基础")],
     "derivation":"back(后)+ground(地) → 后面衬托的地 → 背景;人的来路 → 出身经历",
     "family":FAM("","相关词",[W("ground","地面"),W("underground","地下的")]),
     "mnemonic":"back(后)+ground(底)——衬在后面的底=背景;一个人身后的来路=出身、经历,都是 background。",
     "forms":[F("backgrounds","n.","背景(复数)")]}},
  {"word":"religion","phonetic":"rɪˈlɪdʒən","pos":"n.","def":"宗教，信仰","cefr":"B1","freq_rank":67,
   "sentence_en":"They respect all religions.","sentence_zh":"他们尊重一切宗教。",
   "aids":{"morphemes":[M("re","prefix","再三"),M("lig","root","捆绑(lig)"),M("ion","suffix","名词后缀")],
     "derivation":"re(再三)+lig(捆) → 把人与神/信条紧紧绑在一起 → 宗教",
     "family":FAM("lig","捆绑",[W("oblige","使负义务"),W("ligament","韧带")]),
     "mnemonic":"lig=捆(想 ligament 韧带);把信徒与信仰反复捆缚在一起的体系,就是 religion 宗教。",
     "forms":[F("religious","adj.","宗教的")]}},
  {"word":"murder","phonetic":"ˈmɜːdə","pos":"n./v.","def":"谋杀，凶杀","cefr":"B1","freq_rank":66,
   "sentence_en":"He was charged with murder.","sentence_zh":"他被控谋杀。",
   "aids":{"morphemes":[M("murder","root","杀害(古英语 morthor)")],
     "derivation":"古英语 morthor'致死';蓄意杀人 → 谋杀",
     "family":FAM("mor/mort","死",[W("mortal","致命的；凡人的"),W("mortgage","抵押(死约)")]),
     "mnemonic":"murder 与 mort(死,如 mortal 致命的)同源;蓄意害人性命,就是 murder 谋杀;murderer 凶手。",
     "forms":[F("murderer","n.","凶手"),F("murdered","v.","过去式/过去分词")]}},
  {"word":"critic","phonetic":"ˈkrɪtɪk","pos":"n.","def":"批评家，评论家","cefr":"B2","freq_rank":56,
   "sentence_en":"The film received praise from critics.","sentence_zh":"这部电影受到评论家的赞誉。",
   "aids":{"morphemes":[M("crit","root","判断，分辨"),M("ic","suffix","…的人")],
     "derivation":"crit(判断)+ic → 专门评判的人 → 批评家",
     "family":FAM("crit","判断、分辨",[W("critical","批判的"),W("criticize","批评"),W("criterion","标准")]),
     "mnemonic":"crit=判断(想 critical);以评判为业的人,就是 critic 批评家;动词 criticize,形容词 critical。",
     "forms":[F("critical","adj.","批判的"),F("criticize","v.","批评")]}},
  {"word":"violence","phonetic":"ˈvaɪələns","pos":"n.","def":"暴力，暴行；猛烈","cefr":"B1","freq_rank":20,
   "sentence_en":"The film contains a lot of violence.","sentence_zh":"这部电影包含很多暴力内容。",
   "aids":{"morphemes":[M("viol","root","强力，侵犯"),M("ence","suffix","名词后缀")],
     "derivation":"viol(强力)+ence → 使用强力伤害 → 暴力",
     "family":FAM("viol","强力、侵犯",[W("violent","暴力的"),W("violate","违反，侵犯")]),
     "mnemonic":"viol=强力侵犯(想 violate 侵犯);诉诸武力伤害,就是 violence 暴力;violent 暴力的。",
     "forms":[F("violent","adj.","暴力的")]}},
  {"word":"nuclear","phonetic":"ˈnjuːkliə","pos":"adj.","def":"核的，原子能的；核心的","cefr":"B2","freq_rank":29,
   "sentence_en":"They discussed nuclear energy.","sentence_zh":"他们讨论了核能。",
   "aids":{"morphemes":[M("nucle","root","核，仁(nucleus)"),M("ar","suffix","…的")],
     "derivation":"nucle(核)+ar → 与原子核有关的 → 核的",
     "family":FAM("nucle","核",[W("nucleus","核心，原子核")]),
     "mnemonic":"nucle=核(想 nucleus 细胞核/原子核);关于原子核能量的,就是 nuclear 核的;nuclear power 核电。",
     "forms":[F("nucleus","n.","核心，原子核")]}},
  {"word":"candidate","phonetic":"ˈkændɪdeɪt","pos":"n.","def":"候选人；应试者","cefr":"B2","freq_rank":15,
   "sentence_en":"She is the best candidate for the job.","sentence_zh":"她是这份工作的最佳人选。",
   "aids":{"morphemes":[M("candid","root","白色，纯洁"),M("ate","suffix","名词后缀")],
     "derivation":"古罗马求职者身穿白袍(candidus 白);由此'穿白袍者'→ 候选人",
     "family":FAM("cand","白、发光",[W("candid","坦率的"),W("candle","蜡烛"),W("candle","烛光")]),
     "mnemonic":"candid=白(想 candle 蜡烛的白光);古罗马候选人穿白袍表清白,由此 candidate 候选人。",
     "forms":[F("candidates","n.","候选人(复数)"),F("candidacy","n.","候选资格")]}},
  {"word":"interview","phonetic":"ˈɪntəvjuː","pos":"n./v.","def":"面试；采访","cefr":"A2","freq_rank":12,
   "sentence_en":"I have a job interview tomorrow.","sentence_zh":"我明天有一场求职面试。",
   "aids":{"morphemes":[M("inter","prefix","在…之间，相互"),M("view","root","看")],
     "derivation":"inter(相互)+view(看) → 双方相互对看交谈 → 面谈、面试",
     "family":FAM("view/vis","看",[W("view","看法"),W("review","复习"),W("preview","预览")]),
     "mnemonic":"inter-(相互)+view(看)——两人面对面互看交谈,就是 interview 面试、采访。",
     "forms":[F("interviews","n.","面试(复数)"),F("interviewer","n.","面试官")]}},
  {"word":"particular","phonetic":"pəˈtɪkjulə","pos":"adj.","def":"特定的；特别的；挑剔的","cefr":"B1","freq_rank":13,
   "sentence_en":"Is there a particular reason?","sentence_zh":"有什么特别的原因吗？",
   "aids":{"morphemes":[M("part","root","部分"),M("icular","suffix","…的")],
     "derivation":"part(部分)+icular → 特指某一小部分的 → 特定的、特别的",
     "family":FAM("part","部分",[W("particle","粒子"),W("partial","部分的"),W("participate","参与")]),
     "mnemonic":"part=部分;单指其中某一具体部分的,就是 particular 特定的;对细节部分都在意=挑剔的;in particular 尤其。",
     "forms":[F("particularly","adv.","特别，尤其")]}},
  {"word":"professional","phonetic":"prəˈfeʃənl","pos":"adj./n.","def":"专业的，职业的；专业人士","cefr":"B1","freq_rank":26,
   "sentence_en":"She gave a very professional presentation.","sentence_zh":"她做了一场非常专业的演示。",
   "aids":{"morphemes":[M("pro","prefix","向前，公开"),M("fess","root","说，宣称"),M("ional","suffix","…的")],
     "derivation":"pro(公开)+fess(宣称) → 公开宣称精通某行 → 职业的、专业的",
     "family":FAM("fess","说、宣称",[W("profess","声称"),W("confess","坦白"),W("professor","教授")]),
     "mnemonic":"fess=说(想 confess 坦白);公开(pro-)宣称以此为业、精于此道,就是 professional 专业的;professor 教授。",
     "forms":[F("professionally","adv.","专业地"),F("profession","n.","职业")]}},
  {"word":"senior","phonetic":"ˈsiːniə","pos":"adj./n.","def":"高级的；年长的；毕业班学生","cefr":"B1","freq_rank":25,
   "sentence_en":"She holds a senior position.","sentence_zh":"她担任高级职位。",
   "aids":{"morphemes":[M("sen","root","老，年长"),M("ior","suffix","较…的")],
     "derivation":"sen(老)+ior(较) → 较年长/资深的 → 高级的",
     "family":FAM("sen","老",[W("senate","参议院(元老院)"),W("senior","资深的")]),
     "mnemonic":"sen=老(想 senate 元老院);更年长、更资深的,就是 senior;反义 junior 初级的/年幼的。",
     "forms":[F("seniority","n.","资历")]}},
  {"word":"client","phonetic":"ˈklaɪənt","pos":"n.","def":"客户，委托人","cefr":"B1","freq_rank":28,
   "sentence_en":"The lawyer met with her client.","sentence_zh":"律师与她的委托人会面。",
   "aids":{"morphemes":[M("cli","root","倾斜，依靠(clin)"),M("ent","suffix","…的人")],
     "derivation":"cli(依靠)+ent → 有事依靠专业者的人 → 委托人、客户",
     "family":FAM("clin","倾斜、依靠",[W("incline","倾向"),W("decline","下降；婉拒"),W("lean","倚靠")]),
     "mnemonic":"cli=依靠(想 incline 倾靠);有事托付、依靠你专业服务的人,就是 client 客户、委托人。",
     "forms":[F("clients","n.","客户(复数)")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 6
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
