#!/usr/bin/env python
# 第九批词:约55个高频词,逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -cept/-ceive 拿
  {"word":"perception","phonetic":"pəˈsepʃən","pos":"n.","def":"感知，知觉；看法","cefr":"B2","freq_rank":74,
   "sentence_en":"Color perception varies among people.","sentence_zh":"人们对颜色的感知各不相同。",
   "aids":{"morphemes":[M("per","prefix","彻底，完全"),M("cept","root","拿，取"),M("ion","suffix","名词后缀")],
     "derivation":"per(完全)+cept(拿) → 完全地把信息抓取进来 → 感知",
     "family":FAM("cept/ceive","拿、取",[W("perceive","察觉"),W("accept","接受"),W("concept","概念"),W("receive","收到")]),
     "mnemonic":"cept=拿(想 accept 接受);把外界信息完全(per-)抓取进大脑,就是 perception 感知、看法;动词 perceive。",
     "forms":[F("perceive","v.","察觉"),F("perceptions","n.","看法(复数)")]}},
  # -fid 信
  {"word":"confidence","phonetic":"ˈkɒnfɪdəns","pos":"n.","def":"信心，自信；信任","cefr":"B1","freq_rank":75,
   "sentence_en":"She spoke with great confidence.","sentence_zh":"她说话非常有信心。",
   "aids":{"morphemes":[M("con","prefix","完全"),M("fid","root","信任"),M("ence","suffix","名词后缀")],
     "derivation":"con(完全)+fid(信任) → 完全相信(自己/他人) → 自信、信任",
     "family":FAM("fid","信任",[W("confident","自信的"),W("confide","倾诉"),W("faith","信念"),W("fidelity","忠诚")]),
     "mnemonic":"fid=信任(想 confide 吐露心事);对自己/他人完全(con-)信得过,就是 confidence 信心、信任。",
     "forms":[F("confident","adj.","自信的"),F("confidential","adj.","机密的")]}},
  # -fer 带
  {"word":"reference","phonetic":"ˈrefərəns","pos":"n.","def":"提及，参考；参考文献","cefr":"B2","freq_rank":85,
   "sentence_en":"Keep this book for future reference.","sentence_zh":"留着这本书以备日后参考。",
   "aids":{"morphemes":[M("re","prefix","回，向"),M("fer","root","带"),M("ence","suffix","名词后缀")],
     "derivation":"re(向)+fer(带) → 把注意力带回某处查看 → 参考、提及",
     "family":FAM("fer","带、拿",[W("refer","提及"),W("offer","提供"),W("transfer","转移"),W("prefer","更喜欢")]),
     "mnemonic":"refer(提及、查阅)的名词;供你回头带去查看的东西,就是 reference 参考、参考文献。",
     "forms":[F("references","n.","参考文献(复数)")]}},
  # -par 准备/相等
  {"word":"separate","phonetic":"ˈsepəreɪt","pos":"v./adj.","def":"分开，分离；单独的","cefr":"A2","freq_rank":81,
   "sentence_en":"Separate the eggs from the flour.","sentence_zh":"把鸡蛋和面粉分开。",
   "aids":{"morphemes":[M("se","prefix","分开，离"),M("par","root","准备，摆"),M("ate","suffix","动词后缀")],
     "derivation":"se(分开)+par(摆) → 分开摆放 → 分离",
     "family":FAM("par","准备、摆",[W("prepare","准备"),W("repair","修理"),W("apparatus","设备")]),
     "mnemonic":"se-(分开)+par(摆)——把混在一起的分开摆,就是 separate 分开;形容词 separate 各自的/单独的。",
     "forms":[F("separation","n.","分离"),F("separately","adv.","分别地")]}},
  # -mot 动
  {"word":"motion","phonetic":"ˈməʊʃən","pos":"n./v.","def":"运动，移动；动议；打手势","cefr":"B1","freq_rank":53,
   "sentence_en":"The motion of the waves is calming.","sentence_zh":"海浪的起伏令人平静。",
   "aids":{"morphemes":[M("mot","root","动"),M("ion","suffix","名词后缀")],
     "derivation":"mot(动)+ion → 动的状态 → 运动、移动",
     "family":FAM("mot/mov","动",[W("move","移动"),W("motive","动机"),W("emotion","情绪"),W("promote","促进")]),
     "mnemonic":"mot=动(想 motor 马达);物体运动的状态=motion;会上正式提出的'动'议也是 motion;in motion 运动中。",
     "forms":[F("motions","n.","动作(复数)")]}},
  # -limin 门槛
  {"word":"eliminate","phonetic":"ɪˈlɪmɪneɪt","pos":"v.","def":"消除，排除；淘汰","cefr":"B2","freq_rank":63,
   "sentence_en":"We must eliminate all errors.","sentence_zh":"我们必须消除所有错误。",
   "aids":{"morphemes":[M("e","prefix","出，离"),M("limin","root","门槛，界限"),M("ate","suffix","动词后缀")],
     "derivation":"e(出)+limin(门槛) → 赶出门槛外 → 排除、消除",
     "family":FAM("limin/limit","门槛、界限",[W("limit","限制"),W("preliminary","预备的")]),
     "mnemonic":"limin=门槛(想 limit 界限);把它撵出(e-)门槛之外,就是 eliminate 消除、淘汰。",
     "forms":[F("elimination","n.","消除；淘汰")]}},
  # -vestig 足迹
  {"word":"investigate","phonetic":"ɪnˈvestɪɡeɪt","pos":"v.","def":"调查，研究","cefr":"B2","freq_rank":47,
   "sentence_en":"Police are investigating the case.","sentence_zh":"警方正在调查此案。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("vestig","root","足迹"),M("ate","suffix","动词后缀")],
     "derivation":"in(向内)+vestig(足迹) → 顺着足迹深入追查 → 调查",
     "family":FAM("vestig","足迹",[W("vestige","痕迹"),W("investigation","调查")]),
     "mnemonic":"vestig=足迹(想 vestige 遗迹);顺着蛛丝马迹深入追查,就是 investigate 调查。",
     "forms":[F("investigation","n.","调查"),F("investigator","n.","调查员")]}},
  # -crit 判断
  {"word":"criterion","phonetic":"kraɪˈtɪəriən","pos":"n.","def":"标准，准则","cefr":"C1","freq_rank":46,
   "sentence_en":"Price is not the only criterion.","sentence_zh":"价格不是唯一的标准。",
   "aids":{"morphemes":[M("crit","root","判断，分辨"),M("erion","suffix","名词后缀")],
     "derivation":"crit(判断)+erion → 用来判断的依据 → 标准",
     "family":FAM("crit","判断、分辨",[W("critical","关键的"),W("criticize","批评"),W("critic","批评家")]),
     "mnemonic":"crit=判断(和 critical 一家);评判优劣所依据的尺子,就是 criterion 标准;复数 criteria。",
     "forms":[F("criteria","n.","标准(复数)")]}},
  # -estim 价值
  {"word":"estimate","phonetic":"ˈestɪmeɪt","pos":"v./n.","def":"估计，估算；评价","cefr":"B1","freq_rank":45,
   "sentence_en":"They estimated the cost at $5000.","sentence_zh":"他们估计成本为五千美元。",
   "aids":{"morphemes":[M("estim","root","估价，评价"),M("ate","suffix","动词后缀")],
     "derivation":"estim(估价)+ate → 估量其价值/数量 → 估计",
     "family":FAM("estim/esteem","估价",[W("esteem","尊重"),W("estimation","估计")]),
     "mnemonic":"estim=估价(想 esteem 看重);大致估量数量或价值,就是 estimate 估计;esteem 尊重(看高其价值)。",
     "forms":[F("estimation","n.","估计"),F("estimated","adj.","估计的")]}},
  # -ven 来
  {"word":"intervention","phonetic":"ˌɪntəˈvenʃən","pos":"n.","def":"干预，介入；调停","cefr":"C1","freq_rank":92,
   "sentence_en":"Military intervention was avoided.","sentence_zh":"军事干预得以避免。",
   "aids":{"morphemes":[M("inter","prefix","在…之间"),M("ven","root","来"),M("tion","suffix","名词后缀")],
     "derivation":"inter(之间)+ven(来) → 插到中间来 → 干预、介入",
     "family":FAM("ven","来",[W("event","事件"),W("prevent","预防"),W("convention","惯例"),W("invent","发明")]),
     "mnemonic":"ven=来(想 event);硬插到双方中间(inter-)来,就是 intervention 干预、调停;动词 intervene。",
     "forms":[F("intervene","v.","干预"),F("interventions","n.","干预(复数)")]}},
  # -cit 召唤
  {"word":"cite","phonetic":"saɪt","pos":"v.","def":"引用，引证；举例；传讯","cefr":"B2","freq_rank":93,
   "sentence_en":"She cited several examples.","sentence_zh":"她引用了几个例子。",
   "aids":{"morphemes":[M("cite","root","召唤，激起(cit)")],
     "derivation":"拉丁 citare'召唤';把话/例子召来作证 → 引用、引证",
     "family":FAM("cit","召唤、激起",[W("excite","使兴奋"),W("recite","背诵"),W("incite","煽动")]),
     "mnemonic":"cit=召唤(想 excite 激起、recite 背诵);把原话/例子召来佐证,就是 cite 引用、引证。",
     "forms":[F("citation","n.","引用；引文"),F("cited","v.","过去式/过去分词")]}},
  # -divid 分
  {"word":"division","phonetic":"dɪˈvɪʒən","pos":"n.","def":"分开，划分；部门；除法","cefr":"B2","freq_rank":68,
   "sentence_en":"There is a clear division of labor.","sentence_zh":"分工明确。",
   "aids":{"morphemes":[M("di","prefix","分开"),M("vis","root","分(vid)"),M("ion","suffix","名词后缀")],
     "derivation":"di(分开)+vis(分) → 分割 → 划分、部门",
     "family":FAM("vid/vis","分、看",[W("divide","分开"),W("individual","个体"),W("device","装置")]),
     "mnemonic":"和 divide(分开)一家;把整体切分开=division 划分;切出来的一块机构=部门;数学的'除法'也是 division。",
     "forms":[F("divide","v.","分开"),F("divisions","n.","部门(复数)")]}},
  # -pel 推
  {"word":"appeal","phonetic":"əˈpiːl","pos":"n./v.","def":"呼吁，恳求；吸引力；上诉","cefr":"B2","freq_rank":69,
   "sentence_en":"The idea appeals to me.","sentence_zh":"这个主意对我很有吸引力。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("peal","root","推动，驱(pel)")],
     "derivation":"ap(朝向)+peal(推) → 推动别人朝你所求 → 呼吁、吸引",
     "family":FAM("pel/peal","推、驱",[W("compel","强迫"),W("repel","击退"),W("propel","推进")]),
     "mnemonic":"peal=推(pel 家族);推动人心朝你所愿=呼吁/恳求;打动、拉住人心=吸引;向上级'推请'重审=上诉。",
     "forms":[F("appealing","adj.","有吸引力的"),F("appeals","n.","呼吁(复数)")]}},
  # -ly 信赖
  {"word":"rely","phonetic":"rɪˈlaɪ","pos":"v.","def":"依赖，依靠；信赖","cefr":"B1","freq_rank":71,
   "sentence_en":"You can rely on me.","sentence_zh":"你可以依靠我。",
   "aids":{"morphemes":[M("re","prefix","再，back"),M("ly","root","绑，系(lig)")],
     "derivation":"re+ly(绑) → 把自己绑靠上去 → 依赖",
     "family":FAM("li/lig","绑、系",[W("reliable","可靠的"),W("reliance","依赖"),W("ally","盟友")]),
     "mnemonic":"ly=绑(lig 家族,想 ally 结盟绑一起);把自己牢牢系靠在某人某物上,就是 rely on 依赖;reliable 可靠的。",
     "forms":[F("reliable","adj.","可靠的"),F("reliance","n.","依赖")]}},
  # -plain 抱怨/平
  {"word":"complain","phonetic":"kəmˈpleɪn","pos":"v.","def":"抱怨，投诉","cefr":"A2","freq_rank":73,
   "sentence_en":"She complained about the noise.","sentence_zh":"她抱怨噪音太大。",
   "aids":{"morphemes":[M("com","prefix","加强"),M("plain","root","捶胸，悲叹(plangere)")],
     "derivation":"拉丁 plangere'捶胸痛哭';大声诉说不满 → 抱怨",
     "family":FAM("plain/plaint","捶胸、悲叹",[W("complaint","抱怨"),W("plaintiff","原告")]),
     "mnemonic":"plain=捶胸悲叹(不是'平原'那个 plain);捶胸顿足地诉苦,就是 complain 抱怨;名词 complaint。",
     "forms":[F("complaint","n.","抱怨，投诉")]}},
  # -sol 单独/整
  {"word":"solve","phonetic":"sɒlv","pos":"v.","def":"解决，解答","cefr":"A2","freq_rank":55,
   "sentence_en":"Let's solve this problem together.","sentence_zh":"让我们一起解决这个问题。",
   "aids":{"morphemes":[M("solv","root","松开，解开"),M("e","suffix","结尾")],
     "derivation":"solv(解开) → 把难题解开 → 解决",
     "family":FAM("solv/solu","松开、解开",[W("solution","解决办法"),W("resolve","解决；决心"),W("dissolve","溶解")]),
     "mnemonic":"solv=解开;把纠缠的难题一松一解,就是 solve;名词 solution 解决办法。",
     "forms":[F("solution","n.","解决办法"),F("solved","v.","过去式/过去分词")]}},
  # -equ 相等
  {"word":"equal","phonetic":"ˈiːkwəl","pos":"adj./v./n.","def":"相等的，平等的；比得上","cefr":"A2","freq_rank":57,
   "sentence_en":"Everyone deserves equal rights.","sentence_zh":"每个人都应享有平等权利。",
   "aids":{"morphemes":[M("equ","root","相等，平"),M("al","suffix","…的")],
     "derivation":"equ(相等)+al → 相等的 → 平等的",
     "family":FAM("equ","相等、平",[W("equality","平等"),W("equation","方程"),W("equivalent","等价的"),W("adequate","足够的")]),
     "mnemonic":"equ=相等(想 equation 方程 A=B);数量/地位一样的,就是 equal 相等的、平等的;名词 equality。",
     "forms":[F("equality","n.","平等"),F("equally","adv.","平等地")]}},
  # -limin/-forth 常见
  {"word":"afford","phonetic":"əˈfɔːd","pos":"v.","def":"负担得起；提供","cefr":"A2","freq_rank":66,
   "sentence_en":"I can't afford a new car.","sentence_zh":"我买不起新车。",
   "aids":{"morphemes":[M("af","prefix","朝向(ad 变体)"),M("ford","root","向前，促进(forth)")],
     "derivation":"af(朝向)+ford(向前促进) → 力所能及去做到 → 负担得起",
     "family":FAM("","相关词",[W("affordable","负担得起的")]),
     "mnemonic":"记 can afford='能往前够得着'——钱/时间够得上去承担,就是 afford 负担得起;affordable 买得起的。",
     "forms":[F("affordable","adj.","负担得起的")]}},
  # 高频名词(常见/词根清晰)
  {"word":"percentage","phonetic":"pəˈsentɪdʒ","pos":"n.","def":"百分比，比例","cefr":"B1","freq_rank":41,
   "sentence_en":"A high percentage of students passed.","sentence_zh":"高比例的学生通过了。",
   "aids":{"morphemes":[M("per","prefix","每，通过"),M("cent","root","百"),M("age","suffix","名词后缀")],
     "derivation":"per(每)+cent(百) → 每一百中所占的量 → 百分比",
     "family":FAM("cent","百",[W("percent","百分之"),W("century","世纪"),W("cent","分")]),
     "mnemonic":"cent=百(想 century 世纪、cent 一分=百分之一元);每百分之几,就是 percentage 百分比。",
     "forms":[F("percent","n.","百分之"),F("percentages","n.","百分比(复数)")]}},
  {"word":"combination","phonetic":"ˌkɒmbɪˈneɪʃən","pos":"n.","def":"结合，组合","cefr":"B1","freq_rank":50,
   "sentence_en":"The dish is a combination of flavors.","sentence_zh":"这道菜是多种味道的组合。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("bin","root","二，双"),M("ation","suffix","名词后缀")],
     "derivation":"com(一起)+bin(二) → 把两者/多者合到一起 → 组合",
     "family":FAM("bi/bin","二",[W("combine","结合"),W("binary","二进制的")]),
     "mnemonic":"combine(结合)的名词;把几样东西并到一起形成的整体,就是 combination 组合。",
     "forms":[F("combine","v.","结合"),F("combinations","n.","组合(复数)")]}},
  {"word":"improvement","phonetic":"ɪmˈpruːvmənt","pos":"n.","def":"改善，进步","cefr":"B1","freq_rank":95,
   "sentence_en":"There is room for improvement.","sentence_zh":"还有改进的空间。",
   "aids":{"morphemes":[M("improve","root","改善"),M("ment","suffix","名词后缀")],
     "derivation":"improve(改善)+ment → 改善的结果 → 进步",
     "family":FAM("prof/prov","有益",[W("improve","改善"),W("prove","证明")]),
     "mnemonic":"improve(改善)的名词;变得更好的状态或成果,就是 improvement 改善、进步。",
     "forms":[F("improve","v.","改善")]}},
  {"word":"requirement","phonetic":"rɪˈkwaɪəmənt","pos":"n.","def":"要求，必要条件","cefr":"B1","freq_rank":79,
   "sentence_en":"You must meet all the requirements.","sentence_zh":"你必须满足所有要求。",
   "aids":{"morphemes":[M("re","prefix","反复"),M("quire","root","寻求"),M("ment","suffix","名词后缀")],
     "derivation":"require(要求)+ment → 所要求的东西 → 必要条件",
     "family":FAM("quire/quest","寻求",[W("require","要求"),W("inquire","询问"),W("request","请求")]),
     "mnemonic":"require(需要、要求)的名词;必须具备/达到的条件,就是 requirement 要求、必要条件。",
     "forms":[F("require","v.","要求"),F("requirements","n.","要求(复数)")]}},
  {"word":"expectation","phonetic":"ˌekspekˈteɪʃən","pos":"n.","def":"期望，预期","cefr":"B2","freq_rank":80,
   "sentence_en":"The results exceeded our expectations.","sentence_zh":"结果超出了我们的预期。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("spect","root","看"),M("ation","suffix","名词后缀")],
     "derivation":"ex(向外)+spect(看) → 向前张望盼着 → 期望",
     "family":FAM("spect","看",[W("expect","期望"),W("respect","尊重"),W("inspect","检查"),W("aspect","方面")]),
     "mnemonic":"spect=看(和 expect 一家);向前(ex-)张望等着某事发生,就是 expectation 期望;exceed expectations 超预期。",
     "forms":[F("expect","v.","期望"),F("expectations","n.","期望(复数)")]}},
  {"word":"association","phonetic":"əˌsəʊʃiˈeɪʃən","pos":"n.","def":"协会；联系，联想","cefr":"B2","freq_rank":72,
   "sentence_en":"He joined a sports association.","sentence_zh":"他加入了一个体育协会。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("soci","root","同伴"),M("ation","suffix","名词后缀")],
     "derivation":"associate(结伴、联系)+ion → 结成的团体/建立的联系 → 协会、联想",
     "family":FAM("soci","同伴、社会",[W("associate","联系"),W("social","社会的"),W("society","社会")]),
     "mnemonic":"soci=同伴(和 social 一家);人们结伴组成的团体=协会;心理上把两者联到一起=联想。",
     "forms":[F("associate","v.","联系"),F("associations","n.","协会(复数)")]}},
  {"word":"perception","phonetic":"pəˈsepʃən","pos":"n.","def":"感知，看法","cefr":"B2","freq_rank":74,
   "sentence_en":"Public perception has changed.","sentence_zh":"公众看法已经改变。",
   "aids":{"morphemes":[M("per","prefix","完全"),M("cept","root","拿"),M("ion","suffix","名词后缀")],
     "derivation":"per(完全)+cept(拿) → 完全接收 → 感知","family":FAM("cept","拿",[W("accept","接受"),W("concept","概念")]),
     "mnemonic":"cept=拿;把外界完全接收进脑,就是 perception 感知、看法。","forms":[F("perceive","v.","察觉")]}},
  # 常见词
  {"word":"debt","phonetic":"det","pos":"n.","def":"债务，欠款；人情","cefr":"B1","freq_rank":76,
   "sentence_en":"He is in debt.","sentence_zh":"他负债了。",
   "aids":{"morphemes":[M("debt","root","欠(debere 应还)")],
     "derivation":"拉丁 debere'应偿还'(与 due 同源);该还未还的钱 → 债务(b 不发音)",
     "family":FAM("deb/due","欠、应",[W("due","应付的"),W("debit","借方")]),
     "mnemonic":"debt 与 due(应付的)同源;欠着该还的钱,就是 debt 债务;注意 b 不发音,读 /det/;in debt 负债。",
     "forms":[F("debts","n.","债务(复数)")]}},
  {"word":"era","phonetic":"ˈɪərə","pos":"n.","def":"时代，纪元","cefr":"B2","freq_rank":78,
   "sentence_en":"We live in the digital era.","sentence_zh":"我们生活在数字时代。",
   "aids":{"morphemes":[M("era","root","纪元(拉丁 aera 计数起点)")],
     "derivation":"拉丁 aera'纪年起点';一段有特色的历史时期 → 时代",
     "family":FAM("","相关词",[W("epoch","时代")]),
     "mnemonic":"era=纪元;有鲜明标志的一段历史时期,就是 era 时代;a new era 新纪元。",
     "forms":[F("eras","n.","时代(复数)")]}},
  {"word":"coverage","phonetic":"ˈkʌvərɪdʒ","pos":"n.","def":"覆盖范围；报道；保险范围","cefr":"B2","freq_rank":77,
   "sentence_en":"The event got wide media coverage.","sentence_zh":"这次活动得到了广泛的媒体报道。",
   "aids":{"morphemes":[M("cover","root","覆盖"),M("age","suffix","名词后缀")],
     "derivation":"cover(覆盖)+age → 覆盖到的范围 → 覆盖范围、报道",
     "family":FAM("cover","盖",[W("cover","覆盖"),W("discover","发现"),W("recover","恢复")]),
     "mnemonic":"cover(覆盖)的名词;信号/新闻/保险'盖'到多大范围,就是 coverage 覆盖范围、报道。",
     "forms":[F("cover","v.","覆盖")]}},
  {"word":"actual","phonetic":"ˈæktʃuəl","pos":"adj.","def":"实际的，真实的","cefr":"B1","freq_rank":35,
   "sentence_en":"The actual cost was higher.","sentence_zh":"实际成本更高。",
   "aids":{"morphemes":[M("act","root","做，行动"),M("ual","suffix","…的")],
     "derivation":"act(行动)+ual → 真正做出来、实际发生的 → 实际的",
     "family":FAM("act","做、行动",[W("act","行动"),W("action","行动"),W("active","积极的"),W("actor","演员")]),
     "mnemonic":"act=做;真正付诸行动、实际存在的,就是 actual 实际的;actually 实际上(常表转折'其实')。",
     "forms":[F("actually","adv.","实际上，其实")]}},
  {"word":"grant","phonetic":"ɡrɑːnt","pos":"v./n.","def":"授予，准予；拨款","cefr":"B2","freq_rank":86,
   "sentence_en":"The university granted her a scholarship.","sentence_zh":"大学授予她奖学金。",
   "aids":{"morphemes":[M("grant","root","答应，信任(credent)")],
     "derivation":"古法语 granter'答应、允准';正式应允给予 → 授予、拨款",
     "family":FAM("","相关词",[W("granted","assuming 假定")]),
     "mnemonic":"grant=允准给予;正式批给你钱/权利,就是 grant 授予、拨款;take...for granted 想当然、视为理所当然。",
     "forms":[F("grants","n.","拨款(复数)"),F("granted","v.","过去式/过去分词")]}},
  {"word":"minister","phonetic":"ˈmɪnɪstə","pos":"n.","def":"部长，大臣；牧师","cefr":"B1","freq_rank":87,
   "sentence_en":"The prime minister gave a speech.","sentence_zh":"首相发表了演讲。",
   "aids":{"morphemes":[M("mini","root","小，仆(minus)"),M("ster","suffix","人")],
     "derivation":"mini(小、仆)+ster → 本是'仆人'——为公众/君主服务的人 → 部长、大臣",
     "family":FAM("min","小",[W("minor","次要的"),W("minimum","最小"),W("administer","管理")]),
     "mnemonic":"mini=小/仆(对照 magister 大人物=master);为国服务的'公仆'首脑,就是 minister 部长;prime minister 首相。",
     "forms":[F("ministry","n.","部(政府)"),F("ministers","n.","部长(复数)")]}},
  {"word":"stretch","phonetic":"stretʃ","pos":"v./n.","def":"伸展，拉长；一段(时间/路)","cefr":"B1","freq_rank":88,
   "sentence_en":"Stretch your arms before running.","sentence_zh":"跑步前先伸展手臂。",
   "aids":{"morphemes":[M("stretch","root","拉紧伸展(古英语 streccan)")],
     "derivation":"古英语'拉直伸开';把身体/物体拉长 → 伸展",
     "family":FAM("str","拉紧",[W("strict","严格的"),W("string","线")]),
     "mnemonic":"str=拉紧(和 strict 一家);把肢体/东西往长里拉,就是 stretch 伸展;a stretch of road 一段路。",
     "forms":[F("stretched","v.","过去式/过去分词"),F("stretches","n.","一段(复数)")]}},
  {"word":"volume","phonetic":"ˈvɒljuːm","pos":"n.","def":"体积，容量；音量；卷，册","cefr":"B1","freq_rank":89,
   "sentence_en":"Turn down the volume, please.","sentence_zh":"请把音量调小。",
   "aids":{"morphemes":[M("volu","root","卷(volvere 卷)"),M("me","suffix","结尾")],
     "derivation":"volu(卷)→ 卷起的书卷 → 册;书卷有大小 → 体积、容量、音量",
     "family":FAM("volv/volu","卷、转",[W("involve","涉及"),W("revolve","旋转"),W("evolve","进化")]),
     "mnemonic":"volu=卷(和 involve 一家);古书是卷轴=一卷 volume;由'卷的大小'引申为体积、容量、音量。",
     "forms":[F("volumes","n.","卷；大量(复数)")]}},
  {"word":"relief","phonetic":"rɪˈliːf","pos":"n.","def":"宽慰，缓解；救济","cefr":"B1","freq_rank":51,
   "sentence_en":"It was a great relief to hear the news.","sentence_zh":"听到这个消息真是大大松了口气。",
   "aids":{"morphemes":[M("re","prefix","再，back"),M("lief","root","抬起，轻(lev)")],
     "derivation":"re+lief(抬轻) → 把重担重新抬起放轻 → 宽慰、缓解",
     "family":FAM("lev/liev","抬起、轻",[W("relieve","缓解"),W("elevate","抬高"),W("relevant","相关的")]),
     "mnemonic":"lief=抬轻(lev 家族,想 elevate 抬高);把压在心上的重担卸下变轻,就是 relief 宽慰;动词 relieve。",
     "forms":[F("relieve","v.","缓解"),F("relieved","adj.","宽慰的")]}},
  {"word":"ancient","phonetic":"ˈeɪnʃənt","pos":"adj.","def":"古代的，古老的","cefr":"A2","freq_rank":52,
   "sentence_en":"They studied ancient history.","sentence_zh":"他们研究古代史。",
   "aids":{"morphemes":[M("anci","root","在前，古(ante)"),M("ent","suffix","…的")],
     "derivation":"与 ante'在前'同源;很久以前的 → 古老的",
     "family":FAM("ant/anci","在前",[W("ancestor","祖先"),W("antique","古董")]),
     "mnemonic":"anci≈ante(在前,想 ancestor 祖先);久远之前的,就是 ancient 古代的、古老的。",
     "forms":[F("ancients","n.","古人(复数)")]}},
  {"word":"chain","phonetic":"tʃeɪn","pos":"n./v.","def":"链条；一连串；连锁店；拴住","cefr":"A2","freq_rank":48,
   "sentence_en":"A chain of events led to war.","sentence_zh":"一连串事件导致了战争。",
   "aids":{"morphemes":[M("chain","root","链(catena)")],
     "derivation":"拉丁 catena'链';一环扣一环 → 链条、一连串",
     "family":FAM("cat/chain","链",[W("concatenate","连结")]),
     "mnemonic":"chain=链;环环相扣=链条;事件一环扣一环=a chain of;同品牌一家扣一家=连锁店 chain store。",
     "forms":[F("chains","n.","链条(复数)"),F("chained","v.","过去式/过去分词")]}},
  {"word":"branch","phonetic":"brɑːntʃ","pos":"n./v.","def":"树枝；分支，分部；分叉","cefr":"B1","freq_rank":49,
   "sentence_en":"The bank has branches nationwide.","sentence_zh":"这家银行在全国设有分行。",
   "aids":{"morphemes":[M("branch","root","爪，枝(branca)")],
     "derivation":"拉丁 branca'爪';像树枝/爪那样从主干分出 → 分支、分部",
     "family":FAM("","相关词",[W("branching","分支的")]),
     "mnemonic":"branch=树枝;从主干分出的枝=分支;公司从总部分出的点=分部/分行;branch out 拓展。",
     "forms":[F("branches","n.","分支(复数)"),F("branched","v.","过去式/过去分词")]}},
  {"word":"frame","phonetic":"freɪm","pos":"n./v.","def":"框架，结构；给…装框；陷害","cefr":"B1","freq_rank":58,
   "sentence_en":"Put the photo in a frame.","sentence_zh":"把照片装进相框。",
   "aids":{"morphemes":[M("frame","root","构造(古英语 framian)")],
     "derivation":"古英语'使成形、构造';支撑起来的骨架 → 框架",
     "family":FAM("","相关词",[W("framework","框架"),W("framed","被陷害的")]),
     "mnemonic":"frame=骨架;撑起结构的架子=框架/相框;把无辜者'装进套里'=陷害(be framed);framework 体系。",
     "forms":[F("framework","n.","框架"),F("framed","v.","过去式/过去分词")]}},
  {"word":"typical","phonetic":"ˈtɪpɪkl","pos":"adj.","def":"典型的，有代表性的","cefr":"B1","freq_rank":60,
   "sentence_en":"It was a typical summer day.","sentence_zh":"那是个典型的夏日。",
   "aids":{"morphemes":[M("typ","root","类型，样式"),M("ical","suffix","…的")],
     "derivation":"typ(类型)+ical → 能代表一类的 → 典型的",
     "family":FAM("typ","类型",[W("type","类型"),W("typewriter","打字机"),W("stereotype","刻板印象")]),
     "mnemonic":"typ=类型(想 type);最能代表某一类特征的,就是 typical 典型的;typically 通常、一般。",
     "forms":[F("typically","adv.","通常，典型地")]}},
  {"word":"except","phonetic":"ɪkˈsept","pos":"prep./v.","def":"除…之外；把…除外","cefr":"A2","freq_rank":61,
   "sentence_en":"Everyone came except John.","sentence_zh":"除了约翰，大家都来了。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("cept","root","拿，取")],
     "derivation":"ex(向外)+cept(拿) → 拿出去、单拎出来 → 除…之外",
     "family":FAM("cept/ceive","拿、取",[W("accept","接受"),W("concept","概念"),W("receive","收到")]),
     "mnemonic":"cept=拿(和 accept 一家);把某个单拎(ex-)出去不算在内,就是 except 除…之外;exception 例外。",
     "forms":[F("exception","n.","例外"),F("exceptional","adj.","异常的，杰出的")]}},
  {"word":"currently","phonetic":"ˈkʌrəntli","pos":"adv.","def":"目前，现在","cefr":"B1","freq_rank":30,
   "sentence_en":"He is currently working abroad.","sentence_zh":"他目前在国外工作。",
   "aids":{"morphemes":[M("curr","root","跑，流"),M("ent","suffix","…的"),M("ly","suffix","地")],
     "derivation":"current(当前的)+ly → 在当前 → 目前",
     "family":FAM("curr/cur","跑、流",[W("current","当前的"),W("occur","发生"),W("currency","货币")]),
     "mnemonic":"curr=流/跑(和 current 一家);在此刻正流淌的时间点,就是 currently 目前;=at present。",
     "forms":[F("current","adj.","当前的")]}},
  {"word":"apparently","phonetic":"əˈpærəntli","pos":"adv.","def":"显然；据说，似乎","cefr":"B1","freq_rank":17,
   "sentence_en":"Apparently, he missed the train.","sentence_zh":"据说他没赶上火车。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("par","root","出现，可见"),M("ently","suffix","…地")],
     "derivation":"apparent(明显的)+ly → 从表面看得出地 → 显然、据表面看",
     "family":FAM("par/pear","出现、可见",[W("apparent","明显的"),W("appear","出现"),W("transparent","透明的")]),
     "mnemonic":"par=可见(和 appear 一家);从表面就看得出来地,就是 apparently 显然;也表'据说、看样子'。",
     "forms":[F("apparent","adj.","明显的")]}},
  {"word":"emergency","phonetic":"ɪˈmɜːdʒənsi","pos":"n.","def":"紧急情况","cefr":"B1","freq_rank":34,
   "sentence_en":"Call 120 in an emergency.","sentence_zh":"紧急情况下拨打120。",
   "aids":{"morphemes":[M("e","prefix","向外"),M("merg","root","沉，浸"),M("ency","suffix","名词后缀")],
     "derivation":"e(向外)+merg(浸) → 突然冒出水面的意外 → 紧急情况",
     "family":FAM("merg","沉、浸",[W("emerge","浮现"),W("merge","合并"),W("submerge","淹没")]),
     "mnemonic":"和 emerge(浮现)一家;突然冒(e-merg)出来、须马上应对的意外,就是 emergency 紧急情况。",
     "forms":[F("emergencies","n.","紧急情况(复数)")]}},
  {"word":"advice","phonetic":"ədˈvaɪs","pos":"n.","def":"建议，忠告","cefr":"A2","freq_rank":27,
   "sentence_en":"Let me give you some advice.","sentence_zh":"我给你一些建议。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("vice","root","看(vis)")],
     "derivation":"ad(朝向)+vis(看) → 把看法给对方看 → 忠告",
     "family":FAM("vis/vid","看",[W("advise","建议(动词)"),W("view","看法"),W("vision","视力")]),
     "mnemonic":"vice=看(vis);把'依我看'的意见给你,就是 advice 建议(名词,不可数);动词是 advise(读 /z/)。",
     "forms":[F("advise","v.","建议"),F("adviser","n.","顾问")]}},
  {"word":"host","phonetic":"həʊst","pos":"n./v.","def":"主人；主持人；主办","cefr":"B1","freq_rank":65,
   "sentence_en":"They will host the Olympics.","sentence_zh":"他们将主办奥运会。",
   "aids":{"morphemes":[M("host","root","客人/主人(hospes)")],
     "derivation":"拉丁 hospes'主客';招待客人的人 → 主人;引申主持、主办",
     "family":FAM("hosp/host","主客",[W("hospital","医院(接待所)"),W("hotel","旅馆"),W("hospitality","好客")]),
     "mnemonic":"host 与 hospital/hotel 同源(接待);招待客人的东道主=主人;办活动当东道=主办;节目 host 主持人。",
     "forms":[F("hosts","n.","主人(复数)"),F("hosted","v.","过去式/过去分词")]}},
  {"word":"zone","phonetic":"zəʊn","pos":"n.","def":"地带，区域","cefr":"B1","freq_rank":37,
   "sentence_en":"This is a no-parking zone.","sentence_zh":"这里是禁止停车区。",
   "aids":{"morphemes":[M("zone","root","带，腰带(zona)")],
     "derivation":"希腊 zone'腰带';像带子一样划出的一片 → 地带",
     "family":FAM("","相关词",[W("zonal","地带的")]),
     "mnemonic":"zone 本义'腰带';像带子般圈出的一块区域,就是 zone 地带;time zone 时区;comfort zone 舒适区。",
     "forms":[F("zones","n.","区域(复数)")]}},
  {"word":"estate","phonetic":"ɪˈsteɪt","pos":"n.","def":"房地产；庄园；财产","cefr":"B2","freq_rank":39,
   "sentence_en":"He works in real estate.","sentence_zh":"他从事房地产工作。",
   "aids":{"morphemes":[M("e","prefix","出(ex)"),M("stat","root","站，立"),M("e","suffix","结尾")],
     "derivation":"与 state/status(站立、状态)同源;一个人'立身'的产业地位 → 财产、地产",
     "family":FAM("st/sta","站、立",[W("state","状态"),W("status","地位"),W("statue","雕像")]),
     "mnemonic":"和 status(地位)同源;一个人立身的产业=estate 财产;real estate 房地产;庄园大宅也是 estate。",
     "forms":[F("estates","n.","地产(复数)")]}},
  {"word":"loan","phonetic":"ləʊn","pos":"n./v.","def":"贷款，借款；出借","cefr":"B1","freq_rank":29,
   "sentence_en":"She took out a loan to buy a house.","sentence_zh":"她贷款买了房。",
   "aids":{"morphemes":[M("loan","root","借出(古诺斯语 lán)")],
     "derivation":"古诺斯语'借出之物';借出/借入的钱 → 贷款",
     "family":FAM("","相关词",[W("lend","借出")]),
     "mnemonic":"loan=借出的钱;银行借给你、你要连本带息还的钱,就是 loan 贷款;student loan 助学贷款。",
     "forms":[F("loans","n.","贷款(复数)"),F("loaned","v.","过去式/过去分词")]}},
  {"word":"pilot","phonetic":"ˈpaɪlət","pos":"n./adj.","def":"飞行员；试点的，试验性的","cefr":"B1","freq_rank":38,
   "sentence_en":"They launched a pilot program.","sentence_zh":"他们启动了一个试点项目。",
   "aids":{"morphemes":[M("pilot","root","舵手，向导")],
     "derivation":"本义'舵手、领航员';引导航向的人 → 飞行员;先行试探=试点的",
     "family":FAM("","相关词",[W("autopilot","自动驾驶")]),
     "mnemonic":"pilot=领航舵手;驾机领航的人=飞行员;先跑一趟探路的=试点的(pilot study 试点研究)。",
     "forms":[F("pilots","n.","飞行员(复数)")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 9
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
