#!/usr/bin/env python
# 第七批词:约55个高频词,逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -tend 伸 扩展
  {"word":"extend","phonetic":"ɪkˈstend","pos":"v.","def":"延伸，扩大；延长","cefr":"B1","freq_rank":38,
   "sentence_en":"They extended the deadline by a week.","sentence_zh":"他们把截止日期延长了一周。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("tend","root","伸展")],
     "derivation":"ex(向外)+tend(伸) → 向外伸开 → 延伸、扩大",
     "family":FAM("tend/tens","伸展",[W("tend","倾向"),W("attend","出席"),W("intend","打算"),W("tension","紧张")]),
     "mnemonic":"tend=伸;向外(ex-)伸展开来,就是 extend 延伸、延长;名词 extension。",
     "forms":[F("extension","n.","延长；扩展"),F("extensive","adj.","广泛的")]}},
  # -pend 挂
  {"word":"depend","phonetic":"dɪˈpend","pos":"v.","def":"依赖，取决于","cefr":"A2","freq_rank":46,
   "sentence_en":"Children depend on their parents.","sentence_zh":"孩子依赖父母。",
   "aids":{"morphemes":[M("de","prefix","向下"),M("pend","root","悬挂")],
     "derivation":"de(向下)+pend(挂) → 向下挂靠着 → 依赖",
     "family":FAM("pend/pens","悬挂",[W("independent","独立的"),W("suspend","悬挂；暂停"),W("pending","待定的")]),
     "mnemonic":"pend=挂(想 pendant 吊坠);像挂件一样往下挂靠着别人,就是 depend on 依赖、取决于。",
     "forms":[F("dependent","adj.","依赖的"),F("dependence","n.","依赖")]}},
  # -nect 连
  {"word":"connection","phonetic":"kəˈnekʃən","pos":"n.","def":"连接，联系；人脉","cefr":"B1","freq_rank":31,
   "sentence_en":"There is a strong connection between them.","sentence_zh":"他们之间有紧密的联系。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("nect","root","系，绑"),M("ion","suffix","名词后缀")],
     "derivation":"con(一起)+nect(系) → 系到一起 → 连接",
     "family":FAM("nect","系、绑",[W("connect","连接"),W("annex","附加")]),
     "mnemonic":"nect=系(和 connect 一家);把两头系(nect)到一起(con-),就是 connection 连接、联系。",
     "forms":[F("connect","v.","连接"),F("connections","n.","人脉(复数)")]}},
  # -text 编织
  {"word":"context","phonetic":"ˈkɒntekst","pos":"n.","def":"上下文；背景，语境","cefr":"B2","freq_rank":32,
   "sentence_en":"You must read the word in context.","sentence_zh":"你必须结合上下文来理解这个词。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("text","root","编织")],
     "derivation":"con(一起)+text(编织) → 文字一起编织成的整体 → 上下文",
     "family":FAM("text","编织",[W("texture","质地"),W("textile","纺织品"),W("text","文本")]),
     "mnemonic":"text=编织(想 textile 纺织品);词句一起(con-)编织成的语言环境,就是 context 上下文、语境。",
     "forms":[F("contexts","n.","语境(复数)"),F("contextual","adj.","上下文的")]}},
  # -spect 看
  {"word":"respect","phonetic":"rɪˈspekt","pos":"n./v.","def":"尊重，敬重；方面","cefr":"B1","freq_rank":72,
   "sentence_en":"Everyone deserves respect.","sentence_zh":"每个人都值得被尊重。",
   "aids":{"morphemes":[M("re","prefix","回，反复"),M("spect","root","看")],
     "derivation":"re(反复)+spect(看) → 反复回头看重 → 尊重",
     "family":FAM("spect","看",[W("aspect","方面"),W("inspect","检查"),W("prospect","前景"),W("perspective","视角")]),
     "mnemonic":"spect=看;愿意一再(re-)回头看重某人,就是 respect 尊重;in this respect 在这方面。",
     "forms":[F("respectful","adj.","恭敬的"),F("respected","adj.","受尊敬的")]}},
  # -pand/-plex 展开/编
  {"word":"expand","phonetic":"ɪkˈspænd","pos":"v.","def":"扩大，膨胀；详述","cefr":"B1","freq_rank":74,
   "sentence_en":"The company plans to expand overseas.","sentence_zh":"公司计划向海外扩张。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("pand","root","展开(pat)")],
     "derivation":"ex(向外)+pand(展开) → 向外张开 → 扩大、膨胀",
     "family":FAM("pand/pans","展开",[W("expansion","扩张"),W("expanse","广阔空间")]),
     "mnemonic":"pand=展开(想 expanse 广阔);向外(ex-)铺展张开,就是 expand 扩大;expand on=详述。",
     "forms":[F("expansion","n.","扩张，膨胀"),F("expanded","v.","过去式/过去分词")]}},
  {"word":"complex","phonetic":"ˈkɒmpleks","pos":"adj./n.","def":"复杂的；综合体；情结","cefr":"B2","freq_rank":79,
   "sentence_en":"The problem is very complex.","sentence_zh":"这个问题非常复杂。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("plex","root","编织，折叠")],
     "derivation":"com(一起)+plex(编织) → 多股交织在一起 → 复杂的",
     "family":FAM("plex/ply","编织、折叠",[W("complicated","复杂的"),W("perplex","使困惑"),W("duplex","双的")]),
     "mnemonic":"plex=编织(想 perplex 使困惑);许多线头交织一起,就是 complex 复杂的;一堆建筑交织=综合体。",
     "forms":[F("complexity","n.","复杂性")]}},
  # -plor 喊/探
  {"word":"explore","phonetic":"ɪkˈsplɔː","pos":"v.","def":"探索，勘探；探究","cefr":"B1","freq_rank":78,
   "sentence_en":"They explored the ancient cave.","sentence_zh":"他们探索了那个古老的洞穴。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("plor","root","喊，寻(探)")],
     "derivation":"ex(向外)+plor(寻) → 向外去寻查 → 探索",
     "family":FAM("plor","喊、寻",[W("explorer","探险家"),W("deplore","悲叹")]),
     "mnemonic":"plor=寻(古时猎人向外呼喊寻猎物);走出去四处寻查未知,就是 explore 探索。",
     "forms":[F("exploration","n.","探索"),F("explorer","n.","探险家")]}},
  # -fun 履行
  {"word":"function","phonetic":"ˈfʌŋkʃən","pos":"n./v.","def":"功能，作用；运转","cefr":"B1","freq_rank":37,
   "sentence_en":"What is the function of this button?","sentence_zh":"这个按钮有什么功能？",
   "aids":{"morphemes":[M("funct","root","履行，执行"),M("ion","suffix","名词后缀")],
     "derivation":"funct(履行)+ion → 所履行的职责/作用 → 功能",
     "family":FAM("funct","履行",[W("functional","功能的"),W("malfunction","故障")]),
     "mnemonic":"funct=履行;某物所承担、执行的职责,就是 function 功能;运转正常=function 起作用;malfunction 故障。",
     "forms":[F("functional","adj.","功能的"),F("functions","n.","功能(复数)")]}},
  # -part/-cip
  {"word":"participate","phonetic":"pɑːˈtɪsɪpeɪt","pos":"v.","def":"参加，参与","cefr":"B1","freq_rank":50,
   "sentence_en":"Everyone can participate in the game.","sentence_zh":"每个人都可以参加这个游戏。",
   "aids":{"morphemes":[M("part","root","部分"),M("i","connector","连接"),M("cip","root","拿"),M("ate","suffix","动词后缀")],
     "derivation":"part(部分)+cip(拿) → 拿一份、加入其中 → 参与",
     "family":FAM("part","部分",[W("participant","参与者"),W("particle","粒子"),W("partial","部分的")]),
     "mnemonic":"part(部分)+cip(拿)——在活动里拿一份、掺一脚,就是 participate;名词 participation。",
     "forms":[F("participation","n.","参与"),F("participant","n.","参与者")]}},
  # -pos 放
  {"word":"impossible","phonetic":"ɪmˈpɒsəbl","pos":"adj.","def":"不可能的","cefr":"A2","freq_rank":82,
   "sentence_en":"It is impossible to finish in one day.","sentence_zh":"一天之内完成是不可能的。",
   "aids":{"morphemes":[M("im","prefix","不"),M("poss","root","能"),M("ible","suffix","能…的")],
     "derivation":"im(不)+possible(可能的) → 不可能的",
     "family":FAM("poss/pot","能",[W("possible","可能的"),W("potential","潜力"),W("power","力量")]),
     "mnemonic":"im-(不)+possible(可能)——办不到的,就是 impossible;词根 poss/pot=能(想 potential 潜力)。",
     "forms":[F("possible","adj.","可能的"),F("impossibility","n.","不可能")]}},
  # -sess 坐
  {"word":"assessment","phonetic":"əˈsesmənt","pos":"n.","def":"评估，评定","cefr":"B2","freq_rank":71,
   "sentence_en":"The teacher made an assessment of my work.","sentence_zh":"老师对我的作业做了评估。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sess","root","坐"),M("ment","suffix","名词后缀")],
     "derivation":"as+sess(坐) → 坐下来仔细估量(原指法官坐着定税) → 评估",
     "family":FAM("sess/sid","坐",[W("assess","评估"),W("session","会期"),W("possess","拥有")]),
     "mnemonic":"sess=坐;像法官'坐'着仔细估量定夺,就是 assessment 评估;动词 assess。",
     "forms":[F("assess","v.","评估"),F("assessments","n.","评估(复数)")]}},
  # -sess 坐
  {"word":"session","phonetic":"ˈseʃən","pos":"n.","def":"(一段)时间；会议，会期；学期","cefr":"B1","freq_rank":67,
   "sentence_en":"We had a two-hour training session.","sentence_zh":"我们进行了两小时的培训。",
   "aids":{"morphemes":[M("sess","root","坐"),M("ion","suffix","名词后缀")],
     "derivation":"sess(坐)+ion → 大家坐下来活动的一段时间 → 会期、一场",
     "family":FAM("sess/sid","坐",[W("assess","评估"),W("possess","拥有"),W("preside","主持")]),
     "mnemonic":"sess=坐;坐下来开会/做一件事的一段时段,就是 session 会期、一场、一节。",
     "forms":[F("sessions","n.","会期(复数)")]}},
  # -sci/-tell
  {"word":"intelligence","phonetic":"ɪnˈtelɪdʒəns","pos":"n.","def":"智力，才智；情报","cefr":"B2","freq_rank":30,
   "sentence_en":"Artificial intelligence is developing fast.","sentence_zh":"人工智能发展迅速。",
   "aids":{"morphemes":[M("intel","prefix","在…之间(inter)"),M("lig","root","选，读(leg)"),M("ence","suffix","名词后缀")],
     "derivation":"intel(之间)+lig(选、辨) → 在事物之间分辨选择的能力 → 智力;搜集分辨的消息 → 情报",
     "family":FAM("lig/lect","选、读",[W("intelligent","聪明的"),W("select","挑选"),W("elect","选举")]),
     "mnemonic":"lig=辨选(和 select 一家);能在纷杂中分辨挑选的脑力,就是 intelligence 智力;搜集分辨的消息=情报。",
     "forms":[F("intelligent","adj.","聪明的")]}},
  # -struct 建
  {"word":"construction","phonetic":"kənˈstrʌkʃən","pos":"n.","def":"建造，建筑；结构","cefr":"B1","freq_rank":29,
   "sentence_en":"The bridge is under construction.","sentence_zh":"这座桥正在建造中。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("struct","root","建，堆叠"),M("ion","suffix","名词后缀")],
     "derivation":"con(一起)+struct(建) → 搭建的过程/成果 → 建造、建筑",
     "family":FAM("struct","建、堆叠",[W("construct","建造"),W("structure","结构"),W("instruct","指导"),W("destruction","破坏")]),
     "mnemonic":"struct=建(想 construct);把材料一起搭建起来的过程,就是 construction 建造;under construction 施工中。",
     "forms":[F("constructions","n.","建筑(复数)")]}},
  # 高频动词/名词(常见)
  {"word":"promise","phonetic":"ˈprɒmɪs","pos":"n./v.","def":"承诺，保证；有希望","cefr":"A2","freq_rank":35,
   "sentence_en":"He kept his promise.","sentence_zh":"他信守了诺言。",
   "aids":{"morphemes":[M("pro","prefix","向前，预先"),M("mise","root","送，放(mit/miss)")],
     "derivation":"pro(预先)+mise(送) → 预先把话放出去 → 承诺",
     "family":FAM("mis/mit","送、放",[W("mission","任务"),W("submit","提交"),W("compromise","妥协")]),
     "mnemonic":"mise=送(mit 家族);把话预先(pro-)放出去、说定,就是 promise 承诺;show promise 有前途。",
     "forms":[F("promising","adj.","有前途的"),F("promised","v.","过去式/过去分词")]}},
  {"word":"combine","phonetic":"kəmˈbaɪn","pos":"v.","def":"结合，联合","cefr":"B1","freq_rank":40,
   "sentence_en":"Combine the flour and sugar.","sentence_zh":"把面粉和糖混合。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("bine","root","二，双(bi)")],
     "derivation":"com(一起)+bi(二) → 使两者合二为一 → 结合",
     "family":FAM("bi/bine","二",[W("binary","二进制的"),W("combination","组合")]),
     "mnemonic":"bine=二(想 binary 二进制);把两样一起(com-)并成一个,就是 combine 结合;名词 combination。",
     "forms":[F("combination","n.","结合，组合")]}},
  {"word":"remind","phonetic":"rɪˈmaɪnd","pos":"v.","def":"提醒，使想起","cefr":"A2","freq_rank":41,
   "sentence_en":"Please remind me to call her.","sentence_zh":"请提醒我给她打电话。",
   "aids":{"morphemes":[M("re","prefix","再"),M("mind","root","心，记")],
     "derivation":"re(再)+mind(记) → 使再记起 → 提醒",
     "family":FAM("mind/ment","心、记",[W("mind","头脑"),W("mental","精神的"),W("remember","记得")]),
     "mnemonic":"mind=心/记;把某事再(re-)推回你心里,就是 remind 提醒;remind sb of=使某人想起。",
     "forms":[F("reminder","n.","提醒物"),F("reminded","v.","过去式/过去分词")]}},
  {"word":"contact","phonetic":"ˈkɒntækt","pos":"n./v.","def":"联系，接触","cefr":"A2","freq_rank":48,
   "sentence_en":"Please contact me by email.","sentence_zh":"请通过邮件联系我。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("tact","root","触，摸")],
     "derivation":"con(一起)+tact(触) → 相互触碰 → 接触、联系",
     "family":FAM("tact/tang","触、摸",[W("contact","接触"),W("tactile","触觉的"),W("intact","完整的"),W("tangible","可触的")]),
     "mnemonic":"tact=触(想 tactile 触觉的);彼此触碰、搭上线,就是 contact 联系、接触。",
     "forms":[F("contacts","n.","联系人(复数)"),F("contacted","v.","过去式/过去分词")]}},
  {"word":"supply","phonetic":"səˈplaɪ","pos":"n./v.","def":"供给，供应；补给品","cefr":"B1","freq_rank":54,
   "sentence_en":"They supply water to the village.","sentence_zh":"他们向村庄供水。",
   "aids":{"morphemes":[M("sup","prefix","在下，向上补(sub)"),M("ply","root","填满(ple)")],
     "derivation":"sup(向上补)+ply(填满) → 从下往上填补充足 → 供应",
     "family":FAM("ple/ply","满、填",[W("supplement","补充"),W("complete","完整的"),W("plenty","充足")]),
     "mnemonic":"ply=填满(想 supplement 补充);把缺口从底下(sup-)填满,就是 supply 供应;supply and demand 供需。",
     "forms":[F("supplies","n.","补给品(复数)"),F("supplier","n.","供应商")]}},
  {"word":"desire","phonetic":"dɪˈzaɪə","pos":"n./v.","def":"渴望，欲望；想要","cefr":"B1","freq_rank":70,
   "sentence_en":"She has a strong desire to succeed.","sentence_zh":"她有强烈的成功欲望。",
   "aids":{"morphemes":[M("de","prefix","离，来自"),M("sire","root","星(sider)")],
     "derivation":"de(来自)+sire(星) → 向星星祈愿、盼望 → 渴望",
     "family":FAM("sider","星",[W("consider","考虑(观星)"),W("sidereal","恒星的")]),
     "mnemonic":"sire=星(和 consider 观星同源);像对着星星许愿般热切盼望,就是 desire 渴望。",
     "forms":[F("desired","adj.","期望的"),F("desirable","adj.","值得拥有的")]}},
  {"word":"exchange","phonetic":"ɪksˈtʃeɪndʒ","pos":"n./v.","def":"交换，交流；兑换","cefr":"B1","freq_rank":58,
   "sentence_en":"We exchanged phone numbers.","sentence_zh":"我们交换了电话号码。",
   "aids":{"morphemes":[M("ex","prefix","出，相互"),M("change","root","改变")],
     "derivation":"ex(相互)+change(换) → 相互换过来 → 交换",
     "family":FAM("change/camb","换",[W("change","改变"),W("changeable","易变的")]),
     "mnemonic":"ex-(相互)+change(换)——你我把东西换过来,就是 exchange 交换;货币兑换、交流也是 exchange。",
     "forms":[F("exchanges","n.","交换(复数)"),F("exchanged","v.","过去式/过去分词")]}},
  {"word":"damage","phonetic":"ˈdæmɪdʒ","pos":"n./v.","def":"损害，损坏","cefr":"A2","freq_rank":62,
   "sentence_en":"The storm caused serious damage.","sentence_zh":"暴风雨造成了严重损失。",
   "aids":{"morphemes":[M("dam","root","损失(damnum)"),M("age","suffix","名词后缀")],
     "derivation":"dam(损失)+age → 造成的损失 → 损害",
     "family":FAM("damn/dam","损失、罚",[W("condemn","谴责"),W("damn","诅咒")]),
     "mnemonic":"dam=损失(拉丁 damnum);使受损失,就是 damage 损害(不可数);damages 复数指'赔偿金'。",
     "forms":[F("damaged","adj.","受损的"),F("damaging","adj.","有害的")]}},
  {"word":"appropriate","phonetic":"əˈprəʊpriət","pos":"adj.","def":"适当的，恰当的","cefr":"B2","freq_rank":53,
   "sentence_en":"Wear appropriate clothes for the interview.","sentence_zh":"面试请穿得体的衣服。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("propri","root","自己的，恰当"),M("ate","suffix","…的")],
     "derivation":"ap(朝向)+propri(自己的) → 正对得上、合乎其分的 → 适当的",
     "family":FAM("propr","自己的、恰当",[W("proper","恰当的"),W("property","财产；属性"),W("proprietor","业主")]),
     "mnemonic":"propri=恰当(想 proper);正好对得上场合、合乎身份的,就是 appropriate 适当的。",
     "forms":[F("appropriately","adv.","适当地"),F("inappropriate","adj.","不适当的")]}},
  {"word":"primary","phonetic":"ˈpraɪməri","pos":"adj.","def":"首要的，主要的；初级的","cefr":"B1","freq_rank":55,
   "sentence_en":"Safety is our primary concern.","sentence_zh":"安全是我们的首要考虑。",
   "aids":{"morphemes":[M("prim","root","第一"),M("ary","suffix","…的")],
     "derivation":"prim(第一)+ary → 排第一位的 → 首要的;最早那一级 → 初级的",
     "family":FAM("prim","第一",[W("prime","首要的"),W("primitive","原始的"),W("principle","原则")]),
     "mnemonic":"prim=第一(想 prime);位列第一、最先的,就是 primary 首要的;primary school 小学。",
     "forms":[F("primarily","adv.","主要地")]}},
  {"word":"device","phonetic":"dɪˈvaɪs","pos":"n.","def":"装置，设备；手段","cefr":"B1","freq_rank":57,
   "sentence_en":"A smartphone is a useful device.","sentence_zh":"智能手机是一种有用的装置。",
   "aids":{"morphemes":[M("de","prefix","分开"),M("vice","root","分开，看(vis)")],
     "derivation":"与 devise(设计)同源;设计分划出来的巧妙东西 → 装置、手段",
     "family":FAM("vis/vid","分、看",[W("devise","设计"),W("division","分割")]),
     "mnemonic":"device 是 devise(设计)的名词;精心设计出来的小机件或巧计,就是 device 装置、手段。",
     "forms":[F("devise","v.","设计，想出"),F("devices","n.","设备(复数)")]}},
  {"word":"application","phonetic":"ˌæplɪˈkeɪʃən","pos":"n.","def":"申请；应用；应用程序","cefr":"B1","freq_rank":61,
   "sentence_en":"I filled in the application form.","sentence_zh":"我填了申请表。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("plic","root","折叠，贴"),M("ation","suffix","名词后缀")],
     "derivation":"ap(朝向)+plic(贴) → 把自己/规则贴上去 → 申请、应用",
     "family":FAM("plic/ply","折叠、贴",[W("apply","申请"),W("imply","暗示"),W("complicated","复杂的")]),
     "mnemonic":"plic=贴(和 apply 一家);把申请贴上去=申请;把规则贴到实际=应用;手机的 app=application。",
     "forms":[F("applications","n.","应用(复数)")]}},
  {"word":"leadership","phonetic":"ˈliːdəʃɪp","pos":"n.","def":"领导力；领导层","cefr":"B1","freq_rank":26,
   "sentence_en":"The team needs strong leadership.","sentence_zh":"这个团队需要强有力的领导。",
   "aids":{"morphemes":[M("leader","root","领导者"),M("ship","suffix","…的状态/能力")],
     "derivation":"leader(领导者)+ship → 当领导者的能力/群体 → 领导力",
     "family":FAM("","相关词",[W("leader","领导者"),W("lead","带领")]),
     "mnemonic":"leader+ship(-ship 表能力/身份,如 friendship);当好领头人的本事,就是 leadership 领导力。",
     "forms":[F("leader","n.","领导者")]}},
  {"word":"category","phonetic":"ˈkætɪɡəri","pos":"n.","def":"类别，种类","cefr":"B2","freq_rank":43,
   "sentence_en":"Books are sorted into categories.","sentence_zh":"书籍按类别分类。",
   "aids":{"morphemes":[M("cate","prefix","向下，依据(kata)"),M("gor","root","说，聚集"),M("y","suffix","名词后缀")],
     "derivation":"希腊 kategoria'断言、归类';按性质归到一起的一组 → 类别",
     "family":FAM("","相关词",[W("categorize","分类"),W("categorical","绝对的")]),
     "mnemonic":"把同性质的事物归拢成一组,就是 category 类别;动词 categorize 分类。",
     "forms":[F("categories","n.","类别(复数)"),F("categorize","v.","分类")]}},
  {"word":"academic","phonetic":"ˌækəˈdemɪk","pos":"adj./n.","def":"学术的，学业的；学者","cefr":"B2","freq_rank":44,
   "sentence_en":"She has a strong academic record.","sentence_zh":"她学业成绩优异。",
   "aids":{"morphemes":[M("academ","root","学园(Academy)"),M("ic","suffix","…的")],
     "derivation":"源自柏拉图讲学的'Akademeia 学园';与学园、学问有关的 → 学术的",
     "family":FAM("","相关词",[W("academy","学院"),W("academically","学业上")]),
     "mnemonic":"源自柏拉图的学园 Academy;和学问、学业有关的,就是 academic 学术的;academic year 学年。",
     "forms":[F("academy","n.","学院"),F("academically","adv.","学业上")]}},
  {"word":"negative","phonetic":"ˈneɡətɪv","pos":"adj./n.","def":"否定的；消极的；负的","cefr":"B1","freq_rank":45,
   "sentence_en":"He has a negative attitude.","sentence_zh":"他态度消极。",
   "aids":{"morphemes":[M("neg","root","否定，不"),M("ative","suffix","…的")],
     "derivation":"neg(否)+ative → 表示否定/负向的 → 否定的、消极的",
     "family":FAM("neg","否定",[W("deny","否认"),W("neglect","忽视"),W("negotiate","谈判")]),
     "mnemonic":"neg=否(想 deny 否认);说'不'的、往坏处走的、数轴负向的,就是 negative;反义 positive。",
     "forms":[F("negatively","adv.","消极地")]}},
  {"word":"justice","phonetic":"ˈdʒʌstɪs","pos":"n.","def":"正义，公正；司法","cefr":"B1","freq_rank":49,
   "sentence_en":"They fought for justice.","sentence_zh":"他们为正义而战。",
   "aids":{"morphemes":[M("just","root","公正，法"),M("ice","suffix","名词后缀")],
     "derivation":"just(公正)+ice → 公正的状态 → 正义、司法",
     "family":FAM("just/jur","公正、法",[W("just","公正的"),W("justify","证明正当"),W("jury","陪审团")]),
     "mnemonic":"just=公正(想 just 公平的);合乎公道、依法裁断,就是 justice 正义、司法。",
     "forms":[F("justify","v.","证明…正当"),F("just","adj.","公正的")]}},
  {"word":"corporate","phonetic":"ˈkɔːpərət","pos":"adj.","def":"公司的，法人的；共同的","cefr":"B2","freq_rank":75,
   "sentence_en":"She works in corporate finance.","sentence_zh":"她从事公司财务工作。",
   "aids":{"morphemes":[M("corpor","root","身体，团体(corpus)"),M("ate","suffix","…的")],
     "derivation":"corpor(身体)+ate → 结成一个法人'团体'的 → 公司的",
     "family":FAM("corpor/corp","身体、团体",[W("corporation","公司"),W("corpse","尸体"),W("corps","军团")]),
     "mnemonic":"corpor=身体/团体(想 corporation 公司);组成一个法人'集体'的,就是 corporate 公司的。",
     "forms":[F("corporation","n.","公司")]}},
  {"word":"urban","phonetic":"ˈɜːbən","pos":"adj.","def":"城市的，都市的","cefr":"B1","freq_rank":76,
   "sentence_en":"Urban life can be stressful.","sentence_zh":"都市生活可能压力很大。",
   "aids":{"morphemes":[M("urb","root","城市"),M("an","suffix","…的")],
     "derivation":"urb(城市)+an → 与城市有关的 → 城市的",
     "family":FAM("urb","城市",[W("urbanize","使城市化"),W("suburb","郊区(城下方)")]),
     "mnemonic":"urb=城市;属于城里的,就是 urban;反义 rural 乡村的;sub-urb=城市下缘=郊区 suburb。",
     "forms":[F("suburb","n.","郊区"),F("urbanization","n.","城市化")]}},
  {"word":"mental","phonetic":"ˈmentl","pos":"adj.","def":"精神的，心理的；智力的","cefr":"B1","freq_rank":77,
   "sentence_en":"Mental health is important.","sentence_zh":"心理健康很重要。",
   "aids":{"morphemes":[M("ment","root","心，智"),M("al","suffix","…的")],
     "derivation":"ment(心)+al → 与心智有关的 → 精神的",
     "family":FAM("ment","心、智",[W("mention","提到"),W("comment","评论"),W("mentor","导师")]),
     "mnemonic":"ment=心/智;关于头脑、心理层面的,就是 mental;mental health 心理健康。",
     "forms":[F("mentally","adv.","精神上")]}},
  {"word":"domestic","phonetic":"dəˈmestɪk","pos":"adj.","def":"国内的；家庭的；驯养的","cefr":"B2","freq_rank":68,
   "sentence_en":"They sell to the domestic market.","sentence_zh":"他们面向国内市场销售。",
   "aids":{"morphemes":[M("dom","root","家"),M("estic","suffix","…的")],
     "derivation":"dom(家)+estic → 家里的/本国的 → 家庭的、国内的",
     "family":FAM("dom","家",[W("dome","圆顶"),W("domain","领域"),W("dominate","支配")]),
     "mnemonic":"dom=家(想 dome 圆顶、domain 领地);自家的、本国的、家养的,就是 domestic。",
     "forms":[F("domestically","adv.","国内地")]}},
  {"word":"literature","phonetic":"ˈlɪtərətʃə","pos":"n.","def":"文学；文献","cefr":"B1","freq_rank":69,
   "sentence_en":"She studied English literature.","sentence_zh":"她学的是英国文学。",
   "aids":{"morphemes":[M("liter","root","字母，文字"),M("ature","suffix","名词后缀")],
     "derivation":"liter(文字)+ature → 用文字写成的作品 → 文学、文献",
     "family":FAM("liter","字母、文字",[W("literary","文学的"),W("literal","字面的"),W("literacy","读写能力")]),
     "mnemonic":"liter=文字(想 literal 字面的);用文字写就的作品集合,就是 literature 文学;某领域资料=文献。",
     "forms":[F("literary","adj.","文学的")]}},
  {"word":"surround","phonetic":"səˈraʊnd","pos":"v.","def":"包围，环绕","cefr":"B1","freq_rank":80,
   "sentence_en":"Mountains surround the village.","sentence_zh":"群山环绕着村庄。",
   "aids":{"morphemes":[M("sur","prefix","超过，在上"),M("round","root","圆，绕")],
     "derivation":"sur(在上)+round(绕) → 绕着圈围住 → 包围、环绕",
     "family":FAM("round","圆、绕",[W("round","圆的"),W("around","周围")]),
     "mnemonic":"sur-(周遭)+round(绕圈)——绕一圈把它围住,就是 surround 包围;surroundings 周围环境。",
     "forms":[F("surrounding","adj.","周围的"),F("surroundings","n.","环境")]}},
  # 常见词
  {"word":"weapon","phonetic":"ˈwepən","pos":"n.","def":"武器，兵器","cefr":"B1","freq_rank":10,
   "sentence_en":"The soldiers carried weapons.","sentence_zh":"士兵们携带着武器。",
   "aids":{"morphemes":[M("weapon","root","武器(古英语 wǣpen)")],
     "derivation":"古英语 wǣpen'武器'。→ 用于攻防的器械 → 武器",
     "family":FAM("","相关词",[W("weaponry","武器(总称)")]),
     "mnemonic":"weapon 就是'武器';用来打斗攻防的家伙,不论刀枪还是核弹,都是 weapon;weapons of mass destruction 大规模杀伤性武器。",
     "forms":[F("weapons","n.","武器(复数)")]}},
  {"word":"traditional","phonetic":"trəˈdɪʃənl","pos":"adj.","def":"传统的，惯例的","cefr":"A2","freq_rank":9,
   "sentence_en":"They wore traditional costumes.","sentence_zh":"他们穿着传统服装。",
   "aids":{"morphemes":[M("tra","prefix","传，越过"),M("dit","root","给"),M("ional","suffix","…的")],
     "derivation":"tra(传)+dit(给) → 世代传交下来的 → 传统的",
     "family":FAM("dit/dat","给",[W("tradition","传统"),W("edit","编辑"),W("add","增加")]),
     "mnemonic":"dit=给(拉丁 dare);一代代传(tra-)交下来的,就是 traditional 传统的;名词 tradition。",
     "forms":[F("tradition","n.","传统"),F("traditionally","adv.","传统上")]}},
  {"word":"cultural","phonetic":"ˈkʌltʃərəl","pos":"adj.","def":"文化的","cefr":"B1","freq_rank":11,
   "sentence_en":"The city has a rich cultural life.","sentence_zh":"这座城市文化生活丰富。",
   "aids":{"morphemes":[M("cult","root","耕种，培养"),M("ural","suffix","…的")],
     "derivation":"cult(培养)+ural → 精神上'培育'出来的成果 → 文化的",
     "family":FAM("cult","耕种、培养",[W("culture","文化"),W("cultivate","耕作，培养"),W("agriculture","农业")]),
     "mnemonic":"cult=耕种/培养(想 cultivate);一个群体精神上'耕耘'出的东西=文化,cultural 文化的。",
     "forms":[F("culture","n.","文化"),F("culturally","adv.","文化上")]}},
  {"word":"commercial","phonetic":"kəˈmɜːʃəl","pos":"adj./n.","def":"商业的；商业广告","cefr":"B1","freq_rank":15,
   "sentence_en":"It was made for commercial use.","sentence_zh":"它是为商业用途制造的。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("merc","root","交易，商品"),M("ial","suffix","…的")],
     "derivation":"com(一起)+merc(交易) → 与买卖有关的 → 商业的",
     "family":FAM("merc","交易、商品",[W("merchant","商人"),W("market","市场"),W("mercy","仁慈")]),
     "mnemonic":"merc=交易(想 merchant 商人、market 市场);和做买卖有关的,就是 commercial 商业的;电视上的 commercial=广告。",
     "forms":[F("commercially","adv.","商业上"),F("commerce","n.","商业")]}},
  {"word":"civil","phonetic":"ˈsɪvl","pos":"adj.","def":"公民的，民用的；民事的","cefr":"B2","freq_rank":17,
   "sentence_en":"Voting is a civil right.","sentence_zh":"投票是一项公民权利。",
   "aids":{"morphemes":[M("civ","root","公民，城市"),M("il","suffix","…的")],
     "derivation":"civ(公民)+il → 与公民/民间有关的 → 公民的、民用的",
     "family":FAM("civ","公民",[W("civilian","平民"),W("civilization","文明"),W("city","城市")]),
     "mnemonic":"civ=公民(想 civilian 平民、city 城市);属于公民、民间的,就是 civil;civil war 内战;civil rights 公民权。",
     "forms":[F("civilian","n.","平民"),F("civilization","n.","文明")]}},
  {"word":"budget","phonetic":"ˈbʌdʒɪt","pos":"n./v.","def":"预算；把…编入预算","cefr":"B1","freq_rank":18,
   "sentence_en":"We are on a tight budget.","sentence_zh":"我们预算紧张。",
   "aids":{"morphemes":[M("budg","root","小皮包(bougette)"),M("et","suffix","小")],
     "derivation":"古法语 bougette'小钱袋';旧时财政大臣把方案装在皮包里 → 预算",
     "family":FAM("","相关词",[W("budgetary","预算的")]),
     "mnemonic":"budget 原指装钱的'小皮包';打开钱袋盘算怎么花,就是 budget 预算;on a budget 省着花。",
     "forms":[F("budgets","n.","预算(复数)"),F("budgeted","v.","过去式/过去分词")]}},
  {"word":"victim","phonetic":"ˈvɪktɪm","pos":"n.","def":"受害者，牺牲品","cefr":"B1","freq_rank":19,
   "sentence_en":"He was a victim of the crime.","sentence_zh":"他是这起犯罪的受害者。",
   "aids":{"morphemes":[M("victim","root","祭牲(victima)")],
     "derivation":"拉丁 victima'献祭的牲畜';引申遭受伤害的人 → 受害者",
     "family":FAM("","相关词",[W("victimize","使受害"),W("victimization","迫害")]),
     "mnemonic":"victim 本义'祭坛上的牺牲';无辜遭殃、被伤害的人,就是 victim 受害者;fall victim to 沦为…的牺牲品。",
     "forms":[F("victims","n.","受害者(复数)")]}},
  {"word":"district","phonetic":"ˈdɪstrɪkt","pos":"n.","def":"地区，区域；行政区","cefr":"B1","freq_rank":22,
   "sentence_en":"She lives in the business district.","sentence_zh":"她住在商业区。",
   "aids":{"morphemes":[M("di","prefix","分开"),M("strict","root","拉紧，管辖(string)")],
     "derivation":"di(分开)+strict(管辖) → 划分出来受管辖的一片 → 行政区",
     "family":FAM("strict/string","拉紧",[W("strict","严格的"),W("restrict","限制"),W("string","线")]),
     "mnemonic":"strict=管辖/拉紧(想 restrict 限制);划(di-)出来单独管辖的一片地,就是 district 地区、行政区。",
     "forms":[F("districts","n.","地区(复数)")]}},
  {"word":"facility","phonetic":"fəˈsɪlɪti","pos":"n.","def":"设施；容易，便利","cefr":"B2","freq_rank":25,
   "sentence_en":"The hotel has excellent facilities.","sentence_zh":"这家酒店设施一流。",
   "aids":{"morphemes":[M("fac","root","做"),M("ility","suffix","名词后缀")],
     "derivation":"fac(做)+ility → 使事情好做的东西/性质 → 设施、便利",
     "family":FAM("fac/fic","做",[W("facile","容易的"),W("factory","工厂"),W("faculty","才能；系")]),
     "mnemonic":"fac=做(想 facile 容易做的);让事情变好做的场所/设备,就是 facility 设施;单数指'便利'。",
     "forms":[F("facilities","n.","设施(复数)"),F("facilitate","v.","促进")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 7
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
