#!/usr/bin/env python
# 第十六批(约50词):逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -draw 拉
  {"word":"withdraw","phonetic":"wɪðˈdrɔː","pos":"v.","def":"撤回，撤退；取(款)","cefr":"B2","freq_rank":74,
   "sentence_en":"She withdrew some money from the bank.","sentence_zh":"她从银行取了些钱。",
   "aids":{"morphemes":[M("with","prefix","向后，离(反)"),M("draw","root","拉")],
     "derivation":"with(向后)+draw(拉) → 往回拉、抽走 → 撤回、取款",
     "family":FAM("draw","拉、画",[W("draw","拉；画"),W("drawer","抽屉"),W("draft","草稿")]),
     "mnemonic":"with-(往回)+draw(拉)——把话/军队/钱往回抽,就是 withdraw 撤回、取款(不规则:withdrew/withdrawn)。",
     "forms":[F("withdrawal","n.","撤回；取款"),F("withdrew","v.","过去式")]}},
  # -miss 送
  {"word":"dismiss","phonetic":"dɪsˈmɪs","pos":"v.","def":"解雇，开除；解散；不予考虑","cefr":"B2","freq_rank":79,
   "sentence_en":"He was dismissed from his job.","sentence_zh":"他被解雇了。",
   "aids":{"morphemes":[M("dis","prefix","离开，分散"),M("miss","root","送，派")],
     "derivation":"dis(离)+miss(送) → 打发走 → 解雇、解散",
     "family":FAM("mit/miss","送、派",[W("mission","任务"),W("submit","提交"),W("permit","允许"),W("transmit","传送")]),
     "mnemonic":"miss=送(和 mission 一家);把人打发(dis-)走=解雇/解散;把想法'打发走'=不予考虑(dismiss the idea)。",
     "forms":[F("dismissal","n.","解雇")]}},
  # -sess 坐
  {"word":"possess","phonetic":"pəˈzes","pos":"v.","def":"拥有，占有；(情绪)控制","cefr":"B2","freq_rank":95,
   "sentence_en":"She possesses great talent.","sentence_zh":"她拥有非凡的才能。",
   "aids":{"morphemes":[M("pos","prefix","有力，能(pot)"),M("sess","root","坐")],
     "derivation":"pos(能)+sess(坐) → 稳坐其上、占着 → 拥有",
     "family":FAM("sess/sid","坐",[W("session","会期"),W("assess","评估"),W("preside","主持")]),
     "mnemonic":"sess=坐(和 session 一家);像主人稳坐占着,就是 possess 拥有;possession 财产;被恶念'占据'=possessed。",
     "forms":[F("possession","n.","拥有；财产"),F("possessive","adj.","占有欲强的")]}},
  # -volu 卷
  {"word":"evolve","phonetic":"ɪˈvɒlv","pos":"v.","def":"(使)进化，(逐渐)发展","cefr":"B2","freq_rank":89,
   "sentence_en":"Birds evolved from dinosaurs.","sentence_zh":"鸟类从恐龙进化而来。",
   "aids":{"morphemes":[M("e","prefix","向外"),M("volve","root","卷，转")],
     "derivation":"e(向外)+volve(卷) → 向外一层层展开 → 逐渐发展、进化",
     "family":FAM("volv/volu","卷、转",[W("revolve","旋转"),W("involve","涉及"),W("volume","卷"),W("revolution","革命")]),
     "mnemonic":"volve=卷(和 involve 一家);像卷轴向外(e-)徐徐展开,就是 evolve 进化、发展;evolution 进化。",
     "forms":[F("evolution","n.","进化，演变"),F("evolutionary","adj.","进化的")]}},
  # -just 正
  {"word":"justify","phonetic":"ˈdʒʌstɪfaɪ","pos":"v.","def":"证明…正当，为…辩护","cefr":"B2","freq_rank":91,
   "sentence_en":"Nothing can justify such cruelty.","sentence_zh":"没有什么能为如此残忍开脱。",
   "aids":{"morphemes":[M("just","root","公正，正当"),M("ify","suffix","使…")],
     "derivation":"just(正当)+ify → 使显得正当 → 证明正当",
     "family":FAM("just/jur","公正、法",[W("just","公正的"),W("justice","正义"),W("adjust","调整")]),
     "mnemonic":"just=正当(想 justice 正义);说明某事合情合理、站得住,就是 justify;justification 正当理由。",
     "forms":[F("justification","n.","正当理由")]}},
  # -exter 外
  {"word":"external","phonetic":"ɪkˈstɜːnl","pos":"adj.","def":"外部的，外面的；外来的","cefr":"B2","freq_rank":106,
   "sentence_en":"The building needs external repairs.","sentence_zh":"这栋楼需要外部修缮。",
   "aids":{"morphemes":[M("exter","root","外面(exter)"),M("nal","suffix","…的")],
     "derivation":"exter(外面)+nal → 外面的 → 外部的",
     "family":FAM("exter/extra","外",[W("exterior","外部"),W("extra","额外的"),W("extreme","极端的")]),
     "mnemonic":"exter=外(想 exterior 外部);处于外面/来自外部的,就是 external;反义 internal 内部的。",
     "forms":[F("externally","adv.","外部地")]}},
  # -st 站
  {"word":"constitute","phonetic":"ˈkɒnstɪtjuːt","pos":"v.","def":"构成，组成；设立","cefr":"C1","freq_rank":114,
   "sentence_en":"Twelve months constitute a year.","sentence_zh":"十二个月构成一年。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("stitut","root","建立，站")],
     "derivation":"con(一起)+stitut(立) → 一起立起、组成 → 构成",
     "family":FAM("st/stitut","站、建立",[W("institution","机构"),W("substitute","替代"),W("statute","法令")]),
     "mnemonic":"stitut=立(和 institution 一家);各部分一起(con-)立起、组成整体,就是 constitute;constitution 宪法/构成。",
     "forms":[F("constitution","n.","宪法；构成")]}},
  # -vers 转
  {"word":"convert","phonetic":"kənˈvɜːt","pos":"v.","def":"(使)转变，转换；改变信仰","cefr":"B2","freq_rank":118,
   "sentence_en":"They converted the barn into a house.","sentence_zh":"他们把谷仓改造成了房子。",
   "aids":{"morphemes":[M("con","prefix","完全"),M("vert","root","转")],
     "derivation":"con(完全)+vert(转) → 完全转变 → 转换",
     "family":FAM("vers/vert","转",[W("reverse","颠倒"),W("version","版本"),W("universe","宇宙"),W("diverse","多样的")]),
     "mnemonic":"vert=转(和 reverse 一家);从一种彻底(con-)转成另一种,就是 convert 转换;conversion 转变。",
     "forms":[F("conversion","n.","转变，转换")]}},
  {"word":"controversy","phonetic":"ˈkɒntrəvɜːsi","pos":"n.","def":"争议，争论","cefr":"C1","freq_rank":111,
   "sentence_en":"The decision caused great controversy.","sentence_zh":"这一决定引起了极大争议。",
   "aids":{"morphemes":[M("contro","prefix","相反(contra)"),M("vers","root","转"),M("y","suffix","名词后缀")],
     "derivation":"contra(相反)+vers(转) → 双方转向对立 → 争议",
     "family":FAM("vers/vert","转",[W("reverse","颠倒"),W("convert","转换"),W("adverse","不利的")]),
     "mnemonic":"contra(相反)+vers(转)——立场转到对立面吵起来,就是 controversy 争议;controversial 有争议的。",
     "forms":[F("controversial","adj.","有争议的")]}},
  {"word":"diverse","phonetic":"daɪˈvɜːs","pos":"adj.","def":"不同的，多种多样的","cefr":"B2","freq_rank":85,
   "sentence_en":"The city has a diverse population.","sentence_zh":"这座城市人口多元。",
   "aids":{"morphemes":[M("di","prefix","分开(dis)"),M("vers","root","转，方向")],
     "derivation":"di(分开)+vers(转) → 各转各的方向 → 多样的",
     "family":FAM("vers/vert","转",[W("diversity","多样性"),W("reverse","颠倒"),W("convert","转换")]),
     "mnemonic":"vers=转(和 diversity 一家);各朝不同方向、种类繁多,就是 diverse 多样的;diversity 多样性。",
     "forms":[F("diversity","n.","多样性"),F("diversify","v.","使多样化")]}},
  # -alter 另一
  {"word":"alter","phonetic":"ˈɔːltə","pos":"v.","def":"改变，更改；改动(衣服)","cefr":"B2","freq_rank":115,
   "sentence_en":"We had to alter our plans.","sentence_zh":"我们不得不更改计划。",
   "aids":{"morphemes":[M("alter","root","另一，其他")],
     "derivation":"alter(另一)→ 变成另一个样子 → 改变",
     "family":FAM("alter","另一、改变",[W("alternative","替代方案"),W("alternate","交替"),W("alien","外来的")]),
     "mnemonic":"alter=另一个(想 alternative);把它变成另一副样子,就是 alter 改变;alteration 改动;别和 altar(祭坛)混。",
     "forms":[F("alteration","n.","改动，变更")]}},
  # -min 突出
  {"word":"prominent","phonetic":"ˈprɒmɪnənt","pos":"adj.","def":"突出的，显著的；杰出的","cefr":"B2","freq_rank":120,
   "sentence_en":"He is a prominent scientist.","sentence_zh":"他是位杰出的科学家。",
   "aids":{"morphemes":[M("pro","prefix","向前"),M("min","root","突出，伸(min/ment)"),M("ent","suffix","…的")],
     "derivation":"pro(向前)+min(突出) → 向前凸出的 → 突出的、杰出的",
     "family":FAM("min/ment","突出、伸",[W("eminent","杰出的"),W("imminent","迫近的"),W("mountain","山")]),
     "mnemonic":"min=突出(想 eminent 杰出、mountain 山凸起);向前(pro-)凸显出来的,就是 prominent 突出的、杰出的。",
     "forms":[F("prominence","n.","突出，显赫")]}},
  # -prehend 抓
  {"word":"comprehensive","phonetic":"ˌkɒmprɪˈhensɪv","pos":"adj.","def":"全面的，综合的","cefr":"B2","freq_rank":119,
   "sentence_en":"The report is comprehensive.","sentence_zh":"这份报告很全面。",
   "aids":{"morphemes":[M("com","prefix","一起，全"),M("prehens","root","抓"),M("ive","suffix","…的")],
     "derivation":"com(全)+prehens(抓) → 全都抓进来的 → 全面的",
     "family":FAM("prehend/prise","抓",[W("comprehend","理解"),W("comprise","包含"),W("enterprise","企业"),W("surprise","惊讶")]),
     "mnemonic":"prehens=抓(和 comprehend 理解=抓住含义);把方方面面全(com-)抓进来,就是 comprehensive 全面的。",
     "forms":[F("comprehend","v.","理解"),F("comprehension","n.","理解(力)")]}},
  # -sight 看
  {"word":"insight","phonetic":"ˈɪnsaɪt","pos":"n.","def":"洞察力，深刻理解","cefr":"B2","freq_rank":94,
   "sentence_en":"The book offers insight into human nature.","sentence_zh":"这本书让人深刻洞悉人性。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("sight","root","看，视力")],
     "derivation":"in(向内)+sight(看) → 看进内部、看透 → 洞察力",
     "family":FAM("sight/see","看",[W("sight","视力"),W("foresight","远见"),W("oversight","疏忽")]),
     "mnemonic":"in(向内)+sight(看)——能看进事物内部、看透本质的眼力,就是 insight 洞察力;insightful 有洞见的。",
     "forms":[F("insights","n.","洞见(复数)"),F("insightful","adj.","有洞察力的")]}},
  # -tend 伸
  {"word":"extensive","phonetic":"ɪkˈstensɪv","pos":"adj.","def":"广泛的，大量的","cefr":"B2","freq_rank":97,
   "sentence_en":"She has extensive experience.","sentence_zh":"她有丰富的经验。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("tens","root","伸展"),M("ive","suffix","…的")],
     "derivation":"ex(向外)+tens(伸) → 向外伸展得很开的 → 广泛的",
     "family":FAM("tend/tens","伸展",[W("extend","延伸"),W("tension","紧张"),W("intense","强烈的")]),
     "mnemonic":"tens=伸(和 extend 一家);向外(ex-)铺展得很广的,就是 extensive 广泛的;extent 程度。",
     "forms":[F("extensively","adv.","广泛地")]}},
  # -lax 松
  {"word":"relax","phonetic":"rɪˈlæks","pos":"v.","def":"放松，休息；使缓和","cefr":"A2","freq_rank":104,
   "sentence_en":"Sit down and relax.","sentence_zh":"坐下来放松一下。",
   "aids":{"morphemes":[M("re","prefix","回，back"),M("lax","root","松")],
     "derivation":"re(回)+lax(松) → 松回去、松下来 → 放松",
     "family":FAM("lax/lease","松",[W("release","释放"),W("lease","租约"),W("lax","松懈的")]),
     "mnemonic":"lax=松(想 lax 松懈的);把绷紧的神经/肌肉松(re-)下来,就是 relax 放松;relaxation 放松。",
     "forms":[F("relaxation","n.","放松"),F("relaxed","adj.","放松的")]}},
  # -ven 来
  {"word":"adventure","phonetic":"ədˈventʃə","pos":"n.","def":"冒险，冒险经历","cefr":"B1","freq_rank":105,
   "sentence_en":"They set off on an adventure.","sentence_zh":"他们踏上了冒险之旅。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("vent","root","来"),M("ure","suffix","名词后缀")],
     "derivation":"ad(朝向)+vent(来) → 朝未知走去、看会来什么 → 冒险",
     "family":FAM("ven","来",[W("event","事件"),W("invent","发明"),W("prevent","预防"),W("convention","惯例")]),
     "mnemonic":"vent=来(想 event);朝(ad-)未知走去、迎接不知会'来'什么,就是 adventure 冒险;adventurous 爱冒险的。",
     "forms":[F("adventurous","adj.","爱冒险的")]}},
  # -salt/-sault 跳
  {"word":"assault","phonetic":"əˈsɔːlt","pos":"n./v.","def":"袭击，攻击；殴打","cefr":"C1","freq_rank":103,
   "sentence_en":"He was charged with assault.","sentence_zh":"他被控殴打罪。",
   "aids":{"morphemes":[M("as","prefix","朝向(ad 变体)"),M("sault","root","跳(salt)")],
     "derivation":"as(朝向)+sault(跳) → 朝人猛扑上去 → 袭击",
     "family":FAM("sal/sault","跳",[W("assault","袭击"),W("insult","侮辱(跳到身上)"),W("result","结果"),W("salmon","鲑鱼(跳)")]),
     "mnemonic":"sault=跳(和 insult 一家);朝人猛扑猛跳上去动手,就是 assault 袭击、殴打。",
     "forms":[F("assaults","n.","袭击(复数)")]}},
  # -prov 证明
  {"word":"proof","phonetic":"pruːf","pos":"n.","def":"证据，证明；校样","cefr":"B1","freq_rank":107,
   "sentence_en":"Do you have any proof?","sentence_zh":"你有任何证据吗？",
   "aids":{"morphemes":[M("proof","root","证明(prove)")],
     "derivation":"prove(证明)的名词形式 → 证据",
     "family":FAM("prov/prob","证明、检验",[W("prove","证明"),W("approve","批准"),W("probable","很可能的")]),
     "mnemonic":"proof 是 prove(证明)的名词;能证明为真的东西,就是 proof 证据;waterproof 防水的(经得起水的检验)。",
     "forms":[F("prove","v.","证明")]}},
  # 高频名词/动词(常见/词根)
  {"word":"finance","phonetic":"ˈfaɪnæns","pos":"n./v.","def":"财政，金融；资金；提供资金","cefr":"B2","freq_rank":83,
   "sentence_en":"She works in finance.","sentence_zh":"她从事金融业。",
   "aids":{"morphemes":[M("fin","root","结束，付清(界限)"),M("ance","suffix","名词后缀")],
     "derivation":"fin(付清、了结)+ance → 与钱款结算有关的 → 财政、金融",
     "family":FAM("fin","界限、结束",[W("final","最终的"),W("fine","罚款"),W("define","定义")]),
     "mnemonic":"fin=了结/付清(想 fine 罚款);和钱款结算、筹措有关的,就是 finance 财政/金融;financial 财政的。",
     "forms":[F("financial","adj.","财政的"),F("financing","n.","融资")]}},
  {"word":"platform","phonetic":"ˈplætfɔːm","pos":"n.","def":"平台；站台；讲台；纲领","cefr":"B1","freq_rank":82,
   "sentence_en":"The train is at platform 2.","sentence_zh":"火车在2号站台。",
   "aids":{"morphemes":[M("plat","root","平，扁(flat)"),M("form","root","形状")],
     "derivation":"plat(平)+form(形状) → 平的台面 → 平台、站台",
     "family":FAM("plat/plan","平",[W("plain","平原"),W("plane","平面")]),
     "mnemonic":"plat=平(想 plain 平原)+form(形);一块平台面,就是 platform 平台/站台/讲台;政党的'纲领'也是 platform。",
     "forms":[F("platforms","n.","平台(复数)")]}},
  {"word":"delivery","phonetic":"dɪˈlɪvəri","pos":"n.","def":"递送，交付；分娩","cefr":"B1","freq_rank":80,
   "sentence_en":"Free delivery on all orders.","sentence_zh":"所有订单免费送货。",
   "aids":{"morphemes":[M("de","prefix","去除，离"),M("liver","root","自由(liber)"),M("y","suffix","名词后缀")],
     "derivation":"deliver(放走、送出)+y → 递送的行为 → 交付",
     "family":FAM("liber","自由",[W("deliver","递送"),W("liberty","自由"),W("liberate","解放")]),
     "mnemonic":"deliver(送出)的名词;把货'放'到目的地=delivery 递送;把婴儿'交付'到世上=分娩(delivery room 产房)。",
     "forms":[F("deliver","v.","递送")]}},
  {"word":"license","phonetic":"ˈlaɪsns","pos":"n./v.","def":"执照，许可证；许可，特许","cefr":"B1","freq_rank":109,
   "sentence_en":"You need a license to drive.","sentence_zh":"开车需要驾照。",
   "aids":{"morphemes":[M("lic","root","允许(licere)"),M("ense","suffix","名词后缀")],
     "derivation":"拉丁 licere'被允许';官方给的许可 → 执照",
     "family":FAM("lic","允许",[W("licence","许可证(英式)")]),
     "mnemonic":"lic=允许(想 it is licit 合法的);官方发的'准许你做某事'的证,就是 license 执照;英式拼 licence。",
     "forms":[F("licensed","adj.","持证的")]}},
  {"word":"shelter","phonetic":"ˈʃeltə","pos":"n./v.","def":"庇护所，避难所；遮蔽，保护","cefr":"B1","freq_rank":110,
   "sentence_en":"They took shelter from the rain.","sentence_zh":"他们躲雨避了一下。",
   "aids":{"morphemes":[M("shelter","root","遮蔽(可能源自 shield 盾)")],
     "derivation":"可能与 shield(盾)相关'遮护';挡风避雨之处 → 避难所",
     "family":FAM("","相关词",[W("sheltered","受保护的")]),
     "mnemonic":"shelter≈用盾(shield)遮护;挡风雨、避危险的地方=避难所;给予庇护=shelter;take shelter 躲避。",
     "forms":[F("sheltered","adj.","受保护的")]}},
  {"word":"profession","phonetic":"prəˈfeʃən","pos":"n.","def":"职业，行业(尤指专业性的)","cefr":"B1","freq_rank":113,
   "sentence_en":"Teaching is a noble profession.","sentence_zh":"教书是崇高的职业。",
   "aids":{"morphemes":[M("pro","prefix","公开"),M("fess","root","说，宣称"),M("ion","suffix","名词后缀")],
     "derivation":"pro(公开)+fess(宣称) → 公开宣称精通的行当 → (专业)职业",
     "family":FAM("fess","说、宣称",[W("professional","专业的"),W("confess","坦白"),W("professor","教授")]),
     "mnemonic":"fess=说(和 confess 坦白一家);公开(pro-)宣称以此为专长的行业,就是 profession;professional 专业的。",
     "forms":[F("professional","adj.","专业的")]}},
  {"word":"craft","phonetic":"krɑːft","pos":"n./v.","def":"手艺，工艺；精心制作","cefr":"B2","freq_rank":93,
   "sentence_en":"Pottery is a traditional craft.","sentence_zh":"制陶是一门传统手艺。",
   "aids":{"morphemes":[M("craft","root","力量，技艺(古英语 cræft)")],
     "derivation":"古英语'力量、技能';手上的技能 → 手艺",
     "family":FAM("craft","技艺",[W("aircraft","飞行器"),W("crafty","狡猾的"),W("handicraft","手工艺")]),
     "mnemonic":"craft=技艺;需要手上功夫的活=手艺、工艺;精雕细琢地做=craft;aircraft 飞行器;crafty 有'心机'的。",
     "forms":[F("crafts","n.","手工艺(复数)"),F("crafted","v.","过去式/过去分词")]}},
  {"word":"headquarters","phonetic":"ˈhedkwɔːtəz","pos":"n.","def":"总部，司令部","cefr":"B2","freq_rank":108,
   "sentence_en":"The company's headquarters is in London.","sentence_zh":"公司总部在伦敦。",
   "aids":{"morphemes":[M("head","root","头，首"),M("quarters","root","住所，营区")],
     "derivation":"head(首)+quarters(营区) → 首脑所在的营区 → 总部",
     "family":FAM("","相关词",[W("quarter","四分之一；地区")]),
     "mnemonic":"head(首脑)+quarters(驻地)——指挥中枢所在地,就是 headquarters 总部/司令部(常缩写 HQ)。",
     "forms":[]}},
  {"word":"ingredient","phonetic":"ɪnˈɡriːdiənt","pos":"n.","def":"(烹饪)原料，配料；成分，要素","cefr":"B1","freq_rank":45,
   "sentence_en":"Mix all the ingredients together.","sentence_zh":"把所有配料混合在一起。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("gred","root","走(grad)"),M("ient","suffix","…的东西")],
     "derivation":"in(向内)+gred(走) → '走进'配方里的东西 → 配料、成分",
     "family":FAM("grad/gress","走、步",[W("progress","进步"),W("gradual","逐渐的"),W("aggressive","好斗的")]),
     "mnemonic":"gred=走(和 progress 一家);'走进'一道菜/一件事里的组成物,就是 ingredient 配料、要素。",
     "forms":[F("ingredients","n.","配料(复数)")]}},
  # 高频形容词/副词
  {"word":"mutual","phonetic":"ˈmjuːtʃuəl","pos":"adj.","def":"相互的，彼此的；共同的","cefr":"B2","freq_rank":78,
   "sentence_en":"The feeling is mutual.","sentence_zh":"这种感觉是相互的。",
   "aids":{"morphemes":[M("mut","root","改变，交换"),M("ual","suffix","…的")],
     "derivation":"mut(交换)+ual → 相互交换、彼此对等的 → 相互的",
     "family":FAM("mut","改变、交换",[W("mutation","突变"),W("commute","通勤；交换"),W("mutable","易变的")]),
     "mnemonic":"mut=交换(想 commute 通勤=往返交换);你来我往、彼此对等的,就是 mutual 相互的;mutual friend 共同的朋友。",
     "forms":[F("mutually","adv.","相互地")]}},
  {"word":"relevant","phonetic":"ˈrelɪvənt","pos":"adj.","def":"相关的，切题的","cefr":"B2","freq_rank":86,
   "sentence_en":"Please provide relevant information.","sentence_zh":"请提供相关信息。",
   "aids":{"morphemes":[M("re","prefix","再"),M("lev","root","抬起(lift)"),M("ant","suffix","…的")],
     "derivation":"re(再)+lev(抬起) → 能抬起来对应上的 → 相关的",
     "family":FAM("lev","抬起、轻",[W("elevate","抬高"),W("relief","缓解"),W("lever","杠杆")]),
     "mnemonic":"lev=抬(和 elevate 一家);能'抬'出来跟话题对得上的,就是 relevant 相关的;反义 irrelevant 无关的。",
     "forms":[F("relevance","n.","相关性")]}},
  {"word":"ideal","phonetic":"aɪˈdɪəl","pos":"adj./n.","def":"理想的，完美的；理想，典范","cefr":"B1","freq_rank":87,
   "sentence_en":"This is the ideal place for a picnic.","sentence_zh":"这是野餐的理想地点。",
   "aids":{"morphemes":[M("ide","root","看，观念(idea)"),M("al","suffix","…的")],
     "derivation":"idea(观念)+al → 只存在于观念中的完美 → 理想的",
     "family":FAM("ide","看、观念",[W("idea","主意"),W("idol","偶像"),W("ideology","意识形态")]),
     "mnemonic":"ide=观念(和 idea 一家);符合心中完美观念的,就是 ideal 理想的;ideally 理想情况下。",
     "forms":[F("ideally","adv.","理想情况下"),F("ideals","n.","理想(复数)")]}},
  {"word":"considerable","phonetic":"kənˈsɪdərəbl","pos":"adj.","def":"相当大的，可观的","cefr":"B2","freq_rank":100,
   "sentence_en":"It took a considerable amount of time.","sentence_zh":"这花了相当多的时间。",
   "aids":{"morphemes":[M("consider","root","考虑，重视"),M("able","suffix","值得…的")],
     "derivation":"consider(重视)+able → 值得重视、量大到需考虑的 → 相当大的",
     "family":FAM("sider","星、考虑",[W("consider","考虑"),W("consideration","考虑"),W("desire","渴望")]),
     "mnemonic":"consider(重视)+able;数量大到得认真对待的,就是 considerable 相当大的;considerably 相当地。",
     "forms":[F("considerably","adv.","相当地")]}},
  {"word":"intellectual","phonetic":"ˌɪntəˈlektʃuəl","pos":"adj./n.","def":"智力的，脑力的；知识分子","cefr":"B2","freq_rank":102,
   "sentence_en":"Chess is an intellectual game.","sentence_zh":"国际象棋是一种智力游戏。",
   "aids":{"morphemes":[M("intel","prefix","在…之间(inter)"),M("lect","root","选，读"),M("ual","suffix","…的")],
     "derivation":"intel(之间)+lect(辨选) → 在事物间分辨的脑力 → 智力的",
     "family":FAM("lect","选、读",[W("intelligence","智力"),W("select","挑选"),W("elect","选举")]),
     "mnemonic":"lect=辨选(和 intelligence 一家);靠脑力思辨的,就是 intellectual 智力的;搞脑力工作的人=知识分子。",
     "forms":[F("intellect","n.","智力，才智")]}},
  {"word":"advanced","phonetic":"ədˈvɑːnst","pos":"adj.","def":"先进的；高级的；晚期的","cefr":"B1","freq_rank":77,
   "sentence_en":"She took an advanced English course.","sentence_zh":"她上了一门高级英语课。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("vanc","root","前(ante)"),M("ed","suffix","…的")],
     "derivation":"advance(前进)+ed → 走在前面的 → 先进的、高级的",
     "family":FAM("van/vance","前",[W("advance","前进"),W("advantage","优势")]),
     "mnemonic":"advance(前进)的形容词;走在前列、程度更深的,就是 advanced 先进的/高级的;advanced age 高龄。",
     "forms":[F("advance","v.","前进")]}},
  {"word":"attractive","phonetic":"əˈtræktɪv","pos":"adj.","def":"有吸引力的，迷人的","cefr":"B1","freq_rank":84,
   "sentence_en":"It's an attractive offer.","sentence_zh":"这是个诱人的提议。",
   "aids":{"morphemes":[M("at","prefix","朝向(ad 变体)"),M("tract","root","拉，拽"),M("ive","suffix","…的")],
     "derivation":"attract(吸引)+ive → 能把人拉过来的 → 有吸引力的",
     "family":FAM("tract","拉、拽",[W("attract","吸引"),W("extract","提取"),W("contract","合同"),W("distract","分心")]),
     "mnemonic":"tract=拉(和 attract 一家);能把人往这边拉的,就是 attractive 有吸引力的;反义 unattractive。",
     "forms":[F("attract","v.","吸引"),F("attraction","n.","吸引力")]}},
  {"word":"similarly","phonetic":"ˈsɪmɪləli","pos":"adv.","def":"相似地；同样地","cefr":"B1","freq_rank":75,
   "sentence_en":"Similarly, prices rose in other cities.","sentence_zh":"同样地，其他城市物价也上涨了。",
   "aids":{"morphemes":[M("simil","root","相同，类似"),M("arly","suffix","…地")],
     "derivation":"similar(相似的)+ly → 相似地",
     "family":FAM("simil/sembl","相同、类似",[W("similar","相似的"),W("assemble","集合"),W("resemble","像")]),
     "mnemonic":"simil=相似(和 similar 一家);以类似方式、同样地,就是 similarly;写作衔接词(类比)。",
     "forms":[F("similar","adj.","相似的"),F("similarity","n.","相似")]}},
  {"word":"whereas","phonetic":"weərˈæz","pos":"conj.","def":"然而，反之；鉴于","cefr":"B2","freq_rank":64,
   "sentence_en":"He likes tea, whereas she prefers coffee.","sentence_zh":"他喜欢茶，而她更爱咖啡。",
   "aids":{"morphemes":[M("where","root","何处，在…处"),M("as","root","如，像")],
     "derivation":"where(在…处)+as(如) → 就…而言而另一方却… → 然而(对比)",
     "family":FAM("","相关词",[W("whereby","凭此"),W("wherein","在其中")]),
     "mnemonic":"whereas 用于'前者如此、而后者却…'的对比,就是'然而、反之';比 but 更书面,常连接对比分句。",
     "forms":[]}},
  {"word":"constantly","phonetic":"ˈkɒnstəntli","pos":"adv.","def":"不断地，经常地","cefr":"B1","freq_rank":28,
   "sentence_en":"He is constantly complaining.","sentence_zh":"他老是抱怨。",
   "aids":{"morphemes":[M("con","prefix","完全"),M("st","root","站"),M("antly","suffix","…地")],
     "derivation":"constant(恒定的)+ly → 恒定不变地 → 不断地",
     "family":FAM("st/sta","站、立",[W("constant","恒定的"),W("stand","站立"),W("stable","稳定的")]),
     "mnemonic":"constant(恒定)的副词;稳稳地、一刻不停地,就是 constantly 不断地、经常地。",
     "forms":[F("constant","adj.","恒定的")]}},
  # 常见词
  {"word":"extreme","phonetic":"ɪkˈstriːm","pos":"adj./n.","def":"极端的，极度的；极端","cefr":"B1","freq_rank":31,
   "sentence_en":"They faced extreme cold.","sentence_zh":"他们面临极端寒冷。",
   "aids":{"morphemes":[M("extrem","root","最外，最末(exter)"),M("e","suffix","结尾")],
     "derivation":"exter(外)的最高级'最外'→ 到了尽头的 → 极端的",
     "family":FAM("exter/extra","外",[W("external","外部的"),W("extra","额外的"),W("exterior","外部")]),
     "mnemonic":"extrem=最外(exter 的极);到了最尽头、无以复加的,就是 extreme 极端的;extremely 极其。",
     "forms":[F("extremely","adv.","极其"),F("extremes","n.","极端(复数)")]}},
  {"word":"valuable","phonetic":"ˈvæljuəbl","pos":"adj.","def":"有价值的，贵重的","cefr":"B1","freq_rank":48,
   "sentence_en":"This is valuable advice.","sentence_zh":"这是宝贵的建议。",
   "aids":{"morphemes":[M("valu","root","价值"),M("able","suffix","…的")],
     "derivation":"value(价值)+able → 有价值的",
     "family":FAM("val","价值、强",[W("value","价值"),W("evaluate","评估"),W("valid","有效的")]),
     "mnemonic":"valu=价值(和 value 一家);值钱的、宝贵的,就是 valuable;valuables(n.)贵重物品;反义 valueless/worthless。",
     "forms":[F("value","n.","价值"),F("valuables","n.","贵重物品(复数)")]}},
  {"word":"chart","phonetic":"tʃɑːt","pos":"n./v.","def":"图表；排行榜；绘制图表","cefr":"B1","freq_rank":68,
   "sentence_en":"The chart shows monthly sales.","sentence_zh":"这张图表显示月度销售。",
   "aids":{"morphemes":[M("chart","root","纸，图(charta 纸)")],
     "derivation":"拉丁 charta'纸';画在纸上的表 → 图表",
     "family":FAM("chart/card","纸",[W("card","卡片"),W("charter","宪章")]),
     "mnemonic":"chart 与 card/charta(纸)同源;把数据画成表=图表;音乐销量排名=the charts 排行榜;chart 绘制。",
     "forms":[F("charts","n.","图表(复数)"),F("charted","v.","过去式/过去分词")]}},
  {"word":"solar","phonetic":"ˈsəʊlə","pos":"adj.","def":"太阳的，日光的","cefr":"B1","freq_rank":69,
   "sentence_en":"They installed solar panels.","sentence_zh":"他们安装了太阳能板。",
   "aids":{"morphemes":[M("sol","root","太阳(sol)"),M("ar","suffix","…的")],
     "derivation":"sol(太阳)+ar → 太阳的",
     "family":FAM("sol","太阳",[W("solstice","至日"),W("parasol","阳伞")]),
     "mnemonic":"sol=太阳(想 solar system 太阳系);与太阳/日光有关的,就是 solar;solar energy 太阳能;solar system 太阳系。",
     "forms":[]}},
  {"word":"virus","phonetic":"ˈvaɪrəs","pos":"n.","def":"病毒","cefr":"B1","freq_rank":62,
   "sentence_en":"A virus can spread quickly.","sentence_zh":"病毒可以迅速传播。",
   "aids":{"morphemes":[M("virus","root","毒液(拉丁 virus)")],
     "derivation":"拉丁 virus'毒液、黏液';致病的微小病原 → 病毒",
     "family":FAM("","相关词",[W("viral","病毒的；疯传的")]),
     "mnemonic":"virus 本义'毒液';让人生病的微小病原=病毒;电脑'病毒'也是 virus;go viral 疯传(像病毒扩散)。",
     "forms":[F("viruses","n.","病毒(复数)"),F("viral","adj.","病毒的；疯传的")]}},
  {"word":"smooth","phonetic":"smuːð","pos":"adj./v.","def":"光滑的；平稳的，顺畅的；使平滑","cefr":"B1","freq_rank":19,
   "sentence_en":"The road is smooth.","sentence_zh":"这条路很平坦。",
   "aids":{"morphemes":[M("smooth","root","平滑(古英语 smōth)")],
     "derivation":"古英语'平滑';表面无凹凸 → 光滑的;过程无阻碍 → 顺畅的",
     "family":FAM("","相关词",[W("smoothly","顺利地")]),
     "mnemonic":"smooth=平滑;摸着不糙=光滑的;进行无阻=平稳/顺畅的(a smooth ride);smoothly 顺利地。",
     "forms":[F("smoothly","adv.","顺利地")]}},
  {"word":"essay","phonetic":"ˈeseɪ","pos":"n.","def":"文章，论文；随笔","cefr":"B1","freq_rank":33,
   "sentence_en":"Write an essay on the topic.","sentence_zh":"就这个题目写一篇文章。",
   "aids":{"morphemes":[M("essay","root","尝试(exagium 称量)")],
     "derivation":"源自'称量、尝试';对题目的一次探讨尝试 → 文章、随笔",
     "family":FAM("","相关词",[W("assay","化验")]),
     "mnemonic":"essay 原义'尝试'(和 assay 化验同源);围绕一个题目试着阐述的短文,就是 essay 论文/随笔。",
     "forms":[F("essays","n.","文章(复数)")]}},
  {"word":"deputy","phonetic":"ˈdepjuti","pos":"n./adj.","def":"副手，代理人；副的","cefr":"B2","freq_rank":38,
   "sentence_en":"She is the deputy manager.","sentence_zh":"她是副经理。",
   "aids":{"morphemes":[M("de","prefix","离，向下"),M("put","root","想，指派")],
     "derivation":"与 depute'委派'相关;被指派代行职责的人 → 副手、代理",
     "family":FAM("put","想、指派",[W("dispute","争论"),W("reputation","名声"),W("compute","计算")]),
     "mnemonic":"put=指派(想 depute 委派);被委派代理正职的人,就是 deputy 副手/代理人;deputy director 副主任。",
     "forms":[F("deputies","n.","副手(复数)")]}},
  {"word":"brand","phonetic":"brænd","pos":"n./v.","def":"品牌，商标；打烙印；给…定性","cefr":"B1","freq_rank":40,
   "sentence_en":"It's a well-known brand.","sentence_zh":"这是个知名品牌。",
   "aids":{"morphemes":[M("brand","root","烧，烙印(古英语 brand 火)")],
     "derivation":"古英语'燃烧、烙铁';牲畜身上烙的标记 → 商标、品牌",
     "family":FAM("","相关词",[W("brand-new","全新的")]),
     "mnemonic":"brand 本义'烙印';旧时给牲口烙记号,引申为商家的'烙印'=品牌/商标;给人贴标签=brand sb as。",
     "forms":[F("brands","n.","品牌(复数)"),F("branded","v.","过去式/过去分词")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 16
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
