#!/usr/bin/env python
# 第十二批(冲500收官,约100词):逐词精做 aids,追加进 data/vocab-seed.json 至655(+500)。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -pos 放
  {"word":"suppose","phonetic":"səˈpəʊz","pos":"v.","def":"假设，认为；应该","cefr":"A2","freq_rank":34,
   "sentence_en":"I suppose you are right.","sentence_zh":"我想你是对的。",
   "aids":{"morphemes":[M("sup","prefix","在下(sub)"),M("pose","root","放置")],
     "derivation":"sup(在下)+pose(放) → 先放个底、垫个前提 → 假设",
     "family":FAM("pos/pose","放置",[W("propose","提议"),W("impose","强加"),W("expose","暴露"),W("oppose","反对")]),
     "mnemonic":"pose=放;心里先垫(sub-)个前提,就是 suppose 假设;be supposed to=应该/理应。",
     "forms":[F("supposed","adj.","所谓的"),F("supposedly","adv.","据称")]}},
  {"word":"impose","phonetic":"ɪmˈpəʊz","pos":"v.","def":"强加；征(税)","cefr":"B2","freq_rank":98,
   "sentence_en":"They imposed a new tax.","sentence_zh":"他们征收了一项新税。",
   "aids":{"morphemes":[M("im","prefix","在上，向内"),M("pose","root","放置")],
     "derivation":"im(在上)+pose(放) → 硬压放到别人身上 → 强加",
     "family":FAM("pos/pose","放置",[W("propose","提议"),W("suppose","假设"),W("expose","暴露"),W("compose","组成")]),
     "mnemonic":"pose=放;把规矩/税硬压(im-)到别人头上,就是 impose 强加;impose on 打扰/占便宜。",
     "forms":[F("imposition","n.","强加")]}},
  {"word":"opposite","phonetic":"ˈɒpəzɪt","pos":"adj./n.","def":"相反的，对面的；对立面","cefr":"A2","freq_rank":57,
   "sentence_en":"They sat on opposite sides.","sentence_zh":"他们坐在对面。",
   "aids":{"morphemes":[M("op","prefix","对着(ob)"),M("pos","root","放置"),M("ite","suffix","…的")],
     "derivation":"op(对着)+pos(放) → 放在对立面的 → 相反的",
     "family":FAM("pos/pose","放置",[W("oppose","反对"),W("propose","提议"),W("expose","暴露")]),
     "mnemonic":"pos=放;放在正对面(op-)的,就是 opposite 相反的、对面的;the opposite 相反的事物。",
     "forms":[F("oppose","v.","反对")]}},
  # -cept 拿
  {"word":"perceive","phonetic":"pəˈsiːv","pos":"v.","def":"察觉，感知；理解","cefr":"B2","freq_rank":35,
   "sentence_en":"I perceived a change in his mood.","sentence_zh":"我察觉到他情绪有变化。",
   "aids":{"morphemes":[M("per","prefix","完全"),M("ceive","root","拿，取")],
     "derivation":"per(完全)+ceive(拿) → 完全抓取到信息 → 察觉",
     "family":FAM("ceive/cept","拿、取",[W("receive","收到"),W("accept","接受"),W("conceive","构想"),W("deceive","欺骗")]),
     "mnemonic":"ceive=拿(想 receive 收到);把外界信息完全抓入心,就是 perceive 察觉;名词 perception。",
     "forms":[F("perception","n.","感知"),F("perceived","v.","过去式/过去分词")]}},
  # -sist 站
  {"word":"consist","phonetic":"kənˈsɪst","pos":"v.","def":"组成，构成；在于","cefr":"B1","freq_rank":45,
   "sentence_en":"The team consists of five players.","sentence_zh":"这支队伍由五名队员组成。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("sist","root","站")],
     "derivation":"con(一起)+sist(站) → 一起立住构成整体 → 组成",
     "family":FAM("sist","站",[W("insist","坚持"),W("resist","抵抗"),W("assist","协助"),W("exist","存在")]),
     "mnemonic":"sist=站;各部分一起(con-)立住撑成整体,就是 consist;consist of=由…组成;consist in=在于。",
     "forms":[F("consistent","adj.","一致的"),F("consistency","n.","一致性")]}},
  {"word":"consistent","phonetic":"kənˈsɪstənt","pos":"adj.","def":"一致的，始终如一的","cefr":"B2","freq_rank":59,
   "sentence_en":"Her work is consistent.","sentence_zh":"她的工作始终如一。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("sist","root","站"),M("ent","suffix","…的")],
     "derivation":"con(一起)+sist(站) → 前后立场立得一致 → 一致的",
     "family":FAM("sist","站",[W("consist","组成"),W("insist","坚持"),W("resist","抵抗")]),
     "mnemonic":"sist=站;前后立场站得一致、不自相矛盾,就是 consistent;反义 inconsistent 不一致的。",
     "forms":[F("consistency","n.","一致性"),F("consistently","adv.","一贯地")]}},
  {"word":"resistance","phonetic":"rɪˈzɪstəns","pos":"n.","def":"抵抗，反抗；阻力，电阻","cefr":"B2","freq_rank":60,
   "sentence_en":"They met with strong resistance.","sentence_zh":"他们遇到了强烈的抵抗。",
   "aids":{"morphemes":[M("re","prefix","反，back"),M("sist","root","站"),M("ance","suffix","名词后缀")],
     "derivation":"re(反)+sist(站) → 反着站住顶回去 → 抵抗、阻力",
     "family":FAM("sist","站",[W("resist","抵抗"),W("insist","坚持"),W("consist","组成"),W("assist","协助")]),
     "mnemonic":"sist=站;顶着劲反(re-)着站住不退,就是 resistance 抵抗、阻力;动词 resist。",
     "forms":[F("resist","v.","抵抗"),F("resistant","adj.","有抵抗力的")]}},
  # -serv 保持
  {"word":"preserve","phonetic":"prɪˈzɜːv","pos":"v.","def":"保护，保存；维持","cefr":"B2","freq_rank":49,
   "sentence_en":"We must preserve the environment.","sentence_zh":"我们必须保护环境。",
   "aids":{"morphemes":[M("pre","prefix","预先"),M("serve","root","看守，保持")],
     "derivation":"pre(预先)+serve(看守) → 事先守护好 → 保存",
     "family":FAM("serv","看守、保持",[W("conserve","节约"),W("reserve","保留"),W("observe","观察"),W("serve","服务")]),
     "mnemonic":"serve=看守(想 conserve 保存);提前(pre-)守护、使不坏,就是 preserve 保护、保存。",
     "forms":[F("preservation","n.","保护，保存")]}},
  # -trans 跨
  {"word":"transition","phonetic":"trænˈzɪʃən","pos":"n.","def":"过渡，转变","cefr":"B2","freq_rank":51,
   "sentence_en":"The transition to adulthood is gradual.","sentence_zh":"向成年的过渡是渐进的。",
   "aids":{"morphemes":[M("trans","prefix","跨越"),M("it","root","走"),M("ion","suffix","名词后缀")],
     "derivation":"trans(跨越)+it(走) → 从一头走到另一头 → 过渡、转变",
     "family":FAM("it","走、行",[W("transit","运输"),W("exit","出口"),W("initial","最初的")]),
     "mnemonic":"it=走(想 exit);跨(trans-)着从旧状态走到新状态,就是 transition 过渡、转变。",
     "forms":[F("transitional","adj.","过渡的")]}},
  {"word":"transfer","phonetic":"trænsˈfɜː","pos":"v./n.","def":"转移，调动；转让；换乘","cefr":"B1","freq_rank":91,
   "sentence_en":"He transferred to another school.","sentence_zh":"他转到了另一所学校。",
   "aids":{"morphemes":[M("trans","prefix","跨越"),M("fer","root","带")],
     "derivation":"trans(跨越)+fer(带) → 带到另一处 → 转移",
     "family":FAM("fer","带、拿",[W("refer","提及"),W("offer","提供"),W("prefer","更喜欢"),W("differ","不同")]),
     "mnemonic":"fer=带(想 offer 提供);跨(trans-)地方把人/物/钱带过去,就是 transfer 转移、调动、换乘。",
     "forms":[F("transferred","v.","过去式/过去分词")]}},
  {"word":"transportation","phonetic":"ˌtrænspɔːˈteɪʃən","pos":"n.","def":"运输，交通(工具)","cefr":"B1","freq_rank":118,
   "sentence_en":"Public transportation is cheap here.","sentence_zh":"这里的公共交通很便宜。",
   "aids":{"morphemes":[M("trans","prefix","跨越"),M("port","root","搬运"),M("ation","suffix","名词后缀")],
     "derivation":"transport(运输)+ation → 运输(系统) → 交通",
     "family":FAM("port","搬运",[W("transport","运输"),W("export","出口"),W("import","进口"),W("portable","便携的")]),
     "mnemonic":"port=搬运(想 transport);把人/货跨地搬运的整套系统,就是 transportation 交通、运输。",
     "forms":[F("transport","v.","运输")]}},
  # -spir 呼吸
  {"word":"inspire","phonetic":"ɪnˈspaɪə","pos":"v.","def":"激励，鼓舞；启发","cefr":"B2","freq_rank":85,
   "sentence_en":"Her speech inspired us all.","sentence_zh":"她的演讲鼓舞了我们所有人。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("spir","root","呼吸")],
     "derivation":"in(向内)+spir(呼吸) → 把气/灵感吹进心里 → 激励、启发",
     "family":FAM("spir","呼吸",[W("spirit","精神"),W("respire","呼吸"),W("expire","到期"),W("aspire","渴望")]),
     "mnemonic":"spir=呼吸(想 spirit 精神);把灵气/斗志'吹进'(in-)人心,就是 inspire 激励;inspiration 灵感。",
     "forms":[F("inspiration","n.","灵感；鼓舞"),F("inspiring","adj.","鼓舞人心的")]}},
  # -domin 支配
  {"word":"dominate","phonetic":"ˈdɒmɪneɪt","pos":"v.","def":"支配，主导；俯视","cefr":"B2","freq_rank":90,
   "sentence_en":"One team dominated the game.","sentence_zh":"一支球队主导了比赛。",
   "aids":{"morphemes":[M("domin","root","主人，支配"),M("ate","suffix","动词后缀")],
     "derivation":"domin(主人)+ate → 当主人一样掌控 → 支配",
     "family":FAM("domin","主人、支配",[W("dominant","占主导的"),W("domestic","家庭的"),W("dominion","统治权")]),
     "mnemonic":"domin=主人(想 domestic 家里的);像主人般掌控全局,就是 dominate 支配;dominant 占主导的。",
     "forms":[F("dominant","adj.","占主导的"),F("domination","n.","支配")]}},
  # -tact 触
  {"word":"attach","phonetic":"əˈtætʃ","pos":"v.","def":"附上，贴上；使依附","cefr":"B1","freq_rank":92,
   "sentence_en":"Please attach your photo to the form.","sentence_zh":"请把照片贴在表格上。",
   "aids":{"morphemes":[M("at","prefix","朝向(ad 变体)"),M("tach","root","钉，桩(接触)")],
     "derivation":"at(朝向)+tach(钉) → 钉到某物上 → 附上",
     "family":FAM("tach/tact","接触、钉",[W("attack","攻击"),W("contact","接触"),W("detach","拆开")]),
     "mnemonic":"tach=钉(和 attack 一家);把东西朝(at-)某处钉贴上去,就是 attach 附上;反义 detach 拆下;attached 附上的/依恋的。",
     "forms":[F("attachment","n.","附件；依恋"),F("attached","adj.","附上的")]}},
  # -val 价值
  {"word":"evaluate","phonetic":"ɪˈvæljueɪt","pos":"v.","def":"评估，评价","cefr":"B2","freq_rank":99,
   "sentence_en":"We need to evaluate the results.","sentence_zh":"我们需要评估结果。",
   "aids":{"morphemes":[M("e","prefix","出"),M("valu","root","价值"),M("ate","suffix","动词后缀")],
     "derivation":"e(出)+valu(价值) → 估出其价值 → 评价",
     "family":FAM("val","价值、强",[W("value","价值"),W("valid","有效的"),W("valuable","有价值的"),W("evaluation","评估")]),
     "mnemonic":"valu=价值(想 value);把价值/优劣估算出来,就是 evaluate 评估;名词 evaluation。",
     "forms":[F("evaluation","n.","评估")]}},
  # -ple 满
  {"word":"accomplish","phonetic":"əˈkʌmplɪʃ","pos":"v.","def":"完成，实现","cefr":"B2","freq_rank":102,
   "sentence_en":"She accomplished her goal.","sentence_zh":"她实现了目标。",
   "aids":{"morphemes":[M("ac","prefix","朝向(ad 变体)"),M("compl","root","填满(ple)"),M("ish","suffix","动词后缀")],
     "derivation":"ac+compl(填满) → 把事情做满做全 → 完成",
     "family":FAM("ple/plet","满、填",[W("complete","完整的"),W("complement","补充"),W("plenty","充足")]),
     "mnemonic":"compl=填满(和 complete 一家);把任务做满、做圆满,就是 accomplish 完成;accomplishment 成就。",
     "forms":[F("accomplishment","n.","成就")]}},
  # -lustr 光
  {"word":"illustrate","phonetic":"ˈɪləstreɪt","pos":"v.","def":"举例说明，阐明；插图","cefr":"B2","freq_rank":105,
   "sentence_en":"Let me illustrate with an example.","sentence_zh":"让我用一个例子来说明。",
   "aids":{"morphemes":[M("il","prefix","向内，使(in)"),M("lustr","root","光，照亮"),M("ate","suffix","动词后缀")],
     "derivation":"il(使)+lustr(照亮) → 使照亮、说清楚 → 阐明",
     "family":FAM("lustr","光、照亮",[W("luster","光泽"),W("illustration","插图")]),
     "mnemonic":"lustr=照亮(想 luster 光泽);把道理'照亮'讲清、配图说明,就是 illustrate 阐明;illustration 插图。",
     "forms":[F("illustration","n.","插图；说明")]}},
  # -centr 中心
  {"word":"concentrate","phonetic":"ˈkɒnsəntreɪt","pos":"v.","def":"集中，专注；浓缩","cefr":"B1","freq_rank":111,
   "sentence_en":"I can't concentrate with all this noise.","sentence_zh":"这么吵我没法专心。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("centr","root","中心"),M("ate","suffix","动词后缀")],
     "derivation":"con(一起)+centr(中心) → 全聚到中心 → 集中、专注",
     "family":FAM("centr","中心",[W("center","中心"),W("central","中央的"),W("eccentric","古怪的")]),
     "mnemonic":"centr=中心(想 center);把注意力/物质全汇到一个中心点,就是 concentrate 专注、浓缩。",
     "forms":[F("concentration","n.","专注；浓度")]}},
  # -tribute 给
  {"word":"distribution","phonetic":"ˌdɪstrɪˈbjuːʃən","pos":"n.","def":"分配，分发；分布","cefr":"B2","freq_rank":117,
   "sentence_en":"The distribution of wealth is uneven.","sentence_zh":"财富分配不均。",
   "aids":{"morphemes":[M("dis","prefix","分开，散"),M("tribute","root","给予"),M("ion","suffix","名词后缀")],
     "derivation":"dis(散)+tribute(给) → 分散地给出去 → 分配、分布",
     "family":FAM("tribute","给予",[W("distribute","分发"),W("contribute","贡献"),W("attribute","归因于")]),
     "mnemonic":"tribute=给(想 contribute 贡献);把东西分散(dis-)给出去,就是 distribution 分配;动词 distribute。",
     "forms":[F("distribute","v.","分发")]}},
  # -mun 公共/职责
  {"word":"commission","phonetic":"kəˈmɪʃən","pos":"n./v.","def":"委员会；佣金；委托，委任","cefr":"C1","freq_rank":119,
   "sentence_en":"She earns a commission on each sale.","sentence_zh":"她每笔销售都能拿佣金。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("miss","root","送，派"),M("ion","suffix","名词后缀")],
     "derivation":"com(一起)+miss(派) → 把职责派交出去 → 委托、委员会;办成给的酬=佣金",
     "family":FAM("mit/miss","送、派",[W("mission","任务"),W("submit","提交"),W("commit","投入"),W("permit","允许")]),
     "mnemonic":"miss=派(和 mission 一家);受委派办事的一群人=委员会;办成后的抽成=佣金;正式委托=commission。",
     "forms":[F("commissions","n.","委员会(复数)")]}},
  # -pret 说明
  {"word":"interpretation","phonetic":"ɪnˌtɜːprɪˈteɪʃən","pos":"n.","def":"解释，诠释；口译","cefr":"C1","freq_rank":120,
   "sentence_en":"There are different interpretations of the poem.","sentence_zh":"这首诗有不同的解读。",
   "aids":{"morphemes":[M("inter","prefix","在…之间"),M("pret","root","说明，交易"),M("ation","suffix","名词后缀")],
     "derivation":"inter(之间)+pret(说明) → 在双方之间说明沟通 → 解释、口译",
     "family":FAM("pret","说明、交易",[W("interpret","解释；口译"),W("interpreter","口译员")]),
     "mnemonic":"在双方之间(inter-)牵线说明,就是 interpretation 解释/口译;interpreter 口译员;动词 interpret。",
     "forms":[F("interpret","v.","解释；口译")]}},
  # -found 底
  {"word":"foundation","phonetic":"faʊnˈdeɪʃən","pos":"n.","def":"基础，地基；基金会","cefr":"B2","freq_rank":70,
   "sentence_en":"Trust is the foundation of friendship.","sentence_zh":"信任是友谊的基础。",
   "aids":{"morphemes":[M("found","root","底，基"),M("ation","suffix","名词后缀")],
     "derivation":"found(打底、创立)+ation → 打下的底/所立之基 → 基础",
     "family":FAM("found/fund","底、基础",[W("found","创立"),W("fundamental","基础的"),W("fund","基金")]),
     "mnemonic":"found=打底/创立(和 fund 一家);垫在最底下的根基,就是 foundation 基础、地基;设立的机构=基金会。",
     "forms":[F("found","v.","创立")]}},
  {"word":"fundamental","phonetic":"ˌfʌndəˈmentl","pos":"adj.","def":"基本的，根本的","cefr":"B2","freq_rank":94,
   "sentence_en":"There is a fundamental difference between them.","sentence_zh":"它们之间有根本区别。",
   "aids":{"morphemes":[M("fund","root","底，基"),M("ament","suffix","名词"),M("al","suffix","…的")],
     "derivation":"fund(底)+amental → 处于根底的 → 根本的",
     "family":FAM("fund/found","底、基础",[W("fund","基金"),W("foundation","基础"),W("found","创立")]),
     "mnemonic":"fund=底(和 foundation 一家);位于最底层、最要紧的,就是 fundamental 根本的;fundamentally 根本上。",
     "forms":[F("fundamentally","adv.","根本上")]}},
  # -sym 一起
  {"word":"symbol","phonetic":"ˈsɪmbl","pos":"n.","def":"符号，象征","cefr":"B1","freq_rank":100,
   "sentence_en":"The dove is a symbol of peace.","sentence_zh":"鸽子是和平的象征。",
   "aids":{"morphemes":[M("sym","prefix","一起"),M("bol","root","投掷(ball)")],
     "derivation":"sym(一起)+bol(投) → 把抽象意义'投合'到具体标记上 → 象征",
     "family":FAM("bol/ball","投掷",[W("symbolic","象征的"),W("parable","寓言")]),
     "mnemonic":"sym(一起)+bol(投)——把含义和某个标记'合到一起',就是 symbol 符号、象征;symbolize 象征。",
     "forms":[F("symbolic","adj.","象征的"),F("symbolize","v.","象征")]}},
  {"word":"symptom","phonetic":"ˈsɪmptəm","pos":"n.","def":"症状；征兆","cefr":"B2","freq_rank":66,
   "sentence_en":"A fever is a symptom of infection.","sentence_zh":"发烧是感染的症状。",
   "aids":{"morphemes":[M("sym","prefix","一起"),M("ptom","root","落下(pt)")],
     "derivation":"sym(一起)+ptom(落) → 随病一起显露出来的 → 症状",
     "family":FAM("pt/pto","落",[W("ptomaine","尸毒")]),
     "mnemonic":"sym(一起)+ptom(落下、发生)——伴随疾病一起冒出来的表现,就是 symptom 症状、征兆。",
     "forms":[F("symptoms","n.","症状(复数)")]}},
  # -phil 爱
  {"word":"philosophy","phonetic":"fɪˈlɒsəfi","pos":"n.","def":"哲学；人生观，理念","cefr":"B2","freq_rank":68,
   "sentence_en":"He studies philosophy.","sentence_zh":"他学哲学。",
   "aids":{"morphemes":[M("phil","root","爱"),M("soph","root","智慧"),M("y","suffix","名词后缀")],
     "derivation":"phil(爱)+soph(智慧) → 爱智慧 → 哲学",
     "family":FAM("phil","爱",[W("philanthropy","慈善(爱人类)"),W("philosopher","哲学家")]),
     "mnemonic":"phil(爱)+soph(智慧,想 sophisticated 老练);'爱智慧'的学问,就是 philosophy 哲学;引申'处世理念'。",
     "forms":[F("philosopher","n.","哲学家"),F("philosophical","adj.","哲学的")]}},
  # 高频动词
  {"word":"enable","phonetic":"ɪˈneɪbl","pos":"v.","def":"使能够，使成为可能","cefr":"B1","freq_rank":47,
   "sentence_en":"The app enables you to book tickets.","sentence_zh":"这个应用让你能订票。",
   "aids":{"morphemes":[M("en","prefix","使…"),M("able","root","能")],
     "derivation":"en(使)+able(能) → 使有能力/条件 → 使能够",
     "family":FAM("abl/able","能",[W("able","能够的"),W("ability","能力"),W("disable","使失效")]),
     "mnemonic":"en-(使)+able(能)——赋予能力或条件,就是 enable 使能够;反义 disable 使失效。",
     "forms":[F("enabled","v.","过去式/过去分词")]}},
  {"word":"enhance","phonetic":"ɪnˈhɑːns","pos":"v.","def":"提高，增强","cefr":"B2","freq_rank":96,
   "sentence_en":"Music can enhance your mood.","sentence_zh":"音乐能改善你的心情。",
   "aids":{"morphemes":[M("en","prefix","使"),M("hance","root","高(altus)")],
     "derivation":"en(使)+hance(高) → 使更高、抬升 → 提高、增强",
     "family":FAM("","相关词",[W("enhancement","增强")]),
     "mnemonic":"hance≈high(高,源自 altus);使某物往高里提、更好,就是 enhance 提高、增强;比 improve 更强调锦上添花。",
     "forms":[F("enhancement","n.","增强")]}},
  {"word":"implement","phonetic":"ˈɪmplɪment","pos":"v./n.","def":"实施，执行；工具","cefr":"B2","freq_rank":80,
   "sentence_en":"They will implement the new rules.","sentence_zh":"他们将实施新规则。",
   "aids":{"morphemes":[M("im","prefix","向内(in)"),M("ple","root","填满"),M("ment","suffix","名词后缀")],
     "derivation":"im(向内)+ple(填满) → 把计划填实、落到实处 → 实施",
     "family":FAM("ple/plet","满、填",[W("complete","完整的"),W("supplement","补充"),W("plenty","充足")]),
     "mnemonic":"ple=填满(和 complete 一家);把方案填实、付诸落实,就是 implement 实施;做事的'家伙'=工具。",
     "forms":[F("implementation","n.","实施")]}},
  {"word":"adjust","phonetic":"əˈdʒʌst","pos":"v.","def":"调整，调节；适应","cefr":"B1","freq_rank":86,
   "sentence_en":"Adjust the volume as needed.","sentence_zh":"根据需要调节音量。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("just","root","正，对(正确)")],
     "derivation":"ad(朝向)+just(对) → 朝正确/合适方向弄对 → 调整",
     "family":FAM("just","正、对",[W("just","恰好；公正"),W("justice","正义"),W("justify","证明正当")]),
     "mnemonic":"just=对/正;朝(ad-)着'对'的方向拧一拧弄合适,就是 adjust 调整;adjust to=适应。",
     "forms":[F("adjustment","n.","调整")]}},
  {"word":"resolve","phonetic":"rɪˈzɒlv","pos":"v./n.","def":"解决；决心；分解","cefr":"B2","freq_rank":65,
   "sentence_en":"They resolved the conflict peacefully.","sentence_zh":"他们和平地解决了冲突。",
   "aids":{"morphemes":[M("re","prefix","再，彻底"),M("solve","root","松开，解开")],
     "derivation":"re(彻底)+solve(解开) → 彻底解开 → 解决;下定决心也=拿定主意解开困惑",
     "family":FAM("solv/solu","松开、解开",[W("solve","解决"),W("solution","解决办法"),W("dissolve","溶解")]),
     "mnemonic":"solve=解开(和 solution 一家);把纠纷/难题彻底(re-)解开,就是 resolve 解决;下定'解开犹豫'的心=决心。",
     "forms":[F("resolution","n.","决心；解决"),F("resolved","adj.","下定决心的")]}},
  {"word":"advance","phonetic":"ədˈvɑːns","pos":"v./n.","def":"前进，推进；进步；预先(的)","cefr":"B1","freq_rank":84,
   "sentence_en":"Technology advances quickly.","sentence_zh":"技术进步很快。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("vance","root","前(ante)")],
     "derivation":"ad(朝向)+vance(前) → 朝前走 → 前进、进步",
     "family":FAM("van/vance","前",[W("advantage","优势"),W("vanguard","先锋")]),
     "mnemonic":"vance=前(和 advantage 一家);朝前推进、往前一步,就是 advance 前进/进步;in advance 提前。",
     "forms":[F("advanced","adj.","先进的；高级的"),F("advancement","n.","进步")]}},
  {"word":"arrange","phonetic":"əˈreɪndʒ","pos":"v.","def":"安排，筹备；排列","cefr":"A2","freq_rank":54,
   "sentence_en":"I'll arrange a meeting.","sentence_zh":"我来安排一次会议。",
   "aids":{"morphemes":[M("ar","prefix","朝向(ad 变体)"),M("range","root","排，行")],
     "derivation":"ar(朝向)+range(排) → 按次序排好 → 安排",
     "family":FAM("rang/rank","排、行",[W("range","范围"),W("rank","排名")]),
     "mnemonic":"range=排(和 rank 一家);把人/事按次序摆(ar-)好,就是 arrange 安排;名词 arrangement。",
     "forms":[F("arrangement","n.","安排"),F("arranged","v.","过去式/过去分词")]}},
  {"word":"deserve","phonetic":"dɪˈzɜːv","pos":"v.","def":"应得，值得","cefr":"B1","freq_rank":58,
   "sentence_en":"You deserve a break.","sentence_zh":"你该休息一下了。",
   "aids":{"morphemes":[M("de","prefix","加强"),M("serve","root","服务，尽责")],
     "derivation":"de(加强)+serve(尽责) → 尽了力理应得到 → 应得",
     "family":FAM("serv","服务、尽责",[W("serve","服务"),W("service","服务"),W("servant","仆人")]),
     "mnemonic":"serve=尽责;尽了本分、理当得到回报,就是 deserve 应得、值得;well-deserved 当之无愧的。",
     "forms":[F("deserved","adj.","应得的"),F("deserving","adj.","值得的")]}},
  {"word":"urge","phonetic":"ɜːdʒ","pos":"v./n.","def":"催促，力劝；冲动","cefr":"B2","freq_rank":71,
   "sentence_en":"I urge you to reconsider.","sentence_zh":"我力劝你重新考虑。",
   "aids":{"morphemes":[M("urg","root","推，逼(urgere)"),M("e","suffix","结尾")],
     "derivation":"拉丁 urgere'推、逼';推着人去做 → 催促、力劝",
     "family":FAM("urg","推、逼",[W("urgent","紧急的"),W("urgency","紧迫")]),
     "mnemonic":"urg=推逼(想 urgent 紧急的);推着、逼着人赶紧做,就是 urge 催促;内心的'推力'=冲动。",
     "forms":[F("urgent","adj.","紧急的"),F("urged","v.","过去式/过去分词")]}},
  {"word":"quote","phonetic":"kwəʊt","pos":"v./n.","def":"引用，引述；报价","cefr":"B1","freq_rank":69,
   "sentence_en":"She quoted a famous poet.","sentence_zh":"她引用了一位著名诗人的话。",
   "aids":{"morphemes":[M("quot","root","多少，标数(quot)"),M("e","suffix","结尾")],
     "derivation":"拉丁 quotus'第几、多少';原指'标出章节号引述' → 引用;标出价钱 → 报价",
     "family":FAM("quot","多少",[W("quotation","引文；报价"),W("quotient","商")]),
     "mnemonic":"quot=标数(想 quotient 商);标出出处地引述=quote 引用;标出数字=报价;quotation 引文/报价单。",
     "forms":[F("quotation","n.","引文；报价"),F("quoted","v.","过去式/过去分词")]}},
  {"word":"retire","phonetic":"rɪˈtaɪə","pos":"v.","def":"退休，退役；退下","cefr":"B1","freq_rank":87,
   "sentence_en":"He retired at 65.","sentence_zh":"他65岁退休。",
   "aids":{"morphemes":[M("re","prefix","向后"),M("tire","root","拉(tirer)")],
     "derivation":"re(向后)+tire(拉) → 往后抽身退下 → 退休、退役",
     "family":FAM("tir","拉",[W("retirement","退休")]),
     "mnemonic":"tire=拉(法语 tirer);把自己从岗位上往后(re-)一抽、退下来,就是 retire 退休;retirement 退休。",
     "forms":[F("retirement","n.","退休"),F("retired","adj.","退休的")]}},
  # 高频形容词/名词
  {"word":"intense","phonetic":"ɪnˈtens","pos":"adj.","def":"强烈的，剧烈的；紧张的","cefr":"B2","freq_rank":83,
   "sentence_en":"There was intense competition.","sentence_zh":"竞争非常激烈。",
   "aids":{"morphemes":[M("in","prefix","向内，加强"),M("tens","root","拉紧")],
     "derivation":"in(加强)+tens(拉紧) → 绷得极紧 → 强烈的、紧张的",
     "family":FAM("tens/tend","拉紧、伸",[W("tension","紧张"),W("extend","延伸"),W("intend","打算")]),
     "mnemonic":"tens=拉紧(想 tension 张力);绷到极致、又强又紧,就是 intense 强烈的;intensity 强度;intensive 密集的。",
     "forms":[F("intensity","n.","强度"),F("intensive","adj.","密集的")]}},
  {"word":"severe","phonetic":"sɪˈvɪə","pos":"adj.","def":"严重的；严厉的；剧烈的","cefr":"B2","freq_rank":95,
   "sentence_en":"She has a severe headache.","sentence_zh":"她头痛得厉害。",
   "aids":{"morphemes":[M("severe","root","严厉(severus)")],
     "derivation":"拉丁 severus'严厉、认真';程度重、不留情 → 严重的、严厉的",
     "family":FAM("sever","严厉",[W("severity","严重性")]),
     "mnemonic":"severe=严厉;伤病/后果重=严重的;要求/惩罚不留情=严厉的;天气/疼痛猛=剧烈的;severity 严重性。",
     "forms":[F("severely","adv.","严重地"),F("severity","n.","严重性")]}},
  {"word":"practical","phonetic":"ˈpræktɪkl","pos":"adj.","def":"实际的，实用的；务实的","cefr":"B1","freq_rank":78,
   "sentence_en":"That's a practical solution.","sentence_zh":"那是个实用的解决办法。",
   "aids":{"morphemes":[M("pract","root","做，实践"),M("ical","suffix","…的")],
     "derivation":"pract(做)+ical → 能实际去做的 → 实用的",
     "family":FAM("pract","做、实践",[W("practice","练习；实践"),W("practise","练习")]),
     "mnemonic":"pract=做(想 practice 实践);能落到实处、真管用的,就是 practical 实用的;反义 theoretical 理论的。",
     "forms":[F("practically","adv.","几乎；实际上")]}},
  {"word":"numerous","phonetic":"ˈnjuːmərəs","pos":"adj.","def":"众多的，许多的","cefr":"B2","freq_rank":74,
   "sentence_en":"There are numerous examples.","sentence_zh":"例子多得很。",
   "aids":{"morphemes":[M("numer","root","数字，数目"),M("ous","suffix","…的")],
     "derivation":"numer(数目)+ous → 数目大的 → 众多的",
     "family":FAM("numer","数目",[W("number","数字"),W("numeral","数字的"),W("innumerable","无数的")]),
     "mnemonic":"numer=数目(想 number);数目庞大、数不胜数,就是 numerous 众多的。",
     "forms":[]}},
  {"word":"grand","phonetic":"ɡrænd","pos":"adj.","def":"宏伟的，壮丽的；重大的","cefr":"B1","freq_rank":64,
   "sentence_en":"They live in a grand house.","sentence_zh":"他们住在一栋豪宅里。",
   "aids":{"morphemes":[M("grand","root","大(grandis)")],
     "derivation":"拉丁 grandis'大、宏伟';气派大的 → 宏伟的",
     "family":FAM("grand","大",[W("grandeur","壮丽"),W("grandiose","宏大的")]),
     "mnemonic":"grand=大(想 grandmother 祖母'大'一辈);规模气派宏大的,就是 grand 宏伟的;grand total 总计。",
     "forms":[F("grandeur","n.","壮丽，宏伟")]}},
  {"word":"formal","phonetic":"ˈfɔːml","pos":"adj.","def":"正式的；形式的","cefr":"B1","freq_rank":50,
   "sentence_en":"Wear formal clothes to the interview.","sentence_zh":"面试要穿正装。",
   "aids":{"morphemes":[M("form","root","形式"),M("al","suffix","…的")],
     "derivation":"form(形式)+al → 讲究形式规矩的 → 正式的",
     "family":FAM("form","形式、形状",[W("form","形式"),W("format","格式"),W("reform","改革"),W("uniform","制服")]),
     "mnemonic":"form=形式;按规定形式、讲礼数的,就是 formal 正式的;反义 informal 非正式的;formality 手续。",
     "forms":[F("formally","adv.","正式地"),F("informal","adj.","非正式的")]}},
  {"word":"visible","phonetic":"ˈvɪzəbl","pos":"adj.","def":"看得见的，可见的；明显的","cefr":"B1","freq_rank":88,
   "sentence_en":"The stars are visible tonight.","sentence_zh":"今晚能看见星星。",
   "aids":{"morphemes":[M("vis","root","看"),M("ible","suffix","能…的")],
     "derivation":"vis(看)+ible → 能被看见的 → 可见的",
     "family":FAM("vis/vid","看",[W("vision","视力"),W("visual","视觉的"),W("visit","拜访")]),
     "mnemonic":"vis=看(和 vision 一家);肉眼能看到的,就是 visible;反义 invisible 隐形的。",
     "forms":[F("invisible","adj.","看不见的"),F("visibility","n.","能见度")]}},
  {"word":"digital","phonetic":"ˈdɪdʒɪtl","pos":"adj.","def":"数字的，数码的","cefr":"B1","freq_rank":109,
   "sentence_en":"We live in a digital age.","sentence_zh":"我们生活在数字时代。",
   "aids":{"morphemes":[M("digit","root","手指，数字"),M("al","suffix","…的")],
     "derivation":"digit(手指→数字)+al → 用数字表示的 → 数字的",
     "family":FAM("digit","手指、数字",[W("digit","数字"),W("digitize","数字化")]),
     "mnemonic":"digit=手指/数字(古人扳手指计数);以0/1数字方式处理的,就是 digital 数字的;反义 analog 模拟的。",
     "forms":[F("digitally","adv.","数字化地")]}},
  # 高频名词(常见/词根)
  {"word":"atmosphere","phonetic":"ˈætməsfɪə","pos":"n.","def":"大气；气氛，氛围","cefr":"B1","freq_rank":55,
   "sentence_en":"The restaurant has a cozy atmosphere.","sentence_zh":"这家餐厅气氛温馨。",
   "aids":{"morphemes":[M("atmo","root","气，蒸汽"),M("sphere","root","球")],
     "derivation":"atmo(气)+sphere(球) → 包裹地球的气层 → 大气;引申环境'气氛'",
     "family":FAM("sphere","球",[W("hemisphere","半球"),W("spherical","球形的")]),
     "mnemonic":"atmo(气)+sphere(球)——裹在地球外的气层=大气;引申一个场合的'空气'=气氛 atmosphere。",
     "forms":[F("atmospheric","adj.","大气的")]}},
  {"word":"existence","phonetic":"ɪɡˈzɪstəns","pos":"n.","def":"存在，生存","cefr":"B2","freq_rank":52,
   "sentence_en":"They believe in the existence of aliens.","sentence_zh":"他们相信外星人的存在。",
   "aids":{"morphemes":[M("ex","prefix","出"),M("sist","root","站"),M("ence","suffix","名词后缀")],
     "derivation":"exist(站出来存在)+ence → 存在的状态 → 存在",
     "family":FAM("sist","站",[W("exist","存在"),W("insist","坚持"),W("resist","抵抗"),W("consist","组成")]),
     "mnemonic":"exist(存在)的名词;立于世上、活着的状态,就是 existence;come into existence 产生。",
     "forms":[F("exist","v.","存在")]}},
  {"word":"independence","phonetic":"ˌɪndɪˈpendəns","pos":"n.","def":"独立，自主","cefr":"B1","freq_rank":82,
   "sentence_en":"The country gained independence in 1947.","sentence_zh":"这个国家于1947年获得独立。",
   "aids":{"morphemes":[M("in","prefix","不"),M("depend","root","依赖"),M("ence","suffix","名词后缀")],
     "derivation":"in(不)+depend(依赖) → 不依赖的状态 → 独立",
     "family":FAM("pend/pens","悬挂",[W("depend","依赖"),W("independent","独立的"),W("suspend","暂停")]),
     "mnemonic":"independent(独立的)的名词;不依赖他人自主自立,就是 independence;Independence Day 独立日。",
     "forms":[F("independent","adj.","独立的")]}},
  {"word":"discipline","phonetic":"ˈdɪsɪplɪn","pos":"n./v.","def":"纪律，自律；学科；训练，惩戒","cefr":"B2","freq_rank":76,
   "sentence_en":"Learning requires discipline.","sentence_zh":"学习需要自律。",
   "aids":{"morphemes":[M("disc","root","学习(disciple 门徒)"),M("ipline","suffix","名词后缀")],
     "derivation":"与 disciple(门徒)同源'学习';训导学习所需的规矩 → 纪律;所学门类 → 学科",
     "family":FAM("disc","学习",[W("disciple","门徒"),W("disciplinary","纪律的")]),
     "mnemonic":"与 disciple(门徒、学生)同源;学习/训导要守的规矩=纪律、自律;一门学问=学科;施以管教=训练、惩戒。",
     "forms":[F("disciplined","adj.","守纪律的")]}},
  {"word":"substance","phonetic":"ˈsʌbstəns","pos":"n.","def":"物质；实质，主旨","cefr":"B2","freq_rank":75,
   "sentence_en":"Water is a common substance.","sentence_zh":"水是一种常见物质。",
   "aids":{"morphemes":[M("sub","prefix","在下"),M("st","root","站"),M("ance","suffix","名词后缀")],
     "derivation":"sub(在下)+st(站) → 立于底下支撑的东西 → 物质、实质",
     "family":FAM("st/sta","站、立",[W("stand","站立"),W("stable","稳定的"),W("status","状态"),W("substitute","替代")]),
     "mnemonic":"sub(在下)+st(站)——垫在底下、构成事物的真材实料,就是 substance 物质;引申'实质、主旨'。",
     "forms":[F("substantial","adj.","大量的；实质的")]}},
  {"word":"territory","phonetic":"ˈterɪtəri","pos":"n.","def":"领土，领地；(活动)范围","cefr":"B2","freq_rank":41,
   "sentence_en":"The lion defends its territory.","sentence_zh":"狮子保卫自己的领地。",
   "aids":{"morphemes":[M("terr","root","土地"),M("itory","suffix","名词后缀")],
     "derivation":"terr(土地)+itory → 一片属己的土地 → 领土",
     "family":FAM("terr","土地",[W("territory","领土"),W("terrain","地形"),W("terrace","露台"),W("Mediterranean","地中海")]),
     "mnemonic":"terr=土地(想 terrain 地形);归属某方管辖的一片地,就是 territory 领土;引申'势力/活动范围'。",
     "forms":[F("territories","n.","领土(复数)")]}},
  {"word":"portion","phonetic":"ˈpɔːʃən","pos":"n.","def":"部分，一份","cefr":"B1","freq_rank":40,
   "sentence_en":"A large portion of the budget goes to salaries.","sentence_zh":"很大一部分预算用于工资。",
   "aids":{"morphemes":[M("port","root","部分，分(pars)"),M("ion","suffix","名词后缀")],
     "derivation":"port(分)+ion → 分出来的一块 → 部分、一份",
     "family":FAM("part/port","部分",[W("part","部分"),W("partial","部分的"),W("proportion","比例")]),
     "mnemonic":"port≈part(部分);从整体分出的一块或一人份,就是 portion;proportion 比例。",
     "forms":[F("portions","n.","部分(复数)")]}},
  {"word":"layer","phonetic":"ˈleɪə","pos":"n./v.","def":"层，层次；分层","cefr":"B1","freq_rank":37,
   "sentence_en":"There is a thick layer of dust.","sentence_zh":"有厚厚的一层灰。",
   "aids":{"morphemes":[M("lay","root","放，铺"),M("er","suffix","名词后缀")],
     "derivation":"lay(铺)+er → 铺开的一片 → 层",
     "family":FAM("lay","放、铺",[W("lay","放置"),W("layout","布局")]),
     "mnemonic":"lay=铺放(想 lay down 放下);一片片铺叠起来的每一层,就是 layer;layered 分层的。",
     "forms":[F("layers","n.","层(复数)"),F("layered","adj.","分层的")]}},
  {"word":"occasion","phonetic":"əˈkeɪʒən","pos":"n.","def":"场合，时刻；时机","cefr":"B1","freq_rank":72,
   "sentence_en":"Wear it on special occasions.","sentence_zh":"在特殊场合才穿它。",
   "aids":{"morphemes":[M("oc","prefix","朝向(ob)"),M("cas","root","落，降"),M("ion","suffix","名词后缀")],
     "derivation":"oc(朝向)+cas(落) → 事情正好落下发生的当口 → 场合、时机",
     "family":FAM("cas/cid","落、降",[W("accident","事故"),W("incident","事件"),W("case","情况")]),
     "mnemonic":"cas=落(和 accident 一家);事情恰好'落'下发生的那个时刻,就是 occasion 场合;on occasion 偶尔。",
     "forms":[F("occasional","adj.","偶尔的"),F("occasionally","adv.","偶尔")]}},
  {"word":"emphasis","phonetic":"ˈemfəsɪs","pos":"n.","def":"强调，重点","cefr":"B2","freq_rank":103,
   "sentence_en":"He put emphasis on teamwork.","sentence_zh":"他强调团队合作。",
   "aids":{"morphemes":[M("em","prefix","使处于(en)"),M("phas","root","显示，说"),M("is","suffix","名词后缀")],
     "derivation":"em(使)+phas(显示) → 使凸显 → 强调、重点",
     "family":FAM("phas/phan","显示",[W("emphasize","强调"),W("phase","阶段"),W("phenomenon","现象")]),
     "mnemonic":"phas=显示(和 emphasize 一家);被特别凸显的那个点,就是 emphasis 重点;place emphasis on 强调。",
     "forms":[F("emphasize","v.","强调")]}},
  {"word":"monitor","phonetic":"ˈmɒnɪtə","pos":"v./n.","def":"监控，监测；显示器；班长","cefr":"B1","freq_rank":106,
   "sentence_en":"Doctors monitor the patient closely.","sentence_zh":"医生密切监测病人。",
   "aids":{"morphemes":[M("mon","root","警告，提醒"),M("itor","suffix","…的人/物")],
     "derivation":"mon(警告、提醒)+itor → 提醒示警的人/装置 → 监控者、监视器",
     "family":FAM("mon","警告、提醒",[W("monument","纪念碑"),W("summon","召唤"),W("premonition","预感")]),
     "mnemonic":"mon=提醒/警告(想 monument 提醒后人的碑);盯着并示警,就是 monitor 监控;显示画面的屏=显示器。",
     "forms":[F("monitored","v.","过去式/过去分词"),F("monitoring","n.","监测")]}},
  {"word":"entertainment","phonetic":"ˌentəˈteɪnmənt","pos":"n.","def":"娱乐，消遣；款待","cefr":"B1","freq_rank":107,
   "sentence_en":"The park offers lots of entertainment.","sentence_zh":"这个公园提供很多娱乐活动。",
   "aids":{"morphemes":[M("enter","prefix","在…之间(inter)"),M("tain","root","拿，持"),M("ment","suffix","名词后缀")],
     "derivation":"enter(之间)+tain(持) → 把人留住、让宾客尽兴 → 娱乐、款待",
     "family":FAM("tain/ten","拿、持",[W("entertain","娱乐；款待"),W("contain","包含"),W("maintain","维持")]),
     "mnemonic":"tain=持(和 contain 一家);把宾客/观众的兴致'持'住、招待好,就是 entertainment 娱乐;动词 entertain。",
     "forms":[F("entertain","v.","娱乐；款待")]}},
  {"word":"arrangement","phonetic":"əˈreɪndʒmənt","pos":"n.","def":"安排，布置；约定","cefr":"B1","freq_rank":110,
   "sentence_en":"We made arrangements for the trip.","sentence_zh":"我们为旅行做了安排。",
   "aids":{"morphemes":[M("ar","prefix","朝向(ad 变体)"),M("range","root","排"),M("ment","suffix","名词后缀")],
     "derivation":"arrange(安排)+ment → 安排的结果 → 安排、布置",
     "family":FAM("rang/rank","排、行",[W("arrange","安排"),W("range","范围"),W("rank","排名")]),
     "mnemonic":"arrange(排好、安排)的名词;把事情/物品排布妥当的结果,就是 arrangement 安排、约定。",
     "forms":[F("arrange","v.","安排")]}},
  {"word":"evaluation","phonetic":"ɪˌvæljuˈeɪʃən","pos":"n.","def":"评估，评价","cefr":"B2","freq_rank":108,
   "sentence_en":"The teacher gave a fair evaluation.","sentence_zh":"老师给出了公正的评价。",
   "aids":{"morphemes":[M("e","prefix","出"),M("valu","root","价值"),M("ation","suffix","名词后缀")],
     "derivation":"evaluate(评估)+ion → 估出价值的过程 → 评估",
     "family":FAM("val","价值",[W("evaluate","评估"),W("value","价值"),W("valid","有效的")]),
     "mnemonic":"valu=价值(和 evaluate 一家);对价值/优劣做出的判断,就是 evaluation 评估。",
     "forms":[F("evaluate","v.","评估")]}},
  # 常见名词
  {"word":"gene","phonetic":"dʒiːn","pos":"n.","def":"基因","cefr":"B2","freq_rank":81,
   "sentence_en":"Eye color is determined by genes.","sentence_zh":"眼睛颜色由基因决定。",
   "aids":{"morphemes":[M("gene","root","产生，种(gen)")],
     "derivation":"gen(产生)→ 决定遗传、产生性状的单位 → 基因",
     "family":FAM("gen","产生、种类",[W("generate","产生"),W("genetic","基因的"),W("gender","性别"),W("genius","天才")]),
     "mnemonic":"gen=产生(和 generate 一家);决定遗传、'产生'性状的单位,就是 gene 基因;genetic 基因的。",
     "forms":[F("genes","n.","基因(复数)"),F("genetic","adj.","基因的")]}},
  {"word":"comparison","phonetic":"kəmˈpærɪsn","pos":"n.","def":"比较，对照","cefr":"B1","freq_rank":36,
   "sentence_en":"There's no comparison between them.","sentence_zh":"它们没有可比性。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("par","root","相等，配对"),M("ison","suffix","名词后缀")],
     "derivation":"compare(比较)+ison → 并到一起比 → 比较",
     "family":FAM("par","相等、配对",[W("compare","比较"),W("pair","一对"),W("parity","同等")]),
     "mnemonic":"par=配对(和 compare 一家);把两者并排对比,就是 comparison;in comparison with 与…相比。",
     "forms":[F("compare","v.","比较")]}},
  {"word":"participation","phonetic":"pɑːˌtɪsɪˈpeɪʃən","pos":"n.","def":"参与，参加","cefr":"B2","freq_rank":53,
   "sentence_en":"Audience participation is welcome.","sentence_zh":"欢迎观众参与。",
   "aids":{"morphemes":[M("part","root","部分"),M("cip","root","拿"),M("ation","suffix","名词后缀")],
     "derivation":"participate(参与)+ion → 参与的行为 → 参与",
     "family":FAM("part","部分",[W("participate","参加"),W("participant","参与者"),W("particle","粒子")]),
     "mnemonic":"part(部分)+cip(拿)——在活动里掺一份的行为,就是 participation;participant 参与者。",
     "forms":[F("participate","v.","参加")]}},
  {"word":"discovery","phonetic":"dɪˈskʌvəri","pos":"n.","def":"发现","cefr":"A2","freq_rank":61,
   "sentence_en":"It was an important scientific discovery.","sentence_zh":"这是一项重要的科学发现。",
   "aids":{"morphemes":[M("dis","prefix","去除"),M("cover","root","盖"),M("y","suffix","名词后缀")],
     "derivation":"discover(揭开盖子)+y → 发现的行为/所得 → 发现",
     "family":FAM("cover","盖",[W("discover","发现"),W("cover","覆盖"),W("recover","恢复")]),
     "mnemonic":"discover(揭盖发现)的名词;揭开未知看到的新东西,就是 discovery。",
     "forms":[F("discoveries","n.","发现(复数)")]}},
  {"word":"exposure","phonetic":"ɪkˈspəʊʒə","pos":"n.","def":"暴露，接触；曝光；揭露","cefr":"B2","freq_rank":62,
   "sentence_en":"Too much sun exposure is harmful.","sentence_zh":"过度日晒有害。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("pos","root","放"),M("ure","suffix","名词后缀")],
     "derivation":"expose(放到外面)+ure → 暴露的状态 → 暴露、接触",
     "family":FAM("pos/pose","放置",[W("expose","暴露"),W("pose","摆姿势"),W("impose","强加")]),
     "mnemonic":"expose(暴露)的名词;暴露在外、接触到某物的状态,就是 exposure;曝光/揭露也是 exposure。",
     "forms":[F("expose","v.","暴露")]}},
  {"word":"stream","phonetic":"striːm","pos":"n./v.","def":"小溪，水流；一连串；流播","cefr":"B1","freq_rank":63,
   "sentence_en":"A stream runs through the valley.","sentence_zh":"一条小溪流过山谷。",
   "aids":{"morphemes":[M("stream","root","流(古英语 stream)")],
     "derivation":"古英语'流水';流动的水 → 小溪;引申一连串、在线'流'播",
     "family":FAM("","相关词",[W("streaming","流媒体"),W("mainstream","主流")]),
     "mnemonic":"stream=流;流动的小河=小溪;源源不断的一串=a stream of;在线'流'着放=streaming 流媒体。",
     "forms":[F("streams","n.","溪流(复数)"),F("streaming","n.","流媒体")]}},
  {"word":"manufacturer","phonetic":"ˌmænjuˈfæktʃərə","pos":"n.","def":"制造商，厂商","cefr":"B2","freq_rank":67,
   "sentence_en":"The car manufacturer recalled the vehicles.","sentence_zh":"这家汽车制造商召回了车辆。",
   "aids":{"morphemes":[M("manu","root","手"),M("fact","root","做"),M("urer","suffix","…的人")],
     "derivation":"manu(手)+fact(做) → 动手制造的一方 → 制造商",
     "family":FAM("man/fact","手/做",[W("manufacture","制造"),W("manual","手动的"),W("factory","工厂")]),
     "mnemonic":"manu(手)+fact(做)——批量做东西的厂家,就是 manufacturer 制造商;动词 manufacture 制造。",
     "forms":[F("manufacture","v.","制造")]}},
  {"word":"joint","phonetic":"dʒɔɪnt","pos":"adj./n.","def":"共同的，联合的；关节，接头","cefr":"B1","freq_rank":56,
   "sentence_en":"It was a joint effort.","sentence_zh":"这是一次共同的努力。",
   "aids":{"morphemes":[M("join","root","连接"),M("t","suffix","名词后缀")],
     "derivation":"与 join(连接)同源;连在一起的 → 共同的;连接处 → 关节",
     "family":FAM("join/junct","连接",[W("join","连接"),W("junction","交汇处"),W("conjunction","连词")]),
     "mnemonic":"join=连接;两方连在一起干=joint 共同的;骨头相连处=关节;管子接头也是 joint。",
     "forms":[F("jointly","adv.","共同地"),F("joints","n.","关节(复数)")]}},
  {"word":"abandon","phonetic":"əˈbændən","pos":"v.","def":"放弃，抛弃；遗弃","cefr":"B2","freq_rank":43,
   "sentence_en":"They had to abandon the plan.","sentence_zh":"他们不得不放弃这个计划。",
   "aids":{"morphemes":[M("a","prefix","去，处于"),M("bandon","root","控制，命令(ban)")],
     "derivation":"古法语 abandoner'交出、放任';不再掌控、任其而去 → 放弃、遗弃",
     "family":FAM("ban","命令、禁止",[W("ban","禁止")]),
     "mnemonic":"abandon 由 a-+bandon(掌控);不再掌控、撒手不管,就是 abandon 放弃、抛弃(不规则,无明显词根,靠场景记)。",
     "forms":[F("abandoned","adj.","被遗弃的")]}},
  {"word":"consist","phonetic":"kənˈsɪst","pos":"v.","def":"由…组成；在于","cefr":"B1","freq_rank":45,
   "sentence_en":"Water consists of hydrogen and oxygen.","sentence_zh":"水由氢和氧组成。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("sist","root","站")],
     "derivation":"con(一起)+sist(站) → 一起立住组成 → 组成","family":FAM("sist","站",[W("insist","坚持"),W("resist","抵抗"),W("exist","存在")]),
     "mnemonic":"sist=站;各部分一起(con-)立住成整体,就是 consist;consist of=由…组成。","forms":[F("consistent","adj.","一致的")]}},
  {"word":"desert","phonetic":"ˈdezət","pos":"n./v.","def":"沙漠；(dɪˈzɜːt)抛弃，遗弃","cefr":"B1","freq_rank":48,
   "sentence_en":"The Sahara is a huge desert.","sentence_zh":"撒哈拉是一片巨大的沙漠。",
   "aids":{"morphemes":[M("de","prefix","离，去除"),M("sert","root","连接，加入(ser)")],
     "derivation":"de(离)+sert(连接) → 断开联系、被遗弃 → 荒漠;动词'抛弃'",
     "family":FAM("sert","连接、加入",[W("insert","插入"),W("series","系列")]),
     "mnemonic":"sert=连接(想 insert 插入);被断(de-)了联系、无人问津之地=沙漠(名词/deza/);抛下不管=desert(/dɪˈzɜːt/);别和 dessert 甜点(双s)混。",
     "forms":[F("deserted","adj.","荒废的；被遗弃的")]}},
  {"word":"formal","phonetic":"ˈfɔːml","pos":"adj.","def":"正式的","cefr":"B1","freq_rank":50,
   "sentence_en":"This is a formal letter.","sentence_zh":"这是一封正式信函。",
   "aids":{"morphemes":[M("form","root","形式"),M("al","suffix","…的")],
     "derivation":"form(形式)+al → 讲形式规矩的 → 正式的","family":FAM("form","形式",[W("form","形式"),W("format","格式"),W("uniform","制服")]),
     "mnemonic":"form=形式;按规矩、讲礼数的,就是 formal;反义 informal。","forms":[F("informal","adj.","非正式的")]}},
  {"word":"bother","phonetic":"ˈbɒðə","pos":"v./n.","def":"打扰，烦扰；费心","cefr":"B1","freq_rank":44,
   "sentence_en":"Sorry to bother you.","sentence_zh":"抱歉打扰你。",
   "aids":{"morphemes":[M("bother","root","烦扰(爱尔兰语 bodhaire 聒噪)")],
     "derivation":"可能源自爱尔兰语'耳聋、聒噪';使人心烦 → 打扰",
     "family":FAM("","相关词",[W("bothersome","恼人的")]),
     "mnemonic":"bother=烦扰;打断、麻烦别人=打扰;费神去做=can't be bothered 懒得做;don't bother 不必麻烦。",
     "forms":[F("bothered","adj.","烦恼的")]}},
  {"word":"symptom","phonetic":"ˈsɪmptəm","pos":"n.","def":"症状；征兆","cefr":"B2","freq_rank":66,
   "sentence_en":"Coughing is a common symptom.","sentence_zh":"咳嗽是常见症状。",
   "aids":{"morphemes":[M("sym","prefix","一起"),M("ptom","root","落下")],
     "derivation":"sym(一起)+ptom(落) → 随病一起显现 → 症状","family":FAM("","相关词",[W("symptomatic","有症状的")]),
     "mnemonic":"sym(一起)+ptom(发生)——伴随疾病一起冒出的表现,就是 symptom 症状、征兆。","forms":[F("symptoms","n.","症状(复数)")]}},
  {"word":"vary","phonetic":"ˈveəri","pos":"v.","def":"变化，不同；使多样","cefr":"B1","freq_rank":116,
   "sentence_en":"Prices vary from shop to shop.","sentence_zh":"各家店价格不一。",
   "aids":{"morphemes":[M("var","root","变化"),M("y","suffix","动词后缀")],
     "derivation":"var(变化)+y → 发生变化 → 变化、不同",
     "family":FAM("vari","变化",[W("various","各种的"),W("variety","多样"),W("variable","可变的")]),
     "mnemonic":"var=变(和 various 一家);因情况而不同、有变化,就是 vary;vary from A to B=从A到B不等。",
     "forms":[F("varying","adj.","不同的"),F("varied","adj.","多样的")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 12
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
