#!/usr/bin/env python
# 第二十一批(约52词,跨1000):逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -fort 强
  {"word":"reinforce","phonetic":"ˌriːɪnˈfɔːs","pos":"v.","def":"加强，强化；增援","cefr":"B2","freq_rank":57,
   "sentence_en":"The walls were reinforced with steel.","sentence_zh":"墙用钢筋加固了。",
   "aids":{"morphemes":[M("re","prefix","再"),M("in","prefix","使"),M("force","root","力量")],
     "derivation":"re(再)+force(力量) → 再加力 → 加强",
     "family":FAM("fort/forc","力量、强",[W("force","力量"),W("effort","努力"),W("comfort","安慰"),W("enforce","执行")]),
     "mnemonic":"force=力量(和 enforce 一家);再(re-)给它加把劲/添兵,就是 reinforce 加强、增援;reinforcement 增援。",
     "forms":[F("reinforcement","n.","加强；增援")]}},
  # -tribute 给
  {"word":"attribute","phonetic":"əˈtrɪbjuːt","pos":"v./n.","def":"把…归因于；属性，特质","cefr":"B2","freq_rank":65,
   "sentence_en":"She attributes her success to hard work.","sentence_zh":"她把成功归因于努力。",
   "aids":{"morphemes":[M("at","prefix","朝向(ad 变体)"),M("tribute","root","给予")],
     "derivation":"at(朝向)+tribute(给) → 把功劳/原因归给某方 → 归因于",
     "family":FAM("tribute","给予",[W("contribute","贡献"),W("distribute","分发"),W("tribute","贡品")]),
     "mnemonic":"tribute=给(和 contribute 一家);把原因/功劳归(at-)到某处,就是 attribute...to 归因于;事物固有的'特质'也是 attribute。",
     "forms":[F("attribution","n.","归因")]}},
  # -pos 放
  {"word":"compose","phonetic":"kəmˈpəʊz","pos":"v.","def":"组成，构成；创作，作曲；使镇定","cefr":"B2","freq_rank":76,
   "sentence_en":"Water is composed of hydrogen and oxygen.","sentence_zh":"水由氢和氧组成。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("pose","root","放置")],
     "derivation":"com(一起)+pose(放) → 放到一起构成 → 组成;把音符组到一起 → 作曲",
     "family":FAM("pos/pose","放置",[W("propose","提议"),W("expose","暴露"),W("impose","强加"),W("position","位置")]),
     "mnemonic":"pose=放(和 propose 一家);把部分放到一起=组成(be composed of);把音符/文字组织好=创作/作曲;心'放'定=使镇定(composed 镇定的)。",
     "forms":[F("composer","n.","作曲家"),F("composed","adj.","镇定的")]}},
  # -reg 统治/规
  {"word":"regulate","phonetic":"ˈreɡjuleɪt","pos":"v.","def":"管理，控制；调节，调整","cefr":"B2","freq_rank":78,
   "sentence_en":"The government regulates the industry.","sentence_zh":"政府对该行业进行监管。",
   "aids":{"morphemes":[M("reg","root","规，直，统治"),M("ulate","suffix","动词后缀")],
     "derivation":"reg(规、直)+ulate → 按规矩使合规、使顺 → 管理、调节",
     "family":FAM("reg","规、统治",[W("regular","规则的"),W("region","地区"),W("regime","政权")]),
     "mnemonic":"reg=规(和 regular 规则一家);按规矩管控、把参数调顺,就是 regulate;regulation 规章;regulator 监管者。",
     "forms":[F("regulation","n.","规章；调节"),F("regulator","n.","监管者")]}},
  # -rupt 破
  {"word":"interrupt","phonetic":"ˌɪntəˈrʌpt","pos":"v.","def":"打断，打扰；中断","cefr":"B1","freq_rank":87,
   "sentence_en":"Sorry to interrupt, but I have a question.","sentence_zh":"抱歉打断一下，我有个问题。",
   "aids":{"morphemes":[M("inter","prefix","在…之间"),M("rupt","root","破，断")],
     "derivation":"inter(之间)+rupt(断) → 从中间打断 → 打断",
     "family":FAM("rupt","破、断",[W("erupt","喷发"),W("corrupt","腐败的"),W("bankrupt","破产的"),W("disrupt","扰乱")]),
     "mnemonic":"rupt=断(和 erupt 喷发一家);从中间(inter-)插进来把话/事截断,就是 interrupt 打断;interruption 打断。",
     "forms":[F("interruption","n.","打断")]}},
  # -super 上
  {"word":"superior","phonetic":"suːˈpɪəriə","pos":"adj./n.","def":"(更)优越的，上级的；上级","cefr":"B2","freq_rank":88,
   "sentence_en":"This product is superior to the others.","sentence_zh":"这款产品优于其他产品。",
   "aids":{"morphemes":[M("super","root","在上"),M("ior","suffix","较…的")],
     "derivation":"super(在上)+ior(较) → 更高一等的 → 优越的、上级的",
     "family":FAM("super","在上、超过",[W("superb","极好的"),W("supervise","监督"),W("supreme","至高的")]),
     "mnemonic":"super=在上(想 superman 超人);高人一等、更强的,就是 superior;superior to 优于;反义 inferior 低劣的/下级的。",
     "forms":[F("superiority","n.","优越")]}},
  # -bat 打
  {"word":"combat","phonetic":"ˈkɒmbæt","pos":"n./v.","def":"战斗，搏斗；与…作斗争","cefr":"B2","freq_rank":90,
   "sentence_en":"Measures to combat crime.","sentence_zh":"打击犯罪的措施。",
   "aids":{"morphemes":[M("com","prefix","一起，相互"),M("bat","root","打，击")],
     "derivation":"com(相互)+bat(打) → 互相打 → 战斗、作斗争",
     "family":FAM("bat","打、击",[W("battle","战斗"),W("debate","辩论"),W("beat","打")]),
     "mnemonic":"bat=打(和 battle 一家);双方互相(com-)打斗;引申'与…作斗争'(combat poverty 消除贫困)。",
     "forms":[F("combatant","n.","战斗人员")]}},
  # -integr 完整
  {"word":"integrate","phonetic":"ˈɪntɪɡreɪt","pos":"v.","def":"(使)融合，(使)成为一体","cefr":"B2","freq_rank":100,
   "sentence_en":"Immigrants often struggle to integrate.","sentence_zh":"移民往往难以融入。",
   "aids":{"morphemes":[M("integr","root","完整，未触(in+tang)"),M("ate","suffix","动词后缀")],
     "derivation":"integr(完整)+ate → 使各部分合成完整一体 → 融合",
     "family":FAM("integr/tang","完整、触",[W("integrity","正直；完整"),W("entire","整个的"),W("intact","完整的")]),
     "mnemonic":"integr=完整(和 entire/integrity 一家);把分散的合成一个完整体,就是 integrate 融合;integration 一体化。",
     "forms":[F("integration","n.","融合；一体化")]}},
  # -pon 放
  {"word":"compound","phonetic":"ˈkɒmpaʊnd","pos":"n./adj./v.","def":"化合物，复合物；复合的；使加剧","cefr":"B2","freq_rank":98,
   "sentence_en":"Water is a chemical compound.","sentence_zh":"水是一种化合物。",
   "aids":{"morphemes":[M("com","prefix","一起"),M("pound","root","放置(pon)")],
     "derivation":"com(一起)+pound(放) → 放到一起合成 → 化合物、复合的",
     "family":FAM("pon/pos","放置",[W("component","部件"),W("compose","组成"),W("opponent","对手")]),
     "mnemonic":"pound=放(pon 家族);把不同成分放到一起合成的,就是 compound 化合物/复合词;把问题'叠加'放大=使加剧。",
     "forms":[F("compounds","n.","化合物(复数)")]}},
  # -fac 做
  {"word":"defeat","phonetic":"dɪˈfiːt","pos":"v./n.","def":"击败，战胜；使落空；失败","cefr":"B1","freq_rank":55,
   "sentence_en":"They defeated the champions.","sentence_zh":"他们击败了卫冕冠军。",
   "aids":{"morphemes":[M("de","prefix","去除，反"),M("feat","root","做(fact)")],
     "derivation":"de(反)+feat(做) → 使对方做不成 → 击败",
     "family":FAM("fac/feat","做、造",[W("fact","事实"),W("feature","特征"),W("affect","影响")]),
     "mnemonic":"feat=做(fact 家族);让对手'做'不成、搞垮他,就是 defeat 击败;admit defeat 认输;a crushing defeat 惨败。",
     "forms":[F("defeated","v.","过去式/过去分词")]}},
  # -cap 拿
  {"word":"occupation","phonetic":"ˌɒkjuˈpeɪʃən","pos":"n.","def":"职业；占领，占用","cefr":"B1","freq_rank":61,
   "sentence_en":"Please state your occupation.","sentence_zh":"请注明你的职业。",
   "aids":{"morphemes":[M("oc","prefix","朝向(ob)"),M("cup","root","拿(cap)"),M("ation","suffix","名词后缀")],
     "derivation":"occupy(占住)+ation → 占用时间的活/占据 → 职业、占领",
     "family":FAM("cap/cup","拿、抓",[W("occupy","占据"),W("capture","捕获"),W("capable","有能力的")]),
     "mnemonic":"cup=拿(和 occupy 一家);占用你日常时间的事=职业;军事上占据地盘=占领,都是 occupation。",
     "forms":[F("occupy","v.","占据"),F("occupational","adj.","职业的")]}},
  # -fus 倒
  {"word":"confusion","phonetic":"kənˈfjuːʒən","pos":"n.","def":"混乱；困惑，混淆","cefr":"B1","freq_rank":62,
   "sentence_en":"There was confusion about the schedule.","sentence_zh":"对于日程有些混乱。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("fus","root","倒，流"),M("ion","suffix","名词后缀")],
     "derivation":"con(一起)+fus(倒) → 全倒到一起搅混 → 混乱、混淆",
     "family":FAM("fus/found","倒、流",[W("confuse","使困惑"),W("refuse","拒绝"),W("confound","混淆")]),
     "mnemonic":"fus=倒(把东西全倒一起搅);头脑/秩序被搅乱,就是 confusion 混乱、困惑;动词 confuse;confusing 令人困惑的。",
     "forms":[F("confuse","v.","使困惑"),F("confusing","adj.","令人困惑的")]}},
  # -dic 说
  {"word":"indication","phonetic":"ˌɪndɪˈkeɪʃən","pos":"n.","def":"迹象，指示；表明","cefr":"B2","freq_rank":74,
   "sentence_en":"There was no indication of danger.","sentence_zh":"没有危险的迹象。",
   "aids":{"morphemes":[M("in","prefix","向"),M("dic","root","说，指"),M("ation","suffix","名词后缀")],
     "derivation":"indicate(指出)+ion → 指示出来的信号 → 迹象",
     "family":FAM("dic/dict","说、指",[W("indicate","表明"),W("predict","预测"),W("dictate","口述")]),
     "mnemonic":"dic=说/指(和 indicate 一家);指点/透露出来的信号,就是 indication 迹象;动词 indicate;indicator 指标。",
     "forms":[F("indicate","v.","表明"),F("indicator","n.","指标")]}},
  # -form 形
  {"word":"formula","phonetic":"ˈfɔːmjulə","pos":"n.","def":"公式，方程式；配方；套话","cefr":"B1","freq_rank":63,
   "sentence_en":"There is no magic formula for success.","sentence_zh":"成功没有魔法公式。",
   "aids":{"morphemes":[M("form","root","形式，规则"),M("ula","suffix","小")],
     "derivation":"form(规则)+ula → 固定成形的规则/式子 → 公式",
     "family":FAM("form","形式、形状",[W("form","形式"),W("format","格式"),W("uniform","制服")]),
     "mnemonic":"form=形式/规则(和 format 一家);固定套路的式子=公式;婴儿配方奶=formula;客套的固定说法=套话;复数 formulae/formulas。",
     "forms":[F("formulas","n.","公式(复数)"),F("formulate","v.","制定")]}},
  # -vir 人/力
  {"word":"virtue","phonetic":"ˈvɜːtʃuː","pos":"n.","def":"美德，德行；优点；功效","cefr":"B2","freq_rank":70,
   "sentence_en":"Patience is a virtue.","sentence_zh":"耐心是一种美德。",
   "aids":{"morphemes":[M("virt","root","力量，德性(vir 人/力)"),M("ue","suffix","名词后缀")],
     "derivation":"vir(力、德)+tue → 内在的优良品质 → 美德",
     "family":FAM("virt/vir","力、德",[W("virtual","实质的"),W("virtually","实际上")]),
     "mnemonic":"virt=德/力(想 virtuoso 大师);高尚的品质=美德;好处/长处=优点;by virtue of=凭借;virtuous 有德的。",
     "forms":[F("virtues","n.","美德(复数)"),F("virtuous","adj.","有德的")]}},
  # -tect 盖
  {"word":"architect","phonetic":"ˈɑːkɪtekt","pos":"n.","def":"建筑师；缔造者，设计师","cefr":"B2","freq_rank":71,
   "sentence_en":"She is a famous architect.","sentence_zh":"她是位著名的建筑师。",
   "aids":{"morphemes":[M("archi","prefix","首，主(arch)"),M("tect","root","建造(tekton 木匠)")],
     "derivation":"archi(主)+tect(建造) → 主持建造的人 → 建筑师",
     "family":FAM("archi/arch","首、主",[W("architecture","建筑学"),W("monarch","君主")]),
     "mnemonic":"archi=主(想 monarch 君主)+tect(建造);主持设计建造的人=architect 建筑师;引申某事的'缔造者';architecture 建筑学。",
     "forms":[F("architecture","n.","建筑；架构")]}},
  # -cresc 生长
  {"word":"decrease","phonetic":"dɪˈkriːs","pos":"v./n.","def":"减少，下降","cefr":"B1","freq_rank":73,
   "sentence_en":"Sales decreased last month.","sentence_zh":"上个月销量下降了。",
   "aids":{"morphemes":[M("de","prefix","向下"),M("crease","root","生长(cresc)")],
     "derivation":"de(向下)+crease(生长) → 往下长、变少 → 减少",
     "family":FAM("cresc/cret","生长",[W("increase","增加"),W("crescent","新月"),W("concrete","混凝土")]),
     "mnemonic":"crease=生长(和 increase 一家);往下(de-)长=减少;反义 increase 增加(往上长)。",
     "forms":[F("decreased","v.","过去式/过去分词")]}},
  # -sign 记号
  {"word":"resign","phonetic":"rɪˈzaɪn","pos":"v.","def":"辞职；(resign oneself to)听任，顺从","cefr":"B2","freq_rank":82,
   "sentence_en":"He resigned from his post.","sentence_zh":"他辞去了职务。",
   "aids":{"morphemes":[M("re","prefix","反，回"),M("sign","root","记号，签")],
     "derivation":"re(回)+sign(签) → 反签、交回签字(职位) → 辞职",
     "family":FAM("sign","记号、标志",[W("sign","签"),W("signature","签名"),W("assign","分配"),W("design","设计")]),
     "mnemonic":"sign=签(和 sign 一家);签字'交回'职位,就是 resign 辞职;resignation 辞职;心里认命=resign oneself to。",
     "forms":[F("resignation","n.","辞职")]}},
  # -mark 记号
  {"word":"remark","phonetic":"rɪˈmɑːk","pos":"n./v.","def":"评论，谈论；注意到","cefr":"B1","freq_rank":81,
   "sentence_en":"He made a rude remark.","sentence_zh":"他说了句无礼的话。",
   "aids":{"morphemes":[M("re","prefix","再，加强"),M("mark","root","记号，注意")],
     "derivation":"re(加强)+mark(注意) → 特别注意到并说出 → 评论",
     "family":FAM("mark","记号、注意",[W("mark","标记"),W("remarkable","非凡的"),W("marker","标记物")]),
     "mnemonic":"mark=注意(和 remarkable 一家);把注意到的说一句,就是 remark 评论;remark on 评论;remarkable 非凡的。",
     "forms":[F("remarks","n.","评论(复数)")]}},
  # -cept 拿
  {"word":"receiver","phonetic":"rɪˈsiːvə","pos":"n.","def":"接收器，听筒；接受者","cefr":"B1","freq_rank":85,
   "sentence_en":"Pick up the receiver.","sentence_zh":"拿起听筒。",
   "aids":{"morphemes":[M("re","prefix","回"),M("ceiv","root","拿(cept)"),M("er","suffix","…的物/人")],
     "derivation":"receive(收到)+er → 接收信号/东西的器/人 → 接收器",
     "family":FAM("ceive/cept","拿、取",[W("receive","收到"),W("accept","接受"),W("perceive","察觉")]),
     "mnemonic":"ceiv=拿(和 receive 一家);负责接收的装置(听筒/收音机)或人,就是 receiver;动词 receive。",
     "forms":[F("receive","v.","收到")]}},
  # -thes 放
  {"word":"hypothesis","phonetic":"haɪˈpɒθəsɪs","pos":"n.","def":"假设，假说","cefr":"C1","freq_rank":75,
   "sentence_en":"The experiment tested the hypothesis.","sentence_zh":"实验检验了这一假说。",
   "aids":{"morphemes":[M("hypo","prefix","在下"),M("thes","root","放置(the)"),M("is","suffix","名词后缀")],
     "derivation":"hypo(在下)+thes(放) → 放在下面作前提 → 假设",
     "family":FAM("the/thes","放置",[W("thesis","论点；论文"),W("synthesis","合成"),W("theme","主题")]),
     "mnemonic":"thes=放(和 thesis 论点一家);垫在下面(hypo-)作为待验证前提,就是 hypothesis 假设;复数 hypotheses;hypothetical 假设的。",
     "forms":[F("hypotheses","n.","假设(复数)"),F("hypothetical","adj.","假设的")]}},
  # -fend 打
  {"word":"defendant","phonetic":"dɪˈfendənt","pos":"n.","def":"被告","cefr":"C1","freq_rank":68,
   "sentence_en":"The defendant pleaded not guilty.","sentence_zh":"被告不认罪。",
   "aids":{"morphemes":[M("de","prefix","离开，防"),M("fend","root","打，击"),M("ant","suffix","…的人")],
     "derivation":"defend(防御、辩护)+ant → 在庭上为自己辩护的一方 → 被告",
     "family":FAM("fend/fens","打、击",[W("defend","防御"),W("offend","冒犯"),W("defence","防御")]),
     "mnemonic":"fend=打(defend=挡开打击=防御);诉讼中需为自己辩护抵挡指控的人,就是 defendant 被告;反义 plaintiff 原告。",
     "forms":[F("defend","v.","防御；辩护")]}},
  # -cept 拿
  {"word":"acceptable","phonetic":"əkˈseptəbl","pos":"adj.","def":"可接受的，令人满意的","cefr":"B1","freq_rank":93,
   "sentence_en":"The quality is acceptable.","sentence_zh":"质量还可以接受。",
   "aids":{"morphemes":[M("ac","prefix","朝向(ad 变体)"),M("cept","root","拿"),M("able","suffix","可…的")],
     "derivation":"accept(接受)+able → 可以接受的 → 可接受的",
     "family":FAM("cept/ceive","拿、取",[W("accept","接受"),W("concept","概念"),W("except","除外")]),
     "mnemonic":"cept=拿(和 accept 一家);能接得下、可以接受的,就是 acceptable;反义 unacceptable 不可接受的。",
     "forms":[F("accept","v.","接受"),F("unacceptable","adj.","不可接受的")]}},
  # -tinu 保持
  {"word":"continuous","phonetic":"kənˈtɪnjuəs","pos":"adj.","def":"连续的，不间断的","cefr":"B1","freq_rank":95,
   "sentence_en":"There was continuous rain all day.","sentence_zh":"一整天都在下不停的雨。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("tinu","root","保持，连(ten)"),M("ous","suffix","…的")],
     "derivation":"continue(不断保持)+ous → 一直保持不断的 → 连续的",
     "family":FAM("tin/ten","保持、连",[W("continue","继续"),W("maintain","维持"),W("contain","包含")]),
     "mnemonic":"tinu=保持(和 continue 一家);中间不断、一直保持的,就是 continuous;continuity 连续性;continuously 不断地。",
     "forms":[F("continue","v.","继续"),F("continuity","n.","连续性")]}},
  # 高频名词/动词(常见/词根)
  {"word":"pregnancy","phonetic":"ˈpreɡnənsi","pos":"n.","def":"怀孕(期)","cefr":"B1","freq_rank":56,
   "sentence_en":"She is in the early stages of pregnancy.","sentence_zh":"她处于怀孕早期。",
   "aids":{"morphemes":[M("pre","prefix","在前"),M("gn","root","生(gen)"),M("ancy","suffix","名词后缀")],
     "derivation":"pregnant(即将生育的)+cy → 孕育状态 → 怀孕",
     "family":FAM("gen/gn","产生、生",[W("pregnant","怀孕的"),W("generate","产生"),W("gene","基因")]),
     "mnemonic":"gn=生(和 pregnant/generate 一家);孕育胎儿的时期,就是 pregnancy 怀孕;形容词 pregnant。",
     "forms":[F("pregnant","adj.","怀孕的")]}},
  {"word":"exact","phonetic":"ɪɡˈzækt","pos":"adj.","def":"确切的，精确的","cefr":"B1","freq_rank":64,
   "sentence_en":"What are the exact figures?","sentence_zh":"确切的数字是多少？",
   "aids":{"morphemes":[M("ex","prefix","出，彻底"),M("act","root","做，驱(ag)")],
     "derivation":"ex(彻底)+act(做) → 分毫做到位、量准 → 精确的",
     "family":FAM("act/ag","做、驱",[W("act","行动"),W("exam","考试"),W("agent","代理人")]),
     "mnemonic":"act=做(彻底做准);分毫不差、丝毫不含糊的,就是 exact;exactly 确切地/正是如此;反义 approximate 大约的。",
     "forms":[F("exactly","adv.","确切地")]}},
  {"word":"organ","phonetic":"ˈɔːɡən","pos":"n.","def":"器官；机构，机关；管风琴","cefr":"B1","freq_rank":84,
   "sentence_en":"The heart is a vital organ.","sentence_zh":"心脏是重要器官。",
   "aids":{"morphemes":[M("organ","root","工具，器官(organon)")],
     "derivation":"希腊 organon'工具、器官';身体的功能'工具' → 器官;引申'机构'",
     "family":FAM("organ","器官、工具",[W("organize","组织"),W("organism","生物体"),W("organic","有机的")]),
     "mnemonic":"organ=器官/工具;身体各司其职的部件=器官;发挥职能的团体=机构;一种键盘乐器=管风琴,都是 organ。",
     "forms":[F("organs","n.","器官(复数)")]}},
  {"word":"sanction","phonetic":"ˈsæŋkʃən","pos":"n./v.","def":"制裁；批准，认可","cefr":"C1","freq_rank":46,
   "sentence_en":"The UN imposed sanctions.","sentence_zh":"联合国实施了制裁。",
   "aids":{"morphemes":[M("sanct","root","神圣，使有效(sacred)"),M("ion","suffix","名词后缀")],
     "derivation":"sanct(使神圣、批准)→ 正式认可;违规则施加'认可的'惩罚 → 制裁",
     "family":FAM("sanct","神圣",[W("sacred","神圣的"),W("saint","圣人")]),
     "mnemonic":"sanct=神圣/使有效(想 saint 圣);正式认可批准=sanction;对违规方施加官方惩罚=制裁(常用复数 sanctions)。",
     "forms":[F("sanctions","n.","制裁(复数)")]}},
  {"word":"counsel","phonetic":"ˈkaʊnsl","pos":"n./v.","def":"建议，忠告；法律顾问；劝告","cefr":"C1","freq_rank":94,
   "sentence_en":"She sought legal counsel.","sentence_zh":"她寻求了法律咨询。",
   "aids":{"morphemes":[M("coun","prefix","一起(con)"),M("sel","root","召集，商议(sal)")],
     "derivation":"con(一起)+sel(商议) → 一起商量给主意 → 忠告",
     "family":FAM("","相关词",[W("counselor","顾问"),W("council","委员会")]),
     "mnemonic":"和 council(委员会)近亲;共同商议给的主意=counsel 忠告;打官司的法律顾问=counsel;别和 council(委员会)混。",
     "forms":[F("counselor","n.","顾问")]}},
  {"word":"reward","phonetic":"rɪˈwɔːd","pos":"n./v.","def":"奖赏，报酬；酬谢","cefr":"B1","freq_rank":83,
   "sentence_en":"Hard work brings its own reward.","sentence_zh":"努力自有回报。",
   "aids":{"morphemes":[M("re","prefix","回"),M("ward","root","看守，注视(guard)")],
     "derivation":"re(回)+ward(看/给) → 回过头给予好处 → 奖赏",
     "family":FAM("ward/guard","看守、注视",[W("award","授予"),W("guard","守卫"),W("regard","看待")]),
     "mnemonic":"ward=给/看(和 award 一家);对好行为回(re-)以好处,就是 reward 奖赏;rewarding 有回报的/值得的。",
     "forms":[F("rewarding","adj.","有回报的")]}},
  {"word":"ritual","phonetic":"ˈrɪtʃuəl","pos":"n./adj.","def":"仪式，典礼；例行公事；仪式性的","cefr":"B2","freq_rank":86,
   "sentence_en":"Tea drinking is a daily ritual for her.","sentence_zh":"喝茶是她每天的例行仪式。",
   "aids":{"morphemes":[M("rit","root","仪式(ritus)"),M("ual","suffix","…的")],
     "derivation":"rit(仪式)+ual → 按固定程序进行的 → 仪式",
     "family":FAM("rit","仪式",[W("rite","仪式")]),
     "mnemonic":"rit=仪式(想 rite 仪式);按固定程序反复进行的活动,就是 ritual 仪式/例行公事;religious ritual 宗教仪式。",
     "forms":[F("rituals","n.","仪式(复数)")]}},
  {"word":"sculpture","phonetic":"ˈskʌlptʃə","pos":"n.","def":"雕塑，雕刻(品)","cefr":"B1","freq_rank":97,
   "sentence_en":"The park is full of sculptures.","sentence_zh":"公园里满是雕塑。",
   "aids":{"morphemes":[M("sculpt","root","雕，刻(sculpere)"),M("ure","suffix","名词后缀")],
     "derivation":"sculpt(雕刻)+ure → 雕出来的作品 → 雕塑",
     "family":FAM("sculp","雕、刻",[W("sculptor","雕塑家")]),
     "mnemonic":"sculpt=雕刻;凿石/塑泥做出的立体作品,就是 sculpture 雕塑;动词 sculpt;sculptor 雕塑家。",
     "forms":[F("sculptor","n.","雕塑家"),F("sculptures","n.","雕塑(复数)")]}},
  {"word":"highlight","phonetic":"ˈhaɪlaɪt","pos":"v./n.","def":"突出，强调；精彩部分；高光","cefr":"B1","freq_rank":72,
   "sentence_en":"The report highlights key issues.","sentence_zh":"报告强调了关键问题。",
   "aids":{"morphemes":[M("high","root","高"),M("light","root","光")],
     "derivation":"high(高)+light(光) → 打上高光使醒目 → 突出、强调",
     "family":FAM("light","光",[W("light","光"),W("delight","高兴"),W("enlighten","启发")]),
     "mnemonic":"high(高)+light(光)——用亮光把重点照出来,就是 highlight 突出、强调;最精彩的片段=highlights。",
     "forms":[F("highlights","n.","精彩部分(复数)")]}},
  {"word":"adolescent","phonetic":"ˌædəˈlesnt","pos":"n./adj.","def":"青少年；青春期的","cefr":"B2","freq_rank":79,
   "sentence_en":"Adolescents need plenty of sleep.","sentence_zh":"青少年需要充足睡眠。",
   "aids":{"morphemes":[M("adolesc","root","成长(alescere)"),M("ent","suffix","…的")],
     "derivation":"adolesc(成长中)+ent → 正在长大成人的 → 青少年",
     "family":FAM("al/ol","成长、养",[W("adult","成年人(已长成)"),W("nourish","滋养")]),
     "mnemonic":"和 adult(成人)同源(al 成长);正处在长大过程中的人=adolescent 青少年;adolescence 青春期。",
     "forms":[F("adolescence","n.","青春期")]}},
  # 高频形容词/常见词
  {"word":"upset","phonetic":"ʌpˈset","pos":"adj./v.","def":"心烦的，难过的；打乱；弄翻","cefr":"B1","freq_rank":80,
   "sentence_en":"She was upset by the news.","sentence_zh":"她被这消息弄得心烦意乱。",
   "aids":{"morphemes":[M("up","root","向上"),M("set","root","放置")],
     "derivation":"up(向上)+set(放) → 底朝上翻掉 → 弄翻;心绪被'翻乱'→ 心烦的",
     "family":FAM("set","放置",[W("set","放置"),W("setting","环境")]),
     "mnemonic":"up(翻上来)+set(放)——把杯子/计划/心情'翻'乱,就是 upset 弄翻/打乱/心烦的(不规则:upset/upset)。",
     "forms":[F("upsetting","adj.","令人心烦的")]}},
  {"word":"awful","phonetic":"ˈɔːfl","pos":"adj.","def":"糟糕的，可怕的；极度的","cefr":"A2","freq_rank":49,
   "sentence_en":"The weather is awful today.","sentence_zh":"今天天气糟透了。",
   "aids":{"morphemes":[M("awe","root","敬畏，惊惧"),M("ful","suffix","充满…的")],
     "derivation":"awe(惊惧)+ful → 令人惊惧的 → 可怕的、糟糕的",
     "family":FAM("awe","敬畏",[W("awe","敬畏"),W("awesome","极好的")]),
     "mnemonic":"awe=惊惧(对比 awesome 令人惊叹的'好');令人反感/难受的,就是 awful 糟糕的;awfully 非常(口语)。",
     "forms":[F("awfully","adv.","非常")]}},
  {"word":"naked","phonetic":"ˈneɪkɪd","pos":"adj.","def":"裸体的；无遮盖的；赤裸裸的","cefr":"B1","freq_rank":43,
   "sentence_en":"You can see it with the naked eye.","sentence_zh":"用肉眼就能看见。",
   "aids":{"morphemes":[M("naked","root","裸(古英语 nacod)")],
     "derivation":"古英语'赤裸';不着衣物/无遮盖的 → 裸体的",
     "family":FAM("nud/nak","裸",[W("nude","裸体的")]),
     "mnemonic":"naked=裸(和 nude 一家);身上不着衣=裸体的;无遮蔽=naked flame 明火;不借助工具=the naked eye 肉眼;赤裸裸的真相=naked truth。",
     "forms":[]}},
  # 常见实义名词
  {"word":"battery","phonetic":"ˈbætəri","pos":"n.","def":"电池；一系列；殴打","cefr":"A2","freq_rank":45,
   "sentence_en":"The battery is dead.","sentence_zh":"电池没电了。",
   "aids":{"morphemes":[M("batter","root","连续打，击(bat)"),M("y","suffix","名词后缀")],
     "derivation":"batter(连续打)+y → 原指'一组炮'(连续轰击),引申'一组电池'→ 电池",
     "family":FAM("bat","打、击",[W("batter","连续猛击"),W("combat","战斗"),W("battle","战斗")]),
     "mnemonic":"bat=打(和 battle 一家);原指成组的炮'连续轰击',引申成组的蓄电单元=电池;法律上的'殴打'也是 battery。",
     "forms":[F("batteries","n.","电池(复数)")]}},
  {"word":"tunnel","phonetic":"ˈtʌnl","pos":"n./v.","def":"隧道，地道；挖隧道","cefr":"B1","freq_rank":67,
   "sentence_en":"The train went through a tunnel.","sentence_zh":"火车穿过了一条隧道。",
   "aids":{"morphemes":[M("tunnel","root","管，桶(tonne)")],
     "derivation":"古法语'桶、管';像管一样贯通的地道 → 隧道",
     "family":FAM("","相关词",[W("tunnelling","挖隧道")]),
     "mnemonic":"tunnel=管状通道;穿山越地的管状通道=隧道;light at the end of the tunnel 苦尽甘来的曙光;挖隧道=tunnel。",
     "forms":[F("tunnels","n.","隧道(复数)")]}},
  {"word":"gallery","phonetic":"ˈɡæləri","pos":"n.","def":"画廊，美术馆；(剧院)顶层楼座；长廊","cefr":"B1","freq_rank":66,
   "sentence_en":"We visited an art gallery.","sentence_zh":"我们参观了一家美术馆。",
   "aids":{"morphemes":[M("galler","root","长廊(galeria)"),M("y","suffix","名词后缀")],
     "derivation":"中世纪拉丁 galeria'门廊、长廊';陈列画作的长厅 → 画廊",
     "family":FAM("","相关词",[W("gallerist","画廊主")]),
     "mnemonic":"gallery=长廊;沿长廊挂满画作的展厅=画廊/美术馆;剧院最高最便宜的排座=顶层楼座;手机'相册'也叫 gallery。",
     "forms":[F("galleries","n.","画廊(复数)")]}},
  {"word":"surgeon","phonetic":"ˈsɜːdʒən","pos":"n.","def":"外科医生","cefr":"B1","freq_rank":91,
   "sentence_en":"The surgeon performed the operation.","sentence_zh":"外科医生做了手术。",
   "aids":{"morphemes":[M("sur","root","手(cheir)"),M("geon","root","做，工(erg)")],
     "derivation":"希腊 kheirourgos'用手操作者';动手施术的医生 → 外科医生",
     "family":FAM("erg/urg","做、工",[W("surgery","手术"),W("energy","能量")]),
     "mnemonic":"和 surgery(手术)一家(手+做);动手在人体上操作的医生,就是 surgeon 外科医生(对照 physician 内科医生)。",
     "forms":[F("surgeons","n.","外科医生(复数)")]}},
  {"word":"stem","phonetic":"stem","pos":"n./v.","def":"茎，杆；词干；起源于；阻止","cefr":"B2","freq_rank":92,
   "sentence_en":"The problem stems from poor planning.","sentence_zh":"问题源于规划不善。",
   "aids":{"morphemes":[M("stem","root","茎，干(古英语 stemn)")],
     "derivation":"古英语'树干';植物主干 → 茎;从主干长出 → 起源于",
     "family":FAM("","相关词",[W("stem cell","干细胞")]),
     "mnemonic":"stem=茎/主干;植物的茎=stem;词的主干=词干;从根上'长出'=stem from 起源于;挡住水流=stem 阻止;stem cell 干细胞。",
     "forms":[F("stems","n.","茎(复数)"),F("stemmed","v.","过去式/过去分词")]}},
  {"word":"clue","phonetic":"kluː","pos":"n.","def":"线索，提示","cefr":"B1","freq_rank":59,
   "sentence_en":"The police found an important clue.","sentence_zh":"警方发现了一条重要线索。",
   "aids":{"morphemes":[M("clue","root","线团(clew)")],
     "derivation":"源自 clew'线团'(神话中用线团走出迷宫);引路的线 → 线索",
     "family":FAM("","相关词",[W("clueless","茫然的")]),
     "mnemonic":"clue 源自'线团'(希腊神话靠线团走出迷宫);帮你解谜的引路信息=clue 线索;have no clue 毫无头绪;clueless 一无所知的。",
     "forms":[F("clues","n.","线索(复数)")]}},
  {"word":"magic","phonetic":"ˈmædʒɪk","pos":"n./adj.","def":"魔法，魔术；有魔力的，神奇的","cefr":"A2","freq_rank":89,
   "sentence_en":"The show was full of magic.","sentence_zh":"表演充满魔力。",
   "aids":{"morphemes":[M("mag","root","法师(magus 祆教祭司)"),M("ic","suffix","…的")],
     "derivation":"mag(法师)+ic → 法师之术 → 魔法",
     "family":FAM("mag","法师、大",[W("magician","魔术师")]),
     "mnemonic":"mag=法师(源自波斯祭司 magi);超自然之术/戏法=magic 魔法/魔术;神奇的=magic;magician 魔术师。",
     "forms":[F("magical","adj.","神奇的"),F("magician","n.","魔术师")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 21
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
