#!/usr/bin/env python
# 第二十批(约52词):逐词精做 aids,追加进 data/vocab-seed.json。
import json, os, io, sys
try: sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception: pass
HERE = os.path.dirname(os.path.abspath(__file__)); SEED = os.path.join(HERE, "..", "data", "vocab-seed.json")
def M(t,ty,g): return {"text":t,"type":ty,"gloss":g}
def F(w,p,d): return {"word":w,"pos":p,"def":d}
def FAM(r,g,ws): return {"root":r,"gloss":g,"words":ws}
def W(w,g): return {"word":w,"def":g}

BATCH = [
  # -point 点
  {"word":"appoint","phonetic":"əˈpɔɪnt","pos":"v.","def":"任命，委派；约定(时间)","cefr":"B2","freq_rank":43,
   "sentence_en":"They appointed her as manager.","sentence_zh":"他们任命她为经理。",
   "aids":{"morphemes":[M("ap","prefix","朝向(ad 变体)"),M("point","root","点，指定")],
     "derivation":"ap(朝向)+point(指定) → 指定某人担任 → 任命",
     "family":FAM("point/punct","点、指定",[W("point","点"),W("appointment","约会；任命"),W("disappoint","使失望")]),
     "mnemonic":"point=指定(和 appointment 一家);把某个位置指(ap-)给某人,就是 appoint 任命;约定时间也是 appoint。",
     "forms":[F("appointment","n.","约会；任命")]}},
  # -gest 带来
  {"word":"register","phonetic":"ˈredʒɪstə","pos":"v./n.","def":"登记，注册；(仪器)显示；登记簿","cefr":"B1","freq_rank":44,
   "sentence_en":"You must register before the game.","sentence_zh":"比赛前你必须注册。",
   "aids":{"morphemes":[M("re","prefix","回，back"),M("gist","root","带，携(gest)"),M("er","suffix","名词后缀")],
     "derivation":"re(回)+gist(带) → 把信息带回记录下来 → 登记",
     "family":FAM("gest","带来、携带",[W("digest","消化"),W("suggest","建议"),W("gesture","手势")]),
     "mnemonic":"gist=带(和 gesture 一家);把名字/信息带回记录簿,就是 register 登记;cash register 收银机;registration 注册。",
     "forms":[F("registration","n.","注册，登记")]}},
  # -domin 支配
  {"word":"dominant","phonetic":"ˈdɒmɪnənt","pos":"adj.","def":"占主导的，支配的；显性的","cefr":"B2","freq_rank":45,
   "sentence_en":"He has a dominant personality.","sentence_zh":"他性格强势。",
   "aids":{"morphemes":[M("domin","root","主人，支配"),M("ant","suffix","…的")],
     "derivation":"domin(支配)+ant → 起支配作用的 → 占主导的",
     "family":FAM("domin","主人、支配",[W("dominate","支配"),W("domestic","家庭的"),W("dominion","统治权")]),
     "mnemonic":"domin=支配(和 dominate 一家);处于主宰地位、压过其余的,就是 dominant;遗传学的'显性'也是 dominant。",
     "forms":[F("dominate","v.","支配"),F("dominance","n.","优势")]}},
  # -cap/-cip 拿
  {"word":"anticipate","phonetic":"ænˈtɪsɪpeɪt","pos":"v.","def":"预期，预料；预先处理","cefr":"B2","freq_rank":49,
   "sentence_en":"We anticipate a busy summer.","sentence_zh":"我们预计夏天会很忙。",
   "aids":{"morphemes":[M("anti","prefix","在前(ante)"),M("cip","root","拿(cap)"),M("ate","suffix","动词后缀")],
     "derivation":"anti(在前)+cip(拿) → 提前把情况抓在手 → 预期",
     "family":FAM("cap/cip","拿、抓",[W("capture","捕获"),W("participate","参加"),W("accept","接受")]),
     "mnemonic":"anti=在前(ante,想 ancestor 祖先)+cip(拿);事先(anti-)把要发生的抓(cip)住,就是 anticipate 预期;anticipation 期待。",
     "forms":[F("anticipation","n.","预期，期待")]}},
  # -tend 伸
  {"word":"extension","phonetic":"ɪkˈstenʃən","pos":"n.","def":"延长，扩展；(电话)分机；扩展名","cefr":"B2","freq_rank":51,
   "sentence_en":"They asked for an extension of the deadline.","sentence_zh":"他们要求延长截止日期。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("tens","root","伸展"),M("ion","suffix","名词后缀")],
     "derivation":"extend(向外伸展)+ion → 延伸/扩展的部分 → 延长",
     "family":FAM("tend/tens","伸展",[W("extend","延伸"),W("extensive","广泛的"),W("tension","紧张")]),
     "mnemonic":"tens=伸(和 extend 一家);向外伸展出来的部分/时间,就是 extension 延长、扩展;文件的扩展名(.txt)。",
     "forms":[F("extend","v.","延伸")]}},
  # -leg 法
  {"word":"legitimate","phonetic":"lɪˈdʒɪtɪmət","pos":"adj.","def":"合法的，正当的","cefr":"C1","freq_rank":54,
   "sentence_en":"That's a legitimate concern.","sentence_zh":"那是个正当的担忧。",
   "aids":{"morphemes":[M("legitim","root","合法(legitimus)"),M("ate","suffix","…的")],
     "derivation":"leg(法律)→ 合乎法律/情理的 → 合法的、正当的",
     "family":FAM("leg","法律",[W("legal","合法的"),W("legislation","立法"),W("legislator","立法者")]),
     "mnemonic":"leg=法(和 legal 一家);合乎法律、站得住理的,就是 legitimate 合法的/正当的;反义 illegitimate。",
     "forms":[F("legitimacy","n.","合法性")]}},
  # -ori 升起
  {"word":"orientation","phonetic":"ˌɔːriənˈteɪʃən","pos":"n.","def":"方向，定位；(新人)入职培训；倾向","cefr":"B2","freq_rank":55,
   "sentence_en":"New students attend an orientation.","sentence_zh":"新生参加入学培训。",
   "aids":{"morphemes":[M("orient","root","东方，定向"),M("ation","suffix","名词后缀")],
     "derivation":"orient(定向、朝东)+ation → 确定方位/使适应 → 定位、入职培训",
     "family":FAM("ori","升起、起源",[W("orient","东方；定向"),W("origin","起源"),W("original","最初的")]),
     "mnemonic":"orient=朝东定向(太阳升起处);找准方位=定位;帮新人'找方向'=入职培训 orientation;性/价值取向也是 orientation。",
     "forms":[F("orient","v.","使适应；定向")]}},
  # -fla 吹
  {"word":"inflation","phonetic":"ɪnˈfleɪʃən","pos":"n.","def":"通货膨胀；膨胀","cefr":"B2","freq_rank":56,
   "sentence_en":"Inflation is rising fast.","sentence_zh":"通货膨胀上升很快。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("flat","root","吹(flare)"),M("ion","suffix","名词后缀")],
     "derivation":"in(向内)+flat(吹) → 往里吹气鼓大 → 膨胀;货币'吹大'→ 通货膨胀",
     "family":FAM("fla/flat","吹",[W("inflate","使充气"),W("deflate","放气"),W("flatulent","肠胃气胀的")]),
     "mnemonic":"flat=吹(想给气球 inflate 充气);物价像被吹气一样鼓涨,就是 inflation 通货膨胀;反义 deflation 通缩。",
     "forms":[F("inflate","v.","使充气；使膨胀")]}},
  # -pict 画
  {"word":"depict","phonetic":"dɪˈpɪkt","pos":"v.","def":"描绘，描述","cefr":"B2","freq_rank":60,
   "sentence_en":"The painting depicts a battle.","sentence_zh":"这幅画描绘了一场战斗。",
   "aids":{"morphemes":[M("de","prefix","加强"),M("pict","root","画")],
     "derivation":"de(加强)+pict(画) → 画出来、描出来 → 描绘",
     "family":FAM("pict","画",[W("picture","图画"),W("picturesque","风景如画的")]),
     "mnemonic":"pict=画(和 picture 一家);用画笔或文字勾画出来,就是 depict 描绘;depiction 描绘。",
     "forms":[F("depiction","n.","描绘")]}},
  # -laps 滑
  {"word":"collapse","phonetic":"kəˈlæps","pos":"v./n.","def":"倒塌，崩溃；(健康)垮掉；暴跌","cefr":"B2","freq_rank":61,
   "sentence_en":"The old bridge collapsed.","sentence_zh":"那座旧桥坍塌了。",
   "aids":{"morphemes":[M("col","prefix","一起(com)"),M("lapse","root","滑，落")],
     "derivation":"col(一起)+lapse(落) → 一齐塌落 → 倒塌、崩溃",
     "family":FAM("laps","滑、落",[W("lapse","失误；流逝"),W("elapse","(时间)流逝"),W("relapse","旧病复发")]),
     "mnemonic":"lapse=滑落(想 elapse 时间流逝);整体一齐(col-)滑塌下来,就是 collapse 倒塌、崩溃;economic collapse 经济崩溃。",
     "forms":[F("collapsed","v.","过去式/过去分词")]}},
  # -miss 送
  {"word":"permission","phonetic":"pəˈmɪʃən","pos":"n.","def":"许可，允许","cefr":"A2","freq_rank":67,
   "sentence_en":"You need permission to enter.","sentence_zh":"进入需要许可。",
   "aids":{"morphemes":[M("per","prefix","通过"),M("miss","root","送，放"),M("ion","suffix","名词后缀")],
     "derivation":"permit(让通过)+ion → 放行、准许 → 许可",
     "family":FAM("mit/miss","送、放",[W("permit","允许"),W("submit","提交"),W("mission","任务"),W("admit","准入")]),
     "mnemonic":"miss=放(和 permit 一家);让你通过(per-)、放行,就是 permission 许可;动词 permit;ask for permission 请求许可。",
     "forms":[F("permit","v.","允许")]}},
  # -vot 誓
  {"word":"devote","phonetic":"dɪˈvəʊt","pos":"v.","def":"把…奉献给，投入","cefr":"B2","freq_rank":66,
   "sentence_en":"She devoted her life to teaching.","sentence_zh":"她把一生献给了教育。",
   "aids":{"morphemes":[M("de","prefix","完全"),M("vote","root","誓愿(vov)")],
     "derivation":"de(完全)+vote(誓愿) → 立誓完全投入 → 奉献",
     "family":FAM("vot/vov","誓愿",[W("vote","投票"),W("vow","誓言")]),
     "mnemonic":"vote=誓愿(和 vow 誓言一家);立誓把时间/精力完全投进去,就是 devote;devote...to 献身于;devoted 忠诚的。",
     "forms":[F("devotion","n.","奉献；忠诚"),F("devoted","adj.","忠诚的")]}},
  # -sting 刺/区分
  {"word":"distinguish","phonetic":"dɪˈstɪŋɡwɪʃ","pos":"v.","def":"区分，辨别；使杰出","cefr":"B2","freq_rank":73,
   "sentence_en":"Can you distinguish the twins?","sentence_zh":"你能分辨这对双胞胎吗？",
   "aids":{"morphemes":[M("di","prefix","分开"),M("stingu","root","刺，戳(sting)"),M("ish","suffix","动词后缀")],
     "derivation":"di(分开)+stingu(刺、点) → 用记号点开、分辨 → 区分",
     "family":FAM("sting/stinct","刺、戳",[W("distinct","不同的"),W("instinct","本能"),W("extinguish","熄灭")]),
     "mnemonic":"sting=刺/点(和 distinct 一家);用差别把两者点(di-)开来看,就是 distinguish 区分;distinguished 杰出的。",
     "forms":[F("distinction","n.","区别；卓越"),F("distinguished","adj.","杰出的")]}},
  {"word":"distinct","phonetic":"dɪˈstɪŋkt","pos":"adj.","def":"截然不同的；清晰的，明显的","cefr":"B2","freq_rank":74,
   "sentence_en":"There are two distinct groups.","sentence_zh":"有两个截然不同的群体。",
   "aids":{"morphemes":[M("di","prefix","分开"),M("stinct","root","刺，戳")],
     "derivation":"di(分开)+stinct(刺、点) → 被区分点开的 → 截然不同的、清晰的",
     "family":FAM("sting/stinct","刺、戳",[W("distinguish","区分"),W("instinct","本能"),W("extinct","灭绝的")]),
     "mnemonic":"stinct=点/刺(和 distinguish 一家);彼此点(di-)得开、界限分明的,就是 distinct;distinctive 独特的;distinctly 清楚地。",
     "forms":[F("distinctive","adj.","独特的"),F("distinctly","adv.","清楚地")]}},
  # -suad 劝
  {"word":"persuade","phonetic":"pəˈsweɪd","pos":"v.","def":"说服，劝说","cefr":"B1","freq_rank":77,
   "sentence_en":"I persuaded him to stay.","sentence_zh":"我劝他留下来。",
   "aids":{"morphemes":[M("per","prefix","彻底"),M("suade","root","劝，甜(suad)")],
     "derivation":"per(彻底)+suade(劝) → 好言相劝到底 → 说服",
     "family":FAM("suad","劝、甜",[W("persuasion","说服"),W("dissuade","劝阻"),W("suave","温和的")]),
     "mnemonic":"suade=劝(甜言相劝);彻底(per-)把人劝动,就是 persuade 说服;反义 dissuade 劝阻;persuasive 有说服力的。",
     "forms":[F("persuasion","n.","说服"),F("persuasive","adj.","有说服力的")]}},
  # -sequ 跟随
  {"word":"subsequent","phonetic":"ˈsʌbsɪkwənt","pos":"adj.","def":"随后的，后来的","cefr":"C1","freq_rank":78,
   "sentence_en":"Subsequent events proved him right.","sentence_zh":"随后的事件证明他是对的。",
   "aids":{"morphemes":[M("sub","prefix","在下，随后"),M("sequ","root","跟随"),M("ent","suffix","…的")],
     "derivation":"sub(随后)+sequ(跟随) → 紧跟其后的 → 随后的",
     "family":FAM("sequ/secut","跟随",[W("sequence","顺序"),W("consequence","后果"),W("consecutive","连续的")]),
     "mnemonic":"sequ=跟随(和 sequence 一家);紧跟在后面到来的,就是 subsequent;反义 previous 先前的;subsequently 随后。",
     "forms":[F("subsequently","adv.","随后")]}},
  {"word":"frequent","phonetic":"ˈfriːkwənt","pos":"adj.","def":"频繁的，经常的","cefr":"B1","freq_rank":79,
   "sentence_en":"He is a frequent visitor.","sentence_zh":"他是常客。",
   "aids":{"morphemes":[M("frequ","root","频繁，拥挤"),M("ent","suffix","…的")],
     "derivation":"frequ(频繁)+ent → 一再发生的 → 频繁的",
     "family":FAM("frequ","频繁",[W("frequency","频率"),W("frequently","经常")]),
     "mnemonic":"frequ=频繁(和 frequency 一家);一再、常常发生的,就是 frequent;frequently 经常;反义 rare/infrequent。",
     "forms":[F("frequency","n.","频率"),F("frequently","adv.","经常")]}},
  # -ced 走
  {"word":"exceed","phonetic":"ɪkˈsiːd","pos":"v.","def":"超过，超出","cefr":"B2","freq_rank":82,
   "sentence_en":"The cost exceeded our budget.","sentence_zh":"成本超出了我们的预算。",
   "aids":{"morphemes":[M("ex","prefix","向外，超"),M("ceed","root","走")],
     "derivation":"ex(超)+ceed(走) → 走过了头、越过 → 超过",
     "family":FAM("ceed/cess","走",[W("proceed","前进"),W("succeed","成功"),W("process","过程"),W("access","通道")]),
     "mnemonic":"ceed=走(和 proceed 一家);走(ceed)出(ex-)界、越过限度,就是 exceed 超过;excess 过量;exceedingly 极其。",
     "forms":[F("excess","n.","过量"),F("excessive","adj.","过度的")]}},
  # -hab 拿
  {"word":"exhibit","phonetic":"ɪɡˈzɪbɪt","pos":"v./n.","def":"展出，陈列；表现出；展品","cefr":"B1","freq_rank":92,
   "sentence_en":"The museum exhibits ancient art.","sentence_zh":"博物馆展出古代艺术品。",
   "aids":{"morphemes":[M("ex","prefix","向外"),M("hib","root","拿，持(hab)")],
     "derivation":"ex(向外)+hib(拿) → 把东西拿出来给人看 → 展出",
     "family":FAM("hab/hib","拿、持",[W("exhibition","展览"),W("prohibit","禁止"),W("habit","习惯")]),
     "mnemonic":"hib=拿(想 prohibit 拿住不许);把东西/情绪向外(ex-)拿出来显示,就是 exhibit 展出/表现;exhibition 展览。",
     "forms":[F("exhibition","n.","展览")]}},
  # -scrib 写
  {"word":"prescription","phonetic":"prɪˈskrɪpʃən","pos":"n.","def":"处方，药方；规定","cefr":"B2","freq_rank":96,
   "sentence_en":"You need a prescription for this medicine.","sentence_zh":"这种药需要处方。",
   "aids":{"morphemes":[M("pre","prefix","预先"),M("script","root","写"),M("ion","suffix","名词后缀")],
     "derivation":"pre(预先)+script(写) → 医生预先写下的用药单 → 处方",
     "family":FAM("scrib/script","写",[W("describe","描述"),W("subscribe","订阅"),W("manuscript","手稿"),W("script","脚本")]),
     "mnemonic":"script=写(和 describe 一家);医生预先(pre-)写下的用药指示,就是 prescription 处方;动词 prescribe。",
     "forms":[F("prescribe","v.","开处方；规定")]}},
  # -cru 生长
  {"word":"recruit","phonetic":"rɪˈkruːt","pos":"v./n.","def":"招募，征募；新成员","cefr":"B2","freq_rank":98,
   "sentence_en":"The company is recruiting new staff.","sentence_zh":"公司正在招聘新员工。",
   "aids":{"morphemes":[M("re","prefix","再"),M("cruit","root","生长(cresc)")],
     "derivation":"re(再)+cruit(生长) → 补充新血、使队伍再壮大 → 招募",
     "family":FAM("cresc/cru","生长",[W("increase","增加"),W("crescent","新月"),W("concrete","混凝土")]),
     "mnemonic":"cruit=生长(和 increase 一家);给团队补充'新长成'的人手,就是 recruit 招募;新招来的人=新兵/新成员。",
     "forms":[F("recruitment","n.","招募")]}},
  # -vad 走
  {"word":"invasion","phonetic":"ɪnˈveɪʒən","pos":"n.","def":"入侵，侵略；侵犯","cefr":"B2","freq_rank":88,
   "sentence_en":"The invasion began at dawn.","sentence_zh":"入侵在黎明开始。",
   "aids":{"morphemes":[M("in","prefix","向内"),M("vas","root","走(vad)"),M("ion","suffix","名词后缀")],
     "derivation":"invade(走进来)+ion → 强行走入 → 入侵",
     "family":FAM("vad/vas","走",[W("invade","入侵"),W("evade","逃避"),W("pervade","弥漫")]),
     "mnemonic":"vas=走(和 invade 一家);武力走进(in-)别国,就是 invasion 入侵;动词 invade;invasion of privacy 侵犯隐私。",
     "forms":[F("invade","v.","入侵")]}},
  # -tens 伸
  {"word":"intensity","phonetic":"ɪnˈtensəti","pos":"n.","def":"强度，烈度；强烈","cefr":"B2","freq_rank":90,
   "sentence_en":"The intensity of the storm increased.","sentence_zh":"风暴的强度增加了。",
   "aids":{"morphemes":[M("in","prefix","加强"),M("tens","root","拉紧"),M("ity","suffix","名词后缀")],
     "derivation":"intense(绷紧、强烈)+ity → 强烈的程度 → 强度",
     "family":FAM("tend/tens","拉紧、伸",[W("intense","强烈的"),W("tension","紧张"),W("extend","延伸")]),
     "mnemonic":"tens=拉紧(和 intense 一家);绷紧到什么程度、多强烈,就是 intensity 强度;intensive 密集的。",
     "forms":[F("intense","adj.","强烈的"),F("intensive","adj.","密集的")]}},
  # -equ 相等
  {"word":"adequate","phonetic":"ˈædɪkwət","pos":"adj.","def":"足够的，适当的","cefr":"B2","freq_rank":89,
   "sentence_en":"The food was adequate for everyone.","sentence_zh":"食物够所有人吃。",
   "aids":{"morphemes":[M("ad","prefix","朝向"),M("equ","root","相等"),M("ate","suffix","…的")],
     "derivation":"ad(朝向)+equ(相等) → 与需求相当的 → 足够的",
     "family":FAM("equ","相等、平",[W("equal","相等的"),W("equivalent","等价的"),W("equator","赤道")]),
     "mnemonic":"equ=相等(和 equal 一家);量与需求正好相当的,就是 adequate 足够的;反义 inadequate 不足的;adequately 充分地。",
     "forms":[F("adequately","adv.","充分地"),F("inadequate","adj.","不足的")]}},
  # -cresc 生长
  {"word":"concrete","phonetic":"ˈkɒnkriːt","pos":"adj./n.","def":"具体的，实在的；混凝土","cefr":"B2","freq_rank":95,
   "sentence_en":"Give me a concrete example.","sentence_zh":"给我一个具体的例子。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("cret","root","生长，凝结(cresc)")],
     "derivation":"con(一起)+cret(凝结) → 凝固成实体的 → 具体的、混凝土",
     "family":FAM("cresc/cret","生长、凝结",[W("increase","增加"),W("crescent","新月"),W("recruit","招募")]),
     "mnemonic":"cret=凝结(和 increase 生长一家);凝成实体、摸得着的=具体的;凝固的建材=混凝土,都是 concrete;反义 abstract 抽象的。",
     "forms":[F("concretely","adv.","具体地")]}},
  # -capt 抓
  {"word":"chase","phonetic":"tʃeɪs","pos":"v./n.","def":"追赶，追捕；追求","cefr":"B1","freq_rank":97,
   "sentence_en":"The dog chased the cat.","sentence_zh":"狗追猫。",
   "aids":{"morphemes":[M("chase","root","追，抓(captiare)")],
     "derivation":"与 capture/catch'抓'同源;追着要抓住 → 追赶",
     "family":FAM("capt/chase","抓、追",[W("capture","捕获"),W("catch","抓住"),W("purchase","购买")]),
     "mnemonic":"chase 与 catch/capture(抓)同源;紧跟着要抓住,就是 chase 追赶;追梦=chase a dream;cut to the chase 直奔主题。",
     "forms":[F("chased","v.","过去式/过去分词"),F("chases","n.","追逐(复数)")]}},
  # 高频名词/动词(常见/词根)
  {"word":"identification","phonetic":"aɪˌdentɪfɪˈkeɪʃən","pos":"n.","def":"识别，鉴定；身份证明；认同","cefr":"B2","freq_rank":85,
   "sentence_en":"Please show some identification.","sentence_zh":"请出示身份证明。",
   "aids":{"morphemes":[M("ident","root","相同"),M("ification","suffix","名词后缀")],
     "derivation":"identify(认出、确认同一)+ation → 识别/证明身份 → 鉴定",
     "family":FAM("ident","相同",[W("identify","识别"),W("identity","身份"),W("identical","完全相同的")]),
     "mnemonic":"ident=相同(和 identify 一家);确认'是这个人/这个东西'=识别/身份证明(缩写 ID);情感上认同也是 identification。",
     "forms":[F("identify","v.","识别")]}},
  {"word":"heritage","phonetic":"ˈherɪtɪdʒ","pos":"n.","def":"遗产，传统(文化)","cefr":"B2","freq_rank":46,
   "sentence_en":"This site is part of our national heritage.","sentence_zh":"这处遗址是我们民族遗产的一部分。",
   "aids":{"morphemes":[M("herit","root","继承(heres 继承人)"),M("age","suffix","名词后缀")],
     "derivation":"herit(继承)+age → 世代继承下来的 → 遗产、传统",
     "family":FAM("herit","继承",[W("inherit","继承"),W("heir","继承人")]),
     "mnemonic":"herit=继承(想 inherit 继承);祖辈传下来的文化/财富,就是 heritage 遗产;World Heritage 世界遗产;heir 继承人。",
     "forms":[F("inherit","v.","继承")]}},
  {"word":"legacy","phonetic":"ˈleɡəsi","pos":"n.","def":"遗产；遗留问题，传承","cefr":"C1","freq_rank":50,
   "sentence_en":"He left a lasting legacy.","sentence_zh":"他留下了不朽的遗产。",
   "aids":{"morphemes":[M("leg","root","委托，法(leg)"),M("acy","suffix","名词后缀")],
     "derivation":"leg(委托、遗赠)+acy → 遗留/委托下来的 → 遗产",
     "family":FAM("leg","委托、法",[W("legal","合法的"),W("delegate","委派"),W("legislation","立法")]),
     "mnemonic":"leg=委托/遗赠(和 legal 一家);前人遗留、传承下来的东西或影响,就是 legacy;a legacy of=…遗留的问题。",
     "forms":[F("legacies","n.","遗产(复数)")]}},
  {"word":"frustration","phonetic":"frʌˈstreɪʃən","pos":"n.","def":"沮丧，挫败(感)；挫折","cefr":"B2","freq_rank":70,
   "sentence_en":"He shouted in frustration.","sentence_zh":"他沮丧地大喊。",
   "aids":{"morphemes":[M("frustr","root","徒劳，落空(frustra)"),M("ation","suffix","名词后缀")],
     "derivation":"frustrate(使落空)+ion → 努力落空的懊恼 → 挫败感",
     "family":FAM("frustr","徒劳、落空",[W("frustrate","使沮丧")]),
     "mnemonic":"frustr=徒劳落空(拉丁 frustra 白费);努力受挫、事与愿违的懊恼,就是 frustration;动词 frustrate;frustrating 令人沮丧的。",
     "forms":[F("frustrate","v.","使沮丧"),F("frustrating","adj.","令人沮丧的")]}},
  {"word":"habitat","phonetic":"ˈhæbɪtæt","pos":"n.","def":"栖息地，(动植物)生境","cefr":"B2","freq_rank":65,
   "sentence_en":"Pandas' natural habitat is bamboo forests.","sentence_zh":"熊猫的天然栖息地是竹林。",
   "aids":{"morphemes":[M("habit","root","居住，持有"),M("at","suffix","地方")],
     "derivation":"拉丁 habitat'它居住';动植物居住之处 → 栖息地",
     "family":FAM("hab/habit","居住、持有",[W("habit","习惯"),W("inhabit","居住于"),W("inhabitant","居民")]),
     "mnemonic":"habit=居住(想 inhabit 居住于);动植物赖以生存居住的环境,就是 habitat 栖息地。",
     "forms":[F("habitats","n.","栖息地(复数)")]}},
  {"word":"consensus","phonetic":"kənˈsensəs","pos":"n.","def":"共识，一致意见","cefr":"C1","freq_rank":99,
   "sentence_en":"They reached a consensus.","sentence_zh":"他们达成了共识。",
   "aids":{"morphemes":[M("con","prefix","一起"),M("sens","root","感觉，想"),M("us","suffix","名词后缀")],
     "derivation":"con(一起)+sens(想) → 大家想到一块儿 → 共识",
     "family":FAM("sens/sent","感觉、想",[W("sense","感觉"),W("consent","同意"),W("sensible","明智的")]),
     "mnemonic":"sens=想/感(和 sense 一家);众人感受/看法趋于一致,就是 consensus 共识;reach a consensus 达成共识。",
     "forms":[]}},
  {"word":"venture","phonetic":"ˈventʃə","pos":"n./v.","def":"(风险)企业，冒险事业；敢于，冒险(做)","cefr":"B2","freq_rank":87,
   "sentence_en":"It was a risky business venture.","sentence_zh":"那是一项有风险的商业事业。",
   "aids":{"morphemes":[M("vent","root","来"),M("ure","suffix","名词后缀")],
     "derivation":"与 adventure 同根(vent 来);敢冒险闯的事 → 冒险事业",
     "family":FAM("ven/vent","来",[W("adventure","冒险"),W("event","事件"),W("invent","发明")]),
     "mnemonic":"vent=来(和 adventure 一家);敢冒风险去闯的一摊事,就是 venture;joint venture 合资企业;venture to 斗胆做;nothing ventured, nothing gained 不入虎穴焉得虎子。",
     "forms":[F("ventures","n.","企业(复数)")]}},
  {"word":"cope","phonetic":"kəʊp","pos":"v.","def":"(成功)应对，处理","cefr":"B1","freq_rank":57,
   "sentence_en":"She copes well under pressure.","sentence_zh":"她能很好地应对压力。",
   "aids":{"morphemes":[M("cope","root","打，交手(coup)")],
     "derivation":"古法语 couper'打、交手';与困难交手、招架 → 应对",
     "family":FAM("coup","打、击",[W("coup","政变；妙招")]),
     "mnemonic":"cope 源自'交手、招架';与难题过招并顶住,就是 cope with 应对、处理;=deal with/manage。",
     "forms":[F("coped","v.","过去式/过去分词"),F("coping","n.","应对")]}},
  # 高频形容词/副词
  {"word":"impressive","phonetic":"ɪmˈpresɪv","pos":"adj.","def":"给人深刻印象的，令人赞叹的","cefr":"B1","freq_rank":75,
   "sentence_en":"That's an impressive achievement.","sentence_zh":"那是个了不起的成就。",
   "aids":{"morphemes":[M("im","prefix","向内"),M("press","root","压"),M("ive","suffix","…的")],
     "derivation":"impress(压印进心)+ive → 能压下深刻一印的 → 令人印象深刻的",
     "family":FAM("press","压",[W("impress","使印象深刻"),W("pressure","压力"),W("express","表达")]),
     "mnemonic":"press=压(和 impress 一家);能在人心里压下深刻印记的,就是 impressive 令人赞叹的。",
     "forms":[F("impress","v.","使印象深刻")]}},
  {"word":"moderate","phonetic":"ˈmɒdərət","pos":"adj./v.","def":"适度的，温和的，中等的；缓和","cefr":"B2","freq_rank":76,
   "sentence_en":"He is a man of moderate views.","sentence_zh":"他是个观点温和的人。",
   "aids":{"morphemes":[M("moder","root","适度，限度(modus)"),M("ate","suffix","…的")],
     "derivation":"moder(限度)+ate → 有分寸、不走极端的 → 适度的",
     "family":FAM("mod","方式、限度",[W("mode","方式"),W("modest","谦虚的"),W("modify","修改")]),
     "mnemonic":"moder=限度(和 mode/modest 一家);有分寸、不过头的,就是 moderate 适度的/温和的;moderately 适度地。",
     "forms":[F("moderately","adv.","适度地"),F("moderation","n.","适度")]}},
  {"word":"widespread","phonetic":"ˈwaɪdspred","pos":"adj.","def":"广泛的，普遍的","cefr":"B2","freq_rank":83,
   "sentence_en":"There is widespread support for the plan.","sentence_zh":"该计划得到广泛支持。",
   "aids":{"morphemes":[M("wide","root","宽的"),M("spread","root","展开，散布")],
     "derivation":"wide(宽)+spread(散布) → 大范围铺开的 → 广泛的",
     "family":FAM("spread","展开、散布",[W("spread","传播"),W("bedspread","床罩")]),
     "mnemonic":"wide(宽)+spread(散布)——大面积铺开、到处都是的,就是 widespread 广泛的、普遍的。",
     "forms":[]}},
  {"word":"offensive","phonetic":"əˈfensɪv","pos":"adj./n.","def":"冒犯的，无礼的；进攻的；攻势","cefr":"B2","freq_rank":42,
   "sentence_en":"His remarks were offensive.","sentence_zh":"他的话很无礼。",
   "aids":{"morphemes":[M("of","prefix","朝向，反(ob)"),M("fens","root","打，撞(fend)"),M("ive","suffix","…的")],
     "derivation":"of(反)+fens(打) → 打上门去的 → 冒犯的、进攻的",
     "family":FAM("fend/fens","打、撞",[W("offend","冒犯"),W("defend","防御"),W("defence","防御")]),
     "mnemonic":"fens=打(反义想 defend 防御);朝人打过去、令人不快的,就是 offensive 冒犯的/进攻的;动词 offend;反义 defensive 防御的。",
     "forms":[F("offend","v.","冒犯"),F("offence","n.","冒犯；犯罪")]}},
  # 常见词
  {"word":"medium","phonetic":"ˈmiːdiəm","pos":"n./adj.","def":"媒介，媒体；手段；中等的","cefr":"B1","freq_rank":71,
   "sentence_en":"Television is a powerful medium.","sentence_zh":"电视是一种强大的媒介。",
   "aids":{"morphemes":[M("medi","root","中间"),M("um","suffix","名词后缀")],
     "derivation":"medi(中间)+um → 居中传递的东西 → 媒介;不大不小 → 中等的",
     "family":FAM("medi","中间",[W("middle","中间"),W("media","媒体"),W("immediate","立即的")]),
     "mnemonic":"medi=中间(和 middle 一家);居中传递信息的东西=媒介(复数 media 媒体);大小居中=中号的(medium size)。",
     "forms":[F("media","n.","媒体(复数)")]}},
  {"word":"shore","phonetic":"ʃɔː","pos":"n.","def":"(海/湖)岸，滨","cefr":"B1","freq_rank":72,
   "sentence_en":"We walked along the shore.","sentence_zh":"我们沿着海岸散步。",
   "aids":{"morphemes":[M("shore","root","岸(古英语 scora)")],
     "derivation":"古英语'岸';水域与陆地相接处 → 海岸",
     "family":FAM("shor","岸",[W("seashore","海滨"),W("offshore","近海的")]),
     "mnemonic":"shore=岸;海边/湖边的陆地=shore;on shore 在岸上;offshore 离岸的/海上的;和 coast/beach 一起记。",
     "forms":[F("shores","n.","海岸(复数)")]}},
  {"word":"flame","phonetic":"fleɪm","pos":"n./v.","def":"火焰；热情；燃烧","cefr":"B1","freq_rank":58,
   "sentence_en":"The house was in flames.","sentence_zh":"房子着火了。",
   "aids":{"morphemes":[M("flam","root","火，烧(flamma)"),M("e","suffix","结尾")],
     "derivation":"拉丁 flamma'火焰';燃烧发出的火舌 → 火焰",
     "family":FAM("flam","火、烧",[W("inflammable","易燃的"),W("flammable","易燃的")]),
     "mnemonic":"flam=火(想 flammable 易燃的);跳动的火舌=flame;in flames 燃烧着;比喻'热情之火';flammable 易燃的。",
     "forms":[F("flames","n.","火焰(复数)"),F("flaming","adj.","燃烧的")]}},
  {"word":"cluster","phonetic":"ˈklʌstə","pos":"n./v.","def":"串，簇，群；聚集","cefr":"B2","freq_rank":59,
   "sentence_en":"A cluster of stars.","sentence_zh":"一团星群。",
   "aids":{"morphemes":[M("cluster","root","丛，簇(古英语 clyster)")],
     "derivation":"古英语'一丛';挤在一起的一群 → 簇、群",
     "family":FAM("clust","丛、块",[W("clot","凝块")]),
     "mnemonic":"cluster=一簇/一丛;葡萄一串、星星一团、人扎一堆=a cluster of;聚成一簇=cluster together。",
     "forms":[F("clusters","n.","簇(复数)"),F("clustered","v.","过去式/过去分词")]}},
  {"word":"summit","phonetic":"ˈsʌmɪt","pos":"n.","def":"顶峰，山顶；最高级会议(峰会)","cefr":"B2","freq_rank":68,
   "sentence_en":"They reached the summit at dawn.","sentence_zh":"他们黎明时登顶。",
   "aids":{"morphemes":[M("summ","root","最高，总(summus)"),M("it","suffix","名词后缀")],
     "derivation":"拉丁 summus'最高的';最高点 → 顶峰;最高层的会 → 峰会",
     "family":FAM("summ","最高、总",[W("sum","总和"),W("summary","总结")]),
     "mnemonic":"summ=最高(和 sum 总一家);山的最高点=summit 顶峰;各国领导的最高级会=峰会(G20 summit)。",
     "forms":[F("summits","n.","峰会(复数)")]}},
  {"word":"margin","phonetic":"ˈmɑːdʒɪn","pos":"n.","def":"页边空白；边缘；差额，余地；利润率","cefr":"B2","freq_rank":94,
   "sentence_en":"He won by a narrow margin.","sentence_zh":"他以微弱优势获胜。",
   "aids":{"morphemes":[M("marg","root","边缘(margo)"),M("in","suffix","名词后缀")],
     "derivation":"拉丁 margo'边缘';靠边的空白/差数 → 页边、差额",
     "family":FAM("marg","边缘",[W("marginal","边缘的"),W("margarine","人造黄油")]),
     "mnemonic":"marg=边(想 marginal 边缘的);纸的边白=页边;胜负'差额'=by a margin;利润'空间'=profit margin;marginal 边缘的/微小的。",
     "forms":[F("marginal","adj.","边缘的；微小的")]}},
  {"word":"comedy","phonetic":"ˈkɒmədi","pos":"n.","def":"喜剧；喜剧性","cefr":"B1","freq_rank":62,
   "sentence_en":"She stars in a romantic comedy.","sentence_zh":"她主演一部浪漫喜剧。",
   "aids":{"morphemes":[M("com","root","狂欢，欢宴(komos)"),M("edy","suffix","歌(ode)")],
     "derivation":"希腊 komoidia'欢宴之歌';逗乐的戏 → 喜剧",
     "family":FAM("","相关词",[W("comedian","喜剧演员"),W("comic","滑稽的")]),
     "mnemonic":"源自'欢宴之歌';以逗乐、圆满收场的戏,就是 comedy 喜剧;反义 tragedy 悲剧;comedian 喜剧演员。",
     "forms":[F("comedies","n.","喜剧(复数)"),F("comedian","n.","喜剧演员")]}},
  {"word":"charity","phonetic":"ˈtʃærəti","pos":"n.","def":"慈善(团体)；施舍；仁爱","cefr":"B1","freq_rank":84,
   "sentence_en":"They donated to charity.","sentence_zh":"他们向慈善机构捐款。",
   "aids":{"morphemes":[M("char","root","爱，珍视(carus 亲爱)"),M("ity","suffix","名词后缀")],
     "derivation":"char(爱)+ity → 出于爱心的帮助 → 慈善、仁爱",
     "family":FAM("car/char","爱、珍视",[W("cherish","珍爱"),W("charitable","慈善的")]),
     "mnemonic":"char=爱(想 cherish 珍爱);出于爱心救助他人=charity 慈善;慈善机构;charitable 慈善的。",
     "forms":[F("charities","n.","慈善机构(复数)"),F("charitable","adj.","慈善的")]}},
]

def main():
    data = json.load(open(SEED, encoding="utf-8"))
    existing = {w["word"].lower() for w in data["words"]}
    added, skipped = [], []
    for w in BATCH:
        if w["word"].lower() in existing: skipped.append(w["word"]); continue
        data["words"].append(w); existing.add(w["word"].lower()); added.append(w["word"])
    data["meta"]["generated_batches"] = 20
    json.dump(data, open(SEED, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"追加 {len(added)};跳过 {len(skipped)}: {skipped}; 共 {len(data['words'])}")

if __name__ == "__main__": main()
